### ISSUE TITLE
How to save quokka file on Intellij IDEA?

### ISSUE THREAD

**Issue by ramazanpolat** [wallabyjs/quokka#101]
### Issue description or question

**How to save quokka file on Intellij IDEA?**

When Quokka is not running, on the Quokka panel it says:

"Create a new quokka file (CTRL+Alt+Shift+Insert) or open an existing file..."

Unfortunately since Quokka files are not saved, I can't open them. If I accidentally close the file, everything is gone. CTRL+S doesn't work. 

### Code editor version
IntelliJ IDEA 2017.2.5
### OS name and version
Windows 7 x64

**Comment by ArtemGovorov** [comment]
Quokka can either run on existing files of your project, or create new IntelliJ scratch files.

If you run Quokka on an existing file of your project (with the right click context menu in the opened file editor), then you may just save the file as other files of the project.

If you create a new scratch file, then if you'd like to save it, you may [use the way described here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206834865-Is-there-a-Save-Scratch-File-As-) - hit `F5` to save it anywhere. Later on, you may open the file and run Quokka with the right click context menu in the opened file editor.
