### ISSUE TITLE
[ Feature Request ] Output foldable

### ISSUE THREAD

**Issue by Aetherall** [wallabyjs/quokka#103]
Hi !

I'm a happy owner of the pro version since few days, and in my opinion, THE thing to update is the output window.
It would be awesome if outputs could be foldable, so huge objects could became way more readable

Is it doable?

Thanks !
I'm a VS Code user

**Comment by ArtemGovorov** [comment]
For some reason, folding is disabled in output channels in VS Code (otherwise it'd just work without any changes from our extension). I have raised an issue in VS Code repo about it: https://github.com/Microsoft/vscode/issues/36609.

**Comment by 7immer** [comment]
How about JetBrains IDE's?

**Comment by ArtemGovorov** [comment]
@7immer AFAIK, the output console in JetBrains IDE's doesn't support folding either. Some things may be collapsed by default, but there'll be no `+`/`-` in the gutter to fold/unfold (because the console component is not an editor).

**Comment by Faq** [comment]
Issue for VSCode was closed https://github.com/microsoft/vscode/issues/36609

**Comment by smcenlly** [comment]
Closing this feature request as it is not supported by editors.
