### ISSUE TITLE
vscode: DeprecationWarning: 'root' is deprecated, use 'global'​​

### ISSUE THREAD

**Issue by PixelT** [wallabyjs/quokka#105]
![](https://i.imgur.com/elr9iq8.png)

**Comment by ArtemGovorov** [comment]
Are you using any Quokka plugins in your quokka config?

**Comment by PixelT** [comment]
yes, I install jsdom-quokka-plugin and put in my `package.json` file:
```
    "quokka": {
        "plugins": ["jsdom-quokka-plugin"]
    }
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. The issue was in the `jsdom-quokka-plugin`. We have fixed the issue there, please update the module to v1.0.7.
