### ISSUE TITLE
importHelpers in tsconfig.json

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/quokka#106]
### Issue description or question
If `tsconfig.json` have config around helper functions, 
```
   "importHelpers": true,
    "noEmitHelpers": true,
```
it seems `noEmitHelpers` are honored but `importHelpers` are not, so some of downlevel transpiled helper is not being referenced. Not sure if this specific configuration related or default behavior.

### Sample code

```javascript
//import 'tslib' //if explicitly imports, below works
const a = () => Promise.resolve('a');
(async() => console.log(await a()))();
```

tsconfif
```
{
  "compilerOptions": {
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "allowJs": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noImplicitThis": true,
    "noUnusedParameters": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es2016",
    "jsx": "react",
    "outDir": ".tmp/build",
    "lib": [
      "es2016",
      "dom"
    ],
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "include": [
    "src/**/*",
    "build/**/*",
    "spec/**/*"
  ],
}
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​__awaiter is not defined​​
  at ​​​__dirname​​​ ​quokka.ts:2:12​
  at ​quokka.ts:2:12​

```

### Code editor version

[x] Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

[x] Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
I didn't have a chance to fully investigate why it's happening, but the issue doesn't see to be Quokka specific. If I run `tsc` with your `tsconfig` file on your source file, I'm getting this output:

```javascript
const a = () => Promise.resolve('a');
(() => __awaiter(this, void 0, void 0, function* () { return console.log(yield a()); }))();
//# sourceMappingURL=test.js.map
```

**Comment by ArtemGovorov** [comment]
Have done some investigation - [this is by design in TypeScript](https://github.com/Microsoft/TypeScript/issues/12167):

`If the file does not have a toplevel import/export is it is not considered a module, and it is treated as script/global.`

So TypeScript expects these globals for the file because the file does not look like a module to it.

If you import/export into/from the file, it'll start working as expected:

```javascript
import 'path';
const a = () => Promise.resolve('a');
(async() => console.log(await a()))();
```

or 

```javascript
const a = () => Promise.resolve('a');
(async() => console.log(await a()))();
export {};
```

**Comment by davvit** [comment]
@ArtemGovorov seems like what you found out does not help.  I still get the error.

I am testing out async methods and when i call my long1() method i get the same error.

`async function long1(): Promise<any> {
    return await new Promise((resolve) => {
        setTimeout(resolve, 500);
        console.log('long1 done');
        return 1
    });
}`
![image](https://user-images.githubusercontent.com/4433698/32572329-d0573ccc-c48f-11e7-8c8b-d57c791c2fab.png)

**Comment by ArtemGovorov** [comment]
@davvit Could you please 
- share your `tsconfig.json` file,
- on a simple file like this:
```
import 'path';
const a = () => Promise.resolve('a');
(async() => console.log(await a()))();
```
run Quokka, and then run `Quokka.js: Show Instrumented Code` command and paste the output from the Quokka console?
