### ISSUE TITLE
[ Feature Request ] Special comments everywhere

### ISSUE THREAD

**Issue by Aetherall** [wallabyjs/quokka#109]
Is it doable tu allow the special comments to be displayed on every imported file ?

currently :
````javascript
// index.js => file on which quokka is running
import 'file.js'

// file.js
'expression'//?
````

expected :
````javascript
// index.js => file on which quokka is running
import 'file.js'

// file.js
'expression'//? expression
````

**Comment by ArtemGovorov** [comment]
Quokka operates on a file level, so this feature request is out-of-scope for the project. 

Having said that, the feature is fully supported in our other product called [Wallaby.js](https://wallabyjs.com/). It is a test runner (that operates on a project level) and it displays live execution results (and code coverage) for all tests and covered code files in a project.
