### ISSUE TITLE
Not working in atom  Mac

### ISSUE THREAD

**Issue by radjivC** [wallabyjs/quokka#112]
### Sample code

not working on the start

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

no console output

### Code editor version

1.19.5

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Just tried and Quokka is working for me without any issues on OSX in Atom.

Could you please specify how exactly Quokka is "not working on the start"? Does your command palette display Quokka commands?

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.

**Comment by radjivC** [comment]
I have installed it and just it as no quokka palette and no error message

**Comment by ArtemGovorov** [comment]
Could you please try opening the editor Dev Tools to see if there's anything printed in the Console?
