### ISSUE TITLE
Conflict with PlatformIO IDE plugin, make pio ide plugin corrupt.

### ISSUE THREAD

**Issue by picospuch** [wallabyjs/quokka#113]
### Issue description or question

conflict with PlatformIO IDE plugin, make pio ide plugin corrupt.

pio ide:
https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide

### Code editor version

Visual Studio Code v1.18.0

### OS name and version
OSX

**Comment by picospuch** [comment]
![image](https://user-images.githubusercontent.com/2293057/32647612-12ddc9e6-c62d-11e7-8615-1d140498fb17.png)

likely break all 'require()' call with 'receiver' in names of node modules.

**Comment by ArtemGovorov** [comment]
Thanks for the report. We'll publish the fix soon.

**Comment by ArtemGovorov** [comment]
The issue is fixed and the fix is published in Quokka v1.0.79.
