### ISSUE TITLE
Quokka stopped working on existing files

### ISSUE THREAD

**Issue by wildpow** [wallabyjs/quokka#115]
### When I start a new JS file with Quokka everything works fine but when I save that file I get this console output.

```
Error: ENOENT: no such file or directory, open '../Desktop/Untitled-s.js'​​
​​    at Object.fs.openSync (fs.js:646:18)​​
​​    at Object.fs.writeFileSync (fs.js:1291:33)​​
​​    at emitOne (events.js:116:13)​​
​​    at WebSocketServer.emit (events.js:211:7)​​
​​    at emitThree (events.js:136:13)​​
​​    at Server.emit (events.js:217:7)​​
​​    at onParserExecuteCommon (_http_server.js:495:14)​​
​​    at onParserExecute (_http_server.js:450:3)​​
```

Visual Studio Code v1.18
Node 8.9.1
Quokka.js 1.0.79

### OS name and version
OSX 10.13.1

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue, here's what I'm doing: 
- create a new Quokka file and then save it,
- Quokka stops (it is expected). 

If you describe the steps how to reproduce the issue, I'm happy to have a look.

Anyway, try re-launching Quokka on the saved file (`Cmd + K, Q`), it should work for you.

**Comment by ArtemGovorov** [comment]
@mypark Could you please describe the steps to reproduce the issue?

Here's what I've tried doing:
- open a new VS Code instance without any folders opened,
- create new file - Quokka is working on it,
- save the file and restart Quokka on it - Quokka is working on it.

![quokka](https://user-images.githubusercontent.com/979966/36815886-dfbc833e-1d27-11e8-8d23-ac40a258a058.gif)


Here's another scenario that is also working for me:
- open a new VS Code instance without any folders opened,
- open an existing file,
- run Quokka on it, save it - everything is working.


![quokka](https://user-images.githubusercontent.com/979966/36815606-f9863bf8-1d26-11e8-9d94-69e8a8e990ab.gif)

**Comment by mcshaman** [comment]
Had same issue. Was saving the file outside current workspace just to run some minor tests. Looks like it can only function correctly if the file is in the project workspace. Maybe a nice little error message to advise may help others with the same issue.

**Comment by arunkumar201** [comment]
just write js 
inside the  here
![image](https://user-images.githubusercontent.com/70876302/177149081-a5478c72-fbe7-431b-b599-df953250d8f8.png)
it is works perfectly
