### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bsvipas** [wallabyjs/quokka#123]
I just want to say thank you. This extension for VS Code really improved my work, I can easily develop new features in Quokka to get real-time outputs and then I can easily move them to my project.

I really appreciate your work guys! 👍 🥇

**Comment by ArtemGovorov** [comment]
Thank you for your feedback and your kind words!

>  I can easily develop new features in Quokka to get real-time outputs and then I can easily move them to my project.

You may also be interested to check out our other tool [called Wallaby.js](https://wallabyjs.com/), that allows to continuously run tests (to make sure that you app features still work when you refactor/change them).
