### ISSUE TITLE
Creating new JS File in latest version of VS code

### ISSUE THREAD

**Issue by gkoscevic** [wallabyjs/quokka#124]
### Issue description or question
I'm displayed the following error when trying to create a new JS file using Quokka.

![screen shot 2017-11-28 at 3 05 17 pm](https://user-images.githubusercontent.com/12465728/33341648-92ee4c2c-d44d-11e7-9845-b38f9afb3358.png)

### Code editor version
Visual Studio Code v1.18.0

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Just checked and everything is working on OSX in VS Code 1.18.

Please try re-installing the extension. If it doesn't help, please open VS Code Dev Tools (`Help - Toggle Developer Tools`), open the Console tab and paste the output from there.

**Comment by gkoscevic** [comment]
re-installing the extension worked. thank you!
