### ISSUE TITLE
napajs not working

### ISSUE THREAD

**Issue by darky** [wallabyjs/quokka#126]
### Sample code

```javascript
var napa = require("napajs");
var zone1 = napa.zone.create("zone1", { workers: 4 });

zone1.execute(text => text, ["hello napa"]).then(result => {
  console.log(result.value);
});
```

### Quokka.js Console Output

```
​​ReferenceError: $_$wf is not defined​​
```

### Code editor version

Visual Studio Code v1.18.1

### OS name and version

Linux Arch

**Comment by ArtemGovorov** [comment]
Quokka (in a similar as Wallaby) instruments source code to collect code coverage (and display the gutter indicators). When The code is executed by Quokka, the tools is able to correctly handle instrumentation instructions. However `napajs` executes code in a separate process/context, so code instrumentation instructions are not defined there.

To handle cases like this Wallaby supports instrumentation suppression comments, so that code blocks that are not desired to be instrumented for any reason [are marked with the comment like `/* ignore coverage */`](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file).

Up until now, Quokka didn't support anything like that, but we have just added the same mechanism in the latest version 1.0.82, so now you can do mark code blocks executed in a different process with a comment an suppress code instrumentation for them:

```javascript
var napa = require("napajs");
var zone1 = napa.zone.create("zone1", { workers: 4 });

zone1.execute(/* ignore coverage */text => text, ["hello napa"]).then(result => {
  console.log(result.value);
});
```

This comment will tell Quokka that it doesn't need to instrument the `text => text` function (that'll be executed in a different context).

**Comment by darky** [comment]
:+1: This works now!
( Maybe better to use something brief like `/* ic */`)

But when I resave file, other error occured:

![image](https://user-images.githubusercontent.com/1832800/33525102-ad5e4f5e-d839-11e7-9822-14f5c62a4a05.png)

Need to restart quokka on file again

**Comment by ArtemGovorov** [comment]
> But when I resave file, other error occured:

Hmm, I can't reproduce the issue. If I start Quokka on an existing project file with the content above (and `napajs` installed in the project), then everything  is working for me, what am I missing? Could you please describe the steps to reproduce the issue?

**Comment by darky** [comment]
Simply press *Ctrl + S* after some stub changes (like add space).
* node: 9.2.0
* napajs: 0.1.7

Output:

```
​​Module did not self-register.​​
  at ​​​Object.Module._extensions..node​​​ ​module.js:670​
  at ​​​Module.load​​​ ​module.js:560​
  at ​​​tryModuleLoad​​​ ​module.js:503​
  at ​​​Function.Module._load​​​ ​module.js:495​
  at ​​​Module.require​​​ ​module.js:585​
  at ​​​require​​​ ​internal/module.js:11​
  at ​​​Object.<anonymous>​​​ ​./node_modules/napajs/lib/binding.js:22​
  at ​​​Module._compile​​​ ​module.js:641​
  at ​​​Object.Module._extensions..js​​​ ​module.js:652​
  at ​​​Module.load​​​ ​module.js:560​
  at ​​​tryModuleLoad​​​ ​module.js:503​
  at ​​​Function.Module._load​​​ ​module.js:495​
  at ​​​Module.require​​​ ​module.js:585​
  at ​​​require​​​ ​internal/module.js:11​
  at ​​​Object.<anonymous>​​​ ​./node_modules/napajs/lib/log.js:5​
  at ​​​Module._compile​​​ ​module.js:641​
  at ​​​Object.Module._extensions..js​​​ ​module.js:652​
  at ​​​Module.load​​​ ​module.js:560​
  at ​​​tryModuleLoad​​​ ​module.js:503​
  at ​​​Function.Module._load​​​ ​module.js:495​
  at ​​​Module.require​​​ ​module.js:585​
  at ​​​require​​​ ​internal/module.js:11​
  at ​​​Object.<anonymous>​​​ ​./node_modules/napajs/lib/index.js:5​
  at ​​​Module._compile​​​ ​module.js:641​
  at ​​​Object.Module._extensions..js​​​ ​module.js:652​
  at ​​​Module.load​​​ ​module.js:560​
  at ​​​tryModuleLoad​​​ ​module.js:503​
  at ​​​Function.Module._load​​​ ​module.js:495​
  at ​index.js:1:0​
```

Also maybe it OS specific problem

**Comment by ArtemGovorov** [comment]
From the message it looks like it may node process reuse specific issue.

Adding the `recycle` setting to [your Quokka file (or to your `package.json` `"quokka: { "recycle": true }"`)](https://quokkajs.com/docs/configuration.html) should help:

```javascript
({
    recycle: true //<--
}) 

var napa = require("napajs");
var zone1 = napa.zone.create("zone1", { workers: 4 });
 
zone1.execute(/* ignore coverage */text => text, ["hello napa"]).then(result => {
  console.log(result.value);
});
```

**Comment by darky** [comment]
:+1:

**Comment by loganpowell** [comment]
I'm trying to use quokka with puppeteer and would like to leverage [the same ignore functionality](), but it doesn't seem to work for me. Here's my local quokka config:

```json
{
    "babel": false,
    "env": {
        "params": {
            "env": "NODE_PATH=./src"
        }
    },
    "plugins": [
        "jsdom-quokka-plugin"
    ],
    "recycle": true,
    "hints": {
        "ignoreCoverage": "/ignore coverage/"
    }
}
```
and my code block:

```js
    /* ignore coverage */
    const topics = await page.$$eval("[node_name='TaxonomyListTree']", (ts) =>
        ts.map((t) => {
            t.click()
            return t
        })
    )
```

When it hits this, I get this in the quokka output panel (vsCode):

```sh
catch Error: Evaluation failed: ReferenceError: $_$wf is not defined 
    at __puppeteer_evaluation_script__:2:24 
```

**Comment by smcenlly** [comment]
@loganpowell - thanks for letting us know that this wasn't working for you. Quokka's ignore coverage setting had been recently broken but is now fixed.

Please update to the latest version of Quokka for your editor, it should work for you.

**Comment by loganpowell** [comment]
Thank you @smcenlly! I can confirm that with the latest update it's working 🙏
