### ISSUE TITLE
Quokka not working with postgres

### ISSUE THREAD

**Issue by darky** [wallabyjs/quokka#128]
### Issue description or question
Quokka not show log highlights and time measure

![image](https://user-images.githubusercontent.com/1832800/33673793-daa5fec6-dabe-11e7-978f-e96c3b25f9d6.png)

### Sample code

Need `npm install pg knex` and simple postgres installed

```javascript
(async () => {
  const knex = require("knex")({
    client: "pg",
    connection: {
      host: "localhost",
      user: "postgres",
      database: "postgres"
    }
  });

  await knex("users")
    .select()
    .where({ name: "Mouse" }); //?
})();
```

### Quokka.js Console Output

Quokka show logs in output, but not show time measure

### Code editor version

Visual Studio Code v1.18.1

### OS name and version

Linux Arch

**Comment by ArtemGovorov** [comment]
`//?`

The correct comment for displaying execution time is `//?.`

> Quokka show logs in output,

This means that Quokka is working as expected. Some results, including the execution time, can [only be displayed when your program exits](https://github.com/wallabyjs/quokka/issues/129#issuecomment-349822532).

Looks like `knex` keeps your node program running and it doesn't exit. You may easily try it with a plain node by running:
```
node your_script.js
```
and observe it not finishing.

Looks like `knex` has the `destroy` function, so to get the results you are expecting, you may do this:

```diff
(async () => {
    const knex = require("knex")({
      client: "pg",
      connection: {
        host: "localhost",
        user: "artemgovorov",
        database: "artemgovorov"
      }
    });
  
    await knex("users")
      .select()
      .where({ name: "Mouse" }); //?.

+     knex.destroy();
  })();
```
