### ISSUE TITLE
Quokka doesn't show data in the editor.

### ISSUE THREAD

**Issue by zaker102** [wallabyjs/quokka#129]
### Issue description or question
Quokka doesn't show data in the editor.

![image](https://user-images.githubusercontent.com/24941405/33686817-607fd10e-dad6-11e7-944d-701f74e55731.png)
### Sample code

```javascript
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

/* Middleware */
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

const server = app.listen(80, () => {
    console.log(`Server started and running on port ${server.address().port}`);
});
```
### Quokka.js Console Output
Quokka show logs in output, but not show data in editor.

### Code editor version
WebStorm 2017.2
Build #WS-172.3317.70

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
This is by design. Quokka displays data in editor only when your program finishes executing. In your case the program doesn't exit because the web server keeps running. If you add some code that stops the server at some point, for example:

```javascript
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

/* Middleware */
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

const server = app.listen(0, () => {
    console.log(`Server started and running on port ${server.address().port}`);
    server.close(); // <--
});
```

then it'll show you the results in the editor.

**Comment by ArtemGovorov** [comment]
@Guardiannw We are planning to add the feature in future. At the moment Quokka shows logs in output panel for infinitely running apps, but not in the editor.
