### ISSUE TITLE
Does not print properties from prototype

### ISSUE THREAD

**Issue by zhengbli** [wallabyjs/quokka#13]
### Issue description or question
Properties from prototype are not printed

### Quokka.js file

```javascript
var t = { age: 10 }
var t2 = Object.create(t);
t2     // correct output
t2.age // no output
```

### Quokka.js Console Output

```
​​​​Quokka #2 (node: v7.5.0, TypeScript: 2.2.1)​​​​

​​​​​{}​​​​​ at ​​​t2​​​ ​quokka.js:3:0​
```

### Code editor version

Visual Studio Code v1.11

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
This is by design. For now quokka only automatically logs identifier expressions, ie:
```
someVar
```
For other cases you may use `console.log(anyKindOfExpression);`

So this wil work:

```javascript
var t = { age: 10 }
var t2 = Object.create(t);
t2     // correct output
console.log(t2.age) // correct output
```
or this

```javascript
var t = { age: 10 }
var t2 = Object.create(t);
t2     // correct output
var age = t2.age;
age  // correct output
```
