### ISSUE TITLE
Error `at TCP.onread`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/quokka#130]
### Issue description or question

When running Quokka for the first time I see this message whenever I make a change. After it displays, nothing updates anymore.

Is there a way to see logs of what Quokka is doing?

### Quokka.js Console Output

```
Quokka #1 (node: v8.9.0, babel: v6.26.0)

    at TCP.onread (net.js:594:20)
```

### Code editor version

Visual Studio Code v1.?
**Webstorm** v?
Atom v1.?

### OS name and version

Windows
**OSX**
Linux

**Comment by vjpr** [comment]
I deleted my `~/.quokka` dir and it started working again.

Is there any caching happening with quokka that could have caused this? Maybe a button to clear the cache would be useful.

**Comment by vjpr** [comment]
Okay error came back.

Started occurring after I imported file containing this:

```
import mqtt from 'mqtt'
import Debug from 'debug'
import type {Blah} from '../types'
```

Since the error came back, I tried these things:

- restarting quokka with new scratch file
- deleting `~/.quokka/data`

Both didn't work.

**Comment by vjpr** [comment]
So turns out that my root `.babelrc` used `stage-0` syntax and was requiring `babel-register`.

I had some complicated logic in there to workaround some `next.js` issues...but I guess its really asking for trouble to use `babel-register` in a `babel-preset` definition.

This worked fine, but ended up breaking with Quokka in strange ways.

Maybe you have an idea of why this breaks Quokka in this way? And maybe there is a way to alert the user of it, given that if someone uses `babel-register` in a plugin...things might break.

**Comment by ArtemGovorov** [comment]
If the issue is indeed caused by `babel-register`, we should definitely do something about it, at the very least find out why the error message is not meaningful at all.

> So turns out that my root `.babelrc` used `stage-0` syntax (imports/exports) and was requiring `babel-register`.
> I had some complicated logic in there to workaround some `next.js` issues

I'm not sure how to start reproducing the issue, `stage-0` preset by itself doesn't use `babel-register`. Could you please share some more details on how exactly `babel-register` is used in your `.babelrc`?

**Comment by smcenlly** [comment]
Closing this issue due to age and inactivity.
