### ISSUE TITLE
Can't use multiple env variables

### ISSUE THREAD

**Issue by darky** [wallabyjs/quokka#132]
### Sample code

```json
{
  "env": {
    "params": {
      "env": "NODE_ENV=developement NODE_PATH=/home/user/projects/test"
    }
  }
}
```

### Quokka.js Output

Quokka parse `NODE_ENV` value as `"developement NODE_PATH=/home/user/projects/test"`

### Code editor version

Visual Studio Code v1.18.1

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
`env.params.env` are expected to be `;` separated:

```
{
  "env": {
    "params": {
      "env": "NODE_ENV=developement;NODE_PATH=/home/user/projects/test"
    }
  }
}
```

I have changes the docs to mention it.
