### ISSUE TITLE
Quokka not working in Webstorm

### ISSUE THREAD

**Issue by rikster** [wallabyjs/quokka#133]
### Issue description or question
Quokka is not working in Webstorm?

### Quokka.js Console Output
runnerw.exe: CreateProcess failed with error 193 (no message available) 

### Code editor version
Webstorm 2017.3.1 

### OS name and version
Windows 10
Node 8.9.3 

![image](https://user-images.githubusercontent.com/3039870/34019337-76cc8454-e182-11e7-81de-df5a85077e79.png)

**Comment by ArtemGovorov** [comment]
Try specifying a full path to your `node.exe` in your [Quokka config file `node` setting](https://quokkajs.com/docs/configuration.html#nodejs-version).

```
{
    "node": "C:\\Users\\...path to your node...\\node.exe"
}
```

**Comment by rikster** [comment]
Thanks, that did the trick.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
