### ISSUE TITLE
Use `inspect` method for output if available on object

### ISSUE THREAD

**Issue by avanslaars** [wallabyjs/quokka#134]
### Issue description or question

`console.log` will output the result of calling `inspect` when present on an object, that is not the case with Wallaby/Quokka output.

It would be nice to have this as an option or default behavior for `console.log` statements.

### Sample code

```javascript
const maybeNumber = getMaybe(5)
// Inline output for the following log:
// ... [λ: alt], zero: [λ], ap: [λ: ap], of: [λ], chain: [λ: chain], sequence: [λ: sequence], traverse: [λ: traverse] }
console.log(maybeNumber) // result of `inspect` "Just 5"

```

**Comment by ArtemGovorov** [comment]
Thanks for submitting the feature request. `inspect` support has been added and published in the latest version.
