### ISSUE TITLE
Font used in follows gif from your package

### ISSUE THREAD

**Issue by richellyitalo** [wallabyjs/quokka#135]
Please, whats the font family used in image follows

https://user-images.githubusercontent.com/979966/28608415-a14cf732-7223-11e7-898a-c7c9b5ba1424.gif

**Comment by ArtemGovorov** [comment]
The GIF is recorded in VS Code standard Dark+ theme. The font family used in the theme is `font-family: Menlo, Monaco, "Courier New", monospace;`.

**Comment by richellyitalo** [comment]
Thanks!
