### ISSUE TITLE
Live Comment is not working

### ISSUE THREAD

**Issue by unional** [wallabyjs/quokka#138]
### Issue description or question
Seems like the current version is not working for both TS and JS.

### Sample code

```javascript
function getRelativePath(from, to) {
  return 'aabce'
}

const y = getRelativePath('', '')
y/*?*/.indexOf('b') // nothing shown
y  // shows aabce
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.6.0)​​​​

​​​​​aabce​​​​​ at ​​​y​​​ ​quokka.js:7:0​
```

### Code editor version

Visual Studio Code v1.19.1

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment]
Just checked and everything is working as expected for both TypeScript and JavaScript:

<img width="412" alt="screen shot 2017-12-28 at 6 12 25 pm" src="https://user-images.githubusercontent.com/979966/34404674-c0066a22-ebfa-11e7-9dad-ba6612653e4c.png">

Please note that Live Comments is a [`Pro` edition](https://quokkajs.com/pro/) feature, while you are probably using `Community` edition. To try the feature (as well as other `Pro` edition features), you may use `Quokka.js: Switch to Pro Edition` command with `Cmd + Shift + P`.
