### ISSUE TITLE
document not definded while using a module pattern in js

### ISSUE THREAD

**Issue by nestoralonsovina** [wallabyjs/quokka#140]
### Issue description or question
Quokka throws an error while using the module pattern in js, the code works as expected without  any problems.
### Sample code

```javascript
// STANDARD MODULE PATTERN
const UICtrl = (() => {
    let text = 'Hello World';
    const changeText = () => {
        const element = document.querySelector('h1');
        element.textContent = text;
    }

    return {
        callChangeText: () => {
            changeText();
            console.log(text);
        }
    }
})();

UICtrl.callChangeText();
```

### Quokka.js Console Output

```
​​document is not defined​​
  at ​​​changeText​​​ ​patterns.js:17:8​
  at ​​​Object.callChangeText​​​ ​patterns.js:23:12​
  at ​patterns.js:29:0​
```

### Code editor version

Visual Studio Code v1.19.1?

### OS name and version

OSX High Sierra 10.13.2

**Comment by ArtemGovorov** [comment]
Quokka runs in node, so as [mentioned here](https://github.com/wallabyjs/quokka/issues/9), to use browser code you may use one of [Quokka plugins](https://quokkajs.com/docs/configuration.html#plugins), specifically [jsdom-quokka-plugin](https://github.com/wallabyjs/jsdom-quokka-plugin).
