### ISSUE TITLE
Error on object spread

### ISSUE THREAD

**Issue by LawJolla** [wallabyjs/quokka#144]
### Issue description or question

Quokka v 1.0.90
Errors out on object spread.  I'm not sure what could be causing this since Node deals with it properly.  This happens in both VS Code and PHPStorm

### Sample code

![untitled](https://user-images.githubusercontent.com/17485128/34631121-2fb2697a-f22c-11e7-83df-128045e425ec.jpeg)

### Quokka.js Console Output

![untitled](https://user-images.githubusercontent.com/17485128/34631068-f41234ae-f22b-11e7-8c32-b67da3955364.jpeg)

### Code editor version

Visual Studio Code v1.19.1
PHPStorm v2017.3.2

### OS name and version

OSX 10.13.1

**Comment by ArtemGovorov** [comment]
It looks like the error is coming not from `node` but from `babel`. You must have the `babel` setting used in your quokka config (global or package.json). Try removing it and rerun Quokka. 

Also, looks like babel is pointing to a character before `...`, perhaps you have some invisible character there? For example this code works for me with the same babel and node versions:

```javascript
const x = {x: 42}
const y = { ...x}
y
```
<img width="324" alt="screen shot 2018-01-06 at 10 37 49 am" src="https://user-images.githubusercontent.com/979966/34634226-ab273f3a-f2cd-11e7-9faa-26d1b25918fa.png">

**Comment by LawJolla** [comment]
Really odd.  Thank you for the quick follow up.  I didn't think that babel could be the problem, but somehow it is.  ({ babel: false }) fixed the problem.

Thanks for your hard work and great plug in!
