### ISSUE TITLE
Quokka does not recognise console.log if method log is saved into dedicated variable

### ISSUE THREAD

**Issue by fedulovivan** [wallabyjs/quokka#148]
Hello, tried with vs code version.

Noticed that quokka does not recognise call of **console.log** if method **log** is saved into dedicated variable.

Given code snippet:
```javascript
const { log } = console;
log(1);
```
Expected that such expression should also be recognised by engine, and **1** value will be shown.

**Comment by ArtemGovorov** [comment]
Yep, Quokka finds and instruments `console.log` code snippets specifically and it's almost impossible to make it work for all cases when the `log` method is extracted and used differently. While we could hard code something in our AST traversal just for this case, there are lots of other cases that would still be missed.

Having said that, with your code it should still log values to the Quokka console (just won't be displaying them inline). You may also consider using [Live Comments Quokka Pro version feature]( https://quokkajs.com/pro/#live-comments), where `console.log` use is not even required to log various values.
