### ISSUE TITLE
Create a VSIXPackage for install offline in Visual Studio Code?

### ISSUE THREAD

**Issue by m2web** [wallabyjs/quokka#15]
### Code editor version

Visual Studio Code v1.10.2

### OS name and version
Ubuntu 16.04

**Comment by ppasieka** [comment]
Q: Can I download an extension directly from the Marketplace?
https://code.visualstudio.com/docs/extensions/debugging-extensions#_common-questions

Download link:
http://WallabyJs.gallery.vsassets.io/_apis/public/gallery/publisher/WallabyJs/extension/quokka-vscode/1.0.32/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
