### ISSUE TITLE
Cannot get it working with WSL

### ISSUE THREAD

**Issue by CoLdAs1cE** [wallabyjs/quokka#152]
### Issue description or question
Trying to get it to work where i have node on my wsl

### Quokka.js Console Output

```
​​module.js:557​​
​​    throw err;​​
​​    ^​​
​​​​
​​Error: Cannot find module '/mnt/f/test/C:\Users\CoLd As IcE\.vscode\extensions\WallabyJs.quokka-vscode-1.0.94\dist\wallaby\server.js'​​
​​    at Function.Module._resolveFilename (module.js:555:15)​​
​​    at Function.Module._load (module.js:482:25)​​
​​    at Function.Module.runMain (module.js:701:10)​​
​​    at startup (bootstrap_node.js:193:16)​​
​​    at bootstrap_node.js:617:3​​
​​​​
```

### Code editor version

Visual Studio Code v1.19.3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
At the moment Quokka needs local node instance to run your code. You [may change used node path to any locally installed node instance](https://quokkajs.com/docs/configuration.html#nodejs-version).

**Comment by CoLdAs1cE** [comment]
does that mean i cannot run in in wsl ?

**Comment by ArtemGovorov** [comment]
Sorry, I'm not familiar with the abbreviation, what is wsl?

**Comment by CoLdAs1cE** [comment]
windows linux subsystem

**Comment by CoLdAs1cE** [comment]
makes it have my developer tools instead of installing it all in windows, i get it in console

**Comment by ArtemGovorov** [comment]
In case of Quokka, VS Code and node has to be on the same system. If you can install VS Code in wsl, then it may work (but I haven't tried it).

**Comment by CoLdAs1cE** [comment]
i did a bat and i have this loading [---=---], but i don't know much about wsl so i don't know if it is local instance as you said previously

**Comment by ArtemGovorov** [comment]
I think the easiest way would be to install node on your main Windows system. I expect you may need it not only for Quokka but for a few other tools as well.

**Comment by CoLdAs1cE** [comment]
VSCode is quite nice as its uses WSL with a simple command

so far no problem, but yeah i suspect that as well

**Comment by DamianRivas** [comment]
@ArtemGovorov I'm not familiar with developing extensions for VS Code, but if your extention has a launch.json file then perhaps you can give users the option to use Quokka with WSL by altering the launch.json as shown here: https://blogs.msdn.microsoft.com/commandline/2017/10/27/running-node-js-on-wsl-from-visual-studio-code/

**Comment by ArtemGovorov** [comment]
@DamianRivas Quokka doesn't use/have `launch.json`, it just uses a specified path to node executable and runs it.

**Comment by DamianRivas** [comment]
Got it. From my understanding, WSL is just a Windows driver for running linux applications in the command line. So technically Node and Quokka _are_ in the same system and I think there should be a way to get them working. I'll come back if I find a way to point Quokka to linux's filepath for node.

**Comment by DamianRivas** [comment]
In the Quokka docs:

> By default quokka runs the `node` command to run your code.

So in a future version of Quokka maybe you can implement a configuration that instead of doing a solitary `node` command, it pipes all commands by running `wsl node`
