### ISSUE TITLE
Reason or cljs support

### ISSUE THREAD

**Issue by texastoland** [wallabyjs/quokka#153]
### Issue description or question

One of my all-time favorite tools 🙌🏽 Reminds me of Swift Playgrounds without visualizations. Just a quandary if additional language support is on the roadmap? I imagine every language community community would love to contribute integration if the architecture were to support it.

### Sample code
<caption>Typescript</caption>

```ts
const fib = (n: number): number =>
  n == 0 || n == 1
    ? n
    : fib(n - 1) + fib(n -2)

console.log(fib(10))
```
<caption>Reason</caption>

```reason
let rec fib = (n) => {
  n == 0 || n == 1
    ? n
    : fib(n - 1) + fib(n -2)
};

Js.log(fib(10));
```
<caption>ClojureScript</caption>

```cljs
(defn fib [n]
  (if
    (or (= n 0) (= n 1))
    n
    (+ (fib (- n 1)) (fib (- n 2)))))

(.log js/console (fib 10))
```

**Comment by ArtemGovorov** [comment]
Thanks! The feature is [on the roadmap](https://github.com/wallabyjs/quokka/issues/121).

**Comment by texastoland** [comment]
No idea why I couldn't find that thanks!

**Comment by texastoland** [comment]
It's been over a year. Could I work on this? I'd be willing to sign anything or provide professional references!

**Comment by smcenlly** [comment]
Thanks for your offer of working on this with us. Please contact us at hello@wallabyjs.com to discuss further.

You will need to start by creating a compiler for our other product, wallaby.js. https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler

Once you get the compiler working in wallaby, you can hand that over to us and we will integrate it with our existing code base and apply the necessary changes to Quokka. There's a bit of work on our side in our editor plugins to support new languages so we'll need to do that too.

If you don't already have a license to wallaby, let us know when you email us and we'll give you one to support working on this.

**Comment by texastoland** [comment]
I'll get in touch today! Thank you so much @smcenlly 🙌

**Comment by seanpoulter** [comment]
Which language(s) were you looking at @texastoland? I'm interested in IDE integration for ClojureScript test coverage and I think this might be the easiest way to land it in VS Code and IntelliJ. 🤞

**Comment by texastoland** [comment]
I'm interested in Reason support but it's still blocked by no source maps in BuckleScript/bucklescript#1699 🤞🏽
