### ISSUE TITLE
Cannot find module /.../vscode/extenstions/WallabyJS.quokka...

### ISSUE THREAD

**Issue by valentinpalkovic** [wallabyjs/quokka#154]
### Issue description or question
After installing quokka for vscode and choosing *Quokka.js: Start on current file* the console outputs an error (see below). The command is used on a typescript file. Creating a new javascript file with the quokka command fails as well. Trying to open the file manually throw the terminal works without problems.

### Quokka.js Console Output

```
Quokka #1​​​​
​​module.js:557​​
​​    throw err;​​
​​    ^​​
​​​​
​​Error: Cannot find module '/Users/xxxxx/.vscode/extensions/WallabyJs.quokka-vscode-1.0.96/dist/wallaby/server.js'​​
​​    at Function.Module._resolveFilename (module.js:555:15)​​
​​    at Function.Module._load (module.js:482:25)​​
​​    at Function.Module.runMain (module.js:701:10)​​
​​    at startup (bootstrap_node.js:194:16)​​
​​    at bootstrap_node.js:618:3​​
```

### Code editor version

Visual Studio Code v1.19.2

### OS name and version
OSX 10.13.3

**Comment by ArtemGovorov** [comment]
Looks like your Quokka installation is corrupted. Try re-installing the extension. 

If it throws the same error after the re-installation, please archive and attach the `/Users/xxxxx/.vscode/extensions/WallabyJs.quokka-vscode-1.0.96/` folder.
