### ISSUE TITLE
Strange v8 error

### ISSUE THREAD

**Issue by DanielRamosAcosta** [wallabyjs/quokka#157]
### Issue description or question

When I create a "New Javascript File" I get a red error message:

```
​​v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/home/daniel/.config/fnm/bin/node]​​
​​ 7: 0x351c9528463d​​
```

I'm using [fnm](https://github.com/fisherman/fnm) to change the Node version, I dont now if it's interfearing someway.

### Code editor version

Visual Studio Code v1.20

### OS name and version

Ubuntu 17.10

**Comment by ArtemGovorov** [comment]
> I'm using fnm to change the Node version, I dont now if it's interfearing someway.

It may be. Try [downloading node 9.5](https://nodejs.org/en/download/current/) manually and [setting the path in your Quokka config](https://quokkajs.com/docs/configuration.html#nodejs-version) to see it ti works.

**Comment by ArtemGovorov** [comment]
Just tried to install node 9.5 on Ubuntu 17.10 and everything seems to work ok for me:

<img width="1101" alt="screen shot 2018-02-09 at 7 10 14 pm" src="https://user-images.githubusercontent.com/979966/36020074-1e472eb6-0dcd-11e8-8b97-b7d6a479c5f7.png">

Try downloading/installing node w/o `fnm`, it should work.

**Comment by DanielRamosAcosta** [comment]
I have downloaded Node 8.9.4 and 9.5.0 manually, and I have setted the "node" attribute in `~/.quokka/config.json` and I'm getting the same result :disappointed: 

```
​​​​Quokka #1 (node: v8.9.4)​​​​
​​v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/home/daniel/Descargas/node-v8.9.4-linux-x64/bin/node]​​
​​ 5: 0xb9043c [/home/daniel/Descargas/node-v8.9.4-linux-x64/bin/node]​​
​​ 6: ​​
​​v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/home/daniel/Descargas/node-v8.9.4-linux-x64/bin/node]​​
​​ 7: 0x3bf2a70463d​​
```

Hola
```
​​​​Quokka #1 (node: v9.5.0)​​​​
​​/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node[27393]: ../src/node_file.cc:505:void node::InternalModuleReadFile(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `(numchars) >= (0)' failed.​​
​​​​
​​ 1: node::Abort() [/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node]​​
​​ 2: 0x8c811b [/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node]​​
​​ 3: 0x90395a [/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node]​​
​​ 4: ​​
​​v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))​​
​​ [/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node]​​
​​​​
​​​​
​​ 5: ​​
​​0xaddc5c​​
​​ [/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node]​​
​​​​
​​​​
​​ 6: ​​
​​v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)​​
​​ [/home/daniel/Descargas/node-v9.5.0-linux-x64/bin/node]​​
​​​​
​​​​
​​ 7: ​​
​​0x1b8109042fd​​
```

**Comment by ArtemGovorov** [comment]
I have no idea what may be causing it. Also can't try much because I can't reproduce the issue on the same OS, so it may be your environment specific.

There's just one thing I may suggest trying, try disabling the recently enabled by default in Quokka `@std/esm` module in your `~/.quokka/config.json`:

```diff
{
  ...
+ "stdEsm": false
}
```

Let me know if it changes anything.

**Comment by DanielRamosAcosta** [comment]
Exactly! That was the problem.  I've tried a few times set it to false and true to be sure it is.

Thanks a lot @ArtemGovorov !

**Comment by ArtemGovorov** [comment]
Hmm, the issue seems to be with how `@std/esm` is built. 

To confirm it, could you please try some quick test for me:

- Clone this repo https://github.com/ArtemGovorov/std-esm-integration/tree/v8issue and switch to the `v8issue` branch,
- run `npm i`,
- run `npm run esm`.

Does it produce the same error?

**Comment by DanielRamosAcosta** [comment]
Sorry I'm very busy now with a deadline, I'll try on monday!

**Comment by DanielRamosAcosta** [comment]
Sorry for the delay @ArtemGovorov . I've tried the test but it didn't give me any error:

![image](https://user-images.githubusercontent.com/11427028/36196592-28dad52c-1169-11e8-9e34-af6268d93fa6.png)

**Comment by ArtemGovorov** [comment]
@DanielRamosAcosta Thanks for checking!
