### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by danjdewhurst** [wallabyjs/quokka#158]
### Issue description or question
quokka won't run because my JS file uses navigator, so quokka says it's undefined. Do I need to do something to ignore this variable?

### Sample code

```javascript
var user_agent = navigator.userAgent;
```

### Quokka.js Console Output

```
navigator is not defined​​
```

### Code editor version

Visual Studio Code v1.20.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Quokka runs in node, so browser related objects like window/document/navigator/etc. are not available. To enable browser environment you may [use the Quokka `jsdom` plugin](https://github.com/wallabyjs/jsdom-quokka-plugin).
