### ISSUE TITLE
Babel 7 and custom global config

### ISSUE THREAD

**Issue by blackxored** [wallabyjs/quokka#159]
### Issue description or question
Apparently, Babel 7 doesn't seem to play nice with Quokka when it comes to global config in ~/.quokka/. 
Since you've changed module resolution in the past I'm hoping this is fixable.

### Sample code

```javascript
// ~/.quokka/package.json
{
  "dependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-proposal-pipeline-operator": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40"
  }
}

```

```javascript
// ~/.quokka/config.json
{"pro":true,"babel":{"presets":["@babel/preset-env"]}}
```

### Quokka.js Console Output

```
Quokka #1 (node: v9.5.0, babel: v7.0.0-beta.40)

Failed to run compilers on quokka.es6, Error: Cannot find module '@babel/preset-env' from '/Users/blackxored/Code/sample/...
```

### Code editor version

IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.3741.2, built on February 13, 2018
IntelliJ IDEA EAP User
Expiration date: March 15, 2018
JRE: 1.8.0_152-release-1136-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

**Comment by ArtemGovorov** [comment]
Thanks for the report. Babel 7 beta.40 support has been released in the latest Quokka plugin version 1.0.73.
