### ISSUE TITLE
window is not defined - front end js code

### ISSUE THREAD

**Issue by Smilebags** [wallabyjs/quokka#16]
### Issue description or question
Starting Quokka on an existing JS file, I'm getting 'window is not defined' on lines referencing the DOM window object. How can I stop this error? I understand Quokka has no idea of the context that the JS will be running in so the error is technically correct, is there a way to tell Quokka to ignore a section of code?
### Quokka.js file

```javascript
var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
ss = getUrlVars();
```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v6.9.1)​​​​
​​​​
​​window is not defined​​
```

### Code editor version

Visual Studio Code v1.10.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Quokka runs in node. To emulate browser environment you may [use this plugin](https://quokkajs.com/docs/configuration.html#community-plugins).

**Comment by frederico-kluser** [comment]
just create a mock object for your proposes

**Comment by frederico-kluser** [comment]
const document = {
  body: {
    getElementsByTagName: () => {},
  },
};
// mock -----

var elems = document.body.getElementsByTagName("*");

**Comment by frederico-kluser** [comment]
`const document = {
  body: {
    getElementsByTagName: () => {},
  },
};
// mock -----

var elems = document.body.getElementsByTagName("*");`

**Comment by frederico-kluser** [comment]
```
const document = {
  body: {
    getElementsByTagName: () => {},
  },
};
// mock -----

var elems = document.body.getElementsByTagName("*");
```
