### ISSUE TITLE
TypeScript doesn't error on invalid type assignments.

### ISSUE THREAD

**Issue by kid-icarus** [wallabyjs/quokka#161]
### Issue description or question

Expected: I see typescript's error [like this](https://www.typescriptlang.org/play/index.html#src=interface%20Car%20%7B%0D%0A%20%20%20%20make%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Alet%20redCar%3A%20Car%20%3D%20%7B%0D%0A%20%20%20%20make%3A%205%2C%0D%0A%7D)

Actual: No errors are presented, the code just runs.

### Sample code

```typescript
interface Car {
    make: string
}

const redCar: Car = {
   make :5
}
```

### Code editor version

Webstorm v2017.3?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Quokka doesn't stop or report any TS compilation errors. As long as TypeScript can produce any valid JavaScript code, Quokka can run it. Type checking is out-of-scope for the tool and is a job of IDE integrated compiler.

Unfortunately [Webstorm doesn't support type checking for scratch files](https://youtrack.jetbrains.com/issue/WEB-17352), but you may run Quokka on existing files (for example create real tmp file in your project), and IntelliJ built-in TypeScript compiler should be able to handle these cases (if your project has a valid TS configuration). 

These compilation errors for real files are displayed even if Quokka is not installed or not running:

<img width="420" alt="screen shot 2018-02-20 at 2 35 46 pm" src="https://user-images.githubusercontent.com/979966/36407610-6781ca06-164b-11e8-9f12-909551de94c9.png">

**Comment by kid-icarus** [comment]
Ah I see, thanks for the prompt response 👍
