### ISSUE TITLE
Cannot read property 'stack' of undefined

### ISSUE THREAD

**Issue by EdonGashi** [wallabyjs/quokka#163]
### Issue description or question

While trying to build a [plugin](https://github.com/EdonGashi/quokka-plugin-sharp-pad) to allow dumping outputs to SharpPad extension screen, I keep getting this message when trying to import the plugin:

![image](https://user-images.githubusercontent.com/12145268/36635088-87ca954c-19af-11e8-8123-50dcf21318d8.png)

I am finding it difficult to pinpoint the issue due to the cryptic error message. Running the dump.js code in a local node works as expected. Any help would be appreciated.

### Sample code

https://github.com/EdonGashi/quokka-plugin-sharp-pad
or
npm install quokka-plugin-sharp-pad

### Code editor version

Visual Studio Code
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### OS name and version

Windows 10 x64

**Comment by EdonGashi** [comment]
I unminified that file to try locate the error. It comes from this line:

![image](https://user-images.githubusercontent.com/12145268/36635237-ffd011be-19b1-11e8-819a-0db90ce42721.png)

**Comment by ArtemGovorov** [comment]
> `Cannot read property 'stack' of undefined`

This issue is fixed, thanks for the report.

> Update: As soon as I start using import/export the plugin breaks, it's crossing script engines and I'm losing type information.

Not sure what the issue is, I can't run the plugin as it displays:
```
​​{ [Error: connect ECONNREFUSED 127.0.0.1:5255]​​
​​  errno: 'ECONNREFUSED',​​
​​  code: 'ECONNREFUSED',​​
​​  syscall: 'connect',​​
​​  address: '127.0.0.1',​​
​​  port: 5255 }​​
```
error for me, so I'm probably missing some required dependency running on that port. 
Either way, looks pretty cool on your screenshot, even without exports/imports. 
BTW, does it work with exports/imports with [`babel` configured](https://quokkajs.com/docs/configuration.html#babel)?

**Comment by EdonGashi** [comment]
The connection refused is because you don't have the extension host open. It creates a listener where you can post structured objects and it pretty prints them. Makes an ideal combination with quokka!

![image](https://user-images.githubusercontent.com/12145268/36638244-ff0dcd32-19ef-11e8-9660-87013bf2ca70.png)

Yes, with babel it works as expected. Since I plan on using babel anyway it's not much of a problem.

You need this extension to test the plugin: 
https://marketplace.visualstudio.com/items?itemName=jmazouri.sharppad

Then run command `Show SharpPad Window`
