### ISSUE TITLE
​​NodeList is not defined​​

### ISSUE THREAD

**Issue by David-Else** [wallabyjs/quokka#166]
### Issue description or question
Hi,

I am trying out Quokka pro (using the import syntax), I have the JSDom plugin installed in `/home/david/.quokka` working fine with this config:

`{"pro":true,"plugins":["jsdom-quokka-plugin"],"jsdom":{"html":""}}`

but the first actual project I try to run it on gives me the error pasted below into the Console Output.

I am importing the package in question like this:

`import flatpickr from 'flatpickr';`

### Sample code

```javascript
const fp = flatpickr('#flatpickr', { <<< This is generating the error src/main.js:154:0
  onChange(selectedDates) {
    if (genderChosen !== undefined) {
      calculateNaturalExpression(selectedDates);
    }
  },
});
```

### Sample repository link
https://github.com/Else-Web-Development/natural-expression-calculator-application

and the file in question:

https://github.com/Else-Web-Development/natural-expression-calculator-application/blob/master/src/main.js

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.9.4)​​​​
​​​​
​​NodeList is not defined​​
  at ​​​flatpickr​​​ ​./node_modules/flatpickr/dist/flatpickr.js:2072​
  at ​​​Object.<anonymous>​​​ ​src/main.js:154:0​
```

### Code editor version

Visual Studio Code 1.20.1

### OS name and version
Linux Fedora 27

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in `jsdom-quokka-plugin@1.0.11`. Please update the module in your `/home/david/.quokka`.
