### ISSUE TITLE
Can't start Quokka

### ISSUE THREAD

**Issue by fandy** [wallabyjs/quokka#168]
### Issue description or question
When I start a new JS or TS file I'm getting the error `command 'quokka.createTypeScriptFile' not found`. I've tried reinstalling and restarting VScode but that did not fix it..

### Code editor version

Visual Studio Code v1.21

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Just tried to install Quokka from the scratch in the same version of VS Code on OSX and everything is working for me as expected.

Please try to delete any Quokka related folders in `~/.vscode/extensions`, restart the editors, install thee extension and restart the editor again.

If it doesn't help, please share the output from Developer Tools console (`Help - Toggle Developer Tools`) after you get the error.
