### ISSUE TITLE
Quokka overwrite the const value

### ISSUE THREAD

**Issue by fcrespo82** [wallabyjs/quokka#17]
### Issue description or question
When a const is defined and assigned a new value, Quokka warns that it cannot be assigned because is a const.

But if I print the value it shows the new value, I think would be of greater help if it showed the original value since the code can be large and the two lines not be visible at the same time on screen.

### Quokka.js file

```typescript
const b:number = 500;

b = 23434;

b;
```

### Quokka.js Console Output

```
​​​​Quokka #2 (node: v7.7.2, TypeScript: v2.1.6)​​​​

​​​​​23434​​​​​ at ​​​b​​​ ​quokka.ts:5:0​
```

### Code editor version

Visual Studio Code v1.10.2

### OS name and version

OSX 10.12.3 (16D32)

**Comment by ArtemGovorov** [comment]
You're using TypeScript and by default it compiles the code to ES5, so your 
```javascript
const b:number = 500;

b = 23434;

b;
```
becomes
```javascript
var b = 500;

b = 23434;

b;
```

If you change your TS compiler settings in the `tscondig.json` or [in the quokka config](https://quokkajs.com/docs/configuration.html#compiler-settings) to ratget ES6, then you'll get the expected result:
![ts](https://cloud.githubusercontent.com/assets/979966/24081440/23290848-0cff-11e7-99d5-b5d7e1ba1b81.gif)

**Comment by fcrespo82** [comment]
Hmm, nice.

Thank you!
