### ISSUE TITLE
Configurable gutter icons

### ISSUE THREAD

**Issue by ihackalot** [wallabyjs/quokka#170]
In WebStorm, Quokka's gutter icons are a little bit intrusive. IMHO they scream at me anyway, no matter if things are good or wrong, and grab my attention more than necessary. It's a handy indicator, but I'd like it to be a lot smaller, much like a dot than a square. As reference, try writing a recursive function and see the icon that WebStorm displays... I mean something about that size.

Additionally, I wasn't able to disable icons if not by hiding the whole gutter are.

Can I haz dots please? 😄

**Comment by ArtemGovorov** [comment]
Unfortunately icon shape is not configurable, however you may change the icons color to be less "screaming" or even set the colors to be match the color of you gutter to hide them.

**Comment by ihackalot** [comment]
Isn't it possible to use SVG or transparent PNG to "shape" icons?

**Comment by ArtemGovorov** [comment]
It may be, but to make it configurable, we'll need to let users specify their own icons and it adds some configuration complexity.

**Comment by ihackalot** [comment]
Well, you are right. Would you please consider improving your defaults this way? Instead of filling the whole gutter with color, shaping it with less obtrusive shape with SVG maybe.

**Comment by ArtemGovorov** [comment]
Out of hundreds of thousands users of our users (including our other tool Wallaby where the same icons are used), you are the first one to raise the issue. So changing the default may affect other users and make them unhappy.

**Comment by ihackalot** [comment]
It's ok, I appreciate your consideration :)

**Comment by ArtemGovorov** [comment]
Did changing colors in Webstorm settings for Quokka help at all?

**Comment by ArtemGovorov** [comment]
> By configurable I meant exposing WebStorm's tools for color schemes... foreground color... background... anything

Yep, as I mentioned in my initial response, we do support it:

<img width="995" alt="screen shot 2018-03-22 at 7 51 58 pm" src="https://user-images.githubusercontent.com/979966/37763349-847dd5f6-2e0a-11e8-95af-6133638587ba.png">

**Comment by ihackalot** [comment]
Oh yes thank you, I saw how to change color eventually, but unfortunately, it doesn't really help. I'm fine with bright colors and even the defaults. The problem is that after a couple of lines it kinda gets blocky and that's a bit annoying (not meaning to be offensive whatsoever).

Honestly, I don't see how users would be unhappy, considering Quokka's visual indicators are by far the most obtrusive inside WebStorm, even heavier than CSS color previews themselves, that are bigger than normal for a good reason (if you opt-in, you do it to clearly see which color, and chances are you never have more than two or three lines with a gutter icon that big). With Quokka enabled it's like either rolling hills... I mean, substantial grass coverage or bloody hell.

I really don't see the point to be visually so aggressive. I'd be happy to help for a better solution, but if you really don't want to, then I will understand :)

**Comment by julian-hoch** [comment]
I agree with the sentiment in this issue. I would go even further - since vscode is currently not allowing multiple gutter icons, extensions compete for space in the gutter area. It would be helpful if we could simply turn off / on the icons altogether ideally with a simple command.

**Comment by smcenlly** [comment]
@julian-hoch - keen to understand your use case where you want to run Quokka and not have the gutter indicators. I would have thought that disabling the gutter indicators would pretty much cripple Quokka functionality, in which case you could simply stop (or not start) Quokka? 

Can you explain when Quokka gutter indicators have compromised other gutter indicators you were using in VS Code?

**Comment by julian-hoch** [comment]
There is this extension called "Error Lens" that shows icons in the gutter for linting problems. Quokka (and Wallaby) gutter icons cover these up, so it would be nice to be able to switch between them (or show both,but that does not seem possible right now).
