### ISSUE TITLE
Basic usage: "cannot find module" and "cannot find name 'require'" when using a package

### ISSUE THREAD

**Issue by borekb** [wallabyjs/quokka#171]
I'm trying to use packages in a Quokka TypeScript file and cannot get past the simplest require.

If I do:

```
import * as _ from 'lodash';
```

I get

```
[ts] Cannot find module 'lodash'.
```

(note that the actual package is installed; Quokka output is clear, printing just `​​​​Quokka #2 (node: v8.10.0, TypeScript: v2.7.2)​​​​`)

![image](https://user-images.githubusercontent.com/101152/37555244-c05c5310-29e4-11e8-8142-9a08621c5b45.png)

If I do 

```ts
const _ = require('lodash');
```

I get

```
[ts] Cannot find name 'require'
```

![image](https://user-images.githubusercontent.com/101152/37555249-d436fa48-29e4-11e8-8bd0-a01f6f96c467.png)

Everything works, otherwise:

![image](https://user-images.githubusercontent.com/101152/37555275-562b193a-29e5-11e8-844c-738f373d6e40.png)

How do I get rid of those TypeScript errors?

VSCode 1.21.1, Windows 10,

**Comment by borekb** [comment]
I also don't get TypeScript suggestions:

![image](https://user-images.githubusercontent.com/101152/37555406-e72e63c8-29e6-11e8-8964-ea3851c2c64e.png)

**Comment by ArtemGovorov** [comment]
As you can see on your screenshots, Quokka is working fine (indicators and inline messages are displayed). Code completion and TypeScript error checking is not what Quokka does or affects in any way. If you stop Quokka on that file (or even uninstall it), you'll still get those TypeScript errors even without the tool. My guess is that you perhaps don't have a valid tsconfig.json in the project, or don't have node types configured (but it's outside of Quokka scope anyway).

**Comment by borekb** [comment]
I understand but wouldn't there be a way to make the first time experience better somehow? I'd expect basic things like `require` or suggestions to work. It might be technically somewhat challenging but for me, Quokka is a way to save time when experimenting, and for saving time I expect basic IDE features to be there.

**Comment by ArtemGovorov** [comment]
Sorry, I have probably not it made it clear - the issues that you have listed are not Quokka related. If you create a new TypeScript file, and try your code, you will get the exact same result even if you have Quokka stopped (or even not installed in VS Code). 

So you may want to report those issues to VS Code team. But I suspect they may point out exactly the same as I had pointed out above - most likely the issue is that you don't have a valid tsconfig.json in the project, or don't have node types configured in it (so TypeScript compiler has no idea about what `require` is).

**Comment by borekb** [comment]
My scenario: I'm in a project where `tsconfig.json` exists (actually, many of them; it is a monorepo), I'm in a TypeScript file where my code works fine. I want to experiment with it so I run _Quokka.js: New TypeScript file_ and copy/paste the exact same code there, and suddenly I get various errors.

I sort of understand because the file is not saved so it's harder for Quokka to determine my `tsconfig.json`, and maybe there's some config that I didn't quite explore yet but the problem is not with my code.

Another valid scenario, IMO: I open an empty VSCode instance (no project open, no `tsconfig.json` anywhere), I do the same _Quokka.js: New TypeScript file_ and start writing some Node.js code (with imports, etc.).

Quokka has this magical "install package" feature which is awesome, and similarly, I'd expect that it would understand that I'm trying to test some Node.js code. Maybe I'm spoiled a little bit :) For example, it could prompt me "It seems like you're trying to write Node.js code, do you want to enable Node.js support?". I'd click "Yes" and would be all set. You could go further and fetch `@types/package` to get TS suggestions, etc. IMO, this fits into the "experiment quickly" mantra of Quokka quite nicely.

Just some feedback..

**Comment by ArtemGovorov** [comment]
> I sort of understand because the file is not saved so it's harder for Quokka to determine my `tsconfig.json`, and maybe there's some config that I didn't quite explore yet but the problem is not with my code.

Hmm, I can't reproduce this issue. When I try it locally, as soon a valid `tsconfig.json` is added to the project, everything starts working on new TypeScript Quokka files (those are just new unsaved TypeScript files).

Maybe it doesn't work for you because you don't have a root tsconfig.json? Because when file is not saved, it may be treated as it is in the project's root.

> Another valid scenario, IMO: I open an empty VSCode instance (no project open, no `tsconfig.json` anywhere), I do the same _Quokka.js: New TypeScript file_ and start writing some Node.js code (with imports, etc.).

> Quokka has this magical "install package" feature which is awesome, and similarly, I'd expect that it would understand that I'm trying to test some Node.js code. Maybe I'm spoiled a little bit :) For example, it could prompt me "It seems like you're trying to write Node.js code, do you want to enable Node.js support?". I'd click "Yes" and would be all set. You could go further and fetch `@types/package` to get TS suggestions, etc. IMO, this fits into the "experiment quickly" mantra of Quokka quite nicely.

This sounds like a good idea, we will investigate.

**Comment by borekb** [comment]
You're right, the folder doesn't have a root `tsconfig.json`, all of them are nested in concrete subprojects (`/app1`, `/library2`, etc.). That explains it. Also thanks for considering the better "magical" TypeScript experience, it would help me and hopefully others as well.
