### ISSUE TITLE
Loading Typescript Scratch Modules - Webstorm

### ISSUE THREAD

**Issue by NikkiJ19** [wallabyjs/quokka#175]
### Issue description or question
Typescript scratch modules are not loading when imported from another file in the Webstorm scratch directory. 
I am using the pro edition of quokka. Typescript modules seem to load fine when using quokka in a project and when I tried from vs-code.

I have installed ts-node using npm install in the %UserProfile%\.quokka directory. 

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

The files in this repository would all be in the scratch directory.

https://github.com/NikkiJ19/TS-Module-Loading---Webstorm

### Quokka.js Console Output

Quokka #1 (node: v8.9.1, TypeScript: v2.5.2)

Cannot find module './ModuleB'
	at Function.Module._resolveFilename module.js:536
	at Function.Module._load module.js:466
	at require internal/module.js:11
	at Object.<anonymous> quokka.ts:1
	at Module._compile module.js:635

### Code editor version

Visual Studio Code v1.?
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Webstorm v?
WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### OS name and version

Windows 10 - Version
![image](https://user-images.githubusercontent.com/31554476/37941984-ccee5130-3125-11e8-9ea8-ac99ab390994.png)

**Comment by ArtemGovorov** [comment]
Quokka is Webstorm is running in the context of an opened project, so whatever files are imported need to be in the project (except for the scratch file itself). 

With the modules in the project, everything is working as expected.

<img width="574" alt="screen shot 2018-03-27 at 12 31 32 pm" src="https://user-images.githubusercontent.com/979966/37943632-aa9e562a-31bb-11e8-929a-800a2d5ebfc4.png">

**Comment by NikkiJ19** [comment]
Thanks for the clarification. The product has been an excellent learning tool.

Cheers
