### ISSUE TITLE
Show console.info() and console.debug() at OUTPUT panel

### ISSUE THREAD

**Issue by unional** [wallabyjs/quokka#178]
### Issue description or question

I have logging tool that prints output using other console methods (`info()`, `warn()`, `debug()`).
e.g.: https://github.com/unional/aurelia-logging-color

It would be nice if the Quokka OUTPUT panel can display those messages too

### Sample code

```javascript
console.log('from log :)')
console.info('from info :(')
```

![image](https://user-images.githubusercontent.com/3254987/38189214-e3a4ac2e-3613-11e8-953c-6620544e76c9.png)

### Code editor version

Visual Studio Code v1.21.1

### OS name and version

All. :)

🌷 

EDIT: `log`, `warn`, `error` already do. So only need to add `info()` and `debug()`

**Comment by ArtemGovorov** [comment]
Thanks for the request, implemented and published.
