### ISSUE TITLE
Support Sublime Text

### ISSUE THREAD

**Issue by gj1118** [wallabyjs/quokka#18]
Well, this is a not an issue per se, but can you please grant me my wish of having quokka in Sublime Text , please ?  

thanks 
gagan

**Comment by jacktuck** [comment]
Use VS Code 😆

**Comment by fidgetwidget** [comment]
@jacktuck has it's mac support improved at all? when I used it a couple months ago on a mac, it wasn't pretty good...

**Comment by drod3763** [comment]
I second this.

**Comment by bsvipas** [comment]
I'm interested too!

**Comment by iamaamir** [comment]
me too

**Comment by wrisx** [comment]
+1

**Comment by Slapbox** [comment]
Would love to see this happen. Quokka seems great, but not great enough to ditch Sublime.

**Comment by 09wattry** [comment]
Please!

**Comment by tls11** [comment]
This would be awesome!

**Comment by gj1118** [comment]
I don't think they are even planning to do it , otherwise they would have let the community know.
:(

**Comment by mjasnikovs** [comment]
How could you, best editor ever not included? :disappointed_relieved:

**Comment by jakub-frajt** [comment]
+1

**Comment by bhayward93** [comment]
Would love to see this. I'm just too in Sublime to move.

**Comment by ChuksFestus** [comment]
please please add this... i can help 😥

**Comment by evanschaba** [comment]
y'all love quokka dis much huh? 👍  
me too

**Comment by victorhazbun** [comment]
👍

**Comment by rintosarkar** [comment]
Interested and be happy if it available in Sublime

**Comment by gyfnice** [comment]
please add this feature, I only love Sublime...

**Comment by flexbusterman** [comment]
+1 Sublime support

**Comment by hilmerx** [comment]
+1

**Comment by skjghisole** [comment]
up

**Comment by my8bit** [comment]
+1

**Comment by nth-chile** [comment]
+1

**Comment by Palmweaver** [comment]
+1 I would love to see this available for Sublime

**Comment by cryptoads** [comment]
another vote

**Comment by Aaron-von-Awesome** [comment]
+1

**Comment by thecodecafe** [comment]
+1

**Comment by salehdevs** [comment]
+1

**Comment by ianlennymatthews** [comment]
+ 1

**Comment by AdrianSkar** [comment]
+1

**Comment by gj1118** [comment]
**Authors**, I think it will be very polite of you, if you can just give us an update (or an estimate) - are you guys planning to implement it or otherwise. The community will also appreciate this step of yours. Simply going quiet for 2 long years makes me think otherwise , but we all are waiting for an answer from you guys.

Hope you will understand. 

Thanks

**Comment by smcenlly** [comment]
We appreciate everyone's interest. We plan on releasing Quokka for Sublime at some point in the next 6-12 months. We have not started development, and it's not currently scheduled so can't commit to anything more specific at this point in time. We will, of course, update this thread when it's available.

**Comment by gj1118** [comment]
Hey Guys, Thank you 🙏 😄.. I see this on packageControl , https://packagecontrol.io/packages/Quokka , gave it a shot and its working awesome.. so far so good 

Thanks for all the hard work!!! 
Much appreciated ..

**Comment by smcenlly** [comment]
@gj1118 - thanks! We were just in the middle of preparing our announcement...

😃🎉 **Quokka for Sublime is now available as a BETA.** 🎉😃

We have a number of known bugs and missing features that we will be rounding out over the next week or two before we officially release. Please hold off on reporting any issues until we're done with our own QA processes (we will let you know when).

If you'd like to try [Quokka PRO edition](https://quokkajs.com/pro/), you may use the trial license key below (valid for 15 days):

_RXh0ZW5kZWQgVHJpYWwKd2FsbGFieWpzQGdtYWlsLmNvbSxRdW9ra2EuanMgcGVyc29uYWwgbGljZW5zZQoyNy8wNi8yMDE5CmpOK3lzSGlTc3BYczhXTURZb1lIVmpnZGY3dDYzUGJrdTJ4eFIwL2hHQ2o5ZERFRjNISncxWThzK2tpU1ExZ1JqbDBFQ0RPV1MvY2tMS0FMQkVNMmMxUFhCU1RxZHN6S1NPN0s2cUNqL1BNYzd3anhBcmFoV2FocVJqRzlLVHFKRlBZTjBiZFQ0R2k2YlFMdTY4QVRsUlRZOGNaOG5yNCtpa0lYUHBQRTNPRlE3TnhMQUFOdmc0ZlFYY3JONzBkTm1kVXJKL2sxM1FvSmFKVU5EOEVNWm1DSElRY3I1emV2ZVVvc0VKUzBIMFVhZ3pJeFB6WndjcDBxek5lQWpZT2hudzh0RjV2Vkl3bUdBQUlaeWt0aVJBSnlLSlZnRXBNK3JvNXZaZUlRaG9ydXhQSWNjY1Z0MXBNSHlVRU1BNUdpdjBnQmUzT3FTQVlPZVY2SGpwdmQ4QT09_
