### ISSUE TITLE
warning No license field | warning package.json: No license field

### ISSUE THREAD

**Issue by mtin79** [wallabyjs/quokka#181]
When i add the babel-core package via "yarn add babel-core" in the global config file under ~/.quokka  

i get various errors like:
- warning No license field
- warning package.json: No license field

Whats going on exactly here.
Do i need to copy the license key into the package.json file?
Couldnt find any docs about it or issues posted here.

Thanks for help.

**Comment by ArtemGovorov** [comment]
These are warnings from yarn, they are not related to quokka and may just ignore them. If you want, you may add a license field (with any value) to the `~/.quokka/package.json` file to make yarn happy.
