### ISSUE TITLE
Output compare doesn't show colors

### ISSUE THREAD

**Issue by ahmed-shehata** [wallabyjs/quokka#184]
### Issue description or question
When using the Quokka compare feature, the output doesn't properly show the diff as the output is not colored correctly. I am not sure if it is a configuration issue with Quokka or VSCode, I have tried different color themes (including default), but still same problem.
### Sample code

```javascript
const array = [5,6,1,8,9];
const array2 = [5,6,1,8,7];

array,array2;
```

![image](https://user-images.githubusercontent.com/4982099/38927179-3bd007ce-4305-11e8-9176-e5807b744b6c.png)

### Code editor version

Visual Studio Code v1.22.2

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
Due to the way [highlighting currently works in VS Code](https://github.com/Microsoft/vscode/issues/11005), it is possible that some other extension had  "stolen" the highlighting for output channels. Please try disabling other extensions to find the conflicting one.

**Comment by ahmed-shehata** [comment]
That did the trick! The problematic extension was Code Runner, thanks!
