### ISSUE TITLE
Live Comments doesn't produce any results (Pro Version)

### ISSUE THREAD

**Issue by kwingat** [wallabyjs/quokka#185]
I can't get the live comments to work. I can import an object and console.log() on the import so I know that Quokka is running and Pro features are activated. 

### Sample code

```javascript
const something/*?*/ = [1, 2, 3];

function sum(a, b) { 
  return a + b;
}

sum (1, 1); //?

console.log(sum(1, 1)); 
```
### Quokka.js Console Output

```
Quokka #1 (node: v6.12.2, babel: v6.26.0)

2 at sum(1, 1) quokka.js:9:0
```

### Code editor version

Visual Studio Code v1.19.2

### OS name and version

OSX MacOS Sierra v10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for the report. We have fixed it and published the new version. Please update your extension in VS Code and it should work for you.

Note that this live comment
```js
const something/*?*/ = [1, 2, 3];
```
will still not work as it is nit positioned after an expression, but in a middle of variable declaration. This should work:

```js
const something = [1, 2, 3]/*?*/;
// or
const something = [1, 2, 3]; /*?*/
```

**Comment by kwingat** [comment]
Great turn around. Thanks so much.
