### ISSUE TITLE
Invalid color for contextual output in IntelliJ

### ISSUE THREAD

**Issue by blackxored** [wallabyjs/quokka#188]
### Issue description or question

Latest Quokka update started setting a custom color (or changed the color in some way), so that it makes it unreadable under dark color schemes. 
I tried briefly going over my Code Style settings but there doesn't seem to be such a value (given I switch color schemes and still remains blue, I'd assume this got hardcoded in some way).

### Sample

<img width="508" alt="screenshot 2018-04-24 18 04 55" src="https://user-images.githubusercontent.com/133308/39199765-8df3e522-47ea-11e8-893d-c74c32550371.png">

### Quokka.js Console Output

```
Quokka #1 (node: v9.11.1, babel: v6.26.0)

Right(6) at (0, _ramda.map)(function (x) {
    retur... quokka.es6:27:0

Left("Some error") at (0, _ramda.map)(function (x) {
    retur... quokka.es6:28:0```

### Code editor version

IntelliJ IDEA 2018.1.2 (Ultimate Edition)
Build #IU-181.4668.14, built on April 17, 2018
Licensed to Adrian Perez
Subscription is active until December 29, 2018
JRE: 1.8.0_152-release-1136-b29 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by ArtemGovorov** [comment]
Quokka is using system output console color of your color scheme, but it does require the IDE restart and the color scheme change.

<img width="815" alt="screen shot 2018-04-25 at 9 34 22 am" src="https://user-images.githubusercontent.com/979966/39219112-ee48107a-486b-11e8-962a-5325ca78e18d.png">

Try restarting your IDE (after applying your color schema changes, and before starting Quokka), it should help.
