### ISSUE TITLE
Configuration file parser has issues

### ISSUE THREAD

**Issue by RandallFlagg** [wallabyjs/quokka#189]
### Issue description
This is the content of my config.json file.

This Doesn't work:
`{"pro":false,"plugins":["jsdom-quokka-plugin"], "jsdom": {"html": '<div id="test">Hello</div>'}}`

But this does work:
`{"pro":false,"plugins":["jsdom-quokka-plugin"], "jsdom": {"html": "<div id='test'>Hello</div>"}}`

They are both valid JSON but the error I get in VSCode is that the config file has to be valid JSON.

### Code editor version

Visual Studio Code v1.22.2

### OS name and version

Windows 10 x64 - 1703 Build 15063.0

**Comment by ArtemGovorov** [comment]
The first snippet is not a valid JSON. VS Code (without Quokka) can tell you that:
<img width="748" alt="screen shot 2018-04-25 at 5 54 24 pm" src="https://user-images.githubusercontent.com/979966/39232771-b8969eec-48b1-11e8-9668-50343890a4af.png">

**Comment by RandallFlagg** [comment]
You are right. The tool I used decided to report it silently for some reason.
