### ISSUE TITLE
Support for Jetbrains IDEs (Intellij Idea, Webstorm, etc.)

### ISSUE THREAD

**Issue by umeshv** [wallabyjs/quokka#19]
Would like to see this amazing tool on Intellij Idea. Thanks for this nice tool. :+1:

**Comment by smeijer** [comment]
Seems to me they've published it yesterday! A wish came true.

https://plugins.jetbrains.com/plugin/9667-quokka

**Comment by ArtemGovorov** [comment]
We have indeed. The announcement and the blog post is coming later today, but feel free to start using it now.
