### ISSUE TITLE
After changing config.json the current window doesn't reflect the changes

### ISSUE THREAD

**Issue by RandallFlagg** [wallabyjs/quokka#190]
### Issue description or question
After changing _`config.json`_ the current window doesn't reflect the changes.

This should be mentioned in the documentation or fixed to be supported.

### Code editor version

Visual Studio Code v1.22.1

### OS name and version

Windows10 x64 1703 Build 15063.0

**Comment by ArtemGovorov** [comment]
Good point, thanks!
