### ISSUE TITLE
looks like not support console.dir

### ISSUE THREAD

**Issue by bluelovers** [wallabyjs/quokka#191]
### Sample code

```javascript
const RE_NO_DOLLAR_PREFIX = /(?<=\$)foo/g;
let a = '$foo %foo foo'.replace(RE_NO_DOLLAR_PREFIX, 'bar');

console.dir(a);
console.log(a);
```

### Quokka.js Console Output

![2018-04-28-15-19-27-2](https://user-images.githubusercontent.com/167966/39393440-cd81a412-4af7-11e8-954e-41fc1feb4e6c.jpg)

### Code editor version

idea v2018.1.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Only console.log (and [live comments](https://quokkajs.com/docs/#comments)) are displayed inline. Having said that, `consoe.dir`/etc. results are displayed in the Quokka Output panel:

<img width="489" alt="screen shot 2018-04-28 at 7 52 06 pm" src="https://user-images.githubusercontent.com/979966/39395097-b62aba26-4b1d-11e8-90d6-2fb56ffe19bf.png">
