### ISSUE TITLE
SyntaxError: Unexpected token at Flowtype declaration in React

### ISSUE THREAD

**Issue by voodoods** [wallabyjs/quokka#193]
### Issue description or question
Quokka.js seems to be having problems with Flowtype declarations in React components. File execution breaks at the line of the type definition. 

### Sample code
```javascript
// @flow
import React from 'react'

type MyPropTypes = {
  text: string
}

const MyComponent = ( props: MyPropTypes ) => {
  const { text } = props

  return (
    <div className="my-component">
      {text}
    </div>
  ) 
}

export default MyComponent
```

### Sample repository link
https://github.com/voodoods/kicker-scoreboard/blob/functional-react-setup/src/game-teaser/GameTeaser.js

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v9.4.0)​​​​
​​SyntaxError: Unexpected token (4:5)​​
```

### Code editor version

Visual Studio Code v1.22.2

### OS name and version
macOS (OSX) High Sierra Version 10.13.4

**Comment by ArtemGovorov** [comment]
Quokka runs your code in node. In order to run Flow/JSX code, it needs to be compiled to JavaScript first. You may [configure Quokka to use Babel](https://quokkajs.com/docs/configuration.html#babel) and it should work for you.
