### ISSUE TITLE
[QUESTION] Is this the expected behaviour for quokka + flow?

### ISSUE THREAD

**Issue by magicspon** [wallabyjs/quokka#194]
### Sample code

```javascript
// @flow

const tim = (value: string) => {
	return value
}

const test = tim(10) // ?

```

![image](https://user-images.githubusercontent.com/3268717/39536155-b178c136-4e2d-11e8-8635-106e91200a8f.png)

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v9.8.0, babel: v6.26.0, plugins: jsdom-quokka-plugin)​​​​

​​​​​10​​​​​ at ​​​tim(10)​​​ ​src/js/sandbox/playground.js:7:0​
```

### Code editor version

Visual Studio Code 1.22.2 (1.22.2)

### OS name and version

OSX 10.13.4 

Thanks

**Comment by ArtemGovorov** [comment]
Looks expected to me:
- Flow does the type checks and displays the type error in VS Code.
- Type errors however are not stopping Flow from compiling the code to valid JavaScript, so Quokka can run the compiled result (and does run it). Type checking with Flow is just dev time experience, all typing related code is removed by Babel when compiling the code to JavaScript. 

Please let me know if it addresses your question, or you were concerned about something else than type checking in this case.

**Comment by magicspon** [comment]
Thanks @ArtemGovorov.
