### ISSUE TITLE
Quokka not working in Webstorm 2018.2 (MacOS)

### ISSUE THREAD

**Issue by jwagon** [wallabyjs/quokka#196]
### Issue description or question

Basically, nothing is happening, though Quokka appears to be running. It seems like it restarts every few seconds.

### Sample code

```javascript
let x = 6;
let z = x + 1;
```

### Quokka.js Console Output

```
Quokka #1 (node: v5.6.0)
```
<img width="909" alt="screen shot 2018-05-03 at 11 49 40 am" src="https://user-images.githubusercontent.com/908153/39588077-03e01884-4ec9-11e8-8dd5-d98b1bd4a93b.png">

### Code editor version

Webstorm v2018.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Quokka is using the [`esm` module](https://github.com/standard-things/esm) by default and it only supports node 6+. You may either [install/specify a newer node version](https://quokkajs.com/docs/configuration.html#nodejs-version), or add  `"stdEsm": false` to your [Quokka config](https://quokkajs.com/docs/configuration.html).
