### ISSUE TITLE
Support for Atom

### ISSUE THREAD

**Issue by tyler-reitz** [wallabyjs/quokka#20]
Not to pile it on but Atom devs really need this one.

**Comment by metasean** [comment]
It's stated that, "We are working on the support for other editors that are supported by Wallaby.js." [0] and Atom is supported by Wallaby.js [1], so at some point we'll get Quokka for Atom.

What is the current ETA for a Quokka Atom package?

---  
0: [quokajs.com](https://quokkajs.com/)
1: [wallabyjs.com Atom package install instructions](https://wallabyjs.com/docs/intro/install.html#atom)

**Comment by ArtemGovorov** [comment]
@metasean We are working on it, the plan is to release it in a few weeks.

**Comment by ArtemGovorov** [comment]
Just wanted to share the teaser:

![q](https://user-images.githubusercontent.com/979966/29616985-96a68868-8856-11e7-912a-80e26c10654c.gif)

It's getting there and we may release it sooner than we thought. Stay tuned.

**Comment by ArtemGovorov** [comment]
The first version is out: https://quokkajs.com/docs/?editor=atom. Official announcement and blog post are coming later this week.

**Comment by metasean** [comment]
step 0: See above message and get giddy
step 1: `apm install atom-quokka`
step 2: see `Installing atom-quokka to /Users/metasean/.atom/packages ✓`
step 3: do a happy, happy dance
![](https://media.tenor.co/images/ca38b8f7e096956f258d406a7820c7ba/tenor.gif)
