### ISSUE TITLE
Show Symbol description

### ISSUE THREAD

**Issue by koziejka** [wallabyjs/quokka#201]
It's a simple one, now using quokka while working with `Symbols` in js is very annoying because all that is shown is `Symbol {}` without it's description.

Maby you could display `symbol.toString()` instead.
Or you can display them like `Symbol (foo) { }`

![image](https://user-images.githubusercontent.com/10416254/39875694-9edcf2fa-5471-11e8-9db9-4bdf486f32fe.png)

Either way I think it would be a great and simple addition.

**Comment by ArtemGovorov** [comment]
Thanks for the feature request, it has been implemented and published in the latest version.
