### ISSUE TITLE
Spinner [--=----] never stops

### ISSUE THREAD

**Issue by simonl65** [wallabyjs/quokka#202]
### Issue description or question
I have noticed that the [--=----] (spinner?) never stops when testing some of my code. I've tracked it down to the `mysql.format` function from the **npm mysql** module, but can't see why it's happening. If I comment-out the `query = mysql.format(query, bind);` line (and uncomment the `bind,` line  in the `connection.query` block) the spinner stops.

### Sample code

```javascript
const mysql  = require('mysql');

try
{
  var pool = mysql.createPool
  ({
    connectionLimit : 100,
    host            : 'hostname',
    user            : 'username',
    password        : 'password',
    database        : 'dbname',
    debug           : false
  });
}
catch(err)
{
  console.error(`Database pool creation failed:`, err);
}

function dbquery(query, bind)
{
  return new Promise
  (
    (resolve) =>
    {
      // Escape the query:
      query = mysql.format(query, bind); // <---- THIS IS THE OFFENDING CODE <<

      pool.getConnection
      (
        (err, connection) =>
        {
          connection.query
          (
            query,
            // bind,  // <--- Reinstate if not using mysql.format() <<<<<<<<<<<
            (err, rows) =>
            {
              connection.release();
              resolve( rows );
            }
          );
        }
      );
    }
  );
}

const projectId = 1526545090463;

process( projectId )
.then( result => console.log("RESULT:", result) )
.catch( err => console.error(`[devprocess] ERR`, err) );

/**
 * Processes a project and return summary data.
 * @param {integer} projectId ID of project to be processed.
 */
async function process( projectId )
{
  try
  {
    const tree = await getProjectTree(projectId);
    return tree;
  }
  catch(err)
  {
    return "fail";
  }
}


/**
 * Returns a project's tree from the database.
 * @param   {integer} projectId ID of project whos tree is required.
 * @returns {object}            Project's tree.
 */
function getProjectTree(projectId)
{
  return new Promise
  (
    (resolve, reject) =>
    {
      const query = `
            SELECT JSON_EXTRACT(tree, '$[0].nodes') AS nodes
            FROM projects
            WHERE
              deleted = 'N'
              AND project_id = ?`;

      const bind = [projectId];

      dbquery( query, bind )
      .then
      (
        ( nodes ) =>
        {
          // Check for error:
          if( !nodes.errCode )
          {
            resolve(nodes);
          }
          else
          {
            reject({ status: "fail" });
          }
        }
      )
    }
  );
}

```

### Sample repository link

Only needs the npm [mysql module](https://www.npmjs.com/package/mysql) So `npm install mysql`.

### Quokka.js Console Output

The console output is as expected - it runs to the finish OK.

### Code editor version

Visual Studio Code v1.23.1

### OS name and version

Windows 10 Pro
Version1803
OS Build 17134.48

**Comment by simonl65** [comment]
Hmmm, just had cause to re-visit this and find that the following (which doesn't use the `mysql.format`) also keeps the sopinner running:
```javascript
/*eslint no-console:0*/
const mysql = require('mysql')

var cnx = mysql.createConnection
({
  connectionLimit : 100,
  host            : 'host',
  user            : 'user',
  password        : 'pass',
  database        : 'db',
  debug           : false
});

function dbquery(query)
{
  return new Promise
  (
    (resolve) =>
    {
      cnx.query
      (
        query,
        (err, rows) =>
        {
          resolve( rows );
        }
      );
    }
  );
}

process()
.then( (res) =>  console.log("RES:", res) )

async function process()
{
  return await dbquery('SELECT project_id, name FROM projects')
}
```
Not sure how much more _bare bones_ this can get!

**Comment by ArtemGovorov** [comment]
If you run the exact same code in plain node, ie. put the code above into `sample.js` file and run in command line:

```
node ./sample.js
```

does the program exit, or keeps running forever?

**Comment by ArtemGovorov** [comment]
if it never exits, then it's expected, as Quokka runs the same node program and exists when the program exists.

Take a look [here](https://github.com/wallabyjs/quokka/issues/128), perhaps you need to call `cnx.exit()` after getting the results, as the [`mysql` docs sample suggests](https://www.npmjs.com/package/mysql#introduction).

Let me know if it doesn't help.

**Comment by simonl65** [comment]
@ArtemGovorov Schoolboy error on my part in the second example - I completely forgot to add the `cnx.end();` - but I have found that I need to use **`connection.destroy();`** (instead of `connection.release();`) to fix the issue when using a connection pool. It seems that the mysql module keeps something running if using `.release`.

Many thanks for spending your time looking into this. I'm loving Quokka!
