### ISSUE TITLE
Unexpected token at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:689​

### ISSUE THREAD

**Issue by zeeshanu** [wallabyjs/quokka#203]
### Issue description or question

I am importing a project file in a file where i am running quokkajs and i am keep getting the same error.

![image](https://user-images.githubusercontent.com/16267321/40260879-55ba0cfe-5b0e-11e8-8a5f-577c3a96d026.png) 

### Quokka.js Console Output

```
Quokka #1 (node: v10.1.0)​​​​
​​​​
​​Unexpected token (25:13)​​
  at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:689​
```

### Code editor version

Visual Studio Code 1.23.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Please share the source of the file that you're importing (or try to comment out parts of the imported source file to find the offending code), maybe it is using some syntax that is only supported with Babel (and you don't seem to have Babel configured with Quokka).
