### ISSUE TITLE
Allow use nodejs from wsl

### ISSUE THREAD

**Issue by ErBlack** [wallabyjs/quokka#204]
Please add option to use nodejs and npm from the linux environment on windows

https://ru.wikipedia.org/wiki/Windows_Subsystem_for_Linux

I think it should be something like this https://code.visualstudio.com/updates/v1_17#_first-steps-towards-wsl-support

**Comment by ArtemGovorov** [comment]
Thanks for suggesting the feature request. You may subscribe to it here: https://github.com/wallabyjs/quokka/issues/187.
