### ISSUE TITLE
Syntax Error Unexpected token { when running quokka after install in VS Code

### ISSUE THREAD

**Issue by ksbalajee** [wallabyjs/quokka#207]
### Issue description

I just installed quokkajs and reloaded my visual studio code, started quokka and got the following error in console.

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v5.12.0)​​​​
​​/home/vdiuser/.vscode/extensions/WallabyJs.quokka-vscode-1.0.125/dist/wallaby/node_modules/esm/esm.js:1​​
​​(function (exports, require, module, __filename, __dirname) { "use strict";const{defineProperty:e}=Reflect,{freeze:t}=Object,{versions:r}=process,n=r.chakracore,o=r.v8||n,c=process.version,{filename:u,id:l}=module,a=l.startsWith("internal/")?N("internal/bootstrap/loaders"):void 0,{Script:i}=require("vm"),{runInNewContext:s,runInThisContext:d}=i.prototype,{existsSync:_,mkdirSync:f,readFileSync:m,unlinkSync:p,writeFileSync:h}=require("fs"),{resolve:y}=require("path"),q=require("module"),v=a&&a.NativeModule,b=new q(l,null),x=module.constructor.length>1;let S;b.filename=u,b.parent=module.parent;let g=require;function D(){let e,t,r,u,l,a="esm.js";if(v)u=v._source["internal/esm/loader"];else{const n=w(c+"\0"+o)+".blob",i=y(__dirname,"esm/loader.js");l=y(__dirname,"node_modules"),r=y(l,".cache"),t=y(r,n),e=I(t),u=I(i,"utf8"),a=y(__dirname,a)}const f=new i("(function (require, module, __shared__) { "+u+"\n});",{_​​
​​​​
​​SyntaxError: Unexpected token {​​
​​    at exports.runInThisContext (vm.js:53:16)​​
​​    at Module._compile (module.js:387:25)​​
​​    at Object.Module._extensions..js (module.js:422:10)​​
​​    at Module.load (module.js:357:32)​​
​​    at Function.Module._load (module.js:314:12)​​
​​    at Module.require (module.js:367:17)​​
​​    at module.js:504:12​​
​​    at Array.forEach (native)​​
​​    at Function.Module._preloadModules (module.js:503:12)​​
​​    at preloadModules (node.js:298:38)​​
```

### Code editor version

Visual Studio Code v1.23.1

### OS name and version

Ubuntu 16.04 LTS

**Comment by ArtemGovorov** [comment]
Quokka is using the [`esm` module](https://github.com/standard-things/esm) by default and it only supports node 6+. You may either [install/specify a newer node version](https://quokkajs.com/docs/configuration.html#nodejs-version), or add  `"stdEsm": false` to your [Quokka config](https://quokkajs.com/docs/configuration.html).

**Comment by ksbalajee** [comment]
Thanks @ArtemGovorov. It worked, and I'm currently using angularjs and I get the error `angular not defined`. Do I need to configure any plugin ?

**Comment by ArtemGovorov** [comment]
Quokka runs in node, so for browser stuff you need to 
- use [Quokka jsdom plugin](https://github.com/wallabyjs/jsdom-quokka-plugin),
- provide/load all framework globals, such as `angular`. You may search for/create a plugin for it yourself, see for example [this jQuery plugin](https://github.com/Dacrol/quokka-jquery-loader) for Quokka.

**Comment by loganpowell** [comment]
I just ran into this same problem very recently. Quokka was working as expected with ESM module (`import * as x from...`) up until a few days ago. I just tried to uninstall and reinstall the plugin for VSCode, but the problem persists. Was there a recent update? Don't know why it's not working for me today.

**Comment by smcenlly** [comment]
@loganpowell - we don't believe that anything has changed recently that would have broken this for you. Are you able to create a new issue and provide us with a sample of your code that is no longer working? We'd be happy to try it with the latest and previous versions to confirm whether there's an issue.

**Comment by loganpowell** [comment]
I am AFC today, but will put together a simple example tomorrow. Thank you for the quick response!

**Comment by loganpowell** [comment]
When I start a new project, the imports are working. It seems as though it has something to do with my `package.json` settings, i.e., when I set the `"type": "module"` quokka no likey... Is this documented somewhere that I missed? Thank you again for following up.

**Comment by smcenlly** [comment]
It looks like your problem is caused by the version of `esm` that we're using for module imports and [this issue](https://github.com/standard-things/esm/issues/784). We're investigating/testing upgrading to a later version that fixes this issue. We should have an update for you within the next day.

**Comment by loganpowell** [comment]
Sweet!

**Comment by smcenlly** [comment]
@loganpowell - We spent yesterday looking at upgrading the `esm` package that we're using but it looks like there are some regressions (at least in the way that we use it) so we are still investigating how to fix. For better visibility and tracking, I have created a new issue https://github.com/wallabyjs/quokka/issues/431 as the root cause is different to this issue (this issue was caused by node version being < node v6.x).

**Comment by dev-ethanjohn** [comment]
Hi, I think there is a problem with the index.js file under this path @babel\parser\lib\index.js I find was causing the issue.

c:\Users\Ethan\.vscode\extensions\wallabyjs.quokka-vscode-1.0.569\dist\wallaby\node_modules\@babel\parser\lib\index.js:2672 
    def test_pythontypes(self): 
    ^^^ 
 
SyntaxError: Unexpected identifier 'def' 
    at internalCompileFunction (node:internal/vm:73:18) 
    at wrapSafe (node:internal/modules/cjs/loader:1153:20) 
    at Module._compile (node:internal/modules/cjs/loader:1205:27) 
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10) 
    at Module.load (node:internal/modules/cjs/loader:1091:32) 
    at Module._load (node:internal/modules/cjs/loader:938:12) 
    at Module.require (node:internal/modules/cjs/loader:1115:19) 
    at require (node:internal/modules/helpers:130:18) 
    at Module._compile (node:internal/modules/cjs/loader:1241:14) 
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10) 
    at Module.load (node:internal/modules/cjs/loader:1091:32) 
    at Module._load (node:internal/modules/cjs/loader:938:12) 
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) 
    at node:internal/main/run_main_module:23:47
