### ISSUE TITLE
Show multiple logs full data.

### ISSUE THREAD

**Issue by DarrylD** [wallabyjs/quokka#21]
Let's say I'm iterating over an array of objects.
```

const doStuff = (obj) => {
  const newObj = obj

  console.log(newObj) // on hover of newObj, would be nice to not have the objects shortened
  
  return newObj
}

someArray.map( obj => doStuff(obj))

```

In the tooltip, the  `newObj`'s are shorten using `...`'s in the front and back. Anyway to show all the data and just scroll? It's currently cutting off all the data.

Amazing project BTW. Crazy potential.

### Code editor version

Visual Studio Code v1.10.02

### OS name and version
OSX

**Comment by DarrylD** [comment]
Here is what I'm referring to 
![logs](https://cloud.githubusercontent.com/assets/1310383/24222380/d9f3723a-0f1f-11e7-86e2-e69956889004.gif)

**Comment by ArtemGovorov** [comment]
> Amazing project BTW. Crazy potential.

Thanks!

This is by design, we tried and putting too much info in the tooltip just doesn't look good. The full output can be inspected (and even searched) in the quokka console output channel, that is much more suitable for displaying larger amounts of data.

**Comment by DarrylD** [comment]
> This is by design, we tried and putting too much info in the tooltip just doesn't look good. 

Is it? Plenty of documentation are in the tooltips by default from typescript/flow/etc... Showing the object structure but, cutting off the long values should be fine, right?

> The full output can be inspected (and even searched) in the quokka console output channel, that is much more suitable for displaying larger amounts of data.

Can it be an option to show it? 

The problem with the output is that I need to go search the dozens of logs and hope to find the data for this particular object. Hovering and seeing the data is the big sell on this concept IMO.

In my case, testing streams with rxjs and works perfect outside of not showing all the data.

**Comment by ArtemGovorov** [comment]
I see what you mean, makes perfect sense. We'll try again to see if tooltips are suitable for it, if not, then we'll consider adding some kind mechanism to quickly view the full output for a specific line.

**Comment by DarrylD** [comment]
Sounds great!

**Comment by ArtemGovorov** [comment]
We have played around and managed to make it look inside tooltips (in our earlier experiments we couldn't preserve line formatting). In the just published v1.0.16 it looks like this:

![vsc](https://cloud.githubusercontent.com/assets/979966/24319402/75ea6be2-1166-11e7-90eb-bbbac2aa2e4e.gif)

**Comment by zerocity** [comment]
Hi,

will this feature also in wallaby ? in the current version of wallaby 1.0.55 it is not present 
(vscode Version 1.14.2 (1.14.2))

**Comment by ArtemGovorov** [comment]
@zerocity Hi, the inline output with multiple values is in wallaby, but not the values in the tooltip feature.
