### ISSUE TITLE
​​/bin/sh: npm: command not found​​

### ISSUE THREAD

**Issue by diegovdc** [wallabyjs/quokka#215]
### Issue description or question
Quokka does not find `npm` when attempting to install a package for Quokka file.

I am using nvm, so `which npm` returns this: `/Users/user/.nvm/versions/node/v8.11.1/bin/npm`

### Quokka.js Console Output

```
​​Command failed: npm install tap-logger​​
​​/bin/sh: npm: command not found​​
```

### Code editor version

Visual Studio Code v1.23.1

### OS name and version
OSX 10.11.6

**Comment by ArtemGovorov** [comment]
You [may configure your path to `npm`](https://quokkajs.com/docs/index.html#modules) by adding the setting value:
```
{
    "installPackageCommand": "/Users/user/.nvm/versions/node/v8.11.1/bin/npm install {packageName}"
}
```

**Comment by diegovdc** [comment]
Thanks, now I am getting this error:
```
​​Command failed: /Users/user/.nvm/versions/node/v8.11.1/bin/npm install tap-logger​​
​​env: node: No such file or directory​​
​​​​```

My config looks like this:
```
{
    "plugins":["jsdom-quokka-plugin"],
    "node":"/Users/user/.nvm/versions/node/v8.11.1/bin/node",
    "installPackageCommand": "/Users/user/.nvm/versions/node/v8.11.1/bin/npm install {packageName}",
    "pro":true
}
```

**Comment by ArtemGovorov** [comment]
It probably means that the `/Users/user/.nvm/versions/node/v8.11.1/bin/npm` path doesn't exist. Please double check the path (`user` part in it should be your user name).

**Comment by diegovdc** [comment]
I can confirm the path is fine, which I am copying directly from the terminal log for `which npm`

**Comment by lgandecki** [comment]
I have the same problem on a brand new mac:

```javascript
{"node":"/Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/node","pro":true,
  "installPackageCommand": "/Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/npm install {packageName}"
}
```


```
➜  knowledge-graph-visualization git:(master) ✗ ls -al /Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/node
-rwxr-xr-x  1 lukaszgandecki  staff  38764112 Aug  1 19:55 /Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/node
➜  knowledge-graph-visualization git:(master) ✗ ls -al /Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/npm
lrwxr-xr-x  1 lukaszgandecki  staff  38 Aug  1 19:55 /Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

```
Command failed: /Users/lukaszgandecki/.nvm/versions/node/v10.8.0/bin/npm install expect
env: node: No such file or directory
```

I never even had to play around with the quokka config before.

**Comment by ArtemGovorov** [comment]
@lgandecki Looks like it may be an [issue with your `nvm`](https://github.com/creationix/nvm/issues/1702).
Try `nvm alias default node`, or putting node path in your `PATH`.

**Comment by lgandecki** [comment]
hard to say - windows-like fix helped (restart) ;-)

thanks!

**Comment by lgandecki** [comment]
I think it might have something to do with the fact that I changed the default shell, but Mac somehow still used the previous one in web storm

**Comment by ByScripts** [comment]
I had the same problem on macOS. Node is installed via `rtx`

So my Node path is: `/Users/byscripts/.local/share/rtx/installs/nodejs/18.14.0/bin/node`

My npm path is: `/Users/thierry/.local/share/rtx/installs/nodejs/18.14.0/bin/npm`

I solved the issue with this configuration:
```json
{
 "pro": true,
 "node": "/Users/byscripts/.local/share/rtx/installs/nodejs/18.14.0/bin/node",
 "installPackageCommand": "/Users/byscripts/.local/share/rtx/installs/nodejs/18.14.0/bin/node /Users/thierry/.local/share/rtx/installs/nodejs/18.14.0/bin/npm install {packageName}"
}
```
