### ISSUE TITLE
Support for the experimental syntax 'classProperties'

### ISSUE THREAD

**Issue by sidati** [wallabyjs/quokka#216]
Hi, I got this error: 
> Support for the experimental syntax 'classProperties' isn't currently enabled

so my question where i can enable `classProperties` option ?
thanks in advance

**Comment by ArtemGovorov** [comment]
This is not a message from Quokka source, looks like a message from Babel. Please check if you have installed and configured the corresponding Babel plugin: https://babeljs.io/docs/plugins/transform-class-properties/.

If you get stuck, please create a sample repo demonstrating the issue, and describe the steps to reproduce it, we are happy to take a look.

**Comment by sidati** [comment]
thanks @ArtemGovorov for you reply, im using `CRA` so i have no control on configuration but im using `esLint/Prettier` and i got no syntax/compiling errors, that why im asking if there is a separate **quokka** config that i need to install any plugins for it :smile: 

thanks again

**Comment by ArtemGovorov** [comment]
@sidati 
> im using CRA so i have no control on configuration

In this case you may configure Quokka to use [specific Babel plugins](https://quokkajs.com/docs/configuration.html#overriding-babel-settings). You may place the config [Quokka configuration](https://quokkajs.com/docs/configuration.html).

**Comment by sidati** [comment]
@ArtemGovorov ,

Can you please clarify, Do i need to `yarn add` theses plugins/packages in the global `/home/username/.quokka` or into my project root folder ?? since its used only by quokka

**Comment by ArtemGovorov** [comment]
These babel plugins (transform class properties specifically) should already be in your project's `node_modules` because you are uisng CRA and CRA installs them.

**Comment by sidati** [comment]
I know thats why im confused because **eslint** will trigger the same error if they aren't there, Is it possible that it may be a conflicts with the global quokka config ??

**Comment by ArtemGovorov** [comment]
What conflicts? Have you configured Quokka to use [specific Babel plugins as described here](https://quokkajs.com/docs/configuration.html#overriding-babel-settings)?

**Comment by ArtemGovorov** [comment]
All you should need for CRA is one preset configured in Quokka: https://github.com/wallabyjs/quokka/issues/31#issuecomment-292053881 (in any of Quokka configuration - global, package.json or inline).

**Comment by sidati** [comment]
Nice :smile: , now where i need to install that package `babel-preset-react-app`, in my project folder or here => `/home/username/.quokka` ??

**Comment by ArtemGovorov** [comment]
As I have mentioned - you should already have it in your project's `node_modules`, so don't need to install it.

**Comment by sidati** [comment]
I really have no idea whats going on anymore :cry:, this shows up after : 
```json
...
  "private": true,
  "quokka": {
    "babel": {
      "presets": [
        "react-app"
      ]
    }
  },
...
```

> ​​Failed to run compilers on src/components/app.jsx, Error: Plugin/Preset files are not allowed to export objects, only functions.

**Comment by ArtemGovorov** [comment]
Looks like you may be mixing babel 6 and babel 7 beta somehow. You need to use the same version presets as your installed babel version.

I have just tried to generate a project using current CRA 1.5.2 version, added 
```
  "quokka": {
    "babel": {
      "presets": [
        "react-app"
      ]
    }
  },
```
to `package.json`, and Quokka is running fine on the CRA files:

<img width="716" alt="screen shot 2018-06-07 at 11 50 54 am" src="https://user-images.githubusercontent.com/979966/41073971-169a9f30-6a49-11e8-955b-7e69394a697c.png">

Try deleting `/home/username/.quokka/node_modules` to see if it helps. If not, please share a sample repo where we could reproduce the issue.
