### ISSUE TITLE
Unable to use Quokka with React

### ISSUE THREAD

**Issue by SeanDez** [wallabyjs/quokka#218]
### Issue description or question

My Phpstorm version is 2018.1.5. On a trial run I tried to test a simple console.log and immediately received an error

```
const test = 9;
console.log(test);
```

```
Quokka #1 (node: v8.10.0)

Failed to parse src/App.js, TypeError: this[type] is not a function
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

screenshot: [https://i.imgur.com/37IhvxI.jpg](https://i.imgur.com/37IhvxI.jpg)

This is within a create-react-app project, default configuration. Therefore I don't believe the app config is the source of the issue.

I'm using Lubuntu 18.04

**Comment by SeanDez** [comment]
More information:

Specify what version of Quokka plugin is installed,
**Quokka version 1.0.95**

Restart your IDE
**done**

Try starting Quokka and provide an extract from your idea.log (starting from the moment/time when you restarted the IDE and started Quokka). You may open the log file by using Help - Show Log menu in the Phpstorm IDE.

[phpstorm_log_jun_6_2018.txt](https://github.com/wallabyjs/quokka/files/2102394/phpstorm_log_jun_6_2018.txt)

**Comment by SeanDez** [comment]
I created a new .es6 and .js scratch file. Both files were tested and **worked successfully** with Quokka. Therefore there is something wrong with Quokka's interaction with my current create-react-app project

**Comment by SeanDez** [comment]
This component is a child component of App.js (from post #1). You can see it encounters the same problem on plugin start:

Quokka #2 (node: v8.10.0)

```
Failed to parse src/components/body_section/ProductPageRequest.js, TypeError: this[type] is not a function
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by SeanDez** [comment]
I haven't ejected / don't have access to .babel rc. Here is package.json:

```
{
  "name": "free_amazon_deal_notifier",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-scripts": "1.1.4",
    "semantic-ui-css": "^2.3.1",
    "semantic-ui-react": "^0.81.1",
    "styled-components": "^3.3.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.4",
    "react-test-renderer": "^16.4.0",
    "sinon": "^6.0.0"
  }
}
```

**Comment by SeanDez** [comment]
I created a fresh create-react-app install. Upon attempting to start Quokka in app.js I saw this:

```
Quokka #1 (node: v8.10.0)

file:///home/owner/PhpstormProjects/cra_test_area/src/App.js:9
            <div className='App'>
            ^

SyntaxError: Unexpected token
```

**Comment by SeanDez** [comment]
Here is my ~/.quokka/config.json:

`{"pro":true}`

package.json in the same directory is just an empty `{}`

**Comment by ArtemGovorov** [comment]
To run Quokka on `create-react-app`, you need to configure it to use the `react-app` babel preset. To [configure babel for the quokka](https://quokkajs.com/docs/configuration.html#overriding-babel-settings) you may add the configuration to [your `package.json` or to the quokka global config](https://quokkajs.com/docs/configuration.html)), or even inline in your source code:


```javascript
({
    babel: {
        presets: ['react-app']
    }
})

...
```

**Comment by SeanDez** [comment]
package.json updated lines:

```
"name": "free_amazon_deal_notifier",
  "quokka": {
    "babel": true
  },
  "version": "0.1.0",
```

Quokka seems to have the same issue:

```
SyntaxError: src/components/body_section/AlertSetup.js: Unexpected token (17:15)
  15 |     }
  16 | 
> 17 |     open_modal = () => this.setState({modal_open : true});
     |                ^
```

**Comment by SeanDez** [comment]
Never mind, issue seems resolved after I copied the preset you showed above:

```
  "quokka": {
    "babel": {
      "presets": ["react-app"]
    }
  },
```

**Comment by SeanDez** [comment]
I notice Quokka works for about 10 minutes and then I have to click on a notification link, then restart Quokka which loses all the code coverage. I assume this is a trial restriction? Is there any way not to lose the code coverage information each time?

**Comment by ArtemGovorov** [comment]
Yes, it is trial limitation. You may restart your editor to get another trial session.
