### ISSUE TITLE
​​​​Quokka #2 (node: v9.10.1)​​​​ ​​​​ ​​Unexpected token (34:19)​​   at ​​​Object.Module._extensions..js​​​ ​module.js:660​

### ISSUE THREAD

**Issue by arryanggaputra** [wallabyjs/quokka#221]
### Sample code

```javascript
import * as action from "./action";
import * as service from "./service";
import * as store from "./store";

export { action, service, store };
```

### Quokka.js Console Output

```
​​​​Quokka #2 (node: v9.10.1)​​​​
​​​​
​​Unexpected token (34:19)​​
  at ​​​Object.Module._extensions..js​​​ ​module.js:660​

```

### Code editor version

Visual Studio Code Version 1.24.1 (1.24.1)

### OS name and version

OSX High Sierra

**Comment by ArtemGovorov** [comment]
Looks like there may be some syntax used in your `action`/`service`/`store` files that isn't supported by node. Try this:

- check that the following code works for you:
```js
import * as fs from "fs";

fs
```
- if it does, then you'll need to configure Babel for Quokka as [described here in the docs](https://quokkajs.com/docs/configuration.html#babel).

**Comment by arryanggaputra** [comment]
Is this support for react-native?

**Comment by ArtemGovorov** [comment]
Quokka runs in node, so if your react-native app can run in node, then yes.
