### ISSUE TITLE
Select workspace not working to get local files

### ISSUE THREAD

**Issue by unional** [wallabyjs/quokka#224]
### Issue description or question
![image](https://user-images.githubusercontent.com/3254987/42667339-ce87f058-85ff-11e8-9401-c90e814bde72.png)
Selected second one
![image](https://user-images.githubusercontent.com/3254987/42667358-ec01f368-85ff-11e8-903c-1686108a4090.png)
The local path still follows the first project ('main')

### Code editor version

Visual Studio Code v1.24.1

### OS name and version

Windows Server 2016

**Comment by unional** [comment]
The good thing is the code actually works.
But since tsserver does not have the correct reference, there is no intellisense for you :(

**Comment by ArtemGovorov** [comment]
Quokka `Select workspace` command is just setting the working directory for Quokka, it doesn't (can't) affect VS Code provided services, such as intellisense. So, correct me if I'm wrong, but the issue seem to be not related to Quokka.

**Comment by unional** [comment]
You are correct. But this makes Quokka much less useful as it cannot get the references correctly (by intellisense).

In the example above, the file is assumed to be under the `main` project, so I think there is a way to let vscode knows when a new file is created, what is the assumed current directory.

VSCode may have a param for it when creating new file, or this would be a good api feature request. 🌷

**Comment by ArtemGovorov** [comment]
Unfortunately VS Code doesn't have a parameter to set a workspace when creating a new file:

```
openTextDocument(options?: {content: string, language: string}): Thenable<TextDocument>
```

> this would be a good api feature request. 

Good point, [created one](https://github.com/Microsoft/vscode/issues/54227).
