### ISSUE TITLE
quokka doesn't work with jsx

### ISSUE THREAD

**Issue by YahngSungho** [wallabyjs/quokka#227]
### Sample code

```javascript
import { Component } from 'react'

class App extends Component {
  render () {
    return (
      <div>
      </div>
    )
  }
```

also my package.json file
```
  "quokka": {
    "babel": true,
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  }
```

### Quokka.js Console Output

```
Quokka #1 (node: v8.9.1)

file:///C:/Users/user/Dropbox/PROJECTS/LearnObit/App/test.js:7
            <div>
            ^

SyntaxError: Unexpected token

```

### Code editor version

Webstorm

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
Looks like there's no babel configuration in the root of your project, so `babel: true` is not enough. If you are using `create-react-app`, this should help: https://github.com/wallabyjs/quokka/issues/218#issuecomment-397485386:

```diff
  "quokka": {
-   "babel": true,
+   "babel": {
+     "presets": ["react-app"]
+    }
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  }
```

**Comment by YahngSungho** [comment]
It still does not work.

Everything in my package.json is like this

```
{
  "name": "App",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "neutrino build",
    "start": "neutrino start",
    "lint": "neutrino lint",
    "test": "neutrino test",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-hot-loader": "^4.3.3"
  },
  "devDependencies": {
    "@neutrinojs/jest": "^8.3.0",
    "@neutrinojs/react": "^8.3.0",
    "@neutrinojs/standardjs": "^8.3.0",
    "@storybook/addon-actions": "^3.4.8",
    "@storybook/addon-knobs": "^3.4.8",
    "@storybook/addon-links": "^3.4.8",
    "@storybook/addons": "^3.4.8",
    "@storybook/react": "^3.4.8",
    "babel-core": "^6.26.3",
    "babel-runtime": "^6.26.0",
    "jsdom-quokka-plugin": "^1.0.13",
    "neutrino": "^8.3.0"
  },
  "quokka": {
    "babel": {
      "presets": ["react-app"]
    },
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  }
}

```

I also tried "presets": ["react"] as well as "presets": ["react-app"] since there is a babel-preset-react in my node_modules folder instead of babel-preset-react-app. But it still did not work.

**Comment by smoothness** [comment]
Same thing here, I upgraded to Pro some months ago and still haven't even got to use it, I mostly work with React projects and I have the same error, Quokka not supporting JSX.
Did someone already fixed this issue?

**Comment by ArtemGovorov** [comment]
@smoothness Could you please provide your
- package.json,
- Quokka config,
- error message?

**Comment by ArtemGovorov** [comment]
> Npm throws the following error:

It doesn't look like Quokka specific error indeed.

Are you using Babel 6 or Babel 7? It's it's the latter, then you need the [`@babel/preset-react` package ](https://www.npmjs.com/package/@babel/preset-react) instead.

**Comment by ArtemGovorov** [comment]
Actually, disregard my previous message.

> Npm throws the following error:

This doesn't seem to be Quokka related error.

**Comment by smoothness** [comment]
> Actually, disregard my previous message.
> 
> > Npm throws the following error:
> 
> This doesn't seem to be Quokka related error.

Yes it is not, thanks for your help @ArtemGovorov
