### ISSUE TITLE
quokka doesn't work with jsx, yet

### ISSUE THREAD

**Issue by YahngSungho** [wallabyjs/quokka#228]
### Sample code

```javascript
import { Component } from 'react'

class App extends Component {
  render () {
    return (
      <div>
      </div>
    )
  }
```

### Quokka.js Console Output

```
Quokka #1 (node: v8.9.1)

file:///C:/Users/user/Dropbox/PROJECTS/LearnObit/App/test.js:7
            <div>
            ^

SyntaxError: Unexpected token

```

### Code editor version

Webstorm

### OS name and version

Windows 7

**Comment by YahngSungho** [comment]
You told me to try "presets": ["react-app"], but it still does not work.

Everything in my package.json is like this

```
{
  "name": "App",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "neutrino build",
    "start": "neutrino start",
    "lint": "neutrino lint",
    "test": "neutrino test",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-hot-loader": "^4.3.3"
  },
  "devDependencies": {
    "@neutrinojs/jest": "^8.3.0",
    "@neutrinojs/react": "^8.3.0",
    "@neutrinojs/standardjs": "^8.3.0",
    "@storybook/addon-actions": "^3.4.8",
    "@storybook/addon-knobs": "^3.4.8",
    "@storybook/addon-links": "^3.4.8",
    "@storybook/addons": "^3.4.8",
    "@storybook/react": "^3.4.8",
    "babel-core": "^6.26.3",
    "babel-runtime": "^6.26.0",
    "jsdom-quokka-plugin": "^1.0.13",
    "neutrino": "^8.3.0"
  },
  "quokka": {
    "babel": {
      "presets": ["react-app"]
    },
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  }
}

```

I also tried "presets": ["react"] as well as "presets": ["react-app"] since there is a babel-preset-react in my node_modules folder instead of babel-preset-react-app. But it still did not work.

**Comment by ArtemGovorov** [comment]
> I also tried "presets": ["react"] as well as "presets": ["react-app"] since there is a babel-preset-react in my node_modules folder instead of babel-preset-react-app. But it still did not work.

So it's not `create-react-app` that you have. Could you please setup and share an example repo where I could reproduce the issue? Happy to take a look.

**Comment by YahngSungho** [comment]
Sorry for late reply

Can you check with this repo? 
https://github.com/YahngSungho/fefdfsfdwefwfdfs

**Comment by ArtemGovorov** [comment]
@YahngSungho Thanks for providing the repo. I have sent you the [PR to make it work](https://github.com/YahngSungho/fefdfsfdwefwfdfs/pull/1). Basically, all you need is to replace `react-app` preset with the `env` preset in your Quokka config.

**Comment by dashndash** [comment]
@ArtemGovorov  Can you please help me with this? https://github.com/wallabyjs/quokka/issues/393

**Comment by HenriqueOmena** [comment]
Hello i already buy a license but into react i aways get the same error im passing in package.json in a project with create-react-app this params 

` "quokka": {
    "babel": {
      "presets": [
        "react-app"
      ]
    },
    "stdEsm": false,
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  },`

but all i get is 

> ​​​​Quokka 'input-text.component.jsx' (node: v12.13.1, babel: v7.6.0, plugins: jsdom-quokka-plugin)​​​​
Test run failure: file src/components/form/input-text/input-text.component.jsx has invalid syntax 


can u help me ? do u need something to get some confirmation about my order ? i buy recently

**Comment by HenriqueOmena** [comment]
by the way i try with ur example in [Create-react-app](https://github.com/wallabyjs/quokka-create-react-app) but with modification, i aways get grey squares inside the component, how fix that ? for example i should get the resulta in my function teste() //?

[Image about the code test](https://ibb.co/s1R92YL)

**Comment by smcenlly** [comment]
@HenriqueOmena - the reason that the squares are gray is that the code is never actually being executed. You are defining a function, exporting it, but it is not being called, (which is why the squares are gray).

**Comment by HenriqueOmena** [comment]
@smcenlly good mornig, that make sense but we working with component and we neve call that inside the same file, has another way to test functions inside functions components ?

**Comment by HenriqueOmena** [comment]
@smcenlly now its working in my main project but wuold be very nice if we could put something to ignore some function with some alias like that
 for example im components like that we could add //ignore

`function InputText() {
  const teste = () => {
    return 'testing';
  };

  let a = 10239017398;
  let b = 1789312;

  let sum = a + b;
  sum;

  return <div className="input-text-component"> asd </div>;
}

InputText(); //we can cancel that`

and igonoring that we dont need to call InputText() or maybe add a parameter in config to ignore functions exported in react, whats you guess ?

**Comment by smcenlly** [comment]
If I understand correctly, you want to always have your component execute when using Quokka, but not at runtime? This is a bit of a hack, but would give you what you want:

```
function InputText() {
  const teste = () => {
    return 'testing';
  };

  let a = 10239017398;
  let b = 1789312;

  let sum = a + b;
  sum;

  return 10;
}

1 //? InputText()
```

The live value comment will output "10" and will only run when Quokka is run on your file.

Having said that, we don't think it would be a nice thing to corrupt your production code base like that.
