### ISSUE TITLE
Needed to install node globally - Object has no method 'homedir'

### ISSUE THREAD

**Issue by orta** [wallabyjs/quokka#23]
### Issue description or question

Hey there, I started teaching Js. newbies with Quokka, one of the first things I found out was that you need to actually have an install of node on the system ( e.g. run the installer of https://nodejs.org ) or Quokka won't launch.

I don't consider this a bug/problem, but when you try run it without node installed globally then you get an error in the console:

### Quokka.js Console Output

```
TypeError: Object # has no method 'homedir' 
```

Which I couldn't find an issue for (nor a simple search result) so it's probably worth seeing if you can catch the case and recommend downloading node etc.

### Code editor version

Visual Studio Code v1.?

### OS name and version

OSX: 10.11

**Comment by ArtemGovorov** [comment]
Hmm, we have some code in place to nicely handle the scenario, here's what I see if I don't have node installed:

![screen shot 2017-03-28 at 5 35 09 pm](https://cloud.githubusercontent.com/assets/979966/24393856/2168a740-13dd-11e7-97d7-310e9bd908da.png)

What version of quokka.js extension are you using?

**Comment by orta** [comment]
Interesting, it was definitely the latest version (we installed it then and there last night ) and I don't really have access to the computer anymore in order to give you some more debugging info :(

**Comment by ArtemGovorov** [comment]
Actually, from the error message it looks like the node was starting, but apparently you have had some very old version of node (like 0.10.x) installed on that machine, so that this code `require('os').homedir()` is failing.

We have just added some code to handle the scenario, will be released later today.

**Comment by orta** [comment]
Thanks for the debugging! 👍

**Comment by ArtemGovorov** [comment]
Thank you for the report :)
