### ISSUE TITLE
Cannot read property “style” of null

### ISSUE THREAD

**Issue by nick-smyth** [wallabyjs/quokka#230]
When I try to run :
Element.style.color 
I get this error. 
I have jsdom globally installed and can’t figure out why this is happening. 
The code is correct because it is working in my browser. Please help

**Comment by ArtemGovorov** [comment]
Could you please paste the full output from Quokka console?

**Comment by ArtemGovorov** [comment]
The output I'm requesting should also contain the list of installed Quokka plugins. So I'm wondering if [Quokka jsdom plugin](https://github.com/wallabyjs/jsdom-quokka-plugin) is installed, because it needs to be in order to run browser code. 

Also please share the full code that you are trying to run. Running only `Element.style.color` doesn't make sense, because `Element` is a function and running this code in browser results in:

<img width="500" alt="screen shot 2018-08-02 at 11 27 41 am" src="https://user-images.githubusercontent.com/979966/43557253-1cfe5dd8-9647-11e8-97ee-33c1c5ba42ca.png">

**Comment by nick-smyth** [comment]
I meant for element. To represent the variable I’m calling .style on. But I will post these things in a few. I know that I do have jsdom installed though

**Comment by nick-smyth** [comment]
<img width="841" alt="screen shot 2018-08-01 at 7 42 22 pm" src="https://user-images.githubusercontent.com/35778812/43559563-61659628-95c3-11e8-9e1e-74b41ac99853.png">
<img width="399" alt="screen shot 2018-08-01 at 7 42 32 pm" src="https://user-images.githubusercontent.com/35778812/43559564-618ae4b4-95c3-11e8-9207-42d8197a5e28.png">
<img width="610" alt="screen shot 2018-08-01 at 7 42 45 pm" src="https://user-images.githubusercontent.com/35778812/43559565-61ae6a6a-95c3-11e8-99ed-42d150407c60.png">

**Comment by nick-smyth** [comment]
<img width="841" alt="screen shot 2018-08-01 at 7 42 22 pm" src="https://user-images.githubusercontent.com/35778812/43559610-8a1032fe-95c3-11e8-9c60-51c8c4b8a68d.png">
<img width="399" alt="screen shot 2018-08-01 at 7 42 32 pm" src="https://user-images.githubusercontent.com/35778812/43559611-8a2aef54-95c3-11e8-9df9-7309578475cd.png">
<img width="665" alt="screen shot 2018-08-01 at 7 45 37 pm" src="https://user-images.githubusercontent.com/35778812/43559612-8a43b3d6-95c3-11e8-9e96-bf123b528da8.png">
<img width="610" alt="screen shot 2018-08-01 at 7 42 45 pm" src="https://user-images.githubusercontent.com/35778812/43559613-8a601026-95c3-11e8-9236-fae5bb5c1436.png">

**Comment by ArtemGovorov** [comment]
@nick-smyth Thanks for sharing the details. 
Looks like the HTML file is not loaded by jsdom Quokka plugin. You may specify the path to the HTML file in your [`jsdom-quokka-plugin` configuration](https://github.com/wallabyjs/jsdom-quokka-plugin#configuration), so that `jsdom` loads it.

**Comment by nick-smyth** [comment]
Ok, is there any way to globally do this? So i dont have to do it every single time?

**Comment by ArtemGovorov** [comment]
@nick-smyth Yes, sure, you may use Quokka global config file for this: https://quokkajs.com/docs/configuration.html#global-config-file.

**Comment by nick-smyth** [comment]
Ok, what should I put in that in order to make it work?
Also I really appreciate how helpful you've been with this.

**Comment by ArtemGovorov** [comment]
@nick-smyth Hmm, actually putting a HTML file path into your global config may not be a good idea. You may want to run Quokka for different HTML files, so package.jso or inline configuration is a better place for settings like this.

> what should I put in that in order to make it work?

You need to put your HTML file path to `jsdom.file` setting as described at https://github.com/wallabyjs/jsdom-quokka-plugin#configuration. For example, if you are running Quokka scratch file like

```js
const test = document.querySelector('.test')
test.style.border = ...
```

and `test` is a class name of a `div` element in the `index.html` file located in the root of your project, then you may add the following inline config into your Quokka file:

```
({
    "jsdom": {
        "file": "./index.html"
    }
})
```

Here's an example:

<img width="549" alt="screen shot 2018-08-02 at 1 27 37 pm" src="https://user-images.githubusercontent.com/979966/43560889-e27a3252-9657-11e8-8247-7422614ddacb.png">
