### ISSUE TITLE
Inline errors don't work while viewing a file outside of the current open folder

### ISSUE THREAD

**Issue by Faustxx** [wallabyjs/quokka#231]
### Issue description or question
Inline errors don't work and the little square to the left of the line number is green when viewing a file outside of the current open folder. Quokka output correctly identifies the error, though. Inline logging does work. 

### Sample code

```javascript
const test = {
	notExists
}
```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.11.3)​​​​
​​​​
​​notExists is not defined​​
  at ​​​Object.<anonymous>​​​ ​quokka_fake_path/test.js:2​
```

### Code editor version

Visual Studio Code v1.25.1

### OS name and version

Windows 8.1

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in the latest v1.0.136.
