### ISSUE TITLE
Quokka not working

### ISSUE THREAD

**Issue by osuulola** [wallabyjs/quokka#232]
### Issue description or question
reports that quokka is not working

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.25.1

### OS name and version

Windows 7 32 bits

**Comment by ArtemGovorov** [comment]
Could you please provide some more details:

- Can you see Quokka commands in the editor command palette?
- When you run `Create New JavaScript File` Quokka command, do you see Quokka panel being opened?
- Are you getting any error messages from Quokka?

**Comment by svipben** [comment]
Same here for macOS.

`Failed to run preprocessors on quokka.ts, Error: ENOENT: no such file or directory, open './quokka.ts'​​`

Same goes for the JS.

VS Code: 1.26.1
Quokka.js: 1.0.137

**Comment by ArtemGovorov** [comment]
@svipben This doesn't seem to be the same issue. The one in your report had been fixed: https://github.com/wallabyjs/quokka/issues/234.
