### ISSUE TITLE
Quokka start on current file goes in error

### ISSUE THREAD

**Issue by tomma5o** [wallabyjs/quokka#233]
### Issue description
Hi,
When I start quokka **in the current file** it shows me an error (output below),
probably the error is because quokka try to find the file in that path in `../../` but the correct path is `~/Desktop`.

My environment is:
I'm in my project located in `~/Document/Foo/Bar` and I've opened a file (located in the desktop)
and I try to start quokka in the last one.

**Update**: When I open a new window of VScode (so the integrated terminal are in the root) start correctly

Hope this helped 👍 

### Quokka.js Console Output

```
Error: ENOENT: no such file or directory, open '../../Desktop/calcgridwhitespaces.js'​
​​    at Object.fs.openSync (fs.js:667:18)​​
​​    at Object.fs.writeFileSync (fs.js:1326:33)​​
​​    at WebSocketServer.emit (events.js:127:13)​​
​​    at Server.emit (events.js:127:13)​​
​​    at onParserExecuteCommon (_http_server.js:531:14)​​
​​    at onParserExecute (_http_server.js:479:3)​​
```

### Code editor version

Visual Studio Code v1.26

### OS name and version

OSX v10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for the report.  The issue is fixed and the fix is published in the latest version 1.0.137.
