### ISSUE TITLE
Copying code from the Output panel in VSC, copies invisible characters too

### ISSUE THREAD

**Issue by garyking** [wallabyjs/quokka#235]
### Issue description or question

When I copy some code from the Output panel in VSC while using Quokka, invisible characters are copied as well. They exist at the end fo each line; about 3 **U+200B** characters are there. So when I paste this code into my file, it won't compile, because the compiler complains about the invisible characters. They can be hard to track down if you aren't aware of them.

I originally filed the bug at VSC [here](https://github.com/Microsoft/vscode/issues/56533).

### Code editor version

VS Code 1.26.0

### OS name and version

OS X 10.13.5

**Comment by ArtemGovorov** [comment]
We are indeed using invisible spaces in the output to be highlight the output. Please subscribe for the issue here: https://github.com/wallabyjs/quokka/issues/235.
