### ISSUE TITLE
Can't type in Quokka pane in WebStorm

### ISSUE THREAD

**Issue by fr0** [wallabyjs/quokka#236]
### Issue description or question

I installed Quokka into WebStorm (2018.2, OSX).
I then bring up the Quokka pane, add a new scratch window (TypeScript) and it has a simple prompt:
```
Quokka #2 (node: v8.9.4, TypeScript: v2.7.2)
```
However, I can't type any characters into the window.

**Comment by ArtemGovorov** [comment]
If I understand the issue correctly, this is by design. You are not supposed to type into the Quokka window, it is read-only. The window should display code execution results of the you type into the editor window.
