### ISSUE TITLE
Quokka cannot find the tsconfig.json in monorepo

### ISSUE THREAD

**Issue by andrew-w-ross** [wallabyjs/quokka#237]
### Issue description or question

Given the following file structure
```
o
|-- packageA
|   |-- src
|   |   `-- fileA.ts
|   `-- tsconfig.json
|-- packageB
|   |-- fileB.ts
|   `-- tsconfig.json
`-- fileC.ts
```

Quokka should attempt to find the closest  parent or sibling `tsconfig.json`  file for typescript files.
If quokka is invoked on `fileA.ts` it should use `tsconfig.json` in `packageA`.

If quokka is invoked on `fileC.ts` it seems reasonable for it to not use a tsconfig.json because of the ambiguity.
Currently it just seems to find the `tsconfig.json` in the root of the folder opened with the editor.

In it's current state quokka is painful in a typescript monorepo project.

### Quokka.js Console Output
```
​​​​Quokka #1 (node: v10.7.0, TypeScript: v3.0.1)​​​​
​​​​
​​Cannot find module '~/constants'​​
  at ​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:581​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:507​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:20​
  at ​​​Object.<anonymous>​​​ ​packages/server/src/utils/connection.ts:7​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:689​
​​​​​​
​​​Couldn't find tsconfig.json. tsconfig-paths will be skipped​​​
```
### Code editor version

Visual Studio Code v1.26.1

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Thanks for reporting this issue. We've duplicated the problem and are working on a fix.

**Comment by smcenlly** [comment]
This is now fixed in the latest version of the Quokka for Visual Studio Code extension (version 1.0.140). Please update your extension to receive the fix.

**Comment by andrew-w-ross** [comment]
Thanks @smcenlly

**Comment by ConneXNL** [comment]
@smcenlly are you sure this is fixed?
I can only seem to get my monorepo workspace to work if I open the directory with the actual tsconfig in vscode

**Comment by smcenlly** [comment]
@ConneXNL - this is working for me. There may be a few things that are causing it to not work for you:

1) If you have a [quokka configuration file](https://quokkajs.com/docs/configuration.html) that overrides your [TypeScript settings](https://quokkajs.com/docs/configuration.html#typescript) then your local `tsconfig.json` files will be ignored.
2) If you're running a scratch file (i.e. unsaved Quokka file), then only the project root `tsconfig.json` will be considered.

If neither of those suggestions help, please create a [new issue](https://github.com/wallabyjs/quokka/issues/new) and include the details requested below. We'd be happy to take a look.
1) Editor verions
2) Quokka version
3) Sample repo with your project structure that has a problem
4) Steps to reproduce your issue
5) Quokka output window results
