### ISSUE TITLE
​​​​Quokka fails with comments in tsconfig.json

### ISSUE THREAD

**Issue by loic-b** [wallabyjs/quokka#240]
### Issue description

Hi, 
When I try to run Quokka on a TS file that is located in a folder where there is a "tsconfig.json" file, it fails to run if the json contains comments, while of course, tsc is able to transpile the code in this case.

I know that comments are not allowed in a json file, but this one was produced by the command:
```bash
tsc --init
```
_Note 1: It works if I remove comments in the config file._
_Note 2: It seems to be a regression bug._

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v10.9.0)​​​​
​​Unexpected token / in JSON at position 29​​
```

### Code editor version
VS Code 1.26.1

### OS name and version
Ubuntu 18.04.1 LTS
Windows 10

**Comment by smcenlly** [comment]
We've duplicated the problem, thanks for reporting the issue. In the latest version of Quokka, we enhanced the tsconfig.json resolution logic which is why you didn't see this error before.

**Comment by smcenlly** [comment]
We've updated how tsconfig.json files are processed to fix the problem, using the same logic as tsc. This is available in the latest Quokka plugin for VSCode, version 1.0.141.

**Comment by loic-b** [comment]
awesome!
Thanks'
