### ISSUE TITLE
Install Missing Package command not available in TypeScript

### ISSUE THREAD

**Issue by texastoland** [wallabyjs/quokka#243]
### Issue description or question

Install Missing Package command not available in TypeScript.

### Sample code

```ts
import _ from "lodash"
```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v10.9.0, TypeScript: v3.0.1)​​​​
```

### Code editor version

VS Code v1.27.0-Insider

### OS name and version

MacOS 10.13.6

**Comment by ArtemGovorov** [comment]
TypeScript compiles the unused import to nothing. So when the resulting (empty) JavaScript runs, there's no missing package issue to report.

If you however start using the imported symbol:

```js
import _ from "lodash"
_
```
then TypeScript will compile the import to valid JavaScript module import and the command will become available.

Hope it makes sense.
