### ISSUE TITLE
Feature request: Add project level .quokka file

### ISSUE THREAD

**Issue by andrewperet** [wallabyjs/quokka#244]
### Issue description or question
Issue: I'd like to maintain project level quokka configurations outside of any files that might get checked in with my project.  Currently, my only options for maintaining project level quokka configurations are package.json and inline file, both of which get checked in my repos.  In some projects I use quokka to test api calls and I use api keys as part of process.env values.  I'd like to make sure these keys do not get checked in to my repos.

Request: Add a project level .quokka file that overrides the global .quokka file.

**Comment by ArtemGovorov** [comment]
The feature is implemented and published in the Quokka latest version.

**Comment by ArtemGovorov** [comment]
Here's the docs for the feature: https://quokkajs.com/docs/configuration.html#quokka-file-config
