### ISSUE TITLE
Using node.dll from Visual Studio Code

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/quokka#246]
### Issue description or question
Is there possible to reuse `node.dll` from VSC to run js files using quokka.js
### Sample code

```javascript
// Not applicable
```

### Sample repository link

*Not applicable* 

### Quokka.js Console Output

```
// Not applicable
```

### Code editor version

Visual Studio Code v1.27.0-insiders?

### OS name and version

Windows 7 Pro

**Comment by ArtemGovorov** [comment]
I'm not sure what is shipped in node.dll, but Quokka needs [node executable](https://quokkajs.com/docs/configuration.html#nodejs-version) to run your code.
