### ISSUE TITLE
further info regarding #242 and #247

### ISSUE THREAD

**Issue by marcelh-gh** [wallabyjs/quokka#248]
@ArtemGovorov 
I still got various errors like the following for various projects.

```
​​​​Quokka #1 (node: v10.5.0)​​​​
​​Unexpected token , in JSON at position 642​​
```

What was very strange about them: at the displayed positions there was never a comma or any other issue.

By comparing the tsconfig in multiple projects and changing them step by step I found the culprit:
In the tsconfigs that were not working I had the following in the exclude section:
`"**/*/*.quokka.ts"`

That was there from when I still did emit js code and this was a way for quick quokka experiments not to land in the compiled results...
Worked fine with the old Quokka ;-)

I don't need this anymore, so I just deleted the entries.
You might want to investigate though, why this could cause such random error messages. Even claiming there is an unexpected token "," at a position in the middle of whitespace...

Anyways, thanks a lot for your great support - as always :-) Quokka is indeed awesome...

**Comment by ArtemGovorov** [comment]
Thanks for the report.

The issue is fixed (as well as the one with trailing comma), and will be published as soon as [VS Code marketplace is fixed](https://twitter.com/code/status/1037046658192748545).
