### ISSUE TITLE
​​Unexpected token when running in typescript

### ISSUE THREAD

**Issue by habsfanongit** [wallabyjs/quokka#249]
### Unexpected token } in JSON at position 722​​

Visual Studio Code v1.26.1
MAC High Sierra 10.13.6
![quokkatest ts typescript 2018-09-05 00-55-05](https://user-images.githubusercontent.com/21362322/45072013-1a2d3f00-b0a7-11e8-83b6-3004deebdd29.png)

I do have ts-node installed and quokka works as expected with javascript files.

**Comment by smcenlly** [comment]
Do you have tsconfig.json defined within your project? This issue may be related to [quokka-issues-248](https://github.com/wallabyjs/quokka/issues/248).

**Comment by ArtemGovorov** [comment]
The issue is indeed related to https://github.com/wallabyjs/quokka/issues/248#issuecomment-418579470, and it has been fixed earlier today. We couldn't publish it because VS Code marketpalce was down, but now when it is up we have just published the fix in the latest v1.0.146.
