### ISSUE TITLE
Can't immediately rerun if delay option is set

### ISSUE THREAD

**Issue by mysyljr** [wallabyjs/quokka#251]
### Issue description or question
I set delay option to 10s to avoid frequent rerun. 
Each time I restart quokka I have to wait for 10s to get my code to run. But I want it to run immediately.

Besides delay option, I also suggest a pause button and a noAutoRun option to avoid frequent rerun.

```javascript
### Sample code
({
  "delay": 10000
})
//some code with side effect that I don't want rerun frequently
console.log('ok')
```

### Sample repository link
Nothing

### Quokka.js Console Output

```
ok
```

### Code editor version
Webstorm 2018.2.2

### OS name and version
OSX

**Comment by smcenlly** [comment]
Thanks for reporting this issue. There was no reason to wait for the delay on the first execution so we've updated the delay logic to be ignored on the first execution. This change is available in our latest version of Quokka (v1.0.113 for Webstorm).

For the "pause button" functionality, we have a separate [feature request #219](https://github.com/wallabyjs/quokka/issues/219) where this is captured.
