### ISSUE TITLE
Typescript: importing with /// <reference path="" /> doesn't work

### ISSUE THREAD

**Issue by johnfn** [wallabyjs/quokka#252]
### Issue description or question

When I use Quokka.js on a TypeScript file, if it has /// references, quokka won't know to pull in those files, meaning it can't resolve any objects in external files. 

### Sample code

a.ts

```typescript
/// <reference path="b.ts" />

b;
```

b.ts

```typescript
let b = 5;
```

### Quokka.js Console Output

​​b is not defined​​

### Code editor version

Visual Studio Code v1.27.1

### OS name and version

macOS high sierra

**Comment by ArtemGovorov** [comment]
`///` reference is not importing anything in runtime.  It serves as a declaration of dependency between files. The `a.ts` file gets compiled to the following JavaScript:

```js
/// <reference path="b.ts" />
b;
```

so the error is expected.

In order to import a module you may use `import` or `require`, for example

```ts
/// <reference path="b.ts" />
import './b'
b;
```

**Comment by johnfn** [comment]
No, that's not true. Depending on how you have your tsconfig configured, it's possible that TypeScript will concatenate all your source files into a single file (if you use outFile). While it's probably unreasonable to expect quokka to compile *every* file, it would be nice if reference paths hinted quokka to concatenate the two files together.

**Comment by johnfn** [comment]
> It's only the case if you run TypeScript for the whole project, however I specifically mentioned the scenario when The a.ts file gets compiled .... 

If you want to be pedantic, there is no such thing as "single file compilation" in a project with outFile set. It's all or nothing 😉 

But yea, seeing this sort of thing would be nice. I actually already bought quokka half with the expectation that this would work (the "try pro" wasn't working for some reason), if that motivates you at all, hehe.
