### ISSUE TITLE
Live comments doesn't show values in Visual Studio Code.

### ISSUE THREAD

**Issue by rcoundon** [wallabyjs/quokka#253]
### Issue description or question
I'm using the VSC plugin with Quokka Pro.  If I use Quokka.js: New Javascript file, I can correctly show live values using the /*?*/ syntax.  However, I cannot get this to show on an existing javascript file. 

### Sample code

```javascript
let sampleString = "123"
let maxTime = sampleString ? parseInt(sampleString) || 0 : 0; /*?*/
```

### Quokka.js Console Output

```
​​​​Quokka #2 (node: v8.9.3)​​​​
```

### Code editor version

Visual Studio Code v1.27.2

### OS name and version

OSX - High Sierra 10.13.6

**Comment by ArtemGovorov** [comment]
Just tried and Quokka is working as expected on an existing JavaScript file for your code sample.
If you have just created the file (saved it from a new file), try restarting Quokka on the file. If it's still not working, please provide a sample project with a simple file where the issue can be reproduced.
