### ISSUE TITLE
Can't find module with babel-plugin-root-import

### ISSUE THREAD

**Issue by arryanggaputra** [wallabyjs/quokka#255]
### Issue description or question
I'm using babel-plugin-root-import , it seems quokka doen't work with this, can help? I'm using pro version

### Sample code

```javascript
import Request from "@/lib/Request/index";

Request({
  method: "get",
  url: "/posts"
}).then(resp => {
  return resp;
});

```

### .babelrc
```json
{
  "presets": ["@babel/preset-env", "next/babel"],
  "plugins": [
    ["transform-define", "./env-config.js"],
    [
      "babel-plugin-root-import",
      {
        "rootPathSuffix": "./",
        "rootPathPrefix": "@"
      }
    ]
  ]
}

```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v9.10.1)​​​​
​​​​
​​Cannot find module '@/lib/Request/index'​​
```

### Code editor version

Visual Studio Code v1.27.2

### OS name and version

OSX 10.13.6

**Comment by ArtemGovorov** [comment]
Quokka should work fine with the plugin, just created a demo in this branch https://github.com/wallabyjs/quokka-babel-import-sample/tree/babel-plugin-root-import. Take a look and check if it's working for you (also check if you have [configured Quokka to use Babel](https://quokkajs.com/docs/configuration.html#babel)). If you get stuck, please create a sample repo demonstrating the issue, happy to take a look.
