### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by inyono** [wallabyjs/quokka#256]
### Issue description or question

It doesn't seem like Quokka.js uses a `babel.config.js` configuration file for Babel 7. This leads to "unexpected token" e.g. because of `import` or JSX.

### Quokka.js Console Output

```
Quokka #1 (node: v8.11.2)​​​​
​​​​
​​Unexpected token (53:6)​​
  at ​​​Object.Module._extensions..js​​​ ​module.js:663​
```

### Code editor version

Visual Studio Code 1.27.2

### OS name and version

macOS 10.14

**Comment by smcenlly** [comment]
There must be something else wrong with your configuration as Quokka does support the use of babel.config.js files. I've updated our (quokka-react-sample repo)[https://github.com/wallabyjs/quokka-react-sample] to use Babel 7 so you can refer to a working example.

If this doesn't help you, please provide us with a sample repo so we can analyze your project configuration for you.
