### ISSUE TITLE
How to import project file from scratch file in Pro?

### ISSUE THREAD

**Issue by davestewart** [wallabyjs/quokka#257]
### Issue description or question

I'm trying to import project files into a scratch. Is this possible?

I've set up webpack aliases, but Quokka doesn't seem to play ball.

Unfortunately, the docs don't seem to be designed to offer useful help / use cases, above and beyond showing that the feature exists :( .

### Sample code

You should be able to see the 2 files below:

1. webpack config / aliases
2. scratch file

![image](https://user-images.githubusercontent.com/132681/46044782-aa452e00-c113-11e8-8193-27abf78856e4.png)

### Quokka.js Console Output

```
Quokka #1 (node: v8.11.1)

Cannot find module '@/core/objects/errors'
	at Object.quokkaStackTraceMarker ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js:14
	at i.quokkaStackTraceMarker [as _onStart] ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js:14
	at i.start ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/server.js:19
	at R.in:run ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/server.js:16
	at WebSocket.<anonymous> ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/server.js:16
	at emitTwo events.js:126
	at WebSocket.emit events.js:214
	at Receiver.ontext ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/node_modules/ws/lib/WebSocket.js:841
	at afterWrite _stream_writable.js:464
	at onwrite _stream_writable.js:455
	at InflateRaw.afterTransform _stream_transform.js:90
	at Zlib.callback zlib.js:515
```

### Code editor version

PHPStorm 2018.2

### OS name and version

OSX 10.12.6

**Comment by davestewart** [comment]
I did some more digging, and I found this plugin, which I also can't get to work.

I created this issue:

https://github.com/Gozala/alias-quokka-plugin/issues/4

**Comment by smcenlly** [comment]
Quokka does not provide native support for aliases, and runs in nodejs, which means your webpack alias configuration will be ignored. We have reviewed the 3rd party quokka plugin and provided a [working sample](https://github.com/wallabyjs/quokka-257) that uses the plugin.

There are two items to note: 
1. This also works for scratch files in IntelliJ IDEs.
2. The alias plugin logic requires that you configure the full path to your alias.

**Comment by davestewart** [comment]
Thanks @smcenlly - that's real decent of you!

Just heading to bed, but I'll check this out tomorrow.

Cheers,
Dave

**Comment by davestewart** [comment]
Thanks for the example repo.

I just can't seem to make this work.

Dumping some console logs into the plugin, it's doing things, and the plugin itself isn't that complex, but whatever it returns is not telling quokka "Here's the file".

I may have another look later.

**Comment by davestewart** [comment]
So it looks like the plugin simply doesn't support partial paths.

I have PR'ed so hopefully that will get accepted.

**Comment by davestewart** [comment]
Have also uploaded a full working demo for Quokka, ES6 + Scratch files here:

- https://github.com/davestewart/alias-quokka-plugin-demo

**Comment by davestewart** [comment]
I've updated the demo with individual examples for ES5, ES6 and TypeScript
