### ISSUE TITLE
Atom package development with Quokka

### ISSUE THREAD

**Issue by ghost** [wallabyjs/quokka#258]
### Issue description or question
Trying to do Atom package development with Quokka community edition, the following can be encountered by using the atom package generator (ctrl+shift+P: "Package Generator: Generate Package"), opening Quokka on the lib/<my-package>.js file and swapping the import lines, Quokka will complain about not finding the module "atom". The npm package "atom" is NOT the atom editor api, and I suppose, not published as an npm node module.

What would be the correct way to use/configure my Atom package or Quokka so that it finds/recognizes the Atom editor "atom" imports? Tried to look through the docs and issues here but did not see any mention of package development or similar issue.

Thanks.

### Sample code

```javascript
import { CompositeDisposable } from 'atom';
```

### Quokka.js Console Output

```
Cannot find module 'atom'
```

### Code editor version

Atom v1.30.0 x64

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Closing this issue. Atom is being discontinued (https://github.blog/2022-06-08-sunsetting-atom/).
