### ISSUE TITLE
Improve the docs styling

### ISSUE THREAD

**Issue by davestewart** [wallabyjs/quokka#259]
Hi Quokka team.

Thanks loads for your excellent plugin.  It's fantastic as it generally works right out of the box!

However, when it doesn't work and one has to trawl the docs, it's not such a fun affair.

I get the presentation is supposed to match the Wallaby JS style, but a monospaced font and large block-like headings really don't make it easy to grok the info.

The style also doesn't lend itself to more details docs, such as code snippets and examples. 

There are really good docs sites out there, which might be worth looking into?

- https://vuepress.vuejs.org
- https://docsify.js.org

I'd be happy to help if needs be.

**Comment by davestewart** [comment]
Just to demo the readability, here is the page with just a couple of minor style tweaks to the font and line-spacing:

Styled:

![styled](https://user-images.githubusercontent.com/132681/46180364-dc8f9080-c2b7-11e8-9da9-cc31e3052643.png)

And the original for a comparison:

![original](https://user-images.githubusercontent.com/132681/46180317-a0f4c680-c2b7-11e8-8087-e111b9ebfbdd.png)

**Comment by ArtemGovorov** [comment]
Thanks for your feedback. We have updated our docs styles to address the points you've raised.

**Comment by davestewart** [comment]
Ha! Amazing! It makes such a difference!

Thanks, and well done :D
