### ISSUE TITLE
Quokka config file seemingly not loading in one project

### ISSUE THREAD

**Issue by davestewart** [wallabyjs/quokka#260]
### Issue description or question

I've just created a new webstorm project, and I've copied the `.quokka` file from another project, installed the required plugin for that file, and run up a scratch file.

In the old project I see:

```
Quokka #1 (node: v8.11.3, babel: v6.26.3, plugins: alias-quokka-plugin)
```

In the new project, I see:

```
Quokka #2 (node: v8.11.3)
```

The config file is exactly the same. 

I can't see that babel has loaded, or the plugin. I can see the plugin in `node_modules`.

Quokka still works in the console, but the plugin doesn't load - which is a problem as we want to use aliases to load modules.

I'm guessing maybe this is because I'm running a typescript project (see `package.json` below) ?

### Sample code

Quokka config file `.quokka`:

```
{
  "babel": true,
  "plugins": ["alias-quokka-plugin"],
  "alias": {
    "@/": "./src/",
    "utils": "./src/utils"
    "log": "./src/utils/log",
  }
}
```

I can delete everything but `babel: true` and it's the same.

This is my `package.json`:

```json
{
  "name": "dev-ts",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "element-ui": "^2.4.7",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.4",
    "@vue/cli-plugin-eslint": "^3.0.4",
    "@vue/cli-plugin-typescript": "^3.0.4",
    "@vue/cli-service": "^3.0.4",
    "@vue/eslint-config-standard": "^3.0.4",
    "@vue/eslint-config-typescript": "^3.0.4",
    "alias-quokka-plugin": "davestewart/alias-quokka-plugin#master",
    "node-sass": "^4.9.3",
    "require-context": "^1.1.0",
    "sass-loader": "^7.1.0",
    "ts-node": "^7.0.1",
    "typescript": "^3.0.0",
    "vue-template-compiler": "^2.5.17"
  }
}
```

### Sample repository link

This is the working original project:

- https://github.com/davestewart/alias-quokka-plugin-demo

The new project doesn't have a repo yet.

### Code editor version

Webstorm 2018.2

### OS name and version

OSX Sierra

**Comment by davestewart** [comment]
It turns out I can attempt to load the plugin using the inline version of the config:

```js
({
  babel: true,
  plugins: ['alias-quokka-plugin']
})

import log from '@/utils/log'
```

Then I get this error:

```
Quokka #1 (node: v8.11.3, babel: v7.0.0-beta.47, plugins: alias-quokka-plugin)

Unexpected token import
	at createScript vm.js:80
	at Object.runInThisContext vm.js:139
	at Module._compile module.js:616
```

So something somewhere is importing (not the file or the plugin).

If I remove `babel: true` I get:

```
Quokka #1 (node: v8.11.3, plugins: alias-quokka-plugin)

Cannot find module '@/utils/log'
	at Object.quokkaStackTraceMarker /Users/davestewart/Library/Application%20Support/WebStorm2018.2/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js:14
	at i.quokkaStackTraceMarker [as _onStart] /Users/davestewart/Library/Application%20Support/WebStorm2018.2/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js:14
	at i.start /Users/davestewart/Library/Application%20Support/WebStorm2018.2/quokka-intellij/dist/server.js:19
	at v.in:run /Users/davestewart/Library/Application%20Support/WebStorm2018.2/quokka-intellij/dist/server.js:16
	at WebSocket.<anonymous> /Users/davestewart/Library/Application%20Support/WebStorm2018.2/quokka-intellij/dist/server.js:16
	at emitTwo events.js:126
	at WebSocket.emit events.js:214
	at Receiver.ontext /Users/davestewart/Library/Application%20Support/WebStorm2018.2/quokka-intellij/dist/node_modules/ws/lib/WebSocket.js:841
	at afterWrite _stream_writable.js:464
	at onwrite _stream_writable.js:455
	at InflateRaw.afterTransform _stream_transform.js:90
	at Zlib.callback zlib.js:515
```

So it's as if the plugin hasn't run :(

I'm figuring this is all because we're running TypeScript and don't have the right babel libs loaded.

Any ideas on how to update the project or my approach?

Thanks :)

**Comment by smcenlly** [comment]
Your .quokka file has some errors in it, it needs to be valid JSON. Once I fixed it, quokka loaded for me.

I've added a new issue for Quokka to report on when the file has errors, [Quokka does not warn when there is an error in .quokka project file](https://github.com/wallabyjs/quokka/issues/261).

```diff
{
  "babel": true,
  "plugins": ["alias-quokka-plugin"],
  "alias": {
    "@/": "./src/",
-   "utils": "./src/utils"
+   "utils": "./src/utils",
-   "log": "./src/utils/log",
+   "log": "./src/utils/log"
  }
}
```

**Comment by davestewart** [comment]
Drat! I'll check when I'm work tomorrow; hopefully not a GitHub copy/paste typo.

I guess I missed this because the quokka file has no extension, so my editor doesn't show any errors.

If the file was called `quokka.config.js` or `quokka.json` this would afford the user a valuable way to keep the file valid.
