### ISSUE TITLE
Plugin code not running for scratch files

### ISSUE THREAD

**Issue by davestewart** [wallabyjs/quokka#262]
### Issue description or question

For some reason, my Quokka plugin code is not running when running Quokka in scratch files.

I don't understand, as I'm 99% sure it was running in scratch files yesterday!

I've been continuing work on the alias plugin as mentioned in this issue:

- https://github.com/wallabyjs/quokka/issues/260

### Sample code

The new demo shows the plugin running for various languages. You can clone this demo to see it running and not running as described above.

Clone the demo here:

- https://github.com/davestewart/alias-quokka-plugin-demo

Choose a subfolder to run, for example `es6`

Open folder in WebStorm.

Run `npm install`.

Open `src/main.js` and start Quokka. Witness the console output:

```
Quokka #7 (node: v8.11.1, babel: v6.26.3, plugins: alias-quokka-plugin)

Hello ES6 ! 
```

Copy the same code, paste into a scratch file, and start Quokka. Witness the console output:

```
Quokka #8 (node: v8.11.1)

Cannot find module '@/classes/Greeter'
	at Object.quokkaStackTraceMarker ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js:14
	at i.quokkaStackTraceMarker [as _onStart] ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js:14
	at i.start ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/server.js:19
	at v.in:run ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/server.js:16
	at WebSocket.<anonymous> ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/server.js:16
	at emitTwo events.js:126
	at WebSocket.emit events.js:214
	at Receiver.ontext ./Library/Application%20Support/PhpStorm2018.2/quokka-intellij/dist/node_modules/ws/lib/WebSocket.js:841
	at afterWrite _stream_writable.js:464
	at onwrite _stream_writable.js:455
	at InflateRaw.afterTransform _stream_transform.js:90
	at Zlib.callback zlib.js:515
```

To check the plugin itself, edit the file `node_modules/alias-quokka-plugin/src/main.js` to add a `console.log()`:

```js
exports.before = config => {
  const aliases = config.alias || {}
  Module._load = (path, ...rest) => {
    console.log('>>>>>> RUNNING!')
    const src = resolveAlias(aliases, path)
    return src
      ? _load(resolvePath(src, path), ...rest)
      : _load(path, ...rest)
  }
}
```

You will see the console log for all loaded files in the saved file, but not the scratch file.

### Code editor version

Webstorm 2018.02

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Just tested the repo, but can't reproduce the issue, here is what I'm doing:

![shr5](https://user-images.githubusercontent.com/979966/46325073-fcb5ab80-c639-11e8-9442-0e2fad4a2d2f.gif)

Have I missed anything? From your output it looks like your `.quokka` file was not loaded for you scratch file for some reason (perhaps try moving Quokka settings to package.json to see if it's working form there).

**Comment by davestewart** [comment]
So, checked in...

- WebStorm 2018.2.3 and it worked :)
- PhpStorm 2018.2.3 and 2018.2.4 and the plugin doesn't run

In VSCode:

- Saved files run fine
- New (untitled) files load the plugin, but with the current code, can't find the target path on the alias. The target file appears to be `.runners/node/bootstrap` so no idea what's going on there, I will need to investigate. Most likely a new ticket!

**Comment by smcenlly** [comment]
We're aware that unsaved scratch files don't work in VSCode, this is a limitation of the Quokka plugin for VSCode. This is because the file doesn't have a physical location to refer to your existing project like they do in IntelliJ IDEs.

Unfortunately we can't duplicate the issue with Quokka not working in PhpStorm. It's working for us on a fresh install. Sounds like you've installed a new version, perhaps you could try uninstall, remove old PhpStorm user files and then reinstall?

![phpstorm](https://user-images.githubusercontent.com/2074089/46382833-58427080-c6f0-11e8-9df3-b3f9be9e0bbd.gif)

**Comment by smcenlly** [comment]
RE: VSCode - I was mistaken - we **do** support VSCode on unsaved scratch files, but sometimes VSCode can get confused when you have multiple folders in the same workspace. In this case, Quokka allows you to select your workspace folder for scratch files using the `Quokka.js: Select Workspace Folder` folder.

If you are opening multiple projects in the same PhpStorm instance, you may have a similar issue with VSCode. For PhpStorm, for scratch files we only support opening 1 project at a time. You will need to open each project it its own window.

**Comment by davestewart** [comment]
Thanks for looking into this.

Still no luck for me.

I guess I'll add some notes to the main readme and be done with it.

Cheers!
