### ISSUE TITLE
Pro features don't work on project .ts files (IntelliJ / WebStorm)

### ISSUE THREAD

**Issue by anodynos** [wallabyjs/quokka#263]
### Issue description or question

Pro features (or trial mode) don't work on project .ts files, but they do work on .js & ALL scratch files - see 
![image](https://user-images.githubusercontent.com/856453/46507863-99db3480-c832-11e8-9d0b-535cf9b14fce.png)

### Sample code

```javascript
let a = 1;/*?*/
a = 3; /*?*/
new Promise(resolve => resolve(13))/*?*/
console.log(a * 10)/*?*/
```

### Sample repository link
Not needed 

### Quokka.js Console Output

```
// JS file's output
Quokka #3 (node: v9.9.0)
1 at api/src/various/javascriptFile.js:1:0
3 at a = 3 api/src/various/javascriptFile.js:2:0
30 at a * 10 api/src/various/javascriptFile.js:4:0
undefined at console.log(a * 10, 'a * 10', 1, 4) api/src/various/javascriptFile.js:4:0
then 13 at new Promise(resolve => resolve(13)) api/src/various/javascriptFile.js:3:0

// .ts file's output
Quokka #2 (node: v9.9.0, TypeScript: v2.9.2)
30 at a * 10 api/src/various/typescriptFile.ts:4:0
```

### Code editor version

IntelliJ 2018.2.4 Ultimate (Build Sep 18, 2018)
Quokka plugin Version: 1.0.115
### OS name and version

Linux Kubuntu 16.04.5 64bit

**Comment by anodynos** [comment]
Thanks for your response - I'm sending you the smallest example that has the same behaviour :-(
[quokka-trial.zip](https://github.com/wallabyjs/quokka/files/2448478/quokka-trial.zip)

**Comment by smcenlly** [comment]
Thanks for the sample, was really helpful. The reason that you're not getting values is that the tsConfig that we're using has `"removeComments": true`. We will investigate whether we can enhance Quokka to clear this flag during Quokka executions. The reason that you didn't get this on your scratch file is that the TypeScript compiler doesn't find your project `tsconfig.json` when it executes against your scratch file.
