### ISSUE TITLE
No shortcut can be defined for *View Value* in IntelliJ / Webstorm plugin.

### ISSUE THREAD

**Issue by anodynos** [wallabyjs/quokka#264]
### Issue description or question

No shortcut can be defined for *View Value* in IntelliJ plugin - please add this feature!

![image](https://user-images.githubusercontent.com/856453/46509030-57b4f180-c838-11e8-91c4-f217911da9e4.png)

### Code editor version

IntelliJ 2018.2.4 Ultimate (Build Sep 18, 2018)
Quokka plugin Version: 1.0.115

### OS name and version

Linux Kubuntu 16.04.5 64bit

**Comment by smcenlly** [comment]
Thanks for reporting this issue. This is a bug and not by design. We will add support for this in our next release. Will update this ticket when it's released.
