### ISSUE TITLE
Shows an error

### ISSUE THREAD

**Issue by gabrieldlazcano** [wallabyjs/quokka#265]
### Issue description or question
It is not supposed to be an error, because it runs on nodejs
### Sample code
```javascript
var fs = require('fs')
var output = fs.readFileSync("data.txt")
```

### Quokka.js Console Output

```
ENOENT: no such file or directory, open 'data.txt'
```

### Code editor version

Visual Studio Code 

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Just tried and the code is working as expected if the `data.txt` file is in he working directory of the Quokka file. If it's not, then the error is expected.

My guess is that you don't have a project opened, or have multiple projects opened and haven't set Quokka workspace context.

Here's an easy test, try this code in the same Quokka file:

```js
console.log(__dirname)
```

and make sure that the folder is correct and that the `data.txt` exists in the folder.

**Comment by folivieri** [comment]
relative path did not work for me but adding '__dirname' does like:
`fs.readFileSync(__dirname + '/data.txt', 'utf8')`

**Comment by smcenlly** [comment]
@folivieri - this is working for us in VS Code. The steps we took to reproduce:

1) Create a new empty project (no installed dependencies)
2) Create a file in the project root, called `data.txt` with some simple content (e.g. `Hello World`)
3) Create a new Quokka file with the content `fs.readFileSync('data.txt').toString() //?` "Hello World" is displayed beside code

Could you please [create a new issue](https://github.com/wallabyjs/quokka/issues/new) with the steps that you're taking to reproduce the problem? We'd be happy to investigate further if we can reproduce the problem.
