### ISSUE TITLE
Setting to disable auto-display of console output

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#266]
**Feature request:** would like to be able to configure quokka to disable launching the console output when Quokka starts.

**Comment by donfak** [comment]
Totally support this!
For some folks like me, the inline interpreter (using /*?*/) it's enough most of the time.
And also, on small screens the output window takes too much space.

Will be cool to disable that in the settings.

**Comment by smcenlly** [comment]
Our next version of Quokka for VS Code will add support for this. In VS Code, you will need to add a new user setting, `"quokka.showOutputOnStart": false`. If it's missing, the default is `true` (same behavior as today).

Will update this issue after the next version is published.

**Comment by smcenlly** [comment]
This is available in the latest version of Quokka for VS Code, version 1.0.153.
