### ISSUE TITLE
Live Comments in Typescript files

### ISSUE THREAD

**Issue by simerlec** [wallabyjs/quokka#27]
### Issue description or question
Hey guys,

love the new Live Comment feature, great work.

Apparently it does only work in JS files, not in TS files though. I tried it with the current version of quokka.js via the `Quokka.js: New TypeScript File` command - Live comments are not shown. Doing the same with a new JavaScript file works just fine.

For reference I postet my dummy TS file below.

Thanks and keep up the good work :)

### Quokka.ts file

```javascript
var persons = [{
    "id": 1,
    "name": "Peter",
    "age": 12
}, {
    "id": 2,
    "name": "Sven",
    "age": 55
}, {
    "id": 3,
    "name": "Mike",
    "age": 33
}];

var report = (id) => `id is ${id}`;

persons/*?*/
    .filter(person => {
        return (person.age > 30);
    }).map(person => {
        console.log(person);
        return person;
    })
    .map(person => {
        return report(person.id);
    });
```

### Code editor version

Visual Studio Code Version 1.10.2 (1.10.2)

### OS name and version

macOS Sierra Version 10.12.3 (16D32)
(node: v7.7.2, TypeScript: v2.1.5)​​​​

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.20, once you update the extension - it should work for you.
