### ISSUE TITLE
unwanted characters copied text from vscode output 

### ISSUE THREAD

**Issue by eldyvoon** [wallabyjs/quokka#273]
### Issue description or question
How do I copy object or array of quokka's output? I copy from the output terminal of vscode, but the copied text contains unwanted character which is really annoying.

### Sample code
const myObject = ​​​​​{ id: 123 }​​​​​
console.log(myObject)

### Quokka.js Console Output
If you paste it like usual it may not be noticeable, but the hidden special characters are there, paste the copied text here https://www.soscisurvey.de/tools/view-chars.php and you shall see it.

pasted text I got for { id: 123 } became
https://i.imgur.com/fds4lBp.png

**Comment by ArtemGovorov** [comment]
It's a known issue. You may find the reason description and a solution here - https://github.com/wallabyjs/quokka/issues/151#issuecomment-430102831.
