### ISSUE TITLE
Error while loading tsconfig.json

### ISSUE THREAD

**Issue by mrgrauel** [wallabyjs/quokka#274]
### Issue description or question

​​Error while loading tsconfig.json. Does anybody has an Idea? I can't find any related issues.

### Steps 

Try to start Quokka on current file give the following output.

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v10.12.0)​​​​
​​Error while loading tsconfig.json:​​
​​require(...).getCompilerOptions is not a function​​
```

### Code editor version
Visual Studio Code Version 1.28.1

### OS name and version
macOS 10.14 Mojave

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in the latest extension v1.0.155.
