### ISSUE TITLE
"runnerw.exe: CreateProcess failed with error 2: The system cannot find the file specified." in WebStorm on Windows

### ISSUE THREAD

**Issue by tonycngo** [wallabyjs/quokka#276]
I've installed the Quokka.js plugin in my WebStorm.   Purchased Pro license.  Create a file js file and start typing as instructed and do not see any square dots on the left or anything on the right.

### Sample code

const obj = {
  firstName: 'Tony'
}

console.log(obj.firstName);

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Webstorm v? 2018.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Could you please provide a screenshot of the issue?

**Comment by tonycngo** [comment]
Sent from Mail for Windows 10

**Comment by ArtemGovorov** [comment]
Unfortunately it doesn't look like any screenshot had been attached to your previous post.

**Comment by tonycngo** [comment]
Sent from Mail for Windows 10

**Comment by ArtemGovorov** [comment]
The same again - no screenshot. Please try uploading the file using GutHub UI.

**Comment by tonycngo** [comment]
It’s in the attached ms word document.

Sent from Mail for Windows 10

**Comment by ArtemGovorov** [comment]
There is no attached document. Please open the issue in browser and try uploading the file using GutHub UI.

**Comment by tonycngo** [comment]
Sent from Mail for Windows 10

**Comment by ArtemGovorov** [comment]
You are just adding empty messages. Please open the issue in browser.

**Comment by tonycngo** [comment]
![image](https://user-images.githubusercontent.com/3741661/47261695-8bc81d80-d49a-11e8-8996-b4a0f7b228f6.png)

**Comment by ArtemGovorov** [comment]
It looks like you are using Quokka on an existing file, not on a Scratch file, and you haven't started Quokka on the file.

Our [tutorial for Quokka for Webstorm](https://quokkajs.com/docs/?editor=jb) may be helpful for you. As the docs say:

`
You may create a new Quokka scratch file, or start Quokka on an existing file by using the Start Quokka context menu action in any opened file editor (you may also assign some shortcut to the action). 
`

The same information is actually displayed on your screen:

![47261695-8bc81d80-d49a-11e8-8996-b4a0f7b228f6](https://user-images.githubusercontent.com/979966/47261725-020b6500-d519-11e8-8835-0bc792a92547.png)

**Comment by tonycngo** [comment]
I don't think so.  I did follow the doc and right click to open the context menu.  I select start quokka(run once).  Nothing is happening.  I've even try to create the scratch file.  Doesn't work there either.  I've tried on the VS Code and it's working fine.  Please try it in Webstorm and show me how to do it in WebStorm.  I hate to be wrong but I need this to work.

**Comment by tonycngo** [comment]
What is this error when I tried to create a scratch file?

runnerw.exe: CreateProcess failed with error 2: The system cannot find the file specified.

**Comment by tonycngo** [comment]
![image](https://user-images.githubusercontent.com/3741661/47261955-13fcf180-d4a0-11e8-8226-85cc3f77fea6.png)

**Comment by ArtemGovorov** [comment]
Looks like you are doing it correctly, however the same thing is working for me in WebStorm:

<img width="432" alt="screen shot 2018-10-21 at 10 45 17 am" src="https://user-images.githubusercontent.com/979966/47261980-88767580-d51e-11e8-83b6-c64fe00bfcea.png">

Can you please try:

- opening Terminal in Webstorm, run `node -v` command, and paste the command execution result?
- updating your WebStorm to 2018.2 to see if it starts working?

**Comment by tonycngo** [comment]
v9.11.1

**Comment by ArtemGovorov** [comment]
Try the WS 2018.2 to see if it helps, I'd also suggest trying to specify the path to your node.exe directly in the [`node` setting in Quokka config file](https://quokkajs.com/docs/configuration.html#nodejs-version):

```
{
    ...
    "node": "C:\\Program Files... etc"
}
```

**Comment by tonycngo** [comment]
Updated to WS 2018.2 .  Still not working 

WebStorm 2018.2.4
Build #WS-182.4505.50, built on October 3, 2018

You have a perpetual fallback license for this version
Subscription is active until August 2, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ArtemGovorov** [comment]
Have you tried specifying node executable path as I have suggested above?

**Comment by tonycngo** [comment]
I did.  Still not  working.

**Comment by ArtemGovorov** [comment]
- Is it showing the same error on scratch files?
- Please attach your idea.log file (can be found with `Help - Show Log ...` menu in WebStorm).

**Comment by tonycngo** [comment]
{
	"pro":true
	"node": "/Users/tngo/.nvm/versions/node/v7.7.1/bin/node"
}

**Comment by tonycngo** [comment]
[idea.log](https://github.com/wallabyjs/quokka/files/2498706/idea.log)

**Comment by ArtemGovorov** [comment]
> "node": "/Users/tngo/.nvm/versions/node/v7.7.1/bin/node"

It doesn't looks like a valid path. You are on Windows, how can this be a real path? The docs just list an example of the path. Please specify your real path to your node.exe in the setting as I have suggested above: `"node": "C:\\Program Files... etc"`.

**Comment by ArtemGovorov** [comment]
This is still not a valid node.exe path:
- slashes are not escaped,
- as I have mentioned, it has to be a full path to your node **executable**. Should be something like:

```
"node": "C:\\Program Files\\nodejs\\node.exe"
```

but you need to make sure that it is a correct path and the file does exist.

**Comment by tonycngo** [comment]
After I fixed the config file.  It's working now.
Thanks for your patience.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
