### ISSUE TITLE
Vscode - Quokka - spawn EACCESS

### ISSUE THREAD

**Issue by radswiat** [wallabyjs/quokka#278]
### Issue description or question
- VScode live feedback doesn't work

### Sample code

```javascript
const a = 5;
const b = 'asdasd';

console.log(a + b); //?

```

### Sample repository link

n/a

### Quokka.js Console Output

![image](https://user-images.githubusercontent.com/6523154/47371726-367d4d80-d6e0-11e8-8658-647f34901c1c.png)

### Quokka global config:

```json
{"pro":true,"babel":true,"node":"~/.nvm/alias/default"}
```

### Code editor version
Version 1.28.2 (1.28.2)

### OS name and version
OSX - Mojave

**Comment by smcenlly** [comment]
The `node` setting must point to a valid node executable. Can you please confirm that `~/.nvm/alias/default` points to the node executable on your environment? On my nvm install, `~/.nvm/alias/default` is a text file with the version specified in its contents: 

```
v8.11.4
```

Try running `~/.nvm/alias/default --version` to confirm that this is a node executable.

**Comment by radswiat** [comment]
Thanks @smcenlly !

```
± |develop ✓| → ~/.nvm/alias/default --version
-bash: /Users/rswiat/.nvm/alias/default: Permission denied
```

And when trying with sudo, `command not found`.

You've been right, pointing to `alias` don't work and because of the permission issue it doesn't give any precise errors. Changing to `"~/.nvm/versions/node/v8.11.2/bin/node"` fixed the problem.

Thanks again,
