### ISSUE TITLE
Cannot use absolute path in require, imports

### ISSUE THREAD

**Issue by lekhnath** [wallabyjs/quokka#28]
### Issue description or question
As there is no way to provide environment variables to quokka I cannot configure it to support absolute requireing, importing of local modules.

### Quokka.js file

```javascript
import mongoose from 'mongoose';
import Bluebird from 'bluebird';

import config from 'lib/config';
import autoload from 'lib/autoload';

mongoose.Promise = Bluebird;
const connection = mongoose
  .createConnection(`mongodb://localhost:27017/${config.get('db:name')}`);

autoload(config.get('dir:models'), '.model.js');


export default connection;
```

### Quokka.js Console Output

```
Quokka #1 (node: v6.9.1, babel: v6.24.0)​​​​
​​​​
​​Cannot find module 'lib/config'​​
  at ​​​Function.Module._resolveFilename​​​ ​module.js:469​
  at ​​​Function.Module._load​​​ ​module.js:417​
  at ​server/lib/quokka.js:7:0​
```

### Code editor version

Visual Studio Code v1.10.2?

### OS name and version
Ubuntu

**Comment by ArtemGovorov** [comment]
You can use the way I [suggested in the comments](https://quokkajs.com/docs/#comment-3232782010). However, babel hoists `imports`, so you'll need to do it [via a plugin](https://quokkajs.com/docs/configuration.html#plugins). Create the plugin file `modulePatch.js` in your project root folder:
*modulePatch.js*
```javascript
process.env.NODE_PATH = __dirname + '/server'
require('module').Module._initPaths();
```

and add it to your quokka config:
```
{
     ...,
     "plugins": [
        "./modulePatch"
     ]
 }
```
