### ISSUE TITLE
e.console.log.apply is not a function

### ISSUE THREAD

**Issue by skylarmb** [wallabyjs/quokka#280]
### Issue description or question
Just installed Quokka. Typed `console.log('foo')`. Received error.

### Sample code

```javascript
console.log('foo');
```

### Sample repository link
N/A

### Quokka.js Console Output

```
Quokka #1 (node: v10.11.0)​​​​
​​​​
​​e.console.log.apply is not a function​​
  at ​​​Object.<anonymous>​​​ ​quokka.js:1:0​

```

### Code editor version

Visual Studio Code v1.28.2

### OS name and version

OSX 10.14.1 Beta

### Screenshot
![screen shot 2018-10-26 at 10 32 11 am](https://user-images.githubusercontent.com/7543705/47583006-ed5d1180-d90a-11e8-931f-eb199cc04473.png)

**Comment by ArtemGovorov** [comment]
Unfortunately we can't yet reproduce the issue. Could you please paste the following code in your Quokka and share the execution output:

```js
var test = console.log.toString();
test
```

**Comment by skylarmb** [comment]
Solved. Uninstalled/Re-installed the extension, then completely rebooted VS Code, and it works now.

**Comment by willys123** [comment]
Just disabled and enable again the Quokka
