### ISSUE TITLE
Typescript via babel

### ISSUE THREAD

**Issue by dandevs** [wallabyjs/quokka#281]
### Issue description or question
Unable to run typescript via babel, tried to use `"babel": true` with a `.quokka` and as an inline config.

### Code editor version
Visual Studio Code v1.28.2

### OS name and version
Windows

**Comment by chrisblossom** [comment]
Eta on this feature? It is relatively common for new projects to use babel to compile typescript now.

**Comment by smcenlly** [comment]
We've added this feature to Quokka, please update Quokka to get the new feature. We've also updated [our docs](https://quokkajs.com/docs/configuration.html#using-babel-to-compile-typescript) on how to enable this. Please update your `.quokka` configuration to include a setting, `ts` set to true:

```json
{
  "babel": {
    "ts": true,
    "plugins": ["@babel/plugin-transform-typescript"]
  }
}
```

Depending on your runtime environment, you may also need to update the compiler options for `babel/plugin-transform-typescript` ([see here](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options)).

---

**Out of interest, we're keen to understand why you want your `Quokka` files compiled with babel? What is your scenario/use case?**

**Comment by chrisblossom** [comment]
Because **_I personally think_** both already wallaby and quokka require too much configuration. I have found most of it often unnecessary. I shouldn't have to install `ts-node` because I want quokka to work when I don't use `ts-node` for anything else (or at the very least quokka should handle it on the backend / call `npx ts-node`). But alas, this requires more configuration ;).

IMO most of this can and should be handled automatically.

Thanks for the quick response!!

**Comment by smcenlly** [comment]
Thanks for your feedback. We're currently working on reducing the configuration effort (starting with Wallaby).

**Comment by chrisblossom** [comment]
@smcenlly I've pretty much eliminated all configuration for my backend node projects [using this config](https://github.com/chrisblossom/backtrack-preset-jest/blob/master/lib/files/wallaby.js).

[I have mentioned this before](https://github.com/wallabyjs/public/issues/1571), but I still think most all configuration issues could be solved by simply keeping wallaby's cache in the local `node_modules` folder using something like [find-cache-dir](https://github.com/avajs/find-cache-dir). I know it would have saved me [more hours than I'd like to admit](https://github.com/wallabyjs/public/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Achrisblossom+) of configuration problems (obviously not all, but a lot of them).

**Comment by ArtemGovorov** [comment]
@chrisblossom We are actually getting rid of Wallaby cache for Jest completely. It should eliminate the whole class of problems, moreover our goal is to have **no Wallaby config** at all for Jest projects.

>  I shouldn't have to install `ts-node` because I want quokka to work when I don't use `ts-node` for anything else (or at the very least quokka should handle it on the backend / call npx ts-node). 

If it helps at all, you may install `ts-node` for Quokka only (once) in the `~./quokka` folder:

```
cd ~/.quokka && npm i ts-node
```

and it'll work for you without any additional configuration.

**Comment by chrisblossom** [comment]
> We are actually getting rid of Wallaby cache for Jest completely. It should eliminate the whole class of problems, moreover our goal is to have no Wallaby config at all for Jest projects.

That's great news! What is the eta? When ready, I'd be happy to beta test and report any issues I've found.

> If it helps at all, you may install ts-node for Quokka only (once) in the ~./quokka folder:

That is exactly what I did shortly after asking the ETA of this feature. Why not have quokka do that automatically on the backend?

Another question, is it possible for me to write tests against my wallably config to verify wallaby will work as expected?

**Comment by ArtemGovorov** [comment]
>  What is the eta? When ready, I'd be happy to beta test and report any issues I've found.

It is still in development, but we are close to finish it. After some internal testing, we'll publish the beta and will make sure to let you know so you could test it on your projects.

>  Why not have quokka do that automatically on the backend?

We'd need to maintain the dependency (ship or update to newer versions of `ts-node`). Back when the feature was developed, the dependency/complexity seemed to be undesirable. Having said that we could at least suggest user a quick link to install the module in Quokka folder (like we are doing for `jsdom`).

> Another question, is it possible for me to write tests against my wallably config to verify wallaby will work as expected?

Can't think of an easy way to do it.

**Comment by ArtemGovorov** [comment]
> Why not have quokka do that automatically on the backend?

Created the feature request https://github.com/wallabyjs/quokka/issues/378

**Comment by chrisblossom** [comment]
> Another question, is it possible for me to write tests against my wallably config to verify wallaby will work as expected?
> Can't think of an easy way to do it.

I didn't think so, would definitely be nice but I don't think it will needed (for me) once your jest update is complete.

> It is still in development, but we are close to finish it. After some internal testing, we'll publish the beta and will make sure to let you know so you could test it on your projects.

That would be great, thank you!

**Comment by smcenlly** [comment]
@chrisblossom - today we released our experimental automatic configuration for jest v24+. [Check it out](https://wallabyjs.com/docs/intro/config.html#automatic-configuration), we'd appreciate your feedback.
