### ISSUE TITLE
Quokka couldn't find my project

### ISSUE THREAD

**Issue by fr0** [wallabyjs/quokka#282]
### Sample code
TypeScript; two issues:

1. it can't find my tslint.json file (which is sitting in the root directory of my project)
2. It can't find my source code

<img width="818" alt="screen shot 2018-10-29 at 5 16 48 pm" src="https://user-images.githubusercontent.com/435418/47680906-83f53100-db9e-11e8-8049-5e8a1aabf9bd.png">

(I didn't generate that crazy path to `../../../../Documents/...`, WebStorm did that when I typed `AppComponent` and pressed Enter -- I'm guessing this is indicating some deeper path-related issue)

Alos, I am using the PRO version of Quokka.

### Quokka.js Console Output

```
Cannot find module '../../../../Documents/web-frameworks/angular-cli-test/src/app/app.component'
	at Function.Module._resolveFilename module.js:538
	at Function.Module._load module.js:468
	at require internal/module.js:11
	at Object.<anonymous> quokka.ts:1
	at Module._compile module.js:643
```

### Code editor version

WebStorm 2018.2.5

### OS name and version

OSX

**Comment by smcenlly** [comment]
The TSLint message you are receiving is from Webstorm and is not related to Quokka. You can read more about enabling TSLint for Webstorm in the [Jetbrains docs](https://www.jetbrains.com/help/webstorm/tslint.html).

Quokka runs scratch files from your Webstorm project root. In your case, JetBrains has provided you with a relative path to use the scratch file temporary location. You can see the path that Quokka is using for your scratch file by typing `process.cwd() //?` in your scratch file while Quokka is running. Having said that, Quokka runs using `node` and depending upon what you're doing, you may need to bootstrap parts of Angular to run Angular components within Quokka. You may also find that you need to use the [jsdom-quokka-plugin](https://github.com/wallabyjs/jsdom-quokka-plugin) if your code requires the DOM.

**Comment by fr0** [comment]
Thanks for the help -- I'm still not sure how to get past the `Cannot find module` errors, but I will keep trying.

**Comment by smcenlly** [comment]
Can you try this on a new project?

1. Create a new directory and open it in WebStorm.
2. Create `Foo.ts`
3. Set its contents to:

```typescript
export class Foo {
  title: string;

  constructor() {
    this.title = 'Boo!';
  }
}
```

4. Create a new scratch file.
5. Set its contents to:

```typescript 
import { Foo } from './Foo';

new Foo().title //?
```

You should see `Boo!` appear beside the question mark.

**Comment by fr0** [comment]
I tried the steps you suggested. Here's the error I'm getting:

```
Quokka #1 (node: v8.9.4, TypeScript: v2.5.2)

⨯ Unable to compile TypeScript:
error TS6053: File '/Users/crfrolik/Library/Application Support/WebStorm2018.2/quokka-intellij/dist/node_modules/typescript/lib/lib.d.ts' not found.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
	at createTSError ./node_modules/ts-node/src/index.ts:261
	at getOutput ./node_modules/ts-node/src/index.ts:367
	at Object.compile ./node_modules/ts-node/src/index.ts:558
	at Module.m._compile ./node_modules/ts-node/src/index.ts:439
	at Module._extensions..js module.js:654
	at Object.require.extensions.(anonymous function) [as .ts] ./node_modules/ts-node/src/index.ts:442
	at Module.load module.js:556
	at tryModuleLoad module.js:499
	at Function.Module._load module.js:491
	at require internal/module.js:11
	at Object.<anonymous> quokka.ts:1
	at Module._compile module.js:643
```

I installed both `ts-node` and `typescript` *globally* using npm.

**Comment by fr0** [comment]
Here is what that folder (`/Users/crfrolik/Library/Application Support/WebStorm2018.2/quokka-intellij/dist/node_modules/typescript/lib/`) looks like:

![screen shot 2018-10-30 at 11 39 34 am](https://user-images.githubusercontent.com/435418/47730462-92902680-dc38-11e8-9108-b9701566809b.png)

Compared to a stock `typescript@2.5.2` install, it seems like it is missing some files?

I tried uninstalling/re-installing the Quokka plugin in WebStorm, but the problem persists.

**Comment by fr0** [comment]
Yep, that did it. I was able to get it to work. Thanks!
