### ISSUE TITLE
Webstorm - Node.js - Couchbase - Module did not self-register

### ISSUE THREAD

**Issue by OSSDeveloper** [wallabyjs/quokka#284]
### Issue description or question
Quokka.js is giving 'Module did not self-register' error while requiring 'couchbase'.

### Sample code
const couchbase = require("couchbase")

### Quokka.js Console Output

Quokka #1 (node: v10.13.0)

Module did not self-register.
	at Object.Module._extensions..node internal/modules/cjs/loader.js:717
	at bindings ./node_modules/bindings/bindings.js:81
	at Object.<anonymous> ./node_modules/couchbase/lib/binding.js:213
	at Object.Module._extensions..js internal/modules/cjs/loader.js:699
	at Object.<anonymous> ./node_modules/couchbase/lib/couchbase.js:3
	at Object.Module._extensions..js internal/modules/cjs/loader.js:699

### Code editor version

Webstorm 2018.2.5

### OS name and version

OSX

### Steps to reproduce error
1. setup an empty node.js project.
2. In command prompt, type : npm install couchbase
3. In scratchpad type : const couchbase = require("couchbase")

**Comment by smcenlly** [comment]
When (re)running your code, Quokka by default tries to re-use previously created node.js process(es) to make the code run faster. In your case, `couchbase` is doing something that is stopping Quokka from re-using the same `node` process for subsequent Quokka executions, which is causing the error you're receiving.

You can fix this by updating your Quokka config with the `recycle` setting set to `true`. Please see an example below. You can read more about Quokka configuration [here](https://quokkajs.com/docs/configuration.html).

```javascript
{
  ...
  "recycle": true
}
```

**Comment by rsxdalv** [comment]
Thank you!

Request: add a hint about this in the error or bump the pagerank of this page for "quokka module did not self-register" keyword
