### ISSUE TITLE
Incorrectly warned about reuse of license

### ISSUE THREAD

**Issue by rcoundon** [wallabyjs/quokka#287]
### Issue description or question
Receiving message:
Quokka.js 'Pro' is stopped because your license is being used elsewhere on the network by MacBook-Pro (0.0.0.0). Only one active computer at the same time may use the license. If you would like to purchase an additional license, please visit our website. If you have already purchased the license, please activate it.

But have only one machine running it (only own one MacBook!)

### Code editor version

Visual Studio Code Version 1.28.2

### OS name and version
MacOS Mojave 10.14

**Comment by ArtemGovorov** [comment]
Looks like there may be some orphaned Quokka processes running on your machine. Try closing your editor, killing all `node` processes on your machine and then start Quokka - it should help.
