### ISSUE TITLE
Unexpected token : error when using Typescript

### ISSUE THREAD

**Issue by kevincam3** [wallabyjs/quokka#290]
### Issue description or question

```javascript
const hello = (name: string) => {
    return `Hello ${name}`;
}

hello('kevin'); //?
```

### Quokka.js Console Output
​​​​Quokka 'kata.ts' (node: v10.13.0, TypeScript: v3.1.4, plugins: jsdom-quokka-plugin)​​​​
​​​​
​​Unexpected token :​​
  at ​​​new Script​​​ ​vm.js:79​
  at ​​​createScript​​​ ​vm.js:251​
  at ​​​Object.runInThisContext​​​ ​vm.js:303​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:656​

### Code editor version
Visual Studio Code v1.20.0

### OS name and version
Windows 10

**Comment by smcenlly** [comment]
Can you please provide the contents of your quokka configuration file(s)?

Is the source code that you provided the entirety of `kata.ts`?

**Comment by kevincam3** [comment]
Where do I find the quokka configuration file(s). I just installed it as a VSCode extension.

Yes what I provided is the only thing in my source file. It works if I choose "New Typescript File" and copy and paste but not when I use "Start on Current File"

**Comment by smcenlly** [comment]
The reason I asked for your configuration is that it looks like you have the `jsdom-quokka-plugin` configured. You can read about how Quokka processes your configuration [here](https://quokkajs.com/docs/configuration.html).

Quokka.js supports 4 sources of configuration:

1. global config file,
2. project’s package.json file,
3. project’s .quokka file,
4. inline code in your quokka file.

The settings in the global config file (1) are applied to all quokka files, no matter if you are running quokka in an opened project or not.

The settings in a package.json file (2) are applied to all quokka files opened in the context of the opened project.

The settings in a .quokka file (3) are applied to all quokka files opened in the context of the opened project.

The inline settings in your quokka file (4) are applied only to the opened file.

The global the quokka.js settings can be found: 
* On Mac OSX and Linux: ~/.quokka
* On Windows: %USERPROFILE%\\.quokka

**Comment by kevincam3** [comment]
Here's what's in the config.json file I found at %USERPROFILE%\.quokka

{"pro":true,"plugins":["jsdom-quokka-plugin"]}

**Comment by smcenlly** [comment]
Everything is working for us with the same content in both a new TypeScript file and in an existing file. Can you please provide us with a sample repo so we can replicate the issue at our end?

**Comment by kevincam3** [comment]
By "sample repo" do you mean upload the file to a repo. I did that here: https://github.com/kevincam3/kata Let me know what else I can do.

**Comment by smcenlly** [comment]
Thanks Kevin, we've been able to duplicate the problem. There's an issue running within any directory that starts with a `.`. We'll investigate the cause and get back to you. In the meantime, you can continue to use quokka as long as your file is not in a directory starting with `.`.

**Comment by kevincam3** [comment]
Ok, got it. Thanks.

**Comment by smcenlly** [comment]
We've fixed this in the latest version of Quokka for all editors. Please update your VS Code Quokka plugin and this will work for you.
