### ISSUE TITLE
Value Explorer copy function does not copy data that has not been "expanded"

### ISSUE THREAD

**Issue by diegovdc** [wallabyjs/quokka#291]
This might be related to #238, but the `Copy Data` feature of the Value Explorer does not copy all the data that has been processed, only the data that has been expanded in the explorer.  This is a problem when we want to copy the data of deeply nested structures.

**Comment by smcenlly** [comment]
This is by design. It's possible that the data you're copying can expand indefinitely (e.g. through circular references). 

I'll mark this as a feature request, and we'll investigate providing another option to expand on copy.

**Comment by fmquaglia** [comment]
I have the same thought just today. May be have a "expand all" toggle?

**Comment by ArtemGovorov** [comment]
We have introduced the [new feature to auto-expand object trees](https://medium.com/@wallabyjs/value-explorer-for-jetbrains-ides-wallaby-quokka-bundle-and-more-cdbbea7791e0#3ab1) with a special comment.
