### ISSUE TITLE
Can't set file settings with prettier & no-semi

### ISSUE THREAD

**Issue by JakeGinnivan** [wallabyjs/quokka#294]
With prettier and no-semi's turned on, a `(` will be prefixed with `;`, and then quokka doesn't seem to parse the settings.

```javascript
;({
    plugins: "jsdom-quokka-plugin",
    jsdom: { html: `<button id="test">Click me</div>` }
})

// stuff
```

Could the semi colon be ignored, or handled?

**Comment by smcenlly** [comment]
We've updated our logic to ignore settings prefixed with semi-colons. This is available in the latest version of Quokka for each editor (v1.0.166 for VS Code, v1.0.128 for JetBrains editors, v1.0.119 for Atom).
