### ISSUE TITLE
Create-React-app and JSX issues

### ISSUE THREAD

**Issue by jwill9999** [wallabyjs/quokka#295]
### Issue description or question
I am running a front end client with Create-react-app 2.0. On running Quokka on a JSX file I get SyntaxError: Unexpected token​​ on JSX code. My config is set up as below as indicated in previous replies here to similar problems. Despite me looking into previous resolved issues I'm unable to get this to work with JSX. I've also added the plugin ``` jsdom-quokka-plugin```

### Package.json / Config
```json
 {
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "author": {
    "name": "Jason Williams",
    "email": "jasonwilliams@letuscode.co.uk",
    "url": "http://www.letuscode.co.uk"
  },
  "dependencies": {
    "dotenv": "^6.1.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.6.0",
    "global": "^4.3.2",
    "react": "^16.6.0",
    "react-dom": "^16.6.0",
    "react-redux": "^5.1.0",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "flow": "flow status"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "@types/react-dom": "^16.0.9",
    "@types/redux": "^3.6.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.1.0",
    "eslint-plugin-flowtype": "^3.2.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx": "^0.0.2",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-react": "^7.11.1",
    "flow-bin": "^0.85.0",
    "flow-typed": "^2.5.1",
    "jsdom-quokka-plugin": "^1.0.13",
    "prettier": "^1.14.3",
    "prettier-eslint": "^8.8.2",
    "prettier-eslint-cli": "^4.7.1",
    "react-test-renderer": "^16.6.0"
  },
  "quokka": {
    "babel": {
      "polyfill": true,
      "presets": ["react-app"]
    },
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  }
}
```

### Global config .quokka/config.json

```json
{
  "pro": true
}
```

### Sample code
```javascript
// @flow

import * as React from "react";
import "./navBar.css";

const NavBar = () => <h1>Navbar</h1>;

export default NavBar;


```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

```
> git clone https://github.com/jwill9999/testme/tree/homepage 

> cd client

```

### Quokka.js Console Output

```
​​​​Quokka 'NavBar.js' (node: v10.13.0)​​​​
​​​​
​​file:///C:/Users/escap/Documents/repos/training/testme/client/src/components/NavBar/NavBar.js:6​​
​​        return $_$w(1, 1), <h1>Navbar</h1>;​​
​​                           ^​​
​​​​
​​SyntaxError: Unexpected token​​

```

### Code editor version

Visual Studio Code : October 2018 (version 1.29)

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. 

From Quokka output it looks like neither Babel, nor jsdom plugin had been initialised. It happens when Quokka can't find its config. In your case the `quokka` section should be in the opened project's root, because Quokka is using current opened project as a working dir. So you may either:
- open `client` as a project in VS Code (and leave `quokka` section in its `package.json`),
- or move `quokka` section to the root `package.json` (note that you may need to specify [Babel path](https://quokkajs.com/docs/configuration.html#babel-path) in this case because Babel is installed in `client`, not in root).

Also your Quokka config for babel request it to use `polyfill`, so you may need to install the package too (Quokka will prompt you about it).

**Comment by jwill9999** [comment]
Many thanks to @ArtemGovorov who quickly provide this solution which I share here.

## Assistance for others trying to resolve the same issue with Create-React-App 

#### Key resolved  points

1. I was trying to setup my quokka in a nested file system (client) as illustrated below. (create-react-app)
2. The root file system did not contain my setup in a config file or package json,  so quokka could not find it.
3. This was because I was opening my React app as well as my server etc in one project, however my Quokka  cvonfig was in client/package.json. *** NOT THE PROJECT ROOT ***

<img src="https://uvnyig.am.files.1drv.com/y4mHxXg6Wbf3VEoquvOnzrTxsH3r75HqtzCMJBeykK_MhvsLXlOGlhaNKFMDG_pxOMnDy-A5LVZkX1q13r7OmjNQwh8aViQPoViNoOmzlcq0wnOYPJ1949DdUFC5R-wkYAJDmVHe716TP1bFWvZfY3JwNhu8IToDMyAMAAhM6tPmnR0qFTHHMi_YskJmZM78mOdK4coHXk4nb6yUw0trWClOw?width=660&height=434&cropmode=none" width="660" height="434" />

#### Solution for me 

1. I kept my setup within client the same however I only opened that folder into my editor not the nested file structure as below.

<img src="https://uvn9ig.am.files.1drv.com/y4mlOmx5ngo1h6yCWMUW6X1dPVazBuWpdHxJfyuEGL0c15hEKSDnlDF4LmXRIWQBeXRTBVHeh2t4IK1zyv2ORmiXf2i54mG3IfEru4WWfz9veuxZdf71KbTwDS2IhOUpn2VbvZ4NS4Kt-vY0bzFz3V5Ea_UjF0cDLVZlwZVhCFap5FLedrbCA2W6t9Gcdz3J5vf2fLM4grAM69yAgp6nq-EQA?width=660&height=434&cropmode=none" width="660" height="434" />

2. Because I was now providing my configuration for Quokka in the root of the opened file structure , Quokka worked without issue.
