### ISSUE TITLE
Quokka,js Pro not working in vscode

### ISSUE THREAD

**Issue by mathiasmaerker** [wallabyjs/quokka#296]
### Issue description or question
Hi Team,

I just purchased a Pro Licence  and activated it in Vscode(successfully), switched to Pro Edition, restarted and wanted to try out Quokka.
I created a new "Quokka" file and tried the code below and I get no results. I tried Show Output command, and I get nothing, nor even an error.

can you provide any help?

### Sample code

```javascript
const a = 'bla'
const b = () => {
	return 	a //
}
b()
const c = () => {
	let sfd = b()
	sfd = sfd +' Hallo' //
}
c() //
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​Quokka 'test2.js' (node: v8.9.3)​​​​
```

### Code editor version

Visual Studio Code v1.29.1
Version: 1.29.1 (system setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
In order to get the values printed, the [live comment](https://quokkajs.com/docs/#comments) should be used, it is: `//?` or `/*?*/`:

```js
const a = 'bla'
const b = () => {
	return 	a //?
}
b()
const c = () => {
	let sfd = b()
	sfd = sfd +' Hallo' //?
}
c() //?
```
