### ISSUE TITLE
Quokka stops working when file is saved in vsCode

### ISSUE THREAD

**Issue by habsfanongit** [wallabyjs/quokka#298]
### Quokka.js Console Output

```
// console output is empty.
```
<img width="659" alt="screen shot 2018-11-26 at 12 35 48 am" src="https://user-images.githubusercontent.com/21362322/48995003-2956e280-f114-11e8-96ac-8a716ac26bd5.png">

Visual Studio Code Version 1.29.1 (1.29.1)

**Comment by ArtemGovorov** [comment]
Quokka should only stop when Quokka scratch file is saved on disk via Save File dialog. When it happens, the file changes its name (and internal VS Code file URI scheme). So it is by design.

If it is something else and not what is described above, please let us know.

**Comment by habsfanongit** [comment]
It stopped working with any files other than scratch files before being saved. Not working on existing js files or TS files either

**Comment by ArtemGovorov** [comment]
Just tried on the same OS/editor version on an existing file - editing/saving and everything is working as expected:

![test](https://user-images.githubusercontent.com/979966/48995560-28fe2c00-f194-11e8-85c3-14a3697e6bef.gif)


What am I missing?

**Comment by habsfanongit** [comment]
That's what I am used to doing before today.
Now I don't have the option "Start on current files".
<img width="1009" alt="screen shot 2018-11-26 at 1 07 13 am" src="https://user-images.githubusercontent.com/21362322/48995895-e434af80-f117-11e8-8a91-b9eebbb0eaf4.png">

**Comment by ArtemGovorov** [comment]
Try typing `>Quokka Start`, maybe the command is at the end of the list. Also try the `Cmd + K, Q` shortcut.

**Comment by habsfanongit** [comment]
Quokka Start did the trick. I was trying Cmd + K, Q but it didnt change anything.
Now I can see the Start on Current File option.
Thanks for your help.
