### ISSUE TITLE
Support loops

### ISSUE THREAD

**Issue by slavik57** [wallabyjs/quokka#3]
Can you please add support for loops?
For instance add some next/prev buttons to loop or show some kind of list of the outputs

```javascript
for(let i = 0 ;i<10;i++){
    i;
    if(i>2){
        i
    }
}
```

### Quokka.js Console Output

```
​​​​​0​​​​​ at ​​​i​​​ ​quokka.ts:9:4​

​​​​​3​​​​​ at ​​​i​​​ ​quokka.ts:11:8​
```

Visual Studio Code v1.10.2

Windows 10

**Comment by ArtemGovorov** [comment]
Quokka logs once instance of the identifier expression hit, like
```javascript
for(let i = 0 ;i<10;i++){
    i
}
```
for performance reasons. You may be typing the `i` in a large loop and probably don't want to see many values as you're typing

There's the supported way to log from the loops (or anywhere else), just use `console.log`:

```javascript
for(let i = 0 ;i<10;i++){
    console.log(i);
    if(i>2){
      console.log(i);
    }
}
```

this way you'll see all values displayed.
