### ISSUE TITLE
Quokka with Gatsby

### ISSUE THREAD

**Issue by mrruby** [wallabyjs/quokka#302]
### Issue description or question

How to configure quokka global file with Gatsby to work with JSX?

### Sample code

```javascript
const Nav = ({ siteTitle }) => (
  <div
    style={{
      background: 'rebeccapurple',
      marginBottom: '1.45rem',
    }}
  >
```

### Quokka.js Console Output

```
components/nav.js: Unexpected token (5:2)​​
​​​​
​​  3 | ​​
​​  4 | const Nav = ({ siteTitle }) => (​​
​​> 5 |   <div​​
​​    |   ^​​
```

### Code editor version

Visual Studio Code v1.?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Most likely you just need to let Quokka know to [use Babel via Quokka config](https://quokkajs.com/docs/configuration.html#babel). If you are using CRA, then the [solution can be found here](https://github.com/wallabyjs/quokka/issues/227#issuecomment-407266213).

**Comment by mrruby** [comment]
I'm using [Gatsby CLI](https://www.gatsbyjs.org/docs/) and CRA solution doesn't work.
It is throwing the 
```​​Failed to run compilers on src/components/nav.js, Error: Cannot find module 'babel-preset-react-app' from '/Main/App```

This is my quokka config file:
```{
  "babel": {
    "presets": ["react-app"]
  },
  "plugins": ["jsdom-quokka-plugin"],
  "pro": true,
  "env": {
    "params": {
      "env": "BABEL_ENV=test"
    }
  }
}```

**Comment by mrruby** [comment]
> We configured Babel as per [Gatsby's Babel documentation](https://www.gatsbyjs.org/docs/babel/) using `babel-preset-gatsby`. The only thing we needed to do was override the environment settings for `NODE_ENV` in our `.quokka` file.
> 
> **Our `.babelrc` file looks like this:**
> 
> ```json
> {
>   "presets": ["babel-preset-gatsby"]
> }
> ```
> 
> **and our `.quokka` file looks like this:**
> 
> ```json
> {
>   "babel": true,
>   "plugins": ["jsdom-quokka-plugin"],
>    "env": {
>     "params": {
>       "env": "NODE_ENV=test"
>     }
>   }
> }
> ```

After this steps I'm getting 
```​​​​Quokka 'nav.js' (node: v8.12.0, babel: v7.1.2, plugins: jsdom-quokka-plugin)​​​​
​​​​
​​Unexpected token import​​
  at ​​​createScript​​​ ​vm.js:80​```

**Comment by smcenlly** [comment]
Please provide us with a sample repo and details of which file you're running on and we'll take a look for you.

**Comment by mrruby** [comment]
Hi!

Repo: https://github.com/mrruby/fryzjerstwo
Branch: feature/basicFunc
File: components/nav/index.js

**Comment by smcenlly** [comment]
Thanks for the repo. There were a few issues (including a product fault) that were stopping this from working for you. The `gatsby` library that you're requiring is actually a `jsx` file in `node_modules` that is not processed by babel.

To get this working on your sample, you will need to:
1) Update to use the latest version of Quokka for your editor (v1.0.172 for VS Code).
2) Add `@babel/register` module to your project's devDependencies. (`npm install @babel/register --save-dev`)
3) Update your `.quokka` configuration file as shown below (note: I used a project-level `.quokka` file):

```
{
  "babel": {
    "ignore": ["node_modules/(?!gatsby)"],
    "presets": [
      "babel-preset-gatsby"
    ]
  },
  "plugins": ["jsdom-quokka-plugin"],
   "env": {
    "params": {
      "env": "NODE_ENV=test"
    }
  }
}
```

**Comment by mrruby** [comment]
I'm still getting an error
```​​​​Quokka 'Nav.js' (node: v8.12.0, babel: v7.2.0, plugins: jsdom-quokka-plugin)​​​​
​​​​
​​Cannot find module 'core-js/modules/es6.array.sort'​​```

**Comment by smcenlly** [comment]
I just got latest on the repo and tried again on `src/nav/index.js` and everything is working for me. It looks like you're running on a different file now, `Nav.js`, what are the contents of that file?

I expect that your problem is that `babel` is adding some polyfills that rely on `core-js`.

Given the error you're receiving, have you tried installing [core-js](https://www.npmjs.com/package/core-js) module to fix the problem? (`npm install core-js --save-dev`)

**Comment by mrruby** [comment]
I have ```jsdom-quokka-plugin``` installed in global ```.quokka``` file, so I needed to add core-js also there.

Thank you for your patience nad help <3

**Comment by chocobuckle** [comment]
Would it be possible for you guys to release a quokka-gatsby-sample, the way you did for React? I've read through the above issue and [this one ](https://github.com/wallabyjs/quokka/issues/439) but can't for the life of me get Quokka working with Gatsby. I just bought the Pro version today, but have yet to get it working successfully.

**Comment by smcenlly** [comment]
[This repo](https://github.com/wallabyjs/quokka-gatsby-typescript) might help. We created it when helping with [Can't get Quokka working with Gatsby, JSX and Typescript. #510](https://github.com/wallabyjs/quokka/issues/510). Depending on what you are doing with Gatsby, and what runtime components you're using, you may run into similar challenges described in https://github.com/wallabyjs/quokka/issues/510. Specifically, this user's code was relying on GraphQL runtime which is not available when using Quokka.

From the issue:
> Unfortunately Quokka does not currently provide first class support for gatsby as a runtime environment. If you're using runtime components that gatsby sets up in its own startup scripts, you will need to augment the Quokka runtime to do the same, or to mock these components.

If your project has unit tests then our other product, [Wallaby.js](https://wallabyjs.com/) may provide more of what you're looking for and unlike Quokka, it has support for complex runtime environments (both browser and node.js based).
