### ISSUE TITLE
There is supporting for react-native?

### ISSUE THREAD

**Issue by ulises-castro** [wallabyjs/quokka#303]
### Issue description or question
I was trying using react configuration and it only returns the following response I don't know if it exists support for react-native...

### Sample code

```javascript
// paste the code you are running here
Failed to run compilers on app/components/Discover.js, Error: Cannot find module 'babel-preset-react-app' 



### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version
Atom v1.?

### OS name and version
Linux

**Comment by ArtemGovorov** [comment]
Please 
- share your Quokka config,
- check if the `babel-preset-react-app` module exist in your `node_modules`.

**Comment by ulises-castro** [comment]
This is my quokka config

![image](https://user-images.githubusercontent.com/17864276/49267845-05e8ac00-f422-11e8-9f1a-6ae75c0da045.png)


**This is my react native project:**



_**Node Modules**_
![image](https://user-images.githubusercontent.com/17864276/49267875-27e22e80-f422-11e8-978b-2f54163ffd40.png)


**This is a vainilla react project:**


`{
  "name": "testquokka",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-scripts": "2.1.1"
  },
  "quokka": {
    "babel": {
      "presets": ["react-app"]
    },
    "plugins": [
      "jsdom-quokka-plugin"
    ]
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
`


**_I can't using quokka.js, always this appears to me even restarting my IDE_**

![image](https://user-images.githubusercontent.com/17864276/49267752-86f37380-f421-11e8-93c3-2b6a86e4a331.png)

my package.json config

**Comment by ArtemGovorov** [comment]
Try changing `"quokka": { "babel": { "presets": ["react-app"] }, "plugins": [ "jsdom-quokka-plugin" ] }` to `"quokka": { "babel": { "presets": ["react-native"] }, "plugins": [ "jsdom-quokka-plugin" ] }`


> I can't using quokka.js, always this appears to me even restarting my IDE

Do you have Pro license? If so, have you activated it (by clicking the link in the popup on the screenshot)?

**Comment by ulises-castro** [comment]
I don't have one, you must get one talking about react/react-native? I thought you only restarting IDE each 10 minutes

**Comment by ArtemGovorov** [comment]
> I don't have one, you must get one talking about react/react-native? 

You don't need a license to use Community Edition. You may switch to Community Edition using the link in the popup.

Note that some features are only available in Pro version, for example you can import other modules from your code in a running Quokka file only in Pro edition.

> I thought you only restarting IDE each 10 minutes

Yes, during trial period of the Pro edition it is possible to keep using it by just restarting your editor. However, as the popup message saying, your trial period has expired. So you either need to purchase a license, or switch to Community Edition (which is free), by using the link in the popup.
