### ISSUE TITLE
Passing arguments

### ISSUE THREAD

**Issue by benfletcher** [wallabyjs/quokka#305]
### Issue description or question

How to define arguments (`process.argv`) or pass them in? I'm working on a node CLI project that relies on arguments. I see the docs address params, but don't see any way to use that functionality for straight arguments.

My arguments are static.

### Sample code

```javascript
const cliArguments = process.argv.slice(2);
```

(When manually running, user arguments begin at index 2.)

### Sample repository link

n/a

### Quokka.js Console Output

n/a

### Code editor version

VSCode 1.29.1

### OS name and version

OSX Mojave 10.14.2

Node version 10.14.1

**Comment by ArtemGovorov** [comment]
Passing process arguments is not possible because Quokka doesn't run your file directly. It runs its own server to instrument the file, then a separate node process to run the file (and rerun with some cached dependencies).

**Comment by benfletcher** [comment]
Ok, thanks for the quick reply. Not a huge deal to use a default argument during dev, just thought I was missing something obvious!
