### ISSUE TITLE
How to disable "Quokka.js will not display coverage indicators in the gutter because the editor.glyphMargin setting is set to false" gutter error?

### ISSUE THREAD

**Issue by chiboreache** [wallabyjs/quokka#309]
Poping-up every time when I starting quokka, extremely annoying `~_~`

>Quokka.js will not display coverage indicators in the gutter because the `editor.glyphMargin` setting is set to `false`.

**Comment by smcenlly** [comment]
We've added a new setting to ignore suppress this message. Please add a new setting override to your settings.json file:

```json
"quokka.suppressGlyphMarginNotifications": true
```

To set this property, you need to open your settings (`File->Preferences->Settings`) and then click the braces icon (`{}`) on the top right of your editor to switch to `json` editing mode. You can read more about editing your settings [here](https://code.visualstudio.com/docs/getstarted/settings).

**Comment by chiboreache** [comment]
That's aweeesome, thanks a lot! ^___^


@ArtemGovorov 
Мейн ризон в том что гаттер отъедает кучу места, а я люблю клин лук и не хочу ничего менять ;)
