### ISSUE TITLE
Support for create-react-app

### ISSUE THREAD

**Issue by bstro** [wallabyjs/quokka#31]
### Issue description or question
When I try to start quokka inside a react component file, I get all manner of errors relating to ES6 module support, i.e. `​​Unexpected token import​​ at ​​​Object.exports.runInThisContext​​​ ​vm.js:76​`

It also complains about exports, and I assume it would complain about JSX as well if it could get that far.

I'm not sure how to get quokka running within the context of a `create-react-app` app. Do I need to tell Quokka where to find react-create-app's (already installed) Babel dependency?

Visual Studio Code v1.10.2

**Comment by ArtemGovorov** [comment]
Once you upgrade to the latest version v1.0.24, you should be able to run quokka in `create-react-app` generated projects with just [configuring babel for the quokka](https://quokkajs.com/docs/configuration.html#overriding-babel-settings) (note that you may also add the configuration to your `package.json` or to the [quokka global config](https://quokkajs.com/docs/configuration.html)):


```javascript
({
    babel: {
        presets: ['react-app']
    }
})

import App from './src/App'
```

<img width="782" alt="screen shot 2017-04-06 at 12 45 13 pm" src="https://cloud.githubusercontent.com/assets/979966/24735582/ed85b9fe-1ac6-11e7-98f4-82349555c729.png">

**Comment by bstro** [comment]
Thanks @ArtemGovorov! Putting the expression at the top of my working file solved the issue. I would like Quokka to work across my entire project, however, and I would also like this configuration to be shared across my team. Putting the following at the top level of my project's package.json does not fix the error:

```
  "babel": {
    "presets": ["react-app"]
  },
```

**Comment by ArtemGovorov** [comment]
@bstro Looks like you're missing the [parent "quokka" property](https://quokkajs.com/docs/configuration.html#packagejson-config), try:

```
{
  ...
  "quokka": {
    "babel": {
      "presets": ["react-app"]
    }
  }
}
```

**Comment by imbaniac** [comment]
Added 
```
"quokka": {
    "babel": {
      "presets": ["react-app"]
    }
  }
```
to package.json, still getting:

```
Couldn't find preset "react-app" relative to directory 
"/Users/timreznik/.vscode/extensions/WallabyJs.quokka-vscode-?1.0.27/dist/wallaby/runners/node"​​
```

**Comment by ArtemGovorov** [comment]
@imbaniac Just tried on a freshly created react app and it's working for me. Please create a sample github repo where I could reproduce the issue, happy to have a look.

**Comment by jonathanphz** [comment]
Hi - I tried adding: 

{
  "pro":true,
  _"babel": {
      "presets": ["react-app"]
    }_
}

to global config but nothing seems to be happening - testing with simple console.log(1 + 3);

**Comment by ArtemGovorov** [comment]
@jonathanphz Hi, could you please paste the full output from the Quokka Console?

**Comment by jonathanphz** [comment]
Hi 

- _Paste the full output from the Quokka Console:_ Can't reproduce console message.

- _See if the node_modules/babel-preset-react-app exists in your project folder:_ I confirm it's there.

- _Provide some more details about what do you mean by "Problem only occurs on react files." Ideally please list the steps you're doing to receive the error._: If I create a new JS file and write `console.log(1 + 2)` I get an output of `3`.

If I create a new file with a react component and console log I get no output: 
![untitled-1_ _unleash-app__unsupported_](https://user-images.githubusercontent.com/1545577/28802499-12c2e13a-762d-11e7-80b0-04334c3df90e.jpg)


- Specify your OS version: MacOS Sierra 10.12.4

- create-react-app --version: 1.0.2 ----->maybe this is the problem...?

**Comment by ArtemGovorov** [comment]
@jonathanphz On your screenshot, you run Quokka on the component file itself. Quokka executed the file - but obviously nothing calls the `render` method. If you place `console.add(1+2)` after the class definition, but before the export - it'll be executed.

**Comment by jonathanphz** [comment]
yup - just tried and it worked. Thanks!

**Comment by volotovskyy** [comment]
I got this error message when I was running quokka:

```
Failed to run compilers on src/App.js, Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "undefined". (While processing preset: "/Users/Yu/Desktop/myapp/node_modules/babel-preset-react-app/index.js")
    at Object.<anonymous> (/Users/Yu/Desktop/myapp/node_modules/babel-preset-react-app/index.js:49:9)
    at require (internal/module.js:11:18)
    at /Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:296:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/Yu/Desktop/myapp/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**My ~/.quokka json:**
```
{
  "pro":true,
  "babel": {
    "presets": [
      "react-app"
    ]
  }
}
```
Note: babel `true` or with presets doesn't matter

**Details:**
- [ ] MacOS Sierra 10.12.4

- [ ] Atom

- [ ] create-react-app@1.4.0

- [ ] node_modules/babel-preset-react-app - confirm

- [ ] Provide some more details about what do you mean by "Problem only occurs on react files." 

I've just run Qoukka right in the default CRA configuration:

![screenshot 2017-09-04 11 08 47](https://user-images.githubusercontent.com/13667038/30017353-88ceae6e-9161-11e7-902c-73f57ad6fa76.png)

Same problem when I try to do something custom.

**Comment by ArtemGovorov** [comment]
@volotovskyy 

Try adding the environment setting requested in the error to your quokka.json file:

```diff
{
  "pro":true,
  "babel": {
    "presets": [
      "react-app"
    ]
  },
+ "env": {
+   "params": {
+     "env": "BABEL_ENV=test"
+   }
+ },
}
```

Let me know if this helps.

**Comment by volotovskyy** [comment]
@ArtemGovorov 

Thank you for fast reply!

Well now I get different errors:(
Like this one:
`Unexpected token import`
`at createScript vm.js:74`
`at Object.runInThisContext vm.js:116`

Its clear that Quokka swears at `import` and `export` statements.
Also, I'm almost sure that Quokka doesn't support JSX in the return of render method.
There are no any errors when I've tried React.createElement() to recreate my elements.

**Comment by ArtemGovorov** [comment]
@volotovskyy Most likely your quokka config.json is invalid, because it looks like it is now not applied at all (babel doesn't even try to run as it did before). Please double check your config file (should be a valid JSON file, no comments, no trailing commas). Fresh CRA works for me with teh config like this:

```json
{
  "pro": true,
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "env": {
    "params": {
      "env": "BABEL_ENV=test"
    }
  }
}
```

![at](https://user-images.githubusercontent.com/979966/30096189-6949f958-931a-11e7-92e1-94254ce77076.gif)

**Comment by volotovskyy** [comment]
@ArtemGovorov 

Great video example! Thank for your support.
> because it looks like it is now not applied at all

You are right!

When I launched qoukka config.json this morning it had only `{"pro":true}` and non of my old custom settings.
And now even if I try your `config.json` I'll get same weird error with ENVs.
Tested on ejected CRA app - same result.

Feels like quokkas `config.json` doesn't sync properly. 
In my `zshconfig` I have only aliases, nvm and yarn settings. Nothing that could change anything in global.
I guess there might be some issues with my local machine but I have no idea how to check and fix this.

**Comment by ArtemGovorov** [comment]
@volotovskyy We have just pushed some changes 5 minutes ago that may have fixed the issue (though based on your comment I doubt the change had fixed it, but still). Please try the latest v1.0.10. If it doesn't work, please create an empty Quokka file with this content:

```
process.env //?
```
run it, and paste the results from Quokka panel here (you may need to remove some security sensitive details from the output).

**Comment by volotovskyy** [comment]
@ArtemGovorov 

I did as you said

![2017-09-06 15 20 38](https://user-images.githubusercontent.com/13667038/30111648-2e50ffe8-9317-11e7-9452-7825723c0583.gif)

Same story about empty Quokka file with `process.env //?` when I create it in the `root` or `src` dir.

Of course if I do it in empty folder Quokka will response `Configured to use babel, but can not find babel-core module`.
Finally I do`npm init` and install babel-core and presets in `package.json`
This is what I got:
![screenshot 2017-09-06 15 34 00](https://user-images.githubusercontent.com/13667038/30112195-0ffe2bd6-9319-11e7-8c11-499daef1bede.png)

Hope it can be helpful.

**Comment by ArtemGovorov** [comment]
@volotovskyy Unfortunately what I was hoping to see is truncated in your second screenshot. Please copy/paste here the results from Quokka panel.

**Comment by volotovskyy** [comment]
@ArtemGovorov 

`{ ATOM_HOME: '/Users/Yu/.atom',
`
//cropped some private datas

```
  _system_type: 'Darwin',
  _system_name: 'OSX',
  _system_version: '10.12',
  _system_arch: 'x86_64',
  rvm_version: '1.27.0 (master)',
  GEM_HOME: '/Users/Yu/.rvm/gems/ruby-2.3.1',
  GEM_PATH: '/Users/Yu/.rvm/gems/ruby-2.3.1:/Users/Yu/.rvm/gems/ruby-2.3.1@global',
  MY_RUBY_HOME: '/Users/Yu/.rvm/rubies/ruby-2.3.1',
  IRBRC: '/Users/Yu/.rvm/rubies/ruby-2.3.1/.irbrc',
  RUBY_VERSION: 'ruby-2.3.1',
  _: '/usr/bin/env',
  quokka: '{"globalConfigFile":"/Users/Yu/.quokka/config.json","tempDir":"/Users/Yu/.quokka/data/n5biw","pro":true,"babel":{"presets":["react-app"],"path":"/Users/Yu/Desktop/test/node_modules/babel-core","version":"6.26.0"},"env":{"params":{"env":"BABEL_ENV=test"}}}',
  BABEL_ENV: 'test' } at process.env quokka.js:1:0
```

**Comment by ArtemGovorov** [comment]
@volotovskyy Thanks, I think I finally was able to fix it. Please update your Atom plugin to 1.0.12, and try again.

**Comment by volotovskyy** [comment]
@ArtemGovorov Congrats 🎉 👍 
It works almost like a charm now!

Still show 'gray box' in gutter on `render` method (while linter feels completely fine)
![screenshot 2017-09-07 10 39 23](https://user-images.githubusercontent.com/13667038/30151632-db81f1da-93b8-11e7-8914-e334e13c07e0.png)

Otherwise, it's great update and I'll continue to use Quokka! Thank You!

**Comment by ArtemGovorov** [comment]
@volotovskyy Awesome, thanks for the update! 
Gray box is expected, those [boxes represent code coverage](https://quokkajs.com/docs/#live-code-coverage-basic-feature). The gray one means that the line of code hasn't been executed - nothing in the Quokka file calls the `render` function.

**Comment by volotovskyy** [comment]
@ArtemGovorov Cool. Got it!
This was epic battle! I'm really happy that issue has been fixed!
Thank you.

**Comment by Dimomir** [comment]
Hi @ArtemGovorov 
I hope it's okay to continue the discussion here, I'm also happy to open a new issue if that's the preferred approach.

I keep getting the same `​​Unexpected token import​​` error. I'm using 
VS Code `1.16.1`
 and 
Quokka extension `1.0.66`

The code beings like 
```import React from 'react';
import PropTypes from 'prop-types';

import BpkInput, { INPUT_TYPES } from 'bpk-component-input';
```

Which is interesting as the `import` for React works but not for my installed libraries? Is that a clue as to why it's still failing?



Full error for reference:
```​​​​Quokka #1 (node: v7.0.0, babel: v6.26.0)​​​​
​​​​
​​Unexpected token import​​
  at ​​​Object.exports.runInThisContext​​​ ​vm.js:76​
  at ​​​Module._compile​​​ ​module.js:545​
  at ​​​Module._extensions..js​​​ ​module.js:582​
  at ​​​Object.require.extensions.(anonymous function) [as .js]​​​ ​/Users/dimodimov/.quokka/node_modules/babel-register/lib/node.js:152​
  at ​​​Module.load​​​ ​module.js:490​
  at ​​​tryModuleLoad​​​ ​module.js:449​
  at ​​​Function.Module._load​​​ ​module.js:441​
  at ​client/src/components/ExperimentTableFilter/ExperimentTableFilterComponent.jsx:4​
```


Quokka config.json:


```{
  "pro": true,
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  },
  "env": {
    "params": {
      "env": "BABEL_ENV=dev"
    }
  }
}```

**Comment by ArtemGovorov** [comment]
@Dimomir Thanks for providing the config and the failing code.

Looks like the you are hitting this issue https://github.com/wallabyjs/quokka/issues/82, because the `bpk-component-input` node module is published with ES6 imports/exports (instead of being published as CommonJs like the majority of node modules), and babel(-register) ignores `node_modules` by default.

All you need to do is to specify [babel `ignore` setting](https://babeljs.io/docs/usage/api/#options) to ignore all node modules but `bpk-*`.

```diff
{
  "pro": true,
  "babel": {
+   "ignore" : "node_modules/(?!bpk-)",
    "presets": [
      "es2015",
      "react"
    ]
  },
  "env": {
    "params": {
      "env": "BABEL_ENV=dev"
    }
  }
}
```

**Comment by Dimomir** [comment]
@ArtemGovorov 
Thanks for the speedy reply mate!

Adding the ignore takes me a step further and then I have some more problems to solve :)

I keep getting
```
​​​​Quokka #2 (node: v7.0.0, babel: v6.26.0)​​​​
​​​​
​​./client/node_modules/bpk-component-text/src/BpkText.js: Unexpected token (33:66)​​
  at ​./client/node_modules/bpk-component-text/src/BpkText.js
```
​It would appear it happens only when something is being destructured e.g. `const { className, ...rest } = props;`
to solve it I add 
```
"plugins": [
      "transform-object-rest-spread"
    ]
``` 
to my config at which point with the suggested changes it looks like

```
{
  "pro": true,
  "babel": {
    "ignore" : "node_modules/(?!bpk-)",
    "presets": [
      "es2015",
      "react"
    ],"plugins": [
      "transform-object-rest-spread"
    ]
  },
  "env": {
    "params": {
      "env": "BABEL_ENV=dev"
    }
  }
}
```

That seems to get it to work

I really appreciate you taking the time to help out! 👍
