### ISSUE TITLE
There are no output when i change data

### ISSUE THREAD

**Issue by Lake1GitHub** [wallabyjs/quokka#310]
### Issue description or question
There is my :
![image](https://user-images.githubusercontent.com/20634106/50429674-c9ae4b80-08fa-11e9-8ebf-bf2ffed4c197.png)

There is your :
![image](https://user-images.githubusercontent.com/20634106/50429791-4e00ce80-08fb-11e9-8ba2-b48b34e11b3d.png)

I have reload much tims but it's useless.
Is it my misconfiguration?
### Sample code

```
function add(a, b){
    return a+b;
}
var result = add(1, 3);

console.log(result);
```

### Code editor version

Visual Studio Code

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Looks like your Quokka is not started. Try [starting it with the `Ctrl + K, Q`](https://quokkajs.com/docs/#live-feedback) on the file. If it is started, then check/share the output from Quokka console output channel.
