### ISSUE TITLE
Quokka Not updating values

### ISSUE THREAD

**Issue by ovidius72** [wallabyjs/quokka#312]
### Code editor version
Visual Studio Code v1.30.1
### OS name and version
OSX

I'm running quokka in a .ts file in VSCode. The file imports another files containing a plain javascript object.
It works fine but when I make some changes to the .ts file or to the imported one quokka output is still the same as the first time it was started. I see the console and the inline values refreshing but the values are always the old ones.
I'm running it using "Run on save for current file"
I would expect that changes on the imported files could be not updated, but on the current running file I expect live updates.
Is there anything i could have missed in the configuration ? Or maybe it's because i'm importing another file ?

Thanks.

**Comment by smcenlly** [comment]
Quokka has 3 modes of execution:
1) `Start on Current File` - Quokka runs as you change your file or when any of your project files change)
2) `Run on save for Current File` - Quokka only runs when your file contents change and the file is saved.
3) `Run once for Current File` - Quokka will run once and report results to your Quokka output/editor window.

As you are using the command, `Quokka.js: Run on save for Current File`, Quokka will only run if:

1) there are changes to the contents of the file, and
2) you save the file using `Cmd+S` or `File->Save/Save All`.

If only your import file changes, Quokka will not run. If your import file changes and you then make changes to your file, Quokka will re-execute.

If you want Quokka to be running continuously as you make changes to your file, please use the command, `Quokka.js: Start on Current File` (`cmd+k q`).

If this is still not working for you, please provide us with a sample, we'd be happy to take a look. Our contrived sample worked for us:

**Typescript file (test.ts)**
```typescript
import * as im from './importFile';

im.foo();

var a = 0;

a //?
```

**Javascript file (importFile.js)**
```javascript
exports.foo = function() {
  console.log('foo');
}
```
