### ISSUE TITLE
quokka corrupted my node js package

### ISSUE THREAD

**Issue by Remo-Somesh** [wallabyjs/quokka#313]
I installed quokka js plugin for VS code and apparently uninstalled it later. Now if I try to run my Javascript files via command prompt (Windows), I get this message 'Kindly provide your Email ID for recording your purchase'. Kindly help me out with the situation.

### Quokka.js Console Output
Kindly provide your Email ID for recording your purchase

### Code editor version

Visual Studio Code v1.30.1

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
During install, uninstall and execution, Quokka does not touch any files outside of

`%USERPROFILE%/.vscode/extensions/wallabyjs.quokka-vscode-%VERSION%`, and `%USERPROFILE/.quokka`. Quokka also does not adjust any `path` settings/variables.

This message must be coming from another source and is not related to Quokka.

Additionally, the message you are describing is not something any of our software asks for.
