### ISSUE TITLE
Live Result won't show

### ISSUE THREAD

**Issue by miorfs** [wallabyjs/quokka#314]
### Live result won't show
I just installed using VS Code version 1.30.1 on mac. The problem is the live result won't show and as I know the live results is available for community. Below is the example of my code. I already tried both 3 option to run Quokka but nothing happen. Please help.

### Sample code

```javascript
const quokka = {
    isAwesome = true
}

console.log(quokka);
```

### Quokka.js Console Output

```
// nothing happen here
```

### Code editor version

Visual Studio Code v1.30.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
First of all, the code you are using doesn't look valid. Try:

```js
const quokka = {
    isAwesome: true
}

console.log(quokka);
```

Second, looks like you haven't shared Quokka Console Output. The output should at least Quokka header.

If the suggestion above doesn't help, please do the following:
- share a screenshot of your Quokka output channel in VS Code,
- copy& paste output from Dev Tools Console (`Help - Toggle Developer Tools`).

**Comment by miorfs** [comment]
> First of all, the code you are using doesn't look valid. Try:
> 
> ```js
> const quokka = {
>     isAwesome: true
> }
> 
> console.log(quokka);
> ```
> 
> Second, looks like you haven't shared Quokka Console Output. The output should at least contain Quokka header.
> 
> If the suggestion above doesn't help, please do the following:
> 
> * share a screenshot of your Quokka output channel in VS Code,
> * copy& paste output from Dev Tools Console (`Help - Toggle Developer Tools`).

Already tried your code, but still nothing happen, and I'm trying to run 'Quokka:Run once for current file' but it is not happen because it said I have to purchase for pro to use this feature. Is it true? So this Live Result is not for community?

**Comment by ArtemGovorov** [comment]
`Quokka:Run once for current file` is a pro feature, however Live Results is free/community feature, you just need to run `Quokka Start on Current File`.

**Comment by miorfs** [comment]
> `Quokka:Run once for current file` is a pro feature, however Live Results is free/community feature, you just need to run `Quokka Start on Current File`.

Just changed from `Quokka:Run once for current file` to `Quokka:Start on current file` and it works! Thanks!
