### ISSUE TITLE
After react-app config, doesn't work on regular JS files

### ISSUE THREAD

**Issue by danchamorro** [wallabyjs/quokka#317]
### Issue description or question
I have added the necessary configuration for Quokka to work with create-react-app and it works in React, but now when I try and use it on a regular Javascript file I get:

### Sample code

```javascript
{
  "pro": true,
  "plugins": ["jsdom-quokka-plugin"],
  "babel": {
    "presets": ["react-app"]
  }
}
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
Configured to use babel, but can not find babel-core or @babel/core module​​
​​Babel core is not found​​
```

### Code editor version

Visual Studio Code Version 1.30.2

### OS name and version

OSX 10.14.2

**Comment by danchamorro** [comment]
OK, I think I got it to work correctly here is what I did: 

I removed the following from the Global Quoka file `config.json`:
```javascript
 "babel": {
    "presets": ["react-app"]
  }
```
Then in my projects `package.json` file I added: 
```javascript
"quokka": {
    "babel": {
      "presets": [
        "react-app"
      ]
    }
  }
```
Now it works in React and on regular Javasciprt files as well, but I did notice some behavior I wasn't expecting, and maybe this is the way Quokka is intended to work. From the screenshot below you can see that it works above the class component but does not work in the `render()` even though it's above the return statement. 

![image](https://user-images.githubusercontent.com/19739839/51081962-d4bef500-16ca-11e9-806e-089124d05bab.png)

**Comment by ArtemGovorov** [comment]
>  From the screenshot below you can see that it works above the class component but does not work in the render() even though it's above the return statement.

Quokka just run the code in the file. Nothing in the file is calling the `render` method, so everything seems to be working as expected.

**Comment by danchamorro** [comment]
Thanks for the reply. What about in this scenario should I be able to see the response with Quokka?
```javascript
import React, { useState, useEffect } from "react";
import axios from "axios";

export default function App() {
  const [results, setResults] = useState([]);
  const [query, setQuery] = useState("reacthooks");

  useEffect(() => {
    axios
      .get(`http://hn.algolia.com/api/v1/search?query=${query}`)
      .then(res => {
        console.log(res.data); // Quokka Not Showing Here
        setResults(res.data.hits);
      });
  }, []);
```

**Comment by ArtemGovorov** [comment]
Nothing in the file calls your `App` function, so no results are expected. 
Quokka is not a linter - it doesn't analyse your code, it runs it. Imagine that your file is a small node program and you run it in node - that's what quokka does. If you run the code above in node, nothing happens.

**Comment by danchamorro** [comment]
Thanks for the quick reply. I guess I was confused as to how it all worked. I saw some videos online where people are fetching data from API and the data showed up in Quokka. But then again they weren't using React and it was in a regular javascript file. Thanks Again.

**Comment by ArtemGovorov** [comment]
You may use React too, just need to call your function right in the file (like `render` in the first example or `App` in the second one). If there's enough context set and you can run them, then Quokka will show coverage/inline results inside the functions.
