### ISSUE TITLE
​​Must call super constructor in derived class before accessing 'this' or returning from derived constructor​​

### ISSUE THREAD

**Issue by jamelcole-ah** [wallabyjs/quokka#318]
### Issue description or question
I have made an extension of the RegExp class, which requires that I modify the string input to function correctly. The function which is modifying the string, is a global function which makes no references to "this". But i still get this error. 

​​`Must call super constructor in derived class before accessing 'this' or returning from derived constructor​​`

### Sample code

```javascript
function stripParts ( pattern: string ) {
    let namedCapture = /\<\?(.*?)\>/g;
    let names = pattern.replace(namedCapture,( match: string , ...args )=>{
        console.log(match, args);
        return "";
    });
//contrived example
return names;
}
class RevExp extends RegExp {
    flag : string ;
    name: string; 
    tokens: [];
    offset: number;
    globalPattern: RegExp;
    startPattern: RegExp;

    static registry:object = {};
    private static savedAttributes: object = {}
    private __attributes: any[] = [];
    private __queries: any[] = [];
    private partNames: object = {};

    constructor( pattern:string, flag?:string, name?:string ){
        pattern = stripParts(pattern);
        
        super(pattern, flag);
        // this.flag = flag; 
        this.name = name;
...
}
}
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​Quokka 'index2.ts' (node: v10.14.1, TypeScript: v3.2.2)​​​​
​​​​
​​Must call super constructor in derived class before accessing 'this' or returning from derived constructor​​
  at ​​​new RevExp​​​ ​index2.ts:34:8​
  at ​​​Object.<anonymous>​​​ ​index2.ts:219:0​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:688​

```

### Code editor version

Visual Studio Code v1.30.2
Quokka Pro

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Could you please provide full output from Quokka Console (it should include node and TypeScript versions)?

**Comment by jamelcole-ah** [comment]
I've updated my last comment to have the full console output! sorry about that.

**Comment by ArtemGovorov** [comment]
Thanks! I can't reproduce the issue with the code above and the same node/TS version. Here is the code I use:

```ts
function stripParts ( pattern: string ) {
    let namedCapture = /\<\?(.*?)\>/g;
    let names = pattern.replace(namedCapture,( match: string , ...args )=>{
        console.log(match, args);
        return "";
    });
//contrived example
return names;
}
class RevExp extends RegExp {
    flag : string ;
    name: string; 
    tokens: [];
    offset: number;
    globalPattern: RegExp;
    startPattern: RegExp;

    static registry:object = {};
    private static savedAttributes: object = {}
    private __attributes: any[] = [];
    private __queries: any[] = [];
    private partNames: object = {};

    constructor( pattern:string, flag?:string, name?:string ){
        pattern = stripParts(pattern);
        
        super(pattern, flag);
        // this.flag = flag; 
        this.name = name;
}
}

new RevExp('<?>')
``` 

and here's the result I'm getting:

<img width="618" alt="screen shot 2019-01-15 at 11 13 36 am" src="https://user-images.githubusercontent.com/979966/51151446-a3a31800-18b6-11e9-968f-db0cb53fefd1.png">

Could you please try my code above to see if you are getting the error, and if yes, then please share your `tsconfig.json` file.

**Comment by ArtemGovorov** [comment]
I tried running your code above (had to add empty `ret` and `countParens` functions because the sample code was failing w/o them):

```ts
function stripParts ( pattern: string ) {
    let namedCapture = /\<\?(.*?)\>/g;
    let names = pattern.replace(namedCapture,( match: string , ...args )=>{
        console.log(match, args);
        return "";
    });
    return names;
}

function ret(){}
function countParens(){}

class RevExp extends RegExp {
    flag : string ;
    name: string; 
    tokens: [];
    offset: number;
    globalPattern: RegExp;
    startPattern: RegExp;

    static registry:object = {};
    private static savedAttributes: object = {}
    private __attributes: any[] = [];
    private __queries: any[] = [];
    private partNames: object = {};

    constructor( pattern:string, flag?:string, name?:string ){
        pattern = stripParts(pattern);
        
        super(pattern, flag);
        // this.flag = flag; 
        this.name = name;
        this.tokens = ret(pattern); //this is being imported, but with or without it it throws error
        this.offset = countParens(pattern) //ditto as above
        this.globalPattern = new RegExp(pattern, "g");
        this.startPattern = new RegExp("^"+pattern, flag);
    }
   
}

new RevExp('<?>')
```

but it it still working as expected for me:

<img width="813" alt="screen shot 2019-01-15 at 11 30 07 am" src="https://user-images.githubusercontent.com/979966/51152760-efef5780-18b8-11e9-9826-b3c1b73c881c.png">

Could you please check if the code is working for you, and if yes, please share a sample that doesn't.

**Comment by jamelcole-ah** [comment]
Copying your code still gives me an error in my console... **Shrugz**

![image](https://user-images.githubusercontent.com/45606658/51153508-5b87e500-1825-11e9-8c9f-6bf4d2d35f01.png)

**Comment by ArtemGovorov** [comment]
Could please share your `tsconfig.json` file? I'm running your sample without any project opened, but your `tsconfig.json` may be affecting compilation.

**Comment by jamelcole-ah** [comment]
sorry... i meant to put this in the last comment. 

```javascript
ts.json
{
    "compilerOptions": {
        "target": "esNext",
        "module": "commonjs",
        "sourceMap": true
    }
}
```

**Comment by ArtemGovorov** [comment]
Thanks. With the config (this line specifically `"target": "esNext",`) I'm able to reproduce the issue. The issue is not related to Quokka though, you may observe the same error if you compiled your code with `tsc` and run the resulting JavaScript.

Here is the simplest example:

```js
class RevExp extends RegExp {
    p: object = {};
    constructor() {
        pattern = '';
        super('');
    }
}

new RevExp()
```

The code above is compiled (with or without Quokka) to JavaScript that throws the error:

```js
​​​class RevExp extends RegExp {​​​
​​​    constructor() {​​​
​​​        this.p = {};​​​
​​​        pattern = '';​​​
​​​        super('');​​​
​​​    }​​​
​​​}​​​
new RevExp();​​​
```

As you may see, to initialise the `p` property, generated JavaScript has to run `this.p = ...`, hence the error.

Also, the error is reported by VS Code TypeScript compiler even prior to running your code (if you hover over the constructor body):

<img width="645" alt="screen shot 2019-01-15 at 12 51 21 pm" src="https://user-images.githubusercontent.com/979966/51155768-58900180-18c4-11e9-9b89-1625a29adf49.png">
