### ISSUE TITLE
Async Mongoose calls not showing output in quokka

### ISSUE THREAD

**Issue by e1um** [wallabyjs/quokka#319]
My node console logs the value for a mongoose call to my Mongodb, but it doesn't get printed by quokka. Am I doing something wrong?

```
const getUser = async email => {
  const user = await User.findOne({ email }).then(res => res);
  return user;
};

function test(email) {
  return getUser(email);
}

test('test@test.com').then(res => {
  console.log(res);
});

```

<img width="555" alt="screen shot 2019-01-18 at 12 36 46 pm" src="https://user-images.githubusercontent.com/5743404/51403460-87a1af80-1b1e-11e9-89c0-eeb689b0970b.png">

Visual Studio Code v1.30.2
OSX Mojave 10.14.1

**Comment by ArtemGovorov** [comment]
As coverage gray indicators on your screenshot display, the code that logs the response never gets called. Given the limited context, it's hard to tell why - maybe there's an error being thrown, maybe there's a connection timeout. Try 
- adding error handling and checking Quokka console output for any hints;
- also try running the code in plain node to check if the output you expect is being displayed. 

If the suggestions above don't help, please create a sample repo demonstrating the issue, we are happy to take a look.
