### ISSUE TITLE
Quokka still not working on fresh create-react-app

### ISSUE THREAD

**Issue by raymiS** [wallabyjs/quokka#322]
Hello, I know this might be an already closed issue, but I just installed Quokka on my VS Code to run it on a `create-react-app` for some classes and still having trouble with the configuration and also is not showing me any output

I used the `package.json` configuation option.
```javascript
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "quokka": {
    "babel": true
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
Also I wanted to know if I have a functional component where to test quokka. In the code below I tried to console log the `<App />` component after the render method is called but I'm not sure if this is right. 

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<App />, document.getElementById('root'));

console.log(App);
serviceWorker.unregister();
```

### Repository link

[Quokka Test React Repository](https://github.com/raymiS/quokka-test)

### Quokka Console Output 

```​​​​Quokka 'index.js' (node: v8.9.4)​​​​
​​​​
​​$_$w(1, 0), ReactDOM.render(<App/>, document.getElementById('root'));​​
​​                            ^​​
​​​​
​​SyntaxError: Unexpected token​​
```
### Code editor version

Visual Studio Code v1.30.2

### OS name and version

macOs Mojave: 10.14 

Any help will be gladly appreciated. Thanks!

**Comment by ArtemGovorov** [comment]
Adding babel preset to your Quokka config should help - https://github.com/wallabyjs/quokka/issues/227#issuecomment-407266213

> Also I wanted to know if I have a functional component where to test quokka. In the code below I tried to console log the <App /> component after the render method is called but I'm not sure if this is right.

Quokka simply runs your code in node (with jsdom if required). So if your code above runs in plain node (and is correct), then Quokka should run it too.
