### ISSUE TITLE
Feature request: console.log produces unnecessary newlines in the VSCode console

### ISSUE THREAD

**Issue by lonix1** [wallabyjs/quokka#323]
I'm not sure if this is related to #151 .

I'm using VSCode.

When using `console.log(...)` in a quokka file, the vscode console shows a newline between each entry. It takes up too much space, I need to scroll every time, even for just a few logs.

**Comment by dfrechdev** [comment]
I am using Quokka with the PRO license and would appreciate this feature as well. Is there already a plan to include this in a future release?

And also, if you could disable the location information at the end of the log (eg "some logging at some.js:4:8"). Maybe as a setting. Especially for presentation both are a distraction from what you want to show.

**Comment by smcenlly** [comment]
@dfrechdev - need to review a couple of things, but we should be able to add this feature within the next week or so. If you track this issue, you'll get notified when it's available.

I don't quite understand the problem with including the line/column. Can you provide a bit more detail on what you're suggesting so we can understand how it's distracting?

**Comment by smcenlly** [comment]
We've added a new VS Code setting, `quokka.compactMessageOutput`. Please set to `false` for compact messages. The default is `true`.

**Comment by dfrechdev** [comment]
Fantastic, thank you Simon! Regarding my other point: Besides the live comments feature I also need console.log statements at some instances to show program flow. The console.log output prints the log message, but behind that the location from where the log originates, so for example "my log message at index.js:4:8". My wish would be that (maybe when the compactMessageOutput setting is set to true), it only prints the log message and nothing else (it ommits the "at index.js:4:8" part). If that's possible. Hope this clarifies my request.

**Comment by smcenlly** [comment]
We don't believe excluding the `file:line:column` is something that most of our users will want. If you'd still like this as a feature, please add another issue and if we get enough interest from our other users, we'll implement it.
