### ISSUE TITLE
log of iterator or condition in for, while, if

### ISSUE THREAD

**Issue by iofjuupasli** [wallabyjs/quokka#324]
### Issue description or question
It would be nice to log iterator on each step of loop, and condition in the case when comment added after the statement.
`for` can output the result of the third part `++i`
`while` outputs result of condition for each iteration
`if` outputs the result of a condition

### Sample code

```javascript
for (let i = 0; i < 10; ++i) {//?
}
if (10 > 42) {//?
}
```

### Quokka.js Console Output
No output

### Code editor version
Atom v1.?

### OS name and version
Linux

**Comment by smcenlly** [comment]
We've made some changes to improve handling of `update` statements in `for` and `while` loops, and for the `test` clause of `if` statements. Check it out, we'd love your feedback. The syntax is a little different to what you had proposed to stay close to the logical elements that you want to instrument.

Taking your example above, you would love those expressions as shown below:

```javascript
for (let i = 0; i < 10; ++i) /*?*/ {
}
if (10 > 42) /*?*/ {
}
```
