### ISSUE TITLE
Feature request: simpler logging

### ISSUE THREAD

**Issue by lonix1** [wallabyjs/quokka#325]
Quokka makes it easy to quickly test something. However most of the time that means lots of `console.log()` statements.

In other REPL environments I've used it was possible to shorten heavily used statements to ease rapid coding. So would be really helpful to do one or both of these instead:

````
log(foo);
l(foo);
````

So quokka would treat them as synonyms for `console.log()`.

**Comment by ArtemGovorov** [comment]
Quokka Pro supports 
- [live comments feature](https://quokkajs.com/docs/#live-comments), that allows to log things without `console.log` with a simple `//?` comment;
- [live value display feature](https://quokkajs.com/docs/#live-value-display), that allows to log things **without typing anything**, just by running a command with a shortcut:

![q](https://user-images.githubusercontent.com/979966/51959381-cbda6b80-249f-11e9-9274-7e3e584d3da7.gif)

**Comment by lonix1** [comment]
Cool features, thanks.
