### ISSUE TITLE
A green square means that the source line has not been executed.

### ISSUE THREAD

**Issue by stevenlupo** [wallabyjs/quokka#328]
Sorry, but didn't know where to ask this. Is there a typo on this docs page https://quokkajs.com/docs/index.html:

It says:
A green square means that the source line has not been executed.

Shouldn't it say:
A green square means that the source line has been executed.

**Comment by smcenlly** [comment]
This is the best place to report Quokka issues (including our website). Thanks for letting us know about the problem in our docs. It's been fixed.
