### ISSUE TITLE
API Docs hooks

### ISSUE THREAD

**Issue by PaulRosset** [wallabyjs/quokka#329]
### Issue description or question

Hello :)

I may miss something but where I can't find the full documentation of the API to create custom plugin.  
I only see the docs [here](https://quokkajs.com/docs/extensibility.html) but only 2 hooks are defined. It could only have 2 hooks (`before` and `beforeEach`) but just I want to be sure then.

Thanks :)

**Comment by ArtemGovorov** [comment]
> It could only have 2 hooks (`before` and `beforeEach`) but just I want to be sure then.

Yes, it is the case. The docs at https://quokkajs.com/docs/extensibility.html fully describe the current API.
