### ISSUE TITLE
allow configuration of predefined globals

### ISSUE THREAD

**Issue by Pyrolistical** [wallabyjs/quokka#33]
### Issue description or question
We need a way to predefine globals or env like eslint

### Quokka.js file

```javascript
// a mocha or jest test
describe('yada', () => {
});
```

### Quokka.js Console Output

```
describe is not defined​​
```

### Code editor version

Visual Studio Code v1.11.0-insider

### OS name and version

OSX 10.12.4

**Comment by Pyrolistical** [comment]
nevermind, i get it its only useful as a scratch pad

**Comment by ArtemGovorov** [comment]
Yep, for unit testing you may be interested to [check out wallaby.js features](https://wallabyjs.com/).

**Comment by rollrodrig** [comment]
I have the same problem. I bought Quokka so... there should be any configuration to skip `describe is not defined​​` because it make the Quokka crash. Or it mean that is necessary i have to buy wallaby?

**Comment by smcenlly** [comment]
Quokka is a scratch pad, not a test runner, so unless you import external dependencies or set up describe beahvior, it is not going run your test for you or inherently know one way or another about describe. We have a [section in our Quokka.js docs](https://quokkajs.com/docs/quokka-vs-wallaby.html) that describes the difference between Quokka.js and Wallaby.js.

**Comment by rollrodrig** [comment]
> Quokka is a scratch pad, not a test runner, so unless you import external dependencies or set up describe beahvior, it is not going run your test for you or inherently know one way or another about describe. We have a [section in our Quokka.js docs](https://quokkajs.com/docs/quokka-vs-wallaby.html) that describes the difference between Quokka.js and Wallaby.js.

I don't wanna run the test, i am just writing in the test file. Maybe Quokka should have some option to ignore `describe()` error method.
