### ISSUE TITLE
Feature request: Display pre-defined code/text/comments

### ISSUE THREAD

**Issue by PaulRosset** [wallabyjs/quokka#330]
### Issue description or question

Hello :)

I would find very useful to have the possibility to config **pre-defined** code/texts/comments when the user will open a new **Quokka** file to avoid redundant scafolding that could be annoying.

I'm explaining myself: 

  - In the config file, add a property, `templating`, that wait a `path` to a templating file.
  - In this file, we can insert text/code, then when the user will open a new **Quokka** file, the text inserted in the previous templating file will be in the new opened file.

Of course, there are many others way to do it, I'm explaining this to give just an idea of the feature, but I think this feature can lead to a better experience, but also less redundant actions and set up.

Thanks :)

**Comment by smcenlly** [comment]
@PaulRosset - what editor are you using?

**Comment by PaulRosset** [comment]
@smcenlly I’m using VS Code.

**Comment by Alexsey** [comment]
There is a [plug-in for VS Code](https://marketplace.visualstudio.com/items?itemName=brpaz.file-templates) that allows you to create file templates, but I think it's more suitable to use [live templates](https://www.freecodecamp.org/news/the-most-powerful-tool-to-boost-your-coding-productivity-2dc80e0eff00/). IntelliJ IDEs is also supporting all this stuff out of the box (file template, live templates, postfix completion)

I don't think there is any reason to duplicate this functionality in Quokka

**Comment by smcenlly** [comment]
@Alexsey - we agree. Going to close this issue and not introduce as a Quokka feature.
