### ISSUE TITLE
Quokka doesn't find Babel config file

### ISSUE THREAD

**Issue by kutenai** [wallabyjs/quokka#331]
### Issue description or question
I am experiencing major frustration with Quokka. Every. Single. Time I try and use it, I get issues. I've never been able to figure out WTF it wants, or expects by way of a configuration. I've read the VERY POOR configuration documents 10 times - literally. WHY IS THIS SO HARD???

### Sample code

```javascript
// paste the code you are running here
import { normalize, schema } from 'normalizr'

```

That's it -- import a module. Quokka gives me this:
```
Quokka #1 (node: v10.11.0, babel: v7.2.2)

Unexpected token {
	at new Script vm.js:79
	at createScript vm.js:251
	at Object.runInThisContext vm.js:303
	at Module._compile internal/modules/cjs/loader.js:657
```

WHY WHY WHY WHY WHY!!!!
I have installed normalyzr in my ~/.quokka node_modules
```
{
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel": "^6.23.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-polyfill": "^6.26.0",
    "jsdom-quokka-plugin": "^1.0.13",
    "lodash": "^4.17.5",
    "normalizr": "^3.3.0",
    "rambda": "^2.3.0",
    "ramda": "^0.26.1",
    "underscore": "^1.8.3"
  },
  "dependencies": {
    "alias-quokka-plugin": "^0.1.0",
    "babel-alias-quokka-plugin": "^1.0.9",
    "install": "^0.12.1",
    "npm": "^6.4.1"
  }
}
```

There is no way to 'debug this'... that I know of. I'm just so frustrated. I've spent nearly an hour JUST TRYING TO GET THE DANG THING TO WORK!! I never even started working on the thing I wanted to work on. What is the point of a "tool to save you time", if the tool simply COSTS YOU TIME!!

I'm really pissed off if you can't tell because I am not getting my value from this tool, because it frustrates the hell out of me each time I try and use it. 

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
Quokka #1 (node: v10.11.0, babel: v7.2.2)

Unexpected token {
	at new Script vm.js:79
	at createScript vm.js:251
	at Object.runInThisContext vm.js:303
	at Module._compile internal/modules/cjs/loader.js:657

```

### Code editor version

PyCharm 2018.3

### OS name and version

OSX

**Comment by kutenai** [comment]
I've tried to create .babelrc. I've created babbel.config.js, but It isn't clear that quokka is using these. In fact, it seems like quokka is NOT using them, but I have no way to know what quokka IS finding (does it find .babelrc? babel.config.js)? No idea.

If I change my ~/.quokka/config.json file to look like this:
```
{"babel":presets: ["es2015", "react"],"plugins":[],"pro":true}
```

Then things work, but the documentation says I should be able to use .babelrc... so, why doesn't that work? I've tried about every combination of that I can think of.

**Comment by smcenlly** [comment]
With our %USER%\.quokka\config.json set to:

```json
{"pro": true, "babel": true}
```

Quokka is then picking up our .babelrc file in our project directory.

Is that working for you?

If not, can you please share your project structure with us (what you have open in PyCharm). A screenshot will suffice.

**Comment by lShinal** [comment]
I have the same issue.

**Comment by lShinal** [comment]
I have the same issue.
I'm trying to add @babel / plugin-proposal-pipeline-operator. Although I described the dependencies in .babelrc and also installed the plugins via npm, qoukka.js does not see this plugin in my IDE. 
it's look like quokka can't see babel config. 

### Sample code
~/.quokka/config.json file
```json
{"pro": true, "babel": true}
```

~/.quokka/.babelrc 

```json
{
  "presets": ["@babel/preset-env", " @babel/preset-react"],
  "plugins": [
    ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ]
}

```

console output in webStorm 

`Add @babel/plugin-proposal-pipeline-operator (https://git.io/vb4SU) to the 'plugins' section of your Babel config to enable transformation.
`

**Comment by lShinal** [comment]
maybe its trouble with nvm?

**Comment by smcenlly** [comment]
The `~/.quokka` configuration is limited to the `config.json` file and any packages that exist in `~/quokka/node_modules`. When quokka runs, it will look for your `.babelrc` file at the project level, not at the global level. If you want to have global settings for babel transformations, you need to put them in your `config.json` file. See an example below:

```json
{
  "pro":true, 
  "babel": {
    "presets": ["@babel/preset-env", " @babel/preset-react"],
    "plugins": [
      ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties", { "loose": true }]
    ]
  }
}
```
