### ISSUE TITLE
Using TSLint

### ISSUE THREAD

**Issue by inlet** [wallabyjs/quokka#334]
### Issue description or question

Is it possible to enable your projects `tslint.json` in scratch files?

### Sample code

For example this overload cannot be tested without tslint.

```ts
// function test(a: string): string;
// function test(a: any[]): any[];
function test(a: string | any[]) {
  return a;
}

test([1, 2, 3]).reverse();

// without tslint it's all fine
// with tslint: Property 'reverse' does not exist on type 'string | any[]'.
```

### Code editor version

PHPStorm 2018.3

### OS name and version

OSX (10.14.3 Mojave)

And thanks for creating such a great product, I'm really loving it!

**Comment by ArtemGovorov** [comment]
Thanks for using Quokka. Unfortunately the issue is out of the plugin scope - it is the issue in PhpStorm not supporting TS services in scratch files. Please feel free to subscribe to/vote up the issue at https://youtrack.jetbrains.com/issue/WEB-17352.

**Comment by inlet** [comment]
Just upvoted, thanks!
