### ISSUE TITLE
Configuring Gutter Icon Color in VS Code

### ISSUE THREAD

**Issue by larryschirmer** [wallabyjs/quokka#335]
### Issue description or question

I use both Wallaby and Quokka in VS Code. One of the first things I did was change the gutter icon color in Wallaby because the default green, yellow, red, and pink all kind of look the same to me (red-green color blindness) [Very easy for Wallaby](https://wallabyjs.com/docs/intro/get-started-vscode.html#changing-icon-colors)

I couldn't find in the documentation how to change the colors for Quokka though. Is there an editor setting like in Wallaby I can use to change colors for Quokka?

Thanks!

### Code editor version

Visual Studio Code v1.32.0-insider

### OS name and version

OSX

**Comment by smcenlly** [comment]
This is supported in a similar way to `wallaby`. In your vscode configuration file, add a section for `quokka.colors`. Please see the example below:

```json
...
  "quokka.colors": {
    "covered": "#62b455",
    "errorPath": "#ffa0a0",
    "errorSource": "#fe536a",
    "notCovered": "#ff0000",
    "partiallyCovered": "#d2a032"
  }
...
```

We will update our Quokka documentation to include these settings.
