### ISSUE TITLE
VT (Vertical tab?) Characters shown in output window

### ISSUE THREAD

**Issue by jafin** [wallabyjs/quokka#336]
### Sample code

```javascript
console.log('hello world');
```

### Quokka.js Console Output
![image](https://user-images.githubusercontent.com/127927/52981354-05611f80-342b-11e9-85b3-cc2a4536b472.png)

When i copy the character into Notepad++ it identifies as 'VT'  (vertical tab?)

### Code editor version
Visual Studio Code v1.31.1

**Comment by smcenlly** [comment]
Sorry for the slow reply, we fixed this yesterday. If you haven't already, please download the latest version, Quokka v1.0.189.
