### ISSUE TITLE
Quokka does not recognize JS reserved word "prompt"

### ISSUE THREAD

**Issue by MadDogDean** [wallabyjs/quokka#338]
### Issue description or question
Quokka does not recognize the JS reserved word prompt and returns an "prompt is not defined" error
All further processing by Quokka is terminated
![quokka prompt not defined](https://user-images.githubusercontent.com/23712335/53384008-71580080-39b4-11e9-8ce9-f57117796aaa.jpg)
![quokka prompt commented out](https://user-images.githubusercontent.com/23712335/53384017-761cb480-39b4-11e9-9280-dc2f25aca15e.jpg)

### Sample code

```javascript
var answer = prompt ("Is Quokka awesome?")
const quokka = {
    isAwesome: true
}
console.log(quokka) 
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
prompt is not defined 
  at ​​​Object.<anonymous>​​​ ​starter/script.js:470:0​
```

### Code editor version

Visual Studio Code v1.31.1
Quokka 1.0.189
Electron 3.1.2
Node.js 10.2.0

### OS name and version

Win7 x64 6.1.7601

**Comment by ArtemGovorov** [comment]
Quokka runs in node, and `prompt` (`window.prompt` to be more precise) is a browser specific thing. 

You may enable browser-like environment (via `jsdom`) in Quokka with a plugin as described at https://github.com/wallabyjs/jsdom-quokka-plugin, or by changing your code to:

```
var answer = window.prompt ("Is Quokka awesome?")
const quokka = {
    isAwesome: true
}
console.log(quokka)
```

and following the instructions in the Quokka output panel.
Please note however, that `jsdom` doesn't fully support `prompt`, your code will run though.

**Comment by MadDogDean** [comment]
Thanks, Is there a way to configure Quokka so that it identifies errors (such as the prompt not defined error), without terminating the remaining process?
Sort of a "identify the problem but skip over it?"
Cheers

**Comment by ArtemGovorov** [comment]
There's nothing special in Quokka to skip errors. Generally speaking, ignoring runtime errors may produce even more errors further down the execution path. If you have a piece of code that you don't really care whether it errors or not, you may try putting it in a `try-catch` block.

**Comment by MadDogDean** [comment]
No problem. Thanks
