### ISSUE TITLE
PRO Multiple instances 

### ISSUE THREAD

**Issue by michaelwclark** [wallabyjs/quokka#339]
### Issue description or question
<3 you guys first of all. I use this every day!

Secondly I'm running multiple projects in VSCode at all times. (front end, back end, npm modules, plus misc instances for whatever else). 

At times I try a Quokka on another instance i get a message (see screenshot): 

Is there anyway to fix this?
### Quokka.js Console Output

![screen shot 2019-02-27 at 3 15 42 pm](https://user-images.githubusercontent.com/1590766/53523495-92971a80-3aa2-11e9-93c3-87117382cf8f.png)

### Code editor version

Visual Studio Code  v1.31.1 (1.31.1)

### OS name and version
OSX : 10.14.3

**Comment by smcenlly** [comment]
We've made some tweaks in the latest version of Quokka for VS Code (v1.0.190). Please upgrade as this should fix your problem.
