### ISSUE TITLE
Doesn't work with TypeScript and JSX

### ISSUE THREAD

**Issue by slikts** [wallabyjs/quokka#340]
### Issue description or question

JSX doesn't work with TypeScript. Secondarily, ESLint doesn't work either because it doesn't pick up the project configuration and can't parse TS without it.

### Sample code

Any TypeScript with JSX.

### Quokka.js Console Output

I have no idea how to access the Quokka.js console.

### Code editor version

Visual Studio Code v1.13.1

### OS name and version

macOS High Sierra

**Comment by smcenlly** [comment]
I've broken the issue down into three parts:
1) Using TypeScript with JSX
2) ESLint doesn't work
3) Quokka Console Output

**Using TypeScript with JSX**

To use TypeScript with JSX within Quokka, depending on your tsconfig.json you may need to override your configuration in Quokka.

By default, Quokka will use your `tsconfig.json` settings, and compile using the JSX options specified there. These are detailed in the [TypeScript Documentation](https://www.typescriptlang.org/docs/handbook/jsx.html).

For Quokka to be able to run your file, the `jsx` setting must be set to `react`. If you do not want to change your `tsconfig.json`, you may override this in Quokka by providing a custom configuration ([described in our docs](https://quokkajs.com/docs/configuration.html)).

For example, if you create a `.quokka` file in your project root, you can override the TypeScript setting with the contents:

```json
{
  "ts": {
    "compilerOptions": {
      "jsx": "react"
    }
  }
}
```

If you are using Quokka with `jsx`, you may also have code that interacts with the DOM, in which case, you will also benefit from using [jsdom-quokka-plugin](https://github.com/wallabyjs/jsdom-quokka-plugin). If you install that plugin, your final configuration file will look like this:

```json
{
  "ts": {
    "compilerOptions": {
      "jsx": "react"
    }
  },
  "plugins": [
    "jsdom-quokka-plugin"
  ]
}
```

Once you've configured Quokka, you will be able to run your `tsx` file, for example:

```TypeScript
import React, { Component } from 'react';

const result = <h1>It works!</h1>

result //?
```

Will return something like:
![image](https://user-images.githubusercontent.com/2074089/53995424-bb916c80-4180-11e9-976b-fb1b60d8141e.png)

**ESLint doesn't work**
I don't understand your comment re: ESLint, can you please provide more information with details of your issue (what is the error, expectation and steps to reproduce)?

**Quokka Console Output**
The Quokka Console Output is the window that you see when you first start Quokka. In VS Code, it appears as an `output` window with the name `Quokka`. Please see the sample screenshot below. If you're not seeing this, please let us know.
![image](https://user-images.githubusercontent.com/2074089/53995750-c5679f80-4181-11e9-8722-68e896492132.png)

**Comment by ArtemGovorov** [comment]
Re: ESLint doesn't work

Quokka doesn't affect ES Lint. It may be VS Code/ES Lint plugin issue that it doesn't support temporary files (in which case you may save the file and run Quokka on an existing file).

Re: Using TypeScript with JSX

Please try @smcenlly suggestions, and if it still doesn't work for you, please create a sample repo demonstrating the issue, we are happy to take a look.
