### ISSUE TITLE
quokka vscode extension makes a space in status bar

### ISSUE THREAD

**Issue by Xiongqi-XQ** [wallabyjs/quokka#353]
### Issue description or question
when enable the quokka vscode extension, there will be a space in the status bar
![image](https://user-images.githubusercontent.com/25862498/55934212-7ae6b080-5c62-11e9-97aa-d21277647811.png)

### Code editor version

Visual Studio Code v1.33.0

### OS name and version
OSX mojave 10.14.4

**Comment by smcenlly** [comment]
Thanks for reporting this issue. We've fixed this in the latest version of Quokka for VS Code, v1.0.207. It should be available in the VS Code marketplace in a few hours.
