### ISSUE TITLE
Quokka errors on clean vue cli3 repo

### ISSUE THREAD

**Issue by PatrickKennedy** [wallabyjs/quokka#358]
### Issue description or question
I'm running on a pristine instance of Vue CLI3 and getting the error represented below. This is also happening the same on a larger project I'm trying to include quokka in. I've been at it for a while (was having issues getting a plugin to run because it didn't indicate the .quokka json was invalid ><) so if there's anything I'm missing, apologies in advance

### Sample code
![image](https://user-images.githubusercontent.com/80598/56553196-e5dd9480-654a-11e9-8f32-0c7ad97eb07a.png)\

.quokka (happens the same with and without directly specifying the `@vue/app` plugin)
```json 
{ babel: true }
```

### Sample repository link
This is for internal development at a bank and my personal laptop is a Chromebook so getting code uploaded to github is... a challenge

### Code editor version
Visual Studio Code v1.???

### OS name and version
Windows 10 17.x

**Comment by smcenlly** [comment]
By default, the vue babel configuration expects your files to be bundled by webpack. Quokka runs in `node`, which means that your `import` statements need to be converted to `commonjs` style. You can lean on vue's babel configuration setting to do this for you just as you would if running `jest` tests. The easiest way to get this working is to create a `.quokka` configuration file in your project with an environment setting of `VUE_CLI_BABEL_TRANSPILE_MODULES=true`. Please see the example below:

```json
{
  "babel": true,
  "env": {
    "params": {
      "env": "VUE_CLI_BABEL_TRANSPILE_MODULES=true"
    }
  }
}
```

The only other item to note is that we were prompted to install `@babel/register`  to be able to run the necessary transforms.

Another way of solving this problem would be to explicitly configure the babel presets that you want to use when you run `quokka`. In your case, you could specify `@vue/app` and `@babel/preset-env`.
