### ISSUE TITLE
Display private properties like __proto__ in value explorer

### ISSUE THREAD

**Issue by felikf** [wallabyjs/quokka#360]
### ~~Issue~~ description or *question*
Is it possible to show private object properties in value explorer, like `__proto__`?

### Sample code
![image](https://user-images.githubusercontent.com/13978154/57013852-bcd59780-6c0d-11e9-9588-e29a540f0cd1.png)

Webstorm v2019.1.2

**Comment by ArtemGovorov** [comment]
Not at the moment, because Quokka is using `get​OwnProperty​Names` to get the list of properties. Having said that, you may still inspect it in Value Explorer if you access it in your code:

```js
person.__proto__//?
```

**Comment by felikf** [comment]
OK thanks, it would be nice to have an option to display all properties.
