### ISSUE TITLE
Basic highlighting to identify type of output

### ISSUE THREAD

**Issue by RDhar** [wallabyjs/quokka#363]
### Issue description or question

**_Is it possible to apply basic syntax highlighting to the output to identify its type?_**

For comparison, this is done in Chrome's Dev Console by applying an accent colour to `number` types that is different from the default colour applied to `string`. Furthermore, `undefined` has a different grey colour to identify its type as well. In essence, it just helps quickly identify whether a number is a `number` or a `string`.

### Sample code (includes Quokka.js Console Output)

Spent a little too long on this...

| Code                  | Quokka Output | Chrome Dev Tools |             Same              | TypeOf |
| :-------------------- | :-----------: | :--------------: | :---------------------------: | :----: |
| `log('' + 1 + 0);`    |      10       |        10        |    :ballot_box_with_check:    | string |
| `log('' - 1 + 0);`    |      -1       |       `-1`       | :negative_squared_cross_mark: | number |
| `log(true + false);`  |       1       |       `1`        | :negative_squared_cross_mark: | number |
| `log(6 / '3');`       |       2       |       `2`        | :negative_squared_cross_mark: | number |
| `log('2' * '3');`     |       6       |       `6`        | :negative_squared_cross_mark: | number |
| `log(4 + 5 + 'px');`  |      9px      |       9px        |    :ballot_box_with_check:    | string |
| `log('$' + 4 + 5);`   |     \$45      |       \$45       |    :ballot_box_with_check:    | string |
| `log('4' - 2);`       |       2       |       `2`        | :negative_squared_cross_mark: | number |
| `log('4px' - 2);`     |      NaN      |      `NaN`       | :negative_squared_cross_mark: | number |
| `log(7 / 0);`         |   Infinity    |    `Infinity`    | :negative_squared_cross_mark: | number |
| `log(' -9 ' + 5);`    |     -9 5      |       -9 5       |    :ballot_box_with_check:    | string |
| `log(' -9 ' - 5);`    |      -14      |      `-14`       | :negative_squared_cross_mark: | number |
| `log(null + 1);`      |       1       |       `1`        | :negative_squared_cross_mark: | number |
| `log(undefined + 1);` |      NaN      |      `NaN`       | :negative_squared_cross_mark: | number |

### System Details (including Code Editor and OS Version)

**Version**: VS Code 1.33.1 (user setup) \
**Electron**: 3.1.6 \
**Chrome**: 66.0.3359.181 \
**Node.js**: 10.2.0 \
**V8**: 6.6.346.32 \
**OS**: Windows_NT x64 10.0.17763

**Comment by rdhar** [comment]
Coming back to this over a year little, and realized it's very similar to #61 with regards to better distinction between different data types.

It's unfair to compare to Chrome' DevTools as that can vary the font family between Sans Serif and Monospace to easily distinguish between strings and numbers. Whereas, Quokka is limited to the default font family in VS Code.

Perhaps, it might be an idea to either:

1. Implement quotation marks to distinguish strings.
2. Introduce options for data types to have different font colours.

I think the 2nd option would be preferred to avoid confusing outputs which already include quotation marks. In addition, by having it as an option, existing users won't be impacted by the change and can choose to opt-in/customize, if they'd like.

Worth considering?
