### ISSUE TITLE
console error when importing a service - `ts-node` module must be installed

### ISSUE THREAD

**Issue by chrisj-skinner** [wallabyjs/quokka#365]
When using Quokka on a angular cli build that includes a service call / import there is a console error (see quokka console output and screenshots 1&2)
When the import is removed Quokka works fine (see screenshot 3)

### Steps taken
```javascript
ng serve
```
Open `app.component.ts`
Run: Quokka.js Start on current file

### Sample repository link
https://github.com/chrisj-skinner/quokka-angular-test

### Quokka.js Console Output

```
Quokka 'app.component.ts' (node: v9.10.1, TypeScript: v3.4.3)​​​​
 
To import TypeScript files from quokka, `ts-node` module must be installed 
  at ​​​Module.load​​​ ​module.js:561​
  at ​​​tryModuleLoad​​​ ​module.js:501​
  at ​​​Function.Module._load​​​ ​module.js:493​
  at ​​​require​​​ ​internal/module.js:11​
  at ​​​Object.<anonymous>​​​ ​quokka-angular-test/src/modules/app/app.component.ts:2​
  at ​​​Module._compile​​​ ​module.js:649​
```

### Code editor version

Visual Studio Code v1.33.1

### OS name and version

OSX v10.13.6

Screenshot 1
<img width="936" alt="Screen Shot 2019-05-14 at 10 15 38" src="https://user-images.githubusercontent.com/5794048/57689300-2eaed780-7637-11e9-9f78-3be7e3949785.png">
Screenshot 2
<img width="656" alt="Screen Shot 2019-05-14 at 10 15 56" src="https://user-images.githubusercontent.com/5794048/57689305-340c2200-7637-11e9-855c-8274186adb20.png">
Screenshot 3
<img width="648" alt="Screen Shot 2019-05-14 at 10 55 03" src="https://user-images.githubusercontent.com/5794048/57689315-38383f80-7637-11e9-80ec-500f1b73fd48.png">

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo, could you please also share your `~/.quokka/config.json` file?

**Comment by chrisj-skinner** [comment]
I don't currently have one setup.

**Comment by smcenlly** [comment]
If you haven't already tried this, could you please clone to a fresh directory, run `npm install` and try again?

**Comment by ArtemGovorov** [comment]
> I don't currently have one setup.

Quokka would not be able to run at all if you did not have the file. Please double check and share your `~/.quokka/config.json` file.

**Comment by chrisj-skinner** [comment]
@smcenlly Tried a fresh clone and `npm install`. Still hitting the same issues.

@ArtemGovorov Contents of the `~/.quokka/config.json` file 

```
{"pro":true}
```

**Comment by smcenlly** [comment]
Can you please try the following steps exactly:

1) Close all instances of VS Code
2) Launch VS Code
3) Select File->Open Folder `quokka-angular-test`
4) Select your project (`node_modules` should exist in this directory)
5) Open `src\modules\app\app.component.ts`
6) Run command, `Quokka.js: Start on Current File`

The only possible explanation that we have right now is that you're working in a mono repo or have a folder open other than the project that has the file you're trying to run.

**Comment by chrisj-skinner** [comment]
Thanks - it worked when opening just the folder `quokka-angular-test`
Previously I had my `dev` folder open which contains `quokka-angular-test`

Running it out of a parent folder throw up the old error again. Interesting...

Thanks for the help
