### ISSUE TITLE
Typescript with decorators

### ISSUE THREAD

**Issue by joaovpmamede** [wallabyjs/quokka#366]
I'm using the `"experimentalDecorators": true` on my `tsconfig.json` file and everything runs fine but as soon as I try to start quokka on a file it gives me this error:

```
Quokka 'user.test.ts' (node: v11.4.0, TypeScript: v3.4.5)​​​​

{"message":"⨯ Unable to compile TypeScript:\npackages/graphql/src/resolvers/user.ts(24,7): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this
```

I've followed the [docs](https://quokkajs.com/docs/configuration.html#typescript) and installed `ts-node` on global config folder.

my project's tsconfig.json:
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "references": [{ "path": "../core" }, { "path": "../test-utils" }]
}
```
My editor is also with `"javascript.implicitProjectConfig.experimentalDecorators": true`

Visual Studio Code v1.33.1

OSX

**Comment by ArtemGovorov** [comment]
Unfortunately we can't reproduce the issue. Decorators (when configured in the project's root `tsconfig.json`) are working as expected:

<img width="733" alt="Screen Shot 2019-05-15 at 11 03 39 pm" src="https://user-images.githubusercontent.com/979966/57777657-b430a580-7765-11e9-964e-3754741ef155.png">


Please create and share a sample project where we could reproduce the issue, we are happy to take a look.

**Comment by joaovpmamede** [comment]
Well it's definitely something on my project as I've created a new one to test the decorators and everything work as expected.

Will close this now and thanks for your answer.
