### ISSUE TITLE
Is it possible to use quokka during debug (webstorm)

### ISSUE THREAD

**Issue by rparree** [wallabyjs/quokka#368]
hi,

Is it possible to use quokka during a debug session (i am using webstorm):

- set a breakpoint
- be able to use quokka with the runtime context available (similar to "evaluate expressions")

**Comment by ArtemGovorov** [comment]
> set a breakpoint

Quokka executes your code immediately as you type, so the idea is not set/use any breakpoints, but see the results immediately.

> be able to use quokka with the runtime context available (similar to "evaluate expressions")

You may evaluate any expression by `console.log`-ing it (or using [live comments](https://quokkajs.com/docs/?editor=jb#comments)) and then using [Value Explorer](https://quokkajs.com/docs/?editor=jb#value-explorer).

**Comment by rparree** [comment]
Hi Artem,

Thanks for your reply.

What i meant was using quokka during a debugging of an  application

tx.,

**Comment by ArtemGovorov** [comment]
Ah, got it. Quokka runs your code separately from a debugging session. While you can run both WS debugger and Quokka at the same time, the tools' results are not synchronised in any way.

**Comment by aderchox** [comment]
CTRL+K+E to disable quokka and then F5 to add breakpoints and debug using node.js and then again CTRL+K+Q. (For people visiting here in future)
