### ISSUE TITLE
Jest-marbles: expect is not defined

### ISSUE THREAD

**Issue by felikf** [wallabyjs/quokka#369]
### Issue description or question
Running sample code in Webstorm gives me following error: _expect is not defined_

### Sample code
```
({
    "jest": true
})

import { hot } from 'jest-marbles';

const a$ = hot('--a|');

a$.subscribe(a => {
    console.log(a);
});
```

package.json:
```
"devDependencies": {
    "jest-marbles": "=2.3.1",
    "jest": "=24.8.0",
}
```

### Quokka.js Console Output

```typescript
Quokka #1 (node: v11.10.0, TypeScript: v3.2.4)

expect is not defined
	at Object.0 ./node_modules/jest-marbles/umd/jest-marbles.js:12033
	at ./node_modules/jest-marbles/umd/jest-marbles.js:97
	at Module._compile internal/modules/cjs/loader.js:738
	at Object.Module._extensions..js internal/modules/cjs/loader.js:749
	at Module.load internal/modules/cjs/loader.js:630
	at tryModuleLoad internal/modules/cjs/loader.js:570
	at Function.Module._load internal/modules/cjs/loader.js:562
	at require internal/modules/cjs/helpers.js:20
	at Object.<anonymous> quokka.ts:5
	at Module._compile internal/modules/cjs/loader.js:738

```

### Code editor version

Webstorm v2019.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Quokka simply runs your code as node program. Running the same code file without Quokka in node produces the same result. If you manage to run your code in node without Quokka, then Quokka will also be able to run it.

It also looks like you are trying to run tests and we have another product called [Wallaby](https://wallabyjs.com/docs/#get-started) that had been designed to run tests (and supports Jest), so you may be interested in taking a look at it too.

**Comment by felikf** [comment]
Thanks, I have wallaby too. It works as you say in wallaby. What I presume quokka to be is a magic box :) I thouth it should work. If I manage to define global object with `expect` it should work .. I guess.

**Comment by ArtemGovorov** [comment]
> If I manage to define global object with expect it should work .. I guess.

If you define global expect prior to importing `jest-marbles` it may work. My understanding is that the package was designed to work within loaded Jest context, so Wallaby running your Jest tests may be a better way to run it.

I think Jest should define `expect` global at some point, but I'm not sure what Jest package defines it, also AFAIK Jest creates separate execution contexts with separate globals, so it may not be that easy.
