### ISSUE TITLE
Configuration for long arrays live comments

### ISSUE THREAD

**Issue by slavik57** [wallabyjs/quokka#37]
Suppose I have a large array with a live comment:
```javascript
const a = [1,2,3,4,5,6,7,8,9,10,11,12];/*?*/
```
and now I log its value:
```javascript
console.log(a);
```

It prints:
```javascript
​​​​​[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ... ]​​​​​
  at ​​​[
    1,
    2,
    3,
    4,
    5,
   ...​​​ ​src/quokka.ts:1:0​
​​​​​​​​​​
​​​​​[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]​​​​​
  at ​​​a​​​ ​src/quokka.ts:2:0​
```

The problem is even worse when I try to access the array later:
```javascript
a[11];/*?*/
```
It prints:
```javascript
undefined​​​​​ at ​​​a[11]​​​ ​src/quokka.ts:4:0​
```

It would be nice to have some kind of configuration I could set on a specific line to make quokka consider all the array and not part of it
For now the solution I found is to omit the /*?*/ on the first line

Visual Studio Code v1.11.2
Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issues is fixed and the fix is published in v1.0.27.
