### ISSUE TITLE
How to connect js and html file - newbie

### ISSUE THREAD

**Issue by pimangit** [wallabyjs/quokka#370]
### Issue description or question
I am a novice programmer. I have read all the documentation but I have no idea how to cause Quokka Pro to see the js file and connect to the appropriate html. Probably it is obvious to most people here, but unfortunately I have a problem.
- I have Quokka Pro
- I install plugin jsdom-quokka-plugin
- I need help with next step :)

Thank you very much for help.

### Example
The simplest possible situation.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <title>Test 1</title>
</head>
<body>
    <div id="testDiv">123</div>
    <script type="text/javascript" src="test.js"></script>
</body>
</html>
```

```javascript
//test.js
const div = document.querySelector("#testDiv");
console.log(div.textContent); //expected "123"
// console shows everything OK
```

### Quokka.js Console Output

```
​​​​Quokka 'test.js' (node: v10.15.3, plugins: jsdom-quokka-plugin)​​​​
 
Cannot read property 'textContent' of null 
  at ​test1.js:2:0​
  at ​​​Object.<anonymous>​​​ ​./test1.js:5​
```

### Code editor version

Visual Studio Code v1.34

### OS name and version

Windows

**Comment by smcenlly** [comment]
To get this working, you need to load your html content into JSDOM.

Check out the jsdom npm package page for examples (https://www.npmjs.com/package/jsdom).

From their `Basic usage` section:

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
console.log(dom.window.document.querySelector("p").textContent); // "Hello world"
```

**Comment by smcenlly** [comment]
If you want to load an existing file you can also use the `jsdom` `fromFile()` method:

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

JSDOM.fromFile('test.html').then(dom => {
  dom.window.document.querySelector("p").textContent //?
});
```

Another way of loading the file is by adding a jsdom setting section to your `.quokka` configuration:

```
{
...
    "jsdom": {
        "file": "./index.html"
    }
...
}
```
