### ISSUE TITLE
Supporting Meetup?

### ISSUE THREAD

**Issue by michaelwclark** [wallabyjs/quokka#374]
### Issue description or question
I'm an organizer and frequent speaker at DSM JS, our local Des Moines Javascript user group. I'm putting together a presentation on Quokka and how amazing and awesome it is. As I was going through the planning it got me thinking how cool it would be to have you guys host our event.

We have had 3rd party tech host before (cloudflare and some others) in exchange for presenting their tech before or during the talk. 

If you guys are open to hosting we would do an intro video for you and during my talk I'll be selling Quokka's awesomeness. We also tweet out kudos and links from our sponsors leading upto the event. 

Other sponsors have sent sticker packs and discount codes as well to get the local devs onboard. Usually sponsorship includes buying a round of pizzas for the group (generally less than 30 people) and/or covering the venue costs ($30-$50). If you guys are interested at all in doing this in any way I'd love to talk more about the details of hosting and what I've been planning for presentation around Quokka if you are interested. 

Thanks so much for what you all do. It's helped me teach so many concepts very quickly and code better and faster myself! :) You all are rockstars, keep it up!

**Comment by smcenlly** [comment]
Thanks for the kind words and for considering us. Please send us an email to discuss further (hello@wallabyjs.com).
