### ISSUE TITLE
nvm current symlink does not work

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/quokka#376]
### Issue description or question

nvm current symlink does not work

```json
{
    "pro": true,
    "babel": true,
    "node": "~/.nvm/current/bin/node"
}
```

<img width="476" alt="Screen Shot 2019-05-30 at 12 30 20 PM" src="https://user-images.githubusercontent.com/1595871/58659174-3200bf00-82d7-11e9-944e-cc81a5e91ab0.png">

### Code editor version

```
WebStorm 2019.2 EAP
Build #WS-192.4205.48, built on May 27, 2019
```

### OS name and version

`macOS 10.14.5`

**Comment by smcenlly** [comment]
Thanks for reporting this issue. This has been fixed in the latest version of Quokka for IntelliJ, v1.0.170.
