### ISSUE TITLE
Quokka restarts when switching between open files ("tabless" IntelliJ)

### ISSUE THREAD

**Issue by fuusle** [wallabyjs/quokka#377]
### Issue description or question
When using the "tabless*" interface in Intellij (or any of the Jetbrains-ideas, I belive) Quokka restarts when tabbing between files. That is to say, when leaving the current Quokka-scratch-file to look at another file, and then come back to said scratch-file, Quokka restarts (not re-run, but actually restarts). This take a couple of seconds and "disturbs" the otherwise smooth flow of Quokka.  

Is this intentional? 

### Code editor version
IntelliJ: 2019.1 (but it is the same for all versions, I belive) 

### OS name and version
OSX

* tabless = Turning the tab-placement to "None" in the settings

**Comment by ArtemGovorov** [comment]
It is intentional unfortunately. The "tabless*" interface in IntelliJ actually disposes editors when you switch between files (not just hides them, but destroys editor instances), so in order to correctly free resources and display indicators Quokka has to stop/start too.
