### ISSUE TITLE
Support ts-node (install automatically when required?)

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/quokka#378]

**Comment by chrisblossom** [comment]
Just an idea, might be a good idea to utilize [npm's `npx`](https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner) command if not found to utilize their cache.

**Comment by inithink** [comment]
+1

**Comment by smcenlly** [comment]
Quokka now installs ts-node by default and no longer requires additional packages to be installed.
