### ISSUE TITLE
Attempting to use pro version with react-native

### ISSUE THREAD

**Issue by MadisonCourto** [wallabyjs/quokka#379]
### Issue description or question

I'm trying to get Quokka to work with react-native, I have added the following to my package.json as per the documentation, but I am receiving an error when attempting to start Quokka against an existing .tsx file.

### Sample code

```javascript
"quokka": {
    "babel": {
      "presets": [
        "env",
        "react-native"
      ]
    }
  },
```
### Quokka.js Console Output

```
 Unexpected token < 
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
>  start Quokka against an existing .tsx file.

In order to run Quokka on TypeScript files with Babel, you need to set `"ts": true,` under "babel" Quokka setting as described at https://quokkajs.com/docs/configuration.html#using-babel-to-compile-typescript. 

If the solution suggested above doesn't help, please create a sample repo demonstrating the issue, we are happy to take a look and help with the configuration.

**Comment by MadisonCourto** [comment]
What would you like in the repo, I can't exactly share NDA code. This is really starting to bug me, I have spent far too long trying to get this to work.

I'm now getting this;

`Failed to run compilers on src/ui/screens/production_calculator_screen/ProductionCalculatorScreen.tsx, TypeError: Cannot read property 'bindings' of null `

**Comment by ArtemGovorov** [comment]
> What would you like in the repo

We don't need the actual source code, and it looks like the issue may not related to any actual source code in your repo. Try this:
- copy&paste your repo to a new folder, 
- delete all source files but configs (package.json, babel config, tsconfig) and the `src/ui/screens/production_calculator_screen/ProductionCalculatorScreen.tsx` file. 
- see if the issue is still reproducible by running Quokka on the ProductionCalculatorScreen.tsx file,
- if it is reproducible, try removing all sensitive code from the file (until there's some bare minimum of code in it, but the issue is still reproducible).
- share the stripped down repo (you may remove most of package.json - we only need dependencies/devDependencies and babel settings from it).

**Comment by MadisonCourto** [comment]
Ok it appears to be failing due to;

`export class ProductionCalculatorScreen {

}`

If I remove everything bar the above it produces the same error, here is my package.json and tsconfig, I don't have a babe config file.

`
 "quokka": {
    "babel": {
      "ts": true,
      "presets": [
        "react-native"
      ]
    }
  },
"dependencies": {
    "@babel/plugin-transform-typescript": "^7.4.5",
    "@types/jquery": "^3.3.29",
    "@types/react-native-video": "^2.0.8",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.5",
    "buffer": "^5.2.1",
    "class-transformer": "^0.1.10",
    "eslint": "^3.17.0",
    "g": "^2.0.1",
    "http": "0.0.0",
    "jsdom-quokka-plugin": "^1.0.14",
    "react": "^16.3.1",
    "react-native": "^0.55.4",
    "react-native-device-info": "^0.21.5",
    "react-native-fused-location": "^0.2.1",
    "react-native-keychain": "^3.0.0",
    "react-native-network-info": "^3.2.2",
    "react-native-photo-view": "^1.5.2",
    "react-native-photo-view-ex": "^1.0.4",
    "react-native-render-html": "^3.10.0",
    "react-native-screenshot-detector": "^1.0.0",
    "react-native-vector-icons": "^6.4.2",
    "react-native-video": "^2.3.1",
    "react-native-video-controls": "^2.2.3",
    "react-navigation": "^2.18.3",
    "react-zlib-js": "^1.0.4",
    "reflect-metadata": "^0.1.13",
    "ts-node": "^8.2.0",
    "tsutils": "^2.29.0",
    "webpack": "^2.7.0"
  },
  "devDependencies": {
    "@types/jest": "^23.3.14",
    "@types/node": "^12.0.4",
    "@types/react": "^16.8.10",
    "@types/react-native": "0.56.1",
    "@types/react-native-photo-view": "^1.5.3",
    "@types/react-native-vector-icons": "^4.6.4",
    "@types/react-navigation": "^2.13.10",
    "@types/react-test-renderer": "^16.8.1",
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "^4.0.1",
    "jest": "23.4.1",
    "react-native-typescript-transformer": "^1.2.12",
    "react-test-renderer": "16.4.1",
    "reactotron-cli": "^1.7.0",
    "reactotron-react-native": "^3.5.2",
    "ts-jest": "^23.10.5",
    "tslint": "^5.14.0",
    "tslint-config-airbnb": "^5.11.1",
    "tslint-react": "^3.6.0",
    "typescript": "^3.0.1"
  },`

tsconfig.json

`{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "jsx": "react-native",
    "lib": [
      "es6"
    ],
    "module": "es6",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": true,
    "target": "es6",
    
  },
  "exclude": [
    "node_modules"
  ]
}`

**Comment by ArtemGovorov** [comment]
Thanks for providing the additional details. 

Quick Googling of the full error text/stack indicates that the issue is related to Babel 6 vs Babel 7 compatibility issues.

Your project has both versions of Babel (6 and 7) installed. By default Quokka is using the latest version of Babel that it can find. The version of react native that you are using is using Babel 6, so you just need to [let Quokka know to use Babel 6](https://quokkajs.com/docs/configuration.html#babel-path):

```diff
  ...
  "quokka": {
    "babel": {
      "ts": true,
+     "path": "./node_modules/babel-core",
      "presets": [
        "react-native"
      ]
    }
  },
```

**Comment by MadisonCourto** [comment]
Thanks but now I'm getting a lot more errors, such as;

```
Quokka 'Icon.d.ts' (node: v10.15.3, babel: v6.26.3)​​​​
SyntaxError: node_modules/@types/react-native-vector-icons/Icon.d.ts: Unexpected token, expected { (156:25) 
  154 |     size?: number, 
  155 |     color?: string, 
> 156 |   ): Promise<ImageSource>; 
      |                          ^ 
  157 |   static loadFont( 
  158 |     file?: string 
  159 |   ): Promise<void>; 
```

**Comment by ArtemGovorov** [comment]
> Quokka 'Icon.d.ts' (node: v10.15.3, babel: v6.26.3)​​​​

From your log it looks like you are (mistakenly?) starting Quokka on a `.d.ts` file (`Icon.d.ts`). There's normally nothing to run in a .d.ts file.

**Comment by MadisonCourto** [comment]
Right I get that, but when I try to run it against ProductionCalculatorScreen.tsx
I get the following;

```
Quokka 'ProductionCalculatorScreen.tsx' (node: v10.15.3, babel: v6.26.3)​​​​
 
Unexpected identifier 
  at ​​​new Script​​​ ​vm.js:80​
  at ​​​createScript​​​ ​vm.js:274​
  at ​​​Object.runInThisContext​​​ ​vm.js:326​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:664​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:712​
  at ​​​Object.require.extensions.(anonymous function) [as .js]​​​ ​./node_modules/babel-register/lib/node.js:152​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:600​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:539​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:531​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:637​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.<anonymous>​​​ ​./src/ui/screens/production_calculator_screen/Header.tsx:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
  at ​​​loader​​​ ​./node_modules/babel-register/lib/node.js:144​
  at ​​​Object.require.extensions.(anonymous function) [as .tsx]​​​ ​./node_modules/babel-register/lib/node.js:154​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:600​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:539​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:531​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.<anonymous>​​​ ​src/ui/screens/production_calculator_screen/ProductionCalculatorScreen.tsx:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
```

Which is referring  to import { Header } from './Header'; on line 3 of ProductionCalculatorScreen
Header.tsx then throws;

```
​​​​Quokka 'Header.tsx' (node: v10.15.3, babel: v6.26.3)​​​​
 
Unexpected identifier 
  at ​​​new Script​​​ ​vm.js:80​
  at ​​​createScript​​​ ​vm.js:274​
  at ​​​Object.runInThisContext​​​ ​vm.js:326​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:664​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:712​
  at ​​​Object.require.extensions.(anonymous function) [as .js]​​​ ​./node_modules/babel-register/lib/node.js:152​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:600​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:539​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:531​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.<anonymous>​​​ ​src/ui/screens/production_calculator_screen/Header.tsx:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
```

Referring to `import { default as SimpleLineIcons } from 'react-native-vector-icons/SimpleLineIcons';`
which is Icon.d.ts, or am I mistaken?

**Comment by ArtemGovorov** [comment]
Looks like `react-native-vector-icons/SimpleLineIcons` module source is published as ES6 module and `babel-register` is not compiling `node_modules` by default. You may use solution described at

https://github.com/wallabyjs/quokka/issues/31#issuecomment-332164600
https://github.com/wallabyjs/quokka/issues/82#issuecomment-325996625


```diff
  "quokka": {
    "babel": {
+     "ignore": "node_modules/(?!react-native-)",
      "ts": true,
      "path": "./node_modules/babel-core",
      "presets": [
        "react-native"
      ]
    }
  },
```

**Comment by MadisonCourto** [comment]
```
​​​​Quokka 'Header.tsx' (node: v10.15.3, babel: v6.26.3)​​​​
 
Cannot find module 'NativeModules' 
  at ​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:582​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:508​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:637​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.get NativeModules [as NativeModules]​​​ ​./node_modules/react-native/Libraries/react-native/react-native-implementation.js:109​
  at ​​​Object.get [as NativeModules]​​​ ​./node_modules/react-native-vector-icons/lib/react-native.js:1​
  at ​​​Object.<anonymous>​​​ ​./node_modules/react-native-vector-icons/lib/ensure-native-module-available.js:4​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
  at ​​​loader​​​ ​./node_modules/babel-register/lib/node.js:144​
  at ​​​Object.require.extensions.(anonymous function) [as .js]​​​ ​./node_modules/babel-register/lib/node.js:154​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:600​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:539​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:531​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:637​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.<anonymous>​​​ ​./node_modules/react-native-vector-icons/lib/create-icon-set.js:11​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
  at ​​​loader​​​ ​./node_modules/babel-register/lib/node.js:144​
  at ​​​Object.require.extensions.(anonymous function) [as .js]​​​ ​./node_modules/babel-register/lib/node.js:154​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:600​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:539​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:531​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:637​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.<anonymous>​​​ ​./node_modules/react-native-vector-icons/SimpleLineIcons.js:6​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
  at ​​​loader​​​ ​./node_modules/babel-register/lib/node.js:144​
  at ​​​Object.require.extensions.(anonymous function) [as .js]​​​ ​./node_modules/babel-register/lib/node.js:154​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:600​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:539​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:531​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:22​
  at ​​​Object.<anonymous>​​​ ​src/ui/screens/production_calculator_screen/Header.tsx:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:701​
```

**Comment by MadisonCourto** [comment]
Even if I remove the import I'm getting a bunch of other errors, this is a joke, can I request a refund?

**Comment by ArtemGovorov** [comment]
@MadisonCourto Please send us an email to hello@wallabyjs.com and we'll arrange it for you.
