### ISSUE TITLE
feature: flow support

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/quokka#38]
Would love to see this as this is what I primarily use, and I can't open pre-existing files that use Flow.

**Comment by ArtemGovorov** [comment]
Quokka [supports babel](https://quokkajs.com/docs/configuration.html#babel), you you have the `.babelrc` with Flow configured, [quokka can handle it](https://quokkajs.com/docs/configuration.html#babel).

**Comment by ArtemGovorov** [comment]
You may check our this example: https://github.com/wallabyjs/quokka-react-sample. It doesn't have flow configured in the .babelrc, but the rest (react, jsdom, babel) is there.

**Comment by vasco3** [comment]
I have the same issue. not sure what I am missing...

quokka.js
```js
({
  pro: true,
  babel: true,
  plugins: ['jsdom-quokka-plugin'],
  env: {
    params: {
      env: 'BABEL_ENV=test',
    },
  },
});
```

.babelrc
```js
{
  "env": {
    "development": {
      "plugins": ["transform-flow-strip-types"],
      "presets": ["next/babel"]
    },
    "production": {
      "plugins": ["transform-flow-strip-types"],
      "presets": ["next/babel"]
    },
    "test": {
      "plugins": ["transform-flow-strip-types"],
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]
    }
  }
}
```

util.js
```js
// @flow
export function calculatePercent(
  unixSecondsStart: number,
  unixSecondsNow: number,
  unixSecondsGoal: number,
): number {
  const totalSeconds = unixSecondsGoal - unixSecondsStart;
  const leftSeconds = unixSecondsNow - unixSecondsStart;
  return leftSeconds / totalSeconds * 100;
}
```

Output

> ​​​​Quokka #1 (node: v8.9.0)​​​​
​​SyntaxError: Unexpected token (3:18)​​

**Comment by ArtemGovorov** [comment]
@vasco3 Just added your code/config to this sample repo branch: https://github.com/wallabyjs/quokka-react-sample/tree/38, and running Quokka on [this file](https://github.com/wallabyjs/quokka-react-sample/blob/38/quokka.js) is working for me as expected:

<img width="591" alt="screen shot 2018-05-13 at 5 38 38 pm" src="https://user-images.githubusercontent.com/979966/39965024-97400586-56d4-11e8-8418-18f23dfb5fec.png">


Could you please clone the repo to see if it's working for you and fork it the bits I'm missing to reproduce the issue.

**Comment by vasco3** [comment]
Thanks @ArtemGovorov !
It does work within quokka.js but doesn't work on a separate file. 
I run `Quokka.js: Start on Current File`

btw I'm using VSCode.

**Comment by ArtemGovorov** [comment]
@vasco3 I'm also using the `Start on Current File` command and VS Code. Could you please fork the sample repo and add your scenario so I could reproduce it?

**Comment by Cwejman** [comment]
I too can't run quokka in a separate file using flow, this is what i've done:

I've cloned the reproduction repo: [quokka-react-sample](https://github.com/wallabyjs/quokka-react-sample/tree/38) and quokka runs as it should in the quokka.js file. Running quokka in another file with flow seems fine aswell but not when importing a flow-typed function from another .js file. Was this the case for you too @vasco3?

 I've made a reproduction repo: [quokka-babel-flow-sample](https://github.com/Cwejman/quokka-babel-flow-sample).

To reproduce:
1. Install npm dependecies
2. Run quokka in `src/math.js` and you'll see it works fine.
3. Run quokka in `src/index.js` and it'll throw an error.

To make sure there is nothing wrong with the babel setup I made this repo: [rollup-babel-flow-sample](https://github.com/Cwejman/rollup-babel-flow-sample). Babel successfully builds a flow stripped file here.

Is this unexpected behaviour? If any other material is needed, I'll be glad to help.

**Comment by ArtemGovorov** [comment]
@Cwejman When Quokka runs on a file, it uses its babel config. However for imported files, `@babel/register` is used and it is trying to find/use standard babel config(s), such as `.babelrc`. Once I add the `.babelrc` to your repo https://github.com/Cwejman/quokka-babel-flow-sample/pull/1 (there is one in your `rollup-babel-flow-sample` repo), then running Quokka on `src/index.js` starts working.

**Comment by ArtemGovorov** [comment]
@Cwejman So, Quokka should be passing using its own babel config (as you have it configured) for babel register as well (babel register is processing imported files). Babel register will also try to merge any other babel configs it finds. It was working for Babel 6, but was broken in Babel 7 beta. Now it is fixed in the latest published version, please update Quokka extension for your editor and it should work for you.

**Comment by Cwejman** [comment]
Updating to v1.0.74 solves the issue.

Thanks!

**Comment by Alacho2** [comment]
I'm opening this again as it seems to still be an issue with types. 
`type SomeValue = "string1" | "string2.`

Yielding:

> Failed to instrument components/mail/import.js
>    5 | import storeAccount from "./storeAccount.js";
>    6 | import {toPairs} from "lodash-es";
> >  7 | import type { AccountSettings } from "./Types.js";
>      |                        ^ SyntaxError: Unexpected token (7:12)
>    8 | 
>    9 | type AcceptedFileEnding = 'ini' | 'adr';
>   10 | 

Removing the line makes quokka crash on line 9.
