### ISSUE TITLE
quokka js Live Results/Code Execution not working on community edition

### ISSUE THREAD

**Issue by AlaguSelvan** [wallabyjs/quokka#381]
### Issue description or question
Quokka.js community edition had supported live results and live logging before, but currently it doesn't seem to support live results
### Sample code

```
const vals = ["foo", "bar", "baz"]
const op = vals.filter(val => val !== "foo")
console.log(op, 'op')```
```

### Quokka.js Console Output

```
​​​​Quokka 'Untitled-1.js' (node: v11.0.0)​​​​
```
### Code editor version
Visual Studio Code v1.35.0

### OS name and version
Windows 10 Pro
![image](https://user-images.githubusercontent.com/34230909/59158748-96442f80-8adc-11e9-98e4-9d347c36670d.png)

**Comment by smcenlly** [comment]
We are unable to reproduce this problem (using `node v11.0.0` and `Windows 10 Pro`).

Could you please try upgrading your version of node to LTS (v10.16.0) or Current (v12.4.0) and see if that fixes your problem? We have seen issues cause by node v11 in the past that may be related (e.g. [Wallaby #2089](https://github.com/wallabyjs/public/issues/2089#issuecomment-496808152)). If you do not want to change your default node version, you can update your Quokka configuration file to point to LTS or Current explicitly (see [our docs](https://quokkajs.com/docs/configuration.html#nodejs-version) for how to do this). Please also note that node v11.x has no LTS and is only supported up until June 30, 2019.

If that doesn't fix your problem, can you please provide us with the list of extensions that you are using in vscode? You can do this from the command-line using `code --list-extensions`.

**Comment by AlaguSelvan** [comment]
node LTS(v10.16.0) seems to work fine and solves this issue thanks 👍
![image](https://user-images.githubusercontent.com/34230909/59174611-9d684d80-8b6f-11e9-9b1d-a211abf44a5d.png)

**Comment by AlaguSelvan** [comment]
Using LTS(10.16.0) version of node seems to solve this issue 💯, Thanks for the help. 👍 
![image](https://user-images.githubusercontent.com/34230909/59174670-e4564300-8b6f-11e9-92f8-9cab7df5a274.png)
