### ISSUE TITLE
Quokka Sublime Text plugin failing to start

### ISSUE THREAD

**Issue by HowlingEverett** [wallabyjs/quokka#384]
### Issue description or question

When I run Quokka: New Javascript File, Quokka interactive session doesn't apply on the new file, and I get an exception in the Sublime Text console.

I have not set up a project with a .quokka config, I'm just trying to start Quokka with default settings in a new javascript file.

### Quokka.js Console Output

```
[warning]: Wallaby.js is not started
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1052, in run_
    return self.run()
  File "<string>", line 123, in run
  File "<string>", line 82, in create_new_file
  File "<string>", line 91, in run_on_file
  File "<string>", line 588, in __init__
AttributeError: 'module' object has no attribute 'create_dir_if_not_exist'
```

### Code editor version

Sublime Text 3.2.1 (Build 3207)

### OS name and version

MacOS 10.14.5

**Comment by smcenlly** [comment]
Could you please trying closing and restart Sublime? We're almost certain that will solve your issue, if not, let us know and we'll reopen this ticket.

**Comment by HowlingEverett** [comment]
Hi, this solved it, thanks 🎈 

I hadn't just installed the plugin, but looking at the console output from earlier it looks like it had recently updated itself. I guess that's why :)

**Comment by smcenlly** [comment]
Without some special logic in our plugin, Sublime only reloads modified python files in the root directory of its plugins. We'll investigate whether it's worth adding logic to force a reload of nested `py` files in our plugin.
