### ISSUE TITLE
[VS code] Can not start node.js process (node), make sure your system has node.js installed.

### ISSUE THREAD

**Issue by jebarjonet** [wallabyjs/quokka#385]
### Issue description or question

On VS Code recently I can't use Quokka anymore. This is what I get when I open a new Quokka Javascript or Typescript file:

<img width="515" alt="Screen Shot 2019-06-20 at 10 19 25 PM" src="https://user-images.githubusercontent.com/4401230/59852545-fe7ef500-93a9-11e9-8863-884b9ec1cdb6.png">

I do not recall having done anything special that could have caused this change.

### Already tried

- I am in a project (I tried with multiple projects)
- I already tried to reinstall VS code
- I already tried to delete `~/.quokka` folder (which was recreated as expected)
- I already tried to set manually the `"node"` property in the `~/.quokka/config.json` file (my `node` is located in `/user/local/bin/node`)
- node & yarn are installed with brew

From VS code terminal itself:

<img width="577" alt="Screen Shot 2019-06-20 at 10 20 01 PM" src="https://user-images.githubusercontent.com/4401230/59852507-e909cb00-93a9-11e9-8b86-f75501d2c30d.png">

### Code editor version

Visual Studio Code v1.35.1

### OS name and version

OSX Mojave 10.14.5

**Comment by jebarjonet** [comment]
Oh my god seriously. I found something 5 min after I opened that issue.

For those who are stuck with this problem:

- Click on `File / Close workspace`
- All your projects are closed
- Some extensions are refreshed and suddenly open windows saying "What's new"
- Open a project (in the "Untitled workspace" that has be created by default)
- Try to run Quokka again, it worked for me

**Comment by NicholasBoll** [comment]
Thanks. This fixed the issue for me as well

**Comment by prathisahrudh** [comment]
Thanks , fixed for me as well.!

**Comment by HetairoiElite** [comment]
Thanks!

**Comment by BaronDls** [comment]
Sorprendentemente si funcionó, gracias.

**Comment by BaronDls** [comment]
> Oh my god seriously. I found something 5 min after I opened that issue.
> 
> For those who are stuck with this problem:
> 
> * Click on `File / Close workspace`
> * All your projects are closed
> * Some extensions are refreshed and suddenly open windows saying "What's new"
> * Open a project (in the "Untitled workspace" that has been created by default)
> * Try to run Quokka again, it worked for me

It worked for me as well
