### ISSUE TITLE
Cannot read property 'include' of undefined 

### ISSUE THREAD

**Issue by hanyanxx1** [wallabyjs/quokka#388]
### Issue description or question
Hello, I used quokkajs when I ran a simple typescript code on visual code.
But it doesn't work, and the output window keeps saying something like this
### Sample code

```javascript
let a = 'a'
```

### Quokka.js Console Output

```
Quokka 'index. Ts' (node: v10.16.0, TypeScript: v3.5.1)
Cannot read property 'include' of undefined
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in the latest extension(s) versions.

**Comment by hanyanxx1** [comment]
@ArtemGovorov 
Great, you fixed it so quickly. You're amazing and responsible. Thank you very much~
