### ISSUE TITLE
Can't get babel-polyfill to work

### ISSUE THREAD

**Issue by X-Tender** [wallabyjs/quokka#389]
### Issue description or question
I try to enable babel polyfill via global config.json.
`{"pro":true,"babel":{"polyfill": true}}`
I get the following error in VSCode

### Quokka.js Console Output
```
Cannot find module './node_modules/@babel/babel-polyfill' 
  at ​​​Function.Module._resolveFilename​​​ ​module.js:548​
  at ​​​Function.Module._load​​​ ​module.js:475​
  at ​​​Module.require​​​ ​module.js:597​
  at ​​​require​​​ ​internal/module.js:11​
​​​​​​
​​​@babel/register is not installed, the module is required if you want to transpile other files imported by the running file​​​
```
SO I installed the package and all necessary polyfill packgaes in the .quokka folder but it doesn't changed anything.

What bothered me that the error says `'./node_modules/@babel/babel-polyfill` but there is no `@babel/babel-polyfill` package available. Only `babel-polyfill` and `@babel/polyfill` (I tried both).

So what could I make wrong?

### Code editor version
Visual Studio Code latest stable

### OS name and version
OSX

**Comment by smcenlly** [comment]
Thanks for reporting the issue. This was a Quokka issue caused by a change in the location of babel's polyfill between babel v6 and babel v7. This has been fixed and is available in the latest version of Quokka for VS Code (v1.0.232).
