### ISSUE TITLE
RequireJS?

### ISSUE THREAD

**Issue by teddyteodoro** [wallabyjs/quokka#39]

**Comment by ArtemGovorov** [comment]
Quokka runs in node, if there's any way to run requirejs in node, then Quokka should support it. 

I haven't tried it, but [this package](https://github.com/podio/node-requirejs) seems to be able to load requirejs modules from node. Try it from your quokka file and let us know how it goes.

**Comment by teddyteodoro** [comment]
I was able to run requirejs together with AMD using this https://github.com/jrburke/amdefine. 

I noticed that unlike WallabyJS, console.log() calls only show up on the main file. On modules called by that main file, console.log() calls no longer display. Is this correct?

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

Correct, inline messages are only displayed for the main file. If you would like to test your require.js app and see coverage and logs in all files, then you should [check out our wallaby.js product](https://wallabyjs.com/docs/).
