### ISSUE TITLE
Quokka ReactJs not working

### ISSUE THREAD

**Issue by dashndash** [wallabyjs/quokka#393]
### Issue description or question

I was about to purchase License for Quokka but Quokka doesnt output the values for the variables and the box indicator on the line is not white not green like shown in this screenshot: [http://prntscr.com/ojhus0](http://prntscr.com/ojhus0) What to do to now? How to make it work? Please help

### Sample code

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import UserInput from './Components/UserInput'
import UserOutput from  './Components/UserOutput'

class App extends Component {

    state = {
      userName: 'SuperMan'
    }
    
    
    usernameChangeHandler = (event) => {
      this.setState({userName: event.target.value});
    }


  render() {
    return (
      <div className="App">

        <ol>
          <li>fasdfa sgasdfasdfadhf</li>
          <li>fasdashsdf sdsg gsdfg asf</li>
          <li>sadg ffa asdgfhas dasdf </li>
          <li>dasr asfasdf as</li>
          <li>sdfdr sfssahfakklkj</li>
          <li>fsdrzsdv dsfhssd asdfsdf</li>
          <li>sacasdas asgdbsd sdafsdfs</li>
        </ol>


        <UserInput
          changed={this.usernameChangeHandler}
        />

        <UserOutput
          userName={this.state.userName}
        />
        <UserOutput
          userName={this.state.userName}
        />
        <UserOutput
          userName="Hank"
        />

      </div>
    );
  }
}

export default App;
```

```javascript
// paste the code you are running here
```

### Sample repository link

```

```

### Quokka.js Console Output

```
​​​​Quokka 'App.js' (node: v10.16.0, babel: v6.26.0, plugins: jsdom-quokka-plugin)​​​​

```

### Code editor version

VSCode 

### OS name and version

OSX

**Comment by dashndash** [comment]
@YahngSungho Can you please help me with this?

**Comment by ArtemGovorov** [comment]
The result on your screenshot is expected. Nothing in the file creates/calls your `App` class function(s), so no results are expected. 

Quokka is not a linter - it doesn't analyse your code, it runs it. Imagine that your file is a small node program and you run it in node - that's what quokka does. If you run the code above in node, nothing happens.
