### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mahdiutshob** [wallabyjs/quokka#394]
- Issue Type: `Performance`
- Extension Name: `quokka-vscode`
- Extension Version: `1.0.238`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mahdi\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mahdiutshob** [comment]
high cpu load

**Comment by smcenlly** [comment]
Could you please provide the file `C:\Users\mahdi\WallabyJs.quokka-vscode-unresponsive.cpuprofile.txt`

**Comment by mahdiutshob** [comment]
Of course thanks for responding 
[Cpu Profile](https://drive.google.com/file/d/18YAiJ7XWhWrZxXSIurBpnpmNrkLoYG7b/view?usp=sharing)

**Comment by smcenlly** [comment]
We've taken a look at the CPU profile that you sent through, and profiled ourselves and the results are very different. We are not seeing any issues on our machines.

I have a few questions for you:

1) Did you disable all extensions except for Quokka before profiling?
2) What steps did you take when you were profiling Quokka? We created a new Javascript file, and wrote some simple code that declared and assigned a variable before outputting to the console.
3) Have you overridden any Quokka configuration (e.g. with a Quokka configuration file)?
4) Have you tried on another computer, and if so, do you get the same result/issue?

**Comment by mahdiutshob** [comment]
1. Did you disable all extensions except for Quokka before profiling?
    -No
2. What steps did you take when you were profiling Quokka? We created a new Javascript file, and wrote some simple code that declared and assigned a variable before outputting to the console.
   -Yes (I did the same)
3. Have you overridden any Quokka configuration (e.g. with a Quokka configuration file)?
    -No
4. Have you tried on another computer, and if so, do you get the same result/issue?
    -No, I didn't do it.

**Comment by smcenlly** [comment]
Could you please try disabling other extensions before profiling and checking on another computer? 

Have you had the error/warning that prompted you to run the CPU profile since?

**Comment by mahdiutshob** [comment]
Thanks
