### ISSUE TITLE
Illegal group reference: group index is missing

### ISSUE THREAD

**Issue by GrayStrider** [wallabyjs/quokka#399]
### Issue description or question
IDE reports error and Quokka doesn't process the code example
java.lang.IllegalArgumentException: Illegal group reference: group index is missing

### Sample code

```javascript
const emitStrats = {
  'Fizz': (i: number) => i % 5 === 0,
  'Baz': (i: number) => i % 3 === 0
}
```

### Code editor version

Webstorm 2019.1

### OS name and version

Windows 10 x64

**Comment by GrayStrider** [comment]
Restarted the IDE, seems to work for now

**Comment by ArtemGovorov** [comment]
Thanks for the update, looks like the issue is not Quokka specific but rather IDE specific.
