### ISSUE TITLE
Error executing the node process

### ISSUE THREAD

**Issue by devmao** [wallabyjs/quokka#4]
### Issue description or question
It's not working at all due to node execution failure.
I'm managing node with nvm so I had to add this line to the VSCode settings:
```javascript
"quokka.node": "/home/mao/.nvm/versions/node/v6.9.5/bin/node",
```

### Quokka.js file
```javascript
// it's empty
```

### Quokka.js Console Output
```
​​​​Quokka #1 (node: v6.9.5, TypeScript: v2.2.1)​​​​
​​Error: spawn node ENOENT​​
​​ at exports._errnoException (util.js:1022:11)​​
​​ at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)​​
​​ at onErrorNT (internal/child_process.js:359:16)​​
​​ at _combinedTickCallback (internal/process/next_tick.js:74:11)​​
​​ at process._tickCallback (internal/process/next_tick.js:98:9)​​
```
### Code editor version
VSCode Version 1.11.0-insider
VSCode Version 1.10.2

### OS name and version
Linux 4.4.0-67-generic #88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.6.
