### ISSUE TITLE
new PC

### ISSUE THREAD

**Issue by youssefsharief** [wallabyjs/quokka#402]
I bought a new laptop. Can I use the license I bought for my old desktop on my new new laptop?

**Comment by smcenlly** [comment]
Yes, you may use your existing license on your new laptop. We support using the same license on multiple PCs but our licensing mechanism will restrict them from being used at the same time.

**Comment by youssefsharief** [comment]
@smcenlly Thank you for your response. How can I install it in a new PC?

**Comment by smcenlly** [comment]
Our [docs include a section on how to apply your license](https://quokkajs.com/docs/license.html). If you can't find your license, please [email us](mailto://hello@wallabyjs.com) and let us know that you've lost your license. We'll be able to look up your license key by your email address.

**Comment by youssefsharief** [comment]
@smcenlly  I sent an email. 

Thank you
