### ISSUE TITLE
Cannot find core-js modules (core-js version 3)

### ISSUE THREAD

**Issue by magicspon** [wallabyjs/quokka#403]
### Issue description or question

Whenever I try and use a modern javascript feature I get an error in the quokka console.

### Sample code

```javascript
const ob = {
	value: 10
}

const fn = () => {}

Object.entries(ob).map(fn)
```

### Quokka.js Console Output

```
​​​​Quokka 'sandbox.js' (node: v12.6.0, babel: v7.5.5, plugins: jsdom-quokka-plugin)​​​​
 
Cannot find module 'core-js/modules/web.dom.iterable' 
Require stack: 
- ./src/sandbox.js 
  at ​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:625​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:527​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:16​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:776​

```

### Code editor version

Visual Studio Code v1.37.1

### OS name and version

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	259.71.1.0.0
  SMC Version (system):	2.38f7
  Serial Number (system):	C02T807TH03Q
  Hardware UUID:	98F63E3F-9DBB-5D81-998D-DD49EBBF0CE3

Cheers

**Comment by smcenlly** [comment]
We put together [a sample](https://github.com/wallabyjs/quokka-403) to try and reproduce your problem but everything appears to be working for us. Could you please try our sample an confirm that it works on your PC?

Can you also please provide us with:
1) Your `package.json` dependencies and devDependencies
2) Your `babel configuration

**Comment by magicspon** [comment]
Heyo, 

I've put together a sample repo

https://github.com/magicspon/quokka-issue

And now i'm getting a different error:

```
Quokka 'sandbox.js' (node: v12.6.0, babel: v7.5.5, plugins: jsdom-quokka-plugin)​​​​
 
Unexpected string 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:720​
```

Thanks

**Comment by smcenlly** [comment]
Thanks for the sample repo, we can now see why this isn't working for you.

Your `.babelrc.js` file is not using `commonjs` for the modules setting when running your Quokka file like it does for tests.

It looks like you intended to configure Quokka to run in `test` mode, but have specified the `babel.env` setting instead of NODE_ENV.

You can fix this and get your file working by changing your Quokka configuration in your `package.json` to:

```diff
"quokka": {
  "babel": {
-   "env": "test",
    "configFile": "./.babelrc.js",
    "polyfill": false
  },
  "installPackageCommand": "yarn add {packageName}",
  "plugins": [
    "jsdom-quokka-plugin"
- ]
+ ],
+ "env": {
+   "params": {
+     "env": "NODE_ENV=test"
+   }
+ }
}
```

**Comment by magicspon** [comment]
Awesome
