### ISSUE TITLE
Default binding of "this" returns NaN

### ISSUE THREAD

**Issue by bjorlov** [wallabyjs/quokka#404]
### Issue description or question

```
On a standalone function invocation, why does quakka return "this.a" as NaN when the global object has a property named a? If not in strict mode (where the default binding is not eligible and will throw a TypeError: undefined), this.a should use the default binding of "this" to the global scope. 

```

### Sample code
```
var a = 1;

function foo() {
    return this.a + 1;
}

var obj = {
    a: 1
}

foo(); //? NaN
foo.call(obj); //? 2

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​Quokka 'thisQuakka.js' (node: v8.12.0, plugins: jsdom-quokka-plugin)​​​​

NaN ​​​​​at ​​​foo()​​​ ​basics/thisQuakka.js:11:0​

2 ​​​​​at ​​​foo.call(obj)​​​ ​basics/thisQuakka.js:12:0​

```

### Code editor version

Visual Studio Code v1.37.1

### OS name and version

OSX High Sierra 10.13.6

**Comment by smcenlly** [comment]
Quokka executes your code using `nodejs`. If you are not using strict mode, then ambient `this` will be an object that has all globally used functions/context like console, process, etc. In your example, this is the context that is used when you call foo **without** explicitly `thisArg`.

You can see this behavior outside of quokka by executing the same code in `node` from the CLI:

```javascript
var a = 1;

function foo() {
    return this.a + 1;
}

var obj = {
    a: 1
}

console.log(foo());
console.log(foo.call(obj));
```

returns:

```shell
NaN
2
```

**Comment by bjorlov** [comment]
I see, thank you for clearing that up for me :)
