### ISSUE TITLE
Plugin crash report window has "Wallaby.js" instead of "Quokka.js"

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#406]
![wallabyInsteadOfQuokka](https://user-images.githubusercontent.com/6392013/64493744-b4146280-d28c-11e9-845b-049f909506b1.png)
### Issue description or question
On Quokka JetBrains plugin crash, in the description text, it says "This plugin is not a production of JetBrains. Please report the problem to Wallaby.js" where "Wallaby.js" is a link that leads to https://quokkajs.com/

It's probably should be "Please report the problem to Quokka.js"

### Code editor version

Webstorm v2019.2.2

### OS name and version

Windows 10 Pro

**Comment by ArtemGovorov** [comment]
This is expected result. While the product name is Quokka.js, vendor's name is Wallaby.
