### ISSUE TITLE
Wallaby and Quokka Usage Clarification

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/quokka#41]
### Issue description or question

Please clarify how or if Quokka can/should be used with Wallaby. 

Thank you!

**Comment by ArtemGovorov** [comment]
These are 2 very different tools, for very different purposes. Wallaby is a testing platform, Quokka is a quick playground.

Unlike Wallaby, Quokka doesn't support any testing frameworks, can't watch/trigger/run tests, only works on a single file, only runs in node.

**Comment by chrisblossom** [comment]
Thank you for the quick response! I actively use Wallaby, and love it!

Really trying to understand if Quokka is intended to be used in combination with Wallaby in the same project. Seems to me you wouldn't use Quokka if using Wallaby with a project already, but I'd like to know if I am missing something here.

**Comment by ArtemGovorov** [comment]
You may still use Quokka with Wallaby in the same project. For example to do a quick throwaway experiment that may nit be worth creating tests for, or for [some benchmarking](https://medium.com/@artem.govorov/using-live-code-comments-to-quickly-measure-code-performance-with-wallaby-js-and-quokka-js-7931a896133).

**Comment by chrisblossom** [comment]
That is basically my Wallaby workflow right now. I write the actual (expect/assert) tests after, but start with Wallaby for the live-feedback while developing. Which is why I am so interested in https://github.com/wallabyjs/public/issues/465, but maybe utilizing Quokka instead might work out better for me.

**Comment by ArtemGovorov** [comment]
Fair enough, thanks for sharing your workflow!
Another scenario - wallaby requires real files, while with quokka you can create scratch files as opposed to using real ones - may be a bit faster.

**Comment by ChaseWnorton** [comment]
I think the issue I have @ArtemGovorov is the price difference.  Were Quokka $15 a year and Wallaby $100...then I understand. Or (and please don't do this;-) but if Quokka was $50 for personal as it is now and Wallaby was $300.  As it is, I keep seeing that they are two completely different programs, but it really is more like, once you get the config of Wallaby down, it just a matter of making another project and test file.  I really struggle with the difference here or seeing them so completely different. One requires setup and one does not. But the setup is not that difficult once you get it down. Help me understand
