### ISSUE TITLE
VSCode Class properties error - Unexpected token =

### ISSUE THREAD

**Issue by jrobber** [wallabyjs/quokka#410]
### Issue description or question

When trying to create class properties quokka throws an error : `Unexpected token =`.
I did this in a blank project just to make sure I had no babel conflicts.
Spec for public field declarations: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

### Sample code

```javascript
class Hi {
  f = 'f';
}

const h = new Hi();
```

### Quokka.js Console Output

```
​​​​Quokka 'scratchpad.js' (node: v10.15.0)​​​​
 
Unexpected token = 
  at ​​​Object.compileFunction​​​ ​vm.js:380​
```

### Code editor version

Visual Studio Code v1.38.1

### OS name and version

OSX
10.14.5

**Comment by smcenlly** [comment]
The console output that you've provided shows that you're system nodejs version that Quokka is using is v10.15.0 and that you aren't babel to perform any transpilation. Support for public and private class fields was [added in V8 v7.2.x](https://v8.dev/features/class-fields) while [Nodejs v10.15.0 uses V8 v6.8.275.32](https://nodejs.org/en/download/releases/). You will get the same error if you run your code from the command line using `node scratchpad.js`.

To get this working, you may upgrade your node version to v12.x+ or [configure babel for your Quokka environment](https://quokkajs.com/docs/configuration.html#babel), using the [babel-plugin-proposal-class-properties](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties).
