### ISSUE TITLE
Live comments may output expression parts in the wrong order

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#411]
### Issue description or question

Live comments may output expression parts in the wrong order. STR order is important

### Steps to reproduce

1. Start Quokka in Autorun mode
2. Enter the single line of code
```javascript
;(1000).toString() + '$' //?
```
3. Duplicate the line (Ctrl + D in JetBrains IDE family)

Expected result:
Identical Quokka output for both lines

Actual result:
First line output subparts are switched

![quokkaSCBug](https://user-images.githubusercontent.com/6392013/65138951-7d6ce380-da14-11e9-81c2-0729255d740a.png)

Note:
The result is unstable - sometimes output may get fixed (on some Quokka re-run). If it would be auto fixed for these two lines - just delete the second line, and output order for the first line would be broken again

![quokkaSCBug](https://user-images.githubusercontent.com/6392013/65139056-ac835500-da14-11e9-976c-d09d7c29f58f.png)

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

$ at _.js:1:2

1000$ at 1000..toString() + '$' _.js:1:2

$ at _.js:2:1

1000$ at 1000..toString() + '$' _.js:2:1
```

### Code editor version

Webstorm v2019.3 EAT1

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment]
This has been fixed, you may update to the latest version of Quokka for IntelliJ (v.1.0.197) to get this fix.
