### ISSUE TITLE
Live Compare doesn't work for some arguments types

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#412]
### Issue description or question

Phantom text in editor says that Live Compare is working, but console output is empty

### Sample code

```javascript
111, 222

111, '333'

'111', '444'
```

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

111444
	at _.js:5:0
```

![liveCompareNumbersBug](https://user-images.githubusercontent.com/6392013/65153546-9dab9b00-da32-11e9-96b6-e9444eaad8b0.png)

### Code editor version

Webstorm v2019.3 EAP1

### OS name and version

Windows 10 Pro

# UPD: It appears that this problem is relevant not only for Numbers but for some other types

### Sample code

```javascript
// Love Compare is NOT working

111, 222

111, '333'

true, '444'

null, '444'

// Love Compare is working

'111', '444'

undefined, '444'

Symbol('bla'), '444'

;({x: 2}, '444')

;([1, 2, 3], '444')

;(() => {} , '444')
```

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

111444
	at _.js:13:0

	at undefined vs '444' _.js:15:0

	at Symbol('bla') vs '444' _.js:17:0

	at { x: 2 } vs '444' _.js:19:1

	at [
    1,
    2,
    3
] vs '444' _.js:21:1

	at () => {
} vs '444' _.js:23:1
```

![liveCompareNumbersBug](https://user-images.githubusercontent.com/6392013/65159837-5f67a900-da3d-11e9-9eda-1e9fd68c849e.png)

Also, it looks like formatting for all but string vs string cases is broken: there should be no padding before `at ...`. Specifically, it looks bad on comparison vs array and function. And would look bad in the same way for vs object with more than one key. Or at least subsequent lines should respect first line padding - this would also make it look better

**Comment by smcenlly** [comment]
Thanks for reporting the issue. Unfortunately diffs are not supported for Number, Boolean, and Function data types. We have updated our docs to reflect this limitation and also updated the message that appears in Quokka, `diff not supported for param types`. If you update to the latest version of Quokka for IntelliJ, v1.0.196 you will get the updated message.

**Comment by Alexsey** [comment]
Ok, I can see that you have changed the string to `diff not supported for param types` but
1. Some of them are still in the console output and some of them are not. I think it would be better to show all of them because in case of non-literal variables different types may be unintended and console output would give a clue on the bug
2. Indent for multiline outputs (with no diff like vs array, function or possibly object) looks broken - a first line should have no indent, or consequent lines should respect that indent. E.g. not
```
    at [
    1,
    2,
    3,
] vs '444'
```
but
```
at [
    1,
    2,
    3,
] vs '444'
```
or
```
    at [
        1,
        2,
        3,
    ] vs '444'
```

**Comment by smcenlly** [comment]
Thanks for your feedback.

> Some of them are still in the console output and some of them are not. I think it would be better to show all of them because in case of non-literal variables different types may be unintended and console output would give a clue on the bug

Unfortunately we can't show for all cases without significant changes that also impacts Wallaby. We have updated the message to show correctly when output exists in the console and have also added a separate feature request issue (https://github.com/wallabyjs/quokka/issues/415) for us to support Boolean, Number, and Function comparisons in the future.

> Indent for multiline outputs (with no diff like vs array, function or possibly object) looks broken - a first line should have no indent, or consequent lines should respect that indent.

This issue affected IntelliJ editors. We've updated the formatting so that it correctly indents. You may update to the latest version of Quokka for IntelliJ (v.1.0.197) to get this fix.
