### ISSUE TITLE
Multiple bugs in code with diff, live comments and leading semicolons

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#419]
### Issue description or question

The code is strongly simplified but based on the real use case. All lines with diff and Live Comment should have the same messages in editor's phantom text, console and Value Explorer. The bugs are listed below

### Sample code

```javascript
const constant = value => value

;'a', 'b' //?
;'a', constant('b') //?
;'a', constant('b') //?
```

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

ab
	at 	_.js:3:1

b at _.js:4:1

ab
	at 	_.js:4:1

ab
	at 	_.js:5:1

undefined at $_$tracer.diff('a', constant('b'), '', 1... _.js:5:1

```

![leadingSemicolonsBugs](https://user-images.githubusercontent.com/6392013/65373740-fe80e080-dc89-11e9-81d8-068352080199.png)

### Bugs list:

1. Editor phantom text, Console and Value Explorer doesn't include output of Live Comment for line 3
2. Editor phantom text, Console and Value Explorer has wrong output for line 5 - `undefined` instead of `b`
3. Editor phantom text and Value Explorer includes Quokka generated code for line 5 `$_$tracer.diff('a', constant('b'), '', 1...`

### Code editor version

Webstorm v2019.3 EAP#2

### OS name and version

Windows 10 Pro

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in plugin v1.0.200.
