### ISSUE TITLE
runnerw.exe: CreateProcess failed with error 2

### ISSUE THREAD

**Issue by stephan-double-u** [wallabyjs/quokka#424]
### Issue description or question
When operning an es6 scratch file, the error message is shown

### Sample code
// irrelevant

### Sample repository link
irrelevant

### Quokka.js Console Output

```
runnerw.exe: CreateProcess failed with error 2: Das System kann die angegebene Datei nicht finden.
```

### Code editor version

IntelliJ IDEA 2019.2.3. (Ultimate Edition)

### OS name and version

Windows 10 Enterprise

![Screenshot](https://user-images.githubusercontent.com/16528498/66257725-f69e6180-e79c-11e9-85fa-caf183f496de.png)

**Comment by smcenlly** [comment]
This error message usually indicates that node is missing from your system path. Quokka.js uses your system’s node.js to run your code. Can you please confirm that you have node.js installed and that it is available in your system path?

If you would like to use a custom node.js version (for example if you are using nvm), you may specify the path to the node executable in your global quokka config.json file ([see our docs for more information](https://quokkajs.com/docs/configuration.html#nodejs-version)).

**Comment by stephan-double-u** [comment]
Thank you very much for this hint.
https://plugins.jetbrains.com/plugin/9667-quokka doesn't mention node.js and the error message isn't too precise ;)

**Comment by smcenlly** [comment]
Thanks for letting us know. Quokka includes exception handling for this case, but it looks like the behavior for how the error is reported at runtime has changed. We've updated the messaging to detail the reason and include steps to rectify for others who have this problem in the future.
