### ISSUE TITLE
Unexpected token < when using styled-components

### ISSUE THREAD

**Issue by gdomaradzki** [wallabyjs/quokka#425]
### Issue description or question
Quokka outputs `Unexpected token <` when using styled-components

### Sample code
```javascript
const SelectNewFormItemTypeModal: FC = () => {
  return (
    <StyledModalSectionsContainer>
      <ModalSection title="項目の形式" isEditable={false}>
        <div>oi</div>
      </ModalSection>
    </StyledModalSectionsContainer>
  );
};
```
### Quokka.js Console Output
```
​​​​Quokka 'SelectNewFormItemTypeModal.tsx' (node: v10.16.3, TypeScript: v3.6.3, plugins: jsdom-quokka-plugin, babel-alias-quokka-plugin)​​​​
 
Unexpected token < 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:723​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:789​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:653​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:593​
  at ​​​Module._load​​​ ​internal/modules/cjs/loader.js:585​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:25​
  at ​​​Object.<anonymous>​​​ ​components/organisms/Modal/modals/SelectNewFormItemTypeModal.tsx:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:778​
```

### Code editor version
Visual Studio Code v1.39.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Can you please share your `tsconfig.json` file?

**Comment by gdomaradzki** [comment]
Sure thing:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "plugins": [{ "transform": "ts-optchain/transform" }],
    "baseUrl": "./",
    "paths": {
      "components": ["components/*"],
      "pages": ["pages/*"],
      "theme": ["theme/*"],
      "hooks": ["hooks/*"],
      "context": ["context/*"]
    }
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "./**/*.tsx"]
}
```

**Comment by ArtemGovorov** [comment]
Thanks.

Your TS compiler options set ` "jsx": "preserve",` meaning JSX syntax is preserved during compilation. While Quokka overrides the setting for the Quokka file itself, any dependent files that your `SelectNewFormItemTypeModal` is importing are loaded via `ts-node` that simply respects your `tsconfig.json`, hence the error.

You may either change your `tsconfig.json` file to `"jsx": "react"`, or configure Quokka to override and pass the setting to `ts-node` as [described in our docs](https://quokkajs.com/docs/configuration.html#compiler-settings).

**Comment by gdomaradzki** [comment]
That solved it, thank you.

**Comment by smcenlly** [comment]
@gdomaradzki - just letting you know that we've changed our default `ts-node` "jsx" compiler setting to be "react" instead of using your `tsconfig.json` setting. You may still override the setting in your quokka configuration. This change means that you will not need to add a configuration file just for this setting in the future.

**Comment by gdomaradzki** [comment]
@smcenlly I tried changing my .quokka's jsx to preserve and I get the `unexpected token <` error again, the only way I solved it was changing my tsconfig's jsx to `react` instead.

**Comment by smcenlly** [comment]
If you set your .quokka `jsx` to `preserve` then you will get the error again. The change that we made means that if you have no `.quokka` TypeScript settings, then Quokka will load your compiler settings from your project's `tsconfig.json` and always override its `jsx` setting to `react`. If you set the `jsx` setting in your `.quokka` file, it will take precedence.

**Comment by gdomaradzki** [comment]
Ah I understand now, thank you, however I'm using next.js and as soon as I run `npm run dev` next will rewrite my tsconfig to preserve. Thanks again.

**Comment by smcenlly** [comment]
@gdomaradzki - I think there might be some confusion. It is OK for your tsconfig to have `jsx` set to `preserve`. If you are using the latest version of Quokka for VS Code (v1.0.256) then you need to remove the `ts` section of your `.quokka` file.

I have this working with the following:

**Quokka File**
Only global quokka file with content:
```json
{"pro":true}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "jsx": "preserve",
    "strict": true,
    "esModuleInterop": true
  }
}
```

**Comment by gdomaradzki** [comment]
Indeed that solved it, thank you for explaining it to me :)

**Comment by erufenix** [comment]
If I use vanilla javascript, what is the solution?

**Comment by ArtemGovorov** [comment]
@erufenix Can you please provide a bit more details about the issue that you are experiencing with Quokka (such as code sample that doesn't run and the error message)?
