### ISSUE TITLE
VS Code 1.40, TypeScript 3.7.2 = The TypeScript language service died 5 times right after it got started.

### ISSUE THREAD

**Issue by David-Else** [wallabyjs/quokka#430]
### Issue description or question
(TypeScript 3.7.2 installed as dev dependency)

Start new typescript file using Quokka command and start typing anything
### Sample code

```javascript
let x = 10;
```
### Quokka.js Console Output

```
​​​​Quokka 'Untitled-1.ts' (node: v10.16.3, TypeScript: v3.7.2)​​​​

10 ​​​​​at ​​​x​​​ ​quokka.ts:2:0​
```
and VS Code keeps on saying this again and again:
```
The TypeScript language service died 5 times right after it got started. The service will not be restarted.
```
### Code editor version

Visual Studio Code v1.4

### OS name and version

Linux Centos 8

Looking through the VS Code issues tracker it seems this error is always due to extensions... I tried choosing the built in TypeScript 3.6.3 and 3.7.2 using VS Codes option box in the bottom right corner, but Quokka still uses 3.7.2 and creates the same error.

**Comment by smcenlly** [comment]
Can you please try the following outside of Quokka and let us know if you have the same problem?

1. Open a new file (Ctrl + N)
2. Change the language mode to TypeScript using the command `Change Language Mode`
3. Type the same as what you were typing using Quokka.

**Comment by smcenlly** [comment]
We have completed testing and a review of VS Code Quokka extension code and do not believe that this is related to Quokka.

We recommend following the steps described in a [VS Code issue](https://github.com/Microsoft/vscode/issues/42236#issuecomment-361323024) with the same problem.

> A few questions:
>
> * Does this happen if you disable all extensions?
> * Does this happen for all projects you open, or just one specifically?
> * Have you set a custom typescript.tsdk value in your workspace or user settings?
>
> Can you also please try collecting the TypeScript server logs:
>
> Add "typescript.tsserver.log": "verbose" to your user settings and restart VSCode.
>
> Reproduce the issue
> Back in the TypeScript section of the output panel, look for a TSServer exited message. Right after that message there should now be the path to a log printed. Open that log directory and look in the tsserver.log file
>
> Look for errors, stack traces, or other suspicious info near the end of the logs.

If you're only getting the error when using Quokka (and not launching a file manually without Quokka) please disable all extensions except for Quokka and see if you're still having the problem. 

If you can show us that you can isolate the issue only to Quokka we will reopen this issue.

**Comment by David-Else** [comment]
Thanks, I don't think it is Quokka now, and made a new bug report here https://github.com/microsoft/vscode/issues/84171
