### ISSUE TITLE
Syntax Error: Unexpected Token when package.json "type" setting is "module"

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#431]
When `package.json` settings `type` is set to `module` quokka errors on imports:

```javascript
import * as os from 'os';

os.homedir(); //?
```

Result: 

```
​​​​Quokka 'index.js' (node: v10.16.3)​​​​
 
Unexpected token * 
  at ​​​Object.compileFunction​​​ ​vm.js:406​
```

_Originally posted by @loganpowell in https://github.com/wallabyjs/quokka/issues/207#issuecomment-555972322_

**Comment by smcenlly** [comment]
This has been fixed and is available in the latest version of Quokka. Please update your editor extension to receive the fix:

* Quokka for VS Code v1.0.260
* Quokka for JetBrains IDEs v1.0.207
* Quokka for Atom v1.0.175
* Quokka for Sublime v1.0.38

**Comment by loganpowell** [comment]
You guys are awesome. Thank you!
