### ISSUE TITLE
Bug in the trial period !

### ISSUE THREAD

**Issue by OmarSAlGhamdi** [wallabyjs/quokka#434]
### Issue description or question

The result of the extension is not true!
### Sample code

```javascript
// paste the code you are running here
```
var balance = 325.00;
var checkBalance = true;
var isActive = false;

if (checkBalance === false ) {
    console.log("Thank you. Have a nice day!");
}
    else if (isActive === true && balance > 0 ) {
        console.log("Your balance is $" + balance.toFixed(2) + ".");
}
    else if (isActive ===false) {
        console.log("Your account is no longer active.");
}
    else if (balance === 0 ) {
        console.log("Your account is empty.");
}
    else if (balance < 0 ) {
        console.log("Your balance is negative. Please contact bank.");
}
### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

​​​​Quokka 'Untitled-1.js' (node: v12.10.0)​​​​
 
Your account is no longer active. 
  at ​quokka.js:13:8​
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows : 10 64bit.
OSX
Linux

**Comment by ArtemGovorov** [comment]
Can't see any issues with your example, Quokka runs the code as expected. It correctly prints `Your account is no longer active.` because `isActive` is `false`. Running the same code in node or browser without Quokka produces the exact same result.

**Comment by OmarSAlGhamdi** [comment]
(I already run it on website and give me different things !)

Oh. I know what is the problem, because I did not save the file.

Thank you so much :) .
