### ISSUE TITLE
Doesn't support numeric separators

### ISSUE THREAD

**Issue by vovk1805** [wallabyjs/quokka#437]
### Doesn't support numeric separators

I'm using nvm. Current nodejs version 12.12.0. Quokka is not support syntax like 1_000_000 although `node index.js` working fine. Help me understand - what is wrong?

### Sample code

```javascript
const delay = s => new Promise(res => setTimeout(res, s * 1_000));

const tasks = [
  delay(1),
  delay(3),
  delay(5)
];

Promise.all(tasks)
  .then(
    console.log.bind(null, 'res >>>>'),
    console.log.bind(null, 'error >>>>')
  )
```

### quokka.js global config
```
{
  "pro": true,
  "node": "/Users/volodymyr_vovk/.nvm/versions/node/v12.12.0/bin/node",
  "ts": {
    "compilerOptions": {
      ...
  }
}
```

### Quokka.js Console Output

```
​​​​Quokka 'index.js' (node: v12.12.0, TypeScript: v2.9.2)​​​​
Failed to instrument streams/index.js 
> 1 | const delay = s => new Promise(res => setTimeout(res, s * 1_000)); 
    |                                                            ^ SyntaxError: Identifier directly after number (1:59) 
  2 |  
  3 | const tasks = [ 
  4 |   delay(1), 
```

### Code editor version

Visual Studio Code Version: 1.40.2

### OS name and version

OSX Mojave (10.14.6)

**Comment by smcenlly** [comment]
Thanks for reporting this problem. By default, we don't include support for tc39 stage 3 proposals. Having said that, we have now added support for numeric separators in the latest version of Quokka. You may update your Quokka for VS Code extension to `v1.0.262` to get support for numeric separators.

**Comment by vovk1805** [comment]
Thanks for a quick resolving issue. On  `v1.0.262` all works fine.
