### ISSUE TITLE
Quokka.js don't work with React.

### ISSUE THREAD

**Issue by cecilialee** [wallabyjs/quokka#439]
### I can't make Quokka.js work with React.

I created the repo with `create-react-app`.
I tried to config my `package.json` for React but can't get it to work.

```json
	"quokka": {
		"babel": {
		  "presets": ["react-app"]
		}
	  }
```

### Sample code

```javascript
import React, { Component } from "react";

const TableHeader = () => {
	return (
		<thead>
			<tr>
				<th>Name</th>
				<th>Job</th>
			</tr>
		</thead>
	);
};
```

### Quokka.js Console Output

```
            <thead> 
            ^ 
 
SyntaxError: Invalid or unexpected token 
```

### Code editor version

Visual Studio Code - Version: 1.40.2

### OS name and version

OSX - 10.14.6

**Comment by smcenlly** [comment]
We tested your code using the latest version of `create-react-app` for both JavaScript and TypeScript and everything is working correctly. We used both `package.json` config and a `.quokka` file.

Please check out [our quokka-create-react-app sample](https://github.com/wallabyjs/quokka-create-react-app) for how to configure Quokka with `create-react-app`.

If you're still having problems after checking out the sample let us know and we will re-open this issue; we will also require:
* The entire Quokka console output (it starts by listing your file name, babel version)
* Your entire `package.json` file (minus any proprietary dependencies)

**Comment by HenriqueOmena** [comment]
@cecilialee im my case i just use 
`npm install jsdom-quokka-plugin @babel/register`


i recomend u create a file called `.quokka` in your `root ` folder then put this code

```javascript
{
  "babel": {
    "presets": ["react-app"]
  },
  "plugins": ["jsdom-quokka-plugin"]
}
```

and press F1 and use Quonkka.ks : Select WorkSpace Folder again to re run the aplication in your file

**Comment by cecilialee** [comment]
It works! Thanks!
