### ISSUE TITLE
TypeScript Strict mode not working when set in config on untitled files

### ISSUE THREAD

**Issue by David-Else** [wallabyjs/quokka#441]
### Issue description or question

`.quokka/config.json`
```
{
  "pro": true,
  "stdEsm": true,
  "ts": {
    "compilerOptions": {
      "strict": true
    }
  }
}
```

### Sample code

Regardless if strict is on in the `tsconfig.json` of the project, when I create a new untitled file:

```ts
let num: number;
num = undefined;
num = null;
```

There should be red lines under the `num =` in strict mode, `Type 'undefined' is not assignable to type 'number'`, so the config file is not setting strict mode to on.

### Quokka.js Console Output

```
// paste your quokka console output here
​​​​Quokka 'Untitled-1.ts' (node: v10.16.3, TypeScript: v3.6.3)​​​​
```

### Code editor version

Visual Studio Code v1.39.2

### OS name and version

Linux Fedora

**Comment by smcenlly** [comment]
Quokka does not put the red underlines in your code files, this is actually done by VS Code.

You should be able to duplicate the problem by creating a new file and changing its language to TypeScript. VS Code will look for your project's `tsconfig.json` as its source of information for editor hints.

**Comment by David-Else** [comment]
@smcenlly Sorry, I was a bit muddled about the red line, but the issue is still the same.

Why is Quokka not using strict mode when it runs my file? It should give an error. Is it reading my `.quokka/config.json`, and if so, what is the `"strict": true` doing? Thanks.

**Comment by smcenlly** [comment]
Quokka does not perform type checking when it runs your code. This is by design to provide a better coding experience when you're coding and transient type errors occur as you're typing. `"strict": true` will be ignored.
