### ISSUE TITLE
Something messy with Scoping

### ISSUE THREAD

**Issue by shihabus** [wallabyjs/quokka#443]
### Issue description or question
Variables declared `let` are still accessible outside block scope.

### Sample code

```javascript
console.log(i)
for(let i=0;i<10;i++){}
```

### Quokka.js Console Output

```
​​​​Quokka 'Untitled-1.js' (node: v10.16.0)​​​​

10 ​​​​​at ​​​i​​​ ​quokka.js:1:0​
```

### Code editor version

Visual Studio Code v1.? 1.35.1 

### OS name and version

Mac Mojave 10.14.6

**Comment by smcenlly** [comment]
We tried your sample code using node v10.16.0 with Quokka and get the results shown below:

```
​​​​Quokka 'Untitled-1.js' (node: v10.16.0)​​​​
 
i is not defined 
  at ​quokka.js:1:1​
```

Can you please try your sample again on a new file? By default Quokka will re-execute your code in the same process after start up; is it possible that you defined `i` in such a way that it was available in an ambient scope and then removed that code?
