### ISSUE TITLE
Install Missing Package command not working

### ISSUE THREAD

**Issue by loganpowell** [wallabyjs/quokka#445]
### Issue description or question

First, let me just say that Quokka is a game-changer. I come from Clojure where the REPL is an integral part of the development experience (DX), and Quokka is a life-saver for my debugging sessions!

My issue:

It may be some configuration I accidentally set, but these days when trying to use the (pro) feature 
```
Install "something" package for the current quokka file​
​Install "something" package into the project​
```
These used to show up as links that I could click (in italics highlight on hover), but now they're just showing up as plain text in the vscode terminal (don't work).

Any pointers?

### Quokka.js Console Output

```
​​​​Quokka 'dispatch.js' (node: v10.16.2, plugins: jsdom-quokka-plugin)​​​​

​Install "loop-recur" package for the current quokka file​
​Install "loop-recur" package into the project​
 
Cannot find module 'loop-recur' 
Require stack: 
- .\test\data\dispatch.js 
```

### Code editor version

Visual Studio Code v1.41.0

### OS name and version

Windows 10

**Comment by loganpowell** [comment]
I just fixed the issue by reinstalling quokka, but this happens on and off. What might I be doing that could break this?

**Comment by ArtemGovorov** [comment]
This looks VS Code issue with rendering output channels content. Next time it happens, try changing currently active output channel from Quokka to any other, and back, it should help.
