### ISSUE TITLE
Project dependencies not working with TypeScript and Quokka Community Edition?

### ISSUE THREAD

**Issue by BrianD91** [wallabyjs/quokka#446]
### Issue description or question

A project I'm working on uses the Immutable.js library. It's installed in the package.json and everything correctly. When I try to run a quokka scratchpad with JavaScript it read the `import {Map} from 'immutable'` just fine, however when I try to use Quokka with a typescript scratchpad it is unable to load that module. I'm not sure if this is a bug or if it's just not supported in the Community Edition

### Code editor version

Visual Studio Code v1.41.1

### OS name and version

MacOS Catalina

**Comment by smcenlly** [comment]
Both the `Community` edition and the `Pro` edition will import your node_modules project references. The difference between `Community` and `Pro` is that the only Pro will import **non** `node module` references. We have tested importing in both TypeScript and JavaScript using the community edition and everything is working for us. It's possible that this is related to the version of TypeScript that is being used, or your TypeScript configuration. For our test, we did the following:

1) Create a new folder, and initialize our project using `npm init`. 
2) Installed `immutable` and `typescript` dependencies using `npm install immutable typescript`.
3) Initialized default typescript compiler settings using `npx tsc --init`.
4) Create a typescript file and start Quokka with the contents:

```typescript
import { Map } from 'immutable';

console.log(Map);
```

To further assist you, we will need a bit more information. Can you please provide:
1) Your `Quokka.js Console` output,
2) Your 'package.json` file,
3) Your 'tsconfig.json` file

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back. If you can provide us with more detail, we will re-open and investigate.
