### ISSUE TITLE
jsdom-quooka-plugin not working as expected

### ISSUE THREAD

**Issue by kevinbcarney** [wallabyjs/quokka#447]
### Issue description or question
I'm using Visual Studio Code and quokka as I go through lessons on CodeAcademy.com. In one lesson I got the code to work and decided I would later install jsdom-quooka-plugin so I can access document objects directly inside the editor because with that turned on I'm certain I would have finished the lesson much earlier.

However, after installing jsdom-quooka-plugin it's not working as expected.

In the spirit of full disclosure, for a completely different purpose, or more accurately a different lesson, I also installed Git on my windows system. I have no idea if this is or is not relevant to my jsdom-quooka-plugin issue, but I hate to not mention it as I made two changes, not one.

I suspect I'm doing something wrong, but I have no idea what it might be. I'm thinking I've configured it wrong, but again, I'm not sure how. 

I've created a file .quokka.json to hold the quokka configure that is specific for this set of files. I settled on the file extension .json after unsuccessfully trying to create a .quokka file without a file extension, but my windows system kept appending .txt.

I'm seeing an unexpected result to the following variable declarations:

let doorImage1 = document.getElementById("door1") //?
let doorImage2 = document.getElementById("door2") //?
let doorImage3 = document.getElementById("door3") //?

Quooka is reporting the variable value as null, then later states "Cannot read property 'src' of null" when I reference doorImage1.src.

### Quokka.js Console Output
Quokka 'script.js' (node: v12.13.0, plugins: jsdom-quokka-plugin)​​​​
 
Cannot read property 'src' of null 
  at ​script.js:23:0​

door1 ​​​​​at ​script.js:1:0​

null ​​​​​at ​​​document.getElementById('door1')​​​ ​script.js:1:0​

null ​​​​​at ​​​document.getElementById('door2')​​​ ​script.js:2:0​

null ​​​​​at ​​​document.getElementById('door3')​​​ ​script.js:3:0​
 
Global startButton: null 
  at ​​​'Global startButton: ' + startButton​​​ ​script.js:18:0​
 
Global doorImage1: null 
  at ​​​'Global doorImage1: ' + doorImage1​​​ ​script.js:22:0​

### Code editor version

Visual Studio Code v1.1.41.1
Webstorm v? : N/A
Atom v1.? : N/A

### OS name and version

Windows 10 Home Version 1903 OS build 18362.535.

![null](https://user-images.githubusercontent.com/59293029/71530203-44af9680-28ae-11ea-9002-db8e43640e51.PNG)

**Comment by ArtemGovorov** [comment]
It looks like Quokka jsdom plugin is not loading HTML file. [This example](https://github.com/wallabyjs/jsdom-quokka-plugin#example-2) explains how to configure  jsdom plugin to load HTML file.


> I settled on the file extension .json after unsuccessfully trying to create a .quokka file without a file extension, but my windows system kept appending .txt.

Quokka doesn't read `.quokka.json` files, please use `.quokka` file [without any extensions](https://www.google.com/search?q=create+file+without+extension+windows).

**Comment by kevinbcarney** [comment]
For some reason my Windows 10 system keeps adding file extensions. At first, it was .txt, then after I switched to .json it's now .json. Thanks for pointing me in the right direction. Every time I delete the extension, it gets put back. I'll now google for how to create files in a Windows 10 file system that have no extension. Thanks!

**Comment by kevinbcarney** [comment]
This follow up note is for anyone else who might make the same mistake I did and not be sure how to tell windows to get rid of the file extension.

Notepad can create a text file with no extension.
https://www.techwalla.com/articles/how-to-create-a-file-without-an-extension-with-notepad

When I opened .quokka.json with Notepad, saved it as .quokka, then deleted .quokka.json (not strictly required, but who needs the clutter), things started working the way I expected.

Thank you for your response.

**Comment by deshadbostic** [comment]
@ArtemGovorov  iv seen you do a few replies on quokka and iv been having issues with setting it up but couldnt find a guide i tried reading docs but still lost. i have few issues i use ejs and not html(i created a html from ejs from last edit of html but not really a fix) and i havea error for jquery "$ is not defined "

**Comment by smcenlly** [comment]
@deshadbostic - could you please [create a new issue](https://github.com/wallabyjs/quokka/issues/new/choose) and include a sample of some code/html that you are trying to run. If at all possible, provide a sample repo and instructions to run your code/page outside of Quokka so we can see what you're doing.
