### ISSUE TITLE
cannot find module 'vscode'

### ISSUE THREAD

**Issue by Meno-101** [wallabyjs/quokka#449]
### Issue description or question
I was trying to enable Quokka on vscode apparently I got the error cannot find module `vscode` even though it's in the node_modules directory.

### Sample code

```javascript
import vscode from 'vscode';

// this doesn't work.
vscode // ?
```

### .quokka/config.json
```json
{
	"pro": true,
	"node": "/usr/bin/node",
	"useWsl": true
}
```

### Sample repository link
https://github.com/Meno-101/sample-ssue-with-quokka.git
**the main work is trying a contribution on vscode-pull-request-github.**
https://github.com/Microsoft/vscode-pull-request-github

### Quokka.js Console Output

```
​​​​Quokka 'index.ts' (node: v13.5.0, TypeScript: v3.7.4)​​​​

​Install "vscode" package for the current quokka file​
​Install "vscode" package into the project​
 
Cannot find module 'vscode' 
Require stack: 
- ./index.js 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1139​
  at ​​​Object.<anonymous>​​​ ​index.ts:1​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:72​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:859​
  at ​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:966​
```

### Code editor version

Visual Studio Code v1.41?

### OS name and version

Windows 10 pro OS Build 19041.1

> Note: the issue applies on macos 10.15.2 (19C57) too, Have I configured something wrong?

MacOs Error Quokka.js:
```
​​​​Quokka 'githubRepository.ts' (node: v12.9.0, TypeScript: v3.7.4)​​​​

​Install "vscode" package for the current quokka file​
​Install "vscode" package into the project​
 
Cannot find module 'vscode' 
Require stack: 
- ./src/github/githubRepository.js 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:936​
  at ​​​Object.<anonymous>​​​ ​src/github/githubRepository.ts:6​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:68​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:677​
  at ​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:772​
​​​​​​
​​​Missing baseUrl in compilerOptions. tsconfig-paths will be skipped​​​
```
> No configuration.

**Comment by ArtemGovorov** [comment]
The issue is not Quokka specific. If you run `npx ts-node index.ts` in your project's root (part of what Quokka does behind the scenes), you'll get the same error. Even simpler, try running:

```
node
> require('vscode')
```

in your project's root, and you'll get the exact same error. 

Regarding the reason why it's not working, my guess is that it is because of the missing `main` field in `vscode` `package.json` file, meaning that the package is not supposed to be used from normal node environment.
