### ISSUE TITLE
can not print values on return command line

### ISSUE THREAD

**Issue by doroncy** [wallabyjs/quokka#45]
### Issue description or question
Please explain why when i putting the comment on a return expression line it doesnt work ?
when i change the line to an assignment statement and then return in a new line, it works as expected.

### Quokka.js file

```javascript
// Not showing anything
[1, 2].map(x=> {
  return x; /*?*/
});

// Showing correct values
[1, 2].map(x=> {
  let tmp = x; /*?*/ 1, 2
  return tmp; 
});

```

### Code editor version
Webstorm

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.4.
