### ISSUE TITLE
Put variable declaration in quokka config file?

### ISSUE THREAD

**Issue by kevinbcarney** [wallabyjs/quokka#450]
### Issue description or question
I'm using Quokka as I do some CodeAcademy.com lessons and exercises.

To make Quokka work with jQuery functions in my code, I need to add the following line to the top of my .js file:
const $ = require('jquery')

When I DON'T add this line, Quokka reports the following error:
$ is not defined

When I DO add this line, the browser executing the code reports the following error:
Uncaught ReferenceError: require is not defined
    at main.js:1

So I'm adding the line while I edit, and commenting it out when I'm done.

If I could somehow move that require statement out of the JS file and into the Quokka config file, I would have the best of both worlds.

Can a line of JS code be stored in the .quokka file somehow? Is this a thing?

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Quokka supports [plugins](https://quokkajs.com/docs/configuration.html#plugins) that can load anything prior to the user's code execution. There's a list of [popular Quokka plugins](https://quokkajs.com/docs/configuration.html#notable-plugins) in our docs, and [jQuery loader](https://www.npmjs.com/package/quokka-jquery-loader) is one of them.
