### ISSUE TITLE
Inconsistencies with IntelliSense between Webstorm and Visual Studio Code using typescript

### ISSUE THREAD

**Issue by Figidon** [wallabyjs/quokka#451]
### Issue description or question
Quokka seems to have a hard time to recognize types for intellisense in WebStorm, while Visual Studio code works more as expected.

Reproduction in WebStorm:

1. Create empty folder
2. Open in WebStorm
3. Create Quokka file with code below
4. Install package for current Quokka file
5. Code works, but no intellisense
6. Create project with npm init and install moment
7. Code works, but no intellisense

Same steps in Visual Studio Code only give Intellisense for step 7.

```typescript
import * as moment from 'moment';

const today = moment();
today. // expecting intellisense here
```
Repeating above steps in WebStorm using code below gives Intellisense on today variable, but only on step 7 (after installing moment into the project).

```typescript
import * as moment from 'moment';

const today:moment.Moment = moment();
today. // now receiving proper intellisense
```

### Another example using https://github.com/wallabyjs/quokka-typescript-import-sample

1. Clone repo & npm install
2. Create new quokka file
3. Code below gives intellisense as expected in VSC, but not in WebStorm.

```typescript
import * as myModule from './myModule';

myModule.default. // expecting intellisense 
```

### Code editor version

Visual Studio Code v1.41.1
Webstorm v2019.3

### OS name and version

Windows

**Comment by smcenlly** [comment]
Quokka does not provide any intellisense for your code files, this is provided by your editor and your editor's language service. 

Unfortunately one of the limitations of **installing a package for the current quokka file**​ is that your editor's language service doesn't know that the package is installed just for that file. This is a know limitation/behavior.

While completely unrelated to Quokka, intellisense should be working for both editors after step 7. For WebStorm, have you tried restarting the editor after `npm install`? We tested using the [quokka-typescript-import-sample](https://github.com/wallabyjs/quokka-typescript-import-sample) example with the steps that you provided and intellisense was working for us on both WebStorm (2019.2.3) and VS Code (v1.41.1).

If you're still having problems with WebStorm, we recommend using the JetBrains support channels.
