### ISSUE TITLE
Pro license expired and cannot find compatible Atom version for last version of Quokka that was included in my 12-months of free upgrades

### ISSUE THREAD

**Issue by sashaskull** [wallabyjs/quokka#454]
Hi there!

My Pro License has recently expired (2019-11-23) and I would like to continue using it. I have read and followed your instructions from [this page](https://quokkajs.com/docs/previous.html?expirydate=2019-11-23#previous-versions). However, after installing a couple of versions back of both Atom and Quokka plugin (paying attention to version compatibility between them), I feel desperate and I feel its more complicated than you present on your listed FAQs. 

It would be grateful if you guys could add an informative table of version compatibility appended to the actual guide to get the user back on their development quickly and hassle free, because this is kind of time consuming and frustrating.

I have tried following your suggestion of installing the last version of Quokka that was included in your 12-months of free upgrades (Quokka-1.0.176 for Atom) which was released in December 18th, 2019, therefore I tried installing Atom 1.4.1 (21 Oct 2019). Without success I also tried downgrading version by version. So how can I get this back working?

### Code editor version
Atom v1.41, 1.40.1, 1.40

### OS name and version
OSX High Sierra 10.13.6

**Comment by smcenlly** [comment]
Hi @sashaskull - thanks for raising the issue. We can see that there's an issue with loading previous versions of Atom. Could you please email us a copy of your license (hello@wallabyjs.com) and we will be able to respond with an updated license that fixes your problem?
