### ISSUE TITLE
console.log() values appear in console but not vs code - newbie!

### ISSUE THREAD

**Issue by Sampajanno** [wallabyjs/quokka#458]
Apologies if I am doing something basic wrong here. When I try to get quokka to show values inside VS Code from a console.log() I get 'null', but when I check the same variables in the browser console I get the expected values. Am I doing something wrong or expecting too much from quokka?

Here is my code:
HTML:
``` 
<body>
    <ul id="star-wars-characters">
      <li class="character luke" data-type="hero">Luke Skywalker</li>
      <li class="character yoda" data-type="master">Yoda</li>
      <li class="character badboy" data-type="villain">Darth Vader</li>
    </ul>
    <script src="js/main.js"></script>
  </body> 
```

JS:
```
const list = document.querySelector('#star-wars-characters');
console.log(list);

const skywalker = document.querySelector('[data-type="master"]');
console.log(skywalker);
```

Quokka:
```​​​​
Quokka 'main.js' (node: v12.13.1, plugins: jsdom-quokka-plugin)​​​​
null ​​​​​at ​​​document.querySelector('#star-wars-chara...​​​ ​js/main.js:1:0​
null ​​​​​at ​​​list​​​ ​js/main.js:2:0​
null ​​​​​at ​​​skywalker​​​ ​js/main.js:5:0​
```

A screen shot is also attached here:
![Screenshot 2020-01-16 at 10 24 10](https://user-images.githubusercontent.com/50716370/72503140-0faeb800-384c-11ea-8aa2-49df63a47a90.png)

Any advice would be highly appreciated and apologies for any newbie errors!

**Comment by ArtemGovorov** [comment]
Looks like Quokka jsdom plugin is not loading your HTML file. You may find instructions how to configure the plugin to load HTML file in the [plugin's repo readme](https://github.com/wallabyjs/jsdom-quokka-plugin#example-2).

**Comment by ArtemGovorov** [comment]
> Also, if I can get this sorted, if I follow the instructions for the global install will this plugin then work on all files I open. I would prefer not to go through this set up process every time. 

Quokka supports [different types/levels of configurations](https://quokkajs.com/docs/configuration.html), so based on your needs you may pick one that suits better.
