### ISSUE TITLE
Looks like Quokka jsdom plugin is not loading your HTML file. You may find instructions how to configure the plugin to load HTML file in the [plugin's repo readme](https://github.com/wallabyjs/jsdom-quokka-plugin#example-2).

### ISSUE THREAD

**Issue by dwhenson** [wallabyjs/quokka#459]
Looks like Quokka jsdom plugin is not loading your HTML file. You may find instructions how to configure the plugin to load HTML file in the [plugin's repo readme](https://github.com/wallabyjs/jsdom-quokka-plugin#example-2).

_Originally posted by @ArtemGovorov in https://github.com/wallabyjs/quokka/issues/458#issuecomment-575024688_

Thanks for the quick feedback. I have tried the above and now seem to get a huge list of items that I don't really need. I would just like to see the output of console log! Any advice. A screenshot is attached.

![Screenshot 2020-01-16 at 11 21 26](https://user-images.githubusercontent.com/50716370/72507728-7be1e980-3855-11ea-9522-c67ccb1e3c42.png)

**Comment by Sampajanno** [comment]
Thanks all clear now. I can get what I want using the plugin and then element.innerHTML rather than trying to console.log everything. Much appreciated!!
