### ISSUE TITLE
Optional parameters don't work

### ISSUE THREAD

**Issue by Fibs7000** [wallabyjs/quokka#461]
### Issue description
Quokka throws an Error if an optional parameter occurs.

### Sample code

```javascript
class User{
  constructor(public firstName: string, public middleName?: string){}
}
```

### Quokka.js Console Output

```
Quokka 'User.ts' (node: v12.8.0, TypeScript: v3.7.2)​​​​
 
Unexpected token ? 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:811​
  at ​​​Module.m._compile​​​ ​./node_modules/ts-node/src/index.ts:814​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:879​
  at ​​​Object.require.extensions.<computed> [as .ts]​​​ ​./node_modules/ts-node/src/index.ts:817​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:731​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:644​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:771​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:68​
  at ​​​Object.<anonymous>​​​ ​./src/core/creation/entities/index.ts:6​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:868​
  at ​​​Module.m._compile​​​ ​./node_modules/ts-node/src/index.ts:814​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:879​
  at ​​​Object.require.extensions.<computed> [as .ts]​​​ ​./node_modules/ts-node/src/index.ts:817​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:731​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:644​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:771​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:68​
  at ​​​Object.<anonymous>​​​ ​./src/core/creation/index.ts:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:868​
  at ​​​Module.m._compile​​​ ​./node_modules/ts-node/src/index.ts:814​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:879​
  at ​​​Object.require.extensions.<computed> [as .ts]​​​ ​./node_modules/ts-node/src/index.ts:817​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:731​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:644​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:68​
  at ​​​Object.<anonymous>​​​ ​src/core/creation/useCases/CreationInteractor.ts:1​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:868​
```

### Code editor version

Visual Studio Code
Version: 1.41.1 (user setup)
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Can you please try to create a new Quokka TypeScript scratch file (`Ctrl + K, T`), paste your code:

```
class User{
  constructor(public firstName: string, public middleName?: string){}
}
```

and see if it errors? If it doesn't, please create a sample repo demonstrating the issue (because in this case it may be related to some other parts of your config/project).

**Comment by Fibs7000** [comment]
If I try it on a new file it works... only with importet files quokka has a problem...

**Comment by Fibs7000** [comment]
So due to further investigation the optional parameter is not the problem.
The real problem is the ?? operator.

If i use this operator in a newly created quokka file it works. If i import the same file it doesn't.

narrowed down the Issue to the following failing code:

```javascript

export class Entity {
    ID = ""
    constructor(
        ID?: string
    ) {
        this.ID = ID ?? "";
    }
}
```

**Comment by ArtemGovorov** [comment]
Thanks for the investigation. Unfortunately we still can't reproduce the issue. I have created this sample repo with your code https://github.com/ArtemGovorov/quokka-461, running Quokka on the `index.ts` file that imports the Entity class is working as expected for me:

<img width="833" alt="Screen Shot 2020-02-06 at 11 07 14 am" src="https://user-images.githubusercontent.com/979966/73897237-2b4c3200-48d1-11ea-9fc8-1cc6b92b3b17.png">

Could you please try the sample repo to see if it's working for you? If it is, please compare the setup with your project (maybe try pasting your project's `tsconfig.json` into the sample repo to see if it reproduces the issue).

**Comment by Fibs7000** [comment]
Yes with this config it works. Had `"target": "esnext"` instead of `"target":"es5"` in my `tsconfig.json`.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
