### ISSUE TITLE
Live comments broken when using "declarationMap" Typescript option in VSCode

### ISSUE THREAD

**Issue by ryparker** [wallabyjs/quokka#465]
### Issue description or question

Live comments will not appear in VSCode if a project contains a `tsconfig.json` with the `declarationMap` option enabled. However the outputs still appear in the Quokka plugin output. 

Additional details:

- I have not tested any other editors besides VSCode.
- I'm a pro member.

### Sample code

With `declarationMap` enabled:

<img width="1626" alt="Screen Shot 2020-03-01 at 3 20 41 PM" src="https://user-images.githubusercontent.com/17558268/75634181-f2059a00-5bd0-11ea-98a8-acb67bed32e8.png">

With `declarationMap` disabled:

<img width="1626" alt="Screen Shot 2020-03-01 at 3 34 23 PM" src="https://user-images.githubusercontent.com/17558268/75634299-29287b00-5bd2-11ea-95e8-930c9750f207.png">

### Sample repository link

My repo is private however it should be reproducible if you test in a directory that contains a simple `tsconfig.json` with
```
{
  "compilerOptions": {
    "declaration": true,
    "declarationMap": true
  }
}
```
and then try to live print something from a typescript file.

_Note: tsconfig requires `declaration` to be enabled before enabling `declarationMap`._

### Quokka.js Console Output

I did enable debug mode in the Quokka global config, but did not notice any errors in the plugin's output.

```
Quokka 'index.ts' (node: v13.9.0, TypeScript: v3.8.2)​​​​

ok ​​​​​
 
{ httpMethod: 'GET', endpoint: 'animal/321' } 
 
{ animal: { find: [λ: find] } } 

```
_Notice the missing `​​​​​at ​src/index.ts:#:#​`_

### Code editor version

Visual Studio Code  v1.42.1
Quokka extension v1.0.280

### OS name and version

OSX Catalina v10.15.3

**Comment by smcenlly** [comment]
Thanks for reporting this issue. By specifying `"declarationMap": true` in your tsconfig.json file, Quokka's sourcemap mapping mechanism was being overridden. We have updated Quokka to ignore the `declarationMap` setting when it executes your files, which will ensure that Quokka correctly displays live comments. This is available for you in the latest version of Quokka for VS Code, v1.0.281.

**Comment by ryparker** [comment]
Thanks!
