### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by tsawan** [wallabyjs/quokka#47]
### Issue description or question
After installation of the plugin in IntelliJ IDEA, there's no context menu to add a new Quokka file.

In IDEA log file, it shows an error message "Icon cannot be found in 'QuokkaIcons.Main13x13', aClass='class com.intellij.openapi.wm.impl.ToolWindowManagerImpl'

### Code editor version

IntelliJ IDEA 2016.2.5

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
> there's no context menu to add a new Quokka file

There's no such action to "add a new Quokka file".  The icon related error message is not relevant. As the documentation and Quokka panel label says, you need to use a context menu on an opened file:

![ws](https://cloud.githubusercontent.com/assets/979966/25563604/97929308-2de2-11e7-883b-0c2177348569.gif)

**Comment by tsawan** [comment]
How do I invoke "Create a new Quokka file" on Windows?
