### ISSUE TITLE
 Cannot use ES6 modules with Typescript and Quokka

### ISSUE THREAD

**Issue by Starcounter-Jack** [wallabyjs/quokka#471]
### ES6 HelloWorld.ts running in Browser, Node and Deno but not with Quokka

I just purchased Quokka. I love it, but I have not yet managed to use ES6. The following simple test fails to run in Quokka. It runs fine in the browser, in Node and in Deno.

``` sh
$ node test.js
Hello World
$ deno test.js
Hello World
$ deno test.ts
Hello World
```

### test.ts / test.js
```javascript
import {Hello} from "./helloworld.js"
console.log(Hello());
```
### helloworld.js
```typescript
export function Hello() {
    return "Hello World";
}
```
#### package.json
```
{
  "type":"module"
}
```

### Quokka config
```
{
    "pro": true
}
```

### tsconfig.json
```
{
    "compilerOptions": {
        "target": "ES6",
        "baseUrl": "./",
    },
}
```

### Quokka.js Console Output

```
​​​​Quokka 'test.ts' (node: v13.12.0, TypeScript: v3.8.3)​​​​
 
Must use import to load ES Module: ./helloworld.js 
require() of ES modules is not supported. 
require() of ./helloworld.js from ./test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. 
Instead rename helloworld.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./package.json. 
 
  at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1163​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:996​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:896​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:72​
  at ​​​Object.<anonymous>​​​ ​test.ts:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1147​
```

### Code editor version
Visual Studio Code v1.44.0

### OS name and version
MacOS

**Comment by smcenlly** [comment]
> It runs fine in the browser, in Node and in Deno.

We would not necessarily expect to see the same behavior running in the browser or in Deno, but you should get the same results when running in node. We get the same problem when running with node using the files/configuration that you provided to us. We have created a [sample repo](https://github.com/wallabyjs/quokka-471) that demonstrates this.

To see the issue outside of quokka, after cloning the package you may:

1. Run `npx ts-node ./test.ts`, which returns:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Temp\quokka-471\helloworld.js
require() of ES modules is not supported.
require() of C:\Temp\quokka-471\helloworld.js from C:\Temp\quokka-471\test.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename helloworld.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Temp\quokka-471\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Temp\quokka-471\test.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module.m._compile (C:\Temp\quokka-471\node_modules\ts-node\src\index.ts:836:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Temp\quokka-471\node_modules\ts-node\src\index.ts:839:12)
```

2. Compile your TypeScript file and then use node:
  a) `npx tsc`
  b) `node ./dist/test.js` (we specified to output compiled version to dist):

```
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Temp\quokka-471\dist\test.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

---

It looks like the error and behavior is expected and in line with node. Can you please fork our repo and provide us with a sample that has the problem inside Quokka but not in node?

**Comment by smcenlly** [comment]
One more thing that's worth mentioning, but isn't the cause of this problem is that your TypeScript import does not need to include the file extension (.js). Unless you know that you need this, you may find doing so will result in runtime errors.

```diff
- import {Hello} from "./helloworld.js"
+ import {Hello} from "./helloworld"
```

**Comment by Starcounter-Jack** [comment]
I am using node. I believe that the node behaviour (i.e. returning the string "Hello World") is the correct behaviour. The reference to to the behaviour in browsers and in deno should only be interpreted as an indication that the node behaviour is intentional.

**Comment by smcenlly** [comment]
@Starcounter-Jack - could you please provide us with instructions to replicate your issue using the repo that we have created? We're keen to help you with the issue but need more information to replicate your problem. As per our [previous response](https://github.com/wallabyjs/quokka/issues/471#issuecomment-613713569) and example, we saw the same behavior using node.

**Comment by Starcounter-Jack** [comment]
@smcenlly 
Now, in the repo you provided, make sure that you have all the files in the `./dist` directory (for simplicity). Just copy the `.js` files to `.ts` files and the `.ts` files to `.js` files (you could use `tsc`, but their content is intentionally valid Typescript and valid ES6, so the transpiler does nothing). So now you have test.ts/js hello world.ts/js ready to run.

1. Run `$ ts-node test.js`. It will produce `"Hello World"`.
2. Now, run `$ ts-node test.ts`. It will crash.

So using Typescript ES6 with Node works, but using Typescript ES6 with Ts-Node does not (unless you provide Ts-node with the `.js` files, which Quokka does not). 

The problem is that you are relying on ts-node. It appears that they have not moved with the times and does not appear to handle ES6 module loading correctly. My take is that they do not offer any intrinsic support for ES6. This was okay in 2016, as most people were targeting ES5, but it does not cut it in 2020. Node, browsers and most other Typescript targets, including Node, fully supports ES6. My guess is that ts-node was construed before people starting use native ES6.

See https://github.com/TypeStrong/ts-node/issues/155.

**Comment by Starcounter-Jack** [comment]
>> It looks like the error and behavior is expected and in line with node. Can you please fork our >> repo and provide us with a sample that has the problem inside Quokka but not in node?

Running `$ node test.js works`. It rightly discovers `"type":"module"` in package.json and allows ES6 imports/exports. Can you demonstrate any repo that allows ES6 export/import without transpiring to ES5 while allowing Quokka to display anything in correlation to the .TS file?

**Comment by Starcounter-Jack** [comment]
A dirty fix might be to fall back to manipulate ts-node to observe `"target":"es5"`in `tsconfig.json` and ignore `"type":"module"` in package.json when employed by Quokka such that Quokka and ES6 node can consume the same environment.

I don't see any benefits for the Quokka/ts-node session to use the same tsc transpiled js code and believe ts-node does not pollute your workspace with the transpiled ES5 js files anyway, so there should be no collision. This would probably be good enough for most use cases for Quokka.

**Comment by Starcounter-Jack** [comment]
The only use case I can think of where the above fix would not work is code relying on advanced module behaviour such as bare import resolution (for example using "import maps"). But little is yet standardised there yet. For example, import maps falls outside of Ecma and is not available in node anyway. Chrome and Deno are using them, but I believe it is enough for Quokka to be able to run the same code and settings as node. So my vote goes for the suggested "fix":

1. Ignore "target":"module" when employing ts-node in Quokka
2. When having "es6", "es2015", "es2020" etc... fix the tsc target to "es5" and set "downlevelIteration" to "true" such that Quokka/ts-node runs your code as close to real es6 as possible

You can see this working quite well in your sample repo by

1. altering things as above manually
2. Watch the beautiful value inspection in Quokka
3. change things back
4. run node with real ES6
5. goto 1.

**Comment by ArtemGovorov** [comment]
Thanks for your input. We have investigated the issue a bit deeper.

First of all, regardless of whether or not ES modules are used, there's currently no way to run TypeScript (`.ts` files) in node without a separate tool (like `ts-node`, or others, or Quokka, or both).

Also, while ES modules are not behind an experimental flag in node anymore, and `node test.js` is working for ES modules, internally ESM loader stable API is not exposed for tools yet. So various tools like Quokka, `ts-node` (or any other node tool that compiles TypeScript on the fly), Babel register, Jest (or other testing frameworks), etc., that need to preprocess or compile files, map module paths, and so on, don't have API yet to fully support node ES modules. Some APIs that can only partially help are still behind experimental flags and are documented as `Note: The loaders API is being redesigned. This hook may disappear or its signature may change. Do not rely on the API described below.`:

https://nodejs.org/api/vm.html#vm_class_vm_module
https://nodejs.org/api/esm.html#esm_experimental_loaders

So to run TypeScript (or JavaScript that needs some processing) in node without pre-compiling it first, you still need a tool on top of node. And Node ESM loader API is simply not yet ready for the tools to use.

Anyway, if I understand correctly, you want to run Quokka on original TypeScript files, not on compiled `.js` files in your `dist` folder (or whereever compiled file are placed to). Running Quokka on compiled files doesn't make much sense outside some one time testing, because the idea of the tool is to provide you feedback when you're editing original source files (with types, etc). So I'll try to focus on making this scenario work for you in the current state of things, and have come up with the updated sample repo: https://github.com/wallabyjs/quokka-471. I have removed `.js` files from the root and had changed the import to omit file extension. Everything seems to be working:
<img width="509" alt="Screen Shot 2020-04-16 at 1 43 37 pm" src="https://user-images.githubusercontent.com/979966/79412240-51383600-7fe8-11ea-8ecf-4c8b9c1f8864.png">

Let us know if the solution works for you.

**Comment by Starcounter-Jack** [comment]
Unfortunately. Node will not resolve a module name without an extension. I.e. your version of test.ts runs in Quokka but not in node.

Using module names without a file extension is valid Typescript. Unfortunatelly, typescript does not add the extension when generating ES6 code. So node will not be able to resolve your version.

I believe that the bug lies in tsc and not in Quokka. https://github.com/microsoft/TypeScript/issues/13422

I believe the problem can be worked around in Chrome and Deno (but not in node) by using import-maps.

```json
{
  "imports": {
    "./helloworld": "./helloworld.js"
  }
}
```
So the challenge of getting Quokka and Node to eat the same ES6 code remains unfortunately.

**Comment by Starcounter-Jack** [comment]
Personally, I can work around this using `deno` instead of node as I'm not using any external node packages. However, I believe this issue will pose an increasing problem as people are starting to adopt native modules.

Thanks for the help. I think I can manage from here (otherwise I'll let you know). I really enjoy Quokka. I also started using Wallaby yesterday and I love it. Given that I can work around any `import/export` issues, I will for sure get a commercial license of Wallaby as well.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> Node will not resolve a module name without an extension. I.e. your version of test.ts runs in Quokka but not in node.

How exactly are you running `test.ts` in node? Or you mean running compiled `test.js` file doesn't run in node without file extension in the import?
