### ISSUE TITLE
[ST4] Troubles with the new way to render unicode character

### ISSUE THREAD

**Issue by kud** [wallabyjs/quokka#472]
Since ST4 allows to display unicode characters via:

```
    // Controls how non-ascii white space is drawn.
    // - "none": Draw unicode white space verbatim, eg. hiding zero-width
    //           spaces.
    // - "punctuation": Draw codepoints of unicode white space defined as
    //                  punctuation. This includes NBSP, but excludes the CJK
    //                  Ideographic Space.
    // - "all": Draw codepoints of all non-ascii space characters.
    "draw_unicode_white_space": "punctuation",
```
like this (for a whitespace):
![image](https://user-images.githubusercontent.com/655838/79340745-12907600-7f2b-11ea-9672-75d2c418bc79.png)

It does now that in the console:

![image](https://user-images.githubusercontent.com/655838/79340776-1e7c3800-7f2b-11ea-9c5b-7c364a8c1997.png)

I talked a bit with the ST support and apparently you could change the space by this:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/655838/79340847-3358cb80-7f2b-11ea-9f3c-550b46cf6f35.png">

=> `none`

**Comment by smcenlly** [comment]
@kud - thanks for letting us know about the problem. By ST4, do you mean the dev build of Sublime Text 3? Or is this something else? We couldn't find any mention of ST4 apart from some forums and were unable to reproduce your problem.

Regardless - we have updated our output settings to set `draw_unicode_white_space` to `none`. This is available in Quokka for Sublime Text **v1.0.55**. It may take up to an hour before the update is available to you through Sublime.

If you continue to have problems we will re-open this issue. Please also provide us with instructions for where to get ST4 and steps to reproduce the issue at the time.

**Comment by rchl** [comment]
ST4 builds are available for testing for registered users at Sublime's Discord (https://discord.gg/RMkk5MR)

**Comment by kud** [comment]
ST4 is Sublime Text 4 yeah indeed. :)

It works like a charm now @smcenlly , thank you so much!

![image](https://user-images.githubusercontent.com/655838/79438761-3fe52e80-7fd4-11ea-8c5f-72ab344848ef.png)
