### ISSUE TITLE
Disable Quokka 'Community Version' toast notifications

### ISSUE THREAD

**Issue by MuhammadimYusoff** [wallabyjs/quokka#474]
### Disable update/toast notifications
Yes I know Quokka is a 'new' extension 'almost' similar to Wallaby, but is there any way to disable Quokka's toast notification? i have used the [Wallaby part notification disabling](https://github.com/wallabyjs/public/issues/1343) but to avail.

I know using 'free' version comes with your kind of Ads, but please how can I disable this thing?
It is ANNOYING.

**Comment by smcenlly** [comment]
@MuhammadimYusoff - I assume that you're using VS Code and that the toast notification says:

```
You are using Quokka.js 'Community' edition (free). Quokka.js 'Pro' edition with some advanced features is also available. 
Would you like to try 'Pro' edition features or to only use the 'Community' edition features?
```

The message will keep displaying until you select an option. If you don't have or want a 'Pro' license, select the action `'Community' features only` and you will never see the toast notification again.
