### ISSUE TITLE
How can I use environment variables inside a file

### ISSUE THREAD

**Issue by felinto-dev** [wallabyjs/quokka#475]
I need to use environment variables

https://quokkajs.com/docs/configuration.html#environment-variables
but I dont want to use in this way

I need to specify the file with my environment variables
how I can to do it with Quokka ?

**Comment by smcenlly** [comment]
We've created a quokka plugin that will allow you to load `.env` files. 

Please follow the instructions in the readme for the package: https://www.npmjs.com/package/dotenv-quokka-plugin
