### ISSUE TITLE
How to break on exceptions and see call stack?

### ISSUE THREAD

**Issue by thunderkid** [wallabyjs/quokka#476]
### Breaking on Exceptions?
Is there a way to break on an exception and see where it occurred in my imported code?
So if my quokka scratchpad file contains this,

```javascript
import {fussyFunction} from 'wherever'

fussyFunction(badArgument) //?       (IN RED): some error occured 
```
then I see that an error was thrown inside `fussyFunction` somewhere. What I'd like to do is see *where* the error occured. Is there a way to break on exceptions, as would happen if I was running using the vscode debugger, so I could view the call stack and variables at the exception point?

### Code editor version

Visual Studio

### OS name and version

Windows

**Comment by smcenlly** [comment]
Unfortunately Quokka doesn't provide a way to debug your code. The correct approach is, as you described is to use your IDE debugger for this.

You should see the stack trace for the error in your Quokka output window, and can use the hyperlinks in the output window to go to the source of the error. Unfortunately you will not be able to view the variables at this point.

While not the same as what you're after, you may go to the error source (e.g. node module) and use `console.log` to output variables from your node module and then **restart Quokka**. You will see these output in your Quokka output. **You will want to be careful to undo your changes after doing this.**

I've created a short animated gif (see below) that shows how to do this.

![quokka476](https://user-images.githubusercontent.com/2074089/81346229-48c1af80-90fd-11ea-9d35-07b65f9206ee.gif)

**Comment by thunderkid** [comment]
Thanks, that's what I'd feared I'd need to do. 
Built in debugging like this (including break on error, stepping through code etc.) would be nice to have if it becomes possible some day.
