### ISSUE TITLE
Quokka doesn't support ES2020

### ISSUE THREAD

**Issue by it-sha** [wallabyjs/quokka#479]
### Sample code

```javascript
const person = {
    name: "Dave",
    age: 30,
    squadNumber: 0
  };

  const squadNumber = person.squadNumber ?? "unassigned";
```

### Quokka.js Console Output

```
Unexpected token '?' 
  at ​​​Object.compileFunction​​​ ​vm.js:381​
```

### Code editor version

Visual Studio Code v1.45.0

### OS name and version

Windows 10 Pro x64

**Comment by smcenlly** [comment]
Quokka supports ES2020 but you will need to be running a version of node.js that also supports this feature at runtime.

The most likely reason for your error is that you are using an old version of node.js. If you [update to node.js `14.2.0`](https://nodejs.org/en/), this will work for you.
