### ISSUE TITLE
import angularjs service

### ISSUE THREAD

**Issue by doroncy** [wallabyjs/quokka#48]
### Issue description or question
Is there an option to import and angular js service/controller and run some of it methods inside Quokka window?
i can import the file, but how do I actually bootstrap angular application to the controller or service will know and initialize all its dependencies?

### Code editor version
Webstorm 

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
You may [create a plugin](https://quokkajs.com/docs/extensibility.html) (that can be a node module or a project file) where you could place any required bootstrapping code. 

Does it answer your question?
