### ISSUE TITLE
Make "Copy Value" to work, if current editors code line contains //?

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/quokka#480]
### Description
Make available to work "Copy Value" action if nothing is selected but current editors code line contains //?
If so it will copy current result from //?
### Sample code
```javascript
var demo2 = 5+1; //? 6
```
Currently if nothing is selected nothing is copied

**Comment by dadiborn** [comment]
addition:
![quokka_sad](https://user-images.githubusercontent.com/36768799/82715653-d0322580-9c9c-11ea-82e8-2ac56b82e8c8.png)
1. Copy Value on big arrays returns empty array
2. Had a luck to copy first portion of 100 items;
after that, sadly, i used Chromes console with `copy(myArray)` to get values

**Comment by smcenlly** [comment]
@dadiborn - thanks for letting us know about the Array behavior. Have created a new separate issue for tracking.

**Comment by smcenlly** [comment]
This is fixed in the latest version of Quokka.
