### ISSUE TITLE
Looks like Delay not working

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/quokka#481]
### Issue description or question
Tried in all possible configurations but when i start typing quokka instantly doing their job and does not respect "delay":1500
Every other setting was picked up (ts || plugins || recycle)
I found that in a moment when i started to type inline comment with / << here it instantly goes with error instead of waiting my 1500ms
### Code editor version
Webstorm v2020.1

**Comment by smcenlly** [comment]
This is working for us. Could you please try cloning and opening [this repo](https://github.com/wallabyjs/quokka-481) from WebStorm and starting Quokka on `index.js`?

We have set the timeout to 10 seconds, so there will be a very noticeable delay when you make changes. Quokka will run immediately on start up and then will wait 10 seconds after every change. If you change the output of `console.log`, you should see the inline display disappear after ~5 seconds and the updated value appear after ~10 seconds.

If you're still having problems, can you please provide us with the version of Quokka that you are using?

If the sample repo works and Quokka is still not working in your project, there is likely a problem with your Quokka configuration. If that is the case, please provide us with your Quokka configuration so we can see what's going on.

**Comment by dadiborn** [comment]
The key sentence was _"at a moment when we start to type inline comment with **/** "_
I did new research and came with this:
![quokka_bug3](https://user-images.githubusercontent.com/36768799/82649973-adfbc180-9c22-11ea-8048-945dafc9a234.png)
when we finish sentence with **;** or **,** and right after pressing **/** or *****, delay will be ignored.

**Comment by ArtemGovorov** [comment]
This is by design. The delay is "a number of milliseconds to wait after your last code change before **running** the code.". Prior to running your code, Quokka also instruments it and if the code file has invalid syntax, Quokka reports it. So any syntactic errors are displayed immediately (your code doesn't need to run to find syntactic errors).
