### ISSUE TITLE
how to make quokka run inside typescript classes

### ISSUE THREAD

**Issue by FauziFadhi** [wallabyjs/quokka#483]
### Issue description or question
I want to run quokka inside class for pre-run test, but quokka like can't recognized it.

as you can see from the following code and pic, I tried to use quokka with console log. but quokka just run outside class (line 10), but didn't run inside class (line 21)

### Sample code
```
console.log('Outside Class');
@Injectable()
export class ApprovalLogService extends BaseService<ApprovalLog> {

  constructor(
    public readonly configService: ConfigService,
    private readonly redisService: RedisService,
  ) {
    super(ApprovalLog, APPROVAL_LOG_CACHE)
    this.setDbConfig(this.configService.dbTrans())
    this.setCacheStore(this.redisService.getClient())
    console.log('Inside Class');
  }
}
```
some pic 
![image](https://user-images.githubusercontent.com/22959762/82697412-17b3b400-9c93-11ea-94c6-680e099e4917.png)

#my setting at package.json
```
"quokka": {
    "ts": {
      "compilerOptions": {
        "target": "es2017"
      }
    }
  },
```
### Quokka.js Console Output

```
​​​​Quokka 'approval-log.service.ts' (node: v10.16.3, TypeScript: v3.7.4)​​​​

Outside Class ​​​​​at ​src/bll/services/approval-log.service.ts:10:0​

```

### Code editor version

Visual Studio Code v1.45

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
When Quokka runs your code, it uses your system’s node.js for its runtime. This means that it will execute the same code as if you had run `node ApprovalLogService.js` or `ts-node ApprovalLogService.ts`.

In your case, you are defining a class, but never instantiating it. This means that when you are using Quokka, you will need to create an instance of your class in addition to defining it.

For example:

```typescript
export class MyTest {
  constructor(param1: string) {
    console.log('constructor was called');
  }
}

// Need to create an instance of the class for the constructor code to be called.
new MyTest();
```

If you are looking for a solution that will run all of the code for your project (including managing dependency injections, etc.) then you may find our other product [Wallaby.js](https://wallabyjs.com) is more suitable for what you're trying to do. Wallaby.js runs your JavaScript and TypeScript tests immediately as you type, highlighting results in your IDE right next to your code.
