### ISSUE TITLE
Copy Value doesn't work properly on large arrays

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#484]
![quokka_sad](https://user-images.githubusercontent.com/36768799/82715653-d0322580-9c9c-11ea-82e8-2ac56b82e8c8.png)

1. Copy Value on big arrays returns empty array
2. Had a luck to copy first portion of 100 items

After that, sadly, i used Chromes console with `copy(myArray)` to get values instead of Quokka

_Originally posted by @dadiborn in https://github.com/wallabyjs/quokka/issues/480#issuecomment-632943733_

**Comment by ArtemGovorov** [comment]
It looks like it is expected. Quokka by design only copies values that have been expanded, so unless all brackets of a large array are expanded, the values will not be copied.
