### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by kalingaCoder** [wallabyjs/quokka#485]
### Issue description or question:
Getting error: Unexpected token export 

### Sample code
export class xyz extends red implements OnInit **{**

### Quokka.js Console Output

​​​​Quokka 'abc.component.ts' (node: v10.16.0, TypeScript: v3.9.3, plugins: jsdom-quokka-plugin)​​​​
 
Unexpected token export 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:721​
  at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:787​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:653​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:593​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:585​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:690​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:25​
  at ​​​Object.<anonymous>​​​ ​./src/app/services/yx.service.ts:6​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:776​
  at ​​​Module.m._compile​​​ ​./node_modules/ts-node/src/index.ts:439​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:787​
  at ​​​Object.require.extensions.(anonymous function) [as .ts]​​​ ​./node_modules/ts-node/src/index.ts:442​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:653​
  at ​​​tryModuleLoad​​​ ​internal/modules/cjs/loader.js:593​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:585​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:25​
  at ​​​Object.<anonymous>​​​ ​src/app/components/offers/abc/abc.component.ts:11​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:776​

### Code editor version

Visual Studio Code v1.45

### OS name and version

Windows 10 PRO

**Comment by smcenlly** [comment]
Could you please provide us with the following:

1. Your `tsconfig.json`.
2. The full file (or a sample file if you don't want to share source code) that has this problem.

Looking at the stack trace, we're particularly interested to see what is on line 11 to confirm whether this is `export class xyz extends red implements OnInit {`.

**Comment by kalingaCoder** [comment]
1. Attached the tsconfig
2. Unfortunately I wont be able to share the actual file, but below is the code @ line 11
import { DummyService } from "@appServices/dummy.service";

My Package.json 

  "version": "1.0.0",
  "quokka": {
    "babel": {
      "ts": {
        
        "path": "...typescript"
      },
      "plugins": [
        "@babel/plugin-transform-typescript"
      ]
    }
  },

[tsconfig.txt](https://github.com/wallabyjs/quokka/files/4675226/tsconfig.txt)

**Comment by smcenlly** [comment]
Your problem is not related to Quokka. You should be able to replicate the problem outside of Quokka by running:

1. `npx tsc -p .`
2. `node .\dist\out-tsc\abc.component.ts`

In your `tsconfig.json`, you are using ES6 Module syntax. This means your environment (which for Quokka is node.js) must support ES6 Module syntax whereas NodeJS uses CommonJS as its module syntax (module.exports), not ES6 module syntax (export keyword).

You may either update your `tsconfig.json` to use commonjs, or else [configure babel to transpile your ES6 to a commonjs target](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs).
