### ISSUE TITLE
Copy data doesn't work, I get Failed to copy to clipboard. spawn xclip ENOENT.

### ISSUE THREAD

**Issue by HugoLiconV** [wallabyjs/quokka#486]
### Issue description or question
Copy data doesn't work.
### Sample code

```javascript
const a = 1
const b = 2

const c = a + b;

console.log(c)
```

### Quokka.js Console Output

```
Failed to copy to clipboard. spawn xclip ENOENT
```

### Code editor version

Visual Studio Code v1.45.1
### OS name and version
Ubuntu 18.04.4 LTS

**Comment by smcenlly** [comment]
Quokka's copy feature works natively for Windows and MacOS but due to operating system limitations in Unix environments, we require `xclip` to be installed.

To install xclip, type the following at your command prompt:

```bash
sudo apt-get install xclip
```

**Comment by amitjangra579** [comment]
> Quokka's copy feature works natively for Windows and MacOS but due to operating system limitations in Unix environments, we require `xclip` to be installed.
> 
> To install xclip, type the following at your command prompt:
> 
> ```shell
> sudo apt-get install xclip
> ```

You saved me... man. Thankyou 👍
