### ISSUE TITLE
Js framework support

### ISSUE THREAD

**Issue by jovancacvetkovic** [wallabyjs/quokka#49]
Is there a way to configure quokka to work with js frameworks eg extjs?

**Comment by ArtemGovorov** [comment]
Quokka runs in node and is able to simulate browser environment [via this plugin](https://github.com/wallabyjs/jsdom-quokka-plugin). If extjs can run in node via `js-dom`, then Quokka can work with it. We [recommend trying and publishing the required bootstrapping code as a plugin if it works](https://quokkajs.com/docs/extensibility.html#plugin-ideas-and-recommendations).
