### ISSUE TITLE
@babel/register is not installed

### ISSUE THREAD

**Issue by marcoSven** [wallabyjs/quokka#491]
### Issue description or question
removed local devDependencies, trying to use globally installed packages in ~/.quokka
```javascript
{
  "dependencies": {
    "@babel/register": "^7.10.1",
    "babel-alias-quokka-plugin": "^1.0.9",
    "babel-core": "^6.26.3",
    "canvas": "^2.6.1",
    "jsdom-quokka-plugin": "^1.0.15",
    "ts-node": "^8.10.2",
    "tsconfig-paths": "^3.9.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```
### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link
https://github.com/wallabyjs/quokka-create-react-app

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
Quokka 'test/src/QuokkaExample.js' (node: v14.3.0, Babel: 7.4.3, plugins: jsdom-quokka-plugin)​​​​

​​Cannot use import statement outside a module​​
  ​​​wrapSafe ​​​at  
  ​​​Module._compile ​​​at  
  ​​​Object.Module._extensions..js ​​​at  
  ​​​Module.load ​​​at  
  ​​​Function.Module._load ​​​at  
  ​​​require ​​​at  
  ​​​Object.<anonymous> ​​​at  
  ​​​Module._compile ​​​at  

​​​@babel/register is not installed, the module is required if you want to transpile other files imported by the running file.​​​
​​​You may install the module in your project by running `npm install @babel/register` command.​​​
```

### Code editor version

Sublime Text 4

### OS name and version

OSX

**Comment by smcenlly** [comment]
This is expected behavior. When we scan for babel, we first look in your project's dependencies. In your case, `create-react-app` ships with babel and so Quokka uses that version. Due to how babel loads it dependencies, @babel/register must be installed alongside the version of babel that is installed.

We'll update our docs and the `​​​@babel/register is not installed` error message so others don't run into the same problem.

**Comment by marcoSven** [comment]
Another possible solution that works better for me is to move .quokka in parent directory, with the goal not to pollute the local project's node modules and still have specific quokka configurations for each project. All dependencies are added to global ~/quokka

**Comment by tim-ethitrade** [comment]
@smcenlly Currently there is no config option to point quokka at the locally installed version of `@babel/register`, so I currently get the message because quokka can load `@babel/core`, but ends up finding `@babel/register` from the global `.quokka` directory.

Can you please add a config option to quokka for the path to `@babel/register`.

Alternatively, would you consider adding support for yarn v2? Happy to make a separate issue for that, if that's likely to happen.

**Comment by smcenlly** [comment]
Quokka's babel configuration already supports a `path` setting ([see our docs](https://quokkajs.com/docs/configuration.html#babel-path)) that allows you to specify where to find babel's libraries. At runtime Quokka will look for:

```
`${quokkaSettings.babel.path}/register`
```

**Comment by tim-stasse** [comment]
@smcenlly isn't the babel path, specified in the quokka config, supposed to point at the `@babel/core` package?

For me, setting the babel path to `./.yarn/sdks/@babel/core` works for finding the `@babel/core` package; however, Quokka then reports the following error:

```
​​​@babel/register could not launched properly. This may indicate that your project packages are not compatible with your current version of Quokka.​​​
​​​Please install @babel/register as a project dependency.​​​
​​​You may install the module in your project by running `npm install @babel/register` command.
```

Given that `@babel/core` and `@babel/register` are two seperate packages, they do of course have 2 seperate paths `./.yarn/sdks/@babel/core` and `./.yarn/sdks/@babel/register` — and `@babel/register` is therefore not found at `./.yarn/sdks/@babel/core/register`.

I've also tried moving `@babel/register` to `./.yarn/sdks/@babel/core/register`, just to see if it would work anyway, but with no luck. I received the same error, regardless.

Also, changing the babel path to `./.yarn/sdks/@babel` doesn't work either; it then can't even find `@babel/core` anymore.

**Comment by ArtemGovorov** [comment]
@tim-stasse Yes, `quokkaSettings.babel.path` is supposed to point to babel core. To correct @smcenlly pseudocode, more precise way Quokka is loading Babel register is:

```js
`${path.dirname(quokkaSettings.babel.path)}/register`
```

so if babel path is pointing to `./.yarn/sdks/@babel/core`, then babel register will be resolved from `./.yarn/sdks/@babel/register`. 

It looks like the issue is not related to the path, but to something else. Can you please describe the steps required to reproduce your setup (or share a sample repo) and we will try it?

**Comment by Lauro235** [comment]
Is it possible to install the babel/register gloablly to avoid having to set up an npm folder / install each time I want to use Quokka?
I've installed the register file globally just in case it is...

**Comment by Lauro235** [comment]
It was working on my machine before. I jump around from one node version to the next, but the quokka config continues to point to the same one...

Currently I'm running node version 19.2.0

Here is my config file

```
{
  "pro": false,
  "node": "/Users/username/.nvm/versions/node/v19.2.0/bin/node",
  "babel": {
    "path": "C:/Users/username/node_modules/babel-core"
  },
  "plugins": ["jsdom-quokka-plugin"],
  "jsdom": {
    "userAgent": "quokka.js",
    "config": {
      "pretendToBeVisual": true,
      "runScripts": "dangerously",
      "url": "http://localhost/"
    }
  },
  "showValueOnSelection": true
}
```
I had never had the babel/register error before if I remember correctly and reading your docs, it doesn't mention this although I did find the following..

> This configuration expects that you have a .babelrc file (or a "babel": {...} section in your package.json) in your project (or the global config folder), as well the babel-core and the used presets in the project’s node_modules.
> 
> If you want to use the same version of babel for all projects and scratch files outside of any project context, you may install babel-core and required presets into the global ~/.quokka/node_modules folder.
>

**Comment by smcenlly** [comment]
> Is it possible to install the babel/register gloablly to avoid having to set up an npm folder / install each time I want to use Quokka?

Yes, you can install the package (and configuration) globally by installing packages in your `~/.quokka` folder and updating your global Quokka `config.json` configuration file. From [our docs](https://quokkajs.com/docs/configuration.html#babel):

> If you want to use the same version of babel for all projects and scratch files outside of any project context, you may install babel-core and required presets into the global `~/.quokka/node_modules` folder.

To do this, go to `~/.quokka` and run `npm install {LIST_OF_YOUR_DEPENDENCIES}`

> I've installed the register file globally just in case it is...

Quokka does not look at your globally installed `node.js` dependencies, only the `~/.quokka/node_modules` folder.

---

If you're still having problems, please provide us with your update configuration file and also check that the dependencies are installed in the locations references in your configuration file.

**Comment by Lauro235** [comment]
Awesome so is it just a case of dragging and dropping the whole register file into the babel-core folder in .quokka re booting and hoping for the best?

**Comment by Lauro235** [comment]
I've read the docs and I'm not sure what part is relevant here as I can't find mention of babel/register...

Should I update the babel object with property register and point it to the correct path within quokka?

A bit like this..
```
{
  "babel": {
    "configFile": "./sub-directory/custom.babel.config.js"
  }
}
```

**Comment by Lauro235** [comment]
Hey so, I have installed the required dep into .quokka as you suggested!

Here is my config.json

```
{
  "pro": false,
  "node": "/Users/Lozzy/.nvm/versions/node/v19.2.0/bin/node",
  "babel": {
    "path": "C:/Users/Lozzy/node_modules/babel-core",
    "plugins": ["@babel/register"]
  },
  "plugins": ["jsdom-quokka-plugin"],
  "jsdom": {
    "userAgent": "quokka.js",
    "config": {
      "pretendToBeVisual": true,
      "runScripts": "dangerously",
      "url": "http://localhost/"
    }
  },
  "showValueOnSelection": true
}
```

**Comment by Lauro235** [comment]
So far I've tried updating the path to an array
    
    "path": [
      "C:/Users/username/node_modules/babel-core",
      "C:/Users/username/.quokka/node_modules@babel"
    ]
    
    Updating "plugins": prop beneath babel not within babel object to
    "plugins": ["jsdom-quokka-plugin", "@babel/register"]
    
    It feels like the documentation isn't super clear here. At least it could be clearer for me.
    I am a paid member by the way but I'm on an old laptop and haven't got round to passing it the credentials.
    
    Your helps appreciated, thanks

**Comment by Lauro235** [comment]
Just in case anyone in the future reads this.
1. cd ~/.quokka/node_modules
2. npm i @babel/register
3. cd ~/.quokka
4. code config.json
5. Update path to
```
C:.Users\yourUsername/.quokka/node_modules/@babel/core
```
6. It should work and the error should be gone now.

**Comment by call0fcode** [comment]
It does not work for me when trying everything said on this issue =(

I'm on the PRO version but it's a pain to configure the extension. I cannot work with imported files at all because they do not resolve as shown on the picture:

![Image](https://github.com/user-attachments/assets/ef4dd885-4127-4765-8839-894b4cc4cea6)

I already installed both babel-core and @babel/register and adjust the global Quokka config as mentioned by @Lauro235:

![Image](https://github.com/user-attachments/assets/2c7f2e68-529c-4c0b-a34a-9c4701a724ee)

@smcenlly , could you please assist me here?

Many thanks in advance 😃

**Comment by smcenlly** [comment]
@call0fcode - based on your `package.json` `dependencies`, you are mixing babel 7 with earlier versions of babel (`@babel/regsiter` and `babel-core`); unfortunately they are not compatible with each other. I think this is why it's not working for you.

Can you please:

1. Clear your `dependencies` in your `package.json` ((i.e `.quokka/package.json`)
2. Delete your `node_modules` (i.e `.quokka/node_modules`)
3. Reinstall your `package.json` dependencies with `npm install jsdom @babel/register`
