### ISSUE TITLE
Out of date info for using old version in your docs and nag screen won't go away

### ISSUE THREAD

**Issue by David-Else** [wallabyjs/quokka#493]
Hi, my license has run out, but I expect to keep using the software nag free.

Your docs https://quokkajs.com/docs/previous.html?expirydate=2020-5-15#how-do-i-continue-to-use-my-expired-license-with-vs-code say:

> How do I continue to use my expired license with VS Code?
> 
> To continue to use the version of Quokka your license entitles you to, you will need to check your license expiry date and download a version of Quokka released before that date.
> 
> You will need to stop VS Code from automatically updating extensions. You can disable auto-update with the Disable Auto Updating Extensions command which sets the extensions.autoUpdate setting to false. If you do not want VS Code to even check for updates, you can set the extensions.autoCheckUpdates setting to false.

This is out of date, see https://github.com/microsoft/vscode/issues/30579 . You can now just select `install another version` and it stops auto update ONLY for that extension.

I have done this, and now every time I start Quokka I get a nag even though I am using the correct older version. Selecting activate accepts my old license, but the nag screen comes again!:

![Screenshot from 2020-06-05 14-44-38](https://user-images.githubusercontent.com/12832280/83883782-dbc12a00-a73b-11ea-8196-933230e8fbcc.png)

**Comment by ArtemGovorov** [comment]
Thanks for pointing out the out of date docs section. It's fixed now. 

> but I expect to keep using the software nag free.

To stop seeing the reminder about expired version you may use the `Suppress Expiration Notifications` Quokka VS Code setting. We have also added the note to the same docs section.
