### ISSUE TITLE
Support using tsconfig.json files nested under project root

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#496]
Currently Quokka runs TypeScript files from the opened project root, and uses `tsconfig.json` from the project root. This can result in Quokka not working on existing project files that override `tsconfig.json` in mono-repos, and perhaps other scenarios. Quokka should be enhanced to support nested `tsconfig.json` files.

At the same time, check whether babel supports having nested configurations and provide similar options.

**Comment by espenja** [comment]
Are there any updates or plans for this feature?
Using Quokka to quickly prototype in a mono repo with extended tsconfig files is quite cumbersome when this feature is missing.

**Comment by smcenlly** [comment]
The issue description is a little misleading (my fault). Quokka does correctly load your TypeScript configuration for saved files in your mono-repo but for scratch files, it uses the `tsconfig.json` from your mono-repo root.

Can you please confirm that your issue is with creating scratch files (unsaved Quokka files) and not for files that are saved in nested repos?

**Comment by smcenlly** [comment]
We have recently [added support for this scenario](https://quokkajs.com/whatsnew/support-for-monorepos.html).
