### ISSUE TITLE
"Axios" file stream  issue

### ISSUE THREAD

**Issue by marcoSven** [wallabyjs/quokka#499]
### Issue description or question
response.data is a string 

### Sample code

```javascript
import axios from 'axios';
import fs from 'fs';

(url =>
	axios({
		url,
		responseType: 'stream',
	}).then(
		response =>
			new Promise((resolve, reject) => {
				response.data
					.pipe(fs.createWriteStream('quokka.jpg'))
					.on('finish', () => resolve())
					.on('error', e => reject(e));
			})
	))(
	'https://images.unsplash.com/photo-1513333420772-7b64ad15ca96?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjEzMjY4NH0'
);
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
response.data.pipe is not a function​​
```

### Code editor version

ST4

### OS name and version

OSX

**Comment by smcenlly** [comment]
Thanks for reporting your issue. We didn't have the same problem as you reported but found there was an issue with writing to `quokka.jpg` in your project folder. This affected Quokka on editors (not just ST). What was happening is that when you wrote `quokka.jpg` to your project folder, this would start Quokka running again, which could lead to misreported errors and indicators. The exact behavior differs based on your editor, and operating system.

Please update to the latest version of Quokka for Sublime, v1.0.60. It may take up to a few hours before the update becomes available through [PackageControl.io](https://packagecontrol.io/). If it is not yet available in the store when you want to update, you may download from [here](https://wallaby-downloads.s3.amazonaws.com/sublime/Quokka.sublime-package).

The sample Quokka file that you provided now works for us with the latest version of Quokka.

**Comment by marcoSven** [comment]
@smcenlly thanks for checking and fixing the other issue. 

You are correct I also have no issues with the provided snippet, I have now noticed that the issue is related to my . quokka config file / jsdom-quokka-plugin . Please try and add 

```
{
    "plugins": ["jsdom-quokka-plugin"]
}
```

**Comment by ArtemGovorov** [comment]
@marcoSven Thanks for letting us know. 

The issue with `axios` in `jsdom` environment is described at https://stackoverflow.com/questions/42677387/jest-returns-network-error-when-doing-an-authenticated-request-with-axios/43020260 and https://github.com/axios/axios/issues/1180, some workaround are described there as well. 

This should work for you (apart from disabling `jsdom` plugin): 

```diff
+global.XMLHttpRequest = undefined;
import axios from 'axios';
import fs from 'fs';
(url =>
```

or this:
```diff
import axios from 'axios';
import fs from 'fs';
+axios.defaults.adapter = require('axios/lib/adapters/http');
(url =>
```

**Comment by marcoSven** [comment]
Thank you @ArtemGovorov for looking into this, the second solution 
```import http from 'axios/lib/adapters/http.js';``` works for me.

The first does not work for me initially when I start quokka.
