### ISSUE TITLE
Not able to access Interactive Examples

### ISSUE THREAD

**Issue by vikrantnegi** [wallabyjs/quokka#501]
### Not able to access Interactive Examples

![quokka-interactive-eg](https://user-images.githubusercontent.com/3294287/84773640-53c00780-affa-11ea-9499-b519b612f879.gif)

### Quokka.js Console Output
```
​​​​Quokka 'Untitled-1.js' (node: v10.16.3)​​​​
```

### Code editor version
Visual Studio Code 1.46.0

### OS name and version
OSX Catalina 10.15.3 (19D76)

**Comment by ArtemGovorov** [comment]
- What version of Quokka extension do you have installed?
- If it is the latest, can you try uninstalling the extension, re-opening VS Code, and installing it back?

**Comment by vikrantnegi** [comment]
@ArtemGovorov Reinstalling the latest version fixed the issue. Thanks.
