### ISSUE TITLE
Quokka doesn't work with TypeScript

### ISSUE THREAD

**Issue by Alexisvt** [wallabyjs/quokka#503]
### Issue description or question

I have QUOKKA PRO and the installed version is  `1.0.298`, I tried to start a new TypeScript file using the Quokka command, but I'm seeing many errors on the console and the live editor doesn't work, this problem is only happening on TypeScript so far.

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.ts' (node: v14.4.0, TypeScript: v3.9.4)​​​​
 
Cannot find module '/Users/test/.vscode/extensions/wallabyjs.quokka-vscode-1.0.298/dist/wallaby/node_modules/ts-node/dist/index.js'. Please verify that the package.json has a valid "main" entry 
  at ​​​tryPackage​​​ ​internal/modules/cjs/loader.js:328​
  at ​​​Function.Module._findPath​​​ ​internal/modules/cjs/loader.js:689​
  at ​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:1016​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:898​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:1089​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:73​
```

### Code editor version

Visual Studio Code v1.46

### OS name and version
macOS Catalina

**Comment by Alexisvt** [comment]
When I downgraded to version `1.0.296` TypeScript worked with no issues

**Comment by smcenlly** [comment]
Thanks for reporting the problem. We added `ts-node` as a dependency for running TypeScript files yesterday (instead of people having to download it) and the package was corrupted by our build process. This has been fixed in the latest version of Quokka for VS Code, 1.0.299.
