### ISSUE TITLE
Add support for native ESM modules

### ISSUE THREAD

**Issue by rlhaben** [wallabyjs/quokka#504]
### Issue description or question
I have upgraded to Node 14 to use ES6 imports on an Express server app. I did this because I have a react app that shares some of the modules. Node requires the ".js" or "mjs" extension and works fine when you use it. But Quokka is no longer usable. I just bought Pro and it was working fine until I started using import. 

I can use an mjs file as an import. But then I cannot interactively use Quokka with that file. 

I am using a total of four files (utils.js, utils.mjs, assets.js, assets.mjs) to illustrate the issue. Preferably I would never need to use mjs files. I would MUCH prefer that node allow me to specify that extension-less imports should be treated as ES6 js files. But right now I am in a no-win situation. I can't use the mjs extension because it prevents me from using Quokka to develop modules. And I can't use .js because Quokka thinks they are cjs files. 

I know Quokka is using Node to run these files in the background. But NodeJS works either way as long as I use an extension. Also, Quokka worked fine on modules when they actually were cjs modules.

### Sample code

```JavaScript
// Error scenario 1 in assets.js
import * as fs from 'fs';
import * as utils from './utils.js'

//quokka works in assets.js
import * as fs from 'fs';
import * as utils from './utils.mjs'

// Error scenario 2 in assets.mjs
import * as fs from 'fs';
import * as utils from './utils.mjs'

// Error scenario 3 in utils.mjs
​​​​​Quokka 'utils.mjs' (node: v14.4.0)​​​​

export class Enum {}

class Utils {}

export const utils = new Utils();

Unexpected token 'export' 
  at ​​​Object.compileFunction​​​ ​vm.js:341​

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka 'assets.js' (node: v14.4.0)​​​​

Must use import to load ES Module: .\data\utils.js 
require() of ES modules is not supported. 
require() of .\data\utils.js from .\data\assets.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. 
Instead rename utils.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from .\package.json. 
 
  at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1216​

When using mjs I get this:

​​​​​Quokka 'assets.mjs' (node: v14.4.0)​​​​
 
Cannot use import statement outside a module 
  at ​​​Object.compileFunction​​​ ​vm.js:341​

```

### Code editor version

Visual Studio Code v1.4.6

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Quokka doesn't currently support native ESM modules. Updating title to reflect as a feature request.

**Comment by ArtemGovorov** [comment]
The major reason why native ES modules support is not yet implemented, is that while ES modules are not behind an experimental flag in node anymore, internally ESM loader stable API is not fully and stably exposed for tools yet. So various tools like Quokka, `ts-node` (or any other node tool that compiles TypeScript on the fly), Babel register, Jest (or other testing frameworks), etc., that need to preprocess or compile files, map module paths, and so on, don't have API yet to fully and stably support node ES modules. Some APIs that can only partially help are still behind experimental flags and are documented as `Note: The loaders API is being redesigned. This hook may disappear or its signature may change. Do not rely on the API described below.`:

https://nodejs.org/api/vm.html#vm_class_vm_module
https://nodejs.org/api/esm.html#esm_experimental_loaders

@rlhaben Having said that, while Quokka doesn't yet support **native** ES modules, by default Quokka is supports ES modules via [`esm` module](https://github.com/standard-things/esm). We have made some changes in the latest version that should address you scenario (`"type": "module" from .\package.json` + `.js` file usage). After updating to the latest version of Quokka extension, `.js` extensions should work for you:

<img width="1215" alt="Screen Shot 2020-06-22 at 7 23 07 pm" src="https://user-images.githubusercontent.com/979966/85271197-d430ad80-b4bd-11ea-837b-ead9d4eb2852.png">

**Comment by rlhaben** [comment]
I have been working around the situation by temporarily renaming the module file that I need to debug. That has worked ok for unit testing modules. I look forward to updating and having it work without renaming.

Thanks!

**Comment by smcenlly** [comment]
@rlhaben - our team is actively working on this. We will share an update in this issue when we have news to share.

**Comment by ArtemGovorov** [comment]
@rlhaben 
> I have been working around the situation by temporarily renaming the module file that I need to debug

Renaming what files, are you still using `.mjs`? You've mentioned:

> Preferably I would never need to use mjs files.

and right now Quokka supports ES modules in `.js` files with package `"type": "module"` via `esm` module.

**Comment by rlhaben** [comment]
I have been renaming to mjs to js for temporary testing. I put my test code at the bottom of the file to test that and upstream modules. It has been an intense project so I have not added any updates since this was (basically) working. I'll look at the esm module and the latest Quokka update. I am probably more irritated that Express doesn't like .js files and is making me use the .mjs extension. I haven't gotten very far down the road yet with React. But I am using .jsx extensions there. I don't think I have had an issue so far.

**Comment by NikGovorov** [comment]
We added support for native ECMAScript Modules and top-level await, please check out our docs for more [information](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await).
