### ISSUE TITLE
"Unexpected token 'export'" with react and import

### ISSUE THREAD

**Issue by yangkennyk** [wallabyjs/quokka#505]
### Issue description or question
I get `Unexpected token 'export'` when importing a npm package

### Sample code
I'm using the quokka react example with an extra import

```javascript
// The config also be placed into package.json or global quokka config,
// see https://quokkajs.com/docs/configuration.html
({
  babel: true,
  plugins: ['jsdom-quokka-plugin'],
});

import React from 'react';
import ReactDOM from 'react-dom';
import ky from 'ky';

document.body.innerHTML += `<div id="root"></div>`;

ReactDOM.render(<h1>Hello, world!</h1>, document.getElementById('root'));

const root = document.getElementById('root').innerHTML;
root;

```

### Sample repository link

https://github.com/yangkennyk/quokka-react-sample

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
Quokka 'quokka.js' (node: v12.17.0, babel: v7.1.0, plugins: jsdom-quokka-plugin)​​​​
 
Unexpected token 'export' 
  at ​​​wrapSafe​​​ ​internal/modules/cjs/loader.js:1054​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1102​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:83​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1158​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:88​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:986​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:879​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:72​
  at ​​​Object.<anonymous>​​​ ​quokka.js:10​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1138​
```

### Code editor version

Visual Studio Code v1.46.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for creating the sample repo, we have sent you the pull request with the working config https://github.com/yangkennyk/quokka-react-sample/pull/1.

You are using babel in your config, and by default, `@babel/register` ignores node modules (doesn't compile them) and `ky` is published as ES module, that's why it wasn't working for you. 

All you need to do is [let babel register know](https://babeljs.io/docs/en/babel-register) that it needs to compile the node module:

```
  babel : {
    ignore : 'node_modules/(?!ky)'
  },
```
