### ISSUE TITLE
New JavaScript File does not work

### ISSUE THREAD

**Issue by umanghome** [wallabyjs/quokka#507]
### Issue description or question

When I create `Quokka.js: New JavaScript file`, it never works. However, if I choose to create a TypeScript file, it does work.

This happens on v1.0.301. I downgraded to v1.0.267 and it works there.

Node version: v12.15.0

This used to work fine earlier, but hasn't been working properly recently.

Also tried deleting `~/.quokka` and disabling all other VS Code extensions, but that did not help.

### Sample code

No code written. Blank file.

### Sample repository link

N/A

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-2.js' (node: v12.15.0)​​​​
 
TypeError: Cannot convert undefined or null to object 
    at Function.keys (<anonymous>) 

```

### Code editor version

Visual Studio Code v1.46.1

### OS name and version

macOS 10.15.4 (Catalina)

**Comment by smcenlly** [comment]
Using the same version of node.js, VS Code, and Quokka on Windows, we don't have a problem. We also tried uninstalling Quokka, deleting the `~/.quokka` directory and reinstalling from scratch and everything is working for us.

Could you please try re-installing Quokka for VS Code v1.0.301 again? (perhaps there was a corrupt installation)

If that doesn't work for you, could you please also try using the latest version of node v12 (v12.18.1)?

**Comment by ArtemGovorov** [comment]
We have also tried in macOS, node: v12.15.0, and it's working for us. Can you please try to install few versions between the latest and v1.0.267 to find out what version had broken the things for you?

**Comment by smcenlly** [comment]
@umanghome - we're going to assume that this is now working for you. If not, please let us know the results of trying our suggestions mentioned above and we will re-open this issue.
