### ISSUE TITLE
Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by ajinkyarajguru** [wallabyjs/quokka#508]
### Issue description or question
When starting on a new JS file quokka is throwing an exception to the output console
### Sample code
config.json 
```javascript
// {
  "pro": true,
  "babel": {
    "path": "./node_modules/@babel/core",
    "presets": ["react-app"]
  },
  "delay": 1500
}

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
 
TypeError: Cannot convert undefined or null to object 
    at Function.keys (<anonymous>) 

```

### Code editor version

Visual Studio Code Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
babel: v7..4

### OS name and version
OS: Darwin x64 18.7.0

**Comment by smcenlly** [comment]
Do you get this for any project that you have opened, or only a specific project?

Could you please send us your `package.json` `dependencies` and `devDependencies` for a project that has the problem?

Could you also please let us know your Quokka extension version?

**Comment by ajinkyarajguru** [comment]
The issue was fixed for me by changing the config.json to update @babel/core and @babel/register versions and then reloading VSCode. No changes were needed in the project package.json. I have a global config for quokka where I also changed the preset to ['create-react-app']

**Comment by smcenlly** [comment]
Glad you got this working, thanks for letting us know what your problem was!
