### ISSUE TITLE
Can't get Quokka working with Gatsby, JSX and Typescript.

### ISSUE THREAD

**Issue by HumidBrains** [wallabyjs/quokka#510]
I've tried for hours to setup Quokka Pro to work with jsx, but without luck. Would be grateful if anyone has a winning recipe to share.

I'm using Gatsby with a mix of js and tsx files at this point.
I also use Theme UI which requires jsx pragma imported.
Quokka runs fine on js files without jsx.
I've tried a myriad babel config and quokka config combos as mentioned in previous issues such as #302, but nope. 

## The error I'm getting with most js files (with jsx)

`Quokka 'HeroGrid.js' (node: v11.15.0, babel: v7.10.4, plugins: jsdom-quokka-plugin)​​​​
SyntaxError: ./src/components/HeroGrid.js: Support for the experimental syntax 'jsx' isn't currently enabled (50:5): 
 
  48 |   console.log('gridItemPosition: ', gridItemPosition) 
  49 |   return ( 
> 50 |     <div 
     |     ^ 
  51 |       sx={{ 
  52 |         display: `grid`, 
  53 |         // gridGap: minMax(0, 1), `
 
Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation. 
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing. 

### I also got this error
​​​​​Quokka 'Layout.js' (node: v11.15.0, babel: v7.10.2, plugins: jsdom-quokka-plugin)​​​​
SyntaxError: ./site/src/components/Layout.js: Unexpected token, expected "</>/<=/>=" (36:12) 
 
  34 |   return ( 
  35 |     <ShadowedLayout> 
> 36 |       <Link to="/">{title}</Link> 
     |             ^ 
  37 |       {items.map(item => ( 
  38 |         <Link to={item.url} key={item.id}> 
  39 |           {item.label} 

## The error I get with tsx files

`​​​​​Quokka 'Article.tsx' (node: v11.15.0, TypeScript: v3.9.6, plugins: jsdom-quokka-plugin)​​​​
 
globalThis is not defined `

### Code editor version

Version: 1.47.0-insider
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:26:01.724Z (6 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

### OS name and version
OS: Darwin x64 19.5.0

**Comment by smcenlly** [comment]
If you already have your gastby project working with TypeScript, then all you need to do is create a [`.quokka` configuration](https://quokkajs.com/docs/configuration.html#quokka-file-config) to tell Quokka to transform your files (including TypeScript) using babel with presets: `babel-preset-gatsby` and `@babel/preset-typescript`.

Your Quokka config will look like this:

```json
{
  "babel": {
    "ts": true,
    "presets": ["babel-preset-gatsby", "@babel/preset-typescript"]
  }
}
```

As per [our docs](https://quokkajs.com/docs/configuration.html#using-babel-to-compile-typescript), with `babel.ts` set to `true`, you are telling Wallaby to use babel for TypeScript files instead of the TypeScript compiler.

We created a [sample quokka-gatsby repo](https://github.com/smcenlly/quokka-gatsby-typescript) that has this configuration and works using Quokka with `jsx` and `tsx` files.

**Comment by HumidBrains** [comment]
Thanks @smcenlly it seemed like I made some progress, but in the end didn't manage to get things working. I previously forgot to mention that my project is composed out of a site and two gatsby themes with a yarn workspaces setup. There is also a Cypress folder with e2e tests written in typescript. 

#### So the base structure is...

```
root
   cypress/...
   site/...
   packages
        theme-1/...
        theme-2/...
```

#### Starting over from scratch, using your suggested config, this is what happened step by step.

## 1. Created .quokka file in root
```
{
  "babel": {
    "ts": true,
    "presets": ["babel-preset-gatsby", "@babel/preset-typescript"]
  }
}
```
#### Result: Error says I'm missing jsdom.

## 2. Installed jsdom globally. Had no effect, so installed locally.
#### Result: 
```
Unexpected token export 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:760​
  at ​​​Object.Module._extensions..js​​​ ​internal/modules/cjs/loader.js:827​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:685​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:620​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:14​
  at ​​​Object.<anonymous>​​​ ​site/src/components/Layout.js:5​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:816​
​​​​​​
​​​@babel/register could not launched properly. This may indicate that your project packages are not compatible with your current version of Quokka.​​​
​​​Please install @babel/register as a project dependency.​​​
​​​You may install the module in your project by running `npm install @babel/register` command.​​​

```

## 3. Installed @babel/register
#### Result:

```
​​​​​Quokka 'Layout.js' (node: v11.15.0, babel: v7.10.2, plugins: jsdom-quokka-plugin)​​​​
 
It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was left in the compiled code. 
 
Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby. 
  at ​​​graphql​​​ ​./packages/gatsby-theme-wordpress/node_modules/gatsby/cache-dir/commonjs/gatsby-browser-entry.js:101​
  at ​​​Object.<anonymous>​​​ ​./packages/gatsby-theme-wordpress/src/components/organisms/ProductCard.tsx:6​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:816​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:827​
  at ​​​Object.newLoader [as .tsx]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:685​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:620​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:723​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:14​
  at ​​​Object.<anonymous>​​​ ​./packages/gatsby-theme-wordpress/index.js:17​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:816​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:827​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:685​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:620​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:14​
  at ​​​Object.<anonymous>​​​ ​site/src/components/Layout.js:5​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:816​
```

 ## I then realized gatsby wasn't running, so did gatsby develop
### Result:
```
​​​​​Quokka 'Layout.js' (node: v11.15.0, babel: v7.10.2, plugins: jsdom-quokka-plugin)​​​​
SyntaxError: ./site/src/components/Layout.js: Unexpected token (35:4) 
 
  33 |   })) 
  34 |   return ( 
> 35 |     <ShadowedLayout> 
     |     ^ 
  36 |       <Link to="/">{title}</Link> 
  37 |       {items.map(item => ( 
  38 |         <Link to={item.url} key={item.id}> 

```

So back to square one, I'm afraid.

**Comment by smcenlly** [comment]
From your error/stack trace, it looks like the file that you're trying to run Quokka with (`ProductCard.tsx`) uses graphql. After running babel transforms on your file, Quokka then runs your code in `node.js`. In your case, the runtime augmentation that gatsby performs when you run `npm serve` or `npm develop` is missing.

Unfortunately Quokka does not currently provide first class support for gatsby as a runtime environment. If you're using runtime components that gatsby sets up in its own startup scripts, you will need to augment the Quokka runtime to do the same, or to mock these components.

In the sample repo that we provided, you will see that the sample mocks these dependencies when the project tests run using `npm test` in the [gatsby mocks](https://github.com/wallabyjs/quokka-gatsby-typescript/blob/master/__mocks__/gatsby.js). It's possible that you could do something similar by mocking the gatsby import by creating a [quokka plugin](https://quokkajs.com/docs/extensibility.html) for gatsby.

Our other product, [Wallaby.js](https://wallabyjs.com/) may provide more of what you're looking for and unlike Quokka, it has support for complex runtime environments (both browser and node.js based).

**Comment by HumidBrains** [comment]
Thanks for your reply @smcenlly, I'm more or less only coding Gatsby projects and just bought Quokka a couple of days ago for that purpose. I'm happy purchasing Wallaby.js if that would solve my problems, but as I just bought Quokka slightly in vain, would there be a possibility to upgrade to Wallaby.js by paying the difference?

**Comment by smcenlly** [comment]
@HumidBrains - we actually provide a free 15-day trial licenses so you can try before you buy. For Wallaby, you may request a trial license [here](https://wallabyjs.com/download/#try-it-free) to confirm that it will meet your needs prior to purchasing.

> I'm happy purchasing Wallaby.js if that would solve my problems, but as I just bought Quokka slightly in vain, would there be a possibility to upgrade to Wallaby.js by paying the difference?

Please send an email to hello@wallabyjs.com if you'd like to change your license from Quokka to Wallaby so we can provide a special order that only charges for the difference.

**Comment by HumidBrains** [comment]
@smcenlly thanks again for your prompt reply. However, there seem to be too much for me to set up and my knowledge too low. I've installed Wallaby.js, tried automatic configuration both from project root and from within a workspace folder, but Wallaby does nothing. I can't even judge whether it's running or not. It doesn't help that I cannot find any documentation related to Gatsby projects either I'm afraid.

**Comment by smcenlly** [comment]
@HumidBrains - not sure if you had a chance to check out the [Wallaby docs](https://wallabyjs.com/docs/tutorial/overview.html)? Wallaby runs in the context of your tests so won't do anything by default without a test; it requires tests as the entry point to executing your code.

If Wallaby is not going to help you or doesn't give you what you need, and you can't use Quokka on your Gatsby project, please email us with your order number if you'd like us to refund your Quokka purchase (this will also invalidate your license).

**Comment by HumidBrains** [comment]
@smcenlly I'm afraid Wallaby is not what I'm looking for, but I'll keep Quokka though it doesn't work with the react syntax in my particular Gatsby project. It still works on files with only classic js syntax, so I'll at least have some use for it every now and then. Thanks for all your help and please don't hesitate to ping me if there would pop up a way to get Quokka work also for more complex Gatsby projects.
