### ISSUE TITLE
How do i get multiple js files to work together

### ISSUE THREAD

**Issue by josephjonesdev** [wallabyjs/quokka#519]
I am writing a class based program with classes in separate files and quokka doesn't work at all because it doesn't see the classes in the other files. How can i get quokka not to show the error or to get my files to work together with quokka?
### OS name and version

Windows

**Comment by smcenlly** [comment]
I'm assuming that you're using the Community version of Quokka? One of the limitations of our community edition is that it is limited to only importing files from your project dependencies (i.e. node_modules). From [our docs](https://quokkajs.com/docs/#project-files):

> Quokka ‘Community’ edition allows you to import any locally installed node modules to a Quokka file. In addition to that, Quokka ‘Pro’ edition also allows to **import any files from your project**.

If you don't have a PRO license, you may [request a trial](https://quokkajs.com/pro/#try-pro-free) from our website.

If you already have a PRO license and you cannot get multiple javascript files working together, then please provide us with code samples of what you're doing so we can take a look for you.

**Comment by smcenlly** [comment]
@josephjonesdev via discord:

> I have pro

@smcenlly  via discord:

> Can you please provide us with code samples of what you're doing?
> (and any errors you're receiving)
