### ISSUE TITLE
​​Unexpected token export​​/import

### ISSUE THREAD

**Issue by pablohpsilva** [wallabyjs/quokka#52]
### Issue description or question
Quokka seems to break when it finds anything starting with either `exports` or `import`.

### Quokka.js file

```javascript
export const calculateMenuHeight = (listSize,
  height = 48,
  gap = 75,
  maxItems = 4,
  maxSize = 275) => {
  if (listSize) {
    const size = (listSize > maxItems) ?
      maxSize :
      (height * listSize) + gap;
    return size < 120 ? 120 : size;
  }
  return 'auto';
};
```

### Quokka.js Console Output

```
Quokka #1 (node: v7.3.0)​​​​
​​​​
​​Unexpected token export​​
  at ​​​Object.exports.runInThisContext​​​ ​vm.js:78​
```

### Code editor version

Visual Studio Code v1.12.1

### OS name and version
OSX Sierra 10.12.4

**Comment by ArtemGovorov** [comment]
Quokka runs in node, that doesn't support ES6 module syntax. You need to [configure quokka to use babel](https://quokkajs.com/docs/configuration.html#babel).

**Comment by ArtemGovorov** [comment]
[Quokka now supports `imports/exports`](https://medium.com/@artem.govorov/es-modules-support-in-quokka-by-default-5a0b18256194) with zero config without Babel.

**Comment by doctafaustus** [comment]
@ArtemGovorov - It seems unable to use imports out of the box: 
https://www.dropbox.com/s/5q5ig46ggdqnfmt/Screenshot%202018-08-23%2015.38.15.png?dl=0

Any Ideas?

**Comment by doctafaustus** [comment]
@smcenlly - working fine now, thanks. I was getting the error with this config:

```
{
  "pro": true,
  "babel": true
}
```

**Comment by Foxhoundn** [comment]
> [Quokka now supports `imports/exports`](https://medium.com/@artem.govorov/es-modules-support-in-quokka-by-default-5a0b18256194) with zero config without Babel.

Hi, is this available only in the PRO version? I have installed Quokka and have the same issue when using `export ...`. I am not using any config.

**Comment by smcenlly** [comment]
@Foxhoundn - ES Modules are supported in both Quokka Community and Quokka PRO versions.

You may find this section of [our docs](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await) useful.

If you're still having problems, could you please [create a new issue](https://github.com/wallabyjs/quokka/issues/new/choose) and provide:
1. Your `.quokka` configuration, 
2. the code that you're attempting to run, 
3. Your `package.json`, 
4. Your node version.

**Comment by Foxhoundn** [comment]
> @Foxhoundn - ES Modules are supported in both Quokka Community and Quokka PRO versions.
> 
> 
> 
> You may find this section of [our docs](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await) useful.
> 
> 
> 
> If you're still having problems, could you please [create a new issue](https://github.com/wallabyjs/quokka/issues/new/choose) and provide:
> 
> 1. Your `.quokka` configuration, 
> 
> 2. the code that you're attempting to run, 
> 
> 3. Your `package.json`, 
> 
> 4. Your node version.

Thanks for the reply and sorry for necroing. I realized that I do not have a quokka config file yet, so I will try to create one and play with it and will open a new issue if the problem still persists.
