### ISSUE TITLE
Quokka.js doesn't resprect TypeScript @types/moment

### ISSUE THREAD

**Issue by wneessen** [wallabyjs/quokka#523]
### Issue description or question
I run Quokka.js Pro in VS Code on some TypeScript code. I am using the @types/moment and @types/moment-timezone extensions in my TypeScript code. The "tsc" transpiler is respecting them accordingly but when I start up Quokka the specific code file, it throws an error in the Quokka output window.

### Sample code

```javascript
const lastModDate = moment(lastModified);
xhrObj.setRequestHeader('If-Modified-Since', lastModDate.tz('UTC').format('ddd, DD MMM YYYY HH:mm:ss [GMT]'));
```

### Quokka.js Console Output

```
Quokka 'myscript.ts' (node: v12.16.1, TypeScript: v3.9.7, plugins: jsdom-quokka-plugin)​​​​
 
moment is not defined 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1158​
  at ​​​Object.<anonymous>​​​ ​ts/myscript.ts:1529:0​
  at ​​​MyScript.renderList​​​ ​ts/myscript.ts:1421​
  at MyScript.<anonymous>​​​ ​ts/myscript.ts:1427:12​
  at ​​​MyScript.checkLastModified​​​ ​ts/myscript.ts:477:8​
  at ​ts/myscript.ts:499:16​
```

### Code editor version

Visual Studio Code v1.47.3

### OS name and version

Windows and MacOSX

**Comment by smcenlly** [comment]
When you start Quokka for your code, Quokka uses node.js as its runtime ([described in our docs](https://quokkajs.com/docs/#runtime)).

In your case, while TypeScript is compiling, it will have the same problems running your code as Quokka has. You need to first import the moment library before attempting to use it ([as described in the moment timezone documentation for node.js](https://momentjs.com/timezone/docs/#/use-it/node-js/)).

The following should work for you:

```javascript
const moment = require('moment-timezone');
moment().tz("America/Los_Angeles").format(); //?
```

and output:

![image](https://user-images.githubusercontent.com/2074089/89230138-19500f80-d626-11ea-84ac-cccba5203ae5.png)

---

Our `package.json` file looked like this:

```json
{
  "name": "quokka-523",
  "version": "1.0.0",
  "devDependencies": {
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.5.13",
    "@types/node": "^14.0.27",
    "moment-timezone": "^0.5.31",
    "typescript": "^3.9.7"
  }
}
```
