### ISSUE TITLE
vscode output panel: console.log output is out of order after the 11th line

### ISSUE THREAD

**Issue by apolopena** [wallabyjs/quokka#524]
### Issue description or question
vscode Output panel is not displaying `console.log()` output in the proper order of execution time when in a loop of 12 or more.
### Sample code

```javascript
const logArrIndex = (arr) => {
  for (var i = 0; i < arr.length; i++) {
    console.log(i);
  }
}

const testArr = [1,2,3,4,5,6,7,8,9,10,11,12] // output is fine when this array has less than 12 items!

logArrIndex(testArr);
```

### Quokka.js Console Output

```
11 ​​​​​at ​​​i​​​ test/simpleTest.js:3:4​

0 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

1 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

2 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

3 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

4 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

5 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

6 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

7 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

8 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

9 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

10 ​​​​​at ​​​i​​​ test/simpleTest.js:3:4​
```

Expected output:
```
0 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

1 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

2 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

3 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

4 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

5 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

6 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

7 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

8 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

9 ​​​​​at ​​​i​​​ ​test/simpleTest.js:3:4​

10 ​​​​​at ​​​i​​​ test/simpleTest.js:3:4​

11 ​​​​​at ​​​i​​​ test/simpleTest.js:3:4​
```

### Code editor version

Visual Studio Code: January 2020 (version 1.42.1)

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
What version of Quokka extension do you have installed? Can't reproduce the issue in the latest version of Quokka, however I do remember a similar issue was reported some time ago and we have fixed it.

**Comment by apolopena** [comment]
Quokka-1.0.277 for VS Code Pro version.
Confirmed fixed in the latest version 1.0.312

$43 for a bug fix (upgrade) or I or just live with this blocking bug?
Is an upgrade my only solution?

I didnt want to basically throw away

**Comment by ArtemGovorov** [comment]
There are a couple of options:

- You may renew your license (to receive the bug fix, and other bug fixes and features that we have added after your license had expired, and 12 more months of upgrades to the latest version).
- You may switch to use Quokka Community edition. It has less features that Pro edition, but is completely free.

**Comment by apolopena** [comment]
confirmed fixed in the latest version.
