### ISSUE TITLE
Quokka does not properly support optional chaining

### ISSUE THREAD

**Issue by ArtemeeSenin** [wallabyjs/quokka#526]
### Issue description or question

Quokka does not properly support optional chaining

I have this statement `machine.states[state]?.on?.[event] ?? state` on which Quokka fails but in browser (chrome 84) this evaluates fine.

```js
const machine = {
  initial: 'idle',
  states: {
    idle: {
      on: {
        FETCH: 'pending'
      }
    },
    pending: {
      on: {
        RESOLVE: 'resolved',
        REJECT: 'rejected'
      }
    },
    resolved: {},
    rejected: {}
  }
}

const transition = machine => (state, event) => (
  machine.states[state]?.on?.[event] ?? state
);

const promise = transition(machine); //?

promise('idle', 'FETCH');
```

I see this error message:
```
./src/00/index.js:36
            return $_$w(1, 8, $_$c), ($_$w(1, 9, $_$c), machine.states[state]?.on?.[event]) ?? ($_$w(1, 10, $_$c), state);
                                                                              ^

SyntaxError: Invalid or unexpected token
    at new Promise (<anonymous>)
```

### Versions
Macos 10.15.5
Quokka for Webstorm 1.0.251
Node.js 14.5.0
Webstorm 2020.2

**Comment by ArtemGovorov** [comment]
Quokka fully supports optional chaining. The error message points out that your node version that Quokka is using doesn't support optional chaining. The version of node that Quokka is using is printed in the Quokka output. By default Quokka is using your system installed node (wherever `node` in CLI is mapped to), you can also configure Quokka to use any [other installed version of node](https://quokkajs.com/docs/configuration.html#nodejs-version).

**Comment by ArtemeeSenin** [comment]
Got it!
Thank you for the help!
