### ISSUE TITLE
Intellij causes null errror

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/quokka#53]
Hi,

I am using Intellij 2017.1.3 on OSX and I noticed a flashing red icon in the lower right that states that there is an error in Quokka

Here are the contents

> null
> java.lang.NullPointerException
> 	at com.quokka.javascript.n.contentsChanged(Unknown Source)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
> 	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:380)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:371)
> 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
> 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
> 	at com.sun.proxy.$Proxy61.modificationCountChanged(Unknown Source)
> 	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:74)
> 	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:100)
> 	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:360)
> 	at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:293)
> 	at com.intellij.psi.impl.file.impl.PsiVFSListener$6.run(PsiVFSListener.java:249)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
> 	at com.intellij.psi.impl.file.impl.PsiVFSListener.fileDeleted(PsiVFSListener.java:243)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:85)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
> 	at com.intellij.psi.impl.file.impl.PsiVFSListener$1.after(PsiVFSListener.java:99)
> 	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:371)
> 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
> 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
> 	at com.sun.proxy.$Proxy166.validityChanged(Unknown Source)
> 	at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.after(VirtualFilePointerManagerImpl.java:528)
> 	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:371)
> 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
> 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
> 	at com.sun.proxy.$Proxy24.fileWithNoDocumentChanged(Unknown Source)
> 	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:153)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:132)
> 	at com.sun.proxy.$Proxy24.fileWithNoDocumentChanged(Unknown Source)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.contentsChanged(FileDocumentManagerImpl.java:581)
> 	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
> 	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
> 	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
> 	at com.sun.proxy.$Proxy20.contentsChanged(Unknown Source)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
> 	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
> 	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
> 	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
> 	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
> 	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
> 	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
> 	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
> 	at com.sun.proxy.$Proxy21.after(Unknown Source)
> 	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:779)
> 	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.b(RefreshSessionImpl.java:196)
> 	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
> 	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:183)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
> 	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
> 	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.a(RefreshQueueImpl.java:81)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.10
