### ISSUE TITLE
Use tsconfig.base.json instead of tsconfig.json

### ISSUE THREAD

**Issue by studds** [wallabyjs/quokka#530]
### Issue description or question

This is mostly just a PSA with a problem & solution, as it took me a half hour to figure this out. But also if there's a better solution, I'd love to know!

I've recently switch over to the new ["solution style" tsconfig.json](https://angular.io/guide/migration-solution-style-tsconfig) preferred by angular cli 10. The upshot of this is that the root tsconfig.json is now called tsconfig.base.json, which meant that tsconfig-paths wasn't working, I'd get this error:

`Couldn't find tsconfig.json. tsconfig-paths will be skipped​​​`

I've got it working using a `.quokka` config file containing:

```json
{
    "env": {
    "params": {
      "env": "TS_NODE_PROJECT=tsconfig.base.json"
    }
  }
}
```

**Comment by smcenlly** [comment]
Thanks for letting everyone know. We'll close this issue (people will be still be able to find it in search).
