### ISSUE TITLE
How to Use with React Functional Components?

### ISSUE THREAD

**Issue by dikuw** [wallabyjs/quokka#532]
### Issue description or question
All my code in functional components is highlighted with grey (not running) squares. How can I get the functionality of Quokka in React functional components?
![image](https://user-images.githubusercontent.com/16313875/91289428-89ccf500-e7bc-11ea-9ddf-1b21d6653bf3.png)
I thought I would see the values of `total`, `props.cart`, etc. when I select them...

### Sample code
See repository here: https://github.com/dikuw/Hely/tree/master/client

### Quokka.js Console Output
```
​​​​​Quokka 'Cart.js' (node: v8.11.3, babel: v7.11.4, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​
```

### Code editor version
Visual Studio Code v1.48.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Quokka simply runs your file in node. Those pieces of your code that have been executed are highlighted with green, and can display runtime values. In your case on the screenshot, nothing that gets executed in the file calls the `Cart`   function, so it is  not executed and doesn't show any runtime values. If you add some code to call the function (for example add `Cart(...)` right before or after it's definition), it will be called and you will see expected results.
