### ISSUE TITLE
Quokka keeps turning it off

### ISSUE THREAD

**Issue by gyuripie** [wallabyjs/quokka#534]
### console.log("please don't stop");

function LetterCapitalize(str) {
  for (let i = 0; i < str.length; i++) {
    if ((i = 0)) {
      str[i] = str[i].toUpperCase();
    } else {
      str[i] = str;
    }
  }
  return str;
}
console.log(LetterCapitalize("hello"));

console.log("what is going on");

**Comment by gyuripie** [comment]
Also, I'd like to know why it also stops working when I copy and paste my code from another file?

**Comment by ArtemGovorov** [comment]
The issue is not Quokka related. Your sample code 

```js
function LetterCapitalize(str) {
for (let i = 0; i < str.length; i++) {
if ((i = 0)) {
str[i] = str[i].toUpperCase();
} else {
str[i] = str;
}
}
return str;
}
console.log(LetterCapitalize("hello"));

console.log("what is going on");
```

has an infinite loop in it, so your program never finishes. This line 
```js
if ((i = 0)) {
```
re-assigns `i` every iteration. Changing the assignment to binary expression should help:

```diff
-if ((i = 0)) {
+if ((i == 0)) {
```
