### ISSUE TITLE
Question: Live Performance Values?

### ISSUE THREAD

**Issue by mann-david** [wallabyjs/quokka#535]
### Issue description or question
Looking at the results for a live perf test, I see the following results:
` Σ 0.021ms, μ 0.010ms, ⋀ 0.008ms, ⋁ 0.013ms 
 0.045ms 
 0.012ms
`

Σ is the total execution time
μ is the mean (average?)

What are the rest?  The docs only mention _total execution time, average execution time (total execution time divided by number of times the expression had been executed), minimum and maximum_

What are the rest of the numbers?

### Code editor version

Visual Studio Code Insiders v1.49.0

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Can you please provide us with some sample code that produces the output that you're seeing? It's likely that you have some other code artifact that is causing values to be shown beyond `total execution time`, `average execution time`, `minimum` and `maximum`. For this sample:

```javascript
const fibonacci = (num) => {
  if (num <= 1) return 1;
  return fibonacci(num - 1) + fibonacci(num - 2);
}

for (let i = 0; i < 30; i++) {  
  fibonacci(i); //?.
}
```

we see:

![image](https://user-images.githubusercontent.com/2074089/91774207-a5f0ec00-ec2b-11ea-9baa-2ea0f2075441.png)

**Comment by smcenlly** [comment]
Closing this issue as we have not heard back. Hopefully you worked out what was wrong. If not, please reply and we'll re-open this issue.
