### ISSUE TITLE
Quokka Commands not found

### ISSUE THREAD

**Issue by sukheja-varun** [wallabyjs/quokka#539]
### Command 'Quokka.js: New TypeScript File' resulted in an error (command 'quokka.createTypeScriptFile' not found)
![image](https://user-images.githubusercontent.com/21065146/93292266-03dc1280-f79a-11ea-8d06-3a3f812e9241.png)

### Quokka.js Console Output
![image](https://user-images.githubusercontent.com/21065146/93292181-cf685680-f799-11ea-8602-6c867bba838c.png)

### Code editor version

Visual Studio Code v1.49.0

### OS name and version

OSX - Cataline v10.15.5

**Comment by smcenlly** [comment]
Could you please provide us with the console log immediately after restarting VS Code?
  1. Close and then reopen VS Code
  2. Immediately after opening, toggle the Developer Tools and provide us with the results (will be different from what you have shown above)

If the error does not provide any guide for what is going wrong, could you please uninstall the extension, delete `~/.vscode/extensions/wallabyjs.quokka-vscode-******` and then try reinstalling the extension.

**Comment by sukheja-varun** [comment]
I am closing this ticket as I was able to resolve it.
