### ISSUE TITLE
Quokka configuration and webpack

### ISSUE THREAD

**Issue by i-have-no-name** [wallabyjs/quokka#549]
Hi. I have a webpack config with
```
context: 'src'
```
I try to create .quokka config file and set 
```
{
  "env": {
    "params": {
      "env": "NODE_PATH=./src"
    }
  }
}
```
but it does not work and if I log `process.env.NODE_PATH` it has value `undefined`.

### Code editor version
Webstorm v20.2.2

### OS name and version

OSX Catalina 10.15.6

**Comment by smcenlly** [comment]
This seems to be working for us. Can you please confirm by trying the [sample repo](wallabyjs/quokka-549) we created that has your `.quokka` file and check that it outputs `process.env.NODE_PATH` as `./src`?

**Comment by smcenlly** [comment]
One thing to note is that your `.quokka` file must be in your project root. So if for example, you have a mono repo and open the mono repo root, the `.quokka` file must be in the mono repo root.

**Comment by i-have-no-name** [comment]
Link with repo is broken

**Comment by i-have-no-name** [comment]
If I move .quokka to the root, everything with env is fine, but `NODE_PATH` is not working for webpack.
```
Cannot find module 'utils/Immutable'
Require stack:
- ./packages/core/src/Document/models/Element.js
```

**Comment by i-have-no-name** [comment]
I found a problem, just fix path in .quokka.
