### ISSUE TITLE
Unable to use quokka in webstorm: java.net.ConnectException

### ISSUE THREAD

**Issue by RikuVan** [wallabyjs/quokka#55]
### Problem
Installing and running Quokka in Webstorm always fails for me with the following error output

```java
Operation timed out
java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at a.a.a.b.run(Unknown Source)
	at com.quokka.javascript.session.n.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
Could this have something to do with the premium version notification which never seems to go away when I first open a scratch file?

### Code editor version
Webstorm v2017.1.3

### OS name and version
MacOS Sierra 10.12.4

**Comment by ArtemGovorov** [comment]
> Could this have something to do with the premium version notification which never seems to go away when I first open a scratch file?

It shouldn't be related. Also, the premium version notification contains actionable links that turn the notification off (regardless of the selection).

Quokka spawns a node server and communicates with it from the IDE via WebSocket. It looks like your system may have some traffic filtering software/firewall or antivirus software installed that may be blocking the web socket traffic. If that's the case, then try disabling the software or whitelisting localhost web socket traffic in its settings.

**Comment by marcinqunabu** [comment]
Having the same issue in PHPStorm (2017.1.4) on MacOS Sierra (10.12.5).

`Operation timed out
java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
	at a.a.a.b.run(Unknown Source)
	at com.quokka.javascript.session.n.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by ArtemGovorov** [comment]
@marcinqunabu Did you check if your system may have some traffic filtering software/firewall or antivirus software installed?

**Comment by RikuVan** [comment]
I just started using in in VSCode without problems instead of Webstorm (still broken there). Never found any firewall/filtering issues as suggested, which doesn't mean they don't exist...but I am skeptical. Anyways, if you are a Webstorm user who really wants to try out quokka, one route is another editor for this purpose.

**Comment by ArtemGovorov** [comment]
@RikuVan Hmm, interesting, thanks for sharing. Are you behind any proxy (perhaps have proxy settings in your VS Code/WebStorm settings)?

**Comment by ArtemGovorov** [comment]
Also could you please paste your `/etc/hosts` file content (or `C:\Windows\system32\drivers\etc\hosts` for Windows users experiencing the issue)?

**Comment by RikuVan** [comment]
Here is part of the file
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
//crap load of vagrant stuff here
10.211.55.3  {myId}-bpm
10.211.55.3  localhost
10.211.55.3     windows-10.shared windows-10 #prl_hostonly shared

**Comment by marcinqunabu** [comment]
For me the problem was with /etc/hosts file and line:
127.0.1.1       localhost.vm    localhost

**Comment by ArtemGovorov** [comment]
I have added some code to try fix the issue. Please try the latest (1.0.12) version of the plugin to see if it works for you.

**Comment by RikuVan** [comment]
The latest version didn't solve the issue for me.

**Comment by tushariscoolster** [comment]
I use following code for development,
#127.0.0.1 localhost
127.0.0.1 media-api
255.255.255.255 broadcasthost
::1             localhost


But this create problem while running qoukka

**Comment by smcenlly** [comment]
We rely on the hostname `localhost` resolving to your local machine, which you've commented out. In your development environment, are you able to uncomment that line so that you have both `localhost` and `media-api` pointing to `127.0.0.1`?

**Comment by smcenlly** [comment]
Can you also confirm that this is working for you if you don't override your hosts file?

**Comment by tushariscoolster** [comment]
It works well when i uncomment, Thanks
