### ISSUE TITLE
Display Quokka filename instead of Quokka #1, Quokka #2 in Quokka output window for JetBrains Editors

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#551]
Feature request from discord: Display Quokka filename instead of Quokka #1, Quokka #2 in Quokka output window for JetBrains Editors

**Comment by rdhar** [comment]
Didn't even realize there was a dedicated [Discord server](https://quokkajs.com/chat/)!

**Comment by smcenlly** [comment]
This has been completed and is available in Quokka for IntelliJ `v1.0.343`.
