### ISSUE TITLE
btoa and atob producing wrong values

### ISSUE THREAD

**Issue by mhamri** [wallabyjs/quokka#552]
the output from `a` isn't equal to `c`

### Sample code

```javascript
({
  plugins: ['jsdom-quokka-plugin'],
});

const c = 'hello world';
const b= atob(c);
b
const a= btoa(b)
a

console.log(c===a)
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.ts' (node: v12.19.0, TypeScript: v4.0.3, plugins: jsdom-quokka-plugin)​​​​
 
ée£ 
+ 
  at ​​​b​​​ ​quokka.ts:7:0​

helloworlQ== ​​​​​at ​​​a​​​ ​quokka.ts:9:0​

false ​​​​​at ​​​c === a​​​ ​quokka.ts:12:0​
```

### Code editor version

Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by ArtemGovorov** [comment]
This is expected and is not Quokka related. If you execute the same code in browser, or in node without Quokka, you will be the exact same result:
<img width="205" alt="Screen Shot 2020-10-12 at 8 48 23 pm" src="https://user-images.githubusercontent.com/979966/95738287-5393f800-0ccc-11eb-8868-1ae040166ac4.png">

Perhaps you wanted to do this instead:

<img width="242" alt="Screen Shot 2020-10-12 at 8 54 56 pm" src="https://user-images.githubusercontent.com/979966/95738859-3f9cc600-0ccd-11eb-8506-42a34a519511.png">

```js
const c = 'hello world';
const b= btoa(c);
b
const a= atob(b)
a

console.log(c===a)
```

**Comment by mhamri** [comment]
you are right, I just noticed, I wrote the functions wrong
