### ISSUE TITLE
Feature Request: Provide the ability to always log the value of every line

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/quokka#554]
I'm hoping to use Quokka like math scratch-pad (similar to Calca).

Quokka already more or less does this perfectly, however, there's one small tweak that should make it absolutely perfect.

Right now, when I write an expression, Quokka does not show the result of that expression.

![image](https://user-images.githubusercontent.com/2074089/96319758-ea0d4400-1053-11eb-8e46-b771394c9c35.png)

It would be awesome if there was a configuration in Quokka that would output the results, without having to append //? (see below).

![image](https://user-images.githubusercontent.com/2074089/96319764-eda0cb00-1053-11eb-8068-10319aa439d3.png)

**Comment by rdhar** [comment]
Same, I thought this'd be included in Pro but it doesn't seem to be the case.

**Comment by smcenlly** [comment]
We have added a new `Auto Log` feature to Quokka (now mentioned in our docs). The feature is available for all editors.

> If you want Quokka to show the runtime values for every single line of your code then you may use the `Toggle Auto Log` command. By default, Quokka will start with Auto Log disabled, but this can be changed with [configuration](https://quokkajs.com/docs/configuration.html#auto-log).
> 
> This feature is useful in scenarios such as when you are live coding and have intermediate results that you want to be displayed as you type.
> 
> ![image](https://quokkajs.com/assets/img/vsc-auto-log.gif)

**Comment by rdhar** [comment]
@smcenlly This is pretty stellar, thanks for sharing!

Is it possible to make this an extension-level setting to have it enabled globally by default, similar to "Show Output on Start"? Amazing to have this level of real-time feedback directly within VS Code.

**Comment by smcenlly** [comment]
Yes - please see the comment above, the default behavior (disabled by default) can be changed with [configuration](https://quokkajs.com/docs/configuration.html#auto-log).

**Comment by rdhar** [comment]
Thanks, @smcenlly. I hope I'm not missing something obvious because I'm still not seeing that option under Quokka's 12 configuration settings within VS Code, attached.

If it's something that can only be enabled by default at a workspace-level, would it be possible to integrate at a global level within the extension settings directly? Thanks for your time.

![image](https://user-images.githubusercontent.com/19497993/111040368-9cdaa600-842a-11eb-9a55-9ab86aa5148d.png)

**Comment by smcenlly** [comment]
I have copy pasted the relevant section from our docs (see below) as per [the link to our docs](https://quokkajs.com/docs/configuration.html#auto-log) in my previous responses. 

If you're not familiar with how to configure Quokka, please read through [our docs](https://quokkajs.com/docs/configuration.html).

> ## Auto Log
> Quokka ‘Pro’ allows users to change the behavior of Quokka to use Show Value to automatically show the runtime value for every line of code. This behavior can be changed after starting Quokka using the `Toggle Auto Log` command.
> 
> By default, this behavior is disabled but may be changed using the autoLog configuration setting:
> 
> ```javascript
> {
>   ...
>  "autoLog": true
> }
> ```
