### ISSUE TITLE
quokka cannot find module

### ISSUE THREAD

**Issue by caberg** [wallabyjs/quokka#555]
### Issue description or question
recently im using quokka for the first time and quokka keep tell me that's something wrong with all the module i have when tried to run Quokka on current file
### Sample code
here's the initial code im using
```javascript
import { Injectable, NotFoundException, HttpService , Logger, NotImplementedException } from '@nestjs/common';
```
but it's tell me this on quokka console output
```javascript
​Install "@nestjs/common" package for the current quokka file​
​Install "@nestjs/common" package into the project​
 
Error quokka_fake_path/instrumented/fwdsg-fe-life-api/src/ha/product.service.ts (1,94): Cannot find module '@nestjs/common' or its corresponding type declarations.
```
hmm i get this, maybe quokka doesnt know its path, so i changed into this
```javascript
import { Injectable, NotFoundException, HttpService , Logger, NotImplementedException } from '../../node_modules/@nestjs/common';
```
but its still had an error even though the install warning is gone
```javascript
Error quokka_fake_path/instrumented/fwdsg-fe-life-api/src/ha/product.service.ts (1,94): Cannot find module '../../node_modules/@nestjs/common' or its corresponding type declarations. 
```
maybe something wrong with my config ? what im missing ? it's happen to all of my module import
here's my tsconfig.json in my root project folder
```javascript
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,    
  }
  ,
  "exclude": ["node_modules", "dist"]
}
```
and for tsconfig.build.json
```javascript
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
}
```
and for my package.json
```json
{
  "name": "fwdsg-fe-life-api",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "",
  "scripts": {
    "xxxxprebuild": "rimraf dist",
    "build": "nest build",
    "build:prod": "rimraf dist && npm run build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "node dist/main.js",
    "start:debug-xxx": "nodemon --config nodemon-debug.json",
    "start:dev": "npm run start:dev-uat",
    "start:dev-uat": "cross-env NODE_ENV=development DB_EN=UAT nest start --watch",
    "start:dev-sit": "cross-env NODE_ENV=development DB_EN=SIT nest start --watch",
    "start:nodemon": "nodemon",
    "start:ts": "ts-node -r tsconfig-paths/register src/main.ts",
    "debug:nest": "nest start --debug --watch",
    "docker:compose-up": "docker-compose up",
    "docker:compose-down": "docker-compose down",
    "docker:debug": "nodemon -L --config nodemon-docker-debug.json",
    "prestart:prod": "rimraf dist && npm run build",
    "prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@fwdsg/fe-shared": "file:../shared",
    "@hapi/joi": "^17.1.1",
    "@nestjs/common": "^7.0.0",
    "@nestjs/config": "^0.5.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/typeorm": "^7.1.1",
    "axios": "^0.20.0",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "dotenv": "^8.2.0",
    "mssql": "^6.2.1",
    "nest-winston": "^1.3.6",
    "node-fetch": "^2.6.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^6.6.2",
    "typeorm": "^0.2.25",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "@nestjs/cli": "^7.0.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@types/express": "^4.17.3",
    "@types/jest": "26.0.10",
    "@types/node": "^13.9.1",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "3.9.1",
    "@typescript-eslint/parser": "3.9.1",
    "cross-env": "^7.0.2",
    "eslint": "7.7.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "form-data": "^2.3.2",
    "jest": "26.4.2",
    "moment": "^2.28.0",
    "nodemon": "^2.0.4",
    "pm2": "^4.4.1",
    "pm2-logrotate": "^2.7.0",
    "prettier": "^1.19.1",
    "rimraf": "^3.0.2",
    "supertest": "^4.0.2",
    "ts-jest": "26.2.0",
    "ts-loader": "^6.2.1",
    "ts-node": "9.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^3.7.4"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".spec.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  }
}
```
### Code editor version

Visual Studio Code v1.50.1

### OS name and version

Windows 10 Pro

**Comment by ArtemGovorov** [comment]
It looks like Quokka can't find any node modules maybe because it is not running in your project directory for some reason. 

- Are node modules installed for the project (ie. `fwdsg-fe-life-api/node_modules/@nestjs/common` exists)?
- Do you have only one `fwdsg-fe-life-api` project root opened in your editor when you're trying to run Quokka on some file in the project?

**Comment by caberg** [comment]
- yes , all the module are installed correctly and `fwdsg-fe-life-api/node_modules/@nestjs/common` is exists

- i had only one project root when this happen, and run only one file

**Comment by smcenlly** [comment]
@caberg - could you please confirm that the project root that you had opened was the `fwdsg-fe-life-api` folder?

Please try the exact following steps:

1. In VS Code, open a new Window with the `New Window` command.
2. In VS Code, open the `fwdsg-fe-life-api` folder using the `File: Open Folder...` command.
3. Start Quokka on a file that exists in the opened folder.

If that does not work for you, please delete and reinstall your `node_modules`. We're assuming that you are using `npm` or `yarn` to install your project dependencies. If not, please let us know what package manager you are using.

**Comment by caberg** [comment]
@smcenlly just following your steps guide but error still happen
`Error quokka_fake_path/instrumented/src/ha/product.service.ts (1,94): Cannot find module '../../node_modules/@nestjs/common' or its corresponding type declarations. `

deleting node_modules and reinstall it again using npm but nothing fix, error still happen
`Error quokka_fake_path/instrumented/src/ha/product.service.ts (1,94): Cannot find module '../../node_modules/@nestjs/common' or its corresponding type declarations.`

do i need to setup the global config or any config for my setup ? because i doesn't set up any config for my project to run quokka

**Comment by smcenlly** [comment]
> do i need to setup the global config or any config for my setup ? because i doesn't set up any config for my project to run quokka

No - from the project configuration you shared, it doesn't look like your project needs any configuration.

Using the details that you provided to us, we have created a [sample repo](https://github.com/wallabyjs/quokka-555) that is working for us. Could you please clone our repo, run `npm install` and confirm that everything is working for you?

If our repo is working but your project is not, you may try copying some files from your actual project to isolate why it's not working for you. Alternatively, if you can provide us with a repo that has your problem, we are happy to take a look.

**Comment by caberg** [comment]
@smcenlly thx for the repo, it's works well in my end. but when i paste my code on it, the error still occur. my setup is very complicated and must have vpn access to make it works, maybe the vpn caouse all of this.

it'll be the best if i create repo for this for all my files but this against company rule. but thx for all the help

**Comment by smcenlly** [comment]
If you copy a single file that doesn't work into the sample project, do you get the same issue? If so, can you strip out any project-specific code and paste the location that you have copied to as well as the content of the single file that is failing below so that we may try on our machines?

**Comment by smcenlly** [comment]
Closing this issue. If you can provide more information, please reply and we will re-open.
