### ISSUE TITLE
Functionality disappear when I save the file

### ISSUE THREAD

**Issue by minifisk** [wallabyjs/quokka#556]
The program works fine, but as soon as I'm trying to save the file, all the functions of quokka disappears.

**Comment by smcenlly** [comment]
Are you using the PRO version? Is it possible that you're launching with the command, `Quokka.js: Run once for Current File` (as that would explain the behavior)?

If you're starting Quokka some other way, can you please:

1. Provide the code that you are running (or a sample that has the same problem)
2. Detail which editor and operating system you are using
3. Provide the version of Quokka that you are using
4. Provide step-by-step instructions for how you are starting Quokka

**Comment by ArtemGovorov** [comment]
After you save Quokka scratch file (first time only), you need to restart Quokka on the saved file using Start on existing file command (`Cmd/Ctrl + K, Q`).

**Comment by minifisk** [comment]
> After you save Quokka scratch file (first time only), you need to restart Quokka on the saved file using Start on existing file command (`Cmd/Ctrl + K, Q`).

Now it's suddenly not working again, even with the commands that you recommended.

`import React from "react"
import App from "./App.js"


const WeatherCard = props => {
let topcolor = (1-(props.temp-12)/28)*255
let lowcolor = topcolor - 150


 return (
<div style={{backgroundImage: `linear-gradient(rgb(255,${topcolor},0),rgb(255, ${lowcolor},0))`}} className="card">
    <div className="location">
        <h1 className="city">Sydney</h1>
        <h3 className="country">AU</h3>
    </div>
    <img className="icon" src="./img/Mostly Cloudy-2x.png" alt="Weather Icon"/>
    <h1 className="temp">20°C</h1>
    <h3 className="conditon"> Clouds</h3>
</div>

    )
}

WeatherCard()

console.log(props.temp)



export default WeatherCard

`

**Comment by smcenlly** [comment]
Your code has an error so it won't actually execute, what if you change it to:

```javascript
import React from "react"
import App from "./App.js"

const WeatherCard = props => {
let topcolor = (1-(props.temp-12)/28)*255
let lowcolor = topcolor - 150

return (
<div style={{backgroundImage: `linear-gradient(rgb(255,${topcolor},0),rgb(255, ${lowcolor},0))`}} className="card">
    <div className="location">
        <h1 className="city">Sydney</h1>
        <h3 className="country">AU</h3>
    </div>
    <img className="icon" src="./img/Mostly Cloudy-2x.png" alt="Weather Icon"/>
    <h1 className="temp">20°C</h1>
    <h3 className="conditon"> Clouds</h3>
</div>
    )
}

WeatherCard({temp: 30}) //?
export default WeatherCard
```

**Comment by minifisk** [comment]
> Your code has an error so it won't actually execute, what if you change it to:
> 
> ```js
> import React from "react"
> import App from "./App.js"
> 
> const WeatherCard = props => {
> let topcolor = (1-(props.temp-12)/28)*255
> let lowcolor = topcolor - 150
> 
> return (
> <div style={{backgroundImage: `linear-gradient(rgb(255,${topcolor},0),rgb(255, ${lowcolor},0))`}} className="card">
>     <div className="location">
>         <h1 className="city">Sydney</h1>
>         <h3 className="country">AU</h3>
>     </div>
>     <img className="icon" src="./img/Mostly Cloudy-2x.png" alt="Weather Icon"/>
>     <h1 className="temp">20°C</h1>
>     <h3 className="conditon"> Clouds</h3>
> </div>
>     )
> }
> 
> WeatherCard({temp: 30}) //?
> export default WeatherCard
> ```

I don't know what you did but suddenly my code started working, thanks so much for that! 

But I still can't manage to get Quokka to work. I've tried "Quokka.js Start on current file" and also the "cmd + k + q" command but still don't get anything. I've taken your code (and call this code in my app.js) but I don't get any console log of "test"...

`import React from "react"
import App from "./App.js"

const WeatherCard = props => {
let topcolor = (1-(props.temp-12)/28)*255
let lowcolor = topcolor - 150


return (
<div style={{backgroundImage: `linear-gradient(rgb(255,${topcolor},0),rgb(255, ${lowcolor},0))`}} className="card">
    <div className="location">
        <h1 className="city">Sydney</h1>
        <h3 className="country">AU</h3>
    </div>
    <img className="icon" src="./img/Mostly Cloudy-2x.png" alt="Weather Icon"/>
    <h1 className="temp">20°C</h1>
    <h3 className="conditon"> Clouds</h3>
</div>
    )
}

console.log("test")


export default WeatherCard

`

**Comment by ArtemGovorov** [comment]
What is the output of your Quokka console output channel in VS Code after you run `Quokka.js Start on current file` command?

**Comment by kalkidanyishak** [comment]
> What is the output of your Quokka console output channel in VS Code after you run `Quokka.js Start on current file` command?

I had the same promblem but now it works thanks
