### ISSUE TITLE
Can't find the extension in VsCode Linux

### ISSUE THREAD

**Issue by M-Gonzalo** [wallabyjs/quokka#559]
![DeepinScreenshot_Seleccionar área_20201102155003](https://user-images.githubusercontent.com/23223606/97907274-cc163380-1d23-11eb-9aea-4d830a6b05cf.png)

**Comment by smcenlly** [comment]
It looks like you are using VS Code from the OSS github repo. As per Microsoft's VS Code github issue, the marketplace is only available in their Visual Studio Code product that they ship and not via VS Code OSS. If this is the case then you will find that only built-in extensions are working and you won't be able to install any others (e.g. Wallaby.js, Prettier, Gitlens, etc.)

We don't have VS Code set up from their github repo so can't easily test, but you should be able to [download the Quokka extension from the marketplace](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) and install it from the VSIX.

From: [https://github.com/microsoft/vscode-wiki/pull/34](https://github.com/microsoft/vscode-wiki/pull/34)

> It's confusing that OSS dev mode missing the extension gallery. The are questions about it in issues and stackoverflow. I think it would be helpful to point out the recommended way of working with extensions, so I did a summary of such questions:
> [#23831](https://github.com/Microsoft/vscode/issues/23831)
> [#30](https://github.com/Microsoft/vscode-wiki/pull/30)

From Microsoft team in [https://github.com/Microsoft/vscode-wiki/pull/30](https://github.com/microsoft/vscode-wiki/pull/30#issuecomment-315265462):
> Access to the Visual Studio Marketplace is something that we only make available as a part of the Visual Studio Code product (see microsoft/vscode#60 (comment)). The way we recommend to test an extension against the OSS build is to side load the extension using the command line (see https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management).

**Comment by M-Gonzalo** [comment]
Oh thanks, that's really helpful! Keep up the good work!
