### ISSUE TITLE
Configure context

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/quokka#56]
I have many folders open in an IntelliJ project and want to run Quokka on one of the sub-folders.

From #5:

> Currently quokka always runs in the context of the project root.

Can this be configurable? Ideally, when I open a Quokka file, it looks for the closest package.json file of the file that was open in the editor, and sets this to the context.

**Comment by vjpr** [comment]
Placing the following at the top of the quokka file is a workaround.

```
require('app-module-path').addPath(__dirname + '/dotfiler/node_modules')
```

...then after it runs you can require modules. But if you try to require at the same time you add this it won't immediately work.

**Comment by vjpr** [comment]
## Usage

```
({
  subdir: 'foo'
})

// You must run without any import's once.
import _ from 'lodash'

```

## Plugin (subdir-quokka-plugin)

```
const {join} = require('path')
const appModulePath = require('app-module-path')

module.exports = {
  before: config => {
    const dir = config.subdir || {}
    if (!dir) return
    const cwd = process.cwd()
    const moduleDir = join(cwd, dir)
    const paths = [
      moduleDir,
      join(moduleDir, 'node_modules'),
    ]
    paths.map(p => appModulePath.addPath(p))
    console.log('Adding to NODE_PATH:', paths)
  },
  beforeEach: config => {

  },
}

```

**Comment by vjpr** [comment]
My issue with the workaround is that I use `babel-plugin-module-resolver` to transpile my code, so when I write `import foo from 'modules/foo'` it is changed to `import foo from ./src/modules/foo` which depends on the `__dirname` being correct.

```
    [require('babel-plugin-module-resolver').default, {
      root: ['./src'],
    }],
```

**Comment by ArtemGovorov** [comment]
> Currently quokka always runs in the context of the project root.

This had been fixed a while ago. Right now only scratch-file based quokkas run in the context of the project's root (there's simply no reasonable way to run the tmp scratch files any other way). 

However, when you run quokka on project files, it will run them the same way as the IDE node configuration would.

![wj](https://cloud.githubusercontent.com/assets/979966/26289506/08fef5e2-3ee4-11e7-96f0-6b20e7df7aa8.gif)

**Comment by vjpr** [comment]
Ok, I was using scratch fIles. Is there a way to have a plugin change the
__filename of thr scratch file - or how it requires relative files? I guess
overriding Module.resolveFilename might be the way to go.

**Comment by ArtemGovorov** [comment]
@vjpr [Patching the `Module._load`](https://quokkajs.com/docs/configuration.html#comment-3311503358) should do the trick.

**Comment by vjpr** [comment]
> there's simply no reasonable way to run the tmp scratch files any other way

Why is that? When the scratch file is opened, couldn't we take the current focused editor, and do a https://www.npmjs.com/package/read-pkg-up to find the closest `package.json`?

This could be configurable in the settings:

a. Use project dir
b. Use closest package.json
c. Use closest IntelliJ project module root

**Comment by vjpr** [comment]
I have completed my plugin and it works well:

```
  // TODO(vjpr): Support multiple extensions, not just .es6.
  const quokkaScratchFile = join(process.cwd(), 'quokka.es6')
  // Where the scratch file should think it is for purposes of requiring other modules.
  const targetContext = join(process.cwd(), dir)
  const targetContextNodeModules = join(targetContext, 'node_modules')

  const originalLoad = Module._load
  Module._load = function(filename, parent, isMain) {
    if (parent.filename === quokkaScratchFile) {
      parent.paths.unshift(targetContextNodeModules)
      if (filename.startsWith('.')) {
        filename = './' + dir + '/' + path.normalize(filename)
      }
    }
    return originalLoad.call(this, filename, parent, isMain)
  }
```

**Comment by ArtemGovorov** [comment]
> When the scratch file is opened, couldn't we take the current focused editor

A scratch file can be opened when there's no opened editors at all, or an opened editor has no focus. Using the last focused editor as a source for the context may be counterintuitive - a user may want to open a quokka file in the project's root, but just because he had some file(s) opened, he may get the unexpected quokka context.

We'll evaluate an idea of opening a new scratch quokka files from the context of the project tree - this way a user should be able to launch a new quokka file in any folder and it should hopefully be more intuitive.

**Comment by vjpr** [comment]
@ArtemGovorov Is there a way to change the CWD that the babel transpiler uses?

**Comment by ArtemGovorov** [comment]
@vjpr I'm not sure I understand the question. The transpiler should just be using the `process.cwd()`. Could you please provide some more context on what you're trying to do, or perhaps share an example that doesn't work for you so I could have a look?

**Comment by ArtemGovorov** [comment]
@vjpr Answering your question, [perhaps `process.chdir` could help](https://nodejs.org/api/process.html#process_process_chdir_directory), but without some more details I'm not really sure how it's going to affect other things (or even if it's something that you really need to do).

**Comment by vjpr** [comment]
@ArtemGovorov I am running quokka in a module that is a sub folder in a bigger intellij project. My babel config uses the `babel-plugin-module-resolver` plugin, which rewrites aliases to relative paths.

```
- monorepo
  - project-b
  - project-a
    - src
      - modules
        - foo
        - index.js
```

```
project-a/src/modules/index.js

require('modules/foo') // transpiled to require('../modules/foo')
```

But babel seems to be running using cwd = `monorepo`, even if I call `process.chdir('monorepo/project-a)`.

And this causes my relative links to the module aliases to not work correctly...

**Comment by vjpr** [comment]
So wherever`babel.compile` is run by quokka, it would be good to be able to specify the cwd. `process.chdir` doesn't seem to affect it.

**Comment by ArtemGovorov** [comment]
This code: 
```
require('modules/foo') // transpiled to require('../modules/foo')
```
is not inside the quokka file, is it? For all files (except the quokka file itself) quokka is simply using [`babel-register`](https://babeljs.io/docs/usage/babel-register/), that doesn't seem to have an option to change/pass cwd.

However the [`babel-plugin-module-resolver` plugin allows to pass cwd](https://github.com/tleunen/babel-plugin-module-resolver#options), so perhaps you could use the setting? Quokka [allows to overwrite .babelrc settings](https://quokkajs.com/docs/configuration.html#overriding-babel-settings).

**Comment by Nodman** [comment]
I made small plugin for resolving imports from subdirectories, if anyone still needs this: search npm for quokka-plugin-subdir

**Comment by ArtemGovorov** [comment]
@Nodman Awesome, thanks for sharing! We have added your plugin to the [plugins section in the docs](https://quokkajs.com/docs/configuration.html#notable-plugins).

**Comment by Nodman** [comment]
@ArtemGovorov thank you! :)
