### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by exclipy** [wallabyjs/quokka#560]
### Issue description or question

I tried starting Quokka for the first time in a while and it failed to start.

### Sample code

(empty file started with the "Quokka.js: New JavaScript File" command)

### Quokka.js Console Output

```
​​​​​Quokka​​​​
TypeError: N.create is not a function 
    at Module._compile (module.js:413:34) 
    at Object.Module._extensions..js (module.js:422:10) 
    at Module.load (module.js:357:32) 
    at Function.Module._load (module.js:314:12) 
    at Function.Module.runMain (module.js:447:10) 
    at startup (node.js:141:18) 
    at node.js:933:3 
```

### Code editor version

Visual Studio Code v1.51.0
Quokka.js v1.0.328

### OS name and version

MacOS 10.15.7

**Comment by ArtemGovorov** [comment]
Try to 
- uninstall the extension, 
- delete all `~/.vscode/wallabyjs.quokka-vscode-*` folders,
- delete `~/.quokka/node_modules` folder,
- install the extension.

to see if it helps.

If it doesn't help, try running `Quokka.js: New JavaScript File`:
- on a different project,
- in VS Code window without any opened project (`File - Close Folder`).

**Comment by exclipy** [comment]
None of that worked but I figured it out.

Somehow, I had reverted to an old version of Node (v5!).  I upgraded to Node 14 and it worked.  Maybe you could add a Node version check so you can show a better error message.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! We'll take a look into improving the error message.
