### ISSUE TITLE
Option to Prevent Update On Selection

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/quokka#561]
In last few days Auto Update on Selection (double click in my case) annoys me a lot!
`//ignore coverage` helps but this is bad workaround and we need good solution for that.
There is situations/projects when we don't want to know what is the value under selection.
**Ideas:**
- Add option to configure this behavior with something like `{"selection_preview":false}` inside configuration file.
- if first line of file contains `//ignore selection`

**Comment by smcenlly** [comment]
Thanks for your feature request. We've added this as a [new Quokka setting](https://quokkajs.com/docs/configuration.html#show-value-on-selection). If you're not familiar with how to configure Quokka, you may refer to the [configuration section](https://quokkajs.com/docs/configuration.html) of our Quokka docs.

```json
 {
     "showValueOnSelection": false
 }
```
