### ISSUE TITLE
Next.js + Typescript + React + Quokka

### ISSUE THREAD

**Issue by bennylame** [wallabyjs/quokka#563]
### Issue description or question
Hi, 

So I have been trying to configure Quokka with a current Next.js + React + Typescript project and can't get it to work. It has been a really frustrating day learning how to configure Quokka without success. I think it is worth it for future projects but right now it feels like a waste of time.

From my understanding, if I do not want to fill up my project's node_modules folder with additional packages I can add them to Quokka globally instead. According to [this](https://github.com/wallabyjs/quokka-create-react-app-ts):

 "_Please note: you may install the jsdom-quokka-plugin and @babel/register packages to your global quokka folder if you don't want to pollute your project's node modules. If you install globally, you will not need to add them again for subsequent projects_." 

```
cd ~/.quokka
npm install jsdom-quokka plugin @babel/runtime
```

Tried that and then started Quokka on a current file and did not succeed. Explored quite a lot and tried different configs, now I have ended up with this:

```
package.json in ~/.quokka

{
  "dependencies": {
    "@babel/plugin-transform-typescript": "^7.12.1",
    "@babel/preset-typescript": "^7.12.7",
    "@babel/register": "^7.12.1",
    "@babel/runtime": "^7.12.5",
    "babel-preset-react-app": "^10.0.0",
    "jsdom": "^16.4.0",
    "jsdom-quokka-plugin": "^1.0.16"
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```

```
config.json in ~/.quokka

{
  "pro":true,
  "babel": {
      "ts": {
        "compilerOptions": {
        "jsx": "react"
        }
      }
    },
  "plugins": ["jsdom-quokka-plugin"],
  "stdEsm": false,
  "nativeEsm": true
}
```

```
tsconfig.json in my project
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

```
package.json in my project
{
  "name": "storefront",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@material-ui/icons": "^4.9.1",
    "mobx": "^6.0.0",
    "mobx-react": "^7.0.0",
    "next": "9.5.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "sass": "^1.26.11"
  },
  "devDependencies": {
    "@types/node": "^14.14.6",
    "@types/react": "^16.9.56",
    "typescript": "^4.0.5"
  }
}
```
### Sample code

```javascript
import styles from "./ColorComponent.module.scss";

const ColorComponent = ({ colors }) => {
  let currentColor = null;
  const chooseColorHandler = (index) => {
    currentColor = index;
  };
  console.log("hej"); //just trying a simple console log to see if Quokka works in project
  let colorBoxes : JSX.Element[] = null;
  if (colors) {
    colorBoxes = colors.map((color, index) => {
      return (
        <div className={styles.colorBoxParent}>
          <div
            className={styles.colorBox}
            key={index}
            onClick={chooseColorHandler}
          />
        </div>
      );
    });
  }
  return (
    <div className={styles.container}>
      <div className={styles.pickedColor}>
        <p>Color</p>
        <h3>{currentColor}</h3>
        {colorBoxes}
      </div>
    </div>
  );
};

export default ColorComponent;
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka 'OrderDetails.tsx' (node: v15.1.0, TypeScript: v4.0.5, plugins: jsdom-quokka-plugin)​​​​
 
Cannot find module './components/OrderDetails/OrderDetails.js' 

Don't know why it is looking for a .js file when I'm running on a .tsx file. This happened after I added: 
    "ts": {
        "compilerOptions": {
        "jsx": "react"
        }
to the config.json
```

### Code editor version

Visual Studio Code v1.51.0

### OS name and version

OSX Catalina 10.15.7

**Comment by smcenlly** [comment]
Thanks for providing so much detail in your issue description, it was a big help in understanding why Quokka wasn't working for you.

The reason you're getting a problem is that your Quokka `config.json` is using `"nativeEsm": true`, which is not compatible when you are running TypeScript with Quokka. Various tools like Quokka, ts-node (or any other node tool that compiles TypeScript on the fly), Babel register, Jest (or other testing frameworks), etc., that need to preprocess or compile files, map module paths, and so on, don’t have access to an API yet to fully and stably support node ES modules. We'll update Quokka to provide a more meaningful error when `nativeEsm` is used in combination with TypeScript files.

If you change this setting to `false` Quokka should work for you. You can do this for all projects by change the setting in your Quokka `config.json` or else you can override the setting at the project level by creating a `.quokka` file in your project root directory (overriding configuration is described in [our docs](https://quokkajs.com/docs/configuration.html)).

In your sample, you will also need to call `ColorComponent` in order to execute your `console.log`. As it exists right now, you are defining functions, but not actually executing anything. For example:

```diff
import styles from "./ColorComponent.module.scss";

const ColorComponent = ({ colors }) => {
  let currentColor = null;
  const chooseColorHandler = (index) => {
    currentColor = index;
  };
  console.log("hej"); //just trying a simple console log to see if Quokka works in project
  let colorBoxes : JSX.Element[] = null;
  if (colors) {
    colorBoxes = colors.map((color, index) => {
      return (
        <div className={styles.colorBoxParent}>
          <div
            className={styles.colorBox}
            key={index}
            onClick={chooseColorHandler}
          />
        </div>
      );
    });
  }
  return (
    <div className={styles.container}>
      <div className={styles.pickedColor}>
        <p>Color</p>
        <h3>{currentColor}</h3>
        {colorBoxes}
      </div>
    </div>
  );
};

export default ColorComponent;

+ ColorComponent()
```

**Comment by bennylame** [comment]
That did it! Also, thanks for reminding me that I'm defining functions!
