### ISSUE TITLE
Quokka.js error with react-native

### ISSUE THREAD

**Issue by smironescu** [wallabyjs/quokka#564]
### Issue description or question
```
Missing initializer in const declaration 
```
When running quokka on an existing react-native project
### Sample code

```javascript
import React from 'react';
import { View } from 'react-native';
import { CommonActions } from '@react-navigation/native';
import { Icon } from 'react-native-elements';
import { homeIcon } from '../../../src/css/styles/home';

const handlerGoHome = (props) => {
    Object.assign(props.group, {
        group_name: 'Moodem'
    });
    props.navigation.dispatch(
        CommonActions.reset({
            index: 0,
            routes: [
                {
                    name: 'Moodem',
                    params: {
                        group: {
                            group_name: 'Moodem',
                            group_id: null
                        }
                    },
                }
            ],
        })
    );
};

export const Home = (props) => (
    <View>
        <Icon
        iconStyle={homeIcon}
        name='home'
        type='antdesign'
        color='#dd0031'
        size={25}
        onPress={() => handlerGoHome(props)}
        />
    </View>
);

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka 'Home.js' (node: v12.16.3, babel: v7.12.9, plugins: jsdom-quokka-plugin)​​​​
 
Missing initializer in const declaration 
  at ​​​wrapSafe​​​ ​internal/modules/cjs/loader.js:1047​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1097​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1153​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:977​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:877​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:1019​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:77​
  at ​​​Object.<anonymous>​​​ ​./node_modules/react-native/Libraries/react-native/react-native-implementation.js:14​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1133​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1153​
  at ​​​Object.newLoader [as .js]​​​ ​./node_modules/pirates/lib/index.js:104​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:977​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:877​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:77​
  at ​​​Object.<anonymous>​​​ ​components/User/functional-components/Home.js:2​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1133​

```

### Code editor version

Visual Studio Code v1.51.1

### OS name and version

OSX Mojave 10.14.5

**UPDATE**

- .quokka file

```
{
  "babel": {
    "presets": ["react-app"]
  },
  "plugins": ["jsdom-quokka-plugin"]
}
```

**Comment by smcenlly** [comment]
While Quokka supports running files within a `create-react-app` project, Quokka does not currently support `react-native`. You may [subscribe to this feature request](https://github.com/wallabyjs/quokka/issues/428) to stay up-to-date with any changes to this.

From the feature request description:

> Quokka.js files run in node.js after applying any configured TypeScript/Babel transformations.
> 
> When `react-native` runs, it has access to device-specific APIs that are not natively available in the node.js runtime. As a result, `react-native` applications cannot simply "run" in node.js, even after babel transforms have been applied.

---

When we last investigated adding support for `react-native` it looked to be possible to implement via a Quokka plugin (which may be open source) that would mock the react-native API calls so that it can run in node.

The first steps to getting this working would be to work completely outside of Quokka and run the same babel transforms that happen when react-native runs (e.g.  `{ "presets": ["module:metro-react-native-babel-preset"] }`) and mock the necessary react API calls so that you can run your file in `node.js`.
