### ISSUE TITLE
vs-codium

### ISSUE THREAD

**Issue by Dimchx** [wallabyjs/quokka#566]
Hello,

is there a way to use your useful "quokka" extension with the vs-codium editor?

Thank you,

**Comment by ArtemGovorov** [comment]
You may install the [extension from VSIX](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) as a temporary solution. To get notified when a permanent solution is available please subscribe to https://github.com/wallabyjs/public/issues/2436.
