### ISSUE TITLE
I can't seem to get .env files working

### ISSUE THREAD

**Issue by zameericle** [wallabyjs/quokka#568]
### Issue description or question
I'm on OS X and am using the Quokka VSCode extension.
Ive installed the Quokka dotnetenv plugin and have created a .env file in the folder where my js file exists within my workspace.  It never sees to load.

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
This appears to be working for us. 

Could you please check if this is working for you in this [sample repository](https://github.com/wallabyjs/quokka-568)? To try it out:

1. Run `git clone https://github.com/wallabyjs/quokka-568.git` from your terminal/command prompt.
1. Run `quokka-568` to go to the project directory.
1. Run `npm install` to install project dependencies (in this case, only `dotenv-quokka-plugin`).
1. Start Quokka on `index.js` or `index.ts` to confirm the environment variable from the `.env` file is being correctly returned.

Please note that by default the `dotenv-quokka-plugin` will load the `.env` file from your **project root** directory, not from the folder where your `js` file exists. If you need to, you may change the location of the `.env` file to load in your configuration. From the [dotenv-quokka-plugin readme.md](https://github.com/wallabyjs/dotenv-quokka-plugin):

> If you need to, you may change the `.env` file to load:
> 
> ```
> {
>     "plugins": ["dotenv-quokka-plugin"],
>     "dotenv": {
>         "path": ".env.test"
>     }
> }
> ```
> 
> Note: if the `dotenv.path` is a relative path, it will be located relative to your project directory.
