### ISSUE TITLE
Unable to use Quokka in Visual Studio Code

### ISSUE THREAD

**Issue by ddanielbee** [wallabyjs/quokka#57]
### Issue description or question

After installing Quokka on Visual Studio Code and restarting the IDE, no command is accesible. Every command throws an error of this kind: 

`command 'quokka.createJavaScriptFile' not found`

No configuration was made, just installation from the marketplace inside the IDE. 

### Code editor version

Visual Studio Code v1.12.2

### OS name and version

OSX 10.12.4

**Comment by ArtemGovorov** [comment]
Try re-installing the extension. If it doesn't help, please share the output from the Dev Tools Console (menu `Help - Toggle Developer Tools`).

**Comment by vacatrin** [comment]
Hi there,

I had the same issue with my Visual Studio Code v1.12.2 on OSX 10.12.4, and had it resolved after re-installing the extension. Thank you very much!

**Comment by ddanielbee** [comment]
Re Installing worked. Thanks !

**Comment by atif089** [comment]
I have this same error on VSCode (Windows 10) for several months. Reinstalling the extension works but only up until I restart VS Code and then it stops working again. Any guidance on how I can get a stack trace for better debugging?

**Comment by ArtemGovorov** [comment]
@atif089 Please share the output from the Dev Tools Console (menu `Help - Toggle Developer Tools`).

**Comment by atif089** [comment]
@ArtemGovorov I shared it here. Thanks

https://github.com/wallabyjs/quokka/issues/289#issuecomment-735247209

**Comment by ArtemGovorov** [comment]
@atif089 Thanks. It looks like there may be a conflict with some other installed extension. Try this:
- temporarily disable all installed extensions but Quokka,
- uninstall Quokka, 
- close your editor, 
- delete all `c:\Users\123\.vscode\extensions\wallabyjs.quokka-vscode-VVV` folders, 
- open your editor, 
- install Quokka, 
- verify that it works without any issues.

After that try re-enabling your other extensions one by one until you find the conflicting extension and let us about it.

**Comment by mt-webdev** [comment]
It's "Live share" which is causing the "conflicts". Please fix htis issue :( this seems to be an issue since quite some time and basically mean we are unable to use quokka at all.

**Comment by smcenlly** [comment]
@mt-webdev - would you mind creating a new issue and providing us with full details of your problem? Could you also please share the output from the Dev Tools Console (menu `Help - Toggle Developer Tools`).

**Comment by uzzT** [comment]
@smcenlly 
Same issue, Quokka plugin doesn't work in vscode when live share plugin enabled
![image](https://user-images.githubusercontent.com/34025908/148176764-e1b461c8-8c0e-4d63-afb3-aa7609a7ae23.png)

It works when live share plugin disabled
![image](https://user-images.githubusercontent.com/34025908/148177550-3470c0cb-e4ee-47e1-86ca-92834abb5767.png)

**Comment by smcenlly** [comment]
Please see: https://github.com/wallabyjs/quokka/issues/734#issuecomment-1001845462

> We were able to reproduce the problem outside of Quokka and have reported it to the VS Code LiveShare team: https://github.com/MicrosoftDocs/live-share/issues/4551

**Comment by smcenlly** [comment]
As of this morning, we have tested the latest version of VS Code (stable) and VS Code Insiders, and everything appears to be working.

If you're still having the problem, can you please ensure that you have the latest VS Code version. If you are having a problem with the latest VS Code version, please provide your VS Code version/operating system details below.

**Comment by smcenlly** [comment]
Our problem with Live Share was caused by a promise that failed to resolve/reject. We have updated our integration with Live Share to be tolerant of this.

Please try updating to the latest version of Quokka for VS Code, `v1.0.436`. We believe this will resolve the problem.

**Comment by Kibetkipsang** [comment]
024-11-26 08:25:12.554 [error] EACCES: permission denied, rename '/home/kibetkipsang/.vscode-server/extensions/.6afd2330-44af-4d60-bd6e-f7cb6471b447' -> '/home/kibetkipsang/.vscode-server/extensions/wallabyjs.quokka-vscode-1.0.668': Error: EACCES: permission denied, rename '/home/kibetkipsang/.vscode-server/extensions/.6afd2330-44af-4d60-bd6e-f7cb6471b447' -> '/home/kibetkipsang/.vscode-server/extensions/wallabyjs.quokka-vscode-1.0.668'
    at async Object.rename (node:internal/fs/promises:782:10)
    at async Object.tN (file:///home/kibetkipsang/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/server-main.js:45:5275)
    at async ph.G (file:///home/kibetkipsang/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/server-main.js:51:25104)
    at async ph.extractUserExtension (file:///home/kibetkipsang/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/server-main.js:51:22143)
    at async Oc.rb (file:///home/kibetkipsang/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/server-main.js:51:15376)
