### ISSUE TITLE
Publish extension to Open VSX registry

### ISSUE THREAD

**Issue by vymarkov** [wallabyjs/quokka#574]
Hi!

I actively use GitPod as my primary IDE, and I wanna see [Quokka extension ](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) in the [Open VSX registry](https://open-vsx.org) to use with tools like Gitpod, VS Codium, Code Server, etc that can't use official Visual Studio Marketplace due to legal restrictions. I hope to see in the  opevscx this extension very soon!

Thanks!

**Comment by ArtemGovorov** [comment]
Hello,

Unfortunately it's not possible for us to publish the extension in Open VSX for the reason explained here https://github.com/wallabyjs/public/issues/2436#issuecomment-741415194.
