### ISSUE TITLE
Quokka not working

### ISSUE THREAD

**Issue by raulbethencourt** [wallabyjs/quokka#576]
### Issue description or question
I'm trying to use Quokka in my VSC and it's stop working. I've tried in diferents files and it dosent work.
### Quokka.js Console Output

I dont have quokka.js Output. I have vsc developer tool output

```
 Looking for parseable documents...
console.ts:137 [Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
console.ts:137 [Extension Host] Found all parseable documents.
console.ts:137 [Extension Host] Parsing documents and looking for CSS class definitions...
console.ts:137 [Extension Host] Summary:
console.ts:137 [Extension Host]% 91 parseable documents found
console.ts:137 [Extension Host]% 43101 CSS class definitions found
console.ts:137 [Extension Host]% 1902 unique CSS class definitions found
console.ts:137 [Extension Host]% 0 failed attempts to parse. List of the documents:
console.ts:137 [Extension Host] 
```

### Code editor version

Visual Studio Code v1.

### OS name and version

Linux

**Comment by smcenlly** [comment]
Can you please do the following:

1. Create a new folder (e.g. `/{someTempDirectory}/quokka-576`)
2. Open VS Code in the new folder.
3. Run the VS Code command, `Extensions: Disable All Installed Extensions for this Workspace`.
4. Run the VS Code command, `Extensions: Show Installed Extensions` and find `Quokka` in the list, select it and click the `Enable (Workspace)` button in the top section of the extension details.
5. Reload your VS Code instance using the command `Developer: Reload Window`
6. Run the command `Quokka.js: New File` at which point you will be provided with a list of options, select `JavaScript: Array.concat()`. You should now see something similar to the screenshot below:

![image](https://user-images.githubusercontent.com/2074089/104967296-c2e95880-5a2e-11eb-8937-d8182cbdb167.png)

7. If you do not see the output window, try using the VS Code command `View: Toggle Output` and then `Quokka.js: Show Output`.

If it is still not working for you:
* Do you have any errors displaying in the Quokka output window? If so, please copy/paste the output in your response. 
* Could you also confirm whether you are getting any line markers (green indicators beside your code)?
* Please check the VS Code developer tool output again as there may be more information provided
* Please confirm that you have a valid `node.js` version that will run from the VS Code terminal when you use `node --version`

If Quokka is working in the new folder but not with all extensions enabled, then it is likely another extension is crashing and not reporting its problem, which then causes Quokka to not load properly. You can try enabling your extensions one by one to isolate which extension is not working for you.

**Comment by smcenlly** [comment]
I've updated the title as the console message, `Quokka.js Live Share integration disabled` does not indicate a problem. This message is expected when you do not have the Microsoft Live Share extension install in VS Code.

**Comment by raulbethencourt** [comment]
Hi.
Thanks a lot for your help.
The problem was that I was using old version of node.js that I've installed
for old project and I've changed for latest lts version of node;js and it
works now.
thanks again

Le lun. 18 janv. 2021 à 23:23, Simon McEnlly <notifications@github.com> a
écrit :
