### ISSUE TITLE
console.info does not display multiple arguments

### ISSUE THREAD

**Issue by drtyh2o** [wallabyjs/quokka#577]
### Issue description or question
The output of `console.info` only contains the first argument. `console.log`, `console.warn`, and `console.error` work as expected.

### Sample code

```javascript
console.error('ERROR', 'this is an error')
console.warn('WARN', 'this is a warning')
console.info('INFO', 'this is not diplayed')
console.log('LOG', 'this is a log')
```

### Quokka.js Console Output

```
​​​​​Quokka 'quokka.ts' (node: v14.2.0, TypeScript: v4.1.3)​​​​
 
ERROR this is an error 
​​​​​​
​​​WARN this is a warning​​​

'INFO' ​​​​​

LOG this is a log ​​​​​at ​quokka.ts:4:0​
```

### Code editor version

Visual Studio Code v1.52.1

### OS name and version

OSX 11.1

**Comment by smcenlly** [comment]
Thanks for reporting the problem.

Previously Quokka was incorrectly logging `console.info` the same way as `console.debug` or `console.dir`. Quokka now logs `console.info` correctly (the same as `console.error`, `console.warn`, and `console.log`).

Please update to the latest version of Quokka for VS Code (v1.0.337) to get updated version that addresses this issue.
