### ISSUE TITLE
Quokka doesn't re-evaluate after the last change reliably

### ISSUE THREAD

**Issue by dbb613** [wallabyjs/quokka#578]
### Issue description or question

I've seen several cases of this after starting to work with Quokka for a few weeks now.   

It appears that Quokka sometimes doesn't re-evaluate the latest code that I've typed leading to errors that don't reflect the current state of my code even within the same file.

Sometimes it is obvious where the error is because it is clear that it evaluated while I was typing and other times the issue is more obscure and the error doesn't directly point to anything in particular.

Examples:

In each case you can clearly see that the current code doesn't have the issue that Quokka is complaining about.

![Screen Shot 2021-01-26 at 1 32 48 PM](https://user-images.githubusercontent.com/390696/105888483-03bb1180-5fdb-11eb-8b3c-a5677fce782d.png)

![Screen Shot 2021-01-26 at 1 36 22 PM](https://user-images.githubusercontent.com/390696/105888853-83e17700-5fdb-11eb-9021-535ef402b99f.png)

![Screen Shot 2021-01-26 at 1 43 47 PM](https://user-images.githubusercontent.com/390696/105889908-b049c300-5fdc-11eb-9e66-bacf749544d6.png)

then, if I make another change to "force" it to re-evaluate it appears to do the right thing.

Steps to reproduce:

* It is inconsistent so I can't force the problem to happen on-demand, but it crops up often enough that it impairs productivity.

### Sample code

```javascript
while (typeof nextResults.next === 'function') {
```

### Quokka.js Console Output

Cannot read property '1' of undefined

### Code editor version

Visual Studio Code November 2020 (version 1.52)

### OS name and version

OSX
![Screen Shot 2021-01-26 at 1 46 47 PM](https://user-images.githubusercontent.com/390696/105890202-0b7bb580-5fdd-11eb-919d-47a8d6be086e.png)

**Comment by smcenlly** [comment]
Unfortunately we weren't able to reproduce the problem. Would you be able to provide us with a full code-sample that exhibits the problem so we can see what might be causing the issue?

**Comment by smcenlly** [comment]
I'm going to close this issue as we do not have sample code we can use to try and reproduce this issue. If we receive a sample, we will reopen this issue.
