### ISSUE TITLE
quokka not starting

### ISSUE THREAD

**Issue by Deepali2** [wallabyjs/quokka#583]
### Issue description or question
Quokka is not starting.
Receiving this error:
<img width="1680" alt="Screen Shot 2021-02-13 at 12 01 28 AM" src="https://user-images.githubusercontent.com/32617384/107845242-f352b700-6d8e-11eb-9717-1b7f97a2a4fe.png">

### Sample code

```javascript
// paste the code you are running here
console.log('hello');
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version
Visual studio code v1.53.2

### OS name and version
MacOS Big Sur Version 11.1

email: deepaligarg1001@gmail.com

**Comment by ArtemGovorov** [comment]
It looks like your Quokka installation got somehow corrupted (https://github.com/wallabyjs/quokka/issues/572), re-installing the extension should help.

**Comment by Deepali2** [comment]
Hello Artam 
I have already tried reinstalling quokka several times.
It does not work.
I have given up I’m quokka unless you have a solution to fix it.
Thanks,
Deepali

**Comment by ArtemGovorov** [comment]
@Deepali2 Can you please archive the follow file `/Users/deepaligarg/.vscode/extensions/wallabyjs.quokka-vscode-1.0.342/dist/wallaby/server.js` and send it to hello@wallabyjs.com?
