### ISSUE TITLE
`allowSyntheticDefaultImports` not working

### ISSUE THREAD

**Issue by nemosmithasf** [wallabyjs/quokka#584]
The `allowSyntheticDefaultImports` option does not seem to work in my file. I'm relatively unfamiliar with toolchains, so maybe there's something I'm missing.

I am able to import the file fine outside of quokka (`allowSyntheticDefaultImports` is set in my `tsconfig`); and if I use `import * as dataForge from...` it also works fine.

I'm using last November's version of Quokka if that's relevant.

```
({
  ts: {
    compilerOptions: {
      allowSyntheticDefaultImports: true,
    },
  },
});

import dataForge from "data-forge";
require("data-forge-fs");

console.log(dataForge); // Undefined
```

**Comment by smcenlly** [comment]
We get the same behavior (undefined variable) when running code using `ts-node` or compiling with `tsc -p .` and running the transpiled javascript code in `node`.

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

Can you please provide us with a sample repo where this works outside of Quokka but not inside Quokka?

**Comment by smcenlly** [comment]
I don't think that this is a problem with Quokka so I am going to close this issue. If you can provide us with a reproduceable sample, I can re-open if necessary and we'll take a look at what's going on in your project/environment for you.

**Comment by nemosmithasf** [comment]
Hey, sorry for the delay.

Here's the repo that should replicate the issue: https://we.tl/t-uR3XIHNMGG.

As you can see, when used without Quokka, we're able to see the methods of the `dataForge` object. Within quokka, dataForge becomes `undefined`. This is fixed if we use `import * as...`

**Comment by smcenlly** [comment]
Thanks for the sample repo. I can see that your project is not actually using TypeScript to transpile your files, it is instead using rollup. Unfortunately Quokka doesn't support using rollup to transpile your files, only TypeScript and Babel are supported at this point in time.

When rollup is transpiling your code, it uses TypeScript compiler but does a bunch of work on top of this. Specifically, the rollup typescript plugin [overrides the import helpers with it's own](https://github.com/rollup/rollup/blob/05d578a1c1baca0e860ad71db6a5690a5ea82e82/src/utils/interopHelpers.ts#L86). This changes your TypeScript transpiled code from something like:

**Native TypeScript (i.e. TypeScript to JavaScript)**
```javascript
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
const data_forge_1 = __importDefault(require("data-forge"));
require("data-forge-fs");
console.log(data_forge_1.default); // Undefined
```

to

**Rollup: (i.e. Rollup with TypeScript to JavaScript)**
```javascript
'use strict';
var dataForge = require('data-forge');
function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
var dataForge__default = /*#__PURE__*/_interopDefaultLegacy(dataForge);
require("data-forge-fs");
console.log(dataForge__default['default']);
```

As I understand it, this behavior is specific to Rollup (although could also be configured using Babel) and is to allow compatibility between legacy modules that do not comply with the ES6 specification. Unfortunately TypeScript does not support what you are trying to do without changing your syntax to `import * as dataForge from 'data-forge'`) (and so neither does Quokka).
