### ISSUE TITLE
Quokka does not work correctly for the javascript array sort method

### ISSUE THREAD

**Issue by ylcnfrht** [wallabyjs/quokka#586]
Quokka does not work correctly for the javascript array sort method

### Sample code

```javascript
const arr = [4,6,5,2,1,3]

console.log(arr.sort((a,b) => a>b));
```

![Screen Shot 2021-03-06 at 01 52 48](https://user-images.githubusercontent.com/22433665/110182853-ac506280-7e1e-11eb-885b-6fc2c745a510.png)

response 
[ 4, 6, 5, 2, 1, 3 ]

actually response
[ 1, 2, 3, 4, 5, 6 ]

Visual Studio Code

### OS name and version
OSX

**Comment by smcenlly** [comment]
This is not a problem in quokka, it's a bug in your code. You'll get the same behavior outside of Quokka. You can see this using browser console or running directly in node.js.

Your code should be:

```
console.log(arr.sort((a,b) => a - b));
```
