### ISSUE TITLE
Quokka does not work correctly for the javascript array sort method

### ISSUE THREAD

**Issue by ylcnfrht** [wallabyjs/quokka#587]
Quokka does not work correctly for the javascript array sort method

Sample code
const arr = [4,6,5,2,1,3]

console.log(arr.sort((a,b) => a>b));

![](https://user-images.githubusercontent.com/22433665/110182853-ac506280-7e1e-11eb-885b-6fc2c745a510.png)

response
[ 4, 6, 5, 2, 1, 3 ]

actually response
[ 1, 2, 3, 4, 5, 6 ]

By the way, I got the same wrong answer from the chrome console but at node.js my code run correctly

**chrome console**
![Screen Shot 2021-03-06 at 02 11 31](https://user-images.githubusercontent.com/22433665/110184127-56c98500-7e21-11eb-862b-3fd5d1cb2d11.png)

**node.js repl**
![Screen Shot 2021-03-06 at 02 09 04](https://user-images.githubusercontent.com/22433665/110183897-f1759400-7e20-11eb-8284-bb432e7de716.png)

Visual Studio Code

OS name and version
OSX

**Comment by smcenlly** [comment]
Under the covers, Quokka is using your local version of node.js, so you may reproduce the same behavior with:

**test.js**
```javascript
const arr = [4,6,5,2,1,3]

console.log(arr.sort((a,b) => a>b));
```

```
❯ node .\test.js
[ 4, 6, 5, 2, 1, 3 ]
```

> at node.js my code run correctly

We get the same behavior as in Quokka using our local version of node.

```
> var arr = [4,6,5,2,1,3]
undefined
>
> console.log(arr.sort((a,b) => a>b));
[ 4, 6, 5, 2, 1, 3 ]
undefined
>
```

Any differences you're seeing are related to your node.js version's internal sort implementation Regardless, your code is incorrect, please refer to the [docs for array.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). You are returning a boolean value, where the result should be an number:

> ```javascript
> function compare(a, b) {
>   if (a is less than b by some ordering criterion) {
>     return -1;
>   }
>   if (a is greater than b by the ordering criterion) {
>     return 1;
>   }
>   // a must be equal to b
>   return 0;
> }
> ```
