### ISSUE TITLE
Output type of object

### ISSUE THREAD

**Issue by hmoritz** [wallabyjs/quokka#59]
### Feature Request - Output type of object

```javascript
function Box(x) {
  this._value = x
}

const b = new Box(5)
b // { _value: 5 }
```
In Chrome's console you'd get `Box {_value: 5}` which can be quite useful.

Would it be possible to change this behavior with a plugin?

### Code editor version

Visual Studio Code v1.13.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for the feature request. Added in the latest version VS Code extension 1.0.36.

**Comment by hmoritz** [comment]
Thank you for implementing this feature.
