### ISSUE TITLE
Quokka new install not working

### ISSUE THREAD

**Issue by Darkmift** [wallabyjs/quokka#590]
Hi,
I installed your plugin in my vscode and cannot get it to show anything unfortunately.
### Sample code

```javascript
const answerToAllthings = 42 //no output
answerToAllthings //no output
console.log(answerToAllthings)  //no output
```

### Code editor version

Visual Studio Code v1.54.1

### OS name and version

Windows 10 Version 2004 (OS Build 19041.804)

I tried the following here but no luck:
https://github.com/wallabyjs/quokka/issues/576

I'd appreciate your assistance on this matter <3

**Comment by ArtemGovorov** [comment]
- what command are you using to start Quokka on the file?
- what is the output in your Quokka output channel?
- is there any error output in your VS Code dev tools console (`Toggle Developer Tools` command)?

**Comment by Darkmift** [comment]
Hi,

Thanks for the prompt reply,

the console shows this:

`[Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
`

**Comment by ArtemGovorov** [comment]
Can you please respond to the other 2 questions at https://github.com/wallabyjs/quokka/issues/590#issuecomment-794989246 as well?

**Comment by Darkmift** [comment]
Sure thing,
I ran no command...as far as I understand the plugin works just by installing however I now see there's a command set for it to run and the output shows in terminal.

Do I need to manually initialize for every file I work with?

**Comment by ArtemGovorov** [comment]
> Do I need to manually initialize for every file I work with?

Yes, you need to start Quokka on file(s) that you would like to run (because running ALL of your opened code automatically is potentially not something that you may want). [This tutorial](https://quokkajs.com/docs/#getting-started) should be a good start to better understand how the tool works and get the best out of it.
