### ISSUE TITLE
Errors when starting Quokka

### ISSUE THREAD

**Issue by habsfanongit** [wallabyjs/quokka#591]
QuokkaJS doesn't work even in a new installation on MacOS Big Sur.
Toggling the developer's tool, yield the same error (shown in the attached screen capture)
Because this is a fresh install of VsCode, Quokkajs is the only installed plug I have

### Sample code

```javascript
console.log("hello");
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
No output. The plugin just crashes after using Command K Q
```

### Code editor version
Visual Studio code
Visual Studio Code v1.?
Version: 1.54.1 (Universal)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

### OS name and version

MAC OS Big Sur 11.2.3 (20D91)

![Screen Shot 2021-03-10 at 3 01 53 PM](https://user-images.githubusercontent.com/21362322/110690971-8d512800-81b2-11eb-829e-c287eb961e94.png)

**Comment by smcenlly** [comment]
Quokka requires [node.js](https://nodejs.org/en/) to be installed for your system. Can you please confirm it is installed by starting your terminal and running:

```
node --version
```

**Comment by habsfanongit** [comment]
I do have node version v15.11.0 and the Typescript version is 4.2.3

**Comment by smcenlly** [comment]
Could you please try:

1. Uninstall and re-install the Quokka extension
2. Ensure that a `.quokka` folder exists in your home directory (i.e. `~/.quokka`); perhaps there was a permission issue that prevented Quokka from creating this directory.
3. Provide a direct path to your node executable in your global Quokka `config.json` file ([see here for details](https://quokkajs.com/docs/configuration.html#nodejs-version)).

**Comment by habsfanongit** [comment]
I didn't uninstall it but I did set the node path in `~/.quokka/config.json` to `/usr/local/bin/node` and it worked. I am curious as to why I had to setup node manual when my PATH includes the same?

` export PATH=$HOME/bin:/usr/local/bin:$PATH `

**Comment by smcenlly** [comment]
It depends how you are setting the path. If you are setting the path in `.bashrc`, etc. then the path is not set when you launch VS Code from the finder.

This may help: https://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications

**Comment by habsfanongit** [comment]
Thank you for your help, Simon.
