### ISSUE TITLE
Electron support?

### ISSUE THREAD

**Issue by rjousse18** [wallabyjs/quokka#592]
Is there a way for quokka works with Electron project ?

When I have
 `app.on('ready', createWindow);`

Quokka say 
`Cannot read property 'on' of undefined`

Why ? My imports are correct.

**Comment by ArtemGovorov** [comment]
Quokka [runs in node.js](https://quokkajs.com/docs/index.html#runtime). Electron runtime is currently not supported and there's not close future plans to add the support.
