### ISSUE TITLE
"Cannot find Module" in VSCode / Typescript for NPM Modules

### ISSUE THREAD

**Issue by yngwi** [wallabyjs/quokka#594]
### Issue description or question

I'm new to Quokka. I want to use npm packages in standalone Quokka files (not part of a project) in Typescript. While the packages seem to be downloaded (the global `.quokka/data/` contains a new folder with a package.json and a node_modules folder with the correct package), they don't seem to be available for the code. The same code works fine inside a JavaScript file. Generally, code also runs fine in Typescript if no imports are used. I have done no custom configurations except enter the "pro" key as the documentation claims that `most times if you are using TypeScript, no configuration is required.`

### Sample code

```typescript
import * as vf from "vector-fun";

const foo = vf.vector2(1, 2)

console.log(foo)
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-2.ts' (node: v15.11.0, TypeScript: v4.2.3)​​​​ ​View recent Quokka files​

​Install "vector-fun" package for the current quokka file​
 
Cannot find module 'vector-fun' 
Require stack: 
- .\quokka.js 
  at ​​​Object.<anonymous>​​​ ​quokka.ts:1
```

### Code editor version

Visual Studio Code v1.54.2

### OS name and version

Windows 10 (not in WSL2)

**Comment by smcenlly** [comment]
After you start a new Quokka file, you will need to install the package each time. This is the same for JavaScript files. If you click on the link to:

```
​Install "vector-fun" package for the current quokka file​
```

or else run the command `Quokka.js: Install Missing Package only for Quokka File` it should work for you.

**Comment by ArtemGovorov** [comment]
If you would like to only install the package once, you may install into the `./quokka` folder, and it'll be available automatically for you new Quokka files, but you'll need to manage the dependency yourself (ie. update/remove when required).

**Comment by yngwi** [comment]
> After you start a new Quokka file, you will need to install the package each time. This is the same for JavaScript files. If you click on the link to:
> 
> ```
> ​Install "vector-fun" package for the current quokka file​
> ```
> 
> or else run the command `Quokka.js: Install Missing Package only for Quokka File` it should work for you.

@smcenlly Yes I am aware of this. The console.log above is *after* I give this command. I'm sorry that I didn't mention this. Also now (didn't see this yesterday) I get a notification "No missing packages to install" after "installing" the package. As I mentioned in my issue, the package does seem to get installed correctly as it is located in the .quokka/data folder afterwards but just not used. Maybe it's a problem with Windows paths?

**Comment by ArtemGovorov** [comment]
It looks like some combo of node caching and something special about this specific module. If you try a similar code but importing a different module, say `left-pad`, then it's working. We'll further investigate the issue, but the workaround for now is to turn off process reuse by [adding this setting to your Quokka settings file](https://quokkajs.com/docs/configuration.html#node-process-reuse):

```
{
  ...
  "recycle": true
}
```

**Comment by yngwi** [comment]
@ArtemGovorov Thank you! The workaround works, and `left-pad` as well. I'll have to say, the other library is made by me some time ago so there sure might be something wrong with it and possibly I'm to blame for it. It works fine on its own (I made it mostly for personal use) but it might well be that I did something wrong when creating the package. I would be glad if you could give me any pointers as to what is causing the problem in Quokka. If you wish, feel free to close the issue.

Best,
Daniel

**Comment by smcenlly** [comment]
@yngwi - we're not sure what was causing the problem and had not seen it before. You may be able to compare your package to others to determine what possible differences are causing the problem. We will close this issue.

**Comment by yngwi** [comment]
Thank you. Great product and support!
