### ISSUE TITLE
Conflict with GitLens on vscode

### ISSUE THREAD

**Issue by smitroshin** [wallabyjs/quokka#595]
### Issue description or question
The extension breaks [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) extension.

Normal way: When you press on the GitLens icon from the actions bar, should open dropdown with some options.

Bug: Dropdown instant appear and disappear.

![image](https://user-images.githubusercontent.com/20210690/111225373-68ace400-85e8-11eb-8568-96c0849b8c11.png)
![image](https://user-images.githubusercontent.com/20210690/111226521-ede4c880-85e9-11eb-9f98-6171248e997e.png)

Your extension somehow breaks the GitLens icon with dropdown, because after I disabled it, dropdown working perfectly.

### Quokka version

v1.0.349

### GitLens version

v11.3.0

### Code editor version

Visual Studio Code v.1.54.2

### OS name and version

Windows_NT x64 10.0.19041

**Comment by smcenlly** [comment]
This appears to be a problem in VS Code and is being tracked in the VS Code repository (see here https://github.com/microsoft/vscode/issues/118413). I'll close this issue in our repo. You may subscribe to the VS Code repository for updates.

I have also just asked if there is an update on this issue.
