### ISSUE TITLE
cannot start node.js process, something regarding its location..can anybody help me?

### ISSUE THREAD

**Issue by kotharii** [wallabyjs/quokka#598]
### Issue description or question
![image](https://user-images.githubusercontent.com/78986375/111776655-49f46900-88d8-11eb-9e55-f035ad281ace.png)

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
Do you have [node.js](https://nodejs.org/en/) install on your system? If not, please install it as it is a requirement for using Quokka.

If you do have node.js installed then perhaps the path is not set correctly when using VS Code. You can set the full path to `node` by setting the value in your Quokka global configuration file. The global configuration file is located in your home directory at `~/.quokka/config.json`. Setting the node version is described in [our docs](https://quokkajs.com/docs/configuration.html#nodejs-version).

> By default Quokka runs the node command to run your code. If you would like to use a custom node.js version (for example if you are using nvm), you may specify the path to the node executable in your global Quokka config.json file, for example:
> 
> ```
> {
>     "node": "~/.nvm/current/bin/node"
> }
> ```
> or
> 
> ```
> {
>     "node": "/Users/username/.nvm/versions/node/v7.7.1/bin/node"
> }
> ```

**Comment by rluvaton** [comment]
`nvm` doesn't have the current folder

**Comment by smcenlly** [comment]
> nvm doesn't have the current folder

You should be able to determine your node location using `which node`

**Comment by rluvaton** [comment]
it points to a specific version, in some projects at my company we use 14 and in others we use 16
```console
$ which node
/Users/<ny-username>/.nvm/versions/node/v14.19.3/bin/node

**Comment by smcenlly** [comment]
> it points to a specific version, in some projects at my company we use 14 and in others we use 16

In most cases, the node version does not need to be configured for Quokka. For example, on my computer, VS Code picks up the default version of nvm/node that is running when VS Code is launched. Are you using `nvm alias default 14` or `nvm alias default 16` as you switch between projects? This should configure `node` so that it is found by Quokka (and other applications). If you can't get that working then you may have to update node versions as you switch between projects.
