### ISSUE TITLE
var scope get wrong

### ISSUE THREAD

**Issue by dilannery** [wallabyjs/quokka#6]
### Issue description or question
When I create a variable inside a function using `var` keyword the variable should be scoped with the function, but the Quokka.js Console Output is return as if the variable i was defined in the global scope.

### Quokka.js file

```javascript
'use strict'

function iEqualTo() {
    var i = 10;
    console.log(i);
}

console.log(i);
```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v6.10.0)​​​​

​​​​​10​​​​​ at ​​​i​​​ ​quokka.js:8:0​
```

### Code editor version

Visual Studio Code v1.10.2

### OS name and version

MacOS Sierra

**Comment by ArtemGovorov** [comment]
If you restart the quokka, or create a new one and paste the code into it, does it start working as expected?

**Comment by dilannery** [comment]
Yes

**Comment by ArtemGovorov** [comment]
It's a caching issue then. Quokka tries to re-use node processes, you must have set the global `i` variable when writing the code, so that's why it is defined for you.
