### ISSUE TITLE
Cannot create new quokka file in Webstorm

### ISSUE THREAD

**Issue by MattSidor** [wallabyjs/quokka#60]
### Issue description or question

Unable to create a new quokka file. When I try to create a new file, "quokka" is not in my list of options, despite the fact that the plugin appears to have been installed correctly and is updated to the latest version.

### Code editor version

Webstorm v2017.1.4

### OS name and version

OSX (macOS) Sierra 10.12.5

![screen shot 2017-06-26 at 2 18 46 pm](https://user-images.githubusercontent.com/6138182/27558533-ad374e6e-5a7a-11e7-8702-7bc6c3fd1e75.png)
![screen shot 2017-06-26 at 2 19 14 pm](https://user-images.githubusercontent.com/6138182/27558537-b42652f6-5a7a-11e7-99c5-87c6216b1d7e.png)

**Comment by ArtemGovorov** [comment]
There's no special Quokka file file in the list. JavaScript, ES6, or TypeScript file types can be selected to start Quokka. Will clarify it in the docs.

**Comment by ArtemGovorov** [comment]
For example:
<img width="183" alt="screen shot 2017-06-27 at 8 46 53 am" src="https://user-images.githubusercontent.com/979966/27563482-4209b1e0-5b15-11e7-85e1-52faf82bbb05.png">

(any JavaScript file type will do).

**Comment by MattSidor** [comment]
Ah, understood! Thank you!
