### ISSUE TITLE
Doesn't see Nodejs in phpstorm

### ISSUE THREAD

**Issue by doox911Finex** [wallabyjs/quokka#601]
### Issue description or question
Quokka does not start. Rebooted the IDE.

![quokka](https://user-images.githubusercontent.com/74534192/112039233-e165f000-8b54-11eb-9eca-eafd74f93598.png)

`.quokka:`
```
{
  "node": "~/.nvm/versions/node/v14.15.0/lib/bin/node"
}
``` 

### Quokka.js Console Output

```
21:18	Quokka
Can not start node.js process (node).
You may use the "node" setting to configure the location of node.
```

### Code editor version

PhpStorm 2020.3.3.

### OS name and version

Linux

**Comment by smcenlly** [comment]
Can you please confirm that running this **exact** command from the terminal works for you?

```shell
~/.nvm/versions/node/v14.15.0/lib/bin/node --version
```

Please note that the path in your Quokka file and the path in your PhpStorm settings are different, you have an extra `lib` directory in your Quokka file. I believe that you have provided an invalid path in your Quokka file settings and it should be corrected to:

**quokka.js**
```json
{
  "node": "~/.nvm/versions/node/v14.15.0/bin/node"
}
```

**Comment by doox911Finex** [comment]
> Can you please confirm that running this **exact** command from the terminal works for you?
> 
> ```shell
> ~/.nvm/versions/node/v14.15.0/lib/bin/node --version
> ```
> 
> Please note that the path in your Quokka file and the path in your PhpStorm settings are different, you have an extra `lib` directory in your Quokka file. I believe that you have provided an invalid path in your Quokka file settings and it should be corrected to:
> 
> **quokka.js**
> 
> ```json
> {
>   "node": "~/.nvm/versions/node/v14.15.0/bin/node"
> }
> ```

![q1](https://user-images.githubusercontent.com/74534192/112114695-6854b000-8bc9-11eb-99ef-20153443ed94.png)

`.quokka`:
```
{
  "node": "~/.nvm/versions/node/v14.15.0/lib/bin/node"
}
```

**Comment by smcenlly** [comment]
Your Quokka configuration is pointing to the wrong directory (it has an extra `lib` in it).

**Comment by finexfloors** [comment]
> Ваша конфигурация Quokka указывает не на тот каталог (в нем есть дополнительный `lib`).

This is very annoying. What else is needed?

![2021-04-22_10-30](https://user-images.githubusercontent.com/74534192/115674042-ee455180-a355-11eb-89c1-71cfd31bdd84.png)

**Comment by ArtemGovorov** [comment]
@finexfloors Please delete your `.quokka` file and specify the same `node` setting in your global Quokka config file. As [described in the docs](https://quokkajs.com/docs/configuration.html#nodejs-version), the `node` setting can only be specified in the global config:

**~/.quokka/config.json**

```
{
  ...
  "node": "~/.nvm/versions/node/v14.15.0/bin/node"
}
```

**Comment by finexfloors** [comment]
> @finexfloors Удалите `.quokka`файл и укажите те же `node`настройки в глобальном файле конфигурации Quokka. Как [описано в документации](https://quokkajs.com/docs/configuration.html#nodejs-version) , `node`параметр можно указать только в глобальной конфигурации:
> 
> **~ / .quokka / config.json**
> 
> ```
> {
>   ...
>   "node": "~/.nvm/versions/node/v14.15.0/bin/node"
> }
> ```

Thank you so much!
