### ISSUE TITLE
Value explorer not encoding japanese chars properly

### ISSUE THREAD

**Issue by fergusmeiklejohn** [wallabyjs/quokka#602]
Japanese characters in the value explorer render properly but if I copy them they become scrambled. Console logging the output and copying from the `OUTPUT` retains the correct char encoding

This:
```
{ id: 'hWhOQaKEV3u6TZNbhhvEhmmhArDf', 
  nameStage: '木村', 
  nameStageKana: 'カナ 木村' } 
```

Becomes this, when copied from the VALUE EXPLORER:
```
{
  id: 'hWhOQaKEV3u6TZNbhhvEhmmhArDf',
  nameStage: 'Êú®Êùë',
  nameStageKana: '„Ç´„Éä Êú®Êùë'
}
```

### Code editor version

Visual Studio Code v1.54.3

### OS name and version

OSX v10.15.7

**Comment by smcenlly** [comment]
This seems to be working for us on both Windows and MacOS (see screenshot attached).

![cp](https://user-images.githubusercontent.com/2074089/112097243-5e43a900-8beb-11eb-9e84-57c54444f09b.gif)

Could you please provide the precise steps that you are taking as well as your node.js version?

**Comment by fergusmeiklejohn** [comment]
Thanks Simon.

Node 14.16.0
Faker 5.4.0

It's a strange intermittent bug: 

https://user-images.githubusercontent.com/11864025/112247508-62290700-8c8f-11eb-836c-107fa11c27b5.mov

**Comment by smcenlly** [comment]
Unfortunately we cannot reproduce your problem. We've tried on both Windows and MacOS with the exact same package version + node version.

It looks like maybe there was some intermittent issue before your error. Are you able to reproduce reliably from a fresh Quokka start? If so, would you be able to show us or provide steps to reproduce from a fresh Quokka start?

**Comment by fergusmeiklejohn** [comment]
Thanks for looking into it. I reinstalled Quokka in VSCode and it seems to work :-) 

rm -rf for the win 🥳
