### ISSUE TITLE
Can not start quokka in current file in webstorm 

### ISSUE THREAD

**Issue by nichitapasecinic** [wallabyjs/quokka#603]
### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Code editor version
Webstorm last

![image](https://user-images.githubusercontent.com/77678851/112194453-89d98a00-8c11-11eb-98c2-1eafe4bed443.png)

Windows 10 pro

**Comment by smcenlly** [comment]
To start Quokka on a current file, you need to use the context menu action, `Start Quokka (Run Automatically)`. Please note that this is available on JavaScript (`*.js`) and TypeScript files (`*.ts`) but Quokka does not currently support `Flow JS` files (`*.flow`).

![quokka-intellij-start](https://user-images.githubusercontent.com/2074089/112223135-3862e680-8c75-11eb-8f36-f3eb1820fcc9.gif)
