### ISSUE TITLE
Quokka running like an endless loop in between

### ISSUE THREAD

**Issue by abisalde** [wallabyjs/quokka#605]
### Issue description or question
I tried using the quokka extension on my VS Code IDE, but quokka keeps loading and doesn't display any output after doing console.log.

I try to fix it through this with the link <a href="https://github.com/wallabyjs/quokka/issues/289">Can't run any Quokka.js commands</a>, but quokka failed to start still and keeps loading like there's an endless loop on my file.
### Sample code

```javascript
// paste the code you are running here
const newFile = ['q', 'q', 1, 2, 2, 5];

console.log(2 + 2);
console.log(newFile);
console.log(5 + 5);
```
![qa](https://user-images.githubusercontent.com/38655623/112711973-cc65c580-8ea2-11eb-825c-768107430dcf.png)
![qok](https://user-images.githubusercontent.com/38655623/112712053-3a11f180-8ea3-11eb-99ed-23c310099570.png)

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
No Output from Quokka
```

### Code editor version

Visual Studio Code v1.54.3

### OS name and version

Linux Ubuntu 20.04

**Comment by ArtemGovorov** [comment]
Can you please:
- try and run new Quokka scratch file (`Ctrl + K, J`) outside of any project, in a new VS Code instance, to see if it works or produces the same result.
- after Quokka hangs to run, open VS Code Developer Tools (`Toggle Developer Tools` command) and copy/paste output from Console tab of the dev tools.

**Comment by abisalde** [comment]
## This is the code
```
const myPofile = { name: 'Abisalde', Job: 'IT', Location: 'Lagos' };

console.log(myPofile.name); //

console.log(5 + 5); //

console.log(10 + 20); //

```
### This is the Developer Tools message from console

👉️ DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

👉️ [Extension Host]  [Info]  #Untitled-1.js Quokka.js stopped

👉️ /snap/code/59/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:62 [Extension Host] No editors associated with document: Untitled-1


#### Picture below

![qokku](https://user-images.githubusercontent.com/38655623/112718668-e7e4c680-8eca-11eb-9a09-fda24b8066e1.png)

**Comment by smcenlly** [comment]
We suspect that your issue may be caused by an error in a different extension which results in Quokka not working for you. 

Could you please:

1. Try creating a new workspace and disabling all extension in that workspace except for Quokka and then see if it works for you?
2. Provide us with the list of extensions you are using by running this command from the CLI:

```
code --list-extensions
```

**Comment by abisalde** [comment]
So I disabled all extension and opened a new workspace but remains the same.

1. Still running endlessly
2. My extensions below
```
aaron-bond.better-comments
abusaidm.html-snippets
auchenberg.vscode-browser-preview
bierner.emojisense
burkeholland.simple-react-snippets
CodeStream.codestream
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
eamodio.gitlens
ecmel.vscode-html-css
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
formulahendry.auto-rename-tag
HookyQR.beautify
ionutvmi.path-autocomplete
mikestead.dotenv
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-python.python
ms-toolsai.jupyter
ms-vscode-remote.remote-wsl
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
oderwat.indent-rainbow
PKief.material-icon-theme
Pluralsight.pluralsight
redhat.vscode-yaml
ritwickdey.LiveServer
RobbOwen.synthwave-vscode
sdras.night-owl
Shan.code-settings-sync
vscode-icons-team.vscode-icons
WakaTime.vscode-wakatime
WallabyJs.quokka-vscode
```


![newQuokka](https://user-images.githubusercontent.com/38655623/112783186-bc71f100-901c-11eb-9234-73e258e5c072.png)

**Comment by smcenlly** [comment]
Can you please confirm that `node.js` is installed on your machine by opening the VS Code terminal and running `node --version`? Could you also please let us know what version of `node.js` you are using?

If `node.js` is installed correctly, could you please try [explicitly setting the path to your `node.js` executable](https://quokkajs.com/docs/configuration.html#nodejs-version) in your Quokka global config file (located at `~/.quokka/config.json`). For example:

**determine node.js path**
```
which node
```

> /home/username/.nvm/versions/node/v14.7.0/bin/node

**~/.quokka/config.json**
```json
{
    "node": "/home/username/.nvm/versions/node/v14.7.0/bin/node"
}
```

**Comment by abisalde** [comment]
### Working Now

✅️ I updated ```nodejs``` from version **12.4 to 14.7** and set the **14.7.0** to default, tried out my code with Quokka and 🤭️🤭️🤭️Viola, below is the code I run initially.

![working](https://user-images.githubusercontent.com/38655623/112909247-07dcdb80-90bf-11eb-8a28-1f1817c2e919.png)


### **THANK YOU FOR HELPING OUT**
