### ISSUE TITLE
Quokka doesn't support RequireJS

### ISSUE THREAD

**Issue by Inevix** [wallabyjs/quokka#606]
### Issue description or question

Quokka doesn't support RequireJS.
For example: 
Magento 2 use RequireJS and all scripts should be wrapped by define functions.
But Quokka doesn't compile code because of errors described below. I have not found a way to skip those errors.

### Sample code

scripts/main.js
```javascript
requirejs(['utils'], function (utils) {
    const sum = utils.sum(1, 2);
    const span = document.querySelector('.js-sum');

    if (span) span.innerText = sum;
});
```

scripts/utils.js
```javascript
define([], function () {
    return {
        sum: function (num1, num2) {
            return num1 + num2;
        }
    }
});
```

### Sample repository link

https://github.com/Inevix/requirejs

### Quokka.js Console Output

```
requirejs is not defined at scripts/main.js:1:0
define is not defined at scripts/utils.js:1:0
```

![image](https://user-images.githubusercontent.com/28815318/112715830-62254300-8eeb-11eb-948d-86b3e75e7583.png)
![image](https://user-images.githubusercontent.com/28815318/112715831-63ef0680-8eeb-11eb-8a21-e33de75591b0.png)

### Code editor version

PhpStorm 2020.3.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Quokka runs in node.js, so `require.js` is not supported. Having said that, if there's a way to run require.js code in node without Quokka (not sure if [this article](https://requirejs.org/docs/node.html) is any help or not), then Quokka should be able to run it too.
