### ISSUE TITLE
Unexpected token } in JSON at position 543

### ISSUE THREAD

**Issue by henleyb** [wallabyjs/quokka#608]
### Issue description or question

When running Quokka in an Angular project, no matter which .ts file, I'm getting the following returned when using it.

### Quokka.js Console Output

```
​​​​​Quokka 'test.component.spec.ts' (node: v14.16.0, TypeScript: v3.2.1)​​​​ ​View recent Quokka files​
 
Unexpected token } in JSON at position 543 
  at ​​​parse​​​ ​./node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts:195​
  at ​​​readFileSync​​​ ​./node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts:181​
  at ​​​Object.loadSync​​​ ​./node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts:151​
  at ​​​readConfig​​​ ​./node_modules/ts-node/src/index.ts:425​
  at ​​​Object.register​​​ ​./node_modules/ts-node/src/index.ts:189
```

### Code editor version

Visual Studio Code v1.54.3

### OS name and version
OSX 11.2.1

Thanks

**Comment by smcenlly** [comment]
The error indicates that one of our dependencies that is used to run your Quokka file (`ts-node`) cannot parse your `tsconfig.json` file. Can you please provide us with the contents of that file `tsconfig.json`?

From our [docs](https://quokkajs.com/docs/configuration.html#typescript):

> Most times if you are using TypeScript, no configuration is required. Quokka uses ts-node to run your TypeScript files.
>
> **Overriding Quokka’s TypeScript Dependencies**
> Quokka is installed with three dependencies that are required to execute TypeScript files:
> 
> * TypeScript (used to compile your TypeScript files)
> * ts-node (used to import other TypeScript files from your project)
> * tsconfig-paths (used for TypeScript’s module resolution)
>
> Depending on your project and the version of Quokka that you are using, you may want to use a different version of these dependencies. You may override the version for any (or all) of these by installing the dependency either as a project dependency or in your global quokka ~/.quokka/node_modules folder. Quokka will attempt to find each dependency first in the project folder, then in the global ~/.quokka/node_modules folder; if the dependency is not found in the project or global folder, Quokka will use its own version.

---

You may also be able to fix your problem by installing `ts-node` as a project-level dependency with:

```
npm install ts-node --save-dev
```

**Comment by henleyb** [comment]
Thanks for your response, I ran npm i ts-node --save-dev but no change unfortunately.

my tsconfig.json is:

{
  "compileOnSave": false,
  "exclude": [
    "node_modules"
  ],
  "include": [
    "src/**/*.ts"
  ],
  "compilerOptions": {
    "outDir": "./dist/out-ts",
    "baseUrl": "src",
    "paths": {
      "@app/*": ["app/*"],
      "@core/*": ["app/core/*"],
      "@env/*": ["environments/*"],
      "@shared/*": ["app/shared/*"],
    },
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2015",
      "dom"
    ]
  }
}

I also noticed that the src folder does not exist under:

./node_modules/ts-node/node_modules/tsconfig/src/tsconfig.ts

**Comment by smcenlly** [comment]
Could you also please provide us with:

1. Your `package.json` dependencies / devDependencies
2. A sample of the code that you are attempting to run (can you replicate the problem without importing any other files/packages? try bisecting your code to produce a minimal reproduceable piece of code that has the problem.

I can see that you're attempting to run Quokka on a `.spec.ts` file (I had missed this before) so I am assuming that this file has tests in it. If you're attempting to run tests then it's possible that there's some other test setup code that is missing, or perhaps mocks that are being set that causing Quokka to fail. If you are looking to run your tests, then perhaps you would be better off using our other product, [Wallaby.js](https://wallabyjs.com).

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you are still having a problem, please provide us with the details requested and we'll re-open.
