### ISSUE TITLE
Output improvements

### ISSUE THREAD

**Issue by hmoritz** [wallabyjs/quokka#61]
### Feature Request - Output improvements

Hey Artem,
thanks for making Quokka.js. I really enjoy using it. I came up with some possible improvements:

It would be pretty helpful if there were quotation marks around strings.

```javascript
const five = '5'
five // 5
const name = 'Adam '
name // Adam
```

And you could probably remove the `[Iterator]` part in the following example in order to save space.

```javascript
const numbers = [1, 2, 3, 4]
numbers // [ [Iterator] 1, 2, 3, 4 ]
```

### Code editor version

Visual Studio Code v1.13.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for suggesting the feature request.

> And you could probably remove the [Iterator] part in the following example in order to save space.

This had been fixed in the latest Quokka extension v1.0.38.

**Comment by smcenlly** [comment]
@rdhar - we have definitely made improvements in this area. Specifically, strings are output between single quotes. The data types themselves are also now displayed in Quokka's Value Explorer feature.

If you haven't used Quokka for a while, you may download the latest version to see how it behaves.

**Comment by rdhar** [comment]
Great to hear, @smcenlly, thanks for the update! Guess this issue can be put to bed.

**Comment by rdhar** [comment]
@smcenlly I think #363 can be resolved along with this issue as well, for a bit of tidying-up.
