### ISSUE TITLE
Possible to bypass or access dynamically read elements from the DOM?

### ISSUE THREAD

**Issue by Mark2Mark** [wallabyjs/quokka#611]
### Sample code

```javascript
const header = document.getElementsByClassName('header')[0];
header
```

The "header" classes can only be read from the DOM, and the JS doesn’t know about it by default. Hence it’s an empty array and the first item undefined. Is it possible to bypass this somehow, because currently, all the code flow is broken (red nodes everywhere). I find quokka quite unuseful if this is the case.

### Quokka.js Console Output

```
undefined ​​​​​at ​​​document.getElementsByClassName('header'...​​​ ​quokka.js:1:0​

undefined ​​​​​at ​​​header​​​ ​quokka.js:2:0​
```

### Code editor version

Visual Studio Code v1.56.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It looks like HTML file with your elements is not loaded. This [docs section](https://quokkajs.com/docs/configuration.html#jsdom) should help to correctly load your HTML file so that your code can access it when ran by Quokka.

**Comment by Mark2Mark** [comment]
Oh, thank you so much. I solved it by renaming the html to "index.html". From your docs section, I wonder: do you have to change the `jsdom.file` every time you switch projects, if one cannot use "index.html"?

In grav the file structure uses twig templates like `default.html.twig` and the JS files are all in a different JS folder.

**Comment by ArtemGovorov** [comment]
> From your docs section, I wonder: do you have to change the jsdom.file every time you switch projects, if one cannot use "index.html"

You may configure the setting on a per project basis using [Quokka project config](https://quokkajs.com/docs/configuration.html) or inline config for ad-hoc files.
