### ISSUE TITLE
Quokka depends on an outdated version of icu4c

### ISSUE THREAD

**Issue by kyledurand** [wallabyjs/quokka#613]
### Issue description or question

Feel free to close this because I don't know if it's actually a quokka issue but someone here might have seen it before and have a solution.

I have icu4c 68.2 installed which is the [latest stable version](https://formulae.brew.sh/formula/icu4c) and quokka won't load because it requires 67 (see output below). I could brew uninstall 68.2 and install 67 but I don't really want to do that.

### Sample code

```javascript
console.log('anything'); 
```

No output

### Quokka.js Console Output

```
​Quokka
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib 
  Referenced from: /usr/local/bin/node 
  Reason: image not found 
```

### Code editor version

Visual Studio Code v1.55.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Quokka doesn't depend on icu4c, from the error message it looks like your default node.js version does though. Quokka uses your default (`/usr/local/bin/node`) node version to run code, but you may change it to [any node version](https://quokkajs.com/docs/configuration.html#nodejs-version) (that doesn't throw the error that is compatible with your icu4c version).

Hope it helps.

**Comment by kyledurand** [comment]
It does. Darn confusing error messages. Thanks Artem!
