### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Lavanbradley** [wallabyjs/quokka#614]
I purchased Quokka with a 30% student discount and it wont let me use it.

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Can you please provide some more details about what exactly is not working for you? Please attach some screenshots and a list of things/commands/actions that you have tried.

**Comment by smcenlly** [comment]
Closing this issue as we have not heard back. If you're still having problems, please provide us with additional details, we're happy to help.
