### ISSUE TITLE
Quokka license as environment variable

### ISSUE THREAD

**Issue by yngwi** [wallabyjs/quokka#618]
### Issue description or question

Please consider the possibility of adding the Quokka License key in different (more permanent) ways than the input field in VSCode (and probably other editors). I mostly use VSCode [Containers](https://code.visualstudio.com/docs/remote/containers) for development as I have to use several very different environments and the Quokka key has to be added any time I have to rebuild a dev container. The same goes for me switching between VSCode in Windows or inside the [WSL](https://code.visualstudio.com/docs/remote/wsl). Other plugins use different ways to solve this, for instance a license file that can be mounted into the container or (even better) the use of an environment variable that can be set once.

**Comment by smcenlly** [comment]
While perhaps not ideal, you may solve this problem in the meantime until we have such a feature by sharing your local Quokka license key with your dev container. For example, in your `docker-compose.yml`:

**docker-compose.yml**
```yaml
...
    volumes:
      # Add .quokka folder from local home directory for licensing
      # Assumes `node` is container username
      - ~/.quokka:/home/node/.quokka
...
```

---

While we can't commit to an immediate timeline for this, we'll consider this feature request in our next planning session.

**Comment by yngwi** [comment]
Thank you for your feedback. Even though a simple env parameter would be even more convenient, this workaround works well enough for me, thank you. Also thank you for considering the feature request. Feel free to close this issue if you wish.
