### ISSUE TITLE
Live result not showing with Ternary Operator

### ISSUE THREAD

**Issue by Faq** [wallabyjs/quokka#620]
### Issue description or question
Quokka 1.0.360 and two examples provided where used with if and else operator and then the same code with Ternary Operator.

### Sample code

```javascript
let isLocked = false;

if (isLocked) {
  console.log('You will need a key to open the door.');
} else {
  console.log('You will not need a key to open the door.');
}
isLocked ? console.log('You will need a key to open the door.') : console.log('You will not need a key to open the door.');

let isNightTime = true;
 
if (isNightTime) {
  console.log('Turn on the lights!');
} else {
  console.log('Turn off the lights!');
}

isNightTime ? console.log('Turn on the lights!') : console.log('Turn off the lights!');
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka 'a.test.js' (node: v14.16.0, plugins: jsdom-quokka-plugin)​​​​
You will not need a key to open the door. 
  at ​a.test.js:24:2​
 
You will not need a key to open the door. 

Turn on the lights! ​​​​​at ​a.test.js:31:2​

Turn on the lights! ​​​​​
```

### Code editor version

Visual Studio Code v1.55.2 and v1.56

### OS name and version

w10Pro 64bit
![image](https://user-images.githubusercontent.com/322016/116501779-6235ab80-a8ba-11eb-863a-0c3c21acca3b.png)

**Comment by smcenlly** [comment]
Thanks for reporting the problem and for your sample. This is fixed in the latest version of Quokka for VS Code, `v1.0.361`. Please update to the latest version to fix the problem.

![image](https://user-images.githubusercontent.com/2074089/116508476-d301b580-a904-11eb-8b7b-9bb0f0d30f76.png)
