### ISSUE TITLE
Quokka disables vim keybinding in VS Code

### ISSUE THREAD

**Issue by fsoft72** [wallabyjs/quokka#621]
### Issue description or question

The latest version of Quokka has some issues with VS Code vim keybindings: once you start editing on a newly open file, you no longer can use vim keybindings but are forced to use 'standard' keybindings.

Maybe it can be related to this issue (reported by me):

[https://github.com/wallabyjs/quokka/issues/326
](https://github.com/wallabyjs/quokka/issues/326)

### Code editor version

Visual Studio Code v1.55.2

### OS name and version

Linux - Kubuntu 20.10

**Comment by smcenlly** [comment]
Unlike the VIM extension, Quokka doesn't have any special handling for keyboard events. 

Similar to the [previous issue](https://github.com/wallabyjs/quokka/issues/326) that we investigated, this is almost certainly a problem with the VIM extension. Please raise the issue in the VIM repository and include the exact steps that they need to take to replicate the issue. They should be able to use Quokka `Community` edition.
