### ISSUE TITLE
Is it possible to launch a Quokka Project directly?

### ISSUE THREAD

**Issue by nemosmithasf** [wallabyjs/quokka#622]
pursuant to this feature: https://github.com/wallabyjs/quokka/issues/554#issue-723568947

Do you have any suggestions on how to launch a Quokka project directly without having to go through the intermediary steps of initiating it via VScode? (e.g. something like a custom shortcut, or even a custom instance of VScode specifically dedicated to Quokka)

**Comment by ArtemGovorov** [comment]
You may use [this setting](https://quokkajs.com/whatsnew/vscode-automatic-start.html) that we have recently added.
