### ISSUE TITLE
VSCode extension not installing properly

### ISSUE THREAD

**Issue by merroth** [wallabyjs/quokka#623]
### VSCode extension not installing properly

When i run the "Quokka.js: Start on Current File" command after installing i get the following error from Quokka Output:

```
Quokka
TypeError: B.create is not a function 
    at Module._compile (module.js:409:26) 
    at Object.Module._extensions..js (module.js:416:10) 
    at Module.load (module.js:343:32) 
    at Function.Module._load (module.js:300:12) 
    at Function.Module.runMain (module.js:441:10) 
    at startup (node.js:139:18) 
    at node.js:968:3 
```

I have tried uninstalling/reinstalling the extension and upgraded node.js using `npm update -g`, but nothing seems to help.

I have also tried manually removing "%USERPROFILE%\\.vscode\extensions\wallabyjs.quokka-vscode-1.0.362" after uninstalling and then reinstalling it fresh.

It works on one of my other machines so the problem may be unique.

### Code editor version

Visual Studio Code v1.55.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
What is your current node.js version?

```
node -v
```

**Comment by merroth** [comment]
> 
> 
> What is your current node.js version?
> 
> ```
> node -v
> ```

v4.4.2

**Comment by ArtemGovorov** [comment]
Thanks for checking. Quokka requires node version to be 8+. Please install a more recent version and it should work for you. If you don't want to change your globally installed node version, you may install a more recent version separately (for example using `nvm`) and [specify the path to the installed version in your Quokka config](https://quokkajs.com/docs/configuration.html#nodejs-version).
