### ISSUE TITLE
console input 

### ISSUE THREAD

**Issue by hamidrezarat** [wallabyjs/quokka#626]
Is there a way to have a console input in Quokka ?
I mean something like the prompt function in the browser .

I think this option is really needed.

**Comment by smcenlly** [comment]
Closing as a duplicate of https://github.com/wallabyjs/quokka/issues/538

**Comment by deniercounter** [comment]
@smcenlly Unfortunately your duplicate is a recursion to a closed issue. 

Is there a way to receive values from a terminal and rerun the “quokka” monitored code of the JS-file based on a watched new received value?

**Comment by smcenlly** [comment]
@deniercounter - I don't understand your comment. The duplication mentioned above is still open...

There is no way for Quokka to receive values from the terminal.

**Comment by deniercounter** [comment]
@smcenlly : Thanks, your fast answer saved time
