### ISSUE TITLE
Typescript - cannot import module

### ISSUE THREAD

**Issue by ppasieka** [wallabyjs/quokka#63]
### Issue description or question

I have typescript file in which I use functions from date-fns library. Problem is that date-fns(v 1.28.5) uses commonJs default export. My code uses default import syntax. Bad things is that allowSynteticDefaultImport seems to not work at all in quokka. Is there any way to configure quokka to correctly execute code like this?

### Quokka.ts file

```typescript
;({
  ts: {
    compilerOptions: {
      module: 'es2015',
      moduleResolution: 'node',
      allowSyntheticDefaultImports: true
    }
  }
})
import addDays from 'date-fns/add_days'
// other imports from date-fns
import { unfold } from 'ramda'

// my function 
export function range(from: Date | DateString, to: Date | DateString) {
  const limit = addOneDay(to) 
  const fn = d => (isBefore(d, limit) ? [parse(d), addOneDay(d)] : false)
  return unfold(fn, from)
}

// test
const res = range('2001-01-01', '2001-01-10')
console.log(res)

****

```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v7.8.0, TypeScript: v2.4.1)​​​​
​​​​
​​add_days_1.default is not a function​​
  at ​​​Object.add​​​ ​ScriptsDev/cms/Reservations/quokka.ts:52:2​
  at ​​​Object.<anonymous>​​​ ​.\node_modules\ramda\src\internal\_createPartialApplicator.js:8​
  at ​​​Object.addOneDay​​​ ​.\node_modules\ramda\src\internal\_arity.js:5​
  at ​​​range​​​ ​ScriptsDev/cms/Reservations/quokka.ts:92:2​
  at ​ScriptsDev/cms/Reservations/quokka.ts:106:0​

```

### Code editor version
Visual Studio Code v1.14.1

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
In TypeScript compiler, the `allowSyntheticDefaultImports` option [doesn't change the compilation result](https://www.typescriptlang.org/docs/handbook/compiler-options.html), only type checking. It means that no matter what you set it to, the compiled code looks exactly the same, and this import: `import addDays from 'date-fns/add_days'` will not work for you after a pure TypeScript compilation.

You may try it yourself - compile your code with `tsc` and run the resulting JavaScript, you'll get the exact same error.

To make it work you may simply change the import as follows:

```javascript
import * as addDays from 'date-fns/add_days'

console.log(addDays)
```
