### ISSUE TITLE
Problem with automatic imports using aurelia

### ISSUE THREAD

**Issue by jeremy-holt** [wallabyjs/quokka#631]
### When using aurelia and quokka, and allowing vs code to do the automatic importing, I get the following error

Quokka 'Untitled-1.ts' (node: v14.15.1, TypeScript: v4.2.4)​​​​ ​View recent Quokka files​
 
**Reflect.getOwnMetadata is not a function** 
  at ​​​Object.getOwn​​​ ​./node_modules/aurelia-metadata/dist/commonjs/aurelia-metadata.js:41​
  at ​​​Object.getOrCreateOwn​​​ ​./node_modules/aurelia-metadata/dist/commonjs/aurelia-metadata.js:47​
  at ​​​deco​​​ ​./node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:5116​
  at ​​​bindable​​​ ​./node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:5135​
  at ​​​__decorate​​​ ​./node_modules/aurelia-templating-resources/dist/commonjs/aurelia-templating-resources.js:47​
  at ​./node_modules/aurelia-templating-resources/dist/commonjs/aurelia-templating-resources.js:106​
  at ​​​Object.<anonymous>​​​ ​./node_modules/aurelia-templating-resources/dist/commonjs/aurelia-templating-resources.js:126​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1063​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1092​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:928​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:769​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:952​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:88​
  at ​​​Object.<anonymous>​​​ ​./node_modules/aurelia-i18n/dist/commonjs/aurelia-i18n.js:14​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1063​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1092​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:928​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:769​
  at ​​​Module.require​​​ ​internal/modules/cjs/loader.js:952​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:88​
  at ​​​Object.<anonymous>​​​ ​./src/core/helpers.ts:3​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1063​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1092​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:928​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:769​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:88​
  at ​​​Object.<anonymous>​​​ ​quokka.ts:1​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1063​

### Sample code

this is the automatic import
import { isNullOrUndefined } from "./../../../../../../Visual Studio/AmbFactoryMonitor/AmbFactoryMonitorClient/src/core/helpers";

### Code editor version

Visual Studio Code v1.561?
### OS name and version

Windows 10 latest

**Comment by smcenlly** [comment]
It looks like this is a [known issue running aurelia in node.js](https://github.com/aurelia/store/issues/65), which is what Quokka does.

A simple way to reproduce the problem is:

```javascript
const templatingResources = require('aurelia-templating-resources');
```

To fix the problem, as per the aurelia issue:
1. Install `reflect-metadata` (e.g. `npm install reflect-metadata --save-dev`).
2. Import `reflect-metadata` at the top of your Quokka file before other imports:

```javascript
require('reflect-metadata');
const templatingResources = require('aurelia-templating-resources');
```

**Comment by jeremy-holt** [comment]
Thanks very much. That fixed it.
