### ISSUE TITLE
Quokka is unable to figure out path constructs from jsconfig

### ISSUE THREAD

**Issue by abhinaba-ghosh** [wallabyjs/quokka#634]
### Issue description or question
Quokka Pro is un-able to figure out the relative paths from the referenced file. it will hard to debug/construct function scratches without this functionality. 

### Sample code

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@config": ["config"],
      "@constants": ["constants"],
    },
    "module": "commonjs",
    "target": "es6",
  },
}
```

### Output
```

​Install "@constants/environment" package for the current quokka file​
​Install "@constants/environment" package into the project​
 
Cannot find module '@constants/environment' 
```

### Code editor version

Visual Studio Code v1.56

### OS name and version

Mac Big Sur 11.2.3

**Comment by smcenlly** [comment]
Is your `jsconfig.json` working outside of Quokka? It looks like it is incorrect; if you're not familiar with paths-mapping, you can [read a bit more in the TypeScript docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). This should work for you:

**jsconfig.json**
```jsonc
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@config/*": ["config/*"],
      "@constants/*": ["constants/*"],
    },
    "module": "commonjs",
    "target": "es6",
  },
}
```
