### ISSUE TITLE
Nullish / coalescing operators not working in ES6 vs. Web API undefined in native ESM

### ISSUE THREAD

**Issue by SaNuelson** [wallabyjs/quokka#639]
### Issue description or question
Nullish operators work fine in plain scripts, but break immediately when put inside ES6 modules.
I found another issue about this [here](https://github.com/wallabyjs/quokka/issues/541).
Using help there, I was able to add 
```json
{
  "stdEsm": false,
  "nativeEsm": true,
  "plugins": ["jsdom-quokka-plugin"]
}
```
to package.json, which fixed the issue.
However, another issue appears. Web API no longer works in scripts when nativeEsm is turned on.

E.g.:
#### using stdEsm
```javascript
import { dummy } from './dummy.js';
let fail = dummy ?? "not dummy";
fetch('./dummy.json').then(res => res.text()).then(text => console.log(text));
```
outputs
```
​​​​​Quokka 'index.js' (node: v16.2.0, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
.\src\index.js:3 
let fail = ($_$w(1, 0, $_$c), ($_$w(1, 1, $_$c), dummy) ?? ($_$w(1, 2, $_$c), 'not dummy')); 
                                                         ^ 
 
SyntaxError: Invalid or unexpected token 
    at new Promise (<anonymous>) 
```

#### using nativeEsm
```javascript
import { dummy } from './dummy.js';
let fail = dummy ?? "not dummy";
fetch('./dummy.json').then(res => res.text()).then(text => console.log(text));
```
outputs
```
​​​​​Quokka 'index.js' (node: v16.2.0, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
fetch is not defined 
  at ​./src/index.js?session=gnz3z:4​
```

Now I'm honestly not all that well-versed in all the nuances of Quokka's internals, and I realize the Web API might be actually inaccessible to it, but is there at least some kind of work-around?

My specific use-case is a fairly large inter-connected module system in which some rely on using fetch to get data for internal logic. I was trying to bypass this by some bamboozles like:
```js
if (!fetch)
  let fetch = () => {};
```
or something similar just to be able to prototype at least partially, but to no avail.
Any help is much appreciated.

### Code editor version
Visual Studio Code v1.56.2

### OS name and version
Windows 10.0.19041 Build 19041

**Comment by SaNuelson** [comment]
My bad, I forgot to include JSDOM plugin.
Config as follows works just fine:
```json
  {
    "stdEsm": false,
    "nativeEsm": true,
    "plugins": ["jsdom-quokka-plugin"]
  }
```

**Comment by smcenlly** [comment]
For the first error you described, we will need you to provide `dummy.js` to understand what is going on.

For the second error, it looks like you need to import `fetch`. When Quokka runs your code, it runs in `node.js` which doesn't provide a global `fetch` implementation. You will need to add the [`node-fetch`](https://www.npmjs.com/package/node-fetch) package and import it in your Quokka file.

**Comment by SaNuelson** [comment]
Hello, thanks for the quick response.
In the first error, dummy.js seems to be irrelevant for the error. For example:
```javascript
import { dummy } from './dummy.js';

let internalDummy = "dummy";
let fail = internalDummy ?? "not dummy";
```
throws the same error at the operator. It seems the coalesing operator just stops working (in stdEsm) once "import" or "export" keyword is found.

Either way 'dummy.js' contents are:
```javascript
export const dummy = "dummy";
```

For the second error, I tried installing the 'node-fetch' package and import it.
```javascript
// index.js
import { dummy } from './dummy.js';
import fetch from 'node-fetch';

let fail = dummy ?? "not dummy";

fetch('./dummy.js').then(res => res.text()).then(text => console.log(text));
```
// package.json
```json
{
  ...
  "type": "module",
  "quokka": {
    "stdEsm": false,
    "nativeEsm": true
  },
  "dependencies": {
    "node-fetch": "^2.6.1"
  }
}
```
with output
```
​​​​​Quokka 'index.js' (node: v16.2.0, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
Only absolute URLs are supported 
  at ​​​getNodeRequestOptions​​​ ​./node_modules/node-fetch/lib/index.js:1305​
  at ​./node_modules/node-fetch/lib/index.js:1410​
  at ​​​fetch​​​ ​./node_modules/node-fetch/lib/index.js:1407​
  at ​./src/index.js?session=y243z:5​
```

So it works... kinda. But does it mean I can't utilize DOM's fetch?

**Comment by smcenlly** [comment]
Regarding the first issue:

```
SyntaxError: Invalid or unexpected token 
```

This has been fixed in the latest version of Quokka. We had actually [seen this error before](https://github.com/wallabyjs/quokka/issues/541#issuecomment-694557801). Please update to the latest version of Quokka to fix the problem.

---

Regarding your second issue, `Only absolute URLs are supported`. This is a limitation of the `node-fetch` module. Unlike when you are using the browser, it doesn't have the context of a "server" and your files are not exposed as any sort of HTTP endpoint. Instead of using `fetch('./dummy.js')`, in your Quokka scratchpad, you may use `require('./dummy.js')`.
