### ISSUE TITLE
Question: Quokkajs in unable to find jquery: $ is not defined

### ISSUE THREAD

**Issue by alexanderdevm** [wallabyjs/quokka#64]
### Issue description or question

When i have enabled Quokka in vscode, it showed an error for  $ is not defined in my js file. 

I am using nginx as the back end for my server

jQuery reference in html file with <script> tags

### Quokka.js file

```
{"pro":false}
```

### Sample repository link

script.js
`$.ajaxSetup({
    async: true,
    type: "GET"
});`

index.html
`<script type="text/javascript" charset="utf8" src="./scripts/jquery-3.2.1.min.js"></script>`

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v6.10.3)​​​​
​​​​
​​$ is not defined​​
  at scripts/quokka.js:184:0​
```

### Code editor version

Visual Studio Code v1.14.0

### OS name and version

Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-514.26.2.el7.x86_64

**Comment by ArtemGovorov** [comment]
Quokka runs in node. To emulate browser environment you may [use this plugin](https://github.com/wallabyjs/jsdom-quokka-plugin). Once the plugin is added to your quokka config, you may do:

```javascript
const $ = require('./scripts/jquery-3.2.1.min.js');
...
$.ajaxSetup({ async: true, type: "GET" });
...
```

**Comment by bryandandan** [comment]
I received the following error after doing what u said:
Only 'Pro' edition of Quokka.js supports project files import

**Comment by smcenlly** [comment]
You can only import file from your project using Quokka 'Pro' edition. However, you may use the 'Community’ edition to import any locally installed node modules to your Quokka file. In your case, it looks like `./scripts/jquery-3.2.1.min.js` is part of your project.

You can switch from 'Community' edition to 'Pro' (and back) any time by using the 'Quokka.js: Switch edition' command in your editor (or the "Help - Quokka.js" menu in your JetBrains IDE).

Note that if you do not have a license for Quokka.js 'Pro', you will be prompted to click a button to continue and occasionally require to restart your editor to keep using the 'Pro' features. Please [contact us](mailto:hello@wallabyjs.com) if you would like to arrange a trial period for yourself or your team without activation prompts and restarts.
