### ISSUE TITLE
IntersectionObserver is not defined

### ISSUE THREAD

**Issue by Willaiem** [wallabyjs/quokka#642]
### Issue description or question
Quokka cannot use IntersectionObserver, but TypeScript correctly works with it.
How I can fix this?

### Sample code

```javascript
const observer = new IntersectionObserver((entries) => {
  console.log(entries);
});
```

This is the workaround I have to use (But I still cannot use any methods or properties):
```javascript
// @ts-ignore
class IntersectionObserver {}

const divEl = document.querySelector('div') as HTMLDivElement;

// Now Quokka won't complain...
const observer = new IntersectionObserver((entries) => {
  console.log(entries);
});

// But this will throw an error in Quokka
observer.observe(divEl)

/*
observer.observe is not a function 
  at ​​​Object.<anonymous>​​​ ​app.ts:11:0​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1063​
*/
```

### Quokka.js Console Output

```
IntersectionObserver is not defined 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1063​
  at ​​​Object.<anonymous>​​​ ​app.ts:1:0
```

### Code editor version

Visual Studio Code v1.56.2

### OS name and version

Windows 10 10.19042

**Comment by smcenlly** [comment]
`IntersectionObserver` is available in the browser, however, Quokka runs in `node.js` which does not support `IntersectionObserver`; this is why you're getting the error.

You may find [this section of the Quokka docs](https://quokkajs.com/docs/how-does-it-work.html) helpful as it explains some of the differences.
