### ISSUE TITLE
Missing line numbers in errors

### ISSUE THREAD

**Issue by kredati** [wallabyjs/quokka#644]
### Issue description or question
The quokka output for errors & stack traces gets the file names right, but instead of line numbers, the output ends with `?session=xxxx`. I've searched the documentation and searched the other issues and couldn't find anything about this. Apologies if there's an easy preference or configuration fix I should have been able to google up. Thanks!!

### Sample code
`a.js`:
```javascript
throw Error('thrown!');
```

### Sample repository link

https://github.com/kredati/quokka-line-numbers

Included for the `quokka` section of `package.json`:

```json
"quokka": {
  "stdEsm": false,
  "nativeEsm": true
}
```

That said, removing this doesn't help. So.

### Quokka.js Console Output

```
​​​​​Quokka 'a.js' (node: v16.1.0)​​​​ ​View recent Quokka files​
 
thrown! 
  at ​./quokka-line-numbers/a.js?session=ea3om:4
```
I'd like a line number here.

### Code editor version

Visual Studio Code v1.56.2

### OS name and version

OSX 11.3 (NB: it's an M1 Mac.)

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Quokka for VS Code, `v1.0.369`.

**Comment by kredati** [comment]
And thanks for fixing it so quickly!
