### ISSUE TITLE
Quokka start issue under NVS

### ISSUE THREAD

**Issue by HorusAK** [wallabyjs/quokka#647]
Using NVS as node version manager on Windows.

Quokka config has a targeted node version as follows:

```json
{"pro":false,"node":"C:\\Users\\Playa\\AppData\\Local\\nvs\\node\\16.2.0\\x64"}
```

Result:
Cannot launch quokka and receiving the following error in console

### Quokka.js Console Output
11:17 PM	Quokka
					Can not start node.js process (C:\Users\Playa\AppData\Local\nvs\node\16.2.0\x64).
					You may use the "node" setting to configure the location of node.

Webstorm v2021.1.2
Win 10

**Comment by smcenlly** [comment]
From the configuration that you provided, the path is incorrect. You need to fully specify the path of the node executable. For example:

```json
{"pro":false,"node":"C:\\Users\\Playa\\AppData\\Local\\nvs\\node\\16.2.0\\x64\\node.exe"}
```

You should be able to confirm that the path is correct by running it from the command line:

```
> C:\Users\Playa\AppData\Local\nvs\node\16.2.0\x64\node.exe --version
```

**Comment by HorusAK** [comment]
It worked like a charm.

I should've guessed it myself, but I referred to the doc - https://quokkajs.com/docs/configuration.html#nodejs-version
, and it mentioned that the parameter in config must contain a path to node. Nothing said about the full path to node execution file.

Thank you for your help.
