### ISSUE TITLE
Mouse pointer shows extra space 

### ISSUE THREAD

**Issue by Faq** [wallabyjs/quokka#648]
### Issue description or question
quokka v1.0.375 Output is ok, but when using mouse pointer on console log, it shows first line staring with extra space.

A)
![image](https://user-images.githubusercontent.com/322016/121814488-06f92600-cc7a-11eb-81a4-3ac1e6de393a.png)
B)
![image](https://user-images.githubusercontent.com/322016/121842954-01d3bf80-ccea-11eb-85a6-a68c4ee7acdb.png)

### Sample code
A)
```javascript
function draw3(n: number) {
  let rectangle: string = "";
  for (let i = 1; i <= n; i++) {
    for (let j = 1; j <= n; j++) {
      if (i === 1 || i === n || j === n || j === 1) {
        rectangle += "*";
      } else {
        rectangle += " ";
      }
    }
    rectangle += "\n";
  }
  return rectangle;
}
console.log(draw3(5));
```
B)
```javascript
function draw6(rows: number) {
  let triangle: string = "";
  for (let i = 1; i <= rows + 1; i++) {
    let j = 0;
    for (let j = 1; j <= i; j++) {
      triangle += " ";
    }
    for (let j = i; j <= rows + 1; j++) {
      triangle += "*";
    }
    triangle += "\n";
  }
  return triangle;
}
console.log(draw6(5));
```
### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output
A)
```
​​​​​Quokka '03.ts' (node: v14.17.0, TypeScript: v4.3.2, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
***** 
*   * 
*   * 
*   * 
***** 
 
```
B)
```
​​​​​Quokka '06.ts' (node: v14.17.0, TypeScript: v4.3.2, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
 ****** 
  ***** 
   **** 
    *** 
     ** 
      * 
```

### Code editor version
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

### OS name and version

w10 64bit

**Comment by smcenlly** [comment]
Thanks for reporting the issue. This is fixed in the latest version of Quokka for VS Code, `v1.0.376`.
