### ISSUE TITLE
quokkajs and intellij modules

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/quokka#649]
### Issue description or question

Hi I am using quokkajs with intellij 2021.1. I typically work with multiple modules in a single project. Each module being a node project with its own version of typescript installed.

When I start typescript on one of the project files. it shows a typescript version which is different from what has been installed for the project. Quokka seems to be picking up project root as the folder from where it conducts its search. Is there a way to configure quokka to use module directory as the root folder when it is running on a particular file from that module. 

### Sample code

```javascript
process.cwd() // shows project root in quokka. Would expect it show module root
```

### Quokka.js Console Output

```
Shows Project root
```

### Code editor version

Intellij Ultimate v2021.1.2?

### OS name and version

OSX 11.4

**Comment by smcenlly** [comment]
The current behavior is by design and there is currently no way of configuring Quokka to use the module directory as the root folder.

We're investigating what it would take to add support for this. If the effort is not too big, we'll roll this out over the next week or so. At this stage, we think we will have to add a new setting to keep the current behavior for those who may be relying on it.

**Comment by bhvngt** [comment]
Thanks for your prompt response. Glad to know that your team is working on this. Looking forward to the change if at all possible.

**Comment by smcenlly** [comment]
We had added support for running Quokka on mono repos. Quokka now supports running from root-level monorepos and projects with nested packages. If you start Quokka on an existing file within a nested package, then Quokka will automatically run in the context of the nested package. In this case, the `project` directory will be the nested package directory containing the `package.json` file for the existing file. This means that your `process.cwd()` will be the nested package directory and any project-level Quokka configuration must be specified in that folder (either as `.quokka` configuration or in `package.json`).

**Comment by bhvngt** [comment]
Thanks a ton. Will check this out.
