### ISSUE TITLE
Styling live output in Sublime Text

### ISSUE THREAD

**Issue by martinkruusement** [wallabyjs/quokka#651]
### Issue description or question

Is there a way to target the scope of Quokka's inline output in a tmTheme file?

Since the output is not selectable in the editor, the scope detection plugins can't help so I'm wondering if those scopes are documented anywhere.

```js
var sample = "demo";
sample //? demo <-- how to make 'demo' red?
```

### Code editor version

Sublime Text 4

### OS name and version

OS 12 Developer Beta 1

**Comment by smcenlly** [comment]
For information messages, Quokka uses the `--bluish` color variable from your theme. For error messages, Quokka uses the `--redish` color variable from your theme. You may modify these colors for your theme to change Quokka's inline value display. See [SublimeText theme doco](https://www.sublimetext.com/docs/themes.html#color_values) for more information.
