### ISSUE TITLE
Y haven't I received my product key

### ISSUE THREAD

**Issue by maxsimongt3** [wallabyjs/quokka#652]
### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
Closing this issue as we have responded via email.
