### ISSUE TITLE
Quokka stops after writing Math.random code

### ISSUE THREAD

**Issue by jdavid82** [wallabyjs/quokka#654]
### Issue description or question
Stops working when using Math random

### Sample code

```javascript
let dice = Math.trunc(Math.random() * 6) + 1;
while (dice !== 6) {
    console.log(`You rolled a dice`);
    if (dice === 6) {
        console.log(`the while loop is about to end`);
    }
}
```

### Quokka.js Console Output

It only shows this:
```
Quokka 'script.js' (node: v14.17.0)​​​​ ​View recent Quokka files
```

### Code editor version

Visual Studio Code v1.57.1

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment]
This is expected as there is a bug in your code that results in an infinite loop. In fact, it is not that Quokka stops, what is happening is that Quokka can only successfully execute your code everyone 1/6 times and so Quokka will show its progress indicator indefinitely when your program never terminates.

You will find the behavior is the same (infinite loop printing: `You rolled a dice`) when you run your code from the CLI using node directly.

Perhaps you need to change your code to something similar to:

```diff
let dice = Math.trunc(Math.random() * 6) + 1;
while (dice !== 6) {
    console.log(`You rolled a dice`);
    if (dice === 6) {
        console.log(`the while loop is about to end`);
    }
+   dice = Math.trunc(Math.random() * 6) + 1;
}
```

**Comment by jdavid82** [comment]
Thank you for your prompt reply, but it is not an infinite loop. I invite
you to run it and see for yourself. Cheers.

**Comment by smcenlly** [comment]
> but it is not an infinite loop. I invite you to run it and see for yourself. Cheers.

Yes it is an infinite loop. We had run this ourselves to confirm before replying. Please see screenshot attached.

![quokka-654](https://user-images.githubusercontent.com/2074089/123532061-22b9fd00-d74d-11eb-9a1e-0f3fa62da677.gif)

**Comment by jdavid82** [comment]
yes you are right, looks like I couldn't delete my silly comment early enough, thank you
