### ISSUE TITLE
why it has weid "[Object]" shows when console.log a complex object?

### ISSUE THREAD

**Issue by LastStranger** [wallabyjs/quokka#655]
<img width="585" alt="截屏2021-06-27 上午9 38 33" src="https://user-images.githubusercontent.com/29811304/123530322-71ef3600-d72b-11eb-84ed-a701f7efdd25.png">

**Comment by ArtemGovorov** [comment]
The output format is not Quokka specific. Node REPL will print the exact same thing if you try it:

<img width="294" alt="Screen Shot 2021-06-28 at 10 57 27 am" src="https://user-images.githubusercontent.com/979966/123565305-bcda7d80-d7ff-11eb-87fa-3f9e41d3e95a.png">

To explore the full value of any logged object, you may use [Quokka Value Explorer](https://quokkajs.com/docs/#value-explorer). Also, Quokka [Live Comments](https://quokkajs.com/docs/#comments) allow you to see a bit more inline:

<img width="569" alt="Screen Shot 2021-06-28 at 11 02 13 am" src="https://user-images.githubusercontent.com/979966/123565463-50ac4980-d800-11eb-8959-80e0134c3199.png">
