### ISSUE TITLE
memo.jsdom.JSDOM is not a constructor 

### ISSUE THREAD

**Issue by semiautomatixfu** [wallabyjs/quokka#657]
### Issue description or question
Cannot run the Quokka.js extension successfully.

### Sample code

```javascript
// any code, for example:
const x = 1;
x;
```

### Sample repository link

Quokka.js: New Typescript File

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-3.ts' (node: v14.16.1, babel: v7.9.0, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
TypeError: memo.jsdom.JSDOM is not a constructor 
    at Array.forEach (<anonymous>) 
    at new Promise (<anonymous>) 

```

### Code editor version

Visual Studio Code v1.57.1

### OS name and version

Linux
Kubuntu 21.04

**Comment by semiautomatixfu** [comment]
Something, something, something, in the React project. It runs in a blank project.

**Comment by ArtemGovorov** [comment]
Can you please try running `npx create-react-app my-app` to generate a fresh CRA and try running Quokka in that project to see if it's working for you? 

- If it's working in the fresh project, then you probably have an old unsupported JSDOM dependency in your dependencies. If you can't update the dependency, you may disable [Quokka config auto detection for your React project](https://quokkajs.com/docs/configuration.html#create-react-app) in your Quokka config file ([`.quokka`](https://quokkajs.com/docs/configuration.html#quokka-file-config) or [`package.json`](https://quokkajs.com/docs/configuration.html#packagejson-config)).

- If it's not working in a freshly generated project, please let us know.
