### ISSUE TITLE
localeCompare doesn't work with local language

### ISSUE THREAD

**Issue by nermin99** [wallabyjs/quokka#658]
### Issue description or question

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#using_locales

```javascript
console.log('ä'.localeCompare('z', 'de')); // a negative value: in German, ä sorts before z
console.log('ä'.localeCompare('z', 'sv')); // a positive value: in Swedish, ä sorts after z
```

### But I get: Quokka.js Console Output

```
console.log('ä'.localeCompare('z', 'de')); -1
console.log('ä'.localeCompare('z', 'sv')); -1
```

### Code editor version

Visual Studio Code v1.57.1

### OS name and version

MacOS

**Comment by smcenlly** [comment]
Your sample code is working for us:

![image](https://user-images.githubusercontent.com/2074089/124834683-851fc280-dfc3-11eb-8230-e16f99be2b4e.png)

---

Quokka runs your code using your local version of `node`. It sounds like you may have an older version of `node` or special `node` build that may be missing localization data.

You can confirm that Quokka is working correctly by saving your file to disk and running `node <filename.js>`; you will get the same results as Quokka reports.

I would suggest upgrading your `node` version to the latest version as I expect that will fix the problem for you.

**Comment by nermin99** [comment]
I am using `node v12.22.1`. I tried saving the file to disk and running it with node and got the same results. I need node version 12 for other projects, so upgrading isn't an option unfortunately.

**Comment by ArtemGovorov** [comment]
@nermin99 You may install node version that supports your scenario (14 and up) side by side your default version and [configure Quokka](https://quokkajs.com/docs/configuration.html#nodejs-version) to use the newer version.

**Comment by nermin99** [comment]
Thanks @ArtemGovorov that was a good solution 👍🏻
