### ISSUE TITLE
Proxy values problems

### ISSUE THREAD

**Issue by MatthD** [wallabyjs/quokka#661]
### Issue description or question

It seems that quokka is showing the wrong object value when using proxy and read the full object
If I point to the property itself then it's ok

### Sample code

```typescript
const target = {
  width: 200,
  background: 'white'
}

const handler: ProxyHandler<typeof target> = {
  get(target, prop, receiver){
    if(prop === 'background'){
      console.log('objectKey') //?
      return 'green';
    }
    return target[prop];
  }
}

const proxiedObj = new Proxy(target, handler) 
console.log(proxiedObj) //? background is white which is wrong
console.log(proxiedObj.background) //? background is green which is ok
```

### Code editor version

Visual Studio Code v1.57.1?

### OS name and version

OSX Big sur 11.4

**Comment by ArtemGovorov** [comment]
Your Quokka code sample works the same way as in node and browser. 

If you create a **test.js** file with the following content:

```
const target = {
  width: 200,
  background: 'white'
}

const handler = {
  get(target, prop, receiver) {
    if (prop === 'background') {
      return 'green';
    }
    return target[prop];
  }
}

const proxiedObj = new Proxy(target, handler)
console.log(proxiedObj)
console.log(proxiedObj.background)
```

and run it in node:
```
node test.js
```

then the result is:

<img width="316" alt="Screen Shot 2021-07-16 at 10 08 52 pm" src="https://user-images.githubusercontent.com/979966/125945121-a4c9a908-7cc9-44d1-ad42-27e7defbe8f9.png">

You may get the same result in Chrome console too.
