### ISSUE TITLE
Error on Quokka Start: dyld Library Not Loaded

### ISSUE THREAD

**Issue by wehrhaus** [wallabyjs/quokka#664]
### Issue description or question
When Starting Quokka on a new or existing file, the following error is output in the Quokka Terminal

### Quokka.js Console Output

```
​Quokka
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib 
  Referenced from: /usr/local/bin/node 
  Reason: image not found 
```

### Code editor version

Visual Studio Code v1.58.2

### OS name and version

OSX Big Sur v11.5

**Comment by smcenlly** [comment]
Quokka uses `node.js` to run your JavaScript/TypeScript code. The error that you are getting is coming from `node.js` and is not related to Quokka. You should get the same error when running the following from the CLI:

```
/usr/local/bin/node
```

If your node version is being referenced from another location and is not part of your system's paths, you may configure Quokka to tell it how to [locate node](https://quokkajs.com/docs/configuration.html#nodejs-version).
