### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by techie-david** [wallabyjs/quokka#670]
### Issue description or question
Getting **Unexpected token export** error while I was trying to use Quokka (**Note**. I've trial license for 15 days)

### Quokka Configuration
```
{"autoLog":true,"showSingleInlineValue":false,"delay":1000,"pro":true,"babel": true}
```

### Node.JS Version
12.0.0

### Sample code
```
import { Helper } from '../../../@core/helper'; // HERE I'M GETTING **UNEXPECTED TOKEN EXPORT**
import { ExtendedFormGroup } from '../../../@core/models/form-group';
import { Entity } from '../../../@core/types/Entity';

type TExtends = ExtendedFormGroup;

export class QuokkaTest<T extends TExtends, TEntity extends Entity> {
  public helper: Helper = new Helper();

  public createEmptyObject(type: string): TEntity {
    return this.helper.emptyObjectHelper(type) as TEntity;
  }
}
```
### Quokka.js Console Output
```
Unexpected token export 
  ​​​​​at ​​​​​​​​Module._compile​​​ ​internal/modules/cjs/loader.js:703​
  ​​​​​at ​​​​​​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:770​
  ​​​​​at ​​​​​​​​Module.load​​​ ​internal/modules/cjs/loader.js:628​
  ​​​​​at ​​​​​​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:555​
  ​​​​​at ​​​​​​​​Module.require​​​ ​internal/modules/cjs/loader.js:666​
  ​​​​​at ​​​​​​​​require​​​ ​internal/modules/cjs/helpers.js:16​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​./src/lib/@core/helper.ts:5​
  ​​​​​at ​​​​​​​​Module._compile​​​ ​internal/modules/cjs/loader.js:759​
  ​​​​​at ​​​​​​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:770​
  ​​​​​at ​​​​​​​​Module.load​​​ ​internal/modules/cjs/loader.js:628​
  ​​​​​at ​​​​​​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:555​
  ​​​​​at ​​​​​​​​require​​​ ​internal/modules/cjs/helpers.js:16​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​projects/xxxx/src/lib/@components/common/xxxx/Quokka.ts:1:0​
  ​​​​​at ​​​​​​​​Module._compile​​​ ​internal/modules/cjs/loader.js:759​
```

### Code editor version
Visual Studio Code v1.57.1

### OS name and version
Windows 10

**Comment by smcenlly** [comment]
It looks like there's a problem when TypeScript is trying to process `../../../@core/helper`. Looking at your configuration, it seems you have `babel` configured to transform your JavaScript files, but not your TypeScript files. Is this intentional? If your project uses `babel` to compile your TypeScript then you will need to [configure Quokka to use babel for TypeScript files](https://quokkajs.com/docs/configuration.html#using-babel-to-compile-typescript) instead of the TypeScript compiler:

```json
{
  "babel": {
    "ts": true,
    "plugins": ["@babel/plugin-transform-typescript"]
  }
}
```

If you're still having problems, could you please provide your `tsconfig.json` or else your `babel` configuration?

**Comment by techie-david** [comment]
Hi smcenlly,

Thanks for the quick reply!

No, I am not using babel to transform typescript to javascript file. I googled and found that we need to modify quokka's configuration and add "babel": true. Without giving that babel configuration also I am getting the same error.

Thanks!

**Comment by ArtemGovorov** [comment]
@techie-david Could you please 
- provide your `tsconfig.json`,
- are there any node modules/files being imported from the `../../../@core/helper`?

**Comment by techie-david** [comment]
Hi ArtemGovorov,

Here is my tsconfig.lib.json file:
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "declaration": true,
    "inlineSources": true,
    "resolveJsonModule": true,
    "types": [],
    "lib": ["dom", "es2018"]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true,
    "resolveJsonModule": true
  },
  "exclude": ["src/test.ts", "**/*.spec.ts"]
}

```
**are there any node modules/files being imported from the ../../../@core/helper?**
No, that helper file is simple file with all the common functions, that's it.

Thanks!

**Comment by smcenlly** [comment]
There are a few things I wanted to confirm / point out:

1. By default, Quokka expects the project root of your project to be opened. For example, if you have a `package.json` then Quokka expects the `package.json` to exist in the root folder opened in your editor. There's a slight exception to this, which is if you are running in a mono-repo; in this case, Quokka will find the the `package.json` for your project based on the on-disk location of the file you are using Quokka from. If you are running Quokka from an unsaved file (or an JetBrains editor "saved" file) then Quokka will only try and use the `package.json` and `tsconfig.json` from your opened folder root directory.

2. It looks like your `tsconfig.json` name is not aligned with the standard name, i.e. you have said that it is `tsconfig.lib.json`. This is non-standard and Quokka won't be able to determine that this is your TypeScript configuration file. If you do not have a `tsconfig.json` or have overridden its settings in another file, you will need to [configure Quokka to provide the TypeScript settings](https://quokkajs.com/docs/configuration.html#compiler-settings):

**Quokka Configuration**
```javascript
{
    "ts": {
        "compilerOptions": {
            target: "es6",
            ...
        }
    }
}
``` 

3. Do you have a folder named `@core` in your project? While it's possible to have a folder with that name, normally when we see `@core` in a project it indicates that people are using TypeScript's [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) as a part of their TypeScript configuration, in which case, trying to refer to the module with relative pathing is not going to work for you.

4. Are you using JetBrains as your editor and using a scratch file? Sometimes the JetBrains editors can incorrectly try and resolve the paths of your imports for scratch files. If this is true in your case, then you will need to adjust the import paths as if the file is running from your project root and not from the JetBrains scratch file location.

**Comment by smcenlly** [comment]
I'm going to assume that our response solved your problem. Closing the issue. If you're still having problems, please reply and we'll reopen.
