### ISSUE TITLE
replaceAll method with Quokka.

### ISSUE THREAD

**Issue by JakobKjaer** [wallabyjs/quokka#671]
### Issue description or question
The .replaceAll methods fail with; String.replaceAll is not a function with Quokka, how can that be?

### Sample code

```javascript
// paste the code you are running here
```
const userName = 'Speedster1000';
const greeting = 'Welcome back user';
const text = 'When user wins the game, then user will earn a reward!';

// .replace(search, replace)
console.log(greeting.replace('user', userName));

// .replaceAll(search, replace)
console.log(text.replaceAll('user', userName));

### Quokka.js Console Output

```
// paste your quokka console output here
```
text.replaceAll is not a function

### Code editor version

Visual Studio Code v1.59.0?

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Quokka runs in node.js and it looks like you are using version of node that doesn't support `replaceAll`. You may install [node version that supports `replaceAll`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility) and [configure Quokka to use that version of node](https://quokkajs.com/docs/configuration.html#nodejs-version).

**Comment by JakobKjaer** [comment]
Thank you very much, I will try to install the new version of Node.js!

**Comment by JakobKjaer** [comment]
It worked.
