### ISSUE TITLE
Quokka seems not to work in Ubuntu

### ISSUE THREAD

**Issue by NamDo8467** [wallabyjs/quokka#673]
### Not be able to use Quokka in VSCode in Ubuntu
My problem is that when I was working with Quokka in Windows OS, everything was good but when I switched to Ubuntu OS, Quokka didn't work. When I create a new JS file using the Quokka command, there was a little "running back and forth bar" next to the "Go Live" in the status bar. When I saved the file, that running bar was gone but the Output tab was just blank, it did not say "Quokka file_name (node v14.1)..." I have tried  to re-installed Quokka but the same issue kept happening

![Screenshot from 2021-08-21 15-31-31](https://user-images.githubusercontent.com/77046082/130315964-e89f7875-f239-4b87-acf2-3839e4ead2ee.png)

### Code editor version

Visual Studio Code v1.59.1

### OS name and version
Linux 20.0.4

**Comment by ArtemGovorov** [comment]
Can you please start Quokka, then open VS Code Dev Tools (`Toggle Developer Tools` command) and copy/paste the output from there?

**Comment by NamDo8467** [comment]
workbench.desktop.main.js:sourcemap:62 [Extension Host] (node:4221) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was create

There are 4 outputs and the above is the error. Do you need other outputs?

**Comment by ArtemGovorov** [comment]
Can you please try this:
- close VS Code,
- open `~/.vscode/extensions/` folder,
- delete all `wallabyjs.quokka-vscode-*` subfolders in there,
- start VS Code,
- install Quokka extension and start it?

If it doesn't help, please try specifying [node executable path in your Quokka settings](https://quokkajs.com/docs/configuration.html#nodejs-version).

**Comment by NamDo8467** [comment]
My path is /snap/node but I got this error in the output tab in VSCode 
"Error: spawn /snap/node EACCES 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19) 
    at onErrorNT (internal/child_process.js:465:16) 
    at processTicksAndRejections (internal/process/task_queues.js:80:21)"

Can you please help me with this?

**Comment by NamDo8467** [comment]
> Can you please try this:
> 
> * close VS Code,
> * open `~/.vscode/extensions/` folder,
> * delete all `wallabyjs.quokka-vscode-*` subfolders in there,
> * start VS Code,
> * install Quokka extension and start it?
> 
> If it doesn't help, please try specifying [node executable path in your Quokka settings](https://quokkajs.com/docs/configuration.html#nodejs-version).

Thank you, it works now

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by reivaj-git** [comment]
Para personas que entren a este hilo. Estoy en Ubuntu, y no podia ejecutar extensiones como Quokka, Code runner entre otras. Tengo Npm y nodeJs instalado pero al querer correr las extensiones me mandaba un error relacionado con node. 

No daba con la solucion pero al fin la encontre instalando 

sudo apt-get install nodejs-legacy

**Comment by smcenlly** [comment]
Translation from above:

> For people who enter this thread. I'm on Ubuntu, and I couldn't run extensions like Quokka, Code runner among others. I have Npm and nodeJs installed but when I wanted to run the extensions it sent me an error related to node.
> 
> I did not find the solution but at last I found it by installing
> 
> sudo apt-get install nodejs-legacy
