### ISSUE TITLE
Quokka confusing generator for an iterator

### ISSUE THREAD

**Issue by nermin99** [wallabyjs/quokka#674]
### Issue description or question

When dealing with generators and logging the object, the output says "Iterator" instead of "Generator" as it should be.

Maybe a generator _technicaly_ also is an iterator (I'm not entirely sure) but nevertheless, it would be more clear and besides when logging the output in normal JS it will show "Object [Generator] ..."

### Sample code

```javascript
function* generator() {
	yield 1
	yield 2
	yield 3
}

const gen = generator()
console.log(gen)
```

### Quokka.js Console Output

```
{ [Iterator] }
```

### Code editor version

Visual Studio Code v1.59.1?

### OS name and version

OSX Big Sur v11.4

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and the fix is published in the latest v1.0.394.

**Comment by sweepy84** [comment]
This is still happening to me but slightly different.

`function* MatchAll(s,regex) {
  let each
  while (each = regex.exec(s)) yield each
}

 for(let match of MatchAll("this is a $[quoted] string as you can $[read]", /\$\[.*?\]/gs)){
     console.log(match)
 }
`

The console log never runs.

on version v1.0.455

**Comment by ArtemGovorov** [comment]
@sweepy84 There's no issue with Quokka in your case. Dev tools/node CLI produce the same result (no console.log):
<img width="457" alt="Screen Shot 2022-04-03 at 3 03 06 pm" src="https://user-images.githubusercontent.com/979966/161412400-3e8c4026-e235-4aa3-ad6e-f8b1d167081f.png">

**Comment by sweepy84** [comment]
hi @ArtemGovorov - my apologies I must have changed the regex before pasting.
This runs in console, but doesn't in Quokka.
```javascript
function* MatchAll(s,regex) {
  let each
  while (each = regex.exec(s)) yield each
}
  
for(let match of MatchAll("this is a $[quoted] string as you can $[read]", /\$\[.*?\]/gs)){
  console.log(match)
}
```

**Comment by smcenlly** [comment]
We copy/pasted your example and ran as a JavaScript file and it seems to be working for us. Which editor are you using? Can you please take a screenshot of your Quokka output? Are you using TypeScript or JavaScript?

![image](https://user-images.githubusercontent.com/2074089/161452482-94b1fc3a-5f47-4f00-a7d1-aa2f222e80fc.png)

**If you are using TypeScript**, can you please share your `tsconfig.json` for your project? If you do not have a `tsconfig.json` then the TypeScript defaults will be used. Your code with the TypeScript defaults will not execute/compile properly. You can see this by saving your file (e.g. to `test.ts` in your project root) and then run `npx test.ts`. You should receive an error:

```
TSError: ⨯ Unable to compile TypeScript:
test.ts:6:18 - error TS2569: Type 'Generator<any, void, unknown>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

6 for(let match of MatchAll("this is a $[quoted] string as you can $[read]", /\$\[.*?\]/gs)){
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (./node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (./node_modules/ts-node/src/index.ts:517:19)
    at getOutput (./node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (./ts-node/src/index.ts:968:32)
    at Module.m._compile (./node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (./node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```
