### ISSUE TITLE
d3 imported via CDN is not recognised

### ISSUE THREAD

**Issue by mohan-ys** [wallabyjs/quokka#676]
### Issue description or question
error message "d3 is not defined" when d3 is added to the HTML page via the script tag

### Sample code
Code in HTML
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <title>Water</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div id="chart-area"></div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
    <script src="index.js"></script>
  </body>
</html>
````
```javascript
const svg = d3
  .select("#chart-area")
  .append("svg")
  .attr("width", WIDTH + MARGIN.LEFT + MARGIN.RIGHT)
  .attr("height", HEIGHT + MARGIN.TOP + MARGIN.BOTTOM);
````

### Quokka.js Console Output

```
d3 is not defined 
  ​​​​​at ​​​​​​index.js:128:0
```

### Code editor version

Visual Studio Code v1.59.1

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
I'm not sure how you are running Quokka on your file. Quokka does not run in a browser environment and so how your code runs in Quokka will be a little different to how it runs in your browser.

Quokka supports a **browser-like environment** using JSDOM. You can read about this in [our docs](https://quokkajs.com/docs/index.html#browser-like-runtime).

There are a few other differences that you should be aware of:
1. Unlike your browser, JSDOM loads scripts asynchronously, which means that you will also need to update your code to wait for the scripts to be loaded.
2. JSDOM runs in `node.js`, which doesn't inherently know about global scoped variables. You will need to access d3 from the `window` object.
3. By default JSDOM doesn't allow external scripts to be loaded so you will need to change the Quokka JSDOM configuration to add `resources`: `usable`.

We were able to access `d3` with the following setup:

**`.quokka` (project-level configuration file)**
```jsdom
{
    "plugins": ["jsdom-quokka-plugin"],
    "jsdom": {
        "file": "index.html",
        "config": {
          "pretendToBeVisual": true,
          "runScripts": "dangerously",
          "resources": "usable",
          "url": "http://localhost/"
        }
    }
}
```

**`index.html` (note that we have excluded index.js)**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <title>Water</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div id="chart-area"></div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
  </body>
</html>
```

**`index.js`**
```javascript
document.addEventListener('DOMContentLoaded', () => {
  console.log(window.d3);
});
```
