### ISSUE TITLE
Quokka breaks w/ VSCode 1.60 on automatic language detection

### ISSUE THREAD

**Issue by maxsommer** [wallabyjs/quokka#678]
### Issue description or question
VSCode automatic language detection seems to break Quokka for e.g. the below snippet because after it has guessed the programming language (in this case wrongly as 'Dart') it switches to different language interpretation mode.

### Sample code

```typescript
const arrString = ["asdf", "zdf"];
const arrMixed = ["asdf", 1, {}, "lel"];
const arrOnlyOther = [{}, 1, 45];

function isStringArray(arr: any[]): arr is string[] {
  const nonStringElements = arr.filter(
    (element) => typeof element !== "string"
  );
  return nonStringElements.length === 0;
}

console.table([
  ["arrString", isStringArray(arrString)],
  ["arrMixed", isStringArray(arrMixed)],
  ["arrOnlyOther", isStringArray(arrOnlyOther)],
]);
```

### Sample repository link

/

### Quokka.js Console Output
There is no further output after VSCode has switched to different language.

### Code editor version

Visual Studio Code v1.60

### OS name and version

macOS 11.5.2

**Comment by ArtemGovorov** [comment]
Thanks for the report. It looks like the issue with VS Code API. We've reported the issue at https://github.com/microsoft/vscode/issues/132431, and once it's fixed we expect Quokka to work correctly.
