### ISSUE TITLE
Copy paste problem in VS Code

### ISSUE THREAD

**Issue by nuni233** [wallabyjs/quokka#679]
### Issue description or question
When trying to populate a array of objects using copy paste the opened 'New File' (opened as Typescript) 
is changing in a manner that Quokka is not active !

### Sample code
```typescript
const data = [
    {
        $id: "2",
        equipmentID: 720,
        EquipmentName: "pmc7",
        machineAreaID: 279,
        AreaName: "Zone1",
        Color: "#C0C0C0",
        DescriptionStatus: "smart",
        StatusLogDetail: null
    },
    {
        $id: "3",
        equipmentID: 720,
        EquipmentName: "pmc7",
        machineAreaID: 279,
        AreaName: "אולם ייצור",
        Color: "#C0C0C0",
        DescriptionStatus: "אין עדיפות",
        StatusLogDetail: null
    },
]
console.log(data[0].AreaName)
```
it seems that the problem is due to the Hebrew Ascii charcters !!!

### Quokka.js Console Output

```
There is no Quokka output !!
```

### Code editor version

Visual Studio Code
====================
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

### OS name and version

Windows

**Comment by smcenlly** [comment]
This is working for us (see animated gif below). 

Your issue may be related to https://github.com/microsoft/vscode/issues/132431 (Automatic language detection overrides openTextDocument API language parameter).

Does it work for you if you start quokka on a file with a `.ts` extension before pasting the content?

![quokka-679](https://user-images.githubusercontent.com/2074089/132922920-636504a3-9780-4e51-8edd-0336a43a3352.gif)

**Comment by nuni233** [comment]
No, my problem is AFTER opening a new file as 'NEW TYPESCRIPT FILE' as in your gif !!
Before :
![image](https://user-images.githubusercontent.com/4318797/132938405-fb4e5ba5-109c-4f5d-8ef5-85d6554f5c54.png)
After:
![image](https://user-images.githubusercontent.com/4318797/132938425-a20d6f5d-c745-43df-b1bb-85a98f127815.png)

**Comment by smcenlly** [comment]
I can see that the language on your file is changing. This is the Microsoft vscode problem I mention above: https://github.com/microsoft/vscode/issues/132431

Unfortunately we need to wait for Microsoft to fix this.
