### ISSUE TITLE
Allow importing a package by it's name

### ISSUE THREAD

**Issue by Gozala** [wallabyjs/quokka#68]
### Issue description or question

Right now to import a project's main module you need to do `import lib from "."`, but for writing examples it's a lot more useful to write `import lib from "my-lib-name"`. It would be really nice if Quokka had a support for that, maybe hidden behind a special setting.

**Comment by ArtemGovorov** [comment]
Quokka is extensible and you may do what you want via a [custom plugin](https://quokkajs.com/docs/extensibility.html). 

For example, you may create a [one file plugin](https://quokkajs.com/docs/configuration.html#plugins) with the code below, or create a node module with a single `index.js` (with the code below) file inside [the quokka global folder](https://quokkajs.com/docs/configuration.html#global-config-file), or actually create and [publish the plugin as an npm package](https://quokkajs.com/docs/extensibility.html#plugin-ideas-and-recommendations) and then install it to your Quokka global folder.

**quokka-resolve-root-plugin.js**

```javascript
var Module = require('module');
var path = require('path');
var originalLoad = Module._load;

Module._load = function () {
  if (path.basename(__dirname) === arguments[0]) {
    arguments[0] = '../' + arguments[0];
  }
  return originalLoad.apply(this, arguments);
};
```

Hope it helps.

**Comment by Gozala** [comment]
@ArtemGovorov Thanks for suggestions, I end up publishing a plugin to npm:
https://github.com/Gozala/alias-quokka-plugin

**Comment by ArtemGovorov** [comment]
Awesome, thanks for sharing! I have added the plugin link to [our docs](https://quokkajs.com/docs/configuration.html#community-plugins).
