### ISSUE TITLE
Atom "Create Javascript File" Tree-sitter Grammar

### ISSUE THREAD

**Issue by fcomrqz** [wallabyjs/quokka#680]
### Feature request for Atom Package
When you create a JavaScript file with Quokka. Quokka set the TextMate Grammar. 

**Could Quokka select Tree-sitter Grammar instead?** Please.

One of the reasons I use Atom is because Tree-sitter.
The best code folding and syntax highlight ever. 😁 

I understand that VS Code is priority but please don't forget to give some love to Atom.

**Comment by smcenlly** [comment]
Can you explain why you believe that Quokka is using the TextMate Grammar and not the Tree-sitter Grammar so that we can confirm the behaviour ourselves?

---

When you create a JavaScript or TypeScript file with Quokka, Quokka uses the Atom API [`getGrammars()`](https://github.com/atom/first-mate/blob/v5.1.1/src/grammar-registry.coffee#L58) to find and select the first grammar that matches the file extension (i.e. `.js` or `.ts`).

On a fresh install of Atom, there is only 1 matching grammar for JavaScript returned by the atom API (`source.js`).

If you are getting the same behavior on a fresh/latest installation, then I believe that the Atom team will need to fix this behavior. You should be able to reproduce the issue outside of Quokka by creating a new package with `Package Generator: Generate Package` and then replacing the `toggle()` implementation to:

```javascript
  toggle() {
    const grammars = atom.grammars.getGrammars().filter(g => g.fileTypes.find(f => f === 'js'));
    if (grammars.length !== 1) {
      throw new Error('Too many matching grammars');
    }
    atom.workspace.open('').then(e => {
      e.setGrammar(grammars[0]);
    });
  }
```

If you don't get this behavior on a fresh installation then you may have old packages that need to be removed.

**Comment by fcomrqz** [comment]
I did a clean install and same behavior.

Check these examples,  keyword colors are different.
<img width="970" alt="Screen Shot 2021-09-12 at 11 48 57 p m" src="https://user-images.githubusercontent.com/1501123/133026624-9024ca0a-07c3-436d-aa48-3d7b6fc5139f.png">
It's not colors what I want to solve, I want all the other benefits from Tree-sitter by default without require to change the grammar manually.

**Comment by smcenlly** [comment]
Were you able to try the instructions to reproduce the behavior outside of Quokka? It behaves exactly the same way.

As I said above, you will need to report this to the Atom team as it looks like it's not using the correct Grammar when using their API.

**Comment by fcomrqz** [comment]
I found that you need to pass an object to get Tree-sitter grammars included.

``` js
const grammars = atom.grammars
      .getGrammars({ includeTreeSitter: true })
```

**Comment by smcenlly** [comment]
Oh, nice... will take a look at it now.

**Comment by fcomrqz** [comment]
Thanks to your first message I could understand what is going on.

If Quokka plugin is using `atom.grammars.getGrammars()` you would get all the TextMate grammars.

Atom allows to setup if you prefer Tree-sitter or TextMate grammars, and prefer your custom grammars over pre installed.

To get this working you need to use:
```js
const { grammar } = atom.grammars.selectGrammarWithScore('js' | 'ts')
```

So you don't need to figure out what grammar to use. Only to setup `js` or `ts` file.

I hope you can make the changes. 😅

Thanks for your patience.

**Comment by smcenlly** [comment]
We've released a new version of Quokka for Atom that prefers Tree-Sitter grammars over TextMate. Please update to version `1.0.251` to get the new behavior.

**Comment by fcomrqz** [comment]
It's not working. 😢

I try it with a clean install too.

Is it working for you? Tree-sitter JavaScript Grammar is the bottom example.
<img width="970" alt="Screen Shot 2021-09-12 at 11 48 57 p m" src="https://user-images.githubusercontent.com/1501123/133032097-5d80e7af-faa1-4855-911f-a278920abb46.png">

**Comment by fcomrqz** [comment]
I check your `quokka-atom` package and is still using `getGrammars`, I hope you can switch to `selectGrammarWithScore` to preserve the user preferences. 

> If Quokka plugin is using `atom.grammars.getGrammars()` you would get all the TextMate grammars.
> 
> Atom allows to setup if you prefer Tree-sitter or TextMate grammars, and prefer your custom grammars over pre installed.
> 
> To get this working you need to use:
> 
> ```js
> const { grammar } = atom.grammars.selectGrammarWithScore('js' | 'ts')
> ```
> 
> So you don't need to figure out what grammar to use. Only to setup `js` or `ts` file.

**Comment by smcenlly** [comment]
Thanks for the tip re: `const { grammar } = atom.grammars.selectGrammarWithScore('js' | 'ts')`

We weren't especially keen to use this method as it is not [documented in the atom api](https://flight-manual.atom.io/api/v1.57.0/GrammarRegistry/), but it does appear to work and looks like it has been in place for the last 4 years.

The latest version of Quokka for Atom uses `atom.grammars.selectGrammarWithScore` and falls back to our previous method if there is any error. Please update to version `1.0.252` of Quokka for Atom.
