### ISSUE TITLE
React Mounting a component and creating an instance

### ISSUE THREAD

**Issue by rosshulford** [wallabyjs/quokka#686]
On the latest version I can mount a component and get live comments

`
ReactDOM.render(<Dropdown />, document.getElementById("root"));`

However I am trying (if possible) to create an instance and call a method but the instance is null

`let instance = ReactDOM.render(<Dropdown />, document.getElementById("root"));`

Is this possible?

**Comment by ArtemGovorov** [comment]
Quokka doesn't modify the way React mounts components, so if it's working outside of Quokka, then it should work in Quokka too. Can you please run your code outside of Quokka to see if the `let instance = ReactDOM.render(<Dropdown />, document.getElementById("root"));` code returns a non-null instance? According to the [React docs](https://reactjs.org/docs/react-dom.html#render), `null` is an expected results from the `ReactDOM.render` for stateless components.

**Comment by smcenlly** [comment]
Assuming that the code is running the same way outside of Quokka. Going to close this issue.
