### ISSUE TITLE
Quokka JS for Sublime Text is outdated

### ISSUE THREAD

**Issue by bitsper2nd** [wallabyjs/quokka#687]
Hi, I am writing this because the Quokka version in Package Control is outdated compared to the one in the visual studio market place.

Here is [QuokkaJS](https://packagecontrol.io/packages/Quokka) in Package Control.
![image](https://user-images.githubusercontent.com/22452474/134817203-103b36a9-8afb-4028-b946-60d206efb95a.png)

Here is the version in [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode).
![image](https://user-images.githubusercontent.com/22452474/134817248-9c7d50a6-2a03-4eb9-b46f-a3ae8e6a5fbc.png)

**Comment by ArtemGovorov** [comment]
Quokka is versioned/published differently for different editors, so the differences in version number or release dates are expected. So Quokka for Sublime Text is not outdated, the latest version for Sublime is 1.0.112.
