### ISSUE TITLE
TypeScript support not working in Sublime Text 4

### ISSUE THREAD

**Issue by romanrguez192** [wallabyjs/quokka#688]
### Issue description or question

I installed the Quokka.js package from the package control in Sublime Text 4 but it's working only with JavaScript files. When I search for the `New TypeScript File` option, nothing shows up.

![image](https://user-images.githubusercontent.com/69876913/134992063-02acec82-64c3-49ae-b045-efc5a261cecb.png)

If I open a TypeScript file and use the `Start on Current File` option, the console shows `node: v14.16.0, TypeScript: 3.9.5`, but then if try to I write some code that should work only in JavaScript and not in TypeScript, it doesn't raise any errors.

![image](https://user-images.githubusercontent.com/69876913/134993066-089facd3-89cc-485f-aa21-9edaaa2981e3.png)

How can I make it work with TypeScript then?

### Code editor version

Sublime Text 4 (Build 4113)

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
TypeScript type errors are compile-time errors which are ignored by Quokka (by design). TypeScript can still compile your code with type errors (which it does when using Quokka) and when Quokka runs the compiled code there are no runtime errors.
