### ISSUE TITLE
Run on demand feature

### ISSUE THREAD

**Issue by JakeGinnivan** [wallabyjs/quokka#69]
This is a feature request, when using quokka sometimes you don't want it to be running every time you type. For example when using it to scrape some data from an API etc.

I would love it to be able to run on demand, this would make Quokka a solid javascript LinqPad replacement.

**Comment by ArtemGovorov** [comment]
> For example when using it to scrape some data from an API etc.

Does the current behaviour (of running as you type) make it harder/impossible to accomplish?

**Comment by JakeGinnivan** [comment]
Sorry for not responding @ArtemGovorov 

It is more that I don't want to hit the API every character. Even a delay in a file would be good

**Comment by ArtemGovorov** [comment]
You may use the new Quokka `delay` [configuration](https://quokkajs.com/docs/configuration.html) setting (in ms) in the latest version (1.0.65 in VS Code, 1.0.39 in WebStorm, 1.0.16 in Atom). For example adding this inline config at the start of a Quokka file will result in a 2 second delay between the last edit and running the code:

```javascript
({
  delay: 2000
})
```

**Comment by JakeGinnivan** [comment]
That will do nicely, thanks.
