### ISSUE TITLE
Quokka not run

### ISSUE THREAD

**Issue by whalemare** [wallabyjs/quokka#691]
### Issue description or question

Quokka not run for any snippets that I want to test. 
Example not worked too
Also, when I try to create new Typescript file, window is not opened

### Sample code

```javascript
const quokka = { isAwesome: true };

console.log(quokka); // ?
```

### Quokka.js Console Output

No output from Quokka, no any logs
```
```

### Code editor version

Visual Studio Code v1.60.2 (Commit: 7f6ab5485bbc008386c4386d08766667e155244e)
Quokka version last updated: 06.10.2021, 08:44:04

### OS name and version

macOS 11.2.1 (20D74) Big Sur

**Comment by whalemare** [comment]
https://user-images.githubusercontent.com/9128731/136341871-39878265-a401-4f75-9e17-8c2c7295321c.mp4

**Comment by ArtemGovorov** [comment]
Can you please try:
- uninstall the extension,
- delete all `~/.vscode/extensions/wallabyjs.quokka-vscode-*` subfolders,
- install the extension and try again?

If it doesn't help, please run the `Developer: Toggle Developer Tools` command after attempting to start Quokka with a `Quokka: New File` command and share the output from the Console tab of the dev tools. 

Also try disabling other extensions that you have to see if any of them is affecting Quokka.
