### ISSUE TITLE
Unable config quokka and jshint in the same file

### ISSUE THREAD

**Issue by vanowm** [wallabyjs/quokka#692]
### Issue description or question
jshint can be configured by adding /*jshint */ to the file. 
However quakka inline config requires for the object expression be on top of the file, because of that jshint cannot be properly configured, since some of it's settings must be applied before javascript executable code
### Sample code
main.js
```javascript
({
  "jsdom": {"file": "index.html"}
});
/*jshint esversion:6*/

const test = document.getElementById("test");

test.querySelectorAll(".blah");
```
index.html
```html
<div id="test"></div>
```

### Quokka.js Console Output

```
Quokka 'main.js' (node: v16.11.0, plugins: jsdom-quokka-plugin)​​​​
```

JSHint result:
```
The 'esversion' option cannot be set after any executable code. (E055) [4,1]
Expected an assignment or function call and instead saw an expression. (W030) [3,2]
```
### Code editor version

Visual Studio Code v1.61.0?
Webstorm v?
Atom v1.?

### OS name and version

Windows

### possible solution
Allow comment above config object expression

**Comment by smcenlly** [comment]
Quokka inline configuration **_must_** be at the top of the file. In order to work with `jshint`, you should configure quokka in a [project-level `.quokka` configuration file](https://quokkajs.com/docs/configuration.html#quokka-file-config) instead of using the inline configuration.
