### ISSUE TITLE
Quokka lagging indefinitely with any larger code block

### ISSUE THREAD

**Issue by tristanbrody** [wallabyjs/quokka#693]
### Issue description or question
When I initially start Quokka, it works as expected. But once I've entered anything more than a few lines, it starts to take an indefinite amount of time to load (I can see a [---=--] spinning at the bottom right in VSCode.)

Quokka used to work fine for me, so maybe there is some extension interfering with it?
### Sample code

```javascript
function countZeroes(arr){
    let leftIdx = 0;
    let rightIdx = arr.length - 1;
    let zeroes = -1;
    while(zeroes === -1){
        let middleIdx = Math.floor((leftIdx + rightIdx)/2);
        if(middleIdx === 0 && arr[middleIdx-1] === -1){
            zeroes = arr.splice(0, arr[middleIdx])
        }
    }
    return zeroes;
}

const res = countZeroes([0,0,0,0,1,1]);
console.log(res);
```
I have followed the instructions [here](https://github.com/wallabyjs/quokka/issues/352) to enable debugging in my quokka config file. I also attached a screenshot below of the output in the VS Code developer tools.

![image](https://user-images.githubusercontent.com/62461672/137250003-aa883596-5128-40eb-98d6-803a966caa96.png)

### Code editor version

Visual Studio Code v1.61.0

![image](https://user-images.githubusercontent.com/62461672/137250387-3d45e156-980b-44e7-8fdd-5af2d2ae75b0.png)

### OS name and version

Windows 10.0.19042

**Comment by tristanbrody** [comment]
Thanks!

**Comment by pmermod** [comment]
Thanks for the info. For me the offender was a poorly written loop in my code. Once I closed it properly Quokka came back.
