### ISSUE TITLE
Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/quokka#697]
### Issue description or question

Babel configs when `module = true` seem to not work.

```
Failed to run compilers on quokka.ts, ./tools/quokka/babel.config.js: Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.
    at loadCjsOrMjsDefault (/Users/Vaughan/.quokka/node_modules/.pnpm/@babel+core@7.15.8/node_modules/@babel/core/lib/config/files/module-types.js:67:13)
    at loadCjsOrMjsDefault.next (<anonymous>)
    at readConfigJS (/Users/Vaughan/.quokka/node_modules/.pnpm/@babel+core@7.15.8/node_modules/@babel/core/lib/config/files/configuration.js:215:47)
    at readConfigJS.next (<anonymous>)
```

Either of these as configs don't work.

```
module.exports = api => {
  
}
```

```
export default function() {

  return {}

}

```

**Comment by Burning-Shadow** [comment]
> As you could probably tell, Quokka previously did not support running with **package.json** `type` set to `module`. Previously users who had been running in this mode had never used babel before. We have added support for this in the latest version of Quokka for JetBrains editors (`v1.0.310`).
> 
> Your configuration should look something like:
> 
> **.quokka file**
> 
> ```js
> {
>   "stdEsm": false,
>   "nativeEsm": true,
>   "babel": {
>     "ts": true
>   }
> }
> ```
> 
> **package.json**
> 
> ```js
> {
> ...
>   "type": "module",
> ...
> }
> ```
> 
> **babel.config.js**
> 
> ```js
> export default function() {
>   return {
>     presets: ["@babel/preset-typescript"]
>   };
> }
> ```

i have the same problem but it does not work
(i do not have .quokka but others has been set like yours.)
if u interest of it ,plz search my repository https://github.com/Burning-Shadow/self-vue3/settings, tks
