### ISSUE TITLE
Use @std/esm for ES modules (imports)

### ISSUE THREAD

**Issue by jiku** [wallabyjs/quokka#70]
### Issue description or question

Not sure if you've seen [@std/esm](https://github.com/standard-things/esm). Could help support ES modules (imports)?

### References

* [standard-things/esm](https://github.com/standard-things/esm)
* [ES Modules in Node Today!](https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b)
* [benjamn/reify](https://github.com/benjamn/reify)
* [Reify: Meteor’s evolving JavaScript module compiler](https://blog.meteor.com/reify-meteors-evolving-javascript-module-compiler-70425fa45d81)

**Comment by ArtemGovorov** [comment]
The [feature is implemented](https://medium.com/@artem.govorov/es-modules-support-in-quokka-by-default-5a0b18256194) in the latest Quokka version.
