### ISSUE TITLE
getBoundingClientRect returning 0 for all properties, but browser console returning correct values

### ISSUE THREAD

**Issue by christianboyle** [wallabyjs/quokka#702]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?:
Yes

--

This test case is set up according to the docs: https://quokkajs.com/docs/configuration.html#loading-from-html-file-example

The basic plugin interaction between the files works, you can see the div is set to `red` in `test.html` via inline style, but then changed to `blue` via `script.js` (can verify by checking the value of `testDiv.style.backgroundColor` with Quokka before it is set to `blue`).

That's good, but when you try to `getBoundingClientRect()` Quokka is always returning `0` for all properties on the object for both logs:
![2021-10-23_11-26-37AM](https://user-images.githubusercontent.com/1605754/138564213-4c30267f-8fbd-4ca9-9eb1-32bee904f83b.png)

But the browser console is returning the correct values for both logs:
![2021-10-23_11-25-18AM](https://user-images.githubusercontent.com/1605754/138564165-b48c40d9-2897-42da-a692-e019ec239955.png)

### Sample code

`script.js`
```javascript
({
  plugins: ['jsdom-quokka-plugin'],
  jsdom: { file: 'test.html' },
});

const testDiv = document.getElementById('testDiv');

console.log(testDiv.getBoundingClientRect());

testDiv.style.backgroundColor = 'blue';
testDiv.style.position = 'absolute';
testDiv.style.top = 200 + 'px';
testDiv.style.left = 300 + 'px';

console.log(testDiv.getBoundingClientRect());
```

`test.html`
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body style="height: 100vh; margin: 0;">

  <div id="testDiv" style="height: 200px; width: 200px; background: red;">
    test
  </div>

  <script src="script.js"></script>
</body>

</html>
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
{ x: 0,
  y: 0,
  bottom: 0,
  height: 0,
  left: 0,
  right: 0,
  top: 0,
  width: 0 }
  ​​​​​at ​​​​​​​​testDiv.getBoundingClientRect()​​​ ​script.js:8:0​

{ x: 0,
  y: 0,
  bottom: 0,
  height: 0,
  left: 0,
  right: 0,
  top: 0,
  width: 0 }
  ​​​​​at ​​​​​​​​testDiv.getBoundingClientRect()​​​ ​script.js:15:0
```

### Code editor version

Visual Studio Code v1.61.2

### OS name and version

Windows Version 10.0.19043 Build 19043
WSL Version 1

**Comment by smcenlly** [comment]
Thanks for the detailed issue report. This behavior is expected.

Quokka [runs your code in `node.js`](https://quokkajs.com/docs/how-does-it-work.html) and uses [JSDOM](https://github.com/jsdom/jsdom) to provide a browser-like environment. JSDOM doesn't do any rendering, so getBoundingClientRect() always returns 0,0,0,0.

**Comment by christianboyle** [comment]
@smcenlly Ah, interesting. Thanks for the explanation!
