### ISSUE TITLE
Issue while running typescript files with node 16.12+

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/quokka#709]
### Issue description or question
I am unable to run typescript files with node `16.12+`. They work when I downgrade my node to `16.11`

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

Here's the screenshot of errors that are displayed. This are `src/test.ts` file

![image](https://user-images.githubusercontent.com/79074469/140598792-03ac3b29-bd6d-40c4-b809-8a6a7ab9eba5.png)
![image](https://user-images.githubusercontent.com/79074469/140598796-b160b645-7572-4e57-9333-26ac4e607ac6.png)

### Code editor version
```
 System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 128.78 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.12.0 - ~/Library/pnpm/node
    npm: 8.1.0 - ~/Library/pnpm/npm
  IDEs:
    IntelliJ: 2021.2.3
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This was related to a recent breaking change to node's ECMAScript modules API. It is fixed in the latest version of Quokka for IntelliJ (`v1.0.314`).
