### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by MarcosRava** [wallabyjs/quokka#712]
### Cannot find module In NestJS typescript project

If you start a simple [nestjs](https://docs.nestjs.com/first-steps) project

```bash
$ npm i -g @nestjs/cli
$ nest new project-name
```
 and use absolute path from root project dir 
```js
import { AppModule } from 'src/app.module'
``` 
instead of relative 
```js
import { AppModule } from './app.module'
```
 in any file, the project works, the tests works, the build works, but quokka fail with this output

### Quokka.js Console Output

```

Cannot find module 'src/module/insurance/dto/personal-information.dto' 
Require stack: 
- ./test/mock/personal-information.dto.mock.js 
  ​​​​​at ​​​​​​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:815​
  ​​​​​at ​​​​​​​​Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename]​​​ ​./node_modules/@cspotcode/source-map-support/source-map-support.js:679​
  ​​​​​at ​​​​​​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:667​
  ​​​​​at ​​​​​​​​require​​​ ​internal/modules/cjs/helpers.js:74​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​test/mock/personal-information.dto.mock.ts:2​
  ​​​​​at ​​​​​​​​Module._compile​​​ ​internal/modules/cjs/loader.js:999​

```

### Code editor version

Visual Studio Code 1.62.1 (Universal)

### OS name and version
OSX Monterey version 12.0.1

**Comment by smcenlly** [comment]
When Quokka runs your code, it runs in `node.js`, first compiling your file with TypeScript, and then using `ts-node` to import any dependencies. You should get the same behavior if you were to compile your project using TypeScript and then running `node filename.js` or using `ts-node` with `ts-node filename.ts`.

We created a fresh `nestjs` project and tried changing the imports as you have above and had the same issue outside of Quokka with `jest` tests (see below).

![image](https://user-images.githubusercontent.com/2074089/141386499-724301ee-62ee-4a74-903f-b173d8426096.png)

Is there some special configuration that you have applied to your project (e.g. jest configuration or build configuration) that is mapping the imports when you refer to them with absolute path? If so, you'll need to ensure the same is configured for Quokka (e.g. with tsconfig `paths`).

If this doesn't help you solve your problem, can you please share your `tsconfig.json` files?

**Comment by MarcosRava** [comment]
Thanks for response

About jest, I used 
```

    "moduleDirectories": [
      "./",
      "node_modules"
    ],
```
to run tests with jest, Wallaby works fine, just quokka breaks

if you run  `nest build --webpack` then `node dist/main.js` it works

**Comment by MarcosRava** [comment]
To solve this problema for the moment, I inserted alias `src` on `path`  in `tsconfig.json`
```json

    "paths": {
      "src": ["src"]
    },
```

Seems ok until now

**Comment by smcenlly** [comment]
I think for a default TypeScript project, you need the `tsconfig.json` modifications. I expect that `nest` build is doing something special for you. Since it's working for you now, I'll close the issue.
