### ISSUE TITLE
loading time

### ISSUE THREAD

**Issue by surya-p-s** [wallabyjs/quokka#714]
Issue Type: <b>Bug</b>

Quokka is taking too much time to get loaded and start working.

Extension version: 1.0.419
VS Code version: Code 1.62.2 (3a6960b964327f0e3882ce18fcebd07ed191b316, 2021-11-11T20:56:38.428Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G    (2 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.97GB free)|
|Process Argv|--crash-reporter-id bdf64beb-f7ba-46f5-8485-5a3b1412d996|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by smcenlly** [comment]
Could you please provide some additional details? Is this happening when your editor loads? Or when you start Quokka?

**Comment by surya-p-s** [comment]
When I start Quokka.
It is taking too much time I make new javascript file using it but it's loading.

**Comment by smcenlly** [comment]
Can you please describe what command you are using (e.g. creating a new TypeScript/JavaScript file) and how long it is taking? e.g. 1 second, 2 seconds? etc.

Can you also please share the code that you are using?

**Comment by surya-p-s** [comment]
https://user-images.githubusercontent.com/93700062/141881103-fd9dba59-e37b-4165-b3ed-ba987729912b.mp4

see this sir no output is coming for this simple code also. And seeing status bar it's loading the quokka but not loaded after 30 mins also.

**Comment by smcenlly** [comment]
Thanks for the video demonstration. Can you please run the VS Code `Developer: Toggle Developer Tools` command and inspect the console and provide us with the output? We're looking for any errors.

Could you also please confirm that you have `node.js` installed on your system and provide us with the results of running `node --version` from the terminal in VS Code?

**Comment by surya-p-s** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/93700062/141923603-ba6f372c-2c27-4036-b675-489cd2782c1a.png)
yes, I have node.js installed on my system

**Comment by surya-p-s** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/93700062/141924483-b4281eab-befc-4c39-ba9e-89926f03c13f.png)
![Screenshot (21)](https://user-images.githubusercontent.com/93700062/141924491-799d975e-ffe5-451c-97b2-c97d734517f2.png)

**Comment by surya-p-s** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/93700062/141925473-c4e0116b-8d20-46bf-bcc8-3be5a7e07e3e.png)

**Comment by ArtemGovorov** [comment]
It doesn't look like the issue is Quokka specific. As you can see in the DevTools, other extensions are also failing to load (Unresponsive warnings). The console indicates that Debugger is attached to your extension host, meaning that you run your VS Code to debug some extension. I suggest to try running VS Code without attaching debugger to extension host to see if it helps to run Quokka and other extensions.

**Comment by surya-p-s** [comment]
but other extensions are working properly and in Quokka initializing of JS/TS is not getting completed.

**Comment by ArtemGovorov** [comment]
Can you try running VS Code without attaching debugger to extension host to see if it helps?

**Comment by surya-p-s** [comment]
not working even when run without debugger and I am not getting run type output.

**Comment by surya-p-s** [comment]
not getting run time output

**Comment by ArtemGovorov** [comment]
Can you please share a recording of the behaviour (without attaching debugger to extension host) including Dev Tools console output?

**Comment by surya-p-s** [comment]
please tell me how to do that I am not getting it.

**Comment by ArtemGovorov** [comment]
Please share a recording (like [this one](https://github.com/wallabyjs/quokka/issues/714#issuecomment-969663833)) of the reported behaviour, but without attaching debugger to extension host, and while recording please run the VS Code `Developer: Toggle Developer Tools` command and open the console so the output is visible.

**Comment by surya-p-s** [comment]
how to de attach debugger from extension host

**Comment by ArtemGovorov** [comment]
> how to de attach debugger from extension host

You have [mentioned here](https://github.com/wallabyjs/quokka/issues/714#issuecomment-969881730):

> not working even when run without debugger and I am not getting run type output.

that you have tried to "run without debugger". Please do it again and share a recording of the reported behaviour (including opened Dev Tools console).

Please also try specifying your node.exe path in Quokka settings as described here https://quokkajs.com/docs/configuration.html#nodejs-version to see if it changes anything.

**Comment by surya-p-s** [comment]
> > how to de attach debugger from extension host
> 
> You have [mentioned here](https://github.com/wallabyjs/quokka/issues/714#issuecomment-969881730):
> 
> > not working even when run without debugger and I am not getting run type output.
> 
> that you have tried to "run without debugger". Please do it again and share a recording of the reported behaviour (including opened Dev Tools console).
> 
> Please also try specifying your node.exe path in Quokka settings as described here https://quokkajs.com/docs/configuration.html#nodejs-version to see if it changes anything
I have done that by using command run without debugger.
And I a beginner and I don't know how to run host without attaching debugger please tell me hoew to do that

**Comment by surya-p-s** [comment]
I have done that by using command run without debugger.
And I a beginner and I don't know how to run host without attaching debugger please tell me hoew to do that

**Comment by surya-p-s** [comment]
[Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.

I am getting this message in console how to fix it.

**Comment by ArtemGovorov** [comment]
> And I a beginner and I don't know how to run host without attaching debugger please tell me hoew to do that

When you simply start new VS Code instance from the scratch, it should not attach debugger to extension host (like it does in your case for some reason that is unknown to me). 

> [Extension Host] Quokka.js Live Share integration disabled, VSLS not found.

This message is expected and doesn't need any fix.

**Comment by surya-p-s** [comment]
So what should I do next because quokka is not displaying real time output.

**Comment by ArtemGovorov** [comment]
I would recommend you to investigate why in your case debugger is attached to extension host when you start your VS Code, because it may be the reason why the extension doesn't work. I don't have any specific advice on how to do it, because it's working for me and my team as expected, we also have not heard from any other users about the issue like this one, so the issue is likely related to your environment. One thing to try may be to run Quokka on a different machine to see if it's working as expected for you.

**Comment by surya-p-s** [comment]
https://github.com/wallabyjs/quokka/issues/381#issue-453891005

I am getting this type of issue

**Comment by ArtemGovorov** [comment]
> https://github.com/wallabyjs/quokka/issues/381#issue-453891005

As you can from the comments, that issue was fixed by the user by using a different version of node.js. You may try the same, but I think your issue is different and related to some other things in your environment.

**Comment by surya-p-s** [comment]
I am not able to find config.json  for Quokka

**Comment by ArtemGovorov** [comment]
The location of the config is described in our docs at https://quokkajs.com/docs/configuration.html#global-config-file. If the file is missing, you may try to create in the documented location.

**Comment by surya-p-s** [comment]
It's working now thank you
