### ISSUE TITLE
VS Code User Settings > "editor.wordWrap": "on" not respected

### ISSUE THREAD

**Issue by emveeoh** [wallabyjs/quokka#72]
VS Code > User Settings   = "editor.wordWrap": "on"

  // Controls how lines should wrap. Can be:
  //  - 'off' (disable wrapping),
  //  - 'on' (viewport wrapping),
  //  - 'wordWrapColumn' (wrap at `editor.wordWrapColumn`) or
  //  - 'bounded' (wrap at minimum of viewport and `editor.wordWrapColumn`).

Any output generated by Quokka in the viewport should respect this global VS Code setting and wrap any output accordingly. Wrapping should respect dynamic viewport resizing. 

My array output is long and goes beyond the right border of the viewport. Ideally, it would wrap according to the global VS Code "editor.wordWrap" user setting.

Visual Studio Code v1.? 1.15.0 (1.15.0)
OSX

Sorry to complain about such a small thing... Thanks for such a great tool!   :)

**Comment by ArtemGovorov** [comment]
Unfortunately this behaviour is not under control of VS Code plugins. Quokka output is not a real text in the editor that respects `editor.wordWrap` setting, it is a decoration for the line, and in VS Code line decorations are not treated the same ways as lines for the purpose of text wrapping.

**Comment by emveeoh** [comment]
Bummer... lol... thanks for the consideration.

**Comment by karlhorky** [comment]
Looks like this problem is being tracked in VS Code here: https://github.com/microsoft/vscode/issues/32856

**Comment by karlhorky** [comment]
Actually, would it be possible to completely disable the scroll like the `gitlens.currentLine.scrollable` option implemented at the link below?

https://github.com/eamodio/vscode-gitlens/blob/30e1d290e8f337d56596a030ff097eeabdd98eb7/src/annotations/annotations.ts#L355-L356
