### ISSUE TITLE
Issue with tsconfig paths React / Typescript Projects (i.e. Remix Run / NX React)

### ISSUE THREAD

**Issue by jaruesink** [wallabyjs/quokka#725]
### Issue description or question

I'm running into issues where tsconfig paths aren't working for these modern typescript projects. In this example (Remix Run).

global quokka config

```
{
  "autoLog": true,
  "showSingleInlineValue": false,
  "pro": true,
  "plugins": ["jsdom-quokka-plugin", "alias-quokka-plugin"],
  "node": "/Users/jake/.nvm/versions/node/v16.13.0/bin/node"
}
```

local .quokka file (trying to add an alias
```
{
  "alias": {
    "~": "./app"
  }
}

```

### Sample code

![image](https://user-images.githubusercontent.com/4207065/143669388-9bdc0f45-20ef-47f5-bd98-e75f96b5b07e.png)

### Sample repository link

https://remix.run/

### Quokka.js Console Output

```
​​​​​Quokka PRO 'root.tsx' (node: v16.13.0, TypeScript: v4.5.2, plugins: alias-quokka-plugin, jsdom-quokka-plugin)​​​​
 
Cannot find module '~/styles/global.css' 
Require stack: 
- ./app/root.js 
  ​​​​​at ​​​​​​​​Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename]​​​ ​/Users/jake/.quokka/node_modules/@cspotcode/source-map-support/source-map-support.js:679​
  ​​​​​at ​​​​​​​​Function.Module._load​​​ ​/Users/jake/.quokka/node_modules/alias-quokka-plugin/src/main.js:13​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​app/root.tsx:13:0​

remix ​​​​​at ​​​​​​app/root.tsx:158:2​
```

### Code editor version

Visual Studio Code v1.62.3

### OS name and version

OSX Latest

**Comment by smcenlly** [comment]
The error that you're receiving appears to be related to loading `.css` files and not so much about the Typescript `paths` or `alias`.

Quokka does not natively support remix projects so you will need to apply configuration to get it working. We recommend first reading about [how quokka works](https://quokkajs.com/docs/how-does-it-work.html).

By default, Quokka will use TypeScript to compile your TypeScript files and any project-level imports. In your case, you are importing a `css` file, which TypeScript doesn't know how to execute or compile. If you use [`ts-node`](https://github.com/TypeStrong/ts-node) from the command line, which is similar to Quokka in that it compiles with TypeScript and runs your code in `node` then you will see that you get a similar problem.

We're not familiar with Remix as a framework, but looking at their code, it appears that they are using [`esbuild`](https://github.com/evanw/esbuild) with some custom loaders to handle importing `css` files, and the expected runtime environment for Remix is also the browser. Quokka does not currently support `esbuild` as a compiler and runs your code in `node` (not the browser).

In addition to the native TypeScript compiler, Quokka also allows you to compile TypeScript using [babel](https://babeljs.io). I'm not sure the level of effort involved (as we don't know what Remix is doing under the covers), but to get this working, I would suggest trying a babel configuration that transforms your typescript and ignores css imports. Relevant links below:

* [How to configure Quokka to use babel for TypeScript files](https://quokkajs.com/docs/configuration.html#using-babel-to-compile-typescript)
* [Using babel to compile TypeScript](https://babeljs.io/docs/en/babel-preset-typescript)
* [Babel plugin to ignore html and css imports](https://www.npmjs.com/package/babel-plugin-ignore-html-and-css-imports)

If you create a working babel configuration for your project, please let us know.
