### ISSUE TITLE
Fails when using baseUrl in Typescript

### ISSUE THREAD

**Issue by jhasselgren** [wallabyjs/quokka#727]
### Issue description or question

Hi, I cannot get quokka to work with a typescript project that is configured with baseUrl.

Works when running 
```
ts-node -r tsconfig-paths/register src/quokka.ts
```

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample repository link
https://github.com/jhasselgren/quokka-typescript-import-sample

### Quokka.js Console Output

```
​​​​​Quokka PRO 'quokka.ts' (node: v14.18.1, TypeScript: v4.4.3)​​​​
 
Cannot find module 'module/myModule' 
Require stack: 
- ./src/quokka.js 
  ​​​​​at ​​​​​​​​Function.Module._resolveFilename​​​ ​internal/modules/cjs/loader.js:902​
  ​​​​​at ​​​​​​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:746​
  ​​​​​at ​​​​​​​​require​​​ ​internal/modules/cjs/helpers.js:93​
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​src/quokka.ts:5​
  ​​​​​at ​​​​​​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1085​
```

### Code editor version
Visual Studio Code Version: 1.62.3

### OS name and version
OSX Big Sur

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Quokka for VS Code, `v1.0.429`.
