### ISSUE TITLE
Can not start node.js process (WebStorm)

### ISSUE THREAD

**Issue by park53kr** [wallabyjs/quokka#73]
### Issue description or question
Hi. I just installed 'Quokka' from WebStrom plugin dialog and tried to use it. But 'Can not start node.js process' error came out. I've already installed node (/usr/local/bin/node), and also run the any javascript code. I don't know why quokka can't find node process... Could you give me a idea to solve this problem?

### Quokka.js Console Output

```
Can not start node.js process
You may use the "node" setting to configure the location of node.
```

### Code editor version
WebStorm 2017.2.1
Build #WS-172.3544.34, built on July 31, 2017

### OS name and version
Mac OS X 10.12.6

**Comment by ArtemGovorov** [comment]
As the error message suggests, try [using the `node` setting in your quokka config](https://quokkajs.com/docs/configuration.html#nodejs-version) to point it to your node.
