### ISSUE TITLE
Quokka on PWA studio (MAGENTO/REACT)

### ISSUE THREAD

**Issue by RihardsEdels** [wallabyjs/quokka#731]
Hi guys, I have been a happy user of quokka for a while, mainly in react.
A the moment working on Magento PWA Studio, which is React based but cant figure out how to setup Quokka correctly

console returns usual unconfigured React message:
./src/components/Helloworld/HelloWorld.js:6 
        <div> 
        ^ 
 
SyntaxError: Invalid or unexpected token 
    at new Promise (<anonymous>)

**Comment by smcenlly** [comment]
We're not familiar with Magento PWA Studio. If your project uses `create-react-app`, Quokka will automatically configure itself to support react. It sounds like this may not be the case with Magento, in which case you will need to create a [Quokka configuration](https://quokkajs.com/docs/configuration.html) to support react:

**.quokka configuration**
```json
{
  "plugins": ["jsdom-quokka-plugin"],
  "babel": {
    "presets": ["react-app"]
  }
}
```
