### ISSUE TITLE
Quokka stopped working with VSCode Insiders

### ISSUE THREAD

**Issue by asampal** [wallabyjs/quokka#732]
### Issue description or question

Since some time last week, I can't run Quokka from VSCode insiders. My Jetbrains Idea Ultimate install of Quokka is still working though.

Invoking any  command the extension exposes pops up a dialog (after some delay) mentioning that the command is not found.

I've fully uninstalled/re-installed the extension (including .quokka settings folder), but to no avail.

![image](https://user-images.githubusercontent.com/281639/145870681-3e0b0360-0d19-4c58-a866-429388d3593e.png)

### Quokka.js Console Output

There doesn't seem to be any Quokka console output.
The extension is version 1.0.432

### Code editor version

Version: 1.64.0-insider (user setup)
Commit: 065b450db9f555f177161748e8f2911ebb5677f9
Date: 2021-12-10T05:14:44.789Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by smcenlly** [comment]
We have tested a fresh Quokka install on the latest VS Code Insiders and it appears to be working for us.

Could you please share the output of VS Code developer tools console (using the `Developer: Toggle Developer Tools` command) after restarting VS Code Insiders, and then trying to start Quokka?

**Comment by asampal** [comment]
It doesn't look like any output related to Quokka is emitted when trying to set the license or attempting to run once for a JS file
[vscode-app-1639439012280.log](https://github.com/wallabyjs/quokka/files/7707610/vscode-app-1639439012280.log)
.

**Comment by ArtemGovorov** [comment]
Can you please try this:
- uninstall Quokka,
- close all VS Code instances,
- delete all folders `wallabyjs.quokka-vscode-*` folders in `~/.vscode/extensions/`,
- start VS Code
- install and try Quokka?

**Comment by asampal** [comment]
Same result, unfortunately
![image](https://user-images.githubusercontent.com/281639/145910727-3aefc29f-2c6c-4044-9b3f-1240ef9712b2.png)

Could it be the type of Insiders installation I'm using? i.e. the system installation rather than the user one - https://code.visualstudio.com/insiders/

**Comment by smcenlly** [comment]
It looks like there are some errors in your log with other extensions. Perhaps this is causing Quokka to never load.

Can you please try renaming your VS Code Insider's `extensions` (`~/.vscode-insiders/extensions`), for example, change it to `extensions-old`. Then restart VS Code (at this point you'll have no extensions installed at all) and then re-install ONLY Quokka.

If that works for you, you can then try and isolate which extensions are causing the others to fail.

**Comment by asampal** [comment]
That does work. I'll try to determine the interfering extension.

**Comment by smcenlly** [comment]
We identified that the problem was with Microsoft's VS Code Live Share Extension.

As of this morning, we have tested the latest version of VS Code (stable) and VS Code Insiders, and everything appears to be working.

If you're still having the problem, can you please ensure that you have the latest VS Code version. If you are having a problem with the latest VS Code version, please provide your VS Code version/operating system details below.

**Comment by smcenlly** [comment]
Our problem with Live Share was caused by a promise that failed to resolve/reject. We have updated our integration with Live Share to be tolerant of this.

Please try updating to the latest version of Quokka for VS Code, `v1.0.436`. We believe this will resolve your problem.

**Comment by asampal** [comment]
Quokka again has stopped working for me. I tried disabling Live Share, but that didn't change anything (not that I expected much since you addressed the issue with that particular extension).

I don't see anything in the Quokka Output tab, but I do see the "processing" indicator moving once I invoke Quokka to run once for the file.
![image](https://user-images.githubusercontent.com/281639/161085489-af7be5b7-c07f-44d8-acdc-55ffe38dd33e.png)

**Comment by asampal** [comment]
As I mentioned it's minimal, for example:
```javascript
a = 2 //?
```

**Comment by smcenlly** [comment]
@asampal - sorry for the slow reply on this. Did you manage to get it working? Can you please try:

1. VS Code Stable build
2. VS Code Insiders build

Do you have the same problem in both?

If you only have the problem in one build, can you please uninstall VS Code (and Quokka) and reinstall both to see if you still have the same problem?

Can you also please try disabling all extensions EXCEPT for Quokka to see if it's working for you?

Finally, if none of that helps, can you please try a different node version to see if that helps?

**Comment by EichSoderland** [comment]
I'm having the same issue
I tried:
- delete quokka files in extensions folder and re installing
- disabling all extension but it doesn't work
- in extensions folder deleted everything except quokka
Still doesn't work

**Comment by smcenlly** [comment]
@EichSoderland - could you please provide answers to the following questions:

1. What is your operating system? Please run the VS Code `Help: About` command and copy/paste the output to this issue. 
2. How did you install **VS Code** and **Node.js**?
3. If you are using VS Code stable, does Quokka work with the [insider's version](https://code.visualstudio.com/insiders/)?
4. If you are using VS Code insiders, does Quokka work with the [stable version](https://code.visualstudio.com)?
5. If you run the VS Code command, `Developer: Toggle Developer Tools` and navigate to the `Console` tab, are there any logs reported? Can you please screenshot or copy/paste them to this issue?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Hope you got it working.
