### ISSUE TITLE
Profile in Chrome does not start

### ISSUE THREAD

**Issue by Filyus** [wallabyjs/quokka#735]
### Issue description or question
Chrome opens the "about:blank" page instead of a dev tab. It seems that the browser opens the console and then immediately closes it.

### Sample code
Most any code is not runs. Something very random here.
```javascript
let a = 1;
console.log(a);
```

### Quokka.js Console Output

```
No errors or warnings in any console
```

### Code editor version

Visual Studio Code v1.63.2

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Can you please share your Google Chrome version?

**Comment by Filyus** [comment]
> Can you please share your Google Chrome version?

Chrome 96.0.4664.110

**Comment by ArtemGovorov** [comment]
The same version of chrome is working as expected for us. Can you please try again and once the "about:blank" page shows up, can you open Dev Tools on the page and check if there are any errors reported in the console tab?

**Comment by Filyus** [comment]
There nothing.

**Comment by Filyus** [comment]
Perhaps there is something wrong with the Node version?

`​​​​​Quokka PRO 'Untitled-1.js' (node: v16.13.1)​​​​`

**Comment by ArtemGovorov** [comment]
Does opening profile in VS Code (as opposed to Chrome) work for you?

**Comment by Filyus** [comment]
Yes.

**Comment by ArtemGovorov** [comment]
It then should not be related to your node version, rather some Chrome specific or environment specific settings. When you open profile in Chrome, does it open Chrome 96.0.4664.110 version, or some other Chrome version (such as Chrome Canary).

**Comment by Filyus** [comment]
Only Chrome 96.0.4664.110 opens. I have no other versions installed.

**Comment by ArtemGovorov** [comment]
We have tried it in Chrome 96.0.4664.110 on Windows 10, but it's working as expected for us, so the issue doesn't seem to be Chrome/OS version specific either. It looks like there may be something in your environment that prevents Chrome from opening the recorded profile. Is there any way you can test the feature on a different machine to see if it's working there?

**Comment by Filyus** [comment]
The same situation on another computer. I realized that there is a problem with another extension for VS Code, which prevents it from working. I'll write when I find the guilty extension.

**Comment by Filyus** [comment]
On one computer I managed to make it work. On another computer, I tried to do the same, but without success.
(I turned off, then turned on all the extension in VS Code one by one)

All settings are in sync, so I don't know what to do.

**Comment by Filyus** [comment]
I tried running clean Visual Studio Code Insiders, but it still has a 50% chance of opening "about: blank".

**Comment by Filyus** [comment]
Now everything is working, but why I still did not understand, maybe after restarting the computer. As soon as I know more, I will write here.

**Comment by smcenlly** [comment]
Glad to hear that it's now working for you. I'm going to close this issue but if you have problems again, we will re-open the issue if you reply to it.
