### ISSUE TITLE
Will you make a version of Quokka for VIM/NeoVim?

### ISSUE THREAD

**Issue by Dennys04** [wallabyjs/quokka#736]
Good evening, a pleasure first of all. Don't you plan to do QUOKKA for vim/Nvim? Because the tool is very useful for testing with some scripts and is very helpful to practice Javascript, without having to have a .html

**Comment by ArtemGovorov** [comment]
Hi, we don't have any close plans to make Quokka version for Vim.

**Comment by dan-peterson** [comment]
@ArtemGovorov with the API's exposed by neovim this should be fairly trivial to implement. Not sure why you wouldn't support as many editors as possible?

**Comment by smcenlly** [comment]
@dan-peterson - we're familiar with the APIs but didn't believe the integration would be trivial. Are you experienced creating neovim plugins? If so, we'd appreciate any pointers as to how the task is trivial that we may be missing (as well as samples of the key parts of implementation we would need); please email hello@wallabyjs.com with any relevant details.

**Comment by dan-peterson** [comment]
@smcenlly sure thing. I just emailed you.

**Comment by dan-peterson** [comment]
Hi @smcenlly, just a quick update: As much as I love and will continue to use Quokka, I was thinking about it recently and I really need more control and want additional features that would be outside of the scope of Quokka. (Including support for more languages)

So I've started an open source prototyping tool. [lab.nvim](https://github.com/0x100101/lab.nvim). Currently there's cross-over in terms of functionality, but I imagine over time the two will diverge quite significantly in terms of features.

Thought I'd give you a heads up, as there might be some lua code there that would be a useful reference should the team decide to create a neovim port of Quokka.

**Comment by smcenlly** [comment]
@dan-peterson - Thanks! Neovim support is on our roadmap so this will be helpful. Thank you!

**Comment by mikeduminy** [comment]
@smcenlly that's awesome news! Do you have any rough estimate for this?

**Comment by smcenlly** [comment]
> @smcenlly that's awesome news! Do you have any rough estimate for this?

Nothing that we can share right now.

**Comment by Shubham29012001** [comment]
@smcenlly More than a year. Please let us know if the vim/neovim is still on target. There are lots of people using nvim and for javascript developers, quokka has become one of the crucial tools for testing prototypes.

**Comment by smcenlly** [comment]
Yes, we still have vim/neovim on our radar, but it is not on our short-term roadmap.

**Comment by Dartv** [comment]
Any news on neovim support?

**Comment by smcenlly** [comment]
We don't have any short-term plans to make a Quokka version for Vim.
