### ISSUE TITLE
Quokka not working with Angular 4

### ISSUE THREAD

**Issue by musti2** [wallabyjs/quokka#74]
I just installed Quokka plugin and I can't seem to get it to work with my .ts files.

It will log / show me results before the @Component decorator but nothing inside the component.. hope that makes sense.

My component looks like this:

```javascript

console.log('123') <-- quokka works here.

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-somecomponent-view',
  templateUrl: 'some.component.html'
})
export class ComponentName implements OnInit {

  someArray = [
    { prop: 'Name' }
  ]

  constructor() { }

  ngOnInit() {
     console.log('123') <--- i expect quokka to show me the value here, instead, it doesn't.
  }
}
```

### Quokka.js Console Output
```
​​​​Quokka #1 (node: v6.11.0, TypeScript: v2.4.0)​​​​
​​​​
​​reflect-metadata shim is required when using class decorators​​
```

### Code editor version

Visual Studio Code v1.15

### OS name and version
OSX Seirra

**Comment by ArtemGovorov** [comment]
Quokka executes the code in your file. Nothing in your file calls `ngOnInit`, so it is expected that the code inside the function is not executed.

**Comment by daggett206** [comment]
@ArtemGovorov , what are your recommendations for work with angular? we can't manually call any of components/services/etc. because of dependency injection. mb there is a way to run quokka on a whole angular project at the same time?

**Comment by ArtemGovorov** [comment]
@daggett206 Quokka runs on a file basis, it just runs code in any given file. So if there's nothing in the file is using the exported component/service, then it'll obviously not run. You can write some code that constructs a component/service (maybe in a way your unit tests for the service/component would do it), and Quokka should be able to run the code. 

Here is how [wallaby](https://wallabyjs.com/) runs Angular unit tests in the [Angular CLI generated project](https://github.com/wallabyjs/ngCliWebpackSample/):

![wallaby](https://user-images.githubusercontent.com/979966/31060520-b32a1dbc-a758-11e7-8e18-5c48d7206751.gif)

It's not the same as Quokka though, Wallaby runs the whole project's code (whatever is reachable from unit tests).

Maybe you could [configure](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/app/app.component.spec.ts#L5) and use Angular [TestBed](https://angular.io/api/core/testing/TestBed) in your Quokka file to create a component/service?

**Comment by daggett206** [comment]
@ArtemGovorov thanks for answering, I definitely try your suggestion

**Comment by blasyaselli** [comment]
@daggett206 did it work for you?
