### ISSUE TITLE
Getting SyntaxError from quokka when Promises are involved

### ISSUE THREAD

**Issue by juni0r** [wallabyjs/quokka#740]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
import { unified } from 'unified'
import rehypeParse from 'rehype-parse'
import rehypeStringify from 'rehype-stringify'
import rehypeSanitize from 'rehype-sanitize'

export const processor = unified()
  .use(rehypeParse)
  .use(rehypeSanitize)
  .use(rehypeStringify)

export default async function sanitize(string) {
  return await processor.process(string)
}

const doc = '<html-blob><u></u><u></u><b>Test</b>.<u></u><u></u></html-blob>'

const result = await sanitize(doc)

console.log(result.value)
```

### Sample repository link

https://github.com/juni0r/quokka-promise

### Quokka.js Console Output

```
​​​​​Quokka PRO 'index.js' (node: v16.13.1)​​​​
 
[wallaby core]/runners/node/quokka@1.0.0/initializer.js:12 
 * and very harmful for the tool and its future. 
                                  ^ 
 
SyntaxError:  
    at new Promise (<anonymous>) 
```

### Code editor version

Visual Studio Code v1.63.2

### OS name and version

OSX 11.6.2

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. Your repo is using native node ESM (`type: module`), so Quokka [default `esm` module](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await) needs to be overwritten.

I have sent you the PR with the working Quokka config: https://github.com/juni0r/quokka-promise/pull/1 (you may put the config to [your package.json](https://quokkajs.com/docs/configuration.html#packagejson-config) if you prefer to).
