### ISSUE TITLE
Results don't show in module.exports

### ISSUE THREAD

**Issue by sleeplesskyru** [wallabyjs/quokka#741]
### Issue description or question
Quokka stops showing live results in the editor after `module.exports`.

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
const test = 'This is a test';

console.log(test); //Output shows here

module.exports = () => {
    return console.log(test); //Output does not show here
};
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.js' (node: v16.6.1, babel: v6.26.3)​​​​

This is a test ​​​​​at ​​​​​​​​test​​​ ​quokka.js:3:1​
```

### Code editor version

Visual Studio Code v1.63.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
The [result is expected](https://quokkajs.com/docs/how-does-it-work.html). Quokka execute your code, using the file as the entry-point for your program (the same way as if you would run `node Untitled-1.js`). So if the file executes some functions, Quokka will run them, otherwise not. To make Quokka execute anything, you may simply call it:

```diff
const test = 'This is a test';

console.log(test); //Output shows here

module.exports = () => {
    return console.log(test); //Output does not show here
};

+module.exports(); 
```

**Comment by sleeplesskyru** [comment]
> The [result is expected](https://quokkajs.com/docs/how-does-it-work.html). Quokka execute your code, using the file as the entry-point for your program (the same way as if you would run `node Untitled-1.js`). So if the file executes some functions, Quokka will run them, otherwise not. To make Quokka execute anything, you may simply call it:
> 
> ```diff
> const test = 'This is a test';
> 
> console.log(test); //Output shows here
> 
> module.exports = () => {
>     return console.log(test); //Output does not show here
> };
> 
> +module.exports(); 
> ```

ooohhhhhh... Awesome, thank you so much for clearing that up!
