### ISSUE TITLE
Not possible to use imports in native esm mode

### ISSUE THREAD

**Issue by gordonmleigh** [wallabyjs/quokka#742]
### Issue description or question

Even when running with `nativeEsm: true`, some sort of translation step seems to be happening and causing imports to fail.

### Sample code

```javascript
({ stdEsm: false, nativeEsm: true, babel: false });

import debug from 'debug';

debug('hello');
```

### Quokka.js Console Output

```
​​​​​Quokka PRO 'test.js' (node: v16.13.2, babel: v7.15.5, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​
 
require is not defined in ES module scope, you can use import instead 
  ​​​​​at ​​​​​​./.scratchpad/test.js:3​
```

### Code editor version

VS Code:

```
$ code --version
1.63.2
899d46d82c4c95423fb7e10e68eba52050e30ba3
arm64
```

Quokka v1.0.442

### OS name and version

MacOS 12.1

**Comment by smcenlly** [comment]
Your Quokka.js console output shows that your project is using `create-react-app`.

If your project uses create-react-app, Quokka will [automatically configure itself](https://quokkajs.com/docs/configuration.html#create-react-app) to launch in an environment that is very similar the enviornment that jest uses when it runs your create-react-app tests. 

When using `create-react-app` Quokka’s configuration will be set to:

```json
{
  "plugins": ["jsdom-quokka-plugin"],
  "babel": {
    "ts": true,
    "presets": ["react-app"]
  }
}
```

In your case, I assume that `babel` is turning your `import` statements into `require`, which is causing your problem.

Please disable Quokka’s automatic configuration for `create-react-app` projects by updating your [global](https://quokkajs.com/docs/configuration.html#global-config-file), or [project](https://quokkajs.com/docs/configuration.html#quokka-file-config) Quokka configuration (not inline Quokka settings) with an `autoDetect` Quokka setting with a value of false as shown below:

```json
{
  "autoDetect": false,
  "stdEsm": false,
  "nativeEsm": true, 
  "babel": false
}
```
