### ISSUE TITLE
"ERR _.rtrim is not a function" & failure to hook if Todo Tree is also enabled.

### ISSUE THREAD

**Issue by lissaxjae** [wallabyjs/quokka#744]
### Issue description or question

Whenever Todo Tree is enabled, Quokka produces an error and fails to hook into the code resulting in an endless loading animation on the status bar.

The below error does not happen, and Quokka works fine, if Todo tree is disabled.
```
log.ts:313   ERR _.rtrim is not a function: TypeError: _.rtrim is not a function
    at k (c:\Users\mel\.vscode\extensions\wallabyjs.quokka-vscode-1.0.442\dist\wallaby\client.js:14:1660)
    at c:\Users\mel\.vscode\extensions\wallabyjs.quokka-vscode-1.0.442\dist\wallaby\client.js:14:1688
    at Server.<anonymous> (c:\Users\mel\.vscode\extensions\wallabyjs.quokka-vscode-1.0.442\dist\wallaby\client.js:15:2812)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at emitCloseNT (net.js:1659:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
```

Link to Todo Tree: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

### Code editor version

![image](https://user-images.githubusercontent.com/34404467/152714195-63f94291-4a42-4347-8b02-1661f23c5d14.png)

### OS name and version

![image](https://user-images.githubusercontent.com/34404467/152714225-f4baaad8-976d-45b5-9c43-a00e5a2c5945.png)

**Comment by smcenlly** [comment]
Unfortunately we couldn't reproduce the problem. We did however identify some code that we thought may cause the problem if another extension were to override some global scoped variables.

Could you please try using the latest version of Quokka for VS Code (`v1.0.443`) and let us know if you still have the problem?

**Comment by lissaxjae** [comment]
Whatever you changed seemed to have worked. Thanks for digging into it.
