### ISSUE TITLE
`experimentalSpeciferResolution is not defined` error while importing an internal package in a rush based monorepo

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/quokka#748]
### Issue description or question
Quokka throws an error when an internal package is imported inside a mono repo.

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
import domain from "@libs/domain";
console.log(domain());
```

### Sample repository link

[sample repo](https://github.com/bhvngt/wallaby-mocha-rushjs)

Setup instructions have been given on the readme

When I run `demo.js` with `node --loader esbuild-node-loader demo.js`. It gives me the expected output.

### Quokka.js Console Output

```
Quokka #2 (node: v17.5.0)

experimentalSpeciferResolution is not defined
	at defaultGetFormat /Users/*****/Library/Application%20Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ%20IDEA.app.plugins/quokka-intellij/dist/runners/node/quokka@1.0.0/hooks-v2.mjs:141
	at getFormat /Users/*****/Library/Application%20Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ%20IDEA.app.plugins/quokka-intellij/dist/runners/node/quokka@1.0.0/hooks.mjs:127
	at load /Users/*****/Library/Application%20Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.6777.52/IntelliJ%20IDEA.app.plugins/quokka-intellij/dist/runners/node/quokka@1.0.0/hooks-v2.mjs:156
```

### Code editor version

intellij v2021.3.2

### OS name and version

OSX 12.2

**Comment by smcenlly** [comment]
Thanks for reporting your problem. There were actually two issues:

**1. Bug in Quokka**
Please update to the latest version of Quokka for IntelliJ (v1.0.128) that fixes the bug in Quokka. 

**2. Your file extension**
Outside of Quokka, your code is being compiler (i.e. from TypeScript) using `esbuild`. Quokka does not currently integrate with or support `esbuild`. This means that if your Quokka file has a `.js` extension, Quokka expects everything to be transpiled for you (e.g. already JavaScript). 

Please change your file extension from `demo.js` to `demo.ts` and it will work for you.

**Comment by bhvngt** [comment]
Thanks @smcenlly. I have updated my quokka with the latest release [1.0.324](https://plugins.jetbrains.com/plugin/9667-quokka/versions). I have also renamed my file to `.ts` from `.js`. I still get following error

```
Quokka #2 (node: v17.5.0, TypeScript: v4.5.5)

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "file://./node_modules/@libs/domain/src/index.ts" 
    at new NodeError (node:internal/errors:371:5)
    at ESMLoader.load (node:internal/modules/esm/loader:380:13)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:47)

(node:4260) ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.
```

**Comment by smcenlly** [comment]
Sorry - there was one other problem. Your `.quokka` configuration is invalid and needs to be changed to:

```diff
{
+ "stdEsm": false,
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node"
    }
  }
}
```

**Comment by bhvngt** [comment]
Thanks @smcenlly. Even with those, changes it gives me the same error. I have updated my [repo](https://github.com/bhvngt/wallaby-mocha-rushjs/) with my changes for your reference.

**Comment by smcenlly** [comment]
Your repo is working for us. Can you please try cloning to a fresh directory and try again? Please make sure that you follow all steps of your readme, as missing linked `node_modules` and libs will cause a problem:

> ```
> - ln -s $(pwd)/common/temp/node_modules node_modules
> - mkdir node_modules/@libs
> - ln -s $(pwd)/libs/domain node_modules/@libs/domain
> - ln -s $(pwd)/libs/store node_modules/@libs/store
> ```

**Comment by smcenlly** [comment]
Quick update: I've just managed to reproduce the problem using a different version of node. We'll get back to you when we know more.

**Comment by smcenlly** [comment]
With your environment setup, specifically linking to your project files from `node_modules`, and wanting them to resolve with `.ts` extension is causing a problem when using `node 17` but not in previous versions of `node`.

What we found is that `node` resolves your project path differently between the two different versions for the same import statement: `import {Foo} from "@libs/domain/utils/Foo";`:

* Node 16: `./libs/domain/src/utils/Foo.ts`
* Node 17: `./node_modules/@libs/domain/src/index.ts`

Quokka is using `ts-node` with TypeScript to compile your project imports dynamically, and by default TypeScript ignores all `node_modules`. In your case, this means your code won't be transpiled for you (which is causing problems). `ts-node` allows you to transpile `node_modules` with an environment variable, [`TS_NODE_SKIP_IGNORE`](https://github.com/TypeStrong/ts-node#skipping-node_modules). Setting this environment variable fixes your problem but may slow Quokka down (or even break in some cases) as all imports that your Quokka file uses will be running through the TypeScript compiler.

This configuration will work for you:

**.quokka (configuration file)**
```javascript
{
  "stdEsm": false,
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node",
      "env": "TS_NODE_SKIP_IGNORE=true"
    }
  }
}
```

Alternatively, you can use `node` version `16` for now. Given that version `17` is a work in progress and not LTS, perhaps this behavior will change again before the release of version `18`.

**Comment by bhvngt** [comment]
Thanks @smcenlly for your insightful analysis. On reverting my node version back to `16`, I see quokka working for my project. Like you suggested, I will stick with node `16` for my current work and will wait for this behaviour to stabilise and possibly upgrade to the next `LTS`. Hopefully by that time, the resolution algorithm would have been stabilised
