### ISSUE TITLE
Quokka not working in Ubuntu/Linux

### ISSUE THREAD

**Issue by Noriller** [wallabyjs/quokka#749]
### Issue description or question

Basically same problem as: https://github.com/wallabyjs/quokka/issues/673
Did everything, but still not working.

I'm using snap:
![image](https://user-images.githubusercontent.com/54413263/155402347-218f365c-72f6-4b3b-b66a-17acce40e22b.png)

I've tried the global config thing, then tried to create a symlink to the default node path and it still not works

### Code / OS
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-30-generic snap

### Logs from a new code window, tried both a new javascript and typescript file
log.ts:301  INFO IExtensionHostStarter.start() took 43 ms.
log.ts:313   ERR [Extension Host] (node:55096) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:55096) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220222/syntaxes/JavaScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220222/syntaxes/JavaScript.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220222/syntaxes/TypeScript.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220222/syntaxes/TypeScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/redhat.vscode-yaml-1.4.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
console.ts:137 [Extension Host] [Wallaby Console] VS Code extension v1.0.327
console.ts:137 [Extension Host] [Wallaby Console] Core v1.0.1226
console.ts:137 [Extension Host] capabilities resolved immediately
console.ts:137 [Extension Host] [vscode-icons] v11.10.0 activated!
console.ts:137 [Extension Host] undefined
console.ts:137 [Extension Host]% {$mid: 1, fsPath: "Untitled-2", external: "untitled:Untitled-2", path: "Untitled-2", scheme: "untitled"}
console.ts:137 [Extension Host] 2022-02-23T20:23:06.805Z - debug: [TypescriptHero] Setting up extension and activatables.
console.ts:137 [Extension Host] 2022-02-23T20:23:06.806Z - debug: [ImportOrganizer] Setting up ImportOrganizer.
console.ts:137 [Extension Host] 2022-02-23T20:23:06.808Z - debug: [TypescriptHero] Starting up extension and activatables.
console.ts:137 [Extension Host] 2022-02-23T20:23:06.809Z - info: [ImportOrganizer] Starting up ImportOrganizer.
console.ts:137 [Extension Host] undefined
console.ts:137 [Extension Host]% {$mid: 1, fsPath: "Untitled-1", external: "untitled:Untitled-1", path: "Untitled-1", scheme: "untitled"}
console.ts:137 [Extension Host] undefined
console.ts:137 [Extension Host]% {$mid: 1, fsPath: "Untitled-2", external: "untitled:Untitled-2", path: "Untitled-2", scheme: "untitled"}
console.ts:137 [Extension Host] undefined
console.ts:137 [Extension Host]% {$mid: 1, fsPath: "Untitled-1", external: "untitled:Untitled-1", path: "Untitled-1", scheme: "untitled"}

**Comment by smcenlly** [comment]
Could you please try running the VS Code command `Quokka.js: New JavaScript File`. It should open a new code window. Then paste the content:

```javascript
console.log('Hello World');
```

Can you then please provide us with:
1. A screenshot of your VS Code (including any error messages that display) 
2. The developer tools console log (open using the VS Code command `Developer: Toggle Developer Tools`)

**Comment by Noriller** [comment]
![image](https://user-images.githubusercontent.com/54413263/155582836-4560dd17-9deb-44bd-b1be-40098b79c02c.png)

### logs
INFO IExtensionHostStarter.start() took 255 ms.
log.ts:313   ERR [Extension Host] (node:103078) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:103078) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.js.jsx.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220223/syntaxes/JavaScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.js.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/javascript/syntaxes/JavaScript.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220223/syntaxes/JavaScript.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220223/syntaxes/TypeScript.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.tsx.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/ms-vscode.vscode-typescript-next-4.7.20220223/syntaxes/TypeScriptReact.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///snap/code/88/usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/noriller/.vscode/extensions/redhat.vscode-yaml-1.4.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] 2022-02-24T18:11:40.342Z - debug: [TypescriptHero] Setting up extension and activatables.
console.ts:137 [Extension Host] 2022-02-24T18:11:40.342Z - debug: [ImportOrganizer] Setting up ImportOrganizer.
console.ts:137 [Extension Host] 2022-02-24T18:11:40.342Z - debug: [TypescriptHero] Starting up extension and activatables.
console.ts:137 [Extension Host] 2022-02-24T18:11:40.343Z - info: [ImportOrganizer] Starting up ImportOrganizer.
console.ts:137 [Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
console.ts:137 [Extension Host] [Wallaby Console] VS Code extension v1.0.327
console.ts:137 [Extension Host] [Wallaby Console] Core v1.0.1226
console.ts:137 [Extension Host] capabilities resolved on focus true
console.ts:137 [Extension Host] [vscode-icons] v11.10.0 activated!
log.ts:307  WARN [File Watcher (parcel)] ignoring a path for watching who's parent is already watched: /home/noriller/git/vanhack-challenges
console.ts:137 [Extension Host]% Object
log.ts:313   ERR [File Watcher (parcel)] Unexpected error: inotify_add_watch on '/home/noriller/.config/Code/User/sync/globalState/preview' failed: No such file or directory (EUNKNOWN) (path: /home/noriller)
log.ts:313   ERR [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '/home/noriller/.config/Code/User/sync/globalState/preview' failed: No such file or directory
log.ts:307  WARN [File Watcher (parcel)] ignoring a path for watching who's parent is already watched: /home/noriller/git/vanhack-challenges
console.ts:137 [Extension Host] undefined
console.ts:137 [Extension Host]% {$mid: 1, fsPath: "Untitled-1", external: "untitled:Untitled-1", path: "Untitled-1", scheme: "untitled"}

**Comment by smcenlly** [comment]
One thing I'd like to check is that you're running a valid version of node. Can you please run `/snap/bin/node --version` and confirm that the version is 8+?

I've found a number of different issues with people having problems using the `snap` version of `node` within VS Code. For example:

* https://github.com/microsoft/vscode/issues/102723
* https://github.com/microsoft/vscode/issues/102355

I also found various discussion threads that have suggested that within the Snap confinement, `node` only has access to your home directory and may have issues with silently refusing to start.

Can you please try installing another instance of node (without `snap`). I believe it will fix your problem.

I'm not familiar with using `snap`, but I also read:

> Snaps installed with --classic aren't sandboxed.
> 
> ...from `man snap`
> 
> ```
> --classic
>               Put snap in classic mode and disable security confinement 
> ```

You may be able to reinstall `node` with `--classic` to see if that fixes your problem.

**Comment by Noriller** [comment]
![image](https://user-images.githubusercontent.com/54413263/155619235-dc338fee-416f-41c8-930e-031f892673d7.png)

The version is v16, logical AND are from v15 and it's working.

The snap version was installed with the classic flag. (also just reinstalled and didn't work)

---

On the developer tools log, it appear "[Extension Host]  Quokka.js Live Share integration disabled, VSLS not found."

I installed and enabled liveshare... it gone with that line, but still not working...

---

I will try to install another way, but I'm provisioning my PC using ansible... so snap is easier...

Also... I've started using ubuntu recently and I'm using ansible to configure it... if you can run a VM, you could basically use the same setup I'm using: https://github.com/Noriller/my-ansible

**Comment by smcenlly** [comment]
We have tried setting up a VM with your ansible script and even outside of Quokka things are not working properly for us. It appears to be permission related:

![image](https://user-images.githubusercontent.com/2074089/156087080-5060ee40-c130-412c-95f9-d96b49234604.png)

Quokka doesn't install anything globally, but does start child processes and set up listening on web sockets. I believe that something to do with snap node permissions is causing Quokka to fail.

Could you please try installing node outside of `snap` (e.g. from [`nvm`](https://github.com/nvm-sh/nvm)). It should work for you.
