### ISSUE TITLE
​​Unexpected token import​​

### ISSUE THREAD

**Issue by Janatbek** [wallabyjs/quokka#75]
I had this error on app.component.ts in angular/cli project
Can I run Quokka in angular4? 

​​​​Quokka #1 (node: v6.11.0, TypeScript: v2.3.4)​​​​
​​​​
​​Unexpected token import​​
  at ​​​createScript​​​ ​vm.js:56​
  at ​​​Object.runInThisContext​​​ ​vm.js:97​
  at ​​​Module._compile​​​ ​module.js:542​
  at ​​​Object.Module._extensions..js​​​ ​module.js:579​
  at ​​​Module.load​​​ ​module.js:487​
  at ​​​tryModuleLoad​​​ ​module.js:446​
  at ​​​Function.Module._load​​​ ​module.js:438​
  at ​src/app/app.component.ts:4​

**Comment by ArtemGovorov** [comment]
Have a look here: https://github.com/wallabyjs/quokka/issues/52 and here https://github.com/wallabyjs/quokka/issues/25 / https://github.com/wallabyjs/quokka/issues/74
