### ISSUE TITLE
Bought pro version years ago, no longer getting support for basic features I used to have

### ISSUE THREAD

**Issue by Tycholiz** [wallabyjs/quokka#750]
### Issue description or question
Features like "Start on current file", "run once for current file" aren't working anymore, throwing the error:

> You are not licensed to use PRO features for this version of Quokka.js 'Pro' because it was released after your license expired. To continue using Quokka, you can: [Renew], [Activate], [Downgrade], or [Use 'Community' Edition].

### Code editor version

Visual Studio Code v1.64.2

### OS name and version
OSX Monterey 12.2.1

**Comment by smcenlly** [comment]
The license key that you purchased allows you to use any version of Quokka released within 12 months after purchase indefinitely.

By default, VS Code will automatically update your extensions, which is why Quokka has broken for you.

To continue to use the version of Quokka your license entitles you to, you will need to [check your license expiry date](https://quokkajs.com/docs/previous.html#previous-versions) and install a version of Quokka released before that date by right-clicking on the extension name in VS Code and using the Install Another Version menu item.

To stop seeing the reminder about expired version you may use the `Suppress Expiration Notifications` Quokka VS Code setting.

**Comment by 1jerry** [comment]
**and when that doesn't work?**
The support page for my license reads:

> Previous Versions
> Your license expired on 27 November, 2022.
> 
> The last version of Quokka that was included in your 12-months of free upgrades was:
> 
> VS Code Quokka-1.0.514 for VS Code ([Read Instructions](https://quokkajs.com/docs/previous.html?expirydate=2022-11-28#how-do-i-continue-to-use-my-expired-license-with-vs-code))
> JetBrains [Quokka-1.0.366 for JetBrains IDEs](https://quokka-versions.s3.amazonaws.com/quokka-intellij-v1.0.366.zip)

So I downloaded and installed and verified and restarted. Again verified it says version 1.0.366.  Still getting the "not licensed..." message.
MacBook Pro, using IntelliJ 2022.3.2 on 2-2-23.

Now what do I do?

**Comment by ArtemGovorov** [comment]
> Again verified it says version 1.0.366. Still getting the "not licensed..." message.

Can you please share a screenshot of the "not licensed..." message that you are getting after installing v1.0.366?

**Comment by 1jerry** [comment]
[image: image.png]
-- 
Jerry
--

**Comment by ArtemGovorov** [comment]
@1jerry Unfortunately the screenshot was not attached to your reply. Can you please attach it via GH website?

**Comment by 1jerry** [comment]
Well that wasn't very useful, was it?
Attaching from GH 
![image](https://user-images.githubusercontent.com/96444/216740697-d0650add-6660-409d-8f2e-31aa543222de.png)

**Comment by ArtemGovorov** [comment]
@1jerry Thanks. The message doesn't mention "not licensed...", it's just a warning about expired license and doesn't stop any features from working. You may suppress the message via IDE Notification settings:

<img width="881" alt="Screen Shot 2023-02-04 at 12 07 15 pm" src="https://user-images.githubusercontent.com/979966/216740860-b487aea3-9690-4bdf-9622-61aabcb231b7.png">

**Comment by 1jerry** [comment]
Thank you for your quick response.  I was doing the same thing as I tell
people *not to do*. That is not to look at the details when reporting a
problem.  I hate it when I'm human.  :)
Anyway, I kept seeing [what I thought] was the same message every time I
tried to run the code with Quokka from the context menu.
Thanks again,
-- 
Jerry
--

**Comment by BitterDone** [comment]
Hello, I ran into the same issue as Tycholiz (original poster). I tried two previous versions that should be valid, but it doesn't seem to work.

The License section of the extension settings states "you may use any extension version available on or before May 6, 2022."

I searched https://quokkajs.com/docs/support/previous/#how-do-i-continue-to-use-my-expired-license-with-vs-code and found version 1.0.466, which I installed in VS Code by right-clicking the Marketplace entry and clicking "Install Specific Version".

I tried again with version 1.0.463, available the day before on May 5, 2022, with the same results.

<img width="2056" alt="Image" src="https://github.com/user-attachments/assets/00d5ec18-4c67-45f8-ba56-1043333bb8f0" />

<img width="2056" alt="Image" src="https://github.com/user-attachments/assets/131a60cd-4605-4586-b21f-88bb35961659" />

**Comment by smcenlly** [comment]
@BitterDone - In mid-September, VS Code included a breaking change that means that versions of Quokka before `v1.0.652` will not work on the latest version of VS Code. Unfortunately, there is nothing we can do to fix this for previous versions. If you downgrade your VS Code version to a version before September 2024, it should work for you.

**Comment by BitterDone** [comment]
> [@BitterDone](https://github.com/BitterDone) - In mid-September, VS Code included a breaking change that means that versions of Quokka before `v1.0.652` will not work on the latest version of VS Code. Unfortunately, there is nothing we can do to fix this for previous versions. If you downgrade your VS Code version to a version before September 2024, it should work for you.

Ah, gotcha. Thank you for the quick reply
