### ISSUE TITLE
Quokka Live Performance Testing Special Comment | Conflict with Wallaby.js

### ISSUE THREAD

**Issue by Rivera-Emmanuel** [wallabyjs/quokka#752]
### Issue description or question

When using using Live Performance Testing comment  ( /*?.*/) test file running wallaby.js errors with “Column must be greater than or equal to 0, got -1" 

Issue appears to only occur when requiring a CommonJS module to test file,
 
example:
```javascript
const { handler } = require(‘../file’)
```

### Quokka.js Console Output

None

### Code editor version

Visual Studio Code v1.64.2

Node 14.7.3

### OS name and version

OSX Version 15.3 (17612.4.9.1.8)

**Comment by smcenlly** [comment]
Could you please provide us with a complete sample that includes the Live Performance Testing comment so that we can see exactly where you're putting it?

**Comment by Rivera-Emmanuel** [comment]
> Could you please provide us with a complete sample that includes the Live Performance Testing comment so that we can see exactly where you're putting it?

Simon, 

I’ve put together some screenshots of some basic code so you can see the behavior:

Screenshot with unexpected behavior:
![Screen Shot 2022-03-03 at 13 38 09](https://user-images.githubusercontent.com/75558288/156649916-aaea68b8-637c-4baf-a64b-7b57a0842662.png)

Screenshot with expected behavior.
![Screen Shot 2022-03-03 at 13 40 56](https://user-images.githubusercontent.com/75558288/156649937-4e3ae34d-fc2c-49ac-91bf-0d41ca303059.png)
.

**Comment by smcenlly** [comment]
Thanks for the sample, we've been able to reproduce the issue and are investigating.

**Comment by smcenlly** [comment]
You mentioned that this was an issue with Quokka, but the sample that you provided was for Wallaby. Did you also have a problem with Quokka?

The latest version of Wallaby core, `v1.0.1235` fixes your issue. Wallaby should automatically update to this version for you but if not, you may explicitly update using the VS Code command `Wallaby.js: Force Core Update`.

We have also released a Quokka update with the same fix in case you also had the same problem in Quokka. Please update to `Quokka for VS Code v1.0.449` (it may take a few minutes for it to become available in the VS Code marketplace).

**Comment by Rivera-Emmanuel** [comment]
I’ve updated to the latest version, and the issue is resolved. Thank you!

I thought I had Quokka running on the non-test file and Wallaby running on the test file. But now I’m not sure if I was confusing the two. I apologize for any confusion.

Thanks again!
