### ISSUE TITLE
How do we clear the console / start a fresh sessidon?

### ISSUE THREAD

**Issue by rbutera** [wallabyjs/quokka#753]
I've been using quokka for the last few days to prototype some code.

I had been running quokka on foo.ts and generated about 100k lines of output in my console.

I then used the vscode command Quokka: stop current file and Quokka: stop all on that file, and opened a new quokka typescript file (let's call that bar.ts)

I've tried clicking the clear button on the quokka output, every option for 'stop' from the command palette, but every time I make a change to `bar.ts` I still get the full output of `foo.ts` (all 100k+ lines ) which obviously is very very slow and locks up my PC for a few seconds.

Please don't ask me for a code sample because it doesn't matter what code I try to run, the same thing happens.

Here's a gif showing what I mean:
![2022-03-03-212041-recommendations scratch ts — lexstep-nest](https://user-images.githubusercontent.com/6047293/156654884-ac991ad5-55b1-4b17-8e0f-2f1a2544cd3e.gif)

I stop all quokka files. I create a new quokka file. It runs my recent file even though that is stopped. I tried clearing the output and still the same bs, I have to close and reload the window in order to get a 'fresh' start.

**Comment by smcenlly** [comment]
@rbutera - did any of our suggestions above help?

**Comment by rbutera** [comment]
Completely closing vscode and reopening fixes the issue, but obviously isn't a great developer experience for what is otherwise a fantastic suite of productivity tools for vscode.

`code -v` output:

1.64.2
f80445acd5a3dadef24aa209168452a3d97cc326
x64

**Comment by smcenlly** [comment]
There is now a new version available, `1.65.0` that was released 4 days ago. Please also try that version. 

It was unclear whether you tried the suggestions above? Specifically:

* Try using `VS Code Insiders`. Do you have the same problem?
* Disable **all** extensions except for Quokka, do you have the same problem?
* Try resetting all of your view locations with the VS Code command `View: Reset View Locations` and reload VS Code. Do you have the same problem still?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you are still having problems and have tried the steps above, please let us know.
