### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by glntlq** [wallabyjs/quokka#754]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript

```

### Quokka.js Console Output

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/21242803/156693398-e7271141-4248-4f3a-957b-075f620a5cb7.png">

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

OSX

**Comment by smcenlly** [comment]
It looks like you are using a version of `node.js` (`v8.9.2`) that has reached end of life (released December 5th, 2017). Node version `8.x` reached end of life on December 31, 2019.

Could you please try and install the latest version of [node.js LTS](https://nodejs.org/), `v16.x` to see if that fixes your problem?

If you're still having problems, could you please provide us with the code that you're attempting to run and an updated Quokka Output log?

**Comment by smcenlly** [comment]
Assuming our suggestion helped. Closing this issue.
