### ISSUE TITLE
GitLens pushes inline Quokka messages away

### ISSUE THREAD

**Issue by ryanaltvater** [wallabyjs/quokka#759]
### Issue description or question

I don't know if this is an extension thing (Quokka or GitLens) or a personal setting that can be updated, but I'm curious if there's a way to set the position/priority of inline messages produced by extensions. I'm currently using Quokka along with GitLens, and the problem is that GitLens is pushing inline Quokka messages away from the code by injecting Git history messages about that selected line. When a line isn't selected, the position of Quokka messages are where they should be.

### Code editor version

Visual Studio Code v1.65.1

### OS name and version

macOS Monterey v12.2.1

### Screenshots

![Screen Shot 2022-03-18 at 11 28 00 AM](https://user-images.githubusercontent.com/1336787/159032550-ae93d9c1-fe91-4a29-8c5d-bd3dcf6f1f59.png)

![Screen Shot 2022-03-18 at 11 27 17 AM](https://user-images.githubusercontent.com/1336787/159032415-1201e6e2-8d98-4443-9758-1ebc5ecc931b.png)

![Screen Shot 2022-03-18 at 11 28 10 AM](https://user-images.githubusercontent.com/1336787/159032591-94d28a59-14dc-48dc-9fa0-37ca7e35e14d.png)

![Screen Shot 2022-03-18 at 11 17 58 AM](https://user-images.githubusercontent.com/1336787/159032434-b6c71b00-9a78-42c0-84ce-5aa9bca42a28.png)

**Comment by ArtemGovorov** [comment]
Unfortunately VS Code API doesn't allow to set inline messages priority/order. 

One possible solution is to use the `gitlens.currentLine.enabled` setting to turn a blame annotation for the current line off:

<img width="1222" alt="Screen Shot 2022-03-19 at 10 16 23 am" src="https://user-images.githubusercontent.com/979966/159098913-39efdf30-6f2e-458c-9949-e5fede175a8a.png">

**Comment by ryanaltvater** [comment]
That stinks, but hey thanks for the suggestion! I know you can disable things on the GitLens side like that, but I just started using GitLens and kind of like the inline annotation.

Here’s to requesting VS Code priority/order of annotations! 🍻😆🍻
