### ISSUE TITLE
Quokka entry point js file

### ISSUE THREAD

**Issue by nicholasio** [wallabyjs/quokka#76]
### Issue description or question
Is it possible to run Quokka on a specific file on a project but have it ran through the entry js file of the application? (for a react app it would be the js file that bootstraps everything and renders the root component). I understand that if I run quokka directly from the component below it won't actually execute anything because nothing is actually calling the component. I was wondering, however, if there's a way to tell Quokka to always run from a entry js file but being able to interact with the file I choose to run from.
### Quokka.js file

```javascript
import React from 'react';

const Categories = ( {categories = []} ) => {
	return (
		<div className="card my-4">
			<h5 className="card-header">Categories</h5>
			<div className="card-body">
				<div className="row">
					<div className="col-lg-6">
						<ul className="list-unstyled mb-0">
							{categories.map( (category,index) => (
								<li><a href="#">{category.name}</a></li>
							) )}
						</ul>
					</div>
				</div>
			</div>
		</div>
	);
};

export default Categories;
```

### Sample repository link

https://github.com/nicholasio/react-blog-wp-graphql

### Code editor version

PHPStorm 2017.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
You may create a new Quokka file, import the bootstrap file and after it import the component file, and then write any code that renders the component into the app, etc.

You may also [create Quokka plugin](https://quokkajs.com/docs/extensibility.html) where you can execute any code before/beforeEach Quokka execution, or import and execute other files, such as app bootstrap files.

**Comment by ArtemGovorov** [comment]
BTW, with the Quokka plugin, you may even not need a separate plugin. 
For example, if your app bootstrap file (like `index.js`) initializes everything you need, then (with the latest plugin version 1.0.27), you may just specify the file as one of the plugins in your [quokka config](https://quokkajs.com/docs/configuration.html):

```
{
    "babel": true,
    "plugins": ["jsdom-quokka-plugin", "./index"]
}
```

This way Quokka will execute the file before executing Quokka file.

**Comment by nicholasio** [comment]
Awesome, worked great by just including the index.js as a plugin (after updating to 1.0.27). Before the update it didn't work but now sounds like babel compiles the plugins first, making it to work.

Thanks you!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
Yes, exactly, we did change the order of plugins and babel initialization.
