### ISSUE TITLE
Auto Logs all lines even if community and option set to false

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [wallabyjs/quokka#760]
### Issue description or question

Even a simple line in a js file does show the value of each lines, not just only the console.log calls

### Sample code

```javascript
({
  autoLog: false
})

const Hello = "World";
```

![image](https://user-images.githubusercontent.com/11965035/159039749-2f467b08-ec31-47b4-bc2e-28593e6eb3a9.png)

### Code editor version

Visual Studio Code v1.65.2

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue has been fixed and is published in the latest v1.0.451.
