### ISSUE TITLE
Settings to disable welcome screen

### ISSUE THREAD

**Issue by travispamaral** [wallabyjs/quokka#761]
### Issue description or question

Hi there! I LOVE quokka however I have found quite an annoying issue with the VSCode plugin and I'm curious if there is a way to solve it. Due to how my local dev env works I make new remote vs code sessions on a regular basis and quokka is auto installed. Everytime I open a new session though I see the welcome screen. Is there any way to disable to screen from showing? Ideally I would never see it.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/5941111/159612968-c33e14f3-b392-46a3-8fab-dc8b765f79ff.png">
 

### Code editor version

Visual Studio Code v1.65.2

### OS name and version

OSX

**Comment by smcenlly** [comment]
For our other product, [Wallaby.js](https://wallabyjs.com), we created a [wallaby-vscode-remote-containers](https://github.com/wallabyjs/wallaby-vscode-remote-containers) sample repo that includes .devcontainer settings for sharing your the local wallaby license with a dev container (see .devcontainer/docker-compose.yml and .devcontainer/devcontainer.json).

You could do a similar thing for Quokka (if you have a Quokka license). To stop the startup page being displayed every time, you should also copy the `~/.quokka/startPage.json` file, which is how Quokka remembers not to show the screen again.

To try out the container:

1. From the command line, run: `git clone https://github.com/wallabyjs/wallaby-vscode-remote-containers.git`.
2. Open the wallaby-vscode-remote-containers folder created by step 1 in VS Code.
3. Run the VS Code command Remote-Containers: Reopen in Container.
4. Run the VS Code command Wallaby.js: Start.

**Comment by travispamaral** [comment]
Im not sure that is a fix for my specific problem. Is just having the `startPage.json` saved enough to not show the page?

**Comment by smcenlly** [comment]
> Is just having the `startPage.json` saved enough to not show the page?

Yes, this should be enough (provided that it has valid content). You may find with feature releases (updates to `What's New` in our start page) that you will need to update the content for your container.

**Comment by travispamaral** [comment]
I think I'm missing something haha. I added the startPage that was created into my settings to ensure its always there and I still got the start up page. You can see from the screenshot below what content is in the file. This isn't the end of the world, just a little annoying when I consistently make new remote instances

![screenshot](https://user-images.githubusercontent.com/5941111/160492946-a9e074d0-f805-4271-88fb-c14761c7cadb.png)

**Comment by smcenlly** [comment]
Please also try copying `config.json` (in addition to `startPage.json`). It should look either like:

```javascript
{"pro":true}
```

or

```javascript
{"pro":false}
```

**Comment by smcenlly** [comment]
Quokka will now automatically pass your license, configuration file, and start up page settings to remote VS Code instances. Please update to the latest version of Quokka for VS Code (`v1.0.453`) and after restarting VS Code, Quokka should start to automatically apply your settings when remote VS Code instances are launched.
