### ISSUE TITLE
Unable to override typescript config

### ISSUE THREAD

**Issue by Rawnly** [wallabyjs/quokka#762]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

It seems that I'm unable to override `compilerOptions`
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/16429579/159806032-c3ed4913-4f93-4c30-9a72-c5be3692111a.png">

Am I doing something wrong?

### Sample code
I tried running the `Reflect.get` example in a new typescript file.
```typescript
({
	"ts": {
		"compilerOptions": {
			"target": "esnext",
			"lib": ["esnext"]
		}
	}
})
  
const object1 = {
	x: 1,
	y: 2
  };
  
  console.log(Reflect.get(object1, 'x'));
  // expected output: 1
  
  var array1 = ['zero', 'one'];
  
  console.log(Reflect.get(array1, 1));
```

### Sample repository link
I'm not into a initialised project, I just started a new file without having any project open.

### Quokka.js Console Output

```
1 ​​​​​at ​​​​​​​​Reflect.get(object1, 'x')​​​ ​quokka.ts:15:3​

one ​​​​​at ​​​​​​​​Reflect.get(array1, 1)​​​ ​quokka.ts:20:3​
```

### Code editor version

Visual Studio Code v1.65.2

### OS name and version
OSX 12.3

**Comment by smcenlly** [comment]
Quokka is correctly applying your `compilerOptions`, which you can see in the Quokka output.

The inline message that you are seeing in your editor in VS Code is not produced by Quokka. You may confirm this by disabling all other extensions and only running Quokka and you will see that the message disappears. 

I assume that you have the eslint plugin configured with defaults and it is running on this file (and it does not/cannot know about Quokka TypeScript compiler overrides).
