### ISSUE TITLE
Quokka.js does not work with vscode snap package on ubuntu

### ISSUE THREAD

**Issue by HiweIt** [wallabyjs/quokka#768]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

When I tried to run Quokka on ANY file, the only thing that happened was that the processing indicator in the lower right corner kept spinning.

Things I've tried with no improvement:
- backup all extensions, remove "~/.vscode/extensions", then install only Quokka
- installing an older version of Quokka extension

What actually got it working, was reinstalling vscode from a .deb package, rather than from the Snap store.

### Sample code

Not dependent on user code.

### Sample repository link

Not dependent on user code.

### Quokka.js Console Output

Empty

### Code editor version

Visual Studio Code v1.66.1

### OS name and version

Linux Ubuntu 20.04.4 LTS

**Comment by smcenlly** [comment]
There are various known issues (unrelated to Quokka) using snap that may occur as a result of snap sandboxing. Without custom flags at installation, or subsequent interface connections, snaps are confined to a restrictive security sandbox with no access to system resources outside of the snap which means that Quokka cannot run. You will find other extensions that spawn child processes are affected in a similar way.

When you installed VS Code, did you install with `sudo snap install code --classic`? If you did not use the `--classic` argument, this may explain why it didn't work for you. If you installed `node.js` using snap, you may run into similar problems.
