### ISSUE TITLE
Live Value Display feature Show Value on Selection and Show All Selected Values settings not work

### ISSUE THREAD

**Issue by Saszr** [wallabyjs/quokka#769]
### Issue description or question

Live Value Display feature Show Value on Selection and Show All Selected Values settings not work.
Can you give a comparative example of it, I am no longer confident in my operation.

### Example

![2022-04-09 20 20 18](https://user-images.githubusercontent.com/22406550/162574021-fdf22606-070e-40a8-8f19-8f7de2330b48.gif)

### Code editor version

Visual Studio Code v1.66.1

### OS name and version

OSX

**Comment by NikGovorov** [comment]
Thanks for providing the detailed set of steps to reproduce the problem. We were able to duplicate the problem and have released a new version of Quokka for VS Code that fixes the problem (v1.0.457).
