### ISSUE TITLE
Node out of memory

### ISSUE THREAD

**Issue by horsemanV** [wallabyjs/quokka#77]
### Issue description or question
I'm just playing around with some big numbers and running out of memory while doing so. Is there a way to pass flags to the node runtime via the ~/.quokka/config.json file? Particularly, I'm interested in the ```--max_old_space_size=x``` flag. (I love Quokka, by the way, it's an awesome tool!)
### Quokka.js file

```javascript
import ramda from 'ramda';

const limit = 600851475143;

const range = ramda.range(1, limit  + 1);

const odd = ramda.complement( x => x % 2 === 0);
const odds = ramda.filter(odd, range);

/* ? */

```

### Quokka.js Console Output

```
Quokka #1 (node: v4.2.6, babel: v6.26.0)​​​​
​​​​
​​FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory​​
```

### Code editor version

Visual Studio Code v1.15.1

### OS name and version
Ubuntu 16.04.3 LTS

**Comment by ArtemGovorov** [comment]
Thanks for the feature request.
We have just published the latest extension version (1.0.52) where you now can specify node flags in [quokka configuration](https://quokkajs.com/docs/configuration) similarly like [we support it in wallaby.js](https://wallabyjs.com/docs/config/runner.html), for example:

```
{
  ...
  "env": {
    "params": {
      "runner": "--max_old_space_size=x"
    }
  }
}
```

- `env.params.runner` allows you to set space-separated spawned runner process flags.

- `env.params.env` allows you to set semicolon-separated spawned runner process environment variables.

Hope it helps
