### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by MrHIDEn** [wallabyjs/quokka#771]
### Issue description or question

Quokka works well with many TS imports, but not in this case. I don't see the problem here. How to solve it?
I read other forum posts but that doesn't work for me.

### Sample code

```typescript
  import psList from 'ps-list';
  (async () => {
    const ps = await psList();
    console.log(ps);
  })();
```

### Quokka.js Console Output

```
Must use import to load ES Module: ./node_modules/ps-list/index.js
require() of ES modules is not supported.
require() of ./node_modules/ps-list/index.js from ./quokka.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ./node_modules/ps-list/package.json.
	at new NodeError internal/errors.js:322
	at Object.Module._extensions..js internal/modules/cjs/loader.js:1102
	at Module.load internal/modules/cjs/loader.js:950
	at Function.Module._load internal/modules/cjs/loader.js:790
	at require internal/modules/cjs/helpers.js:93
	at Object.<anonymous> quokka.ts:1
	at Module._compile internal/modules/cjs/loader.js:1085
```

### Code editor version

InteliJ 2021.2.2

### OS name and version

MacOS

**Comment by MrHIDEn** [comment]
I have tried to run it other way, the error also exists there. Closing.

**Comment by smcenlly** [comment]
FYI: it sounds like your TypeScript compiler options are transforming your `import` statement to `require`. If you don't have any TypeScript compiler settings then this is expected due to TypeScript compiler defaults. If you encounter this issue again and need assistance, please let us know and provide us with your `tsconfig.json`; we'd be happy to take a look at what's going on for you.
