### ISSUE TITLE
Issue with 'await axios.get(...' call

### ISSUE THREAD

**Issue by ChessMess** [wallabyjs/quokka#774]
### Issue with simple Axios Code
Since I'm new to Quokka today I suspect this is just a PEBCAK issue.
Is this issue related to Quokka not outputting the expected results of your code?: Yes
This is the output when ran using "NODE index.js"
```
❯ node index.js
apiData: {"fact":"The leopard is the most widespread of all big cats.","length":51}
```

### Sample code

```javascript
import axios from "axios";

let apiData = 'not set'

await axios.get("[https:atfact.ninja/fact](https://app.slack.com/client/T06HNFUAG/C0CP0R0Q2/thread/atfact.ninja/fact)")
  .then(res => {
    apiData = res.data
  })
  .catch(err => {
    console.log(`${err.response.data.code} : ${err.response.data.message}`)
  })

  console.log(`apiData: ${JSON.stringify(apiData)}`)
```

### Quokka.js Console Output
// paste your quokka console output here
```
​​​​​Quokka PRO 'index.js' (node: v17.8.0)
Cannot read properties of undefined (reading 'data') 
  ​​​​​at ​​​​​​index.js:10:5​
  ​​​​​at ​​​​​​index.js:5:1​
```
### Code editor version
```
Visual Studio Code
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z (2 wks ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0
```
### OS name and version
OSX Monteray 12.3.1

**Comment by smcenlly** [comment]
I get the same error when running the same code from the command line with `node.js`. I'm curious as to why it's working for you from the command-line and not for us. Regardless, if you get an error, your error handling code is wrong as the response property doesn't (at least not always) exist on the error.

**console.log output**
```
> node sample.js

file:///quokka-774/sample.js:10
    console.log(`${err.response.data.code} : ${err.response.data.message}`)
                                ^

TypeError: Cannot read properties of undefined (reading 'data')
    at file:///quokka-774/sample.js:10:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///quokka-774/sample.js:5:1
```

Your code on line 10 is causing a problem:

```
console.log(`${err.response.data.code} : ${err.response.data.message}`)
```

There is no `err.response` property (it is undefined) and so your program is crashing.

---

If you're continuing to have problems, please provide us with a reproducible sample that we can run outside of Quokka and that fails when running inside Quokka.

**Comment by ChessMess** [comment]
Thank you so much for the response, indeed it was a PEBCAK issue and using the proper objects in the error response resolved the issue. Would be nice if Quokka didn't fail everything due to a bit of bad code in a .Catch() handler. Here is the code that now works for reference:
`import axios from "axios";

let apiData = {}

await axios.get("https://catfact.ninja/fact")
  .then(function (response) {
    apiData = response.data
    console.log(response.data);
    console.log(response.status);
    console.log(response.statusText);
    console.log(response.headers);
    console.log(response.config);
  })
  .catch(function (error) {
    if (error.response) {
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else if (error.request) {
      console.log(error.request);
    } else {
      console.log('Error', error.message);
    }
    console.log(error.config);
  });

let msg = `apiData: ${JSON.stringify(apiData)}`
console.log(msg)`
