### ISSUE TITLE
Live comments being ignored in some scenarios

### ISSUE THREAD

**Issue by JDrechsler** [wallabyjs/quokka#776]
### Sample code

```javascript
function test(arr1, arr2) {
  for (let i = 0; i < arr1.length; i++) {
    arr1 //? --- this comment is being ignored
    console.log(arr1)
    arr2 //?
  }
  arr1 //?
  arr2 //?
  arr2.length //?
  return arr2.length === 0
}

test([1, 2], [4, 1])
```

### Quokka.js Console Output
```
​​​​​Quokka PRO 'quokkaTest.js' (node: v14.19.1)​​​​
[ 1, 2 ] ​​​​​at ​​​​​​​​arr1​​​ ​src/problems/anagrams/quokkaTest.js:3:5​
[ 1, 2 ] ​​​​​at ​​​​​​​​arr1​​​ ​src/problems/anagrams/quokkaTest.js:4:5​
[ 4, 1 ] ​​​​​at ​​​​​​​​arr2​​​ ​src/problems/anagrams/quokkaTest.js:5:5​
[ 1, 2 ] ​​​​​at ​​​​​​​​arr1​​​ ​src/problems/anagrams/quokkaTest.js:3:5​
[ 1, 2 ] ​​​​​at ​​​​​​​​arr1​​​ ​src/problems/anagrams/quokkaTest.js:4:5​
[ 4, 1 ] ​​​​​at ​​​​​​​​arr2​​​ ​src/problems/anagrams/quokkaTest.js:5:5​
[ 1, 2 ] ​​​​​at ​​​​​​​​arr1​​​ ​src/problems/anagrams/quokkaTest.js:7:3​
[ 4, 1 ] ​​​​​at ​​​​​​​​arr2​​​ ​src/problems/anagrams/quokkaTest.js:8:3​
2 ​​​​​at ​​​​​​​​arr2.length​​​ ​src/problems/anagrams/quokkaTest.js:9:3​
```

### Sample video - arr1 ignored
![quokkajs3](https://user-images.githubusercontent.com/3910151/165813663-c6f66877-45b2-46b4-8caa-5fb94cbc2f2f.gif)

### Sample video2 - arr1 & arr2 ignored
![quokkajs4](https://user-images.githubusercontent.com/3910151/165818592-20503d9f-7794-4cbf-9394-33d2d3f56cbc.gif)

### Code editor version
Visual Studio Code Version: 1.66.2

### OS name and version
Windows Version 21H2

**Comment by smcenlly** [comment]
Thanks for raising the issue. I couldn't reliably reproduce the behavior initially. The steps to reproduce are:

1. Paste sample code
2. Start Quokka
3. Select `arr1` on line 3
4. Run the command `Quokka.js: Start Time Machine on The Current Line`

**Comment by JDrechsler** [comment]
Thank you for the very quick support!

**Comment by smcenlly** [comment]
We have completed our updates to make fix live comments and identifier expressions sometimes being ignored.

Please update to the latest version of Quokka and it should now work for you (Quokka for VS Code `v1.0.470`).
