### ISSUE TITLE
Codeclip not opening when running WSL

### ISSUE THREAD

**Issue by oguimbal** [wallabyjs/quokka#779]
### Issue description or question

Hi,

Sharing to codeclip.io works well in a vscode when running in windows, but when connected to a WSL instance, the browser does not open when running an instance of vscode pluggin on a WSL workspace.

![codeclip](https://user-images.githubusercontent.com/8973947/166971214-465de7c2-4c1a-4a30-97e0-ecd89fc86b72.gif)

(left: a WSL workspace ... right: a Windows workspace)

### Code editor version

vscode 1.66.2

### OS name and version

Windows, when running in WSL 2 (Ubuntu)

**Comment by NikGovorov** [comment]
Could you please try run this quokka in WSL and see what it outputs and whether it opens a browser tab?
https://codeclip.io/NikGovorov/codeclipissue7791
![image](https://user-images.githubusercontent.com/129254/167064211-82ad2690-e55e-4411-8b51-dbfe7d4c211a.png)

**Comment by oguimbal** [comment]
![image](https://user-images.githubusercontent.com/8973947/167082188-e5a1fc31-be15-4d5f-8577-33fddb01e8e8.png)

So I guess that's not caused by WSL... my workspace has a version of [react-dev-utils](https://www.npmjs.com/package/react-dev-utils) installed which depends on `open@7.4.0`. I guess that Quokka is picking up this old version ?

I  should have checked before: codeclip sharing is working fine in a blank WSL workspace.

**Comment by NikGovorov** [comment]
Quokka uses it's own internal version of `open` when it opens a link after a code clip was uploaded, so having a local version in a project should not be an issue . On the other hand, the snippet above will use whatever version you have installed locally or will ask you to install the package from npm.

Anyway, we've added better error reporting around `open` calls, could you please try to update the extension to `1.0.466`?

**Comment by oguimbal** [comment]
I now works with the latest update (it previously only worked in workspaces which had not the "open"  package installed locally)
...  go figure 🤷‍♂️ 

Thanks !
