### ISSUE TITLE
Error " bad option: --harmony-top-level-await" while trying to run code

### ISSUE THREAD

**Issue by SanderElias** [wallabyjs/quokka#780]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
import { loadRoutes } from './loadRoutes';
const myRoutes = await loadRoutes('./testroute');
console.log(myRoutes)
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka PRO 'index.ts' (node: v18.0.0, TypeScript: v4.6.3)​​​​
/home/user/.nvm/versions/node/v18.0.0/bin/node: bad option: --harmony-top-level-await  
```

### Code editor version

Visual Studio Code-insiders

### OS name and version
Linux

edit:
This only happens if there is:
```json
  "type": "module",
```
in the `package.json` When that is changed to commonJs, the problem changes to:
![image](https://user-images.githubusercontent.com/1249083/167338370-463dabce-2562-46af-9b61-b3de3606d9a9.png)

**Comment by NikGovorov** [comment]
What version of Quokka.js extension do you use?

**Comment by smcenlly** [comment]
Can you also please provide us with your `tsconfig.json`?

**Comment by SanderElias** [comment]
tsconfig:
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
  }
}
```

I have the latest version that's in Code-insiders. Don't know how to get  the version number.

**Comment by smcenlly** [comment]
We're not getting the problem. Do you have a `.quokka` configuration file either for your project, or in your user directory (`~/.quokka/config.json`).

**Comment by SanderElias** [comment]
I don't have a `.quokka` config file. 
This is the `~/.quokka/config.json`:
```json
{"pro":true}
```

**Comment by smcenlly** [comment]
Could you also please answer @NikGovorov's question: 

> What version of Quokka.js extension do you use?

You can find this in the Installed Extension settings:

![image](https://user-images.githubusercontent.com/2074089/167354495-7d0cc936-a998-4a1b-b0b6-10c632d5bebf.png)

**Comment by SanderElias** [comment]
that helps:
![image](https://user-images.githubusercontent.com/1249083/167380108-f881ee9c-ba0d-4a1f-8efa-427451ce71d3.png)

**Comment by NikGovorov** [comment]
Could you please clone the [repo](https://github.com/wallabyjs/quokka-780), run Quokka on `index.ts` and see whether it works?

**Comment by SanderElias** [comment]
result:
![image](https://user-images.githubusercontent.com/1249083/167398921-c7b502dd-fe3a-4f91-ac21-e8d442eb9725.png)

**Comment by NikGovorov** [comment]
Could you please execute `printenv NODE_OPTIONS` in VS Code terminal? Does it by any chance have `--harmony-top-level-await`?

**Comment by SanderElias** [comment]
![image](https://user-images.githubusercontent.com/1249083/167401426-fecaac54-95ba-4fb3-8919-82ea64fa497f.png)
It doesn't
