### ISSUE TITLE
Webpack Config for monorepo

### ISSUE THREAD

**Issue by davidpanzarella** [wallabyjs/quokka#781]
### Issue description or question
Some context first: in our particular setup, we have several nested services in our monorepo. Most of those services have their own babelrc or babel.config., along with some having their own Webpack configs, while others combine multiple services in a single Webpack config.

I've tried several approaches based on the [document page](https://quokkajs.com/docs/configuration.html), along with attempts at using the alias plugins. Needless to say, the modules never resolve. At the basic level, babel complains about never being found, which is odd because our top-level `node_modules` definitely has babel as a dependency, yet the path Quokka is erroring on is the same as the root. This happens regardless of how we implement: package.json, .quokka, etc.

Clearly, I'm doing something wrong and do not understand. 😆  So I'm hoping someone can shed some light? 🙏 

### Sample code
Here is an how some of the aliases look in one of our webpack configs
```javascript
    alias: {
      alias: path.join(paths.serviceApi, '/alias'),
      clients: path.join(paths.serviceApi, '/clients'),
      config: path.join(paths.serviceApi, '/config'),
      constants: path.join(paths.serviceApi, '/constants'),
      controllers: path.join(paths.serviceApi, '/controllers'),
      listeners: path.join(paths.serviceApi, '/listeners'),
      middleware: path.join(paths.serviceApi, '/middleware'),
      models: path.join(paths.serviceApi, '/models'),
      queues: path.join(paths.serviceApi, '/queues'),
      routes: path.join(paths.serviceApi, '/routes'),
      services: path.join(paths.serviceApi, '/services'),
      shared: paths.appShared,
      socketActions: path.join(paths.serviceApi, '/socketActions'),
      utils: path.join(paths.serviceApi, '/utils')
    }
```

Our `babel.config.js`, which is set as a `module.export`, exports all of our babelrcs and looks like this:
```
  const babelrcRoots = [
    '.',
    'src/admin',
    'src/api',
    'src/ml',
    'src/puppeteer',
    'src/shared',
    'src/web',
    'src/webhooks',
    'src/website'
  ];
```

I would hope that Quokka could just piggyback our node services, and use them to display things inline within VSCode, but I likely am not interpreting how it interacts correctly. Anyone have thoughts on how we configure Quokka with this type of setup?

**Comment by smcenlly** [comment]
When you start Quokka, are you starting in a scratch file (new / unsaved file) or are you starting on existing file(s)?

I'm not quite sure I understand exactly how your project is structured with the next repos, etc. I assume that your nested projects within your mono repo each have their own `package.json`?

Would you be able to put together a repo with a similar structure to your project that has the same issue so that we can see how it pieces together?

**Comment by davidpanzarella** [comment]
Thanks for the reply @smcenlly; sorry I took so long.

When working with JS files directly outside of my core project repo, everything works fine. You are correct in thinking that each mono repo has its own `package.json` handing its own dependencies. That said we are using Yarn workspaces to handle that, along with Webpack and docker to spin up/build are services so that they can talk to one another, handle differing environment variables, etc.

Could it be that I need to simply add quokka to each nested `package.json`? Unfortunately, it would be a fair bit of work to try to re-create our particular setup, but I would be happy to set aside  30 minutes to do a screen share with you if you're interested?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Hopefully you got everything working.
