### ISSUE TITLE
Live Logging Question

### ISSUE THREAD

**Issue by DmitriyMalayev** [wallabyjs/quokka#783]
I'd love to know if it's possible to show logging output on a line below the code instead of on the same line. or for it to wrap from one line to another line. 

### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
It is not possible to show logged output on the line below your code. Unfortunately the display options for logged values are limited by editor capabilities and right now VS Code does not allow us to wrap values to multiple lines.

Quokka for VS Code does show the value in the hover window, which may be helpful if you cannot see the full value inline. The hover will display if you hover over the variable with your mouse. You may also use the VS Code `Show Hover` command.
