### ISSUE TITLE
Differen output in quokka and Chrome when I try to import my handlebar markup file

### ISSUE THREAD

**Issue by Nikolay-Tymoshchuk** [wallabyjs/quokka#785]
### Issue description or question

Hello. I faced with such a problem in my small program - when I make an import from my handlebar file everything works fine and correctly in browser but in Quokka it thows me an error, that my imported module **is not a function** (in browser it shows me that this is function) and below by code Qoukka doesn`t work, coz see en error. If  I make not import but **const menueTpl = require ('./templates/list-render.hbs')** in Quokka everything works perfect and I see right output in Quokka console, but in Chrome it throws me a TypeScript error, that this is not a function and program didnt wont to work. Please help me, tell me, how to fix it. I hope it can works correctly in quokka and browser simultaneously.

### Sample code

import menuData from './js/menu.json';
import menueTpl from './templates/list-render.hbs';
console.log('menueTpl :>> ', menueTpl); //undefined in Quokka (show function in a browser console)

const refs = {
  menu: document.querySelector('.js-menu'),
  switcher: document.getElementById('theme-switch-toggle')
}

refs.menu.insertAdjacentHTML('beforeend', menueTpl(menuData)); // menueTpl is non a function

### Sample repository link

https://github.com/Nikolay-Tymoshchuk/goit-practice-additional

### Quokka.js Console Output

```
// quokka console output =>
menueTpl is not a function 
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​src/index.js:17:1​
undefined ​​​​​at ​​​​​​​​menueTpl​​​ ​src/index.js:3:30​
menueTpl :>>  undefined 
  ​​​​​at ​​​​​​src/index.js:3:1
```

### Code editor version

Visual Studio Code v1.67.2?

### OS name and version

Windows

**Comment by smcenlly** [comment]
Quokka [runs your code in node.js](https://quokkajs.com/docs/how-does-it-work.html) (if you run `node index.js` from command line, you should get the same result/errors in Quokka). If you are [emulating a browser environment](https://quokkajs.com/docs/configuration.html#jsdom) using Quokka (vs. running in the browser) then it is expected that there may sometimes be runtime differences (described in [our docs](https://quokkajs.com/docs/how-does-it-work.html)).

Quokka also doesn't have any first class support for handlebar files (`.hbs`), which your `dev` and `build` scripts are processing with `parcel` and `parcel-plugin-handlebars-precompile`, so I expect that will also cause you some problems as `node` does not know how to read/process `.hbs` files.

In your case, with your setup, we would recommend first getting your program to run from the command-line with `node.js`, and then you should be able to also run the same code in Quokka.
