### ISSUE TITLE
[Angular] Any file with imports throws error (quokka works fine on files without imports)

### ISSUE THREAD

**Issue by galloween** [wallabyjs/quokka#786]
### Issue description or question

Quokka works only on new files, but never on existing. 
Every/any import throws error. 
It thinks ALL FILES are "CommonJS modules" (and none of them are).
Please advise 🙏 

### Environment

Big monorepo, mulitple libraries & projects, Angular 13, Typescript 4.4, `nx`, node 12.20

### Sample code

```ts
// every import throws error:

import { log } from '../logger';

// in '../logger' :

export class log { ... }

export const doSomething = (...) => {...}
```

### Quokka config (.quokka file)
```json
{
  "stdEsm": false,
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node"
    }
  }
}
```

### Quokka.js Console Output

```shell
​​​​​Quokka PRO 'func-utils.objects.ts' (node: v12.20.0, TypeScript: v4.7.1-rc)​​​​
 
Named export 'log' not found. The requested module '../logger' is a CommonJS module, which may not support all module.exports as named exports. 
CommonJS modules can always be imported via the default export, for example using: 
 
import pkg from '../logger'; 
const { log } = pkg; 
 
  ​​​​​at ​​​​​​​​ModuleJob._instantiate​​​ ​internal/modules/esm/module_job.js:97​
  ​​​​​at ​​​​​​​​async ModuleJob.run​​​ ​internal/modules/esm/module_job.js:142​
  ​​​​​at ​​​​​​​​async Loader.import​​​ ​internal/modules/esm/loader.js:182​
```

### Code editor version

Visual Studio Code v1.68

### OS name and version

OSX

**Comment by smcenlly** [comment]
Could you please clone [this repo](https://github.com/wallabyjs/quokka-786) and check whether starting on `index.ts` works for you? 

If it works for you, can you please update our `tsconfig.json` to match your own and then see if if it fails? If it's still working, please inspect and update other differences between our project and yours, it should help us to isolate the problem.

Alternatively, could you please provide a minimal reproducible example?

**Comment by galloween** [comment]
Hi! thanks for your reply! 
The test repo works fine, even if i change the tsconfig to match ours, 
which I'm including below.

More observations: 

1) (in our repo) files without any imports work fine

2) (in our repo) if I add `"target": "esnext",` to `.quokka`, _every_ file with imports then gets this error:

```shell
​​​​​Quokka PRO 'func-utils.events.ts' (node: v12.20.0, TypeScript: v4.7.1-rc)​​​​
 
Unexpected token '.' 
  ​​​​​at ​​​​​​​​Loader.moduleStrategy​​​ ​internal/modules/esm/translators.js:140​
  ​​​​​at ​​​​​​​​async link​​​ ​internal/modules/esm/module_job.js:42​
```

3) (in our repo) if i change to node 16.13, the error is more verbose:

```shell
​​​​​Quokka PRO 'func-utils.objects.ts' (node: v16.13.1, TypeScript: v4.7.1-rc)​​​​
 
file://./src/lib/services/utils/functional-utils/func-utils.objects.js?session=w9df31653367528838:8 
import { IGNORE_PROPS_DEF } from './func-utils.const'; 
         ^^^^^^^^^^^^^^^^ 
SyntaxError: Named export 'IGNORE_PROPS_DEF' not found. The requested module './func-utils.const' is a CommonJS module, which may not support all module.exports as named exports. 
CommonJS modules can always be imported via the default export, for example using: 
 
import pkg from './func-utils.const'; 
const { IGNORE_PROPS_DEF } = pkg; 
 
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21) 
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5) 
    at async Promise.all (index 0) 
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24) 
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15) 
```

4) the minimal reproducible example is **any** basic Angular app (for example, generated with `ng new my-app`)
- here is such app here (the file exhibiting the issue is `main.ts`): https://github.com/wallabyjs/quokka-786/pull/1
with this example, changing to target esnext does not get rid of the issue (it never gets to next level "dot" error)

**our tsconfig**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": "./",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "strictNullChecks": false,
    "stripInternal": true,
    "baseUrl": "./",
    "paths": {
      "attendance-features": [
        "libs/features/attendance/features/src/index.ts"
      ],
       ...
    }
  },
  "exclude": [
    "node_modules",
    "tmp"
  ],
  "include": [
    "**/*.ts"
  ]
}

```

**Comment by smcenlly** [comment]
Thanks for the sample repo. Your files are not being generated in a way that allows them to be run in `node.js` (which is [how Quokka works](https://quokkajs.com/docs/how-does-it-work.html)). You can see this for yourself by running the following from your project root:

1. `npx tsc`
2. `node dist/out-tsc/main.js`

You can fix this by updating your `package.json` to include `"type": "module"` to tell Quokka/node that your project is using ES Modules. Alternatively, you may change your `.quokka` configuration to use `commonjs`:

**.quokka**
```
{
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node"
    }
  },
  "ts": {
    "compilerOptions": {
      "target": "es3",
      "module": "commonjs"
    }
  }
}
```

**Comment by galloween** [comment]
thanks! this indeed fixes it.

however, it would've been impossible to deduct this from the available documentation...
if quokka does not work out of the box in the default basic minimal angular app, I believe maybe it would be helpful for future generations if this snippet was included in the docs (in the angular section)...

thanks again!

**Comment by smcenlly** [comment]
> if quokka does not work out of the box in the default basic minimal angular app, I believe maybe it would be helpful for future generations if this snippet was included in the docs (in the angular section)...

Thanks for your feedback!

> btw, wallaby.js also totally doesnt work in angular apps (with karma)

Wallaby seems to be working for us both on the Angular app that you provided to us. If it's not working for you, would you mind creating a [new issue](https://github.com/wallabyjs/public/issues/new) in the Wallaby issues repo and providing your diagnostics report (instructions are detailed in the new issue template).

**Comment by smcenlly** [comment]
> if quokka does not work out of the box in the default basic minimal angular app, I believe maybe it would be helpful for future generations if this snippet was included in the docs (in the angular section)...

We've been playing around and Angular is working for us without any configuration in your sample application that you provided. Is there a reason that you created a Quokka file with: 

**.quokka** (project configuration file)
```
{
  "stdEsm": false,
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node"
    }
  }
}
```

If you delete this file, Quokka should work for you (unless you have a global `config.json` file with configuration).
