### ISSUE TITLE
Why Quokka not showed [...Array]?

### ISSUE THREAD

**Issue by mxcdh** [wallabyjs/quokka#788]
Hello

I have problem, that Quokka not showed result for this line:
```
[...Array(max - min + 1).keys()].map(i => i + min);
```

Below screenshot:
<img width="814" alt="image" src="https://user-images.githubusercontent.com/98115983/170252192-7f6bdf10-790b-458f-9682-113a384335df.png">
What is wrong, and how I can fix it?

**Comment by NikGovorov** [comment]
We could not reproduce it on a simple quokka https://codeclip.io/NikGovorov/quokka788
![image](https://user-images.githubusercontent.com/129254/170253116-5eddae09-8604-4966-839b-5cf090a343d5.png)
Could you please try to run those 2 lines separately and if it does not work correctly share `Quokka` output?

**Comment by mxcdh** [comment]
Another example:
ts-node working correct, but quokka not:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/98115983/170256129-6661ac68-bb7c-42a6-a489-ebcd00862ade.png">

**Comment by NikGovorov** [comment]
We don't set the `target` for typescript and apparently the default one(ES3/ES5) [does not support spread syntax correctly](https://www.typescriptlang.org/play?target=1#code/MYewdgzgLgBATgQzAcwKYwLwwBQFsCWYANDLggB4CUmAfDANoB0zAgnIgJ54UwC0phGAGoYARkqMA1qg4RslALqMyAB2zZ81DHXzCBYSgG4AsAChQkEABtUjKyGTZEKVNlEkArJSNmgA).

Try to add the following code on the top of your file, it should fix it

```typescript
({
  ts: {
    compilerOptions: {
      target: "es6",
    },
  },
});


const range = (min, max) => [...Array(max - min + 1).keys()].map((i) => i + min);
console.log(range(1, 5));
```

Also you may change the setting globally:
https://quokkajs.com/docs/configuration.html#global-config-file
https://quokkajs.com/docs/configuration.html#compiler-settings

**Comment by NikGovorov** [comment]
The latest version(1.0.477) of Quokka for VS Code sets `target` to `es6` by default.
