### ISSUE TITLE
cannot find node-esm-resolve-implementation

### ISSUE THREAD

**Issue by BrettBedarf** [wallabyjs/quokka#789]
### Issue description or question

When using the suggested quokka config settings for any typescript file including empty, I get an error

### Sample code

Any typescript file

.quokka

```
{
  "stdEsm": false,
  "nativeEsm": true
}
```

### Quokka.js Console Output

```
Cannot find module './node_modules/ts-node/dist-raw/node-esm-resolve-implementation' 
Require stack: 
- .../.vscode/extensions/wallabyjs.quokka-vscode-1.0.477/dist/wallaby/runners/node/quokka@1.0.0/initializer.js 
- .../.vscode/extensions/wallabyjs.quokka-vscode-1.0.477/dist/wallaby/server.js 
  ​​​​​at ​​​​​​​​Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename]​​​ ​./node_modules/@cspotcode/source-map-support/source-map-support.js:811
```

### Code editor version

Visual Studio Code v1.67.2

### OS name and version

OSX

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. We've added support of  `ts-node` 10.8.0 and have released a new version of Quokka for VS Code that fixes the problem (v1.0.478).
