### ISSUE TITLE
Quokka  did not start with notification pop up message saying that "Can not start node.js process (node). 

### ISSUE THREAD

**Issue by garbolovo** [wallabyjs/quokka#796]
### Issue description or question

Quokka  does not start with notification pop up message saying that 
`"Can not start node.js process (node).  You may use the "node" setting to configure the location of node."`
But in the console Node starts ok, 
`my-app git:(master) ✗ node --version
v16.14.2
`

I have PRO License , please help ASAP !

### Sample code

no code

### Sample repository link

No
### Quokka.js Console Output

Nothing, quokka did not start

// paste your quokka console output here
Nothing, quokka does not start,  nothing get in console

### Code editor version

Webstorm WebStorm 2021.1.3
Build #WS-211.7628.25, built on June 30, 2021

### OS name and version
MacOS Monterey 12.4

![111111](https://user-images.githubusercontent.com/50718692/177940740-bbaaf7b0-1476-4d95-a5ed-9e61d97de6b2.jpg)

**Comment by ArtemGovorov** [comment]
The link in the error popup loads [the docs page](https://quokkajs.com/docs/configuration.html#nodejs-version) with the solution:


> you may specify the path to the node executable in your [global Quokka config.json file](https://quokkajs.com/docs/configuration.html#global-config-file), for example:
```
{
    "node": "~/.nvm/current/bin/node"
}
or

{
    "node": "/Users/username/.nvm/versions/node/v7.7.1/bin/node"
}
```

**Comment by garbolovo** [comment]
Да  Пробовал
`Can not start node.js process (/Users/aleksei/.nvm/current/bin/node).`

у меня  нет такого каталога .nvm
![2222](https://user-images.githubusercontent.com/50718692/177943565-762ae7dd-fe8a-4225-a75d-8ac51598c5cd.jpg)

**Comment by garbolovo** [comment]
Почему закрыл тикет ? Проблема еще не решена !

**Comment by ArtemGovorov** [comment]
The issue was closed because the solution was suggested. If it's not working for you, just respond in this issue, and we'll keep helping with regardless of whether it's closed or not.

> Can not start node.js process (/Users/aleksei/.nvm/current/bin/node).

As the referenced docs page says, the paths are given as example. You need to find out where your node.js executable is located and specify it as the path. You may run this terminal command

> which node

to find out the path to put in the config.

> https://github.com/wallabyjs/quokka/issues/797

I'm closing this newly opened issue as the current issue is being discussed here.

**Comment by michaelwills** [comment]
@ArtemGovorov the other issue was deleted and this issue still persists on Webstorm Build #WS-222.3345.108, built on July 22, 2022 with Quokka 1.0.354. I have the correct node value set testing in both a JS and Typescript scratch file. It _has_ worked, sporadically. Now, not at all. This is a fairly new issue as in older 1.x versions I didn't have trouble.

**Comment by smcenlly** [comment]
@michaelwills - could you please share your [global Quokka configuration file](https://quokkajs.com/docs/configuration.html#global-config-file) where your [node version](https://quokkajs.com/docs/configuration.html#nodejs-version) is configured?

**Comment by michaelwills** [comment]
Thanks @smcenlly! My global config file is only
```
{
  "pro": true
}
```

My node version was set using the `nvm` style and... I just realized... I was using inline style of per-file configuration at the head of a JS/TS file.  I'll try the per-project or `package.json` style config the next time I launch it to see if it works as expected there. Inline doesn't seem to work.

**Comment by smcenlly** [comment]
> My node version was set using the nvm style and... I just realized... I was using inline style of per-file configuration at the head of a JS/TS file. I'll try the per-project or package.json style config the next time I launch it to see if it works as expected there. Inline doesn't seem to work.

Quokka only supports setting the node version in your **global** Quokka configuration file: `~/.quokka/config.json`.
