### ISSUE TITLE
issue with node 18.6.0: ERR_LOADER_CHAIN_INCOMPLETE

### ISSUE THREAD

**Issue by SimonSiefke** [wallabyjs/quokka#800]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
const add = (a, b) => {
  return a + b;
};

add(1, 2); //?
```

package.json:
```json
{
  "type": "module"
}

```

### Quokka.js Console Output

```
node:internal/errors:477 
    ErrorCaptureStackTrace(err); 
    ^ 
 
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/simon/.vscode/extensions/wallabyjs.quokka-vscode-1.0.489/dist/wallaby/runners/node/quokka@1.0.0/hooks-v2.mjs 'load'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return. 
    at new NodeError (node:internal/errors:387:5) 
    at ESMLoader.load (node:internal/modules/esm/loader:624:13) 
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:472:11) 
    at async link (node:internal/modules/esm/module_job:67:21) { 
  code: 'ERR_LOADER_CHAIN_INCOMPLETE' 
} 
 
Node.js v18.6.0 
```

### Code editor version

Visual Studio Code v1.69.1

### OS name and version

Ubuntu 22.04

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This was the result of a breaking change to node 18's experimental ESM loader hooks. A number of other JavaScript tools have the same problem being reported.

Quokka for VS Code `v1.0.490` should now work for you with the latest version of node 18.
