### ISSUE TITLE
Handle mts and cts extensions in IntelliJ / WebStorm scratch files

### ISSUE THREAD

**Issue by geggo98** [wallabyjs/quokka#804]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

IntelliJ / WebStorm comes with support for TypeScript 4.7 and ESM modules since end of July 2022. Previously, it heavily complained when using top level await or importing ESM modules (although Quokka just ran them fine). These errors disappear, when one renames the file using the "mts" extensions, telling the IDE that it's in fact a module file.

Unfortunately, the Quokka context menu then also disappears and Quokka refuses to run on this file. An already running Quokka session continues to run.

Examples: 

- "ts" file, with errors messages <img width="708" alt="image" src="https://user-images.githubusercontent.com/54929/181189232-a21b2795-ac4f-4d02-8329-1641d11f9e94.png">
- "ts" file with Quokka context menu 
![image](https://user-images.githubusercontent.com/54929/181189993-3ae99b04-e550-4963-89a4-4af2571bff8d.png)
- "mts" file without errors but also without Quokka context menu 
<img width="708" alt="image" src="https://user-images.githubusercontent.com/54929/181189941-a8a3b64c-40e1-4a9d-b31d-7ecb2a52fc9c.png">

### Code editor version

IntelliJ 2022.2

### OS name and version

OSX

**Comment by smcenlly** [comment]
We have added support for `.mts` and `.cts` files in the latest version of Quokka for IntelliJ (`v1.0.354`).
