### ISSUE TITLE
Quokka doesn't do anything

### ISSUE THREAD

**Issue by NikolaiWaerpen** [wallabyjs/quokka#814]
### Issue description or question

Hi! I've previously used Quokka and found it really helpful. I have now switched jobs and have a new Mac. When I tried setting it up on this one I've run into an issue. Quokka doesn't do _anything_. I have attempted switching node versions from 16.13.1 to 18.8.0 and enable debugging, but to no avail. I get no errors, nothing.

My quokka config.json file:
```
{
  "pro": false,
  "node": "/Users/nikolai/.nvm/versions/node/v18.8.0",
  "debug": true
}
```

### Sample code

```javascript
const test = 1
console.log(test)
```

### Quokka.js Console Output

![image](https://user-images.githubusercontent.com/59408867/187168920-9bc923fc-bde3-49de-807c-4033e93db6d8.png)

### Code editor version

VS Code
Version: 1.70.2 (Universal)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

### OS name and version

OSX 12.5.1 (21G83)

**Comment by smcenlly** [comment]
Quokka needs to be started on an existing file using the VS Code command, `Quokka.js: Start on Current File`. Alternatively, it may be started with `Quokka.js: New JavaScript File`.

Could you please try running the command, `Quokka.js: New JavaScript File` and then pasting your code there to confirm whether Quokka is working for you? It should work for you.
