### ISSUE TITLE
Quokka not able to start up

### ISSUE THREAD

**Issue by jjjjn2** [wallabyjs/quokka#815]
I just installed Quokka and I am getting this output from Quokka:

​Quokka
Error: EPERM: operation not permitted, open 'C:\Users\MyUser\.quokka'
    at Object.openSync (node:fs:585:3) 
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812) 
    at Object.writeFileSync (node:fs:2157:35) 
    at WebSocketServer.emit (node:events:526:28) 
    at Server.emit (node:events:526:28) 
    at onParserExecuteCommon (node:_http_server:727:14) 
    at onParserExecute (node:_http_server:641:3)

**Comment by ArtemGovorov** [comment]
Can you please try running your VS Code as administrator to see if it helps?

**Comment by jjjjn2** [comment]
It did, it started working perfectly, I assume that since the folder is already created, I don't need to run VSCode as administrator every time, correct?

**Comment by ArtemGovorov** [comment]
Correct, we don't expect it needs administrator to run, please try and let us know if hit any issues.

**Comment by jjjjn2** [comment]
No, I started up without admin rights and it gave me this error:

​Quokka
Error: EPERM: operation not permitted, mkdir 'C:\Users\JRC\.quokka\data\uvq7k' 
    at Object.mkdirSync (node:fs:1386:3) 
    at WebSocketServer.emit (node:events:513:28) 
    at Server.emit (node:events:513:28) 
    at onParserExecuteCommon (node:_http_server:755:14) 
    at onParserExecute (node:_http_server:669:3)

**Comment by ArtemGovorov** [comment]
Oh, ok. In this case please try providing the user that you are running VS Code under the permissions to write to the `C:\Users\JRC` folder.

**Comment by jjjjn2** [comment]
I'm using JRC, I don't know why it can't write to itself, or is there something I have to do first?

**Comment by ArtemGovorov** [comment]
@jjjjn2 When Quokka worked for you as administrator, has it created the `C:\Users\MyUser.quokka` folder, or the `C:\Users\MyUser\.quokka` folder on your disk?

**Comment by smcenlly** [comment]
Could you also please tell us if you are running Quokka within a WSL environment?

**Comment by jjjjn2** [comment]
> Could you also please tell us if you are running Quokka within a WSL environment?

It's not, just windows 10

**Comment by ArtemGovorov** [comment]
@jjjjn2 Can you please also check https://github.com/wallabyjs/quokka/issues/815#issuecomment-1236494029?

**Comment by jjjjn2** [comment]
> @jjjjn2 Can you please also check https://github.com/wallabyjs/quokka/issues/815#issuecomment-1236494029?


It created Myuser.quokka not myuser/.quokka

**Comment by jjjjn2** [comment]
> @jjjjn2 When Quokka worked for you as administrator, has it created the `C:\Users\MyUser.quokka` folder, or the `C:\Users\MyUser\.quokka` folder on your disk?

It created C:\Users\JRC\.quokka

**Comment by smcenlly** [comment]
We believe that we have found and fixed your problem. Could you please:

1. Uninstall Quokka from VS Code
2. Close all VS Code instances
3. Delete the `C:\Users\JRC.quokka` folder (if it exists)
4. Reinstall the latest version of Quokka for VS Code (`v1.0.501`)
5. Restart VS Code as your user (**NOT** as Administrator)

It should work for you. If you have any other problems, please let us know.

**Comment by jjjjn2** [comment]
There is no JRC.quokka, however, there is a JRC\.quokka

**Comment by jjjjn2** [comment]
There is also a .wallaby folder in JRC

**Comment by smcenlly** [comment]
You do not need to delete any other folders. Have you tried the latest version? Is it working for you now?

**Comment by jjjjn2** [comment]
I reinstalled Quokka, started VS Code as my user, and it's not working, this is the output:
 `​Quokka
Error: EPERM: operation not permitted, mkdir 'C:\Users\JRC\.quokka' 
    at Object.mkdirSync (node:fs:1386:3) 
    at WebSocketServer.emit (node:events:513:28) 
    at Server.emit (node:events:513:28) 
    at onParserExecuteCommon (node:_http_server:755:14) 
    at onParserExecute (node:_http_server:669:3) 
 
`

**Comment by jjjjn2** [comment]
I did reinstall to the latest version(1.0.501)

**Comment by smcenlly** [comment]
Can you please try and delete the `.wallaby` and `.quokka` folders as well? It's possible that these were created by your Administrator user, which is why it's not working for you.

**Comment by jjjjn2** [comment]
I deleted them and it's still giving the same error

**Comment by smcenlly** [comment]
Can you please:

1. Run `cmd.exe` (**not** administrator)
2. Run `CD \Users\JRC`
3. Run `mkdir .quokka`

Does it work for you?

**Comment by smcenlly** [comment]
This thread may also be useful in diagnosing your issue:

https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows

It has a number of suggestions that you may try, ranging from incorrect node configuration to virus scanner related issues.

**Comment by jjjjn2** [comment]
> Can you please:
> 
> 1. Run `cmd.exe` (**not** administrator)
> 2. Run `CD \Users\JRC`
> 3. Run `mkdir .quokka`
> 
> Does it work for you?

No it didn't work for me

**Comment by smcenlly** [comment]
It sounds like you have an underlying permission issue as you should be able to do this for your user profile without adminsitrator privileges. 

Quokka (and many other desktop programs) needs to be able to write to your user directory.

Please [update the folder permissions](https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-change-folder-and-file-permissions/465f2b42-63dd-4486-8dd1-c870290efeed) for `\Users\JRC` so that you can run `mkdir .quokka` from the command-line, and then Quokka should work for you.

**Comment by jjjjn2** [comment]
Oh ok, I have been getting errors linked to that, should I change the permission that groups and users have or something else?

**Comment by smcenlly** [comment]
Yes, you will need to change the permissions. The [link I provided above](https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-change-folder-and-file-permissions/465f2b42-63dd-4486-8dd1-c870290efeed) provides steps for doing that.

**Comment by jjjjn2** [comment]
It worked, thank you very much, I don't know why my settings were like that but it worked
