### ISSUE TITLE
"Quokka globals" to change some behaviors

### ISSUE THREAD

**Issue by Noriller** [wallabyjs/quokka#817]
Feature request: "quokka globals"

---

Some things with side-effects, like fetches, can overload because of the multiple times it's run.

Yes, now we have the run once/on save, but it doesn't give the same experience.

So, why not some quokka globals like `cacheThis`,`mockThis`,`dry-run` and others?
(I say globals, but you could have us import it just like with node globals)

- `cacheThis` would run once and always give the same value as long as the parameters stay the same
- `mockThis` could be something like `mockThis(fn: Function, mockFunction: Function, returnMocked: boolean)` and be a switch you can toggle (even with a `if`)
- `dry-run` would basically work to count how many times and with what it was called

---
With tools like these, you could supercharge quokka to do some cool things.

**Comment by smcenlly** [comment]
You can actually implement this behavior yourself today if you wish, either directly in your project or Quokka file, or with a [Quokka plugin](https://quokkajs.com/docs/configuration.html#plugins).

You can see a more robust example of caching network requests here:  https://github.com/wallabyjs/quokka/issues/637#issuecomment-841903706. This example is a little more robust and would also work with run once/run on save as well as when the [`recycle` setting](https://quokkajs.com/docs/configuration.html#node-process-reuse) is `true`.
 
When your code is running with Quokka, you also have access to `node` `global` and can add any functions to that if you wish. Any modifications you make to the `global` object will remain until your program restarts or is recycled. Which means you can have code that runs only once when you first start your Quokka file. For example:

```javascript
if (!global.quokkaStartTime) {
  global.quokkaStartTime = new Date();
}

// Date never updates
console.log(global.quokkaStartTime);

// Date updates each time the file is changed
console.log(new Date());
```

If you are using a Quokka plugin, you can also configure it to be used on all projects by updating your [global Quokka configuration file](https://quokkajs.com/docs/configuration.html#global-config-file).

If you go ahead and implement a set of functions that are helpful to you, we'd be happy to add your plugin to our docs.
