### ISSUE TITLE
Quokka does not produce same results as introduction video

### ISSUE THREAD

**Issue by markericson** [wallabyjs/quokka#822]
### Issue description or question

Following along with the [Quokka introduction video](https://www.youtube.com/watch?v=f_sEWa5hA0Q&feature=share&utm_source=EJGixIgBCJiu2KjB4oSJEQ&t=240) does not produce the same results as in the video.  I don't see the following demonstrated behaviors:

1. gray box around `return x + y` if `add(x,y)` never called.
2. `NaN` result to the right of `return x + y` when `add()` is called with no parameters
3. `9` result to the right of `return x + y` when the .js file contains the call `add(4,5)`

I know Quokka is active because I do see `9` to the right of `console.log(add(4,5))`

Is this perhaps obsolete behavior that is still in the introduction video? Or, is there a necessary config that enables that particular Quokka behavior?

### Sample code

```javascript
function add(x, y) {
  return x + y  // expected NaN as shown in video
}

add();
```
### Quokka.js Console Output

```​​​​​Quokka PRO 'QuokkaTest.js' (node: v18.10.0)​​​​```

### Code editor version

Visual Studio Code v1.72.1

### OS name and version

OSX 12.6

**Comment by smcenlly** [comment]
Quokka should product the same results as shown in the video.

By default, Quokka does not show values beside your code unless you select the value (or else use the magic comment) `//?` beside the line of code.

You can make Quokka always output the values of every line by enabling the `Auto Log` global setting. You can do this by running the VS Code command `Quokka.js: Quokka.js: Open Start View` and then enabling the `Auto Log` global setting.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/2074089/196061534-63334074-9dec-4757-8a3a-cd0e206fca34.png">

If you don't want to enable `Auto Log` by default, you can also toggle it for your current Quokka session at any time with the VS Code command, `Quokka.js: Toggle Auto Log`.

---

If you're still having problems, please provide us with some screenshots of your code when it's running as well as your Quokka.js `~/.quokka/config.json` in your user home directory and any VS Code Quokka.js configuration overrides.

**Comment by markericson** [comment]
I double-checked this, and I do see the gray box to the left of the function before there is a call as demonstrated in the video.

However, I see different behavior in the video with respect to the Quokka calculated value to the right of the return calculation.

```javascript
function add(x,y) {
    return (x + y); 
}

add()
```

The video at 4:23 shows `NaN` to the right of `return (x + y);` when `add()` is called without parameters. And displays the result of the `(x + y)` when parameters are passed to the `add(x,y)` function.

 I acknowledge that if I put `// ?` to the right of  `return (x + y);` then I do see NaN when no parameters are passed and the result when parameters are passed. However, the use of `// ?` is not discussed in the video.
 
 Perhaps this is old behavior demonstrated in the video, and now it is necessary to use `// ?`

**Comment by markericson** [comment]
Sorry, didn't mean to close this, would still like feedback on the discrepencies.

**Comment by smcenlly** [comment]
As per my reply above, it looks like the video is using the `Auto Log` setting. If you enable this, you should see the same.
