### ISSUE TITLE
Quokka cannot run a test for angular service

### ISSUE THREAD

**Issue by cwayfinder** [wallabyjs/quokka#823]
### Issue description or question

I get an error when trying to run a Jest test with Quokka.
When I run it with Jest it works as expected.

![image](https://user-images.githubusercontent.com/355902/196016476-75c85693-144a-411c-99c1-34c04e694721.png)

### Quokka.js Console Output

```
require() of ES Module /Users/tarashupalo/WebstormProjects/my/ae-editor/node_modules/@angular/core/fesm2015/testing.mjs not supported.
Instead change the require of /Users/tarashupalo/WebstormProjects/my/ae-editor/node_modules/@angular/core/fesm2015/testing.mjs to a dynamic import() which is available in all CommonJS modules.
	at Object.<anonymous> projects/form-gen/core/src/lib/schema2.service.spec.ts:1

```

### Code editor version

Webstorm 2022.2.3

### OS name and version

OSX Monterey 12.6

**Comment by smcenlly** [comment]
When Quokka runs your code, it runs the same way as if you had run `npx ts-node schema2.service.spec.ts` from the command-line. If you try this, you should get the same behavior.

In contrast, when you run tests with `jest`, `jest` is performing some additional processing such as transformations and also knows about `describe` and `beforeEach`, `it` functions being special and how to start executing your code.

If you would like to run your project's tests, our other product, [Wallaby.js](https://wallabyjs.com) may be more suitable for what you're trying to do.

You can read more about how Quokka works in [our docs](https://quokkajs.com/docs/how-does-it-work.html). You can also read a little more about Quokka's support for Angular projects on the same page.

**Comment by cwayfinder** [comment]
Thank you. I started using Wallaby and it does the job.

This article https://quokkajs.com/docs/quokka-vs-wallaby.html also helped to understand what tool I need.
