### ISSUE TITLE
QUOKKA cannot read navigator API. Says cannot read property of undefined. + Often says "Cannot instrument script.js

### ISSUE THREAD

**Issue by gybeasmz** [wallabyjs/quokka#826]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes
 yes

### Sample code

navigator.geolocation.getCurrentPosition <- doesn´t work even with JSDOM installed. The whole navigator API doesn´t work with Quokka.  Nevermind the syntax error on the picture. It doesn´t matter what I try.

Also very often quokka crashes or doesn´t load saying "cannot instrument script.js
Thanks for any help!

![image](https://user-images.githubusercontent.com/40023509/197036280-8d480013-17d1-4b6e-98f0-85a18b685715.png)

// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
This is a limitation of JSDOM. JSDOM does not provide `geolocation.getCurrentPosition` on navigator.

You may consider contributing to JSDOM to provide this functionality.

Closing this issue as it is a limitation fo Quokka due to downstream dependencies.
