### ISSUE TITLE
Getting error "Cannot find module 'core-js/modules/es.object.assign.js'"

### ISSUE THREAD

**Issue by bldunn-dev** [wallabyjs/quokka#831]
### Issue description or question

Nothing I do will get Quokka.js to work. My Pro license for JetBrain's Webstorm expired on May 10th, so I upgraded and used the Community version. I got the same error.

### Sample code

```javascript
const mine = { b: 2, c: 3, d: 4, e: 5 };
let result = { a: 1 };
result = {...result,...mine }; //?
result
```
### Sample repository link

I am using a scratch file. This is specific to my installation, I suspect. 

### Quokka.js Console Output

```
scratch_1.es6 (node: v14.18.1, babel: v7.19.1, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)

Cannot find module 'core-js/modules/es.object.assign.js'
Require stack:
- /Users/udunnbr/Library/Application Support/JetBrains/WebStorm2020.2/plugins/quokka-intellij/dist/runners/node/quokka@1.0.0/jsdomQuokkaPlugin.js
- /Users/udunnbr/Library/Application Support/JetBrains/WebStorm2020.2/plugins/quokka-intellij/dist/runners/node/quokka@1.0.0/initializer.js
- /Users/udunnbr/Library/Application Support/JetBrains/WebStorm2020.2/plugins/quokka-intellij/dist/server.js
	at Function.Module._resolveFilename internal/modules/cjs/loader.js:902
	at Function.Module._load internal/modules/cjs/loader.js:746
	at Module.require internal/modules/cjs/loader.js:974
	at require internal/modules/cjs/helpers.js:93
	at Module._compile internal/modules/cjs/loader.js:1085
	at Module._extensions..js internal/modules/cjs/loader.js:1114
	at Module.load internal/modules/cjs/loader.js:950
	at Function.Module._load internal/modules/cjs/loader.js:790
	at Module.require internal/modules/cjs/loader.js:974
	at require internal/modules/cjs/helpers.js:93

```

### Code editor version

Webstorm v2020.2.4

### OS name and version

OSX version 11.7 "Big Sur"

**Comment by smcenlly** [comment]
From your Quokka Console Output, it looks like your opened project is a `create-react-app` project and so Quokka is using automatically configuring babel, importing react, and setting up JSDOM for your scratch file.

From the error, it looks like `core-js` might be missing. Have you tried to import it?

If that doesn't help, or you don't want to import the file, you may disable Quokka’s automatic configuration for `create-react-app` projects by adding an autoDetect Quokka setting with a value of false in either your [global configuration](https://quokkajs.com/docs/configuration.html#global-config-file), or in your [project's `.quokka` configuration](https://quokkajs.com/docs/configuration.html#quokka-file-config) file:

```javascript
{
...
  "autoDetect": false
}
```

**Comment by bldunn-dev** [comment]
I was not able to import 'core-js' and get that to work. However, your second suggestion worked perfectly, so I will mark this issue as Closed.

To clarify for others, I updated my ~/.quokka/config.json file to look like this:
```
{
  ...
  "autoDetect": false
}
```

Alternatively, I put the config setting at the top of the Scratch file (within parens, which makes it an "IIFE"):

```
({
  "autoDetect": false
})
```
