### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Nigtellios** [wallabyjs/quokka#834]
### Issue description or question

I've started using Quokka PRO Trial as I was really impressed about possibilities. However, I have few of my own private projects on Browser's JS Runtime which works great both with frameworks and without. Problems starts to happens when I move to much more advanced, bigger repository, as I'm working on a games based on WebGL2 frameworks. We're mixing JS browser runtime with Node.js runtime inside, however, My quokka isn't working inside that project (propably because it's mixing many environments). The logging doesn't work, only one option which works is code profiler which successfully shows the outcome. I wonder if quokka would be ever able to work in such a environment.

My quokka's config:
```json
{
  "pro":true,
  "ts": {
    "compilerOptions": {
      "allowJs": true
    }
  },
  "logLimit": 200,
  "delay": 1500
}
```

Our .tsconfig:
```json
{
  "compilerOptions": {
    "rootDir": "./src",
    "moduleResolution": "node",
    "target": "es6",
    "module": "ESNext",
    "noImplicitAny": true,
    "removeComments": false,
    "baseUrl": ".",
    "paths": {
      ...
    },
    "forceConsistentCasingInFileNames": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitUseStrict": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "lib": [
      "webworker",
      "es6",
      "es2016",
      "scripthost",
      "dom"
    ],
    "outDir": "./dist/es6"
  },
  "include": [
    "./src/**/*"
  ]
}
```

And Basically, except not showint me any logs, the Quokka tabs is continously showing me this error in every file which I check in this project. I've read couple of similar issues and none of result works for me.
### Error Code:

```javascript
index.ts (node: v16.16.0, TypeScript: v4.3.5)

Cannot use import statement outside a module
	at Object.require.extensions.<computed> [as .js] ./node_modules/ts-node/src/index.ts:1045
	at Object.<anonymous> src/index.ts:1
```

### Sample repository link

Unfortunately I can't provide one, it's private repo.

### Quokka.js Console Output

```
index.ts (node: v16.16.0, TypeScript: v4.3.5)

Cannot use import statement outside a module
	at Object.require.extensions.<computed> [as .js] ./node_modules/ts-node/src/index.ts:1045
	at Object.<anonymous> src/index.ts:1
```

### Code editor version

IntelliJ IDEA Ultimate 2022.2.3

### OS name and version

Windows 11

**Comment by ArtemGovorov** [comment]
From your tsconfig.json, it looks like you are compiling your TypeScript code to ES modules, however your project package.json is not configured as ES module, hence the error when ts-node is trying to run your code. One option that may work for you is to override your tsconfig.json `module` setting to `CommonJs` in your Quokka config file as described at https://quokkajs.com/docs/configuration.html#compiler-settings.

**Comment by smcenlly** [comment]
Assuming that our reply helped fix your issue. If you're still having problems, please let us know and we'll reopen the issue.

**Comment by Nigtellios** [comment]
No, I just deleted Quokka as it can't handle more complex projects properly, and it's extremely annoying to running it on every file in IntelliJ.

**Comment by smcenlly** [comment]
Sorry to hear... Quokka runs in `node.js` so is limited with how it may integrated with your existing project, but should still be useful for you within a scratchpad context. You can read a little about how Quokka works [here](https://quokkajs.com/docs/how-does-it-work.html), it should help you understand applicable use cases.

For IntelliJ editors, Quokka does start automatically on `scratch` files only. If you don't like/want this behavior, it can be [disabled with a setting](https://quokkajs.com/docs/configuration.html#jetbrains-editor-scratch-files).

If you don't have a need for Quokka, our upcoming [Console Ninja](https://console-ninja.com) product may be useful for your purposes.

**Comment by Nigtellios** [comment]
I've taken your advice, bought Quokka pro and started using it as a scratchpad where I just test some functionalities before I introduce them into code. For sure it's a very nice tool to check JavaScript concepts before starting to write them in the code, saves a little bit of time and allows you to play with features a little bit more before caring about code reusability or just the feature in the scoped project itself. 👍
