### ISSUE TITLE
`bad option: --harmony-top-level-await` after `Quokka: start on current file`

### ISSUE THREAD

**Issue by scarf005** [wallabyjs/quokka#835]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
const foo = [1,2,3,4]

foo.map(x => x * 2)
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.js' (node: v16.14.2 - Electron)​​​​
/usr/share/code/code: bad option: --harmony-top-level-await 
```

### Code editor version

Visual Studio Code v1.73.1

### OS name and version

Linux Ubuntu 22.04

**Comment by NikGovorov** [comment]
Thanks for providing the detailed set of steps to reproduce the problem. We were able to duplicate the problem and have released a new version of Quokka for VS Code that fixes the problem (v1.0.511).
