### ISSUE TITLE
No output, does not work

### ISSUE THREAD

**Issue by Andrey-Yur** [wallabyjs/quokka#836]
### Issue description or question
Extention does not work. No output
Is this issue related to Quokka not outputting the expected results of your code?: Yes

Yes my code run with using `node.js`
### Sample code

```javascript
const c = 1; //?
console.log(c); //?
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output
No output
```
No output
```

### Code editor version
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.4.0-132-generic snap
Sandboxed: No

### OS name and version
Linux
Ubuntu 18
![image](https://user-images.githubusercontent.com/62293778/202576650-fd13e66b-7a06-495b-ba59-e3b672a2bfaa.png)
![image](https://user-images.githubusercontent.com/62293778/202577046-9dab77e4-d7fd-47e5-99a7-25285173537b.png)

**Comment by Andrey-Yur** [comment]
Hey I paid for the PRO licence. What is up?

**Comment by ArtemGovorov** [comment]
Hi, 
- have you [started Quokka](https://quokkajs.com/docs/#live-feedback) on the file? 
- if you have, and it still doesn't work, can you please share Quokka.js Console Output (Quokka.js output channel in VS Code)?

**Comment by Andrey-Yur** [comment]
Да запускал, вообще нет ничего ни в консоле, пусто

**Comment by smcenlly** [comment]
From Google Translate:

> Yes, I ran it, there is nothing in the console at all, it's empty. Nothing to send


To confirm, in your `1.js` file, you ran the VS Code command, `Quokka.js: Start on Current File` and have no results, and no errors displayed?

Can you please open the VS Code developer tools, with the VS Code command, `Developer: Toggle Developer Tools` and take a screenshot of your console output? It should look something like the screenshot below, except with some logs:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/2074089/202582911-6fbb5e8a-2188-43b3-8821-d36a2b29f671.png">

If the logs exceed your screenshot size, please copy/paste them instead.

**Comment by Andrey-Yur** [comment]
![image](https://user-images.githubusercontent.com/62293778/202583122-6ca50053-e738-4939-beba-2cee21b857ae.png)

**Comment by smcenlly** [comment]
You need to run the command in VS Code from the VS Code command palette:

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/2074089/202583487-1d583ce6-75e4-49c6-8c4e-2d3498042d3b.png">

---

Also, if you have installed VS Code using [`snap`](https://snapcraft.io) then you may also run into problems. There are various known issues (unrelated to Quokka) using snap that may occur as a result of snap sandboxing. Without custom flags at installation, or subsequent interface connections, snaps are confined to a restrictive security sandbox with no access to system resources outside of the snap which means that Quokka cannot run. You will find other extensions that spawn child processes are affected in a similar way.

If you have installed VS Code using snap, please uninstall it and instead download/install from the [VS Code website](https://code.visualstudio.com/Download).

**Comment by Andrey-Yur** [comment]
![image](https://user-images.githubusercontent.com/62293778/202584348-29aad622-1380-4679-921b-d3b35389dd16.png)

**Comment by smcenlly** [comment]
Your errors shows that you have installed VS Code using [snap](https://snapcraft.io/).

There are various known issues (unrelated to Quokka) using snap that may occur as a result of snap sandboxing. Without custom flags at installation, or subsequent interface connections, snaps are confined to a restrictive security sandbox with no access to system resources outside of the snap which means that Quokka cannot run. You will find other extensions that spawn child processes are affected in a similar way.

Please uninstall VS Code using `snap` and instead download/install from the [VS Code website](https://code.visualstudio.com/Download).

**Comment by Andrey-Yur** [comment]
Thks, I'll do
