### ISSUE TITLE
Clicking on codeclip icon doesn't do anything (quokka pro)

### ISSUE THREAD

**Issue by mbaljeetsingh** [wallabyjs/quokka#837]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
const users = [
  {
    firstName: 'Leanne',
    lastName: 'Graham',
    email: 'Sincere@april.biz',
  },
  { firstName: 'Ervin', lastName: 'Howell', email: 'Shanna@melissa.tv' },
];

const formattedUsers = users.map((user) => ({
  name: `${user.firstName} ${user.lastName}`,
}));
console.log(formattedUsers);

```

### Quokka.js Console Output
<img width="655" alt="image" src="https://user-images.githubusercontent.com/872762/203699681-1b76bcea-35bc-4b10-aa15-b320636521f2.png">

### Code editor version

Visual Studio Code v1.73.1

### OS name and version

OSX 13.0.1

**Comment by NikGovorov** [comment]
Could you please open developer tools (`Developers: Toggle Developer Tools` command), click the icon and share the output from the console here?

**Comment by mbaljeetsingh** [comment]
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/872762/203746927-8c230db2-f78d-403b-af53-559c89b2be51.png">
Nothing seems to be happening in console too when I click the icon

**Comment by NikGovorov** [comment]
Could you please check that `Do Not Disturb Mode` is disabled?
On the screenshot below it's enabled:

![image](https://user-images.githubusercontent.com/129254/203770522-db5c2496-726e-47bc-bef3-db2c2ff7978d.png)

**Comment by smcenlly** [comment]
Assuming from the 👍 in the comment above that this fixed your problem. Closing this issue.
