### ISSUE TITLE
Closures created within the initialization section of for loop 

### ISSUE THREAD

**Issue by rkrbashyan** [wallabyjs/quokka#838]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
for (let i = 0, getI = () => i; i < 3; i++) {
    console.log(getI());
}
```
### Quokka.js Console Output

```
0
1
2
```

### Expected Console Output

```
0
0
0
```

### Code editor version

Visual Studio Code v1.73.1

### OS name and version

OSX, 13.0.1

**Comment by ArtemGovorov** [comment]
When we run the code, it produces the expected output:
<img width="579" alt="Screen Shot 2022-11-26 at 9 39 58 am" src="https://user-images.githubusercontent.com/979966/204063401-0fb23a83-a34a-44f4-ba9d-35233f89eed1.png">

Can you please try creating new Quokka file, pasting your code and checking if it's working as expected?

By default Quokka reuses created node process, so it's possible that the `i` was closed over in global scope as you were typing the code. You may [use this setting](https://quokkajs.com/docs/configuration.html#node-process-reuse) to disable process reuse by Quokka.

**Comment by rkrbashyan** [comment]
Thank you. The actual problem is my babel preset config
```
    "babel": {
        "presets": ["@babel/preset-env"],
        "plugins": [["@babel/plugin-proposal-decorators", { "version": "2022-03" }]]
    }
 ```
