### ISSUE TITLE
JSDOM module missing!

### ISSUE THREAD

**Issue by AndreFoulem** [wallabyjs/quokka#839]
Issue:
I am getting this issue when I tried to run Quokka on current file:

''' Quokka console error '''
​​​​​Quokka 'binarytree_depth.js' (node: v18.12.0, plugins: jsdom-quokka-plugin)​​​​
 
Cannot find module 'jsdom' 
Require stack: 
- ./index.js 

I am using Visual Code 1.73 on Mac. I am running React from a template on Vite. I am trying to run quokka on a JS file. (not JSX).

**Comment by smcenlly** [comment]
It looks like you have configured Quokka to use `jsdom` but it is not available from your project.

I assume that `jsdom` is configured in your [global Quokka configuration](https://quokkajs.com/docs/configuration.html#global-config-file)?

You should be able to fix this by either removing `jsdom` configuration from your Quokka configuration, or else installing JSDOM for your project with `npm install jsdom`.
