### ISSUE TITLE
package.json Babel config?

### ISSUE THREAD

**Issue by corysimmons** [wallabyjs/quokka#84]
[Docs](https://quokkajs.com/docs/configuration.html#babel) make it appear this only works with `.babelrc`.

If it does work with `package.json` `"babel"` object config, then can that be added to the docs?

**Comment by ArtemGovorov** [comment]
Thanks for the note, `package.json` Babel config is supported. We have changed the docs to mention it everywhere `.babelrc` is mentioned.
