### ISSUE TITLE
I can't configure quokka with nvm

### ISSUE THREAD

**Issue by ludwig-pro** [wallabyjs/quokka#840]
### Description 

I can't configure quokka with nvm, I follow the documentation (here)[https://quokkajs.com/docs/configuration.html#nodejs-version]

Quokka try to use another version or just ignore the configuration 🤷‍♂️

```
which node
/Users/ludwig/.nvm/versions/node/v16.18.1/bin/node
```

quokka throw 

```
You may use the "node" setting to configure the location of node.

Can not start node.js process (/Users/ludwig/.nvm/versions/node/v16.15.0/bin/node), make sure your system has node.js installed.

/Users/ludwig/.nvm/versions/node/v16.15.0/bin/node ENOENT
```

<img width="1728" alt="Capture d’écran 2022-11-28 à 20 47 23" src="https://user-images.githubusercontent.com/62896243/204367386-65efd37e-9226-49f1-9211-f474702ebdca.png">

### Configuration

```json
{
  "pro": true,
  "node": "/Users/ludwig/.nvm/versions/node/v16.18.1/bin/node"
}
```

Visual Studio Code Version : 1.73.1 (Universal)
OSX - Ventura 13.0.1

**Comment by smcenlly** [comment]
Could you please see if there are any errors reported in the VS Code Developer Console (run the command `Developer: Toggle Developer Tools` and inspect the console output).

**Comment by smcenlly** [comment]
Please also try restarting your editor after making changes to the `node` setting in your `config.json` file, it may help.

**Comment by ludwig-pro** [comment]
![image](https://user-images.githubusercontent.com/62896243/204501476-9a42070f-9ca7-4c92-8638-078f4a34436b.png)
![image](https://user-images.githubusercontent.com/62896243/204501670-47014626-712a-4f44-a37b-1fcd1a629a5a.png)

**Comment by ludwig-pro** [comment]
Hi, thanks for your reactivity, I profile to say that I have an old version of quokka, my license has expired

**Comment by ludwig-pro** [comment]
I have restarted vscode :/

**Comment by smcenlly** [comment]
> I have an old version of quokka, my license has expired

Can you please try the latest version of Quokka to see if you have the same problem? You can run the VS Code command, `Quokka.js: Switch to 'Community' Edition` to try the latest version if your license has expired.

**Comment by ludwig-pro** [comment]
hummm latest version of Quokka.js works well! 
I guess the latest vs code upgrade breaks the support of my outdated pro Quokka.js version
