### ISSUE TITLE
There is no output, and no obvious errors. What happened?

### ISSUE THREAD

**Issue by ChrisADrake** [wallabyjs/quokka#842]
### I'm just using the free Quokka.js version, but nothing is displayed. 
The only pop-ups are from VS Code, and they don't match the output in the example GIF's (?) or from another user. Nothing is in the value explorer, too. I have reinstalled the extension several times, I have rebooted my computer. If I tell it to start on a file, the developer console outputs that Quokka.js has stopped.

Is this issue related to Quokka not outputting the expected results of your code?: Yes

🪓 If you answered Yes above, please confirm that your code runs from the command-line using `node.js`

```
PS F:\codeyourshop.com\ChrisADrake.github.io> node index.js
15
10
5
```

### Sample code

```javascript
let num = 15;
let newNum = num - 5;
console.log(num);
let nnn = num - 10;
console.log(newNum);
console.log(nnn);
```

### Sample repository link

https://github.com/ChrisADrake/ChrisADrake.github.io/blob/f849d987ecafe909275876afde2c2cf340199327/index.js

### Quokka.js Console Output
->This is blank...
```

```
### Here is a screenshot:

![Quokka No Output](https://user-images.githubusercontent.com/30100727/204415977-9eaaec9d-4715-4886-a255-ccd9365a36f9.png)

### This is the only pop-up I see, but nothing after the line of code:

![This Happens](https://user-images.githubusercontent.com/30100727/204415999-ad3a60e9-486f-4a07-aa14-09585040fe0a.png)

### Code editor version
VS Code
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

### OS name and version

Windows 10 Home
Version 22H2

**Comment by smcenlly** [comment]
Did you run the VS Code command, `Quokka.js: Start on Current File` after opening `index.js`?

Could you please try closing all instances of your editor and reloading your project to see if that helps?

**Comment by ChrisADrake** [comment]
I have tried that. This just happened:

![Quokka Error](https://user-images.githubusercontent.com/30100727/204929169-1ab8102c-2a1f-408f-aed3-939cf6c3b9f1.png)


_It does take time for these errors to appear in the dev tools window._
Maybe these are the errors preventing Quokka from working?

### Something Interesting Happened
I closed the folder I was working in, which is an internal SSD where all the files & folders I use are, and just opened the specific folder index.js is located. **And It Works Now.** Huh. 🤷🏿 Hope this helps?

![Quokka works so far](https://user-images.githubusercontent.com/30100727/204931586-30acc73e-595e-46b1-81b3-544cb78e6f01.png)

**Comment by ChrisADrake** [comment]
Hmm, it never stated that Quokka started when I had the SSD selected as the folder/project to open, only when it stopped. And then it would never start again, only that Quokka had stopped again.

**Comment by smcenlly** [comment]
I assume if you open the same folder/directory as you initially did that Quokka is still not working for you?

Are you able to provide some additional details of the folder that's not working and its structure / contents?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back.
