### ISSUE TITLE
Could you please stop the nagging to buy this?

### ISSUE THREAD

**Issue by working-name** [wallabyjs/quokka#844]
# Extremely annoying. Please stop nagging.

**Comment by smcenlly** [comment]
What editor are you using? If you click `Don't Show Again`, you should only see the message once.

**Comment by working-name** [comment]
I'm using VS Code on windows and every time I open it I get a notification from your addon. It's extremely annoying. I don't know if it's because it connect to a remote code server (that's how windows works) but it just keeps coming back over and over again every time i open it. Driving me nuts.

**Comment by smcenlly** [comment]
Thanks for letting us know. Definitely sounds like an issue with remote workspaces. I assume you're not using [VS Code settings sync](https://code.visualstudio.com/docs/editor/settings-sync)? I would think you wouldn't have an issue if you were synchronizing your settings between your desktop and remote servers.

**Comment by smcenlly** [comment]
We've made some changes to explicitly ignore remote workspaces, which should solve you problem regardless of your settings sync. Sorry for the inconvenience, and thanks for letting us know about your problem.
