### ISSUE TITLE
Quokka keeps deleted variables and can refer to them despite being deleted?

### ISSUE THREAD

**Issue by essxiv** [wallabyjs/quokka#845]
### Issue description or question

I had a variable that created a 2d array. After I completely removed it from my js script, I could still reference it.. Not sure if this is intended or a bug?

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

Kind of?

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
(OSX)
Linux

**Comment by smcenlly** [comment]
This is expected behavior and can sometimes occur as a side-effect of Quokka reusing the node process to run you code faster.

If this causes you problems, you can disable this behavior by setting the [recycle](https://quokkajs.com/docs/configuration.html#node-process-reuse) setting to `true`.
