### ISSUE TITLE
"Clear File Values" doesn't clear "Only the first N values are automatically logged" message

### ISSUE THREAD

**Issue by wpchen** [wallabyjs/quokka#847]
### Issue description or question

In the first screenshot below, I have Quokka running fine on the below sample code.

<img width="592" alt="screenshot 1" src="https://user-images.githubusercontent.com/8423070/207722806-466ff9a7-88eb-4394-8e01-85cefd577fec.png">

The problem is when I "Clear File Values" (either via hitting "ESC ESC" or via VSCode command palette), the values of the variable are correctly cleared but the "Only the first 10 values are automatically logged..." message sticks around (see second screenshot below).
 
<img width="585" alt="screenshot 2" src="https://user-images.githubusercontent.com/8423070/207722887-5cfce6b4-7168-477f-b6d8-389d2989eb34.png">

I don't think the message should stick around (ie: all blue text should go away) when I "Clear File Values".

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
let a = 1;

for (let i=0; i < 11; i++) {
  a += i;
}
```
### Code editor version

Visual Studio Code v1.74

### OS name and version

OSX - Ventura 13.0.1

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in the latest version of Quokka for VS Code, `v1.0.517`.
