### ISSUE TITLE
Vs Code Word Wrap is not working for Quokka's output

### ISSUE THREAD

**Issue by SwapnilSanghvi** [wallabyjs/quokka#849]
I am using quokka for js file. with the help of this I would like to write  output In comment's. but when output and comments output is to long then word wrap Is not working and this is very bad user experience.

I hope your team will solve this issue asap.

**Comment by ArtemGovorov** [comment]
Unfortunately we don't have control over how VS Code wraps inline decorations. The issue is not specific to Quokka, the same behaviour can be observed in other extensions that are displaying inline decorations, such as GitLens.
