### ISSUE TITLE
Using array at syntax

### ISSUE THREAD

**Issue by 1alexvash** [wallabyjs/quokka#851]
Why is it working, but throws the warning?

![image](https://user-images.githubusercontent.com/46556479/210544057-6858621b-a687-4be0-8fac-8ee64aaf4025.png)

**Comment by ArtemGovorov** [comment]
The warning is not coming from Quokka and it not related to the extension, it's coming from VS Code TypeScript language service. If you create a new (unsaved) file without Quokka, set its language to TypeScript, then you will see the exact same warning.
