### ISSUE TITLE
using Quokka with an HTML file/DOM

### ISSUE THREAD

**Issue by Alex-Beltz** [wallabyjs/quokka#853]
### Issue description or question
I'm looking for a way to use Quokka on a project I'm working on.  I have an index.html file that is linked to my script.js file.  

I understand that node doesn't have the "window" or "document" objects, and further configuration is needed to do what I'm attempting.

I've read through the docs many times and searched this repo for help, I've found my way to where I thought it would work, but Quokka still doesn't see "document" (where I'm grabbing the HTML element in JS file).

I've installed jsdom, found the cofig file for Quokka and added 

{
  "pro": true, (this was the only thing there prior to me finding)

  "plugins": ["jsdom-quokka-plugin"],
  "jsdom": {
    "file": "./index.html"
  }
}

Can you please point out what I'm missing?

BTW I've been to Rottnest Island and saw the Quokkas haha, happy little guys!  Great name!

Thanks for your help!

node.js v18.12.1

### Sample code

```javascript

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
<div id="htmlElem">
    <script src="./script.js"></script>
  </body>
</html>

const htmlElem = document.getElementById("htmlElem") //document is not defined
```

### Quokka.js Console Output

```
npm install jsdom

added 60 packages in 4s

2 packages are looking for funding
  run `npm fund` for details
```

### Code editor version

VS Code v1.74.2

### OS name and version

Windows 10

![Quokka- config for DOM- question](https://user-images.githubusercontent.com/97088270/211227630-dcb2e4d6-b19d-48d9-8dc5-e3969df4f93d.PNG)

**Comment by ArtemGovorov** [comment]
Hi, can you please share your Quokka.js Console Output (`Output` tab in VS Code bottom panel, `Quokka` output channel)?

**Comment by Alex-Beltz** [comment]
You know what, there was a link there that had me 'press ctrl & click', and now it works haha.. sorry for the bother.  If possible, can we leave this chat here for future use of people trying to do the same?

Thanks again!

![Quokka- config for DOM- question2](https://user-images.githubusercontent.com/97088270/211230348-a4aff926-2e96-466b-b5bf-58d416a142c4.PNG)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! I'll close the issue, but it should be visible/searchable for other users encountering a similar issue.
