### ISSUE TITLE
quokka dont appear on vsc arch

### ISSUE THREAD

**Issue by AkkuV2** [wallabyjs/quokka#854]
i try to find Quokka.js on vsc extensions,but it shows "not extensions found"

im on arch, but if i try to find Quokka extension on windows it shows thats are here (on vsc extensions)

somebody can helpme with this?

**Comment by smcenlly** [comment]
The most likely reason Quokka is not showing in your extensions view is that you are not actually using `VS Code`, you have likely installed [`vscodium`](https://vscodium.com), which is a free libre Open Source build VS Code and does not include the standard VS Code marketplace.

The VS Codium extension marketplace is https://open-vsx.org. Unfortunatley we cannot publish any of our extensions there as all extensions published to that marketplace must be open source (as per their marketplace agreement).

Instead, you may manually [download Quokka from the VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) and install it using the `Install from VSIX...` command. You can read more about your marketplace options [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace).
