### ISSUE TITLE
When I save my JS file, Quokka disappears - how to save then?

### ISSUE THREAD

**Issue by dmintz2** [wallabyjs/quokka#859]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
When Quokka scratch file is saved on disk via Save File dialog, the file changes its name (and internal VS Code file URI scheme), so Quokka stops running on the file. 

This only happens after you save Quokka scratch file first time only, and you may restart Quokka on the saved file using Start on existing file command (`Cmd/Ctrl + K, Q`). Once the file is saved on disk and Quokka is running, it should continue working as expected.

**Comment by dmintz2** [comment]
thank you!
