### ISSUE TITLE
Quokka not working

### ISSUE THREAD

**Issue by stvrdeol** [wallabyjs/quokka#860]
### Quokka.js Console Output

```
Unexpected token '?' 
  ​​​​​at ​​​​​​​​Object.compileFunction​​​ ​vm.js:344​

```

### Code editor version

Visual Studio Code v1.70.3

### OS name and version

Windows 7

**Comment by smcenlly** [comment]
Can you please provide the complete code that you are trying to run, as well as the full Quokka Output window content? For example, see our screenshot below that shows both the code and the output window:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/2074089/215363126-a610d567-30cb-45dc-a616-4fc16be1cfd0.png">

**Comment by stvrdeol** [comment]
it does not work with any code
![Capture](https://user-images.githubusercontent.com/105144183/215444294-3ce26038-0d9c-4049-a92b-40d568d2d884.PNG)

**Comment by smcenlly** [comment]
From your output, I can see that you are using `node@13.14.0` which was released 3 years ago with end of life on 1 Jun 2020.

The reason it's not working for you is that you are using `jsdom` and the latest versions of `jsdom` require Node.js v14 or newer. (Versions of jsdom below v20 still work with previous Node.js versions, but are unsupported.); this is mentioned in their [docs](https://www.npmjs.com/package/jsdom). 

Internally, `jsdom` is using the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), which requires node v14+.

---

Please update to a newer version of `node` and it will work for you. You can see current version support [here](https://endoflife.date/nodejs).
