### ISSUE TITLE
Quokka Panel is missing in most projects with Webstorm's New UI Beta.

### ISSUE THREAD

**Issue by jktravis** [wallabyjs/quokka#861]
### Issue description or question

I'm running the latest version of Quokka along with the latest version of WebStorm. I'm using the new Beta UI found under the Appearance Tab. When this is enabled, I do not always see the Quokka panel Icon on the side bar. Some projects have it. Others don't. I am not permitted to share these. And I'm not sure what triggers it, therefore I am unable to provide a sample repo. 

I have tried to remove the plugin and reinstall it.

I don't know if this is something that needs to be addressed here or by JetBrains, though I have reported it to JetBrains as well. 

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

No

### Sample code

N/A

### Sample repository link

Unavailable as I am unable to share the affected projects and unable to recreate in a public project.

### Quokka.js Console Output

N/A

### Code editor version

Webstorm 2002.3.1 New UI Beta

### OS name and version
OSX

**Comment by smcenlly** [comment]
> though I have reported it to JetBrains as well.

I assume that you reported through their YouTrack site? Can you please share the link so we can review their response?

In the meantime, we'll try and see if we can duplicate the issue and understand why it's happening.

**Comment by smcenlly** [comment]
When you don't see Quokka, is it available from the `More tool windows` ellipsis?

<img width="211" alt="image" src="https://user-images.githubusercontent.com/2074089/216470908-c2d5a9a8-77a7-4fb2-8a20-6d82f3b53fca.png">

<img width="355" alt="image" src="https://user-images.githubusercontent.com/2074089/216470928-ac1fe04f-2a65-4469-8edd-af0c94ef6a92.png">

**Comment by jktravis** [comment]
> When you don't see Quokka, is it available from the `More tool windows` ellipsis?
> 
> <img alt="image" width="211" src="https://user-images.githubusercontent.com/2074089/216470908-c2d5a9a8-77a7-4fb2-8a20-6d82f3b53fca.png">
> 
> <img alt="image" width="355" src="https://user-images.githubusercontent.com/2074089/216470928-ac1fe04f-2a65-4469-8edd-af0c94ef6a92.png">
> 
> It seems that after using a tool from the `More tool windows` list, the tool then becomes visible in the side bar. I assume that this is intentional.

🤦 

Nothing to see here. 
https://media4.giphy.com/media/AEMyf9Oj6MpS8/giphy.gif?cid=ecf05e47c9vv87otgehv5vgg3gkucjnepzcc85fcj1rukl1c&rid=giphy.gif&ct=g
