### ISSUE TITLE
quokka fails to parse `import assertions` syntax

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/quokka#862]
### Issue description or question
While trying to import `json` using [import assertions](https://github.com/tc39/proposal-import-assertions), quokka is not able to instrument and parse the syntax

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
import data from "./index.json" assert { type: "json" };

console.log(data);
```

### Sample repository link

[sample repo](https://github.com/bhvngt/quokka_import_assertion)

### Quokka.js Console Output

```
Failed to instrument src/index.js
> 1 | import data from "./index.json" assert { type: "json" };
    |                                 ^ SyntaxError: Unexpected token (1:32)
  2 | console.log(data);
  3 | //# sourceMappingURL=index.js.map
```

### Code editor version

Intellij `v2022.3.2`

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. Import assertions support has been added in v 1.0.372+.

**Comment by bhvngt** [comment]
Thank you very much
