### ISSUE TITLE
Unable to activate Quokka.js

### ISSUE THREAD

**Issue by JerryApplegarth** [wallabyjs/quokka#865]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
Sorry to hear you're having problems. I assume you tried to follow the [steps described on our website](https://quokkajs.com/docs/license.html)?

Could you please detail the steps you are taking and any errors / behavior you are seeing?

Please also let us know what **Code editor** and **Operating System** you are using.

**Comment by JerryApplegarth** [comment]
I started quokka in VS Code.
This pop comes up:

[image: image.png]

There is no clickable link in this popup.  So, I go to the Quokka website.
No hint as to where I should place the license code.

I just need to know where to go.

Jerry Applegarth
Buy me a Coffee @

https://www.buymeacoffee.com/JerryApplegarth
541-643-1630

**Comment by smcenlly** [comment]
Unfortunately the image did not come through. You will need to log into github to post it.

Did you try the steps from my comment above from our docs: [https://quokkajs.com/docs/license.html](https://quokkajs.com/docs/license.html)? This will tell you how/where to place your license.

**Comment by JerryApplegarth** [comment]
Yes, I have been to that place on the website.  But it does not tell me how
to get to the place where I paste in my email address and code.  If I could
find it, I would be set and ready to go.
Jerry Applegarth
Buy me a Coffee @

https://www.buymeacoffee.com/JerryApplegarth
541-643-1630

**Comment by smcenlly** [comment]
If you are using VS Code or Sublime Text, please run the VS Code command, `Quokka.js: Manage License Key`. It should allow you to paste your license key.

If you are using a JetBrains editor, please use the Help | Quokka.js | Manage License menu item in your IDE.

**Comment by JerryApplegarth** [comment]
I got it, the instructions on the website were not helpful but I got it.
Jerry Applegarth
Buy me a Coffee @

https://www.buymeacoffee.com/JerryApplegarth
541-643-1630
