### ISSUE TITLE
Quokka in VPN

### ISSUE THREAD

**Issue by janniks** [wallabyjs/quokka#866]
### Issue description or question

Is it possible Quokka doesn't work in VPNs? I've had a lot of issues recently -- the normal Quokka failing to start `[---=--]` bug

I notice it's fixed when I disconnect my VPN. Would love to be able to use Quokka in a VPN (haven't tried without internet access yet). Please fix this! 😞

### Quokka.js Console Output

```
[Extension Host] Disconnected from wallaby core: 1006
```

![Screenshot 2023-03-23 at 14 32 05](https://user-images.githubusercontent.com/6362150/227220327-b906a67c-039a-4783-a56a-d4d7389a789f.png)

### Code editor version

Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

### OS name and version

macOS Ventura 13.2.1

**Comment by smcenlly** [comment]
Quokka does work with VPNs but will **NOT** work when your VPN is blocking local network traffic (traffic to localhost).

In your case, the error message shows that Quokka could not connect on to your local machine via WebSocket.

This is a problem with your VPN configuration and not Quokka.

If you can't find your VPN setting to allow local network traffic, please let us know what VPN you are using and we will take a look at their documentation and see if we can find it for you.

Closing this issue as this is not a Quokka fault and is not something we can fix within Quokka.

**Comment by janniks** [comment]
Interesting, thanks for the response. I'll try to figure out what my VPN is doing (all other localhost calls seem to work) 🤔
