### ISSUE TITLE
continue after hitting an error in vscode

### ISSUE THREAD

**Issue by Hifilo** [wallabyjs/quokka#871]
### Issue description or question

![Code_HLObRC9ArE](https://user-images.githubusercontent.com/92943726/235345775-75044a75-869d-4e8f-abe4-2ca7f1e46a5a.gif)

This is a very minor issue, but in this case the code that follows the bad function calls are correct, but because quoka hits the error, it stops  showing everything ahead of the error. Is it possible to configure Quoka  to show the errors, but continue as normal?

Any code where there is an error somewhere in the middle of the script
```javascript

//previous code

capitalizeString();          // capitalizeString is not defined

console.log(printString());  //printString is not defined

console.log(capitalizeString());  //capitalizeString is not defined

//Some More Code
```

### Code editor version
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0

### OS name and version
OS: Windows_NT x64 10.0.19045 (WSL)
Sandboxed: No

**Comment by smcenlly** [comment]
This is expected behavior and is by design. Quokka execution behavior for your code is the same as in the browser or when using node.js; execution will stop when an error is encountered.

If you want to continue after an error occurs, you may wrap your code with a try catch block, for example:

```javascript
try {
  capitalizeString();
} catch (e) {
  console.log(e);
}
```
