### ISSUE TITLE
Unable to use Axios even when installed in the Node project

### ISSUE THREAD

**Issue by jackmurra-rgare** [wallabyjs/quokka#872]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
const axios = require('axios')

const result = await axios.get('www.example.com')

console.log(result) //?
```

### Quokka.js Console Output

```
axios.js (node: v16.19.1)

axios.get is not a function
	at quokka.js:3:0
```

### Code editor version

IntelliJ IDE 2023.1.1
Build #IU-231.8770.65

### OS name and version

OSX Ventura 13.1 on Intel i7 - work computer
also happens in WebStorm on my m2 mac (latest OS) home computer

<img width="715" alt="Screenshot 2023-05-02 at 10 08 08 PM" src="https://user-images.githubusercontent.com/56085827/235826244-86b95f75-37dd-45ab-9302-cf7076056eac.png">
<img width="759" alt="Screenshot 2023-05-02 at 10 08 24 PM" src="https://user-images.githubusercontent.com/56085827/235826245-737f2fe1-0107-4167-821c-01b6f1c95bd9.png">
<img width="390" alt="Screenshot 2023-05-02 at 10 08 43 PM" src="https://user-images.githubusercontent.com/56085827/235826246-3f98837e-f79f-4278-bf12-304f0573aa41.png">

**Comment by NikGovorov** [comment]
Does it work if you add `default`

```javascript
  const axios = require('axios').default
  
  const result = await axios.get('https://wallabyjs.com')
  
  console.log(result) //?

```
?

**Comment by ArtemGovorov** [comment]
By default from CommonJs repos [Quokka is using `standard-things/esm` module](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await), that add support for top-level await, etc.

When `standard-things/esm` is used, it sometimes works a bit differently from the standard node module resolution. In this case to make it work you may use this:

```ts
  const axios = require('axios').default
  
  const result = await axios.get('https://wallabyjs.com')
  
  console.log(result) //?
```

If you would like Quokka to work the exact same way in terms of node module resolution, you may add the `stdEsm: false` setting to your [Quokka config](https://quokkajs.com/docs/configuration.html):

```
{
  ...
  "stdEsm": false,
}
```
(for example by creating `.quokka` file in the project with the `{"stdEsm": false}` content).
Please note that in this case however, the top level await will not work for you anymore, the exact same way it won't work if you run the code via node CLI without Quokka.

**Comment by jackmurra-rgare** [comment]
Thanks for the help Artem!
