### ISSUE TITLE
Quokka extension stopped working after upgrade to Pro

### ISSUE THREAD

**Issue by pandec** [wallabyjs/quokka#873]
### Issue description or question

Hi,

I just updated to Pro, and I'm having issues with Quokka in my VS Code (the latest version, running on MacOS).

I only get the values in Quokka output panel but no live comments, colour boxes next to the lines or anything in Value Explorer. I tested both in files I worked with Quokka before (on the Community version) and with new, empty files created with the Quokka command. Sometimes I see the comments briefly (after a 2-3 seconds delay), but they disappear a moment later. And usually 

Something like this:
<img width="780" alt="image" src="https://github.com/wallabyjs/quokka/assets/6330205/e8a5c8e1-d5f9-40a0-abda-b103c89b5a51">

But shortly after they dissapear:
<img width="771" alt="image" src="https://github.com/wallabyjs/quokka/assets/6330205/2106ca6c-d4bf-42f7-a8c8-c18adcaee2d9">

And the Value Explorer shows me only the message: "No logged values. Click to see the feature docs". 
<img width="1101" alt="image" src="https://github.com/wallabyjs/quokka/assets/6330205/e0177122-8a91-4816-adaf-413cd9b605b2">

As a sanity check, I disabled a bunch of extensions I installed recently, even back when it was still working fine + tried to use different workspaces. But nothing helped and I have no idea what else could be wrong. I haven't changed any configuration of the extension or anything like that.

// Edit:
I noticed that the colour blocks only appear when I have an error in the code, but then disappear 2-3 seconds after I fix it.

**Comment by smcenlly** [comment]
If you haven't already tried this, could you please uninstall and reinstall Quokka?

If that doesn't help, can you please try the following:

1. Check the VS Code developer tools console for any errors (open with the command: `Developer: Toggle Developer Tools`)
2. Create a new empty project and see if it works there; if it works here, please try adding dependencies and configuration from your project where it's not working until it breaks to isolate the problem.

**Comment by pandec** [comment]
Ok, I think I isolated the issue. Quokka breaks when I add "type": "module" to my package.json file.

This is what it looks like with module type:
<img width="1661" alt="image" src="https://github.com/wallabyjs/quokka/assets/6330205/bc6fa29d-be62-41cf-ab9e-e2dd46d2bfe9">

And this is the result of stopping Quokka, removing the line and restarting it without any other change:
<img width="1678" alt="image" src="https://github.com/wallabyjs/quokka/assets/6330205/2a3a8bce-fcfd-4e28-a985-e4fb8f9e7e05">

Adding and removing the type in package.json is literally the only change. But I do need to have the type set to module + I'm sure many more people do too. Any idea how this can be addressed?

**Comment by smcenlly** [comment]
Thank you for letting us know this was caused by `"type: "module"`. This was a recently introduced issue when we added support for node.js version 20.x.

Please update to the latest version of Quokka for VS Code (`v1.0.538`). It should now work for you.
