### ISSUE TITLE
"Cannot Find Package" for Vanilla Yarn2 + PnP (Zero-Installs)

### ISSUE THREAD

**Issue by webmonarch** [wallabyjs/quokka#875]
### Issue description or question

I have a vanilla yarn2 + PnP (Zero-Installs) project and Quokka cannot seem to find the dependencies. I am able to click the "Install for current file" option and it will work for the single process but fails again after restart.

### Sample code

```javascript
import fetch from 'node-fetch'

console.log('hello world!')

fetch('https://postman-echo.com/get')
    .then(response => response.json()) //?
```

### Sample repository link

https://github.com/webmonarch/quokka-support-yarn2-pnp

### Quokka.js Console Output

![cannot-find-package-1](https://github.com/wallabyjs/quokka/assets/471903/9f456bf5-95ae-43f5-babe-8dd5c94a449e)

### Code editor version

IntelliJ IDEA 2022.3.3 (Ultimate Edition)

### OS name and version

Apple M1 Max

**Comment by smcenlly** [comment]
Thanks for reporting your issue, and for the sample repo.

Before today, Quokka did not support loading `yarn2` dependencies when your project is using ES Modules. This is now supported in the latest version of Quokka. Please update your plugin version to `v1.0.384` and it should now work for you.

**Comment by webmonarch** [comment]
Just checked and 👍. Thanks for the quick fix!
