### ISSUE TITLE
Can you stop your popup?

### ISSUE THREAD

**Issue by jt6677** [wallabyjs/quokka#876]
"Get Quokka.js Pro 🚀 today with our limited time 40% May Sale discount!"    Your extension ignored the "Don't show again" and show your marketing message on every reload.

**Comment by smcenlly** [comment]
Do you click the `Don't show again` message? If so, you shouldn't see the message again after doing that.

If you are clicking `Don't show again`, can you please tell us a little about your environment? Are you running VS Code locally? Or are you connecting to a remote machine (e.g. docker, ssh, etc.)? If you're connecting to a remote machine, can you please let us know what type?

**Comment by jt6677** [comment]
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No                              The extension auto-upgraded to the newest. **Don't show again** did not work. The same popup shows up on every reload and on new workspace.

**Comment by jt6677** [comment]
I am using 30-40 ish extensions. All the popups would go away after  _Don't show again_  except Quokka and I un-install and re-install multiple times.

**Comment by ArtemGovorov** [comment]
Can you please share the contents of the `~/.quokka/state.json` file?

**Comment by jt6677** [comment]
{"lastUrlOpen":1643343469290,"nextCheck":"2022-12-19T00:00:00.000Z","th":1651627023941}     I have quokka related setting in settings.json.                       I uninstalled and installed and same popup issue.

**Comment by jt6677** [comment]
After uninstall, I did a search for "quokka" on my computer and manually deleted all the files. Then I installed again and the problem is gone.  FYI I guess.

**Comment by smcenlly** [comment]
Not sure why it kept displaying for you but thanks for letting us know that deleting the `~.quokka` folder in your home directory and reinstalling fixed the problem.
