### ISSUE TITLE
Cannot find module './node_modules/ts-node/dist/file-extensions'

### ISSUE THREAD

**Issue by swayf** [wallabyjs/quokka#878]
### Issue description or question

in idea it produces next output:
scratch_4.ts (node: v20.2.0, TypeScript: v4.8.4, plugins: jsdom-quokka-plugin)

Cannot find module './node_modules/ts-node/dist/file-extensions' imported from /home/swayf/apps/idea/config/plugins/quokka-intellij/dist/runners/node/quokka@1.0.0/hooks.mjs
Did you mean to import ./node_modules/ts-node/dist/file-extensions.js?

### Code editor version

Intellijet IDEA 2023.1.2  and with the previous versions the same

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and the fix is available in v1.0.389+.
