### ISSUE TITLE
Unable to use quokka with Typescript

### ISSUE THREAD

**Issue by sergeyzwezdin** [wallabyjs/quokka#88]
### Issue description or question

1. Create new typescript based app: `create-react-app test-app --scripts-version=react-scripts-ts`
2. Add `.env` file as well as add `baseUrl` to `tsconfig.json` to support absolute modules path.
3. Try to run quokka: `Ctrl+Shift+P` and `Start on current file` in `src/index.tsx`.

At this step quokka fails. I've added sample repository below.

### Sample repository link

https://github.com/sergeyzwezdin/quokka-issue-repro/tree/master/test-app

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v6.10.0, TypeScript: v2.4.2)​​​​
​​​​
​​To import TypeScript files from quokka, `ts-node` module must be installed​​
  at ​​​Module.load​​​ ​module.js:487​
  at ​​​tryModuleLoad​​​ ​module.js:446​
  at ​​​Function.Module._load​​​ ​module.js:438​
  at ​src/index.tsx:4​
```

### Code editor version

Visual Studio Code v1.15.1

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. The error message in your Quokka output suggests exactly what needs to be done: 

```
​​To import TypeScript files from quokka, `ts-node` module must be installed​​
```

You may install the module locally into the project, or to the [Quokka global config folder](https://quokkajs.com/docs/configuration.html#global-config-file).

**Comment by ArtemGovorov** [comment]
Also note that in order to use absolute module paths, you'll need to install the `tsconfig-paths` module as well. You may [read more about TypeScript configuration in our docs](https://quokkajs.com/docs/configuration.html#typescript).

**Comment by offg777** [comment]
I installed ts-node both globally and in my project. But it still says "​​To import TypeScript files from quokka, `ts-node` module must be installed​​"

**Comment by ArtemGovorov** [comment]
@offg777 Can you try cloning this repo https://github.com/wallabyjs/quokka-typescript-import-sample, running `npm i` and then running quokka on quokka.ts file to see if it's working for you?

**Comment by ArtemGovorov** [comment]
@offg777 It looks like it's correctly working for you on the sample project. [Project's files import feature is available in Pro edition only](https://quokkajs.com/docs/#project-files), you may switch to Pro edition trial (by using VS Code Quokka Switch edition command) to try it.

In your project Quokka doesn't even get to the point of showing the edition message, so there may be something wrong with the way you've installed `ts-node` (because the sample project is working for you as expected).

**Comment by offg777** [comment]
ok, thanks anyway

**Comment by laczor** [comment]
Hi,

I have cloned the repo, installed the dependencies and I have the same issue : 

​​Quokka #1 (node: v7.10.0, TypeScript: v2.8.3)​​​​
​​​​
​​To import TypeScript files from quokka, `ts-node` module must be installed​​


Do you have an idea what could be the problem?
Thank your support in advance,

**Comment by ArtemGovorov** [comment]
@laczor Are you using Quokka Pro or Quokka Community edition?

**Comment by laczor** [comment]
@ArtemGovorov Thank you for your swift comment!

I am using Quokka Community edition, with Visual Studio  Code (1.2.23) on Windows10 - 64 bit. However, when I switched to Pro edition the problem still exists.
Also when I try to 'install the missing package into the project, or into the file' I get the following answer
"No missing packages to install."

Thank you again for your help,

**Comment by ArtemGovorov** [comment]
Could you please share the repo that are you trying?

> Also when I try to 'install the missing package into the project, or into the file' I get the following answer "No missing packages to install."

Does Quokka report that there are some missing packages in the first place? Could you perhaps attach a screenshot, or a code sample?

**Comment by laczor** [comment]
Yes sure,

I have cloned the following repo: 
https://github.com/wallabyjs/quokka-typescript-import-sample

run npm install

Then I get the following error when I use Visual Studio Code: >Quokka Start on Current File

![image](https://user-images.githubusercontent.com/27684062/39970437-ba2e8664-56eb-11e8-82b5-565f7d4db82b.png)
 
and when i try to install the 'missing package with ">Quokka: Install missing package into the project"'

it says: "No missing packages to install."

Thank you for your swift response, i can't wait to get it done so i can use it in my typescripts projects, thanks again! :)

**Comment by ArtemGovorov** [comment]
Have you opened the project in VS Code (with `File - Open Folder`)? From the error message path, it looks like maybe not. I have just tried doing the exact same steps on the same OS, same editor version, same repo, and everything is working for me:

<img width="721" alt="screen shot 2018-05-14 at 11 53 50 am" src="https://user-images.githubusercontent.com/979966/39974727-d5e8e4bc-576d-11e8-907b-7bac0b3f4b0c.png">

> it says: "No missing packages to install."

But there are no missing packages to install, the message is correct. You need to use the command when [there are some missing packages](https://quokkajs.com/docs/#modules).

**Comment by laczor** [comment]
Yes, I have opened it with (with File - Open Folder), and the problem still exists. Maybe there is some a problem with node version of 7.10. I will try it with a different node version to test it out and post the result.

Thank you for your support ArtemGovorov!

**Comment by ArtemGovorov** [comment]
@laczor Please try with a newer node version, however I'd expect it should work with 7.10 (unless `ts-node` doesn't support it).

**Comment by dannyppaz** [comment]
Hi @ArtemGovorov i tried to run Quokka in .tsx file and got this error 

![image](https://user-images.githubusercontent.com/1591515/50690561-57f3a180-1060-11e9-965a-a8200f5c46f0.png)

Do you have an idea about this ?

**Comment by smcenlly** [comment]
@dannyppaz - can you please provide a code sample or sample repo so we can investigate further?

**Comment by DerJacques** [comment]
I'm experiencing the same issue as @dannyppaz 

Code example:
```typescript
import React, { Component } from "react";

class App extends Component {
  render() {
    return <div className="App" />;
  }
}

export default App;
```

Error:
```
​​​​Quokka 'Test.tsx' (node: v10.3.0, TypeScript: v3.1.6)​​​​
​​​​
​​Unexpected token <​​
  at ​​​new Script​​​ ​vm.js:74​
  at ​​​createScript​​​ ​vm.js:246​
  at ​​​Object.runInThisContext​​​ ​vm.js:298​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:670​
```

**Comment by cerebrl** [comment]
I am having the same problem as the original report documents. Here are the details:

1. Using Quokka Pro
2. I have a purchased license 
3. I'm using Node 6.11 and TypeScript 3.3
4. I have `ts-node` installed globally version 8.0
5. If I run "install missing packages", I get "No missing packages to install."
6. I'm using the latest of VS Code and the latest of Quokka
7. I've tried restarted all processes

The error is the "To import TypeScript files from quokka, `ts-node` module must be installed"

**Comment by ArtemGovorov** [comment]
> I have `ts-node` installed globally version 8.0

When you say globally do you mean `npm i ts-node -g`? If so, this will not work. As described in our Typescript [docs section](https://quokkajs.com/docs/configuration.html#typescript): you will need to install `npm install ts-node` either in your project’s folder or in the [global config folder](https://quokkajs.com/docs/configuration.html#global-config-file).

**Comment by cerebrl** [comment]
Wow, I'm really sorry I missed that, but thank you so much for the quick response. Cheers!

**Comment by PatternFinder** [comment]
I keep getting the "cannot find module" error

```
​​​​​Quokka PRO 'main.tsx' (node: v16.17.0, TypeScript: v4.8.3)​​​​
Cannot find module '.\src\App' imported from .\src\main.js
```

this is from `tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

the code is just react's template:
```
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
```
How do I fix the "cannot find module" issue?

**Comment by ArtemGovorov** [comment]
@PatternFinder can you please create a sample repo demonstrating the problem and share in a new issue?
