### ISSUE TITLE
Feature request: Quokka Pro Basic

### ISSUE THREAD

**Issue by coolCucumber-cat** [wallabyjs/quokka#881]
The Pro version has a lot of features I don't need like CPU profiling and performance testing and also costs 47€. But I also need some more basic features like being able to import things and live comments.

So I am requesting that there is a basic Pro version with:
- Live Value Display
- Live comments
- Importing files
 and either or both of these because I don't know what the difference is:
- Time Machine edit and continue
- Code Story

And it could be about 20€ because it's half the features

**Comment by smcenlly** [comment]
Thank you for your feedback and for using Quokka! ☺️

While we appreciate your suggestion for a basic PRO version, we currently have no plans to introduce such an offering. 

Our PRO version is designed to provide a comprehensive suite of features for a wide variety of needs, and we believe the pricing reflects this value. You may not know, but the PRO version initially was released with a much smaller subset of features, and the other features that you have mentioned were added later, at no additional charge to the PRO version.
