### ISSUE TITLE
Unexpected token ',' when using both an iterator and a private field

### ISSUE THREAD

**Issue by Filyus** [wallabyjs/quokka#885]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes
The code runs with ts-node successfully.

### Sample code

```ts
class MyClass {
  #value: number = 1;
  [Symbol.iterator]() {

  }
}
new MyClass();
```

### Quokka.js Console Output

```
​​​​​Quokka PRO 'temp.ts' (node: v18.14.2, TypeScript: v5.1.6, plugins: jsdom-quokka-plugin)​​​​
.\temp.js:8 
    [_MyClass_value = new WeakMap(), Symbol.iterator]() { 
                                   ^ 
 
SyntaxError: Unexpected token ',' 
    at internalCompileFunction (node:internal/vm:73:18) 
    at wrapSafe (node:internal/modules/cjs/loader:1176:20) 
    at Module._compile (node:internal/modules/cjs/loader:1218:27) 
```

### Code editor version

Visual Studio Code v1.81.0

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue has been fixed and the fix has been published in v1.0.550+ of the extension.
