### ISSUE TITLE
My Quokka Extention is not running,

### ISSUE THREAD

**Issue by FaisalMisbah23** [wallabyjs/quokka#886]
uokka.js 'Pro' requires activation. Please re-enter your email address to your Quokka.js 'Pro' manage license dialog.

**Comment by smcenlly** [comment]
If you do not have a PRO license, you may switch to use Quokka's Community edition with the `Quokka.js: Switch to 'Community' Edition` command.

If you do have a PRO license and it's not working for you, please email hello@wallabyjs.com and we will be able to help you out.
