### ISSUE TITLE
Can't add breakpoint via mouse when green gutter markers shown

### ISSUE THREAD

**Issue by janniks** [wallabyjs/quokka#888]
### Issue description or question

Gutter marks block the adding of breakpoints. As a user I would like to create breakpoints on a line that already ran (and is marked with a green gutter marker by Quokka), currently I'd have to right-click, or command-pallette (or hotkey), or disable Quokka and re-enable to get to add the breakpoint. (Lines without green markers, can add breakpoints)

Maybe clicking the gutter marker could create a breakpoint.

https://quokkajs.com/whatsnew/logpoints.html 

### Code editor version

Visual Studio Code Version: 1.81.1

### OS name and version

macOS 13.4.1

**Comment by smcenlly** [comment]
Thanks for your feedback and suggestion.

Unfortunately this is a limitation/bug within VS Code and there is no event / API that we can use to handle click events in the gutter.
