### ISSUE TITLE
Existing Project Files on Jetbrains/Webstorm

### ISSUE THREAD

**Issue by Poisonlocket** [wallabyjs/quokka#889]
### Issue description or question

Hi there, Quokka will only recognize new scratch files that get created while not finding my current Javascript files.

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Hi, can you please provide a screenshot of the issue?

**Comment by ArtemGovorov** [comment]
You may start Quokka on an existing file by using the Start Quokka context menu action in any opened file editor (you may also assign some shortcut to the action):
<img width="620" alt="Screen Shot 2023-08-24 at 2 04 05 pm" src="https://github.com/wallabyjs/quokka/assets/979966/aa4b6a23-1456-4624-83ca-55b95abb1ca8">
