### ISSUE TITLE
Different Language Documentations

### ISSUE THREAD

**Issue by Poisonlocket** [wallabyjs/quokka#890]
### Issue description or question
Add Documentation in more Languages like German spanish etc to make this great tool more accessible

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
Thanks for your request.

Unfortunately, we have don't have the resources to provide official support for our website / documentation / products in other languages at this time.

Having said that, while not ideal for you, you should be able to make use of publicly available services to automatically translate our website and docs (for example, [Google Website Translate](https://translate.google.com/?sl=auto&tl=en&op=websites)).

Using Google Translate to German for our website looks like this:

<img width="1319" alt="image" src="https://github.com/wallabyjs/quokka/assets/2074089/68fa98f6-9582-42a4-b61b-ae1d11cef78c">

and for our docs:

<img width="1542" alt="image" src="https://github.com/wallabyjs/quokka/assets/2074089/95b8844c-c4b0-4101-bff3-f7548ec04176">

**Comment by Poisonlocket** [comment]
I'd be more than happy to provide you with a full Documentation in german Free of charge.

**Comment by smcenlly** [comment]
We appreciate your offer, but at this time, we're unable to incorporate community-contributed translations. However, we'll keep your offer in mind for future considerations.
