### ISSUE TITLE
Loading "fs/promises" should not require a pro license

### ISSUE THREAD

**Issue by TheOptimisticFactory** [wallabyjs/quokka#893]
### Issue description or question

NodeJS v15 introduced promise-based APIs of their core modules including (but not limited to) `fs/promises`, `timers/promises`, `stream/promises`, `readline/promises`, which exposes functions similar of their callback counterparts.

Doing 
- `const fs = require('fs');` does not require a pro license to be ran by Quokka
- `const fs = require('fs/promises')` will reject with `​​​​​Only 'Pro' edition of Quokka.js supports project files import`

These are a core features of the programming language, not a project file.

While the problem can be circumvented by changing the require to be `const { promises: fs } = require('fs');`, it would be nicer for Quokka to support the simpler import syntax.

### Sample code

```javascript
'use strict';

const fs = require('fs/promises');

// Nothing else is needed
```

### Quokka.js Console Output

```
​Quokka 'demo.js' (node: v18.16.0)​​​​
Only 'Pro' edition of Quokka.js supports project files import. 
```

### Code editor version

Visual Studio Code v1.81.1

### OS name and version

Linux (Ubuntu 22)

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Quokka for VS Code, `v1.0.561`.
