### ISSUE TITLE
Import test helpers into quokka script

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/quokka#894]
I'd like to be able to import my test helper functions into a quokka script. Various combinations of ./tests ../tests etc don't seem to work.

Project uses vite, typescript, solid-js

I have the typical src/ and tests/ directories

### Code editor version

Visual Studio Code v1.81.1

### OS name and version

OSX

### tsconfig
```json
{
  "compilerOptions": {
    "allowJs": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "strict": true,
    "allowSyntheticDefaultImports": true,
    "noUncheckedIndexedAccess": false,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "types": ["vite/client", "node", "vitest/globals"],
    "baseUrl": ".",
    "outDir": "./dist",
    "rootDirs": ["src", "tests", "dev"],
    "paths": {
      "@/*": ["./src/*"],
      "@shared/*": ["../shared/src/*"],
    },
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "tests/**/*.ts", "tests/**/*.tsx", "dev/**/*.ts", "dev/**/*.tsx"],
  "references": [
    { "path": "../shared" }
  ]
}
```
### vite config (I removed some irrelevant bits)
```javascript
import { defineConfig, loadEnv } from 'vite'
import solid from 'vite-plugin-solid'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig(({mode}) => {
  process.env = {...process.env, ...loadEnv(mode, process.cwd())};

  return {

    plugins: [
      tsconfigPaths({loose: true}),
      solid({
        babel: {
          plugins: [
            // ["@locator/babel-jsx/dist", {env: "development"}],
          ],
        }
      })
    ],

    test: {
      environment: 'jsdom',
      transformMode: {
        web: [/\.[jt]sx?$/],
      },
      // solid needs to be inline to work around
      // a resolution issue in vitest:
      deps: {
        inline: [/solid-js/, /solid-app-router/],
      },
      threads: true,
      isolate: true,
      globals: true
    },

  }
})
```

**Comment by smcenlly** [comment]
We tried to reproduce your problem based on the details you provided but everything appears to be working for us. We have created a sample repo that you can try ([see here](https://github.com/wallabyjs/quokka-894)).

We tried importing from both `./test/` and `./tests/` for both an unsaved files, and an existing files.

I suspect that your problem is that you need `vite` to run your code but you haven't configured Quokka to run with `vite-node`. From [our docs](https://quokkajs.com/docs/index.html#vite-node-runtime):

> For projects using [Vite](https://vitejs.dev/), Quokka uses vite-node to run your JavaScript/TypeScript code in node.js using Vite’s resolvers and transformers. To use Quokka with vite-node, The [vite-node](https://www.npmjs.com/package/vite-node) package must be installed in your project; Quokka will automatically detect and use vite-node once it is installed.

---

If you're still having problems, can you please update the sample repo so that it fails in the same way so we can take a look?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Assuming that adding `vite-node` package to you project fixed the problem.
