### ISSUE TITLE
DOM operations

### ISSUE THREAD

**Issue by con-ssc** [wallabyjs/quokka#9]
Is it possible somehow to have some kind of DOM access for quokka?

```javascript
document.querySelector("body");
```

### Quokka.js Console Output

```
document is not defined​​
```

**Comment by ArtemGovorov** [comment]
It is [possible via the plugin](https://quokkajs.com/docs/configuration.html#community-plugins).

**Comment by con-ssc** [comment]
Here a suggestion for the docs at https://quokkajs.com/docs/configuration.html#global-config-file
On Windows <SYSTEM DRIVE>\Users\<USER ACCOUNT NAME> can be replaced with %USERPROFILE%

**Comment by ArtemGovorov** [comment]
@con-ssc Thanks for the suggestions, done.

**Comment by con-ssc** [comment]
Said that on the topic of wallaby, but I'll say it again, your responding times are way of the chart.

**Comment by DevBaZz** [comment]
I'm still having issue with the DOM 

![image](https://user-images.githubusercontent.com/67967265/167295802-03bf2c62-600e-4671-9c63-742c20682d6f.png)

**Comment by smcenlly** [comment]
@DevBaZz - could you please create a [new issue](https://github.com/wallabyjs/quokka/issues/new) and provide us with all of your code and Quokka configuration so we can try to understand why it's not working for you?

If you are not already aware, you will need to configure Quokka to emulate a browser environment (read more in [our docs](https://quokkajs.com/docs/configuration.html#jsdom)). Once you configure Quokka, it should work for you.
