### ISSUE TITLE
Quokka can't detect nuxt auto imports

### ISSUE THREAD

**Issue by antharuu** [wallabyjs/quokka#902]
### Issue description or question

Quokka can't detect nuxt auto imports

### Sample code

```javascript
const config = useRuntimeConfig()
```

### Quokka.js Console Output

```
useRuntimeConfig is not defined
```

### Code editor version

Webstorm 23.2.4

### OS name and version

Windows

**Comment by mburnell** [comment]
Quokka doesn't support this kind of automatically-imported function (though you may be able to import it manually). You can read more about how Quokka runs your code here: [https://quokkajs.com/docs/how-does-it-work.html](https://quokkajs.com/docs/how-does-it-work.html).
