### ISSUE TITLE
TypeError: Cannot set property navigator of #<Object> which has only a getter

### ISSUE THREAD

**Issue by baharalidurrani** [wallabyjs/quokka#903]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
console.log("hello");
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.ts' (node: v21.1.0, babel: v7.17.8, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​
 
TypeError: Cannot set property navigator of #<Object> which has only a getter 
    at Array.forEach (<anonymous>) 
```

### Code editor version

Visual Studio Code Version: 1.84.1 (Universal)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

### OS name and version

macOS Sonoma v14.1
OS: Darwin x64 23.1.0

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and the fix is published in v1.0.577.

**Comment by baharalidurrani** [comment]
@ArtemGovorov any idea when `v1.0.577` is going to be rolled out in public?
I'm still getting `v1.0.576` in my VS Code.

**Comment by ArtemGovorov** [comment]
It has been released, and the latest version is displayed correctly at [the marketplace page](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode). Try restarting your VS Code, it may help.
