### ISSUE TITLE
Feature Request: allow Quokka to run on a selected piece of JavaScript code (not the entire file)

### ISSUE THREAD

**Issue by koraysels** [wallabyjs/quokka#904]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Code editor version

Webstorm 

### OS name and version
OSX

## question? 

How to only execute  a highlghted/selected piece of javascript code. Without running the entire js file?

**Comment by smcenlly** [comment]
Quokka currently only allows you to run your entire file, but we're working on an exciting new feature that will change this.

I'll repurpose your question as a feature request.

**Comment by koraysels** [comment]
> Quokka currently only allows you to run your entire file, but we're working on an exciting new feature that will change this.
> 
> I'll repurpose your question as a feature request.

Nice! I teach computer science and this would be very handy while teaching.

**Comment by stychu** [comment]
Is this feature implemented already ? I would love to use snaps but my project is setup with esm and quokka seems not recognize import of packages at least It cant find the importing package from my file which is private package.

**Comment by smcenlly** [comment]
@stychu - yes - this is supported using Quokka Snaps. It should be working with ES modules (it is for us):

<img width="381" alt="image" src="https://github.com/user-attachments/assets/d48ff9ae-b695-4873-a705-5356b8876baa">

If it's not working for you, can you please create a new issue and provide a code sample so we can attempt to reproduce your problem?

**Comment by smcenlly** [comment]
Closing this feature request, supported using [Quokka Snaps](https://quokkajs.com/docs/#snaps) which was released November 2023.
