### ISSUE TITLE
I'm getting all the Quokka output even though I didn't ask for it. 

### ISSUE THREAD

**Issue by oohkumar123** [wallabyjs/quokka#909]
<img width="1338" alt="Screenshot 2023-11-17 at 7 15 09 AM" src="https://github.com/wallabyjs/quokka/assets/115493729/3b7d6ad1-d302-49a7-8eeb-7f2e4b857bec">
### Issue description or question

I'm getting all the Quokka debug code even though I didn't ask for it. How do I turn this off. This just started happening. It was working fine yesterday. 

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
It sounds like you have accidentally enabled the [Auto Log setting](https://quokkajs.com/docs/configuration.html#auto-log):

<img width="1012" alt="image" src="https://github.com/wallabyjs/quokka/assets/2074089/b6e73a48-abff-4f8a-9395-54727c0956b9">

Please check this setting, and if it's set, disable it. 

If you're still having problems, let us know.

**Comment by oohkumar123** [comment]
I don't have that setting in my vscode config. I paid for the pro version.

**Comment by oohkumar123** [comment]
ok I found the setting thanks.
