### ISSUE TITLE
TypeScript errors suddenly appearing in latest version, where the existing config has worked for months

### ISSUE THREAD

**Issue by lunelson** [wallabyjs/quokka#913]
### Issue description or question

Quokka no longer resolves typescript correctly, in a project which worked up to the end of last week. This is a minimal reproduction of at least one of the issues; I am also finding that tsconfig path resolution fails, but can't reproduce everything consistently

### Sample repository link

https://github.com/lunelson/quokka-issue-2023-11-22

### Quokka.js Console Output

```
⨯ Unable to compile TypeScript: 
error TS5070: Option '--resolveJsonModule' cannot be specified when 'moduleResolution' is set to 'classic'. 
 
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​cannot-import-json.quokka.ts:2:1​
```

### VSCode

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0

**Comment by smcenlly** [comment]
Thanks for reporting the issue. This has been fixed in the latest version of Quokka, `v1.0.590`.
