### ISSUE TITLE
Live Execution and Results is not work   .pnpm/scheduler@0.23.0/node_modules/scheduler

### ISSUE THREAD

**Issue by vaynevayne** [wallabyjs/quokka#914]
```jsx
 const { data: { rawColumns = undefined } = {} } = useMetaQuery()
rawColumns
```
<img width="1020" alt="image" src="https://github.com/wallabyjs/quokka/assets/124666577/a0d78645-1830-4e66-ab28-2d1c4ffc8389">

**Comment by smcenlly** [comment]
Closing as a duplicate of #915. The file and error report are the same.
