### ISSUE TITLE
when i use it's always ask for use pro

### ISSUE THREAD

**Issue by marisamie** [wallabyjs/quokka#916]
### Issue description or question

when i use it's always ask for use pro

### Sample code

i use in normally JS code but can't do it

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code 

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Can you please share a screenshot of the issue?

**Comment by marisamie** [comment]
￼
￼

**Comment by ArtemGovorov** [comment]
@marisamie Unfortunately your screenshots have not been attached, can you please attach them again?

**Comment by marisamie** [comment]
เมื่อ ส. 25 พ.ย. 2566 เวลา 07:25 Artem Govorov ***@***.***>
เขียนว่า:

**Comment by ArtemGovorov** [comment]
@marisamie The screenshots still have not been attached. Please try attaching via opening the GitHub issue in your browser.

**Comment by marisamie** [comment]
sorry i sent it to email I dont know it can send on this too 
so sorry

**Comment by marisamie** [comment]
![Uploading ภาพถ่ายหน้าจอ 2566-11-24 เวลา 18.48.59.png…]()

**Comment by marisamie** [comment]
![ภาพถ่ายหน้าจอ 2566-11-24 เวลา 18 48 59](https://github.com/wallabyjs/quokka/assets/134767377/f031ea8c-f037-423b-aa28-b31729aa4d73)
![ภาพถ่ายหน้าจอ 2566-11-24 เวลา 18 48 48 (2)](https://github.com/wallabyjs/quokka/assets/134767377/61a564b4-4e8c-4405-bd1b-db66969cf52e)

**Comment by marisamie** [comment]
![ภาพถ่ายหน้าจอ 2566-11-24 เวลา 18 48 48](https://github.com/wallabyjs/quokka/assets/134767377/ff58296f-6c10-43f2-9366-093ee74fee92)
![ภาพถ่ายหน้าจอ 2566-11-24 เวลา 18 48 59](https://github.com/wallabyjs/quokka/assets/134767377/2dcc5786-3aed-4099-946e-48068bae171a)

**Comment by ArtemGovorov** [comment]
Thanks. From the error it looks like you are trying to use [Pro version of Quokka](https://quokkajs.com/pro/), but have not activated it. 

If you would like to keep using Quokka Pro version, please activate it by running the `Quokka.js: Open Start View` command in VS Code and then opening the `License` menu on the left.

If you would like to use Community features only, you may run the `Quokka.js: Switch to 'Community' Edition` command in VS Code.

**Comment by marisamie** [comment]
sorry can I ask some more question how I can run it on Vs code ? i have try on terminal but can't do  please give me suggestion to do it

**Comment by marisamie** [comment]
sorry again I can do it already thanks for you help

**Comment by kaij6** [comment]
> sorry again I can do it already thanks for you help

Hi! I was wondering where did you type in the Quokka.js: Switch to 'Community' Edition command in VScode? I have the same issue.

**Comment by smcenlly** [comment]
@kaij6 - please see above: https://github.com/wallabyjs/quokka/issues/916#issuecomment-1826195726
