### ISSUE TITLE
Unknown compiler option 'jsxImportSource'

### ISSUE THREAD

**Issue by samdvlpr** [wallabyjs/quokka#917]
### Issue description or question

I have recently purchased Quokka, and I am looking to work on a legacy project, but when I attempt to use Quokka on any ts file, I get the following console output. 

### Quokka.js Console Output

``` console

​​​​​Quokka PRO 'Untitled-1.ts' (node: v10.16.2, TypeScript: v3.9.9)​​​​
 
TSError: ⨯ Unable to compile TypeScript: 
error TS5023: Unknown compiler option 'jsxImportSource'.

``` 

### Code editor version

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and Quokka v1.0.594+ should work with older versions of TypeScript.
