### ISSUE TITLE
Could you please reduce the release frequency?

### ISSUE THREAD

**Issue by wenfangdu** [wallabyjs/quokka#918]
Currently, quokka releases way too often (almost two releases a day), I have to restart VSCode every few hours to apply the changes:
![image](https://github.com/wallabyjs/quokka/assets/28700378/699a866e-5280-476c-9ddf-8de2586869db)
I admire your hard work, but please reduce the release frequency, it's becoming distractive.

**Comment by smcenlly** [comment]
Thanks for reading out to us, and for using Quokka. We apologise for the frustration.

The spike in November releases (multiple times a day) is a result of essential updates following our major new [Snaps feature](https://quokkajs.com/whatsnew/snaps.html) release, and other work that has been necessary to support the latest version of node and other frameworks.

On average, we aim for a balanced release frequency and we will further review our processes to better align with user expectations (less frequent updates). To avoid disruption, you may like to consider disabling the VS Code `extensions.autoCheckUpdates` setting and perform this periodically (manually) when you want to restart VS Code to apply updates. It's also worth noting that when an update is available, you don't need to restart your editor to apply the update unless you want access to the latest version (VS Code will keep using the older version of the extension until the next time you restart).

You may also find it annoying that the VS Code extensions icon displays pending updates and would like to keep Extension auto-updates;  another option you may consider is to hide the extensions icon from your side-bar. You can launch the Extensions UI at any time with the `Extensions: Focus on Extensions View` command. By hiding the side-bar, VS Code will automatically update extensions when you next restart. Unless you're waiting on a specific feature / fix, you're unlikely to notice any issues by doing this.

**Comment by wenfangdu** [comment]
Here's the better way:
![image](https://github.com/wallabyjs/quokka/assets/28700378/dc01027e-fb16-444a-9074-4768b68e8918)

**Comment by smcenlly** [comment]
@wenfangdu - thank you! 🙏
