### ISSUE TITLE
add React native support please

### ISSUE THREAD

**Issue by garrettmac** [wallabyjs/quokka#923]
### Issue description or question

React Native started importing/exporting its package using [flow type syntax](https://github.com/facebook/react-native/blob/main/packages/react-native/index.js#L14) its causing Quokka/Wallaby to not know how to run RN files resulting in the following error 
<img width="905" alt="Screenshot 2023-12-18 at 9 46 32 AM" src="https://github.com/wallabyjs/quokka/assets/5916111/61b32747-7bc7-4229-816b-3e4171607a08">

Adding support for flow i think is all you need to add for React native to work again.

This is a good starting point.
https://flow.org/en/docs/react/
https://flow.org/en/docs/tools/babel/

**Comment by smcenlly** [comment]
I can see from your Quokka output that you don't have Babel configured for your project.

I think that if you [configure Quokka to use babel](https://quokkajs.com/docs/configuration.html#babel) with the transformers mentioned in the flow docs, then Quokka should work for you.

**Comment by smcenlly** [comment]
Were you able to try our suggestion? Updating your project to use babel should have fixed your problem.

**Comment by smcenlly** [comment]
I'm assuming that configuring babel solved your problem. If you're still having problems, please provide us with a sample repo and we will take a look at the babel configuration for you.
