### ISSUE TITLE
Quokka extension causes a deprecation warning in the console

### ISSUE THREAD

**Issue by lunelson** [wallabyjs/quokka#930]
Type: <b>Bug</b>

I used "extension bisect" and it identified quokka as the cause of this console error:

```sh
ERR [Extension Host] (node:6026) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
```

Extension version: 1.0.621
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:11.430Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 6, 5|
|Memory (System)|32.00GB (2.55GB free)|
|Process Argv|--crash-reporter-id 3eeb5f38-28fb-4ce7-b7cf-15288234da3e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30933248
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928

```

</details>

**Comment by mburnell** [comment]
Thanks for reporting this issue. We have identified and fixed a number of usages of the deprecated Buffer logic. However, our investigation has shown that the easiest-to-encounter instance of this issue triggered by Quokka is actually from calling into a Microsoft Live Share component. We're still investigating, but at this stage it doesn't look like there's anything we can do except report the problem to the appropriate team.

Could you please try (temporarily) disabling your Live Share extension and seeing if the problem goes away?

**Comment by lunelson** [comment]
Thanks @mburnell, yes I can confirm that after disabling Live Share this console error does not occur

**Comment by mburnell** [comment]
Thanks for the confirmation. I've dug a bit deeper and reported the issue at https://github.com/MicrosoftDocs/live-share/issues/5024.

**Comment by smcenlly** [comment]
Closing this issue as this is resolved from Quokka perspective.
