### ISSUE TITLE
Quokka panel does not open automatically

### ISSUE THREAD

**Issue by jimmyn** [wallabyjs/quokka#932]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

In Webstorm Quokka output tab does not open automatically when you run Quokka inside the file.

![2024-01-30 14 42 32](https://github.com/wallabyjs/quokka/assets/5391775/81ddb6a6-5ce8-4ee8-a7e2-7f1a542d88f4)

### Sample code

```javascript
console.log("TEST")
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
test.js (node: v16.20.0, TypeScript: v5.3.2 + swc, plugins: dotenv-quokka-plugin)

'TEST' at test.js:1:0
```

### Code editor version

Webstorm v2023.3.3

### OS name and version

OSX

**Comment by smcenlly** [comment]
Thanks for reporting the issue. It looks like some internals of the latest versions of JetBrains editors broke Quokka.

This is fixed in the latest version of Quokka for JetBrains editors, `v1.0.431`.
