### ISSUE TITLE
Any timeline for Zed Editor integration 

### ISSUE THREAD

**Issue by Oluwasetemi** [wallabyjs/quokka#938]
### Issue description or question

This is not a technical issue. Are there any plans to integrate with [Zed](https://zed.dev/) IDE.

**Comment by smcenlly** [comment]
Zed currently only supports language and theme extensions which is not enough to provide Quokka's functionality. Consequently, we do not have plans to integrate with Zed at this time. If/when their extension API changes, we will re-evaluate.

You can subscribe to [this Zed issue](https://github.com/zed-industries/zed/issues/5269) for updates.

**Comment by mykhailo-ivankiv** [comment]
Alternatively, you can use [Zed Repl](https://zed.dev/blog/repl#typescript); it is not as great as Quokka, but it shares some common principles.
