### ISSUE TITLE
Quokka + CCXT support

### ISSUE THREAD

**Issue by Dvisacker** [wallabyjs/quokka#939]
### Issue description or question

I am having an issue using the ccxt library with quokka. The script below correctly outputs the exchange object when run with node but returns an error (see screenshot) when run with quokka. 

How can i configure quokka to correctly import the ccxt library ?

### Sample code

```javascript
const ccxt = require('ccxt')
const exchange = new ccxt.coinbase()
console.log(exchange)
```

### Quokka.js Console Output

![Screenshot 2024-03-11 at 2 53 34 AM](https://github.com/wallabyjs/quokka/assets/11384092/8a040168-721d-4c31-b0de-c2824f81c748)

**Comment by smcenlly** [comment]
By default, Quokka uses [`standard-things/esm`](https://github.com/standard-things/esm) to support ESM from within commonjs files. The `ccxt` project is a little non-standard in its `package.json` configuration and is causing a problem when you load it with Quokka and are using commonjs.

You can fix this with a [`.quokka` configuration file](https://quokkajs.com/docs/configuration.html#quokka-file-config) in your project root to disable the use of esm.

```javascript
{
  "stdEsm": false
}
```

---

We are working on a fix for Quokka to accommodate the `package.json` exports style seen in `ccxt` that we expect to be available in the next day or so.

**Comment by Dvisacker** [comment]
Thank you @smcenlly, this worked great!
