### ISSUE TITLE
VSCode Ctrl + K + S save all keyboard shortcut cannot work after enabling Quokka 1.0.65

### ISSUE THREAD

**Issue by felixgogo** [wallabyjs/quokka#94]
### Issue description or question
VSCode [Ctrl+K S] save all keyboard shortcut cannot work after enabling Quokka 1.0.65
### Quokka.js file
The version shown on VSCode is 1.0.65.

### Sample repository link

*If the issue can not be reproduced just using the quokka file above (for example because it requires/imports some files from your project), please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.16.1

### OS name and version

Windows 10 Professional

**Comment by ArtemGovorov** [comment]
Thanks for the report. The shortcut to stop Quokka on Windows had been changed to `Ctrl + K, E`. The change is published in v1.0.66.
