### ISSUE TITLE
Add support browsersync or alive-server

### ISSUE THREAD

**Issue by uncol** [wallabyjs/quokka#940]
### Issue description or question

Today, Quokka supports `live-server`, which has not been updated for 2 years, it can instead support [`browsersync`](https://browsersync.io) or [`alive-server`](https://github.com/ljcp/alive-server) (fork live-server)

**Comment by smcenlly** [comment]
Quokka does not support `live-server`. I think you're confusing Quokka with our other product, [Console Ninja](https://console-ninja.com).

Console Ninja provides first class support for [this Live Server](https://github.com/ritwickdey/vscode-live-server), [`alive-server`](https://github.com/ljcp/alive-server) is not a fork of this project, it's a fork of [another project](https://github.com/tapio/live-server) named `live-server`. You *should* be able to use `live-server` and `alive-server` with Console Ninja's [Universal Node application support](https://github.com/wallabyjs/console-ninja?tab=readme-ov-file#universal-node-applications).

You can track Browsersync support via existing issues in the Console Ninja repository:
* https://github.com/wallabyjs/console-ninja/issues/55
* https://github.com/wallabyjs/console-ninja/issues/170
