### ISSUE TITLE
No output when hover fn or var but //? is working

### ISSUE THREAD

**Issue by HakYam** [wallabyjs/quokka#943]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
Quokka allows you to see runtime values with console.log, identifier expressions, live comments, and the Show Value command. In addition, Quokka can be configured to perform the Show Value command on selection ([see config docs here](https://quokkajs.com/docs/configuration.html#show-value-on-selection)).

Quokka will not show variables or function return values if you have not used one of the methods specified above.

If you believe Quokka is not working as described above, can you please provide your code sample, a screenshot of your Quokka output, and detail the exact steps you are taking?

**Comment by smcenlly** [comment]
I'm assuming our response helped you solve your issue. If not and you're still having problems, please reply to this issue and we will re-open it.
