### ISSUE TITLE
Quokka Stops Working Upon Saving File

### ISSUE THREAD

**Issue by DmitriyMalayev** [wallabyjs/quokka#944]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code
let array = [1,2,3] 
https://www.loom.com/share/9d951738643e45809fe3c8b363d4eed9?sid=64a665ac-3fce-4758-9e21-4dd3bb2efb05 

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by mburnell** [comment]
Unfortunately, this is expected behaviour. Please see https://github.com/wallabyjs/quokka/issues/763 for details.
