### ISSUE TITLE
Toggle Shortcut

### ISSUE THREAD

**Issue by DmitriyMalayev** [wallabyjs/quokka#945]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

Code works fine
I'd like to know if it's possible to have one keyboard shortcut to Start Quokka Current File and Stop Quokka Current File 

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
Are you using VS Code? If so, you may use the `Quokka.js: Toggle (Start/Stop) on Current File`. To create a keybinding, use the VS Code command, `Preferences: Open Keyboard Shortcuts` and then set the shortcut for the toggle command.
