### ISSUE TITLE
TS Paths in monorepo

### ISSUE THREAD

**Issue by devastion** [wallabyjs/quokka#946]
### Issue description or question

Cannot resolve tsconfig paths in monorepo.

I have the following structure
```text
- tsconfig.base.json
- packages
- - package-a
- - - tsconfig.json (with paths)
- - - - src/index.ts (import from paths)
```

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

[https://github.com/devastion/eslint-config](https://github.com/devastion/eslint-config/tree/e932aedc3772ddb4969536e21fbd0c450ac74988)

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​Install "@plugins/javascript" package for the current quokka file​
​Install "@plugins/javascript" package into the project​
 
Cannot find package '@plugins/javascript' imported from /Users/<username>/.quokka/packages/eslint-plugins/src/index.js 
    at packageResolve (node:internal/modules/esm/resolve:854:9) 
    at moduleResolve (node:internal/modules/esm/resolve:927:18) 
    at defaultResolve (node:internal/modules/esm/resolve:1157:11) 
    at nextResolve (node:internal/modules/esm/hooks:866:28) 
    at async nextResolve (node:internal/modules/esm/hooks:866:22) 
    at async Hooks.resolve (node:internal/modules/esm/hooks:304:24) 
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18)
```

### Code editor version

Visual Studio Code v1.88.0

### OS name and version

MacOS Sonoma 14.4.1

**Comment by smcenlly** [comment]
Thanks for reporting your problem. We have found and fixed an issue that would cause Quokka to fail when using non-root baseUrl. This is fixed in Quokka for VS Code, `v1.0.635`.
