### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by devastion** [wallabyjs/quokka#948]
### Issue description or question

Importing directory,, doesn't catch `index.ts`. Example - we have
```
- src
- - a
- - - fn
- - - - fn.ts index.ts
- - b
- - - file.js > import fn from "@a/fn" 
```

`@a` is ts path alias.

### Quokka.js Console Output

```
Cannot find module '<rootDir>/src/a/fn' imported from <rootDir>/src/b/file.js 
  ​​​​​at ​​​​​​​​finalizeResolution​​​ ​/Users/<user>/.quokka/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:352​
  ​​​​​at ​​​​​​​​moduleResolve​​​ ​/Users/<user>/.quokka/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801​
  ​​​​​at ​​​​​​​​Object.defaultResolve​​​ ​/Users/<user>/.quokka/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912​
```

Code editor version
Visual Studio Code v1.88.1

OS name and version
MacOS Sonoma 14.4.1

**Comment by smcenlly** [comment]
We don't have enough detail to create a reproducible sample of your issue, but it sounds like your `tsconfig.json` needs some additional configuration.

You will need to explicitly add a path to resolve your `index.ts`. For example:

```diff
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@a/fn/*": ["./a/fn/*"],
+     "@a/fn": ["./a/fn/index"]
    }
  },
}
```

---

If that doesn't work for you, can you please provide us with a sample project?

**Comment by devastion** [comment]
Hi, @smcenlly! You can see example [here](https://github.com/devastion/eslint-config/blob/da0d2abc22211df68fc371ce7de548aaaf079981/packages/eslint-plugins/src/index.ts). I am importing from a directory too (relative path), but quokka doesn't pick up automatically index. It may be issue with ts-node or something else. I am not sure.

**Comment by smcenlly** [comment]
This is actually `node.js` expected behavior when you use ESM (i.e. `"type": "module"` in your `package.json`).

You will need to configure Quokka to run node with an option to allow importing directories with the `experimental-specifier-resolution` setting via [Quokka configuration](https://quokkajs.com/docs/configuration.html):

```json
{
  "env": {
     "params": {
        "runner": "--experimental-specifier-resolution=node"
     }
  }
}
```

**Comment by devastion** [comment]
Thanks! It resolved my problem.
