### ISSUE TITLE
Failed to run compilers on src/components/cardNodes/hooks/canvasNodeHistory/index.ts, Cannot find package '@vue/cli-plugin-babel' imported from <rootDir>\babel-virtual-resolve-base.js 

### ISSUE THREAD

**Issue by tanghaochen** [wallabyjs/quokka#950]
### Issue description or question
The official website claims that Quokka can be used to debug Vite + Vue 3 projects. However, when I run it, various errors occur, indicating missing packages. It's not straightforward to use. If the issues cannot be resolved remotely or otherwise, I would like to request a refund.

### Quokka.js Console Output
![image](https://github.com/wallabyjs/quokka/assets/49523305/6440b997-9fe1-4106-bafc-06025ea53cb4)
![image](https://github.com/wallabyjs/quokka/assets/49523305/9a6ccf32-31a6-438b-8289-bb88aa06d164)

```
​Quokka PRO 'index.ts' (node: v20.13.0, babel: v7.24.5, plugins: alias-quokka-plugin)​​​​
Failed to run compilers on src/components/cardNodes/hooks/canvasNodeHistory/index.ts, Cannot find package '@vue/cli-plugin-babel' imported from <rootDir>\babel-virtual-resolve-base.js 
```

### Code editor version
All the latest version

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Hi there, we have replied to your support email. Please respond and we'll take it from there.
