### ISSUE TITLE
Encoding-Errors in value explorer

### ISSUE THREAD

**Issue by eopo** [wallabyjs/quokka#953]
### Issue description or question
Is this issue related to Quokka not outputting the expected results of your code?: Yes
Logging a value with Umlauts does result in the expected output. However, copying them from the value explorer or using Cmd + X, K does not return the umlauts correctly.

### Sample code

```javascript
const umlautString = 'ÄÖÜäöü'; //?  'ÄÖÜäöü'
// Value obtained using value explorer or Cmd+x,k: √Ñ√ñ√ú√§√∂√º
```
### Quokka.js Console Output

```
​​​​​Quokka PRO 'Untitled-2.js' (node: v22.1.0)​​​​

'ÄÖÜäöü' ​​​​​at ​​​​​​quokka.js:1:1​

```

### Code editor version

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

### OS name and version
macOS Sonoma 14.4.1 (23E224)

**Comment by smcenlly** [comment]
Thanks for reporting the problem.

This is fixed in the latest version of Quokka for VS Code, `1.0.641`.
