### ISSUE TITLE
TypeError: value.replace is not a function 

### ISSUE THREAD

**Issue by smallmain** [wallabyjs/quokka#955]
![image](https://github.com/wallabyjs/quokka/assets/28684663/b2019be5-6447-4c8c-b46c-311c11f44bbb)

The typescript file reports an error directly, but the javascript file has no problem.

**Comment by smallmain** [comment]
maybe https://github.com/TypeStrong/ts-node/issues/2000 ?

**Comment by smcenlly** [comment]
Wallaby ships with the latest official version of `ts-node`, `v10.9.2`.

The last beta available for `ts-node` has support for multiple `extends` files, which I assume is the cause of your problem.

You should be able to fix this by installing the beta version for your project: `npm install ts-node@11.0.0-beta.1`.

It's possible that there are problems with the beta version; we haven't used or tested the beta version extensively but it appears to work. When this becomes official, we'll update Wallaby to use this version.
