### ISSUE TITLE
Can't click gutter to add breakpoint to line with coverage icon

### ISSUE THREAD

**Issue by RCVarley** [wallabyjs/quokka#960]
### Issue description or question

In vscode, the "coverage" icon prevents you from being able to add a breakpoint so you need to use a keyboard shortcut or right click the gutter and select "Add breakpoint".

Even if you already have a breakpoint on that file and the second gutter is showing, the hover feature only works on the main row (where the coverage icon lives). Note that you can select the second row that is used for breakpoints, but only on a row that doesn't have a coverage icon.

![image](https://github.com/user-attachments/assets/c846cf32-e926-4e80-8395-851ef7ac8b27)
_above: the gutter reacting to hovering so that you can click to add a breakpoint_

![image](https://github.com/user-attachments/assets/0e7afd02-d7f6-4647-819b-5a4bbd273827)
_above: gutter without breakpoint_

![image](https://github.com/user-attachments/assets/d7943202-7e7d-48ed-888c-a10d078cb49d)
_above: gutter with breakpoint_

![image](https://github.com/user-attachments/assets/06496a5a-7358-4864-968f-88ffde8639dd)
_above: the hover feature when you have a breakpoint gutter already_

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
N/A
```

### Sample repository link

N/A

### Quokka.js Console Output

```
N/A
```

### Code editor version

Visual Studio Code v1.91.1

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Thanks for taking the time to raise an issue.

Unfortunately this is a limitation within VS Code when gutter indicators are displayed. You can however use the keyboard shortcut to add a breakpoint or else right-click on the gutter and use the `Add Breakpoint` context menu item.
