### ISSUE TITLE
problema instalando Quokka en sublimeText

### ISSUE THREAD

**Issue by El-Fox-001** [wallabyjs/quokka#961]
### Issue description or question
se instala de forma correcta  y hace bien su trabajo, el problema que genera es la forma que da error :
Error trying to parse settings: Expected value in Packages\carpeta\archivo.tmTheme:1:1

el mensaje de error aparece constantemente, problema con los plugins packages Themes  descargados o Themes personales, genera una copia exacta del archivo con la diferencia de extesion la cual no termina en .tmThem  sino en .chback

he intentado eliminar el archivo pero aparece de nuevo y genera un cambio visual, queda todo blaco y sale el mensaje de error.
alguna solución?

### Code editor version
Sublime Text 4 : V4169

### OS name and version
Windows

---

### Translation:

It installs correctly and does its job well, the problem it generates is the way it gives an error:
Error trying to parse settings: Expected value in Packages\folder\file.tmTheme:1:1

The error message appears constantly, problem with the downloaded plugins packages Themes or personal Themes, it generates an exact copy of the file with the difference of extension which does not end in .tmThem but in .chback

I have tried to delete the file but it appears again and generates a visual change, everything remains white and the error message appears.
Any solution?

**Comment by smcenlly** [comment]
This issue is not related to Quokka.

We recommend contacting Sublime Text support: https://www.sublimetext.com/support.
