### ISSUE TITLE
Quokka not recognising inline ts target compilerOption

### ISSUE THREAD

**Issue by Naxos84** [wallabyjs/quokka#962]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

I'm expecting Quokka to throw an error in the following case.

### Sample code

```typescript
({
    ts: {
        compilerOptions: {
            target: "es5"
        }
    }
})

const arr:{state: string}[] = [{state: "error"}, {state: "ok"}, {state: "warning"}];

const a = arr.find(a =>  a.state === "ok");

console.log(a);
```

When compiling the same code (without the inline quokka configuration) with `tsc -t es5 myFile.ts` I receive an error.

```
test.ts:3:15 - error TS2550: Property 'find' does not exist on type '{ state: string; }[]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

3 const a = arr.find((a) => a.state === "ok");
                ~~~~


Found 1 error in test.ts:3
```

### Sample repository link
I don't have a sample repo because I'm just using it inline

### Quokka.js Console Output

```
{ state: 'ok' } ​​​​​at ​​​​​​​​a​​​ ​quokka.ts:13:1​
```

### Code editor version

Visual Studio Code v1.91.1

### OS name and version

Windows

### Installed Typescript version

5.4.5

**Comment by mburnell** [comment]
Thanks for reporting the issue.

The error you're getting from tsc is based on a type check (saying `find` will be absent in an es5 environment). Quokka doesn't perform type checking, only transpilation and execution, and so cannot provide this information / error. Please see https://github.com/wallabyjs/quokka/issues/604#issuecomment-808563037 for a discussion on why we don't perform type checking in Quokka.

**Comment by smcenlly** [comment]
We explicitly set `noEmitOnError: false` and intentionally do not report type errors from the TypeScript compiler.

From Microsoft docs:

> Do not emit compiler output files like JavaScript source code, source-maps or declarations if any errors were reported.
>
> This defaults to false, making it easier to work with TypeScript in a watch-like environment where you may want to see results of changes to your code in another environment before making sure all errors are resolved.

Quokka is exactly a `watch-like environment` which is why we use this setting.

Compilation errors (as you say, failing) is not the same thing as the file not being output. Unless you've overridden the `noEmitOnError` setting (or else you have a custom build process), you should find that even if `tsc` compilation reports an error, your file is still output (regardless of the error).
