### ISSUE TITLE
Quokka adding `+` and `\n` breaks to output.

### ISSUE THREAD

**Issue by loganpowell** [wallabyjs/quokka#963]
### Issue description or question
Is there a way to prevent quokka output from breaking on linebreaks?

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
console.log({ 
    operation: 'response_constructed',
    response: 'something\nwith\nline\breaks'
})
```

### Quokka.js Console Output

```javascript
{ 
    operation: 'response_constructed',
    response: 'something\n'
        + 'with\n'
        + 'line\n'
        + 'breaks'
}
```

### Code editor version

Visual Studio Code v1.92.1

### OS name and version

Apple M2 Pro
Sonoma 14.6.1

**Comment by ArtemGovorov** [comment]
Hello, 
the behaviour is expected. Node logging works the same way (after string reaches certain length, it may be shorter with Quokka). If you run the following code in your node app, or node REPL:
```
console.log({
          operation: 'response_constructed',
          response: 'something\nwith\nline\breakssomething\nwith\nline\breakssomething\nwith\nline\breakssomething',
        });
```

the output will be similar:

<img width="786" alt="Screenshot 2024-09-09 at 10 54 28 AM" src="https://github.com/user-attachments/assets/f6713c39-b7bc-475b-95a8-708e26634b6d">

**Comment by loganpowell** [comment]
I should have followed your issue instructions. I apologize. Thank you for your patience 🙏
