### ISSUE TITLE
SyntaxError: Invalid shorthand property initializer

### ISSUE THREAD

**Issue by j4k0xb** [wallabyjs/quokka#964]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

The code runs fine with node v20.10.0

### Sample code

```javascript
for (const { a = 1 } of [{}]) {
  console.log(a);
}
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
<rootDir>/quokka.js:6 
        a = 1 
        ^^^^^ 
 
SyntaxError: Invalid shorthand property initializer 
    at internalCompileFunction (node:internal/vm:77:18) 
    at Object.compileFunction (node:vm:342:10) 
    at Generator.next (<anonymous>) 
```

### Code editor version

Visual Studio Code v1.93.1

### OS name and version

Manjaro Linux

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in the latest version of Quokka for VS Code, `v1.0.651`.
