### ISSUE TITLE
Quokka stopped working

### ISSUE THREAD

**Issue by pahund** [wallabyjs/quokka#965]
### Issue description or question

After updating IntelliJ IDEA to the latest version recently, Quokka has stopped working altogether.

When I create a new scratch file, the Quokka tool window shows up briefly, then closes again.

When I open it manually, it just says "Create a new scratch file or open an existing file(…)", even though a scratch file is opened.

My Quokka Pro license recently expired, so I purchased a new license, hoping this would fix it, but the problem remains.

I couldn't find any place to insert my updated license key.

Uninstalling Quokka and installing again didn't help.

The [plugin page from JetBrains](https://plugins.jetbrains.com/plugin/9667-quokka) says "Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2.0.1)".

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
const a = "b";
a//?
```

### Quokka.js Console Output

(none)

### Code editor version

IntelliJ IDEA IntelliJ IDEA 2024.2.2 (Ultimate Edition)

### OS name and version

macOS Sonoma 14.6.1 (23G93)

**Comment by ArtemGovorov** [comment]
Hi, thanks for being our user.

> I couldn't find any place to insert my updated license key.

Please follow the instructions at https://quokkajs.com/docs/license.html?editor=jb#entering-license-details.

> Not compatible with the version of your running IDE (IntelliJ IDEA 2024.2.0.1)

It sounds like your currently installed version of Quokka is too old. After you update your license details, please install the latest Quokka version 1.0.455 from JetBrains marketplace.

**Comment by pahund** [comment]
Thanks Artem, I've successfully registered my new license, updated Quokka, everything is OK now 👍🏻
