### ISSUE TITLE
Support for NextJS/React 'server-only' package

### ISSUE THREAD

**Issue by webmonarch** [wallabyjs/quokka#967]
### Issue description or question

I am trying to use NextJS / React `server-only` package in a scratch file I am running in Quokka. I am getting a runtime error. 

I tried configuring node's `--conditions` flag to Quokka but it doesn't seem to be honored or impactful. Specifically, I need to pass `-C react-server` to someplace that impacts the node instance running my script.

More explanation here: https://github.com/webmonarch/quokka-support-server-only/blob/main/README.md#additional-info

Strictly speaking, I think Quokka is doing what is expected, but I am trying to figure out how to pass the node parameter that would be honored here (or other way to work around this)

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

`scratch.ts`

```javascript
import config from './lib/config'

console.log(config)
```

`./lib/config.ts`

```javascript
import 'server-only'

const config = {
    some: "config"
}
export default config
```

### Sample repository link

https://github.com/webmonarch/quokka-support-server-only

### Quokka.js Console Output

```
scratch.ts (node: v20.17.0, TypeScript: v5.6.2 + swc)

This module cannot be imported from a Client Component module. It should only be used from a Server Component.
	at ./lib/config.ts:11
	at Object.<anonymous> ./lib/config.ts:18
	at scratch.ts:1:0

undefined at config_1.default scratch.ts:3:0
```

### Code editor version

IntelliJ

### OS name and version

OSX

**Comment by smcenlly** [comment]
Thanks for the sample repo, we can see why this wasn't working for you.

By default, Quokka will use `commonjs` to run your project imports. This means that all of your imports turn into `require()` statements, which in your case is resulting in the import condition not being applied.

You can fix this one of two ways:

1. Update your `package.json` to specify to load using ESM with `"type": "module"`.
2. Update your `.quokka` configuration to tell Quokka to run using ESM:

```json
{
  "stdEsm": false,
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "-C react-server"
    }
  }
}
```

**Comment by webmonarch** [comment]
I really appreciate the help and you providing clear guidance. It's stuff like this that really makes me happy using and supporting your product. 

Thanks again!
