### ISSUE TITLE
‘PRO’ trial license email not being delivered

### ISSUE THREAD

**Issue by johnnydecimal** [wallabyjs/quokka#969]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

The email with a ‘PRO’ trial license is not arriving in my inbox. I have tried:

- Two separate addresses, on separate domains.
- Entering my address in VSCode and at https://quokkajs.com/pro/.
- Both report success.
- The email is not in spam.

### Code editor version

Version: 1.94.1 (Universal)
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

### OS name and version

OSX 14.7 (23H124)

**Comment by smcenlly** [comment]
Can you please email us: hello@wallabyjs.com?
