### ISSUE TITLE
Single license/bundle for Wallaby + Quokka 'Pro'?

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/quokka#97]
*Not technical issue*

First congratulations on releasing pro versions of quokka. 

As I am approaching date to renew wallaby.js, I am curious if there's single, combined license for wallaby.js and quokka pro both. Mostly it's for convenience purpose - as I write expense report, it'd better to file singly entry instead of each 😅 

Please consider this is personal opinion and feel freely discard if there isn't plan. Still appreciate for great product.

**Comment by ArtemGovorov** [comment]
Thank you!

There's no single license at the moment. However, I think it is a good idea and we may introduce Wallaby+Quokka Pro bundle in future.

Having said that, I'm happy to share that we have decided to offer our Wallaby.js users a discount on Quokka.js ‘Pro’ licenses. So please [contact us with your Wallaby order number, or Wallaby license key](mailto:hello@wallabyjs.com?subject=Quokka.js%20discount%20for%20Wallaby.js%20user) and we will arrange the discount for you.

**Comment by aryehof** [comment]
I'd like to see combined pricing as well. I think that Wallaby is expensive, and my suggestion is that Quokka Pro is free to purchases of Wallaby.

**Comment by FishOrBear** [comment]
Yes, I bought wallaby.js, the quokka function I just use to create new file.

Or I suggest merging the feature in wallaby.js

**Comment by jcyh0120** [comment]
@ArtemGovorov  I've bought the quokka pro license and found that my requirement is much more close to wallaby.js. Is there any discount for users like me, who bought quokka pro first? Though I may not use quokka heavily, I would like  to keep this tool. Both are great tools!

**Comment by ArtemGovorov** [comment]
@jcyh0120 Thanks for being our customer. Please send us an email to hello@wallabyjs.com with your Quokka order number.

**Comment by ArtemGovorov** [comment]
In case if you haven't yet seen it yet, we are now offering Wallaby+Quokka bundle https://wallabyjs.com/store/personal/.

**Comment by jbfretel** [comment]
d
