### ISSUE TITLE
Current line isn't highlighted when starting Time Machine

### ISSUE THREAD

**Issue by lukaszmn** [wallabyjs/quokka#973]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
const a = 1;
const b = 2;
console.log(a + b);
```

### Quokka.js Console Output

If I Start Time Machine With Auto Play, no lines are being highlighted as the code runs.

If I click the second line and Start Time Machine (with the debug icon), I see `Execution Progress: 66%` with a lot of buttons, but the current line in the code is not highlighted.

The videos on https://quokkajs.com/docs/index.html#debugger indicate that the line should be highlighted.

### Code editor version

Visual Studio Code v1.95.1

### OS name and version

Windows 11

**Comment by smcenlly** [comment]
We have been unable to reproduce your problem.

Could you please confirm that you are using the latest version of Quokka for VS Code, `v1.0.656`?

It's also possible that your problem is caused by another extension. Could you please try running the command, `Extensions: Disable All Installed Extensions for this Workspace` and then re-enable just Quokka to see if it works for you?

If it's still not working for you when using the latest version of Quokka with only the Quokka extension disabled, could you please run the `Developer: Toggle Developer Tools` command, and inspect the `Console` for errors?

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back. If you're still having the problem, can you please reply to our previous comment so we can assist?

**Comment by lukaszmn** [comment]
Hi, I'm sorry I missed notification.

So, I'm using this extension https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode, version v1.0.661.

I disabled all extensions, enabled Quokka and still see no highlight.

When I enabled the dev tools and started time machine, I saw the following errors:

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: CodeExpectedError: cannot open file:///c%3A/DATA/<REMOVED>/my-project/src/dict/Collection.ts. Detail: Unable to read file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts' (Error: Unable to resolve nonexistent file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts')
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378

console.ts:137 [Extension Host] stack trace: CodeExpectedError: cannot open file:///c%3A/DATA/<REMOVED>/my-project/src/dict/Collection.ts. Detail: Unable to read file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts' (Error: Unable to resolve nonexistent file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts')
    at OFe.$tryOpenDocument (vscode-file://vscode-app/c:/Users/lukas/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:615:8481)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378

log.ts:439   ERR cannot open file:///c%3A/DATA/<REMOVED>/my-project/src/dict/Collection.ts. Detail: Unable to read file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts' (Error: Unable to resolve nonexistent file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts'): CodeExpectedError: cannot open file:///c%3A/DATA/<REMOVED>/my-project/src/dict/Collection.ts. Detail: Unable to read file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts' (Error: Unable to resolve nonexistent file 'c:\DATA\<REMOVED>\my-project\src\dict\Collection.ts')
    at OFe.$tryOpenDocument (vscode-file://vscode-app/c:/Users/lukas/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:615:8481)
```

The path cannot be found because it is invalid. The correct path is:
`C:\DATA\<REMOVED>\my-project\web-api\src\dict\Collection.ts`

In VS Code I opened the folder `C:\DATA\<REMOVED>\my-project` and `web-api` is one of subprojects with its own `package.json` file.

Note that I can still step back/into, play in the time machine and see the output and progress changes.

**Comment by smcenlly** [comment]
Thanks for providing the additional details. We can see why it's not working for you and we are working on a fix.

We should have an updated version of Quokka for you in the next day or two that fixes the problem.

**Comment by smcenlly** [comment]
We've fixed the problem in the latest version of Quokka for VS Code, `v1.0.662`. Please update to this version, it should fix your issue.

**Comment by lukaszmn** [comment]
Thank you, I confirm it works now.
