### ISSUE TITLE
console.table outputs as string

### ISSUE THREAD

**Issue by bluenex** [wallabyjs/quokka#974]
### Issue description or question

When the output is wrapped in single quotes ('), all internal strings contain escape characters (\'). This differs from the behavior of `console.log`, where the output is not wrapped in single quotes, making it easier to read. The current formatting complicates readability, especially for more complex and larger tables.

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
// paste the code you are running here

const a = [{test: 'tester'}, {test: 'tester2'}]
console.table(a)
```
### Quokka.js Console Output

```
// paste your quokka console output here
'┌─────────┬───────────┐ 
│ (index) │ test      │ 
├─────────┼───────────┤ 
│ 0       │ \'tester\'  │ 
│ 1       │ \'tester2\' │ 
└─────────┴───────────┘' 

// expected output (node.js output)
┌─────────┬───────────┐
│ (index) │   test    │
├─────────┼───────────┤
│    0    │ 'tester'  │
│    1    │ 'tester2' │
└─────────┴───────────┘
```

### Code editor version

Visual Studio Code 1.95.1

### OS name and version

OSX 14.6.1

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue with `console.table` is fixed and the fix is published in v1.0.661 of Quokka extension.
