### ISSUE TITLE
`"quokka.showOutputOnStart": false` does not work with new UI

### ISSUE THREAD

**Issue by jakr-s** [wallabyjs/quokka#975]
### Issue description
 VSCode setting `"quokka.showOutputOnStart": false` does not work with new UI panel

new panel automatically opens on quokka start regardless of setting

### Code editor version

1.95.3

### OS name and version

OSX 15.1.1

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in Quokka for VS Code, `v1.0.667`.
