### ISSUE TITLE
Logs font size in new ui is too small

### ISSUE THREAD

**Issue by Akiyamka** [wallabyjs/quokka#976]
In the new interface, the font of the logs is very small, and I couldn't find any settings that would control this

How it looks in my vscode
![image](https://github.com/user-attachments/assets/7125f801-7073-4453-83fd-2dfc43d27bff)

How I looks at this moment
![image](https://github.com/user-attachments/assets/1760a547-c084-4d46-8a6d-64cc7a31031e)

**Comment by ArtemGovorov** [comment]
Hey, the Logs font size should be the same as in the rest of your VS Code panel (ie. Explorer, Problems view, etc.). Is the font of the Logs same as the font in you VS Code File Explorer side view, or is it also smaller?

**Comment by Akiyamka** [comment]
@ArtemGovorov terminal / output / debug tabs have much bigger font size, it's defined by `terminal.integrated.fontSize` vscode setting 
![image](https://github.com/user-attachments/assets/4f2077d6-85e9-4a1e-8ff0-ea64262879eb)
![image](https://github.com/user-attachments/assets/ccd4e56f-4eb7-4218-80a8-c23c8f2c89f6)

the size of quokka logs is close to the labels in the interface (name of panels, labels in the status bar), 
However, it's important to note that
- they look a little larger because they are not monospaced and are often written in uppercase.
- they are not so important, and you don't usually need to read them, because they are usually static captions whose content is known.

![image](https://github.com/user-attachments/assets/05992704-08aa-4cc5-b8c6-c029047f14e0)

**Comment by smcenlly** [comment]
We've introduced a new VS Code setting to Quokka to allow you to customise the default font-size in the Quokka output window, `quokka.fontSize`:

<img width="506" alt="image" src="https://github.com/user-attachments/assets/34bf1158-b1b7-4852-b30a-3710d60e6ba6" />

This setting is available in Quokka for VS Code `v1.0.677+`.
