### ISSUE TITLE
Can not run quokka on .mjs files in webstorm (vscode works)

### ISSUE THREAD

**Issue by i-have-no-name** [wallabyjs/quokka#977]
### Issue description or question

Can not `Start Quokka` (do not have such buttons) in `.mjs` files in Webstrom. VSCode works fine. 

### .quokka

```json
{
  "autoDetect": false,
  "stdEsm": false,
  "nativeEsm": true,
  "babel": false
}
```

### Code editor version

Visual Studio Code v1.95.3
Webstorm 2024.3

### OS name and version
OSX

**Comment by mburnell** [comment]
Thank you for reporting this issue; it has been fixed in Quokka `1.0.461`.
