### ISSUE TITLE
Command 'Quokka.js: New File' resulted in an error command 'quokka.createFile' not found

### ISSUE THREAD

**Issue by brian-captain-crosby** [wallabyjs/quokka#978]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

I'm not able to start Quokka. The developer tools show error:

> Activating extension 'WallabyJs.quokka-vscode' failed: Cannot find module 'ts-node'
Require stack:
>- /Users/bcrosby/.vscode/extensions/wallabyjs.quokka-vscode-1.0.668/index.js
>- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js.
$onExtensionActivationError @ mainThreadExtensionService.ts:107
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378

I'm using nvm, here's my config:

```json
{
  "autoLog": true,
  "showSingleInlineValue": false,
  "pro": true,
  "node": "~/.nvm/current/bin/node"
}
```

node version is v20.15.1

I tried:

changing my node in the confib to /Users/bcrosby/.nvm/versions/node/v20.15.1/bin/node which is what I get when I run `which node` and restarted VS Code but it didn't help

I tried:

- closing VS Code
- deleting the extensions folder (rm -rf wallabyjs.quokka-vscode-1.0.668)
- re-opening VS Code

I've tried:

 installing `ts-node` globally `npm install -g ts-node`

but that didn't help.

Wallaby.JS is installed and working fine: 
> (Extension Host] [Wallaby Console] VS Code extension
v1.0.396|

### Code editor version

Visual Studio Code Version: 1.95.3 (Universal)

### OS name and version

OSX - 15.1 (24B83)

**Comment by ArtemGovorov** [comment]
Can you please open your VS Code settings JSON file and check that you don't have `quokka.debug` setting specified in there?

**Comment by brian-captain-crosby** [comment]
yay it works again 🎉. Thank you!! 🙇
