### ISSUE TITLE
Atom - new project - can not start node.js process

### ISSUE THREAD

**Issue by metasean** [wallabyjs/quokka#98]
### Issue description or question

For new Atom projects, either cloned or just created (e.g. from terminal, `mkdir bug-demo`, `atom bug-demo`, in Atom `⌘-n`, `⌘-k`, `q` _or_  `⌘-k`, `j`), spinning up Wallaby or Quokka results in the following error messages:
```
// Quokka error message
Can not start node.js process (node), make sure your system has node.js installed.

You may use the "node" setting to configure the location of node.
```

```
// Wallaby error message
Can not start node.js process (node), make sure your system has node.js installed.
```

Restarting Atom resolves this for the project.  (I'd call it a low priority bug because this is an easy fix.  But it's definitely still a nuisance.)

While this may be an Atom problem, the _only_ time I've ever seen these error messages are when I initially set-up Atom, I'm not seeing them under any other circumstances (i.e. no other packages are having a problem with node), and I'm not actually having to re-install node.

### Code editor version

Atom 1.20.1 x64

### OS name and version

OSX 10.12.3

(I was also really sad to get the Quokka pay for Professional features message.  And, no discount for Wallaby license holders?)

**Comment by ArtemGovorov** [comment]
Thanks for the report.
I can't yet reproduce it, could you please create a new project, start Quokka/Wallaby to get the error, open Atom Dev tools and see if there are any other errors reported there apart from this one?


> And, no discount for Wallaby license holders

After some internal discussions in our team, I'm happy to share that we have eventually decided to provide the discount for Wallaby license holders. I have already emailed you anyway.

**Comment by ArtemGovorov** [comment]
Also, when you open the dev tools right after the error (before restarting Atom), please try executing this in the dev tools Console:
```javascript
require('child_process').spawn("node").kill()
```
and let me know the result.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
