### ISSUE TITLE
Module not Found - Quokka not respecting paths and alias 

### ISSUE THREAD

**Issue by AXSJ** [wallabyjs/quokka#980]
Issue: Quokka Not Recognizing Aliased Paths in Monorepo Setup

## Description

I am experiencing an issue where Quokka is unable to resolve aliased paths in my TypeScript monorepo setup. Despite following various troubleshooting steps, the problem persists, and I am unable to import modules using the alias paths defined in my `tsconfig.json`.

```
Cannot find module '@/account/resources/schema'
Require stack:
- <rootDir>/quokka.js
```

## Environment

- **Quokka Version**: v1.0.671
- **IDE**: Cursor 0.43.5
- **Operating System**: MacOS Sonoma 
- **Node.js Version**: 18.20

## Project Setup

- **Monorepo Tool**: Yarn, nx
- **TypeScript Version**: 4.95

<img width="332" alt="image" src="https://github.com/user-attachments/assets/e5191b78-ccd0-44ff-b134-8da4b1be4440">

This is my `tsconfig.json`
``` json
{
"compilerOptions": {
"baseUrl": "./src",
"paths": {
"@dataloaders/": ["../dataloaders/"],
"@/": [""],
"@test/": ["../tests/"]
},
"module": "commonjs",
"target": "es6",
"moduleResolution": "node",
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
"strict": true,
"skipLibCheck": true
}
```

## Steps to Reproduce

1. Set up a monorepo using [Yarn Workspaces/Lerna].
2. Configure `tsconfig.json` with path aliases as shown above.
3. Attempt to run a Quokka file that imports a module using an alias path, e.g., `import { myModule } from '@/myModule'`.
4. Quokka throws an error: `Cannot find module '@/myModule'`.

## What I've Tried

1. **Installed `tsconfig-paths`**: Ensured `tsconfig-paths` is installed in the project.
2. **Quokka Configuration**: Added the following configuration to `.quokka`. I've tried a million different permutations of the following. Some configs i have tried a not included:

   ```json
   {
     "env": {
       "params": {
         "runner": "-r tsconfig-paths/register",
         "env": "NODE_PATH=./src"
       }
     }
   }
   ```

```json
{
  "ts": {
    "compilerOptions": {
      "baseUrl": "./src",
      "paths": {
        "@dataloaders/*": ["../dataloaders/*"],
        "@/*": ["*"],
        "@test/*": ["../__tests__/*"]
      }
    }
  },
  "env": {
    "params": {
      "runner": "-r tsconfig-paths/register"
    }
  }
}
   ```

   ``` json
  {
    "ts": {
        "compilerOptions": {
            "baseUrl": "./src",
            "rootDir": "./src",
            "moduleResolution": "node",
          "paths": {
            "@dataloaders/*": ["../dataloaders/*"],
            "@/*": ["*"],
            "@test/*": ["../__tests__/*"]
      }
    }
  },
  "env": {
    "params": {
      "env": "NODE_PATH=./src"
    }
  }
```

3. **Verified `tsconfig.json`**: Double-checked that `baseUrl` and `paths` are correctly set relative to the `tsconfig.json` file location.
4. **Checked Quokka File Location**: Ensured the Quokka file is within the scope of the `tsconfig.json`.
5. **Restarted Quokka and IDE**: Restarted both Quokka and my IDE after making configuration changes.
6. **Used Absolute Paths**: Attempted to set `NODE_PATH` to the `src` directory.
7. **Checked for Quokka Pro Features**: Verified that my Quokka version supports the required features.

## Expected Behavior

Quokka should resolve the aliased paths as defined in `tsconfig.json` and allow importing modules using these paths without errors.

## Actual Behavior

Quokka throws an error indicating that it cannot find the module specified by the alias path.

## Request for Assistance

I would appreciate any guidance or suggestions on how to resolve this issue. If there are any additional configurations or steps I might have missed, please let me know.

Thank you for your assistance!

---

**Note**: Please let me know if you need any further information or if there are specific logs or files I should provide.

**Comment by smcenlly** [comment]
We have created a working [sample](https://github.com/wallabyjs/quokka-980) for you based on the structure + `tsconfig.json` that you provided. You should be able to get this working by:

1. Cloning the repo
2. Running `npm run install` from the root of the repo
3. Starting Quokka on `./project/src/quokka.ts`

Unless we're missing something, the paths configuration didn't look correct (i.e. the TypeScript language service + `tsc` compiler were generating warnings / errors for us).

---

There's one slightly strange behavior (not Quokka logic, but instead `tsconfig-paths` logic). You have specified:

```
    "baseUrl": "./src",
```

With this setting in place, the path mapping is only attempted for files that exist under you `baseUrl`. This means if you put your `quokka.ts` file in your project root, then it won't work.

---

Hope that helps. If you have other questions / problems, please let us know. Maybe fork the sample repo and update it with your scenario?

**Comment by smcenlly** [comment]
Assuming our responses helped you work this out. If you're still having problems, please let us know and we can reopen the issue.

**Comment by AXSJ** [comment]
Hi @smcenlly Thank you for the response! Moving Quokka to src did fix the issue for files in the project directory but for the tests directory seems I'm getting

```
Cannot find module '@test/lib/helpers/account-helper'
Require stack:
- <rootDir>/src/quokka.js
```

**Comment by smcenlly** [comment]
Do you get the same problem with the sample repo we provided by mimicking the same structure you have in your project?

**Comment by AXSJ** [comment]
Yes it seems to also occur on the sample repo 
<img width="1611" alt="image" src="https://github.com/user-attachments/assets/30027c66-9c2d-4723-ab84-b92a75fc5134">

**Comment by smcenlly** [comment]
Thanks - we can see what you're doing now. This is the same problem that you experienced previously. The `test/sample.ts` file is outside of your `tsconfig.json` `baseUrl` and so it's not working for you.

As a quick fix, you should be able to get this working by modifying your `tsconfig.json`:

**tsconfig.json**
```json
{
  "compilerOptions": {
...
    "baseUrl": ".",
    "paths": {
      "@dataloaders/*": ["src/../dataloaders/*"],
      "@/*": ["src/*"],
      "@test/*": ["src/../test/*"]
    },
...
  }
}
```

Note that we changed the `baseUrl` to `"."`, and then we prefixed each of the paths with `src/`.

---

As I mentioned previously, this behavior is specific to the module loader that Quokka uses internally (`tsconfig-paths`). 

While the suggestion above will work for you, we are also working on a enhancing Quokka to automatically rewrite the `baseUrl` and prefix your `paths` when the `baseUrl` is not the same as your Quokka root. This will also fix the issue for you in the future without you needing to modify your `tsconfig.json`.

**Comment by smcenlly** [comment]
We have released a new version of Quokka that will automatically update your `tsconfig.json` paths when running in Quokka as we described in our previous comment. This means that Quokka should now work in both your original scenario and the latest scenario where it failed.

Please update to Quokka for VS Code `v1.0.674`, it should now work with your original configuration.

**Comment by AXSJ** [comment]
Thank you very much! <3
