### ISSUE TITLE
Question: ignore path - run quokka automatically

### ISSUE THREAD

**Issue by joel3112** [wallabyjs/quokka#981]
### Issue description or question

Hi, I'm using the Quokka plugin in WebStorm  and I love it, plus other plugins that make my productivity easier.

When I create a new scratch file, Quokka runs automatically (the ToolWindow option is activated), and this is fine with me!

But I find it conflicts with another plugin I use [Code Note](https://plugins.jetbrains.com/plugin/17501-code-note--project-notes-visual-markdown-editor) (it helps me to create notes inside the IDE).
When I create/open a note in Typescript/JS (or referenced to a Typescript file), Quokka runs automatically, and I find **it inconvenient because I want to “just read the note”**

These “note files” **do not appear in the “Scratches and Consoles”** section, they are stored in the `notesbook` folder, at the same level of the `scratches` folder  _(/Users/X/Library/Application Support/JetBrains/WebStorm2024.3/notesbook)_.

Is there any way to define an ignored path that does not run Quokka automatically? or to disable it?

Thanks in advance.

### Sample behaviour

https://github.com/user-attachments/assets/2e2e7387-d3b2-42a0-afe3-04661f422736

### Code editor version

Webstorm v2024.3

### OS name and version

OSX

**Comment by smcenlly** [comment]
We don't have a setting to configure which directories to watch, but we **do** have a [setting to not start automatically on scratch files](https://quokkajs.com/docs/config/overview/?editor=jb#global-config-file):

> By default, when using a JetBrains editor, Quokka will automatically start on any JavaScript/TypeScript [scratch file](https://www.jetbrains.com/help/idea/scratches.html) when it is first opened. This behavior can be disabled by adding a [Global Quokka configuration](https://quokkajs.com/docs/config/overview/?editor=jb#global-config-file) setting `scratchAutoStart` with a value of `false`.
> ```
> {
>   "scratchAutoStart": false
> }
> ```
