### ISSUE TITLE
Broken "issue repository" link on https://quokkajs.com/docs/support/feedback/

### ISSUE THREAD

**Issue by dhull** [wallabyjs/quokka#984]
The page https://quokkajs.com/docs/support/feedback/ has an "issue repository" link near the top of the page which I assume should link to `https://github.com/wallabyjs/quokka/issues`, but which links to `https://quokkajs.com/docs/support/feedback/%7B%7B%20site.support%20%7D%7D` (`https://quokkajs.com/docs/support/feedback/{{ site.support }}`) instead.

**Comment by mburnell** [comment]
Thanks for reporting this - the link should now be fixed.
