### ISSUE TITLE
does not work,just  show that "Quokka.js 'Pro' requires activation. Please re-enter your email address to your Quokka.js 'Pro' manage license dialog."

### ISSUE THREAD

**Issue by faruk-alam** [wallabyjs/quokka#988]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes/No

### Sample code

```javascript
// paste the code you are running here
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?
Webstorm v?
Atom v1.?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Please send us an email to hello@wallabyjs.com from the email address that you are trying to activate and we will sort it out for you.
