### ISSUE TITLE
Trial Activated and Showing till Jan but Trial is over error after running quokka for js!

### ISSUE THREAD

**Issue by rahulmasal** [wallabyjs/quokka#989]
![trial_activated](https://github.com/user-attachments/assets/5e7aea71-4581-40a1-8a36-4dfaf97a35f2)
![trial_over](https://github.com/user-attachments/assets/5336a268-c81f-4203-9013-69bc2740a815)

PFA for ref and what is issue here?

**Comment by smcenlly** [comment]
The behavior that you're seeing indicates that you've already used a trial license using a different email address. Please email us and reference this issue for further assistance: hello@wallabyjs.com.
