### ISSUE TITLE
fetch is not defined - in quokka file

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/quokka#99]
Hi,

I just recently registered the PRO version and tried using fetch, webpack seems to work but in a quokka file it does not.

Any ideas?

### Sample code

```javascript
({
  babel: true
})

fetch('flowers.jpg').then(function(response) {
  return response.blob();
})```


I also have a .babelrc file like so

{
  "presets": ["es2015"]
}


### Quokka.js Console Output

```
Quokka #1 (node: v8.4.0, babel: v6.26.0)

fetch is not defined
	at quokka.es6:5:0
```

### Code editor version

Webstorm v2017.2.4?

### OS name and version

OSX

**Comment by appsolutegeek** [comment]
I presume this because the polyfill is missing? It appears that babel doesn't include this as a polyfill?

Anyone suggest if this is the case and which polyfill is recommended ?

**Comment by ArtemGovorov** [comment]
Quokka runs in node, and there's no such thing as global `fetch` in node. Babel doesn't include fetch polyfill. I have seen some users using [`node-fetch`](https://github.com/bitinn/node-fetch), this is the best option to try.

**Comment by appsolutegeek** [comment]
Thanks, yes, makes sense.

**Comment by ecurtis** [comment]
Is this still the best answer? Trying this out I find that it will parse in the IDE but error out in the browser

**Comment by ArtemGovorov** [comment]
@ecurtis Try some [other fetch polyfills for node](https://www.google.com.au/search?q=fetch+polyfill+node) to find one that better suits your purpose.

**Comment by micros123** [comment]
If your app is running in a browser, it does not make sense to include `node-fetch`, because you would be including backend code in your browser app. In that case the most common polyfill is https://github.com/github/fetch

**Comment by mchaov** [comment]
Doesn't work with fetch mock and jest as well. Jest tests using fetch-mock are passing, wallaby is throwing reference error for fetch not being defined.

**Comment by ArtemGovorov** [comment]
> Jest tests using fetch-mock are passing, wallaby is throwing reference error for fetch not being defined.

This is Quokka repo, not Wallaby one. Are you trying to use Wallaby or Quokka?

**Comment by mchaov** [comment]
> > Jest tests using fetch-mock are passing, wallaby is throwing reference error for fetch not being defined.
> 
> This is Quokka repo, not Wallaby one. Are you trying to use Wallaby or Quokka?

came here from Google :) wallaby is the one - moved question there, thanks!

**Comment by felikf** [comment]
See here https://quokkajs.com/docs/configuration.html#jsdom
